### ISSUE TITLE
Panel: lock widgets

### ISSUE THREAD

**Issue by goetzc** [lxde/lxqt#1000]
It would be useful to be able to lock the panel widgets in place, to avoid accidentally moving or deleting them.

**Comment by tsujan** [comment]
+1

**Comment by stefonarch** [comment]
+1

**Comment by palinek** [comment]
Have a look on lxde/lxqt-panel#315

**Comment by goetzc** [comment]
Nice!  
You can add the 0.11 milestone to this.

**Comment by pmattern** [comment]
@goetzc 
The purpose of the milestone label is getting an overview what should be done before some release can be made. So it doesn't make sense to add a milestone tag to changes which have already been applied.
