### ISSUE TITLE
Openbox default settings in LXQt

### ISSUE THREAD

**Issue by selairi** [lxde/lxqt#1002]
The standard path for openbox settings in LXQt is "~/.config/openbox/rc.xml". But openbox can be used as a desktop by itself (adding some tools). 

I think to use another path for Openbox like "~/.config/**lxqt**/openbox/rc.xml" it better for us, because we can change default behaviour of openbox.

Another option is to use "~/.config/openbox/lxqt-openbox-rc.xml" instead the default "~/.config/openbox/rc.xml".

**Comment by Vladimir-csp** [comment]
I wonder how openbox treats other configuration files (autostart, environment, menu.xml) when --config-file is used.

**Comment by pmattern** [comment]
@selairi 
Just to avoid confusion, the path in the first line of the first comment should be `~/.config/openbox/rc.xml`, shouldn't it?

**Comment by selairi** [comment]
> Just to avoid confusion, the path in the first line of the first comment should be ~/.config/openbox/rc.xml, shouldn't it?

Yes. The the default path is ~/.config/openbox/rc.xml.

> I  wonder how openbox treats other configuration files (autostart, environment, menu.xml) when --config-file is used.

"menu.xml" is defined by "rc.xml" (in menu section.). Regarding autostart and environment, I read from [Wiki of Openbox](http://openbox.org/wiki/Help:Autostart):

>  When you log in with the "Openbox" session type, or launch Openbox with the openbox-session command, the environment script will be executed to set up your environment, and the autostart script can launch any applications you want to run at startup.
> 
> When you run the openbox command on its own, the autostart scripts will not run

I have just opened `openbox_default_path` branch and I tested the changes. It works OK.

In `openbox_default_path` branch "~/.config/openbox/lxqt-openbox-rc.xml" is used. Maybe this path is better than "~/.config/lxqt/openbox/". Advanced users could change something in "~/.config/openbox/" and get crazy because their changes are not applied in LXQt.

**Comment by Vladimir-csp** [comment]
I assume, the main reason for separate config is keyboard shortcuts. Specifically, window management shortcuts.
What would the direction be? Would lxqt-config-globalkeyshortcuts get the ability to read/write openbox wm shortcuts, or would lxqt-globalkeysd get the ability to issue generic NetWM commands to compatible window managers?

**Comment by selairi** [comment]
> I assume, the main reason for separate config is keyboard shortcuts. 

Not only do we change key shortcuts, but we can also change mouse actions, for example, we can use mouse wheel to organize tile windows very fast. You can do it by adding the code below in `<context name="Titlebar">`:
```
<mousebind button="Up" action="Click">
        <action name="Unmaximize"/>
        <action name="Maximize">
          <direction>vertical</direction>
        </action>
        <action name="GrowToEdge">
          <direction>west</direction>
        </action>
      </mousebind>
      <mousebind button="Down" action="Click">
        <action name="Unmaximize"/>
        <action name="Maximize">
          <direction>vertical</direction>
        </action>
        <action name="GrowToEdge">
          <direction>east</direction>
        </action>
      </mousebind>
```

> What would the direction be? Would lxqt-config-globalkeyshortcuts get th...

Sorry, I don't know. Why do you need to know that? I guess what you want lxqt-globalkeysd to change window manager keyboard shortcuts.

**Comment by palinek** [comment]
> Another option is to use "~/.config/openbox/lxqt-openbox-rc.xml"

I would suggest just the $XDG_CONFIG_HOME/**openbox/lxqt-rc.xml**

Ad lxqt-session@dd53083f1205d6e858dd26f5b2dd53f0e96a9418: IMO we should get lxqt-session simple and the optional configuration file copying should be performed in the [startlxqt script](https://github.com/lxde/lxqt-common/blob/master/startlxqt.in)

**Comment by selairi** [comment]
> I would suggest just the $XDG_CONFIG_HOME/openbox/lxqt-rc.xml

OK

> Ad lxqt-session@dd53083: IMO we should get lxqt-session simple and the optional configuration file copying should be performed in the startlxqt script

Users can change the window manager in LXQt. startlxqt script can not read those changes. Maybe the missing lxqt-confupdate tool have to do that, [#993](https://github.com/lxde/lxqt/issues/993). lxqt-confupdate is called by lxqt-session. lxqt-session calls first lxqt-confupdate, then it runs the window manager.

Maybe the call to lxqt-confupdate must be moved from lxqt-session to startscript.

**Comment by palinek** [comment]
> > Ad lxqt-session@dd53083: IMO we should get lxqt-session simple and the optional configuration file copying should be performed in the startlxqt script
> Users can change the window manager in LXQt. startlxqt script can not read those changes.

Startlxqt doesn't need to know anything about the selected window manager. It just checks the existence of the $XDG_CONFIG_HOME/openbox/lxqt-rc.xml and optionaly copies the default configuration from /etc/... (or /usr/share/... whatever).

**Comment by selairi** [comment]
I have added new branches called  `openbox_default_path` in `lxqt-common` and in `lxqt-session`. 

I have just pushed the next changes to `openbox_default_path` branch:

- It uses `$XDG_CONFIG_HOME/openbox/lxqt-rc.xml`
- startlxqt copies the default configuration from `$XDG_CONFIG_DIRS`

I have changed in `lxqt-rc.xml` :

- I deleted keyboard shortcuts not related with window management. Then users can use lxqt-globalkeysd to register their shortcuts.
- Mouse wheel over titlebar puts tile window.

**Comment by selairi** [comment]
I have tested branches  `openbox_default_path` in lxqt-common and in lxqt-session. They works OK. I would like to merge it with `master` branch.

If everybody is agreed with this, I will do it in a few days. 

Merge will change Openbox default path from `$XDG_CONFIG_HOME/openbox/rc.xml` to `$XDG_CONFIG_HOME/openbox/lxqt-rc.xml`. 

If you want to keep your actual openbox settings, you should run:

`cp ~/.config/openbox/rc.xml  ~/.config/openbox/lxqt-rc.xml `

**Comment by pmattern** [comment]
Everything working as expected here. Seems GTM.

**Comment by selairi** [comment]
I have just merged `openbox_default_path` branch in `master` branch. 

It changes default `~/.config/openbox/rc.xml` by `~/.config/openbox/lxqt-rc.xml`.

If you want to keep your previous Openbox settings, you should run:

`cp ~/.config/openbox/rc.xml ~/.config/openbox/lxqt-rc.xml`

**Comment by tsujan** [comment]
> If you want to keep your previous Openbox settings,..

*All* users want to keep it. So, couldn't that be done automatically (I don't know how)? Or a warning message after running the new version for the first time? Or .... It's not a big deal but imagine how users will be confused!

**Comment by selairi** [comment]
>  Or a warning message after running the new version for the first time?

Added.

**Comment by RalfJung** [comment]
> So, couldn't that be done automatically (I don't know how)?

What about, check if `~/.config/openbox/rc.xml` exists and `/.config/openbox/lxqt-rc.xml` does not. If that's the case, copy the file.

> Or a warning message after running the new version for the first time?

From a usability standpoint, this is pretty horrible. At least please make sure that users of other DMs don't get a useless warning.

**Comment by pmattern** [comment]
Running lxde/lxqt-common@ac2d616 and lxde/lxqt-session@e5c94a8 I cannot see any warning here.
It doesn't matter whether `~/.config/openbox` isn't preexisting at all or is comprising a file `rc.xml` only or whether the session is started from a virtual terminal by `startx` or from a display manager (SDDM).
So is there something wrong or did I miss something?

Meanwhile I think it would be better if the paths of the template in $XDG_CONFIG_DIRS and production file in $XDG_CONFIG_HOME were consistent.
That is if user's LXQt configuration file is `$XDG_CONFIG_HOME/openbox/lxqt-rc.xml` then the template should be `$XDG_CONFIG_DIRS/openbox/lxqt-rc.xml`, not `$XDG_CONFIG_DIRS/lxqt/openbox/lxqt-rc.xml`.

@RalfJung 
>> Or a warning message after running the new version for the first time?

> From a usability standpoint, this is pretty horrible. At least please make sure that users of other DMs don't get a useless warning.

The warning is meant to be launched by `startlxqt`, see https://github.com/lxde/lxqt-common/commits/master. So users of other desktop environments will hardly ever see it.

@selairi 
Please let me ask you [once more](https://github.com/lxde/lxqt/issues/992#issuecomment-207422016) to handle the commits you want to merge by Pull Requests.
Both finding commits which belong to some issue and keeping track is much easier that way. More importantly it makes a lot of sense to discuss particular problems in general in issues but corresponding commits in PRs.

**Comment by palinek** [comment]
> Running lxde/lxqt-common@ac2d616 and lxde/lxqt-session@e5c94a8 I cannot see any warning here.

There is the `xmessage` used for showing the (GUI) message. I'm completely confused about such usage there because there is no window manager running at that time. Maybe I'm missing something, but who is responsible to show the window then?

**Comment by RalfJung** [comment]
> The warning is meant to be launched by startlxqt, see https://github.com/lxde/lxqt-common/commits/master. So users of other desktop environments will hardly ever see it.

Sorry, DM was the wrong term. Should be WM. I am not using openbox; it would be silly for me to see this warning.

**Comment by selairi** [comment]
> Both finding commits which belong to some issue and keeping track is much easier that way. More importantly it makes a lot of sense to discuss particular problems in general in issues but corresponding commits in PRs.

OK

> Meanwhile I think it would be better if the paths of the template in $XDG_CONFIG_DIRS and production file in $XDG_CONFIG_HOME were consistent.

I agree with you.

> I am not using openbox; it would be silly for me to see this warning.

Fisrt I thought that lxqt-session copied files. Take into account that whenever Openbox is used, lxqt-session will detect it. However, someone suggested that it is better to keep lxqt-session clean. Nowadays, startlxqt copies the default settings. As startlxqt is executed before the Window Manager, I wish I could find a simple command to detect the Window Manager from bash.

To my mind, the warning should be removed in the future. This warning is not for the new installs.

> There is the xmessage used for showing the (GUI) message. I'm completely confused about such usage there, because there is no window manager running at that time. Maybe I'm missing something, but who is responsible to show the window then?

Window Manager does a lot of things with the windows: decorating, moving, resizing, etc. The X11 server draws the window. You can open a qTerminal and run:

`killall openbox`

Openbox will die and you will not be able to move or resize your windows. Run `openbox` again and it will work OK.

**Comment by pmattern** [comment]
The warning didn't come up here as I was assuming binary `xmessage` is available in error. After installing the binary the message comes up as expected (besides @palinek's argument about the missing window manager seems plausible).

> I wish I could find a simple command to detect the Window Manager from bash

The window manager to be used is stated both in `$XDG_CONFIG_{DIRS,HOME}/lxqt/session.conf` so should be rather easy to detect. (Both files should be considered as downstream may want to fiddle with the defaults, the one in `$XDG_CONFIG_HOME` should take precedence.)

Tbh. I'm not that sure whether we need that warning message in the first place.
Regarding releases the change could and should be mentioned in the release notes of 0.11 which users can be expected to read. So what remains is VCS. But honestly folks using VCS code should be aware that changes like that may happen and be able to deal with them.
So no harm in dropping the message with regards to real productive usage of LXQt.

If we do decide to keep the message the formatting should be changed as `xmessage` doesn't allow for line breaks by default making the message look ugly and even impossible to read on screens with horizontal resolution roughly < 1280px.
So if at all I'd propose to invoke it like this
```
echo -e 'LXQt has changed the default path of the Openbox configuration file.\nIf you want to keep your previous Openbox settings, run\n
"cp ~/.config/openbox/rc.xml ~/.config/openbox/lxqt-rc.xml"' | xmessage -file - &
```

**Comment by Atalanttore** [comment]
Unfortunately, there is no shortcut or context menu to copy this command.

![xmessage_no_copy_shortcut_or_context_menu](https://cloud.githubusercontent.com/assets/628474/14741373/0e3266a0-0896-11e6-8846-a37d56caec81.png)

**Comment by pmattern** [comment]
@Atalanttore 
On Linux selecting the message by mouse allows for copying it easily to the [Primary Selection (PSE)](https://en.wikipedia.org/wiki/X_Window_selection#Selections) and pasting it into the shell of a terminal emulator by middle mouse click.
In addition the message will be temporary anyway so I think the lack of a copy button or the like does not really represent a problem.

**Comment by selairi** [comment]
> The window manager to be used is stated both in $XDG_CONFIG_{DIRS,HOME}/lxqt/session.conf so should be rather easy to detect.

Good idea. I have rewritten the script. Then, if the user is using Openbox, the script will show the warning.

The script to copy the default settings of openbox is:

```
# Copy default settings of openbox
if [ ! -e "$XDG_CONFIG_HOME"/openbox/lxqt-rc.xml ] ; then
    _LXQT_COPY_OPENBOX_DEFAULTS=no

    for conf in `echo $XDG_CONFIG_DIRS|sed 's/:/\n/g'` ; do
        if [ -e "$conf"/lxqt/session.conf ] ; then
            if grep -e 'window_manager=openbox' "$conf"/lxqt/session.conf ; then
                _LXQT_COPY_OPENBOX_DEFAULTS=yes
            else
                if grep -e 'window_manager=' "$conf"/lxqt/session.conf ; then
                    _LXQT_COPY_OPENBOX_DEFAULTS=no
                fi
            fi
        fi
    done

    if [ -e $XDG_CONFIG_HOME/lxqt/session.conf ] ; then
        if grep -e 'window_manager=openbox' $XDG_CONFIG_HOME/lxqt/session.conf ; then
            _LXQT_COPY_OPENBOX_DEFAULTS=yes
        else
            if grep -e 'window_manager=' $XDG_CONFIG_HOME/lxqt/session.conf ; then
                _LXQT_COPY_OPENBOX_DEFAULTS=no
            fi
        fi
        if [ "$_LXQT_COPY_OPENBOX_DEFAULTS" = "yes" ] ; then
            # LXQt is already installed and Openbox is the default window manager. Show the warning.
            echo 'LXQt has changed the default path of the Openbox configuration file.\nIf you want to keep your previous Openbox settings, run\n    "cp ~/.config/openbox/rc.xml ~/.config/openbox/lxqt-rc.xml"' | xmessage -file - &
        fi
    fi

    if [ "$_LXQT_COPY_OPENBOX_DEFAULTS" = "yes" ] ; then
        mkdir -p "$XDG_CONFIG_HOME"/openbox/
        for conf in `echo $XDG_CONFIG_DIRS|sed 's/:/\n/g'` ; do
            if [ -d "$conf"/lxqt/openbox/ ] ; then
                cp -v "$conf"/lxqt/openbox/* "$XDG_CONFIG_HOME"/openbox/
            fi
        done
    fi
fi
# END: Copy default settings of openbox
```

**Comment by pmattern** [comment]
In order to use `echo` to work around line break missing in `xmessage` the former has to be invoked with switch `-e`.

Wouldn't it eventually make sense to summarize the two `if` statements to display the message (`echo` / `xmessage`) and to create `~/.config/openbox/lxqt-rc.xml` in a single one?
Both actions will always be needed at the same time and spreading them over two `if` statements makes the script more difficult to read.

That aside the script is working as expected here.

Again, I'm still not sure whether the effort we're putting into this single warning is worth the pain. Maybe we'll be able to re-use what we're figuring out now, though.
