### ISSUE TITLE
Useless empty submenu in Application Menu

### ISSUE THREAD

**Issue by YamashitaRen** [lxde/lxqt#1005]
Some weeks ago, I decided to remove useless applications in my Application Menu.
In order to achieve that, I created "hidden" entries in ~/.local/share/applications.
Now, I haven't any application in "Autre" (french for "Other") but the now empty submenu is still there.
I think that it should be automatically removed.

http://pix.louiz.org/o/kgzCJ.png

**Comment by Esclapion** [comment]
Yes, I have the same problem. It's probably to bind with empty item in the menu.

For the moment, I hide "Autre" by putting in /usr/share/desktop-directories a file lxde-other.directory containing NoDisplay=true.

**Comment by pmattern** [comment]
Already discussed in #65.

**Comment by YamashitaRen** [comment]
Thanks for the workaround @Esclapion
