### ISSUE TITLE
[lxqt-panel] Style new mainmenu search elements

### ISSUE THREAD

**Issue by palinek** [lxde/lxqt#1006]
The search in mainmenu brings new elements which are not styled by themes right now.

@intialonso can you take it?

**Comment by intialonso** [comment]
Absolutely.
Im working on it.

**Comment by palinek** [comment]
> Im working on it.

Thanks.

**Comment by intialonso** [comment]
I did some experiments with our main theme (Frost) [today](https://github.com/lxde/lxqt-common/commit/754f6d99ba362e7c3d515fdb4c46392b34c4888e):

![search](https://cloud.githubusercontent.com/assets/7544231/14195749/784e9cfe-f782-11e5-877f-1f3b3a178de0.png)
![Uploading search-result1.png…]()
![search-result2](https://cloud.githubusercontent.com/assets/7544231/14195751/78558960-f782-11e5-850a-2086cb9cad15.png)

**Comment by palinek** [comment]
> Im having some troubles with the damn clearbutton, it doesnt take any style.

I had a look into the Qt sources and we probably can't do much with it, it overrides the `paintEvent()` with no styling possibility (note the `QPainter` instead of `QStyledPainter`):
```c++
void QLineEditIconButton::paintEvent(QPaintEvent *)
{
    QPainter painter(this);
    // Note isDown should really use the active state but in most styles
    // this has no proper feedback
    QIcon::Mode state = QIcon::Disabled;
    if (isEnabled())
        state = isDown() ? QIcon::Selected : QIcon::Normal;
    const QPixmap iconPixmap = icon().pixmap(QSize(IconButtonSize, IconButtonSize),
                                             state, QIcon::Off);
    QRect pixmapRect = QRect(QPoint(0, 0), iconPixmap.size() / iconPixmap.devicePixelRatio());
    pixmapRect.moveCenter(rect().center());
    painter.setOpacity(m_opacity);
    painter.drawPixmap(pixmapRect, iconPixmap);
}
```

... also positioning of the icons inside `QLineEdit` is hardcoded:
```c++
void QLineEditPrivate::positionSideWidgets()
{   
    Q_Q(QLineEdit);
    if (hasSideWidgets()) {
        const QRect contentRect = q->rect();
        const QSize iconSize = QLineEditPrivate::iconSize();
        const int delta = QLineEditIconButton::IconMargin + iconSize.width();
        QRect widgetGeometry(QPoint(QLineEditIconButton::IconMargin, (contentRect.height() - iconSize.height()) / 2), iconSize);
        foreach (const SideWidgetEntry &e, leftSideWidgetList()) {
            e.widget->setGeometry(widgetGeometry);
            if (e.action->isVisible())
                widgetGeometry.moveLeft(widgetGeometry.left() + delta);
        }   
        widgetGeometry.moveLeft(contentRect.width() - iconSize.width() - QLineEditIconButton::IconMargin);
        foreach (const SideWidgetEntry &e, rightSideWidgetList()) {
            e.widget->setGeometry(widgetGeometry);
            if (e.action->isVisible())
                widgetGeometry.moveLeft(widgetGeometry.left() - delta);
        }   
    }
}
```

We can remove the clearbutton...

@tsujan you're the "styling guru", what do you think?

**Comment by tsujan** [comment]
> Im having some troubles with the damn clearbutton, it doesnt take any style.

Most theme engines rely on qcommonstyle for such icons. qcommonstyle first tries to find `edit-clear-locationbar-rtl` (or `edit-clear-locationbar-ltr` ro RTL) in the icon theme and if not found, it will use Qt's internal `cleartext-16.png`.

Margin setting and positioning should be done by the style engine. With some engines, they can be changed by the user *globally* but most engines have fixed values.

When you try to set such values with stylesheets, the result may seem OK with Fusion, for example, but usually it isn't so with other engines.

All in all, it's much better to leave the clear icon and its positioning to the icon theme + style engine, or you'll break some proportions.

@palinek  You and me have seen how hard it could be to set style-related values in the code ;)

**Comment by tsujan** [comment]
Let me be a little more specific:

When you set a style value in the code, you'll have to set all other *related* values too. Only if you do so, everything will be OK. For example, if you set the text color, you should set the background color, the selected bg color, and the selected text color too.

The problem is that, sometimes there are so many interrelated values. For example, lineedit is drawn partly in `qlineedit_p.cpp` but mostly by (a subclassed) qcommonstyle in `drawPrimitive(QStyle::PE_PanelLineEdit,option,painter,widget)` and `drawPrimitive(QStyle::PE_FrameLineEdit,option,painter,widget)`.

I don't want to discourage hard-coded styles (don't I?) but they should be done completely, and that may not worth the effort.

**Comment by intialonso** [comment]
Ok, so let the clear button alone. Is just the position what bothers me but is not that bad.

**Comment by tsujan** [comment]
Here, without any stylesheet, the search widget is so:

![2016-04-01-15 39 26-scrot](https://cloud.githubusercontent.com/assets/981076/14205534/24b36576-f821-11e5-8b96-6c2d4317bc05.png)

The left blue strip, the blue focus frame, frame widths, item heights, etc. are those of the globally used theme.

My point: there's a limit to making a specific menu stylish while, for example, Fusion is used. It's not your fault.

**Comment by intialonso** [comment]
Sadly, I have been too busy this year. I don't think I can finish this for
the release.

If anyone can take it, please do it.

El martes, 21 de junio de 2016, palinek <notifications@github.com> escribió:
> @intialonso are you still working on other themes?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/3GbN2dGFmLyL-na5dEl4RLAV1toR4xW0Xosn6oK8_Ad_1w3VTnlBWp-koTmqoNRDL8HIHksV8Oj7qC4K-1m7kLOe4nrU7pusC2onXlDumerulfurr1VbtQ0ilAV-0VmcxtrEzWDpzkrvTquNo7ciIUVocTeHKQ=s0-d-e1-ft#https://github.com/notifications/beacon/AHMdp9zJqIh_IKFphqqcoj2cBLZiG1peks5qN6zcgaJpZM4H8vXi.gif
>
