### ISSUE TITLE
Leave dialog no longer shown after update to Qt 5.6

### ISSUE THREAD

**Issue by City-busz** [lxde/lxqt#1008]
After updated my system to Qt 5.6, the leave dialog no longer shown. When I run 'lxqt-leave' without any option, nothing happens. However, it still works when I specify an option (e.g. --logout).

Package versions:
- qt5-base 5.6.0
- lxqt-session 0.10.0

Distribution: Arch Linux

**Comment by tsujan** [comment]
Are you sure that all LXQT components are *recompiled* against Qt 5.6?

**Comment by City-busz** [comment]
I'm using the packages from the official repositories, which are not recompiled. But the existing packages should work after minor Qt version updates.

**Comment by tsujan** [comment]
> But the existing packages should work after minor Qt version updates.

Not always. Sometimes there are backward incompatible changes. The question remains whether some code should be changed or a recompilation should be done for Qt 5.6.

**Comment by pmattern** [comment]
Confirmed, basically as described above.
After recompiling this morning's VCS checkouts of LXQt on up to date Arch Linux the GUI of `lxqt-leave` (so no additional arguments) doesn't come up any longer.

This problem used to affect invocations like `lxqt-leave --foobar` as well. Discussing this issue on freenode #lxde (2016-03-28 15:24 UTC in case anybody has logs) resulted in lxde/lxqt-session#65. But this commit doesn't seem to consider the invocation without arguments which hence is a kind of remnant.
But there's another problem: Once `lxqt-leave` was launched and failed invocations with arguments like `lxqt-leave --foobar` start failing, too, if invoked from panels main menu, but not if launched from `lxqt-runner`

**Comment by luis-pereira** [comment]
@City-busz Fixed in master. Try it.

**Comment by pmattern** [comment]
Ups, I was erroneously assuming I'd still be running branch `fix-leave-dialog` when posting my previous comment.
Everything alright here again as of lxde/lxqt-session@3acb9fe.
