### ISSUE TITLE
startlxqt: strange XDG_DATA_DIRS assignment

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#1010]
I'm not sure that assigning `XDG_DATA_DIRS="$XDG_DATA_HOME:/usr/local/share:/usr/share"` is valid. It should not contain $XDG_DATA_HOME. 
Was it done on purpose? There is no mention of such construct in the spec https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by pmattern** [comment]
This seems a bit odd, indeed.
At least on Arch Linux, none of the other major desktop environments like KDE, LXDE or Xfce is behaving like this. Didn't check whether this is in accordance with the respective upstream but given it's Arch Linux chances are it is.

On a side-note none of those other desktop environments seems to set all four variables `XDG_{CONFIG,DATA}_{DIRS,HOME}` in the first place (which doesn't question that setting all of them like `startlxqt` does is the right thing to do, IMO).

**Comment by luis-pereira** [comment]
@Vladimir-csp It's valid. Maybe a little non orthodox.

@pmattern They set some of them. If a variable is not set, the app/library should use the default values. By assigning it we are being precautious.

After https://github.com/lxde/lxqt-qtplugin/issues/8 gets in we can drop it in `startlxqt`.
