### ISSUE TITLE
crash upon exit

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#1013]
Running latest VCS checkouts of all LXQt components on Arch Linux the panel reproducibly crashes upon exit.

Problem can be seen upon terminating LXQt sessions or when the panel gets stopped within a running session from `lxqt-config-session` or by invoking `kill -SIGTERM $(pidof lxqt-panel)`.
Traces can be found at https://gist.github.com/pmattern/fb312f97b0694a1e9cb0b1344514464f.

Notes:
Besides the findings are very similar this issue was considered technically different from the one discussed in #994, see last comments there.
Issue must not be confused with crashes that can be seen on systems using DRI driver swrast. Usage of glibc 2.*23* plus the swrast driver provided by Mesa 3D 11.1.2 is causing various crashes, among other of virtually all Qt 5 applications on exit, see e. g. https://bbs.archlinux.org/viewtopic.php?id=209466 (attributed to QEMU in error) or https://bugs.kde.org/show_bug.cgi?id=360433#c2. This is fixed in Mesa 3D 11.2.0.

**Comment by tsujan** [comment]
I confirm the existence of this crash on exiting, with LXQT compiled directly from the latest git sources against Qt 5.6 on Manjaro. The backtrace is the same:
````
QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () from /usr/lib/libQt5Core.so.5
````
There's no crash at all with Qt 5.5 on Debian.

**Comment by tsujan** [comment]
These crashes on exiting under Arch/Manjaro seem very suspicious. What I *can* see on Debian too is that if an app with systray icon is affected by https://bugreports.qt.io/browse/QTBUG-50829, not only it but also the panel crashes on logging out with the above-mentioned backtrace. However, the crash reported here happens *without* such apps too!

**Comment by pmattern** [comment]
Further testing strongly suggests the problem is caused by plugin-mount.

The crashes cannot be seen running plugins cpuload, desktopswitch, kbindicator, mainmenu, networkmonitor, quicklaunch, showdesktop, spacer, statusnotifier (hosting [LXQt ConnMan Applet](https://github.com/surlykke/lxqt-connman-applet)), taskbar, tray (hosting [XPad](https://launchpad.net/xpad)), volume and worldclock but can be seen when plugin-mount gets added.
When the panel gets launched from a terminal emulator there are lots of messages
```
QXcbConnection: XCB error: 8 (BadMatch), sequence: 3665, resource id: 16777231, major code: 130 (Unknown), minor code: 3
```
on the shell when plugin-mount gets added to the panel and upon hovering over its icon.
When plugin-quicklaunch hosting `lxqt-leave` is placed at the outer right of the panel and plugin-mount gets added and hence placed right of plugin-quicklaunch it sometimes doesn't display its genuine icon but the one of `lxqt-leave` located at its left. The plugin does start using its genuine icon the next time the panel gets launched onward.
When plugin-mount gets removed from a running panel instance a crash can still be seen upon terminating this instance. The crash doesn't get manifest any longer in another instance that's launched thereafter and doesn't host plugin-mount any more.

So eventually some incompatibility of plugin-mount with Qt 5.*6*?

**Comment by tsujan** [comment]
On an updated Manjaro with the latest LXQT components from GitHub, I can confirm @pmattern's finding: I removed the mount plugin from the panel, logged out and logged in, and *after that*, the panel never crashed on exiting.

**Comment by palinek** [comment]
@pmattern Can you try to crash the panel with libqt5dbus debug symbols (to get the missing pieces of stacktrace)?

**Comment by palinek** [comment]
Just tried some examples with the mount-plugin... and I'm able to reproduce a crash on debian unstable (Qt5.5.1) with following scenario:
- run panel (configuration with plugin-mount)
- remove plugin-mount
- add plugin-mount => crash

The crash happens on any access to `Solid::DeviceNotifier::instance()`:
```c++
Solid::DeviceNotifier *Solid::DeviceNotifier::instance()
{   
    return globalDeviceStorage->notifier();
}
```
The `globalDeviceStorage` is a static variable.... so I believe this is the "library unloading & dangling resources" problem -> as with the QStringLiteral -> https://bugreports.qt.io/browse/QTBUG-49061.
The "do not allow unload" patch (https://codereview.qt-project.org/#/c/140750/) was postponed to Qt5.7

Discussion and agreement on not unloading libraries is here -> http://lists.qt-project.org/pipermail/development/2015-November/023681.html ... after all I agree with it and think we should not unload plugins/libraries on widget removal:
```diff
diff --git a/panel/plugin.cpp b/panel/plugin.cpp
index 159020d..ab6b16a 100644
--- a/panel/plugin.cpp
+++ b/panel/plugin.cpp
@@ -165,11 +165,7 @@ Plugin::Plugin(const LXQt::PluginInfo &desktopFile, LXQt::Settings *settings, co
 Plugin::~Plugin()
 {
     delete mPlugin;
-    if (mPluginLoader)
-    {
-        mPluginLoader->unload();
-        delete mPluginLoader;
-    }
+    delete mPluginLoader;
 }
 
 void Plugin::setAlignment(Plugin::Alignment alignment)
```

With this patch my scenario is OK. Can you @pmattern, @tsujan check if this makes any difference with your scenario?

**Comment by tsujan** [comment]
@palinek
Yes, removal of `mPluginLoader->unload();` was the solution; no crash on exiting anymore.

**Comment by palinek** [comment]
fixed by lxde/lxqt-panel#321

**Comment by palinek** [comment]
@pmattern Please, open dedicated issue for the lxqt-leave vs. plugin-volume icon...

**Comment by tsujan** [comment]
After several reboots between Debian and Manjaro, `/var/lib/systemd/coredump` is empty in both after this little change. Manjaro's KDE suffers from a similar symptom though; they may have to make a similar change.

**Comment by pmattern** [comment]
The crashes cease as of lxde/lxqt-panel@d57a462 on my local Arch Linux systems, too. That error message `QXcbConnection: XCB error: 8 [...]` stated [above](https://github.com/lxde/lxqt/issues/1013#issuecomment-209591553) has gone as well.

@palinek 
Recompiling qtbase (<--> libQt5DBus.so) with debug symbols enabled isn't necessary any longer now, is it?
Cannot see plugin-mount using icons other than it's own any longer running lxde/lxqt-panel@d57a462 either. Maybe this was somehow related to the various crashes I ad provoked while testing. Will open another issue if I should run into this again.

**Comment by palinek** [comment]
> @palinek 
Recompiling qtbase (<--> libQt5DBus.so) with debug symbols enabled isn't necessary any longer now, is it?

Right.... if the crashes are gone, there is no need to take any further actions.

**Comment by pmattern** [comment]
Addendum: the problem affecting the icon of plugin-mount is something already discussed in #927.
