### ISSUE TITLE
[lxqt-panel] Removable Media: "Behavior when a device is connected" is ignored

### ISSUE THREAD

**Issue by RalfJung** [lxde/lxqt#1015]
## Steps to reproduce

1. Right-click the removable media panel icon, select "Configure Removable Media".
2. Set "When a device is connected" to "Do Nothing", and hit "Close"
3. Plug-in some removable media (in my case, an MTP device)

## Actual behavior

A new window appears, asking me what I want to do with the device.

## Expected behavior

I disabled reaction to new media. No such window should appear.

## Further information

I am using lxqt 0.10 as packaged for Debian testing.

**Comment by stefonarch** [comment]
This is kind of double-handled: you have also to configure behaviour in pcmanfm-qt settings -> volume. 

I agree that it would be better if there were   only configuration for the behaviour.

**Comment by RalfJung** [comment]
Ah, thanks for the pointer :)

**Comment by pmattern** [comment]
Eventually abandoning the parallel usage of two GUIs dealing with removable media is addressed in #124.
So can't this issue get closed then?

**Comment by RalfJung** [comment]
Yes, it can :)
