### ISSUE TITLE
[lxqt-config] How to change icon size ?

### ISSUE THREAD

**Issue by Esclapion** [lxde/lxqt#1016]
Probably not an issue, but i don't find how to change the icon size of the LXQt configuration center ?

**Comment by tsujan** [comment]
It's defined by the style engine you use (Fusion, Breeze, ...) and usually can't be changed.

One exception is Kvantum (Kvantum Manager → Configure Active theme → Sizes → Large icon) but then, the icon size of all icon views, the size of whose icons isn't set by their corresponding apps, will be changed.

**Comment by Esclapion** [comment]
All my icons are svg, by default of 512x512, no margin, so somewhere they are resized ?

![lj38x90](https://cloud.githubusercontent.com/assets/3512979/14541763/d0d20a78-028b-11e6-8803-a79ce723982a.png)

Look in this capture the difference between both power management icons.

**Comment by tsujan** [comment]
> All my icons are svg, by default of 512x512, no margin, so somewhere they are resized ?

Yes, by the style engine and according to where they're used (on a menu, icon view, button, header, etc.). Most style engines use 32-px icons for icons views.

**Comment by tsujan** [comment]
See http://doc.qt.io/qt-4.8/qstyle.html#PixelMetric-enum, for example, and search for `QStyle::PM_ListViewIconSize`

**Comment by Esclapion** [comment]
If i understand well, it's hard-coded by this primitive in lxqt-config, and we can do nothing else recompile it after changing this value ?

**Comment by tsujan** [comment]
lxqt-config uses `QApplication::style()->pixelMetric(QStyle::PM_IconViewIconSize)`, which is the standard size for that purpose. Some apps, like PCManFM, allow users to change those sizes because of the jobs they do but there's no reason for others, like lxqt-config, to have such a setting.

**Comment by Esclapion** [comment]
LXQt vs Xfce, same icons, same theme :+1: 

![lj38x90](https://cloud.githubusercontent.com/assets/3512979/14545174/3a30ff86-029d-11e6-9388-b8abc120ee27.png)

**Comment by tsujan** [comment]
> we have icons smaller than the labels.

Icon size can't be compared to label or file-name size because the latter may be short or long.

> LXQt vs Xfce, same icons, same theme

Xfce is based on GTK+, which chooses another default size. In the following screenshot, I've chosen 48-px with Kvantum Manager, which means that most icon views have 48-px icons, but I prefer 32 px myself.

![2016-04-15-02 34 51-scrot](https://cloud.githubusercontent.com/assets/981076/14545262/dc0db9a6-02b2-11e6-9033-dd9ff78c2cbf.png)

All in all, *the icon theme doesn't set the icon sizes,* neither in Qt nor in GTK+.

**Comment by Esclapion** [comment]
For the moment, I find those lxqt icons too small. I don't know how to use Kvantum, probably to study, but....
In you capture, it looks OK, not in mine.

**Comment by tsujan** [comment]
Oh, I almost forgot that I'd applied https://github.com/lxde/lxqt-config/pull/79, which isn't merged yet. Without it, lxqt-config's icons are always 32px in a fixed 100px grid.

**Comment by palinek** [comment]
Well... we can style the `lxqt-config` the same way as other lxqt apps -> `/usr/share/lxqt/themes/*/lxqt-config.qss`. The icon e.g.:
```css
QAbstractItemView {
  icon-size: 48px;
}
```

...but current implementation in master overrides such posibility, we should change it.

@tsujan getting the size here -> https://github.com/lxde/lxqt-config/pull/79/commits/1d05137bc7fa1fa8ebe09db40713d2d918db865a#diff-585cfecf0ce15ac75be3038e77e65611R263 should be changed to proprely query the icon size with considering also the stylesheets.

**Comment by tsujan** [comment]
> @tsujan getting the size ... should be changed to proprely query the icon size with considering also the stylesheets.

I agree.

**Comment by Vladimir-csp** [comment]
> Well... we can style the lxqt-config the same way as other lxqt apps

I would suggest that any LXQt apps should work properly even in case of absence of LXQt-specific styles (plain QT).

**Comment by palinek** [comment]
@tsujan @Esclapion I've jsut pushed lxde/lxqt-config@13e91e7 into  lxde/lxqt-config#79. With that the icon size can be configured by the "standard LXQt qss way".

**Comment by palinek** [comment]
> I would suggest that any LXQt apps should work properly even in case of absence of LXQt-specific styles (plain QT).

Don't they?

**Comment by Vladimir-csp** [comment]
They do. I meant, it is better not to introduce some hard('ish ) dependencies.

**Comment by tsujan** [comment]
> I would suggest that any LXQt apps should work properly even in case of absence of LXQt-specific styles (plain QT).

That's a necessity that should and *is* considered, AFAIK.

**Comment by palinek** [comment]
>  ...but current implementation in master overrides such posibility, we should change it.

@Esclapion there you go. Now the needed change is in master & you can freely configure the icon size by the .qss.

**Comment by tsujan** [comment]
Now that @Esclapion's question resulted in this feature, I propose `lxqt-config.qss` be added to the default theme with this in it:
````
QAbstractItemView {
  icon-size: 48px;
}
````
Or with 32px -- just to show what's possible to theme makers.

**Comment by Esclapion** [comment]
It would be nice for me. But where can i find this qss, who is not installed for the moment ? Sorry if this question is silly.

I try now kvdark.

**Comment by palinek** [comment]
> But where can i find this qss, who is not installed for the moment ? 

> ... we can style the lxqt-config the same way as other lxqt apps -> /usr/share/lxqt/themes/*/lxqt-config.qss ...

Currently there is no styling in any theme, so this file is not shipped within the [`lxqt-common` themes](https://github.com/lxde/lxqt-common/tree/master/themes)

**Comment by tsujan** [comment]
> But where can i find this qss

As @palinek said, nowhere, for now. Once you've installed the latest git lxqt-config, you could manually add it to the folder /usr/share/lxqt/themes/**YOUR_ACTIVE_THEME**.

**Comment by tsujan** [comment]
Or now, that you're trying kvdark (or any other Kvantum theme), you could change the size globally in Kvantum Manager → Configure Active theme → Sizes → Large icon and then save.

**Comment by Esclapion** [comment]
```
[pat@lq32 dark]$ pwd
/usr/share/lxqt/themes/dark
[pat@lq32 dark]$ cat lxqt-config.qss 
QAbstractItemView {
  icon-size: 48px;
}
```


changes nothing, also after reboot.

**Comment by tsujan** [comment]
> changes nothing, also after reboot.

If you compile and install *the latest* lxqt-config from GitHub, there will no need to reboot. The feature was merged just hours ago.

**Comment by Esclapion** [comment]
Better, yes :-)
![ess](https://cloud.githubusercontent.com/assets/3512979/14572516/870c91d2-034f-11e6-9c94-d080fa4e594d.png)

**Comment by tsujan** [comment]
> ...but the icons are very widely spaced.

Look at "Touches de raccourci" and "Monitor settings" in your screenshot! The horizontal space between them is small. The other items have the same spacing but narrower texts. Also the vertical space between "Touches ..." and "Manjaro ..." is small....

The spacing is uniformly based on 3 lines of text, each of which with ~16 chars. at most. Some languages may need that.

**Comment by Esclapion** [comment]
In the initial capture, monitor settings was on **2** lines. Else, I'm happy now, thanks ;)
