### ISSUE TITLE
libsysstat : Incoherence in CmakeLists.txt

### ISSUE THREAD

**Issue by paiiou** [lxde/lxqt#1019]
Lines 5-6-7 
set(MAJOR_VERSION 0)
set(MINOR_VERSION 3)
set(PATCH_VERSION 1)

Line 164
VERSION ${MAJOR}.${MINOR}.${PATCH}

**Comment by pmattern** [comment]
@paiiou 
This looks like a valid issue. But could you please kindly open it on the dedicated tracker of libsysstat at https://github.com/lxde/libsysstat/issues? See https://github.com/lxde/lxqt/blob/master/CONTRIBUTING.md.
