### ISSUE TITLE
[lxqt-panel] Desktop notifications only shown if more than 1 notification is activated

### ISSUE THREAD

**Issue by jajmo** [lxde/lxqt#1020]
For example, if I change my system volume, nothing is shown. But if I change my system volume and I get a chat notification, then they both pop up.

**Comment by ms6676749** [comment]
OS: Archlinux
Versions of lxqt-notificationd tested: 0.10 (arch's repo) and git commit gb01e752

I have a similar issue.  Notifications only show up when there's another OSD notification.  For example, Cantata's notifications won't display unless there's another notification already displayed; I use Configuration Center > Desktop Notifications > Basic Settings > Position on screen to draw the necessary notification  (tracked here (closed): https://github.com/CDrummond/cantata/issues/832).  Even $notify-send 'foo' isn't displayed unless there's another notification window presently displayed.

Other programs that use other notification daemons like konversation (using knotify) display OSD notifications just fine.

**Comment by stefonarch** [comment]
Similar issue here.
$notify-send test 
shows up again  when I change position from notifications settings but only  for some time, some notifications like the ones from  konversation (IRC) work sometimes but I think it's because they are often more than one only.

**Comment by YamashitaRen** [comment]
I was wondering if this is Qt5.6 related or if this is indeed a LxQt regression...
Had the bad idea to update the both together...
Though @ms6676749 comment led me to believe that the issue is indeed tied to the Qt update...

**Comment by tsujan** [comment]
I also see this issue on Manjaro, after updating it, but not on Debian, whose packages are older. Some update broke send-notify.

**Comment by agaida** [comment]
hmm - i'm on the last checkout  - and notify-send "some text" works as expected and pops up a notifications - so i would guess it's a Qt regression.

**Comment by tsujan** [comment]
> ... so i would guess it's a Qt regression

I can't see how. IMO, it may be related to another update in Arch/Manjaro. If you have siduction, there isn't a deep gap between it and Debian Testing+Unstable (my system), hence `notify-send` works in both.

**Comment by agaida** [comment]
the difference is that i use a lxqt that is 100% in sync with git aka daily checkouts

**Comment by tsujan** [comment]
@agaida
Mine is also up-to-date, both in Debian and in Manjaro. The Arch/Manjaro issue with `notify-send` occurs outside LXQt too.

**Comment by agaida** [comment]
The main difference is Qt 5.5.1 vs Qt 5.6 i guess

**Comment by manjarqo** [comment]
confirm this issue, Manjaro LXQT

**Comment by schijo** [comment]
I am not that convinced this being a Qt issue - my KDE install works find, only LXQt having this issue.
My observations:
Multiple messages (i.e. several msgs more or less at the same time) are always shown
Single message is shown only if this is the first msg, following (single) messages are no longer shown

**Comment by luis-pereira** [comment]
Update: After the update to Qt 5.6.1 on Arch it started working.
@tsujan @agaida Can you guys confirm ?

**Comment by YamashitaRen** [comment]
Here qt5 and kframeworks got updated together.
I can confirm that it's now working.

**Comment by tsujan** [comment]
@luis-pereira On Manjaro, it's still 5.6.0. Maybe next week. And in the case of Debian, I prefer to stick with Testing.

**Comment by stefonarch** [comment]
Confirm working now on arch too, I used dunst in the meantime.

**Comment by jajmo** [comment]
Looks good.
