### ISSUE TITLE
lxqt-common - startlxqt - XDG_CONFIG_DIRS - configuration - session can fail

### ISSUE THREAD

**Issue by thx1111** [lxde/lxqt#1022]
Arch Linux
lxqt-common 0.10.0-3

/usr/bin/startlxqt has:

if [ -z "$XDG_CONFIG_DIRS" ]; then
    export XDG_CONFIG_DIRS="/etc/xdg"
fi

When XDG_CONFIG_DIRS has been configured - or misconfigured - in the shell, in ~/.bash_profile for instance, then "/etc/xdg" may not be included in XDG_CONFIG_DIRS, with disastrous result.  When openbox is started, it will fail to find /etc/xdg/openbox/menu.xml, and pcmanfm-qt and the various lxqt utilities will not start, giving a mouse cursor and a black and unresponsive screen.  This kind of failure is not easy to diagnose, since the cause of the error is not written to standard error or standard out.

As an example, a seemingly innocent
export XDG_CONFIG_DIRS=$XDG_CONFIG_DIRS:/opt/trinity/etc/xdg/
in ~/.bash_profile will unwittingly disable any attempted lxqt session.

Too much is presumed when XDG_CONFIG_DIRS has been set.  There is no assurance that it has been set properly.  A much safer and more effective configuration would be to dispense with
 if [ -z "$XDG_CONFIG_DIRS" ] ... fi
altogether, and simply have, for instance:

export XDG_CONFIG_DIRS="/etc/xdg:$XDG_CONFIG_DIRS"

**Comment by palinek** [comment]
> export XDG_CONFIG_DIRS="/etc/xdg:$XDG_CONFIG_DIRS"

Such logic will override the preference, that the user wanted to explain be exporting the XDG_CONFIG_DIRS before `startlxqt` (spec: `$XDG_CONFIG_DIRS defines the preference-ordered set of base directories to search for configuration files in addition to the $XDG_CONFIG_HOME base directory.`)

IMO, this will be more appropriate:
```diff
diff --git a/startlxqt.in b/startlxqt.in
index e591172..17e2e86 100755
--- a/startlxqt.in
+++ b/startlxqt.in
@@ -28,6 +28,10 @@ export XDG_DATA_DIRS
 
 if [ -z "$XDG_CONFIG_DIRS" ]; then
     export XDG_CONFIG_DIRS="@LXQT_ETC_XDG_DIR@"
+else
+    if ! contains "$XDG_CONFIG_DIRS" '@LXQT_ETC_XDG_DIR@'; then
+        XDG_CONFIG_DIRS="$XDG_CONFIG_DIRS:@LXQT_ETC_XDG_DIR@"
+    fi
 fi
 
 if [ -z "$XDG_CACHE_HOME" ]; then
```

@luis-pereira what do you think?

**Comment by thx1111** [comment]
Sure, that's better.  Does ordering matter?  Since running `startlxqt` implies that an lxqt session is now desired, there could be:
    XDG_CONFIG_DIRS="@LXQT_ETC_XDG_DIR@:$XDG_CONFIG_DIRS"

If order does not matter, then it does not matter which way this is written.

There will still need to be an `export` attribute set:
    export XDG_CONFIG_DIRS="@LXQT_ETC_XDG_DIR@:$XDG_CONFIG_DIRS"
or
    export XDG_CONFIG_DIRS="$XDG_CONFIG_DIRS:@LXQT_ETC_XDG_DIR@"

**Comment by palinek** [comment]
> Does ordering matter?

As I've cited the spec before `$XDG_CONFIG_DIRS defines the preference-ordered set of base directories to search for configuration files in addition to the $XDG_CONFIG_HOME base directory.` => so yes, the ordering does matter.

> There will still need to be an `export` attribute set:

Nope, if the variable is set (exported) before the `startlxqt` runs, there is no need to put the export. You can try it yourself.

**Comment by luis-pereira** [comment]
@palinek That's perfectly acceptable.
@thx1111 Ordering does matter. Implementations must follow the ordering set.

**Comment by thx1111** [comment]
> if the variable is set (exported) before the startlxqt runs

Just supposing, while unlikely that XDG_CONFIG_DIRS would be set elsewhere *without* the export attribute, *if* the attribute were *not* set, then lxqt would fail.  It does no harm to set it twice, but lxqt fails if it is not set at all.  Good engineering is about handling fault conditions gracefully, not just about making stuff work under optimistic conditions.

**Comment by palinek** [comment]
startlxqt is a standalone script, which should (must) not be `source`d... therefore if the variable is already defined in the execution, it is gotten from the environment.

**Comment by thx1111** [comment]
Point taken.  Thanks for that.
