### ISSUE TITLE
Adding sensor widget makes crash panel 

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#1031]
Tested with clean account and latest checkout:
```
lxqt-panel
WinIdChange 1c00006 handle QWidgetWindow(0xee47d0, name="LXQtPanel panel1Window") QScreen(0xd69f90, name="DP1")
"Section \"sensors\" not found in /home/stef/.config/lxqt/panel.conf."
()
WinIdChange 1c0003e handle QWidgetWindow(0x1406fd0, name="LXQtPanel panel_{291d4b2b-4e59-4fe7-92a9-598d4048b46e}Window") QScreen(0xd69f90, name="DP1")
Systray started
Detected chip: "acpitz-virtual-0"
Detected feature: "temp1" ( "temp1" )
Detected feature: "temp2" ( "temp2" )
Detected chip: "coretemp-isa-0000"
Detected feature: "temp1" ( "Physical id 0" )
Detected feature: "temp2" ( "Core 0" )
Detected feature: "temp3" ( "Core 1" )
lm_sensors library initialized
Errore di segmentazione (core dump creato)
```
`

**Comment by pmattern** [comment]
Confirmed as depicted above running all LXQt components from latest VCS checkouts on Arch Linux x86_64.
Traces uploaded at https://gist.github.com/pmattern/18e332fe1bf6b74d62a7a2ec23858c45.

**Comment by paulolieuthier** [comment]
@stefonarch, @pmattern please test the PR.

**Comment by pmattern** [comment]
Cannot reproduce the crash any longer running lxde/lxqt-panel@0552574 ([rebased](https://github.com/pmattern/lxqt-panel/tree/fix-plugin-settings-rebased) against current master).

**Comment by stefonarch** [comment]
This issue looks solved, but adding sensors  I just reproduce still https://github.com/lxde/lxqt/issues/927#issuecomment-210497849 (it doubles always kbindicator, the last one on the panel)
