### ISSUE TITLE
Conflicting shortcuts for Showdesktop

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#1032]
On a clean user on first run one of the 4 messagges   says:

` Show Desktop: Global shortcut C+A+d+ cannot be  registered
`

It looks like this conflict is caused by the openbox lxqt-rc.xml file.
Removing 
```
 <keybind key="C-A-d">
    <action name="ToggleShowDesktop"/>
  </keybind>
```
from it solves here.
 I forgot to control but I think C-A-d is set by lxqt-globalshortcuts already.

**Comment by pmattern** [comment]
Both description of problem and proposed solution are accurate.
File `lxqt-rc.xml` that get's shipped [since recently](https://github.com/lxde/lxqt/issues/1002) is assigning shortcut `Ctrl+Alt+D` to minimizing all windows at the window manager level ("ToggleShowDesktop" in terms of Openbox actions), `lxqt-globalkeysd` wants to do the same and fails, hence the message. Also, dropping the three lines stated by @stefonarch fixes this problem.

But unfortunately this made me stumble upon another thing that should get addressed: file `lxqt-rc.xml` shipped right now is seriously outdated.
It's comprising lots of actions like `DesktopDown` which have been deprecated long ago and is pretty different from the default `rc.xml` of Openbox as shipped by Arch Linux, Debian testing, Fedora 23 and openSUSE right now which in turn are the same except some minor modifications in the one of Debian testing.
@selairi 
Any thoughts on this particular topic? Shouldn't we exchange `lxqt-rc.xml` with a modified copy of a more recent version like the one that comes with Openbox 3.6?
This issue would get solved that way, too, as more recent versions of upstream `rc.xml` don't assign action "ToggleShowDesktop" to `Ctrl+Alt+D` any longer but to `"Super Key"+D` only.

**Comment by palinek** [comment]
> @selairi 
Any thoughts on this particular topic? Shouldn't we exchange lxqt-rc.xml with a modified more recent rc.xml like the one that comes with Openbox 3.6?

Agreed.

**Comment by OhDaeto** [comment]
I think I found the reason! Now I deleted `~/.config/lxqt` together with `~/.config/openbox` and noticed that in `lxqt-rc.cml` file a copy is created. Can somehow cancel the creation of this action if the folder does not exist openbox?

**Comment by stefonarch** [comment]
I just created a commit to show the differences:
https://github.com/lxde/lxqt-common/compare/master...stefonarch:patch-3
I can't see any problems as @pmattern  states too.
Using arch's default openbox rc.xml would just be the solution for this small bug and we could close it.

**Comment by pmattern** [comment]
Fixed in lxde/lxqt-common#59.

**Comment by ZiTAL** [comment]
same for lxqt-runner: .config/openbox/lxqt-rc.xml

```
  <keybind key="A-F2">
      <action name="Execute">
<!--
          <command>lxpanelctl run</command>
-->
          <command>/usr/bin/lxqt-runner</command>
      </action>
  </keybind>
```

**Comment by wxl** [comment]
Though it may have had a closer relationship with Openbox in the past, LXQt is currently designed to be window manager agnostic. That said, I'm not even sure why we're shipping an Openbox configuration. The above mentions a deprecated repo but it seems to have moved to [lxqt-session](https://github.com/lxqt/lxqt-session/blob/master/config/openbox/lxqt-rc.xml).

**Comment by tsujan** [comment]
> I'm not even sure why we're shipping an Openbox configuration.

Good point. Maybe, it should be inside `obconf-qt`.

**Comment by wxl** [comment]
> Maybe, it should be inside obconf-qt.

That would be the best place if we are indeed going to ship a configuration.

However, is it presumptuous to imagine that any Openbox package should necessarily come with a default configuration?

**Comment by tsujan** [comment]
> However, is it presumptuous to imagine that any Openbox package should necessarily come with a default configuration?

I don't know. But I agree with you that it shouldn't be in lxqt-session. LXQt is WM-agnostic. I don't know if it will be so with Wayland too -- I really hope it will -- but, IMHO, we should try to keep it that way.

**Comment by devwillie** [comment]
Is this still an issue?  I receive the notification on startup.
Running Debian 10.3 with LXQt 0.14.1

**Comment by stefonarch** [comment]
It depends on the wm shortcuts, debian uses xfwm4 and did not remove cltr+alt+D.

**Comment by tsujan** [comment]
> It depends on the wm shortcuts

In other words, and for the reason [mentioned](https://github.com/lxqt/lxqt/issues/1032#issuecomment-599741571) by @wxl, this wasn't an LXQt issue in the first place — although shipping an openbox config is still a minor issue.

**Comment by devwillie** [comment]
I examined `.config/openbox/lxqt-rc.xml` in my home dir and didn't find any keybinding that uses `Ctrl + Alt + d` and ToggleShowDesktop was bound to `W-d` so I must have the new openbox config that was merged back in 2017.  I also remapped the `Show desktop` action to `Shift + Ctrl + Alt + D` in the Window Manager|Keyboard` util.  After re-booting, the `lxqt-panel` notification still complains about the duplicate binding!?   
NOTE: Both keybindings `Shift + Ctrl + Alt + D` & `Ctrl + Alt + D` show the desktop so are each bound successfully to ToggleShowDesktop. What am I missing here?  Where is the hidden `Ctrl + Alt + D`?

On a separate (probably unrelated but who knows) note, the `lxqt-runner` cited by ZiTAL above does not appear anywhere in my `/home/will/.config/openbox/lxqt-rc.xml`

**Comment by ZiTAL** [comment]
@devwillie I edited the XML and I commented the command part:
```
<!--
          <command>lxpanelctl run</command>
-->
```
and added next one:
```
<command>/usr/bin/lxqt-runner</command>
```
to add the ALT +F2 functionality

**Comment by devwillie** [comment]
> @devwillie I edited the XML and I commented the command part:
> 
> ```
> 
> ```
> 
> and added next one:
> 
> ```
> <command>/usr/bin/lxqt-runner</command>
> ```
> 
> to add the ALT +F2 command runner functionality

My Alt + F2 functionality works and I don't have either <command>lxpanelctl run</command> OR  <command>/usr/bin/lxqt-runner</command> in my `~/.config/openbox/lxqt-rc.xml`
The only incidence of `F2` in that file for me is:
`  <keybind key="W-F2">
    <action name="GoToDesktop"><to>2</to></action>
  </keybind>`

Could LXQt be sourcing these shortcut keys from elsewhere?

**Comment by ZiTAL** [comment]
@devwillie this is for change the desktop: "window key" + F2

Are you using openbox for windows manager?

```
zital@sony:~$ cat .config/lxqt/session.conf 
[General]
__userfile__=true
window_manager=openbox

[Environment]
BROWSER=firefox
GTK_CSD=0
GTK_OVERLAY_SCROLLING=0
TERM=qterminal
```

**Comment by devwillie** [comment]
> @devwillie this is for change the desktop: "window key" + F2
> 
> Are you using openbox for window manager?
> 
> ```
> zital@sony:~$ cat .config/lxqt/session.conf 
> [General]
> __userfile__=true
> window_manager=openbox
> 
> [Environment]
> BROWSER=firefox
> GTK_CSD=0
> GTK_OVERLAY_SCROLLING=0
> TERM=qterminal
> ```

Ah, I'm using `xfwm4` which explains the delta in behavior (I think)

**Comment by ZiTAL** [comment]
@devwillie yo need to check the xfwm4 (xfce's window manager) configuration

**Comment by john-clark** [comment]
4 years and still no fix for this?

**Comment by wxl** [comment]
@john-clark the problem was with the default configuration for shortcuts in LXQt and Openbox. LXQt used to ship an Openbox configuration, but being window manager agnostic, now does not, making the issue all but irrelevant.

However, four years ago, when filing the issue, the OP provided a solution, so you're a little behind.

Also, don't expect closed issues to be "fixed."

**Comment by john-clark** [comment]
That was rude. Closing the issue does not resolve the issue, nor does the
proposed “solution”.

As @devwillie wrote, there is no reference to C-A-d in any files.

The issue still exists and is not fixed and the reason it was still open.

**Comment by john-clark** [comment]
That was rude. Closing the issue does not resolve the issue. There is a reason why it was still open.

As @devwillie wrote, there is no reference to C-A-d in any files.

If there is a solution here please make sure that it actually resolves the issue. Because it is still a problem.

**Comment by stefonarch** [comment]
This was closed 4 years ago.
devwillie wrote:
> UPDATE: Strangely enough, this issue no longer presents! xsession-errors file no longer shows...

And to be on the safe side  I tested a new user with openbox , no  message about C-A-d with the default file shipped by openbox.

**Comment by tsujan** [comment]
In addition to what @stefonarch correctly said:

It's not LXQt's job to explain how openbox works or interferes with LXQt shortcuts. Openbox isn't an LXQt component. Read its documentation!

**Comment by pwright2b** [comment]
Ummm, I have a newly installed (5/13/2021) Debian with LXQT, updated and upgraded, and it gets this error.  I realize that Linux is a pretty free flowing community but SOMEBODY other than the unwary user ought to be responsible for correcting configuration errors.
