### ISSUE TITLE
Reduce default font size?

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#1035]
Actually not a big issue but every time I check first run I get impressed by the font in menu and notifying pop-ups. Installing in ubuntu 16.04 "preferences"  take half a notebook screen, it looks like that (click to enlarge):
![schermata07](https://cloud.githubusercontent.com/assets/10681413/14829530/391fff36-0bec-11e6-8e63-04583d0ed0b3.png)
Everytime my first action is to set it from 11px to 10px.

**Comment by Esclapion** [comment]
Here (desktop), i change from 11px to 12px.

**Comment by goetzc** [comment]
I also do enlarge the font size to 12px or 13px.

**Comment by agaida** [comment]
We should delegate such descisions to the distributions.
