### ISSUE TITLE
Problem of transparency with compton

### ISSUE THREAD

**Issue by manjaro-lxqt** [lxde/lxqt#1045]
(difficult to explain ;)
For example, I define no transparency for active windows, and 0.80 for inactive.

If I open 2 windows of different type : a pcmanfm-qt and a terminal window, it works well.

If I open 2 or more windows of the same type, for example 2 terminals, both have no transparency.

**Comment by tsujan** [comment]
AFAIK, transparency is managed only by Compton, not by LXQt. This may be a Compton issue or a problem Qt5 has with X11. Do you see the same pattern with non-Qt apps or Qt4 ones?

**Comment by manjaro-lxqt** [comment]
"Do you see the same pattern with non-Qt apps or Qt4 ones?"

I'm unsure of the question, but if I open two windows firefox-gtk2, same problem.

**Comment by tsujan** [comment]
> if I open two windows firefox-gtk2, same problem.

So, it should be a general Compton issue. You could report it at https://github.com/chjj/compton, especially if you see it under Openbox too.

**Comment by pmattern** [comment]
This is indeed a feature (bug?) of Compton. Several windows belonging to the same application instance like e. g. Firefox, a terminal emulator or whatever are always treated the same.
You may want to verify by using Xfwm4 which does make that differentiate between windows like that.
So given LXQt will always rely on third-party window managers there's nothing that can be done at our side. Maybe things will be different in Wayland, don't know.
