### ISSUE TITLE
[lxqt-session, lxqt-about] remove the system category from the desktop files

### ISSUE THREAD

**Issue by sixsixfive** [lxde/lxqt#1046]
The system category should be removed since it will create a mess inside the lxqt menu(double entries etc.)

eg: https://github.com/lxde/lxqt-session/blob/master/lxqt-leave/resources/lxqt-hibernate.desktop.in

    -Categories=System;X-Leave;
    +Categories=X-Leave;

double entries:

![untitled](https://cloud.githubusercontent.com/assets/3780774/15045228/cb42a7da-12d9-11e6-9a03-abe0c6b8ccb6.png)

**Comment by pmattern** [comment]
No single duplicate can be seen running latest checkouts of all LXQt components on Arch Linux.
Are you by any chance using an outdated version of `lxqt-common`? Asking as a problem pretty similar to what you're proposing here has been discussed and solved in lxde/lxqt-common#42.

**Comment by sixsixfive** [comment]
>Are you by any chance using an outdated version of lxqt-common? 

hm, no its the latest stable release(0.10) from [september](http://metadata.ftp-master.debian.org/changelogs//main/l/lxqt-common/lxqt-common_0.10.0-2_changelog)

**Comment by agaida** [comment]
hmm - you use a outdated version.

**Comment by sixsixfive** [comment]
well, if it isn't stable someone should make a new release, since nobody runs git versions on production systems...

anyway for me(and anyone else this seems like the lastest stable):
https://github.com/lxde/lxqt/releases

**Comment by luis-pereira** [comment]
@sixsixfive We are preparing to release on May 16th.

**Comment by agaida** [comment]
apt policy lxqt-about
lxqt-about:
  Installiert:           0.10.0-9-g2fc52df-1
  Installationskandidat: 0.10.0-9-g2fc52df-1
  Versionstabelle:
     0.10.0-3 500
        500 http://ftp.debian.org/debian unstable/main amd64 Packages
        500 http://ftp.debian.org/debian testing/main amd64 Packages

sixsixfive - nobody can run it from debian stable - thats right. And please don't argue about the meaning of the word stable. So if you run LXQt on debian systems you run versions from sid and testings - and one must decide if this fits for "production use".
And some words regarding the meaning of "stable":
- might be: stable abi and api - not true
- might be: major development is done, only bug fixes - not true
- might be: available from debian/stable: not true
- might be: is my daily driver for nearly tree years now without major glitches: true
