### ISSUE TITLE
Cant register http://pootle.lxde.org/

### ISSUE THREAD

**Issue by manjarqo** [lxde/lxqt#1049]
Want to help whith localization but cant log in

**Comment by palinek** [comment]
@jleclanche what's the state of deploying pootle for LXQt?

**Comment by MingcongBai** [comment]
+1

**Comment by Serkan-devel** [comment]
Still doesn't work

**Comment by yan12125** [comment]
Seems all changes go into https://github.com/lxde/lxqt-l10n directly?

**Comment by agaida** [comment]
pootle is working again - so i will close this issue. The not so nice thing is that pootle is used for LXDE only. So our translators must wait until the weblate installation is up and running

**Comment by MingcongBai** [comment]
Thanks!
