### ISSUE TITLE
[lxqt-panel] Sensors applet just flashing

### ISSUE THREAD

**Issue by theredbaron1834** [lxde/lxqt#1051]
As of now, the top of the sensor bar is the "tempX_max". However, not all temp sensors have a "max" temp set, such as my "radeon-pci-0008", it only has:

    sensors -u radeon-pci-0008
    radeon-pci-0008
    Adapter: PCI adapter
    GPU Temp:
      temp1_input: 63.000
      temp1_crit: 120.000
      temp1_crit_hyst: 90.000

Because it doesn't have a temp1_max, this means it  is just constantly flashing, and of no real use. The ability to set the min/max temp of the sensors, if doable, would fix this.

**Comment by technic** [comment]
Same story in my laptop

**Comment by palinek** [comment]
Please, check the lxde/lxqt-panel#368

**Comment by pmattern** [comment]
lxde/lxqt@985cc16 of branch `sensors` is terminating the flashing on my system where it was affecting a sensor depicted as `radeon-pci-0008` in the configuration dialogue of plugin-sensors as well.
