### ISSUE TITLE
Path of build directory gets incorporated in binary lxqt-sesssion

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#1053]
The path of the directory were lxqt-session gets built is incorporated in binary `lxqt-session`.

E. g. when directories `/usr/local/x5ae4/{build,lxqt-session,installation}` are used as build directory, the one comprising the sources and dummy target directory there's
```
$ strings /usr/local/x5ae4/installation/usr/local/bin/lxqt-session | grep x5ae4
/usr/local/x5ae4/lxqt-session/lxqt-session/src/sessionapplication.cpp
```
So far I couldn't see any real malfunction associated with this problem, but only messages like
> Mai 12 10:40:16 arch-64-lxqt-git lxqt-session[1009]: /usr/local/peter/yaourt-tmp-peter/aur-lxqt-session-git/src/lxqt-session/lxqt-session/src/sessionapplication.cpp : 79 Session "session" about to launch (default 'session')

in systemd's journal where the path represents the one used by a script invoking `yaourt` on my production system.

On a side note `cmake` throws a warning
```
CMake Warning (dev) at lxqt-session/CMakeLists.txt:59 (add_executable):
  Policy CMP0063 is not set: Honor visibility properties for all target
  types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "lxqt-session" of type "EXECUTABLE" has the following visibility
  properties set for CXX:

    CXX_VISIBILITY_PRESET
    VISIBILITY_INLINES_HIDDEN

  For compatibility CMake is not honoring them for this target.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
which isn't related to the problem, though, if I'm not mistaken.

Seen compiling lxde/lxqt-session@ccbf3d8 and lxde/lxqt-session@9cbb69e on Arch Linux.

**Comment by palinek** [comment]
The source file name/path is stored in every compiled object/binary (currently I can't find any resource stating this, but I've checked on a few examples).
If the object is compiled e.g. like `g++ -o foo.o -c foo.cpp` then the *foo.cpp* is stored in the *foo.o* object file.

The reason for storing the full path in our case is the way how *cmake* builds/creates Makefiles. E.g. (make VEBOSE=1):
```
...
[  2%] Building CXX object lxqt-session/CMakeFiles/lxqt-session.dir/src/sessionapplication.cpp.o
cd /home/palco/work/oss/lxqt/lxqt-session/build/lxqt-session && /usr/bin/c++   -DLXQT_DATA_DIR=\"/home/palco/opt/lxqt/share\" -DLXQT_ETC_XDG_DIR=\"/home/palco/opt/lxqt\" -DLXQT_GRAPHICS_DIR=\
"/home/palco/opt/lxqt/share/lxqt/graphics\" -DLXQT_RELATIVE_SHARE_DIR=\"lxqt\" -DLXQT_RELATIVE_SHARE_TRANSLATIONS_DIR=\"lxqt/translations\" -DLXQT_SHARE_DIR=\"/home/palco/opt/lxqt/share/lxqt\
" -DLXQT_SHARE_TRANSLATIONS_DIR=\"/home/palco/opt/lxqt/share/lxqt/translations\" -DLXQT_VERSION=\"0.10.0\" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_USE_QSTRINGBUILDER -DQT_
WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_XML_LIB -I/home/palco/work/oss/lxqt/lxqt-session/build/lxqt-session -I/home/palco/work/oss/lxqt/lxqt-session/lxqt-session -isystem /usr/include/x86_64-linu
x-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linu
x-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /home/palco/opt/lxqt/include/lxqt -isystem /ho
me/palco/opt/lxqt/include/lxqt/LXQt -isystem /usr/include/KF5/KWindowSystem -isystem /usr/include/KF5 -isystem /home/palco/opt/lxqt/include/qt5xdg -isystem /home/palco/opt/lxqt/include -isyst
em /home/palco/opt/lxqt/include/qt5xdg/1.3.0 -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml  -fno-exceptions -Wall -std=c++11 -O3 -DNDEBUG -fPIE   -fPIC -o CMakeFiles/lxqt-session.dir/src/s
essionapplication.cpp.o -c /home/palco/work/oss/lxqt/lxqt-session/lxqt-session/src/sessionapplication.cpp
...
```
-> the build is performed in a directory completely independent on the sources and the full path to compiled source is given on the command line => the full path is stored into \*.o.

So this "flaw" is present in all *cmake*-driven projects. E.g.:
```
$ strings /usr/lib/libsolid.so.4.14.14 | egrep '\.cpp$'
/build/kde4libs-3hgzgp/kde4libs-4.14.14/solid/solid/networking.cpp
/build/kde4libs-3hgzgp/kde4libs-4.14.14/solid/solid/devicemanager.cpp
/build/kde4libs-3hgzgp/kde4libs-4.14.14/solid/solid/predicateparse.cpp
/build/kde4libs-3hgzgp/kde4libs-4.14.14/solid/solid/powermanagement.cpp
/build/kde4libs-3hgzgp/kde4libs-4.14.14/solid/solid/backends/hal/halfstabhandling.cpp
/build/kde4libs-3hgzgp/kde4libs-4.14.14/solid/solid/backends/udisks2/udisksopticaldisc.cpp
/build/kde4libs-3hgzgp/kde4libs-4.14.14/solid/solid/backends/fstab/fstabhandling.cpp
/build/kde4libs-3hgzgp/kde4libs-4.14.14/solid/solid/backends/fstab/fstabwatcher.cpp
```

As I didn't find any resource/doc about storing the source file/path into compiled object, I can't say if this can be avoided somehow.

**Comment by pmattern** [comment]
I can confirm what you said about paths getting incorporated in general, e. g. in Solid. Yet I still think what we're discussing here is somewhat different as the message in systemd journal stated above suggests that some component wants to make use of that incorporated path but fails. Also, no messages can be found in the journal regarding all kinds of other binaries or libraries where paths of build directories are eventually incorporated as well.

FWIW a similar problem has recently been addressed and solved in QTermWidget, see lxde/qtermwidget#70.

**Comment by palinek** [comment]
> discussing here is somewhat different as the message in systemd journal stated above suggests that some component wants to make use of that incorporated path but fails.

What fail are you talking about? The message from journal you've posted is a regulare debug message:

```c++
bool SessionApplication::startup()
{
    LXQt::Settings settings(configName);
    qDebug() << __FILE__ << ":" << __LINE__ << "Session" << configName << "about to launch (default 'session')";
```

**Comment by paulolieuthier** [comment]
I'm not sure if I missed something, but is this actually an issue?

**Comment by pmattern** [comment]
Unlike I first thought it's a debug and not an error messages. Yet I still think it would be good to get rid of it if it's doable with reasonable effort.
Only meaningful messages should make it to the journal so as to prevent it from getting spammed.

**Comment by palinek** [comment]
> Only meaningful messages should make it to the journal so as to prevent it from getting spammed.

I completely agree here. And I thing we should improove the logging/debug by using the QLoggingCategory... something like I did it in nm-tray (palinek/nm-tray@d0311b3a60bd28b0a91643a8aa5ba6d702e1a76f)

With that we can turn the debugs on/off without the need of recompilation (e.g.: `QT_LOGGING_RULES="lxqt-component.debug=true" lxqt-component`), which is very usefull for end user testing...

**Comment by agaida** [comment]
+1

**Comment by paulolieuthier** [comment]
Great idea.

**Comment by pmattern** [comment]
It definitely is, yes.

**Comment by palinek** [comment]
@agaida, @paulolieuthier, @pmattern See the proposal for lxqt-session in lxde/lxqt-session#76

**Comment by pmattern** [comment]
That superfluous message can no longer be seen running lxde/lxqt-session@f6fba2a. Also, the commit doesn't seem to introduce any regression and hence looks GTM.

On a side note it turned out that the message can only be seen when the LXQt session is launched by a display manager (LightDM, SDDM) but not when it's launched from a virtual terminal by `startx` which seems a bit odd to me.

**Comment by palinek** [comment]
> On a side note it turned out that the message can only be seen when the LXQt session is launched by a display manager (LightDM, SDDM) but not when it's launched from a virtual terminal by startx which seems a bit odd to me.

Can be seen where? Doesn't `startx` redirect stdout/err into e.g. `~/.xsession-errors` ?

**Comment by pmattern** [comment]
I was thinking of systemd journal where I had expected the messages to appear using `startx` as well. As for `~/.xsession-errors` and friends I don't know if or how these are supposed to be used on Arch Linux. I've never seen any such file, didn't bother looking into this as I never missed it and any attempt to redirect the output of `startx` in a file failed so far (the file was either empty or X wouldn't start properly).
But after some tweaking like enlarging the virtual terminals' resolution and chosing a driver throwing less error messages it's obvious that the messages we're discussing here behave the same like when the sessions get started by a display manager.

This made me realize that a lot of other messages like `start "/etc/xdg/autostart/lxqt-foobar.desktop"` or `Module logout "lxqt-foobar.desktop"` are no longer logged either. But this seems like the right thing to do.

Closing this issue. (Could actually have been done before looking into that virtual terminal thing once more but anyway.)
