### ISSUE TITLE
Volume cannot be changed from tray icon

### ISSUE THREAD

**Issue by Mikaela** [lxde/lxqt#1056]
I talked about this at IRC and asked if I should open an issue and what troubleshooting information I should include, but I never got a response.

I can slide the volume anywhere between 0% and 100% with nothing happening. Multimedia keys on my laptop do nothing either.

Same applies to pavucontrol which looks broken. The only way I can change volume is running `alsamixer` in terminal.

![pavucontrol](https://i.imgur.com/7Huwxum.png)

* * * * *

`2016-05-18 08:45:46+0300 < Mikaela> Hi, I installed LXQt last night on Arch Linux. Today I noticed that I cannot change volume either by using the applet or pavucontrol and to change volume I had to go to alsamixer. My lxqt-panel is version 0.10.0-5 according to pacman. Is this a known issue (I was unable to find it from the issue tracker), should I do something to troubleshoot this (what?) or open an issue (and what information should I`
`2016-05-18 08:45:46+0300 < Mikaela> include)?`
`2016-05-18 08:53:35+0300 < Mikaela> another issue I am having and which I am going to search for now is some apps, mainly pavucontrol looking ugly and seeming like missing elements (the tabs aren't nicely separated and the slider is invisible) https://i.imgur.com/7Huwxum.png`
`2016-05-18 08:56:20+0300 < Mikaela> this seems to be the closest to that what I can find https://github.com/lxde/lxqt/issues/369`

**Comment by f2404** [comment]
Are you using pulseaudio, or just alsa?

**Comment by Mikaela** [comment]
PulseAudio which Alsamixer says to manage. I only see one master bar there.

**Comment by f2404** [comment]
Have you tried reading https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting and following the receipts described there?
I think you could start with running `pulseaudio -vvvv` (having killed the pulseadio server beforehand).

**Comment by Mikaela** [comment]
I pastebinned output of that command running for some time to http://sprunge.us/CCSR . The relvant part seems to be ctrl + f for `lxqt-panel` where I see that I changed the volume, but nothing changed.

The end is CTRL + C to pulseaudio.

**Comment by paulolieuthier** [comment]
If you use alsamixer in the terminal, than you should set the volume plugin to use the Alsa backend. About pavucontrol looking broken, that's probably because you're using a Gtk theme not compatible with Gtk 3.20. There are just a few, try using the default one.

**Comment by Mikaela** [comment]
> If you use alsamixer in the terminal, than you should set the volume plugin to use the Alsa backend. 

Thanks, that seems to work. However I wonder why it doesn't work with PulseAudio directly as I only installed alsamixer afterwards when I was unable to change volume any other way.

> There are just a few, try using the default one.

What is the default theme? I seem to be currently using breeze as it makes GTK apps look a little more like the Qt apps.

**Comment by Mikaela** [comment]
I am currently on Numix and it seems to work fine. Thanks for the help.

**Comment by f2404** [comment]
> Thanks, that seems to work. However I wonder why it doesn't work with PulseAudio directly as I only installed alsamixer afterwards when I was unable to change volume any other way.

The LXQt volume control is able to control PulseAudio device for me.
