### ISSUE TITLE
Environment variable TERM not exported ?

### ISSUE THREAD

**Issue by Esclapion** [lxde/lxqt#1062]
I use lxqt 0.10 (Arch).

![bug](https://cloud.githubusercontent.com/assets/3512979/15546752/6e18f17c-22a1-11e6-8ee6-decc2e076171.png)

I found an old discussion on this subject, but I don't understand how to solve that.

**Comment by Vladimir-csp** [comment]
It should not be set in session. Terminal emulators and other specific software should care of that, and values are strictly limited to those present in terminfo database.

**Comment by Esclapion** [comment]
BROWSER is well set.

**Comment by pmattern** [comment]
Using environment variable `TERM` to set the default terminal emulator is contradicting the purpose of this variable and just plain wrong. This needs to be stopped anyway so it actually doesn't matter whether or not the current approach in `lxqt-config-session` is working.
Also, this is already discussed in #433 where the apparent failure of setting the variable in `lxqt-config-session` has been mentioned as well.
