### ISSUE TITLE
lxqt-config-monitor, arandr/xrandr, lxqt-panel, & desktop with two monitors: odd behavior when interacting

### ISSUE THREAD

**Issue by rogerfranz** [lxde/lxqt#1066]
On upgrading to Ubuntu 16.04, I noticed that my dual monitor configuration was not working correctly.

I've been using this script to configure my monitors:
```
#!/bin/sh
xrandr --output HDMI1 --off --output LVDS1 --mode 1366x768 --pos 1680x0 --rotate normal --output VIRTUAL1 --off --output DP1 --off --output VGA1 --mode 1680x1050 --pos 0x0 --rotate normal

```
LVDS1 has been Desktop 1, and VGA1 has been Desktop 2.

However, as of upgrading to ver 16.04, the application menu icon simply does not respond after I run this script. I click, it shows that it's been clicked, but no menu appears. If I reset the monitors to overlay instead of side-by-side, the menu appears when clicked.

Moreover, the context menus presented on right-clicking are presented horizontally (menu items are in a row) rather than vertically (the expected behavior).

So, I checked here and discovered lxqt-config-monitor (haven't been using that). I normally run my primary panel on the right side of the right most screen (which has been Desktop 1).

On reboot (to see if things changed): the main panel had shifted to the right side of the left screen. It would also respond on the left side of the right screen. The application menu did display, however.

I have a second panel configured, positioned at the top of the primary monitor. After running lxqt-config-monitor, this is positioned at the top of the secondary monitor. I have to manually adjust each panel's position individually to put them back where they were originally configured to be, which is now Desktop 2 instead of Desktop 1.

Further, every time I reboot, the wallpaper is misplaced or improperly displayed -- differently each time. I use one huge image for the wallpaper. This last reboot, the image was off by 18-20 pixels in the y-direction. Those 18-20 pixels on VGA1 were occupied by a partial graphic of the second panel (the graphic was not responsive to mouseover or click). On LVDS1 they were occupied by black space (but the panel was working; it's set to autohide). The previous boot, one monitor displayed the correct portion of the image, but the other one displayed the entire image (shrunk to fit, sort of).

Using lxqt-config-monitor and using one of the previously saved Settings does not correctly reposition the wallpaper, and also does not position the panels where they're supposed to be. I have to set up a new configuration, click the "No" response, and then use the one in Settings. This does manage to reposition the wallpaper the way I want it. It also redisplays the other intended content on Desktop 1 (the contents of the Desktop folder, which don't always display after boot, though they're supposed to).

Why does using xrandr suppress application menu activation? I've been using the above script (I set it on my desktop -- if i'm using two monitors, I run it; if I'm not, I don't) for well over a year. I'm guessing this is an lxqt-panel issue.

Why does lxqt-config-monitor not configure the screens as expected?.

Is there a way to script monitor configuration changes without using xrandr and without invoking lxqt-config-monitor's GUI? As mentioned, I've been using the script (generated by arandr) for over a year without troubles until this upgrade.

Looking back at all this, it seems that there may be several bugs involved here.

Thanks.

Roger

versions:

Lubuntu 16.04
Quad-core i7, 16 GB

from dpkg-query:
```
||/ Name                                Version                Architecture           Description
+++-===================================-======================-======================-============================================================================
ii  lxqt                                4.2~ubuntu16.04.1      all                    Metapackage for LXQt
ii  lxqt-about                          0.10.0-3               amd64                  About screen for LXQt
ii  lxqt-admin                          0.10.0-3               amd64                  Admin tools for LXQt
ii  lxqt-common                         0.10.0+201605161848~ub all                    Common files for LXQt
ii  lxqt-config                         0.10.0-3               amd64                  LXQt system settings center
ii  lxqt-core                           4.2~ubuntu16.04.1      all                    Metapackage for the LXQt core
ii  lxqt-desktop                        4.2~ubuntu16.04.1      all                    Metapackage for LXQt
ii  lxqt-globalkeys                     0.10.0-5               amd64                  daemon used to register global keyboard shortcuts (appl.)
ii  lxqt-notificationd                  0.10.0-2               amd64                  LXQt notification daemon
ii  lxqt-openssh-askpass                0.10.0-5~ubuntu16.04.1 amd64                  OpenSSH user/password GUI dialog for LXQt
ii  lxqt-panel                          0.10.0-8~ubuntu16.04.1 amd64                  LXQt desktop panel
ii  lxqt-policykit                      0.10.0-3               amd64                  LXQt authentication agent for PolicyKit
ii  lxqt-powermanagement                0.10.0-3               amd64                  power management module for LXQt
ii  lxqt-qtplugin                       0.10.0-3               amd64                  LXQt system integration plugin for Qt
ii  lxqt-runner                         0.10.0-3               amd64                  LXQt program launcher
ii  lxqt-session                        0.10.0-4~ubuntu16.04.1 amd64                  session manager component for LXQt
ii  lxqt-sudo                           0.10.0-3               amd64                  Graphical QT frontend for plain sudo
```

**Comment by agaida** [comment]
explicit no ubuntu bashing - could someone test this with a multimonitor setup and debian/testing or sid - sorry, i'm out, i prefer one big screen.

**Comment by rogerfranz** [comment]
This seems to have been fixed -- I haven't had a problem with this for some time, so I'm closing this.

I'm using Xrandr/arandr and ignoring lxqt-config-monitor, as it seems to be unreliable (for me. Others may find it quite useful and stable, but for me, it doesn't work properly, and I don't have time to explore why).
