### ISSUE TITLE
Make libkscreen dependency optional

### ISSUE THREAD

**Issue by luke-jr** [lxde/lxqt#1068]
libkscreen unnecessarily depends on Wayland bloat I do not need/want (requiring not just Wayland libs, but rebuilding common libs like Mesa), and its maintainer refuses to allow Wayland stuff to be made optional (see [KDE bug 361954](https://bugs.kde.org/show_bug.cgi?id=361954), so hopefully LxQt can abandon it (at least optionally).

**Comment by palinek** [comment]
The only component depending on libkscreen is `lxqt-config-monitor` ... so don't build/use that and you will not pull the libkscreen dependency.

**Comment by luke-jr** [comment]
How do I build lxqt-config without lxqt-config-monitor?

**Comment by agaida** [comment]
Just comment it out in the CMakeLists.txt i would guess.

**Comment by luke-jr** [comment]
Eh, users shouldn't be expected to edit the build system IMO...

**Comment by agaida** [comment]
you asked - you got an answer - it's just that easy

**Comment by palinek** [comment]
Well, it's not a big deal to add option for building the components. I'll do it instantly...

**Comment by palinek** [comment]
There you go lxde/lxqt-config@96e6569

@luke-jr Now you can easily disable building of lxqt-config-monitor with e.g. `cmake -DWITH_MONITOR=no ..`

**Comment by luke-jr** [comment]
Thanks
