### ISSUE TITLE
lxqt-panel/plugin-colorpicker/: background and font color doesn't match theme

### ISSUE THREAD

**Issue by ms6676749** [lxde/lxqt#1069]
OS: archlinux
lxqt version: git build 6/3/16
lxqt theme: frost

The colorpicker plugin (upper right hand corner) doesn't really integrate with one of the included themes.

![colorpicker](https://cloud.githubusercontent.com/assets/13208509/15772151/51c4e22c-2924-11e6-94fc-14427c75a52e.jpg)

**Comment by palinek** [comment]
@intialonso can you have a look on this?

**Comment by intialonso** [comment]
Yes, Im on it.

**Comment by intialonso** [comment]
Should be fixed in acd8f6ef994710588bd14b1f71c83ec3a57ad72c

**Comment by intialonso** [comment]
Should be fixed in https://github.com/lxde/lxqt-common/commit/acd8f6ef994710588bd14b1f71c83ec3a57ad72c

Please confirm.

**Comment by ms6676749** [comment]
Confirmed thanks!

![colorpicker_1](https://cloud.githubusercontent.com/assets/13208509/15783680/f36b8132-2963-11e6-9975-c98f7bba8cd9.jpg)
