### ISSUE TITLE
Compiling libqtxdg

### ISSUE THREAD

**Issue by Rawbit** [lxde/lxqt#1070]
Hello, 

I'm new to compile programs by myself.
I use Debian Stretch.
Basically I have the question if QT4 or QT5 is  used. I think LXQT uses QT5 ?
Here's the error report !
By the way: Thank you very much for LXQT - I really enjoy it !!!

~/Src/lxqt/libqtxdg$ cmake ..

-- Building in SuperBuild mode. Builds all LXQt CMake projects at once.
    Autotools/Automake based projects not yet supported.
    lximage-qt also not yet supported
-- Building with Qt 4.8.7
-- Checking for module 'QtMimeTypes'
--   No package 'QtMimeTypes' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:363 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:528 (_pkg_check_modules_internal)
  libqtxdg/CMakeLists.txt:158 (pkg_check_modules)

Kind regards

Axel

**Comment by agaida** [comment]
For debian related questions feel free to join oftc #debian-lxqt - and i would really suggest to use the existing packages and don't use the checkout, build and install all method.

**Comment by pmattern** [comment]
There seems to be something seriously wrong with both the scripts in repository `lxqt` and wiki page [Building From Source](https://github.com/lxde/lxqt/wiki/Building-From-Source).

Besides support of Qt 4 has been removed from all LXQt running `build_all.sh` on systems where the usual Qt 5 components are available while Qt 4 lacks yields results like this from Debian stretch
```
qmake: could not find a Qt installation of ''
CMake Error at /usr/share/cmake-3.5/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
```
and after adding Qt 4 there's
```
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Building with Qt 4.8.7
-- Checking for module 'QtMimeTypes'
--   No package 'QtMimeTypes' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:363 (message):
```
To my knowledge QtMimeTypes was abandoned as of Qt 5 and it was definitely removed from repository `lxqt` in lxde/lxqt@890d8aa.
Not sure whether we should fix this or drop those installation scripts altogether.

The said wiki page claims `libqtxdg` is still supporting Qt 4 and describes how to install QtMimeTypes.

Reopening as a reminder to clarify theses topics.

@agaida
The OP said he wanted to look into compiling from source code which is an exercise that cannot be replaced by using binary packages. Binary packages don't allow for compiling current checkouts in real time either. Except from meeting dependencies compiling from source code cannot really be called distribution specific.

@Rawbit
Just curious, how exactly did you try to install? Asking as I could basically reproduce your findings, see above, but not exactly the ones you describe. E. g. invoking just `cmake ..` asks for variable `CMAKE_PREFIX_PATH` here, after adding the variable pkg-config is stated as requirement and so on.

**Comment by agaida** [comment]
Nothing against building from source - but please - not the whole thing. Ok, building the whole LXQt from lxqt/lxqt might be a exercise, but please don't install any of the resulting binaries.

**Comment by Rawbit** [comment]
Dear both,

thank you very much for your answer.

For me it would be great only to compile lxqt.


I followed the manual https://github.com/lxde/lxqt/wiki/Building-From-Source

I use QT5 from Debian Stretch.

I like like to compile in ~/Src/lxqt/


My first problem is to set the enviroment variables for cmake correctly :


rbit@rbitzen:~/Src/lxqt/build$ cmake ..
-- Building in SuperBuild mode. Builds all LXQt CMake projects at once.
     Autotools/Automake based projects not yet supported.
     lximage-qt also not yet supported
CMake Error at CMakeLists.txt:6 (message):
   CMAKE_PREFIX_PATH environment variable not set.  When configuring for the
   first time, make sure CMAKE_PREFIX_PATH is set to the root of the build
   directory.  It can be done by passing it to cmake as an command line
   parameter (e.g.  cmake -DCMAKE_PREFIX_PATH=path_to_your_build_dir ..) 
OR by
   setting the CMAKE_PREFIX_PATH environment variable (e.g.  export
   CMAKE_PREFIX_PATH=path_to_your_build_dir ..).

rbit@rbitzen:~$ echo $PATH
/usr/include/x86_64-linux-gnu/qt5:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games


rbit@rbitzen:~$export CMAKE_PREFIX_PATH=~/Src/lxqt/     (???)

rbit@rbitzen:~/Src/lxqt/build$ cmake ..
-- Building in SuperBuild mode. Builds all LXQt CMake projects at once.
     Autotools/Automake based projects not yet supported.
     lximage-qt also not yet supported
-- Building with Qt 4.8.7
-- Checking for module 'QtMimeTypes'
--   No package 'QtMimeTypes' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:363 
(message):
   A required package was not found
Call Stack (most recent call first):
   /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:528 
(_pkg_check_modules_internal)
   libqtxdg/CMakeLists.txt:158 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/rbit/Src/lxqt/build/CMakeFiles/CMakeOutput.log".i
See also "/home/rbit/Src/lxqt/build/CMakeFiles/CMakeError.log".

vim /home/rbit/Src/lxqt/build/CMakeFiles/CMakeError.log (Cut)

...

Run Build Command:"/usr/bin/make" "cmTC_e74db/fast"
/usr/bin/make -f CMakeFiles/cmTC_e74db.dir/build.make 
CMakeFiles/cmTC_e74db.dir/build
make[1]: Verzeichnis „/home/rbit/Src/lxqt/build/CMakeFiles/CMakeTmp“ 
wird betreten
Building CXX object CMakeFiles/cmTC_e74db.dir/CheckSymbolExists.cxx.o
/usr/bin/c++    -I/usr/include/qt4   -o 
CMakeFiles/cmTC_e74db.dir/CheckSymbolExists.cxx.o -c 
/home/rbit/Src/lxqt/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx
/home/rbit/Src/lxqt/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx: In 
function ‘int main(int, char**)’:
/home/rbit/Src/lxqt/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: 
error: ‘Q_WS_MAC’ was not declared in this scope
    return ((int*)(&Q_WS_MAC))[argc];
                    ^
CMakeFiles/cmTC_e74db.dir/build.make:65: die Regel für Ziel 
„CMakeFiles/cmTC_e74db.dir/CheckSymbolExists.cxx.o“ scheiterte
make[1]: *** [CMakeFiles/cmTC_e74db.dir/CheckSymbolExists.cxx.o] Fehler 1
make[1]: Verzeichnis „/home/rbit/Src/lxqt/build/CMakeFiles/CMakeTmp“ 
wird verlassen
Makefile:126: die Regel für Ziel „cmTC_e74db/fast“ scheiterte
make: *** [cmTC_e74db/fast] Fehler 2

File /home/rbit/Src/lxqt/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <QtCore/qglobal.h>

int main(int argc, char** argv)
{
   (void)argv;
#ifndef Q_WS_MAC
   return ((int*)(&Q_WS_MAC))[argc];
#else
   (void)argc;
   return 0;
#endif
}






Am 05.06.2016 um 13:19 schrieb Peter Mattern:

**Comment by agaida** [comment]
@rawbit - as i said - you can compile it , if you can. It's a good exercise in compiling things. But you should never ever do a 'make install' unless you plan to reinstall sooner or later. Installing application without package manager is considered bad in 9 of 10 cases. 

And you should use Qt5 to compile, Qt4 would not work anymore.

**Comment by agaida** [comment]
since we depend on lxqt-build-tools and require at least Qt 5.6 i think this is solved.
