### ISSUE TITLE
Allow for transparent Qmenu in lxqt-panel.qss

### ISSUE THREAD

**Issue by dayflip** [lxde/lxqt#1071]
I'm using lxqt .10. Trying to add transparent to Qmenu so I can blend with my panel. Just can't do 
so at this time.

I have tried:  
background: rgba(56, 56, 56, 30%);
It still used 100%. Even though I set to 30% or 70%.

**Comment by dayflip** [comment]
What I'm trying to say. Should LXQtPanel #BackgroundWidget { background: rgba } work the same way as QMenu {background: rgba}? So It be possable to have matching transparency. Right now it QMenu {background: rgba} act like QMenu::item:selected. To were it just lighten the color.

**Comment by intialonso** [comment]
Do you have composition enabled?

2016-06-06 0:47 GMT-05:00 dayflip <notifications@github.com>:

**Comment by dayflip** [comment]
nvidia.conf file:
```
Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "metamodes" "nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection


Section "Extensions"
    Option         "Composite" "Enable"
EndSection
```
So yes it enable. I don't like using compton due to how bad refresh rate for the terminal is. And gave up trying to figure how have compton sync to try to fix it. Using xcompmgr since it does not add any issue to terminal refresh rate. And does just about everything I need but lighter.

**Comment by stefonarch** [comment]
Transparency in all qmenu works well with compton (you can see a screenhot and code  here: https://github.com/stefonarch/Valendas/).
I just tested xcompmgr and it works well too:
![schermata01](https://cloud.githubusercontent.com/assets/10681413/19281506/e8265b42-8fea-11e6-8b88-a05d61e0d54a.png)

**Comment by dayflip** [comment]
@stefonarch You mine testing is this widget style problem. Most of the time I may have it gtk2. I got this working with Breeze.
