### ISSUE TITLE
Use Breeze instead of Fusion as default theme engine

### ISSUE THREAD

**Issue by intialonso** [lxde/lxqt#1072]
Breeze is a modern and actively developed engine, there is a compatible (and updated) GTK3 theme, and is (subjectively) better looking.

Fusion is pretty basic, there is no GTK matching theme and look like windows XP.

**Comment by paulolieuthier** [comment]
I agree Breeze is much, much better. The thing is that it depends on Plasma's components:

```
➜  ~ pacman -Qi breeze | grep -i depends
Depends On      : frameworkintegration  kdecoration  breeze-icons
```

And Fusion is shipped with Qt.

**Comment by palinek** [comment]
I also think that we should stick to some of the Qt basic engines.

**Comment by Vladimir-csp** [comment]
In recent news:
Newer Qt versions will be able to mimic GTK3 natively. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=803423#139
GTK 3.20 broke all themes again, this time supposedly to make theming stable at last.
In this light #403 should  get some priority.

**Comment by luis-pereira** [comment]
IMO we should ship with an Qt theme. Distributions can always change it to meet their needs.

**Comment by intialonso** [comment]
Ok, it seems to be a consensus about keeping Fusion as the default QT engine.

Good news that ones about the future gtk integration on QT 5.6!

**Comment by agaida** [comment]
a maybe dumb question - is it possible to let the breeze engine appear in the list if all needed components are installed? (Only theoretical, right now im fine with GTK+)

**Comment by Esclapion** [comment]
A good question, I thought the same ;) I'm also with GTK+

**Comment by intialonso** [comment]
@agaida I dont understand, in what list do you want Breeze to appear?

I installed Breeze and it showed in the LXQT Appearance Settings.

**Comment by agaida** [comment]
@intialonso - thanks, that was the answer to our question :)

**Comment by intialonso** [comment]
@agaida
![search-result3](https://cloud.githubusercontent.com/assets/7544231/15879020/d597bbaa-2ce5-11e6-8dd3-45a1eb41ee60.png)

**Comment by agaida** [comment]
cool :)
