### ISSUE TITLE
openbox uses rc.xml instead lxqt-rc.xml  if set with "search" button

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#1073]
When choosing the windowmanager not with dropdown but hitting "search" in session.conf we will have

`window_manager=/usr/bin/openbox`

and it will use rc.xml instead of lxqt-rc.xml config file.
If set using the drop-down session.conf will read
`window_manager=openbox`
and lxqt-rc.xml is used. 

Probably because of    the 

>  if(mWindowManager == "openbox")
> 197	    {

in https://github.com/lxde/lxqt-session/blame/master/lxqt-session/src/lxqtmodman.cpp#L196

**Comment by luis-pereira** [comment]
@stefonarch Test https://github.com/lxde/lxqt-session/issues/75

**Comment by stefonarch** [comment]
Works as it should.

**Comment by paulolieuthier** [comment]
@stefonarch: thanks!
