### ISSUE TITLE
qterminal ignores window title set by a shell

### ISSUE THREAD

**Issue by grozin** [lxde/lxqt#1077]
qterminal always shows "QTerminal" as a window title. Tab titles are also just some fixed strings. It would be very useful to show the window title set by the shell in the tab title (and probably to show the title of the currently selected tab in the window title).
For example, in Gentoo, when I emerge a long list of packages, I just see a long output flying by. emerge sets the window title to something like "emerge package <m> of <n>", but I cannot see it anywhere. It would be much more useful to see "emerge package 5 of 100" or "emerge package 95 of 100".

**Comment by f2404** [comment]
I agree. There's a similar issue in the qterminal repo: https://github.com/lxde/qterminal/issues/52
