### ISSUE TITLE
Adding panel/plugin-statusnotifier "weird" visual behaviour

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#1079]
It doesn't happen every time. Picture better than words:
![screen-2016-06-24-17-18-17](https://cloud.githubusercontent.com/assets/62877/16343982/2cb8252e-3a32-11e6-81b8-521b9f705c77.png)
![screen-2016-06-24-17-20-29](https://cloud.githubusercontent.com/assets/62877/16343993/388b3832-3a32-11e6-8952-2833ccba3710.png)

Look at the world clock:
![screen-2016-06-24-17-21-53](https://cloud.githubusercontent.com/assets/62877/16344005/4873a022-3a32-11e6-92a1-8f0210347952.png)

**Comment by paulolieuthier** [comment]
See lxqt#927.
