### ISSUE TITLE
"You are not allowed to perform this action" after typing wrong password in Lubuntu Software Center

### ISSUE THREAD

**Issue by EaglePL** [lxde/lxqt#108]
1. Open Lubuntu Software Center.
2. Select application to be installed.
3. Click "Add to basket".
4. Click "Install Packages". - "Authentication Required" window will appear.
5. Type wrong password and click OK. - Authorization failed for some reason" information will appeared.
6. Click OK - unneeded "You are not allowed to perform this action" windows will appear.
7. Click "Close" - second "You are not allowed to perform this action" will appear.
8. Close second ""You are not allowed to perform this action" window by clicking Close.
9. Click "Close" on first ""You are not allowed to perform this action" windows - it will not work.

Window can be closed by clicking X in top right corner.

**Comment by paulolieuthier** [comment]
@EaglePL can you still reproduce it?

**Comment by paulolieuthier** [comment]
I believe the bug is fixed. If it still exists, please, reopen this.
