### ISSUE TITLE
[lxqt-runner] Move away from using deprecated QtScript

### ISSUE THREAD

**Issue by palinek** [lxde/lxqt#1080]
In runner the QtScript is used by math provider to calculate the result. But the QtScript is deprecated beginning from [Qt v5.7](https://wiki.qt.io/New_Features_in_Qt_5.7)

**Comment by goetzc** [comment]
Actually I think QtScript is deprecated since [Qt 5.5](http://wiki.qt.io/New-Features-in-Qt-5.5#Deprecated_Functionality)
