### ISSUE TITLE
Custom code for system tray icons can be dropped

### ISSUE THREAD

**Issue by mitya57** [lxde/lxqt#1082]
LXQt's platform theme currently has some [custom code](https://github.com/lxde/lxqt-qtplugin/blob/master/src/lxqtsystemtrayicon.cpp) for handling QSystemTrayIcons and converting them into StatusNotifierItems based on libdbusmenu-qt.

However, Qt has a [built-in implementation](https://code.qt.io/cgit/qt/qtbase.git/tree/src/platformsupport/dbustray/) of the same since version 5.5 (however it became actually usable in 5.6.1). So I believe the custom code can be dropped in favour of code in Qt.

Moreover, it appears that the code in LXQt is buggy and can lead to crashes sometimes. A test case is available in [QTBUG-54162](https://bugreports.qt.io/browse/QTBUG-54162#comment-324700) (which led me to creating this bug report).

**Comment by jleclanche** [comment]
cc @palinek

**Comment by paulolieuthier** [comment]
I'd rather we fix our implementation, as Qt's is private and thus we shouldn't rely on it.

**Comment by palinek** [comment]
How about using our implementation only in pre-5.6.1 versions ?

**Comment by palinek** [comment]
Have a look on the proposal lxde/lxqt-qtplugin#11

**Comment by paulolieuthier** [comment]
I tested, and it makes @mitya57's test case work. Great job.

**Comment by paulolieuthier** [comment]
@mitya57: out of curiosity, why do you consider it usable only after 5.6.1?

**Comment by mitya57** [comment]
> @mitya57: out of curiosity, why do you consider it usable only after 5.6.1?

Because in 5.6.1 I pushed many fixes to the implementation. The most important ones are probably qt/qtbase@9c7f37e648024a8c7129e332dfb12b3ebd1ebf25 and qt/qtbase@a4fac65938fdee74c07d34727920fb74087f82c6. There has also been a fix in 5.6.2/5.7 which adds support for multiple tray icons per application.

**Comment by palinek** [comment]
@mitya57 How can be the default implementation be used by 3rd party platform theme?

The QtPlatformTheme private aren't exported anyhow and the libQtPlatformTheme is built only as a static library.

I made a hack for testing in lxde/lxqt-qtplugin@16f760d, but this surely isn't the way how to include/use the QtPlatformTheme in 3rd party.

**Comment by mitya57** [comment]
Oh, right, I didn't think about this. Unfortunately there is no public API at the moment, but as you seem to be using private headers in other places anyway, you can try returning `new QDBusTrayIcon` from your `createPlatformSystemTrayIcon()` method (maybe with keeping the check that it's available).

We can try making QDBusTrayIcon public, but I don't think it would be easy because it is currently built as part of static Qt5PlatformSupport library, which gets linked in Qt5XcbQpa which doesn't seem to have any public API at the moment.

**Comment by luis-pereira** [comment]
@mitya57 We use private headers. But the classes we uses are all exported.

**Comment by mitya57** [comment]
You now have `Qt5PlatformSupport` in your `target_link_libraries`. It is a static library, so all symbols in it can be considered exported. So I think keeping using that library is the only your option for now.

Ubuntu's old platform theme (aka appmenu-qt5) also did that (and it inherited from QGnomeTheme, in a similar way to how you now inherit from QGenericUnixTheme).

**Comment by palinek** [comment]
> You now have Qt5PlatformSupport in your target_link_libraries. It is a static library, so all symbols in it can be considered exported. So I think keeping using that library is the only your option for now.

> Ubuntu's old platform theme (aka appmenu-qt5) also did that (and it inherited from QGnomeTheme, in a similar way to how you now inherit from QGenericUnixTheme).

You can't be serious about that ... IMO relying on a completely hidden implementation in `QtPlatformTheme` which seems to be intended exclusively for the purposes of `Qt5XcbQpa` is not a good choice:
- we will just blindly hack the include dirs to be able to compile
- we will link to static library which, I believe, is installed unintentionaly (because it is included in the Qt5XcbQPa)
... so our implementation/build will be fragile and can break anytime

**Comment by mitya57** [comment]
I am not saying that doing that is a good thing, I am just saying that there are no other choices at the moment.

I have just sent a mail about possible ways to solve this to the initial author of D-Bus tray implementation (Shawn Rutledge, who is not on GitHub) CCing you all. Hopefully we'll be able to resolve this problem properly on Qt side.

**Comment by paulolieuthier** [comment]
Bottom line: it's not "custom code", it's our implementation. Qt's implementation is private and thus not usable. If Qt devs decide to make their implementation public and distributions ship it, we'll definitely use it.

**Comment by luis-pereira** [comment]
@paulolieuthier I second that. It would be great if Qt devs could make it public.
