### ISSUE TITLE
PR #56 leads to FTBFS in lxqt-common

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#1085]
Hi, i unerstand the reasons for the check in: lxde/lxqt-common/pull/56 - but sorry, guys, wrong time, wrong place, wrong file  - one never can check a runtime dependency at build time. This might work fine for local builds, but will kill builds in build chroots - sorry, i don't see this before merged.

@palinek: this check should be at runtime (if xmessage is really needed) - this is the only chance - maybe we should mention such runtime dependencies and recommends in a README.md section.
If the programm otherwise run fine, but some functionality will not be available without rendering the program unusable - it's a recommendation - see a similar case in this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828697

**Comment by palinek** [comment]
Should I revert the commit?

**Comment by agaida** [comment]
yes, please - because introducing this in cmake don't make it an automatic runtime dependency - this will be up to the packagers, i would mention it in the README i guess
