### ISSUE TITLE
[lxqt-config] Depends libkf5screen6 but kde upgrade to libkf5screen7

### ISSUE THREAD

**Issue by SunRain** [lxde/lxqt#1086]
Is it possible to upgrade to libkf5screen7 or make a lxqt-project own version of libkf5screen?

**Comment by agaida** [comment]
it's possible to upgrade - one use normally a package manager to do so. Maybe i miss some thing, in that case please explain what you really want to. And no, we will not fork any libkf5*.

**Comment by SunRain** [comment]
Thanks, I made a mistake, it's my distribution problem, not lxqt.
Close issue now lol
