### ISSUE TITLE
Cannot log in to Pootle server

### ISSUE THREAD

**Issue by MingcongBai** [lxde/lxqt#1088]
Couldn't login to the LxQt Pootle server, the log in button does nothing as you can see in the screenshot below.

![screenshot_20160708_151219](https://cloud.githubusercontent.com/assets/5006263/16680043/b890b3c6-451e-11e6-8c8f-3682178295cd.png)

**Comment by goetzc** [comment]
I have also seen this. 

This issue might be the same as #1049.

**Comment by pmattern** [comment]
> This issue might be the same as #1049.

Indeed. Let's sum up the discussion in this preexisting issue.
