### ISSUE TITLE
Give the user the option to lock/not lock the screen when Suspending/Hibernating

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#1089]
Let's not overload https://github.com/lxde/lxqt/issues/431

A very simple start point:
![screen-2016-07-08-23-30-54](https://cloud.githubusercontent.com/assets/62877/16703304/1d755130-4564-11e6-9abf-4b38b7d12e3e.png)

**Comment by tsujan** [comment]
Those two options are definitely needed, but

(1) Can screen locking be considered as a part of power management?
(2) The options don't seem advanced to me. What about another title, like"Screen Locking"?

**Comment by Vladimir-csp** [comment]
1. Screen locking is closely related to both session management and power management. These options are related to power events, so let them be in power management, unless there is a more logical way to put them in lxqt-config-session.
2. Agreed. Put it under "Screen locking" title, add "Lock screen when lid is closed" option.

**Comment by tsujan** [comment]
> These options are related to power events

OK! So, they can belong to power management.

> add "Lock screen when lid is closed" option

Why? What use could it have?

**Comment by Vladimir-csp** [comment]
Lid may or may not invoke sleep. Locking session by closing the lid can be useful in office, or in any situation when a laptop is on AC power and running something.

**Comment by paulolieuthier** [comment]
Screen locking on closing the lid can already be set in lxqt-powermanagement, on the "Lid" page.

**Comment by luis-pereira** [comment]
@paulolieuthier The discussion here is about giving allowing the user to choose between Lock/Not Lock when Hibernating/Suspending. Right now we don't allow the user to choose: We always lock.

**Comment by paulolieuthier** [comment]
@luis-pereira yeah, it was a comment about what @Vladimir-csp said before. I'm working on this issue.

**Comment by paulolieuthier** [comment]
Thinking about it, I don't think this should be in lxqt-powermanagement. Although it's related to power events, it's about the session state and we get notified about the event by systemd/consolekit. Besides that, AFAIK, systemd or consolekit can't differ suspending from hibernating, so this is what I propose:

![screenshot_20160730_134322](https://cloud.githubusercontent.com/assets/1238157/17271787/f5cae2f4-565b-11e6-9bd9-f5908d1cf268.png)

What do you guys think?

**Comment by tsujan** [comment]
Good to me. When the user needs screen locking, he usually wants it for both suspension and hibernation, and the same is true for those who don't need it.

**Comment by luis-pereira** [comment]
Good to me. I wonder how will users react to having settings in different places (powermanagement and lxqt-config-session). But IMO it make sense to have this on the Leave Session.

**Comment by stefonarch** [comment]
+1

**Comment by agaida** [comment]
GTM

**Comment by Vladimir-csp** [comment]
IMHO, It does not matter through how many frontends the option is accessible, as long as it belongs there and governs the same setting of backend. Let it be both in session and power management config.

**Comment by paulolieuthier** [comment]
A small correction: of course systemd and consolekit can differ suspending from hibernating. What I meant was that the signal we listen to is the same.

**Comment by szg0000** [comment]
Is there any hotkey to lock the screen?

**Comment by stefonarch** [comment]
Il 08/12/2016 20:33, szg0000 ha scritto:
> Is there any hotkey to lock the screen?
In lxqt-globalshortcuts assign whatever you want to
xscreensaver-command -lock
(if you're using xscreensaver)
