### ISSUE TITLE
lxqt-panel does not remember desktop 2

### ISSUE THREAD

**Issue by brossaip** [lxde/lxqt#1093]
Hello.
I am using two screens with lxqt 0.10.0 and lxqt-panel is so flexible that I can choose to which screen it can go. If I choose bottom desktop 2, it goes without problem, but the next time that I restart the machine it goes again to bottom desktop 1. Furthermore, every time that I want to change its properties it keep saying the value bottom desktop 1 even when I have chosen bottom desktop 2 and it is in screen 2.
I have checked the configuration files in ~/.local/config/lxpanel/LXDE/panels/panel and in the Global section it does not appear information about the desktop. I think that this is why when it prints the options it keeps saying desktop 1.
Thanks a lot.

**Comment by palinek** [comment]
@brossaip please, confirm that the lxde/lxqt-panel@af59a79 fixes this for you.

**Comment by palinek** [comment]
@pmattern this could be connected also to behavoiur you've described in https://github.com/lxde/lxqt-panel/pull/310#issuecomment-215278898. Pleas check if the lxde/lxqt-panel@af59a79 makes any difference.

**Comment by brossaip** [comment]
Hi!

I have downloade lxqt-panel-master and done the modifications pointed
above. Unfortunately, I am not very good at compiling, I have gone to
lxqt-panel-master and typed "cmake ." It has started to configure  but it
crashes with the following error:

CMake Error at plugin-sysstat/CMakeLists.txt:3 (find_package):
  By not providing "FindSysStat-Qt5.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "SysStat-Qt5", but CMake did not find one.

  Could not find a package configuration file provided by "SysStat-Qt5" with
  any of the following names:

    SysStat-Qt5Config.cmake
    sysstat-qt5-config.cmake

  Add the installation prefix of "SysStat-Qt5" to CMAKE_PREFIX_PATH or set
  "SysStat-Qt5_DIR" to a directory containing one of the above files.  If
  "SysStat-Qt5" provides a separate development package or SDK, be sure it
  has been installed.

Can I compile lxqt-panel independantly of the rest of the project? What do
I need to do?

Yours sincerely,
BrossaIP

2016-07-15 13:00 GMT+02:00 palinek <notifications@github.com>:

**Comment by pmattern** [comment]
The missing file belongs to [libsysstat](https://github.com/lxde/libsysstat) which is one of the prerequisites of lxqt-panel.

Regarding prerequisites you may want to have a look at wiki page [Building-From-Source](https://github.com/lxde/lxqt/wiki/Building-From-Source) and / or tell us which distribution you're using so that we can hand you a specific list of packages.

**Comment by brossaip** [comment]
Hi.

I am using Sabayon, I have checked your page and I have installed libconfig
and libsysstat that were missing. I have configured it and started to
compile it, but it has crashed with this error:
Generating moc_xdgcachedmenu.cpp
[ 21%] Built target mainmenu_automoc
[ 22%] Generating mainmenu.desktop
Scanning dependencies of target mainmenu
[ 22%] Building CXX object
plugin-mainmenu/CMakeFiles/mainmenu.dir/actionview.cpp.o
[ 23%] Building CXX object
plugin-mainmenu/CMakeFiles/mainmenu.dir/lxqtmainmenu.cpp.o
/home/jbd/lxqt-panel-master/plugin-mainmenu/lxqtmainmenu.cpp: In member
function ‘void LXQtMainMenu::setButtonIcon()’:
/home/jbd/lxqt-panel-master/plugin-mainmenu/lxqtmainmenu.cpp:422:77: error:
‘LXQT_GRAPHICS_DIR’ was not declared in this scope
                 .arg(settings()->value(QLatin1String("icon"),
QLatin1String(LXQT_GRAPHICS_DIR"/helix.svg")).toString()));

^
plugin-mainmenu/CMakeFiles/mainmenu.dir/build.make:91: recipe for target
'plugin-mainmenu/CMakeFiles/mainmenu.dir/lxqtmainmenu.cpp.o' failed
make[2]: *** [plugin-mainmenu/CMakeFiles/mainmenu.dir/lxqtmainmenu.cpp.o]
Error 1
CMakeFiles/Makefile2:526: recipe for target
'plugin-mainmenu/CMakeFiles/mainmenu.dir/all' failed
make[1]: *** [plugin-mainmenu/CMakeFiles/mainmenu.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

Thanks a lot for your support and your time. Now I'm leaving and I won't be
connecting during the weekend.

Best regards,
BrossaIP



2016-07-15 17:27 GMT+02:00 Peter Mattern <notifications@github.com>:

**Comment by pmattern** [comment]
@palinek
All problems depicted in https://github.com/lxde/lxqt-panel/pull/310#issuecomment-215278898 (placement of panel on an other monitor not working as expected) are indeed solved running lxde/lxqt-panel@af59a79.
In my opinion the problem addressed in this issue is fixed as well. Only possible problem is that I can test using the multi monitor feature of QEMU only right now which may not behave exactly the same as real hardware.
