### ISSUE TITLE
lxqt-common - misplaced file

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#1094]
Does lxqt-powermanagement_it.desktop really should be in lxqt-common? - Imho the file belong to lxqt-powermanagement?

**Comment by pmattern** [comment]
There are two desktop entry files involved here.

lxqt-powermanagement comes with a desktop entry file `$XDG_DATA_DIRS/applications/lxqt-config-powermanagement.desktop` which is meant to launch the configuration GUI. It is [already translated](https://github.com/lxde/lxqt-powermanagement/tree/master/config/translations) to Italian.

lxqt-common comes with a desktop entry file `$XDG_CONFIG_DIRS/autostart/lxqt-powermanagement.desktop` that's meant to launch binary `lxqt-powermanagement` as LXQt Module. Corresponding translations are maintained in [./autostart/translations/](https://github.com/lxde/lxqt-common/tree/master/autostart/translations) which is where [./lxqt-powermanagement_it.desktop](https://github.com/lxde/lxqt-common) you're probably addressing belongs, too.

(Personally I doubt whether translations of the desktop entry files in lxqt-common make any sense at all as these are only used to autostart stuff after all.)

**Comment by stefonarch** [comment]
Actually lxqt-powermanagement_it.desktop	is  yes in the wrong place, it should be in https://github.com/lxde/lxqt-common/tree/master/autostart/translations 
The translations appear in lxqt-config-session and thje italian one is missing. Probably my fault...
![schermata01](https://cloud.githubusercontent.com/assets/10681413/16886244/51013716-4ad3-11e6-9bee-2cc179fe60ac.png)

**Comment by pmattern** [comment]
Interesting! I didn't realize so far that those translations appear in `lxqt-config-session` so they do make sense.

Problem should be fixed in master now.
