### ISSUE TITLE
Adding program shortcuts to the desktop should be made easier

### ISSUE THREAD

**Issue by GHLieven** [lxde/lxqt#1097]
LXQt 0.10.0 Ubuntu 16.04

In LXDE you could add a program from main menu to the desktop by right clicking the menu item, and then selecting `add to desktop`. This functionality seems to be gone in LXQt.

As an alternative, I tried dragging the program from the main menu to the desktop, then selecting `copy here`, but that didn't work (I get an error message saying `Cannot copy a folder to it's own subfolder`)

The only way I've found so far, is manually copying the file from /usr/share/applications/ to /home/user/Desktop, but that's not very user-friendly.

**Comment by tsujan** [comment]
Drag-n-drop is possible from the main menu to desktop now. Please update your installation of pcmanfm-qt!

**Comment by stefonarch** [comment]
You can still in pcmanfm-qt's sidebar select "Applications" and drag any item you want to the desktop with your version.

**Comment by GHLieven** [comment]
Sorry for asking, but how do I update to the latest version of pcmanfm-qt?
@stefonarch: thanks for that, didn't know that was possible.

**Comment by palinek** [comment]
On ubuntu, you can use the [lubuntu daily ppa](https://launchpad.net/~lubuntu-dev/+archive/ubuntu/lubuntu-daily)

**Comment by pmattern** [comment]
Aside from dragging & dropping menu items to the desktop which definitely works in recent VCS checkouts adding a context menu as mentioned by the OP could be considered.

In LXDE it allows for copying to the desktop and opening a properties dialogue, in KDE there are even more options like adding to a starter in the panel or even application-specific options like editing a new message with Thunderbird.

Just saying while we're discussing this topic. Not sure we really need it.

**Comment by GHLieven** [comment]
@tsujan: Ok, used the lubuntu daily ppa, pcmanfm-qt got updated, but I still can't drag-n-drop from the main menu to the desktop, only to the panel. Am I missing something?

**Comment by stefonarch** [comment]
Did you restart the session?
Be aware that updating all packages will probably break translations, there should be another more "conservative" ppa, daily devel may break things easily. It's
 ppa:lxqt/ppa

**Comment by GHLieven** [comment]
Thanks stefonarch, that did the trick.

**Comment by pmattern** [comment]
Also, `ppa:lubuntu-dev/lubuntu-daily` has proven error-prone frequently in the past, unfortunately.
