### ISSUE TITLE
Need to adopt to Qt alterations suggested by log messages

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#1098]
Running lxde/lxqt-globalkeys@984e0e9 on Arch Linux and hence Qt 5.7.0 there's a warning
> lxqt-globalkeysd[\<PID\>]: Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)

upon each login.
I couldn't see any malfunction due to this so far but IMO the message suggests adjustments to some alterations in Qt are needed in the long run.

Note
I could see this launching the session by a display manager only which I blame to the fact that I failed to redirect messages of this kind in a login file or user instance of systemd journal when launching sessions by `startx` so far.

**Comment by palinek** [comment]
The lxde/lxqt-globalkeys#39 should do the trick...
