### ISSUE TITLE
build env setup

### ISSUE THREAD

**Issue by sequoiar** [lxde/lxqt#1100]
It's better add build step in README.md . I am building lxqt components and meet a lot of build dependency issue, like miss qt5 tools, etc.

**Comment by tsujan** [comment]
Look here: https://github.com/lxde/lxqt/wiki/Building-From-Source

**Comment by sequoiar** [comment]
follow  https://github.com/lxde/lxqt/wiki/Building-From-Source,  still saw the compatibility issue on ubuntu trusty:

root@lxqt-build:~# sudo apt-get install libkf5windowsystem-dev libglib2.0-dev libstatgrab-dev libxkbcommon-x11-dev libkf5solid-dev libdbusmenu-qt5-dev libsensors4-dev libxcb-util0-dev libxcb-damage0-dev libxcomposite-dev libxrender-dev libasound2-dev libpulse-dev libpolkit-agent-1-dev libxcb-screensaver0-dev libxcb-dpms0-dev libexif-dev libkf5screen-dev libxcursor-dev # Libraries for the other components of LXQt
Reading package lists... Done
Building dependency tree       
Reading state information... Done

E: Unable to locate package libkf5windowsystem-dev
E: Unable to locate package libkf5solid-dev
E: Unable to locate package libkf5screen-dev


root@lxqt-build:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
root@lxqt-build:~#

**Comment by tsujan** [comment]
Yout Ubuntu LTS is too old. Upgrade it to Ubuntu Xenial (16.04LTS)!

**Comment by agaida** [comment]
or better the yak

**Comment by agaida** [comment]
and there should be nearly no reason to build the packages with the sources script - downloading the prepared packages from Alioth and make a local build should be sufficient.

**Comment by tsujan** [comment]
Can be closed.

@sequoiar, you could still ask any question here. As @agaida told, it's better to install deb packages from a trusted repository. However, If you really want to compile LXQt from its sources, I recommend you build clean deb packages first (see Debian or Ubuntu doc for that).

**Comment by agaida** [comment]
and btw - one will find special prepared snapshot packages in the debian repositories (https://anonscm.debian.org/git/pkg-lxqt/ the branch is ever called lxqt-snapshots/latest) - checkout, run debian/get-snapshot and build - after that one could install with apt install ./*deb - done :)
