### ISSUE TITLE
the command assigned to a shortcut doesn't get parsed

### ISSUE THREAD

**Issue by GHLieven** [lxde/lxqt#1103]
The command assigned to a shortcut key doesn't get parsed. I mean, if I execute the command from terminal, it's working fine. But when hitting the shortcut key, it doesn't.

Take the following command as an example:
`notify-send "This system uses $(free -m | awk 'FNR == 2 {print $3}') MB of RAM"` 

Executed from terminal the output is:
`This system uses 184 MB of RAM`

Executed from hitting the shortcut key the output stays:
`This system uses $(free -m | awk 'FNR == 2 {print $3}') MB of RAM`

**Comment by paulolieuthier** [comment]
That parsing is done by the shell, and `notify-send` is receive's the final, parsed string. You can set your shortcut to `sh -c "notify-send \"This system uses $(free -m | awk 'FNR == 2 {print $3}') MB of RAM\""`, and then your shell will parse it.

**Comment by GHLieven** [comment]
Thanks for that, I'll try it immediately.

**Comment by GHLieven** [comment]
Ok, it works, but without the backslashes. Somehow the backslashes prevent the display of the notification.
