### ISSUE TITLE
[lxqt-admin] unlicensed files?

### ISSUE THREAD

**Issue by rapgro** [lxde/lxqt#1104]
For a review ¹ of a Fedora package, we need to know what license some files have. Altough there's the general COPYING file with LGPL 2.1 text, those questionable files currently do not have any header valid for license-check script.

```
[!]: License field in the package spec file matches the actual license.
     Note: Checking patched sources after %prep for licenses. Licenses
     found: "LGPL (v2.1 or later)", "Unknown or generated". 8 files have
     unknown license. 

--> Relevant files:
/AUTHORS
/COPYING
/README.md
/lxqt-admin-time/timedatectl.cpp
/lxqt-admin-time/timedatectl.h
/lxqt-admin-user/lxqt-admin-user-helper
/lxqt-admin-user/usermanager.cpp
/lxqt-admin-user/usermanager.h

```

¹ https://bugzilla.redhat.com/show_bug.cgi?id=1343738

**Comment by palinek** [comment]
I'll add the header into the .cpp/.h files...

But is the license header realy needed for the `lxqt-admin-user-helper` script?

**Comment by palinek** [comment]
lxde/lxqt-admin@2f95601

**Comment by agaida** [comment]
palinek - please don't place a license header in COPYING - this would be a licenense violation :p

**Comment by agaida** [comment]
GTM
