### ISSUE TITLE
Battery icons not correct for 2 primary batteries

### ISSUE THREAD

**Issue by edwardtulane** [lxde/lxqt#1105]
Last week, I got a thinkpad T460s, which has two batteries built in, one Li-ion and one Li polymer cell. As far as I can see, both are correctly recognised.  Also, they show up in the battery info window with all their properties.
Now in the panel there are two icons, but both show the charge state of battery 1. Can you please help me out?

**Comment by pmattern** [comment]
Could you let us know which OS you're running and how LXQt was installed?

**Comment by edwardtulane** [comment]
Of course: It's arch linux with the lxqt packages from the official repos (0.10.0 that is).

**Comment by rkapl** [comment]
I can confirm this behaviour. 
In addition to the official repos, I have tried `lxqt-powemanagement`  from GIT with the same result. Both icons share the same tooltip and icon, even though the charge levels are different. The tooltip strings are OK if printed on console for debugging (just before `setTooltip`), but they end up the same in the UI (specifically, only the first one that was set is shown for both icons).
