### ISSUE TITLE
Panel's menu artifact: transparent search field

### ISSUE THREAD

**Issue by paulolieuthier** [lxde/lxqt#1109]
Has anyone seen this?

![screenshot_20160805_000522](https://cloud.githubusercontent.com/assets/1238157/17425800/e5d46b22-5aa7-11e6-9a9b-8dbbff45ef0b.png)

**Comment by tsujan** [comment]
With an nVidia based computer, once I saw an ugly opaque bg behind the menu, while my theme was translucent. That occurred when I changed some panel settings to test https://github.com/lxde/lxqt/issues/927#issuecomment-237511325 but I couldn't reproduce it afterward. Anyhow, nVidia has its magic ;)

**Comment by stefonarch** [comment]
I see that too, but with Intel card and frost, it happens randomly when upgrading panel or other components without restarting session, or other "not regular" use. But  no idea  how to reproduce it.

**Comment by intialonso** [comment]
I have seen this before, also after an update. It goes away after a session
restart. (Nvidia + Kwin)

2016-08-05 1:14 GMT-05:00 Stefano Binde <notifications@github.com>:

**Comment by technic** [comment]
Seen with ATI + openbox. 100% reproducible in this way:

* restart panel - works ok
* reinstall lxqt-common files (arch linux)

  `sudo pacman -U lxqt-common-git/lxqt-common-git-0.10.0.44.g8f872cf-1-any.pkg.tar.xz`
* observe artifacts.

**Comment by palinek** [comment]
@technic Does is happen with all themes?

**Comment by technic** [comment]
yes

**Comment by technic** [comment]
Issue is localized:
Just change of Menu file in settings causes error.

**Comment by technic** [comment]
Seems like I can't always reproduce via settings, but the following should cause error:

`/etc/xdg/menus$ sudo unlink lxqt-applications.menu; sudo cp lxqt-applications.menu.bak lxqt-applications.menu`

**Comment by pmattern** [comment]
The crash of `menu-cached` is most likely due to lxde/menu-cache#8.

**Comment by technic** [comment]
HAVE_MENU_CACHE=0 doesn't help

**Comment by technic** [comment]
The error happens when we move mSearchEditAction to new menu in LXQtMainMenu::buildMenu()
No idea what the hell is going on, but I've found experimentally a fix in my case.

```diff
diff --git a/plugin-mainmenu/xdgcachedmenu.cpp b/plugin-mainmenu/xdgcachedmenu.cpp
index 255f69e..71bd191 100644
--- a/plugin-mainmenu/xdgcachedmenu.cpp
+++ b/plugin-mainmenu/xdgcachedmenu.cpp
@@ -117,7 +117,7 @@ void XdgCachedMenu::addMenuItems(QMenu* menu, MenuCacheDir* dir)
         connect(action, SIGNAL(triggered(bool)), SLOT(onItemTrigerred()));
       else if(type == MENU_CACHE_TYPE_DIR)
       {
-        XdgCachedMenu* submenu = new XdgCachedMenu(menu);
+        XdgCachedMenu* submenu = new XdgCachedMenu(this->parentWidget());
         action->setMenu(submenu);
         addMenuItems(submenu, MENU_CACHE_DIR(item));
       }
```

**Comment by palinek** [comment]
I'm not able to see this... but does it make any difference, if the "old" menu is deleted before adding the widgets into the new menu?:
```diff
diff --git a/plugin-mainmenu/lxqtmainmenu.cpp b/plugin-mainmenu/lxqtmainmenu.cpp
index 89a690f..76d0ac2 100644
--- a/plugin-mainmenu/lxqtmainmenu.cpp
+++ b/plugin-mainmenu/lxqtmainmenu.cpp
@@ -356,23 +356,20 @@ void LXQtMainMenu::buildMenu()
     {
       mMenu->removeAction(mSearchEditAction);
       mMenu->removeAction(mSearchViewAction);
+      delete mMenu;
     }
-    menu->addAction(mSearchViewAction);
-    menu->addAction(mSearchEditAction);
-    connect(menu, &QMenu::hovered, this, &LXQtMainMenu::setSearchFocus);
+    mMenu = menu;
+    mMenu->addAction(mSearchViewAction);
+    mMenu->addAction(mSearchEditAction);
+    connect(mMenu, &QMenu::hovered, this, &LXQtMainMenu::setSearchFocus);
     //Note: setting readOnly to true to avoid wake-ups upon the Qt's internal "blink" cursor timer
     //(if the readOnly is not set, the "blink" timer is active also in case the menu is not shown ->
     //QWidgetLineControl::updateNeeded is performed w/o any need)
     //https://bugreports.qt.io/browse/QTBUG-52021
-    connect(menu, &QMenu::aboutToHide, [this] { mSearchEdit->setReadOnly(true); });
+    connect(mMenu, &QMenu::aboutToHide, [this] { mSearchEdit->setReadOnly(true); });
     mSearchEdit->setVisible(mFilterMenu || mFilterShow);
     mSearchEditAction->setVisible(mFilterMenu || mFilterShow);
-    mSearchView->fillActions(menu);
-
-    QMenu *oldMenu = mMenu;
-    mMenu = menu;
-    if(oldMenu)
-        delete oldMenu;
+    mSearchView->fillActions(mMenu);
 
     searchTextChanged(mSearchEdit->text());
     setMenuFontSize();
```

**Comment by technic** [comment]
Segfault.
@palinek can you reproduce the bug? Open configuration of menu plugin and change *.menu file. (I have two identical files there.)

**Comment by palinek** [comment]
> Segfault.

Fixed that in lxde/lxqt-panel@006391f

> @palinek can you reproduce the bug? Open configuration of menu plugin and change *.menu file. (I have two identical files there.)

Nope. I don't get the corrupted (transparent) QLineEdit here.

**Comment by technic** [comment]
> Fixed that in lxde/lxqt-panel@006391f
No segfault, but artifact is still there (

**Comment by technic** [comment]
I created an example project to illustrate this issue. Bug is somewhere in qt or qt plugins.
https://github.com/technic/qt5-bug

**Comment by tsujan** [comment]
@technic I see no issue with your example; I tested in with Fusion, Breeze and Kvantum.

My previous comment (https://github.com/lxde/lxqt/issues/1109#issuecomment-237750871) wasn't about the problem discussed here. Under Debian and Manajro (Qt-5.6 and Qt-5.7), with Intel or nVidia, with Compton or Compiz, I've never seen artifacts in the panel menu or its search field.

**Comment by technic** [comment]
I was wrong, with QT_QPA_PLATFORMTHEME=qt5ct in about 30% cases transparent background happens, while with QT_QPA_PLATFORMTHEME=lxqt in 99% cases. Breeze and Oxygen themes have this bug, but Fusion doesn't. QT_QPA_PLATFORM=xcb in all cases.

P.S. added more explicit bug creation in my example and posted it to KDE colleagues https://bugs.kde.org/show_bug.cgi?id=368048

**Comment by tsujan** [comment]
Now I can reproduce it with the new https://github.com/technic/qt5-bug, but *only when breeze or gtk style is used*. They give:
````
XcbConnection: XCB error: 8 (BadMatch), sequence: 933, resource id: 60817456, major code: 130 (Unknown), minor code: 3
````
With Fusion and Kvantum, everything is OK.

I think the problem is in those styles, not in LXQt.

**Comment by technic** [comment]
Dear developers, please look at https://bugs.kde.org/show_bug.cgi?id=368048#c5. I think we can do a workaround for this bug until qt/breeze people make a fix on their side.

**Comment by palinek** [comment]
> Dear developers, please look at https://bugs.kde.org/show_bug.cgi?id=368048#c5. I think we can do a workaround for this bug until qt/breeze people make a fix on their side.

So finaly... I'm reproducing the bug with the Light theme & Breeze style. I'm going pushing the fix in a minute...

**Comment by palinek** [comment]
Please, check, if the lxde/lxqt-panel#369 does fix this...
