### ISSUE TITLE
Resize icons in the tray (status notifier) and change the clock font

### ISSUE THREAD

**Issue by Devoter** [lxde/lxqt#1112]
I have changed the panel height to 50 pixels and set "Icons size" to 48 pixes, but the result doesn't satisfies me (see my screenshot).
![_020](https://cloud.githubusercontent.com/assets/1221754/17613702/438ff80c-608a-11e6-9e61-f967d28c04b1.png)

P.S.: Ubuntu 16.04 amd64, LXQt 0.10.0

**Comment by palinek** [comment]
- We can't do much about the shown size of icons if your icon theme (or icon provided by application) doesn't provide suitable sizes of the icons.

- The font of `clock` is always the same (as configured in lxqt-config-appearance). If you need different size of the clock, you can use `worldclock` and fiddle with its configuration.

**Comment by tsujan** [comment]
The clock font aside (use `worldclock`, as @palinek told), here I don't see such a problem, with the latest LXQt:

![panel](https://cloud.githubusercontent.com/assets/981076/17618878/5e3b2f52-6097-11e6-9a31-de5d1a45903b.png)

Panel thickness is 40 and icon size is 28. When I increase them, icons are still aligned.

**Comment by Devoter** [comment]
Yeah, really, world clock looks so good, thanks. But I guess, If large icon cannot be found - the tray widget have to resize source image.

**Comment by tsujan** [comment]
> If large icon cannot be found - the tray widget have to resize source image.

That would be a mistake: small icons would be blurred if scaled to a larger size.

**Comment by palinek** [comment]
>> If large icon cannot be found - the tray widget have to resize source image.

> That would be a mistake: small icons would be blurred if scaled to a larger size.

Exactly. I think, we can close this...

**Comment by Devoter** [comment]
KDE resizes small icons, Unity - resizes, Gnome..., but LXQt doesn't resize, because icons would be blurred. Sad icons quality isn't  a problem, small icons is a problem. For example, we have 3 applications in the tray. First application have all icons sizes and looks good (current size is 48x48). Second application have 32x32 icon only. And third application have 22x22 icon. Its looks like a hell in the tray.

**Comment by pmattern** [comment]
Given that solutions are better than workarounds you should consider filing a bug against those applications then.

**Comment by Vladimir-csp** [comment]
IMHO, uniform size is preferable.

**Comment by Devoter** [comment]
Yes, I thanks for idea, I'll do it. But I still think that the resizing can be appended like an option. Close the issue if you disagree.

**Comment by palinek** [comment]
Just for completeness... are we talking about the tray-plugin or the notifier-plugin?

**Comment by Vladimir-csp** [comment]
does it matter?  If icon size is set, it should be maintained. In plugins, in taskbar, in tray. It does not matter if an app is missing some icons.

**Comment by Devoter** [comment]
statusnotifier, but I agree with Vladimir.

**Comment by palinek** [comment]
Just for the record, it's not our decision to not scale-up, but QT's http://doc.qt.io/qt-5/qabstractbutton.html#iconSize-prop

**Comment by Devoter** [comment]
) Okay, close the issue.

**Comment by tsujan** [comment]
> KDE resizes small icons, Unity - resizes, Gnome...

There's no reason for repeating their mistakes. Blurred KDE icons were always a problem to me, especially in Dolphin. If an icon is 32-pix and has no 64-pix variant, Dolphin will scale it to 64 when the size of its icons is set to 64. That isn't a good practise.

Again, as @palinek correctly mentioned. that's a Qt decision. Since it's a good choice, we have no reason to violate it.

Actually, you could check if an icon theme is correct in LXQt -- I mean in its *latest* GitHub version, which will be released as a stable version soon.

**Comment by Devoter** [comment]
Okay, thanks for the answer.
