### ISSUE TITLE
lxqt-panel feature request: workstation switcher plugin, i3-wm compatibility

### ISSUE THREAD

**Issue by wattahay** [lxde/lxqt#1114]
**Summary:** 
i3-wm is a modular paneling window manager that can be used with the LXQT desktop environment pretty easily. With a couple of small refinements, it would work as a fully presentable option for Lubuntu/LXDE/LXQT users. 

**Setup:**
1. Install i3 window manager - sudo apt-get install i3
2. Login to an LXQT session
3. Open the LXQT Session Settings
         5. Change the Window Manager to i3 (/user/bin/i3)
         6. Under 'LXQt Modules' Uncheck the 'Desktop' and 'Global Keyboard Shortcuts'
         7. Close the LXQt Session Settings
8. Logout and Login to the LXQt session again
9. Press Enter when the little black i3 dialog appears

There should be both the LXQT Panel and the i3bar at the bottom. Leave the i3bar there in order to compare the desktop switcher behavior between i3 and LXQt-Panel

**Steps To Reproduce Behavior:**
- Mess around and open windows from the Lubuntu Application Menu
- Note how applications open in panels. It is not important to become familiar with resizing etc. for this setup. [i3 usage](https://www.youtube.com/watch?v=Wx0eNaGzAZU)
1. Open an application in the current desktop
2. Press: 'Mod Key' + '4'
3. Open an application in that desktop
4. Press: 'Mod Key' + '7'
5. Open an application in that desktop
6. Press: 'Mod Key' + '9'
. . . and so on. . .

('Mod' + 'Shift' + 'q' exits an application)

*****************************************************************************************************
**Present Behavior:** (lxqt-panel desktop switcher only has partial functionality with i3-wm)
When creating new desktop workstations in i3, the numbers of the workstations in i3bar do not correlate to the workstation numbers in the LXQt Panel workstation switcher.

**Desired Behavior:**
When creating and switching workstations in i3, the LXQt workstation switcher plugin would behave as the i3bar does, displaying the numbers associated with specific workstations as they were opened.
*****************************************************************************************************

**libi3ipc-glib for i3 Workstation **
That XFCE plugin uses a [library, libi3ipc-glib, that may also be helpful](https://github.com/acrisci/i3ipc-glib) for this feature.
*****************************************************************************************************
**Additional Thoughts**
[Here is an example of a guide that utilizes a plugin for this in XFCE ](http://feeblenerd.blogspot.com/2015/11/pretty-i3-with-xfce.html)

**Comment by palinek** [comment]
> When creating new desktop workstations in i3, the numbers of the workstations in i3bar do not correlate to the workstation numbers in the LXQt Panel workstation switcher.

Please, be more specific about the _correlation_... How can the discrepancy be tirggered?

(I've tried a few tests in QEMU with manjaro/arch (not up to date) and it seemed to be OK)

**Comment by wattahay** [comment]
I understand. No problem.

**To Reproduce:**
- View both i3bar and the LXQt Panel simultaneously on the same session. 
- Create multiple workstations in i3, such that their numbers on i3bar are not incremental. ie: 1, 4, 6, 9
**Results on the LXQT Panel**
- While the i3bar shows proper non-incremental numbers, the LXQT Panel only shows incremental numbers up to the total number of i3 workstations.
- The numbers in LXQT do not correspond to the number associated with the desktop/workstation in i3.

**It will look something like below:**
****
i3bar:--| 1 | 4 | 6 | 9 |
****
lxqt:----| 1 | 2 | 3 | 4 |
****

lxqt workstations will alway be represented by incremental/consecutive integers, whereas i3 workstations are represented by non-consecutive integers, representing the number the user entered to represent the workstation.

**Comment by palinek** [comment]
> lxqt workstations will alway be represented by incremental/consecutive integers, whereas i3 workstations are represented by non-consecutive integers, representing the number the user entered to represent the workstation.

The default in plugin-desktopswitch is to show the number of virtual desktop. But what i3 shows is the name of the desktop.

Consider following screenshots:
- names
![screenshot](https://cloud.githubusercontent.com/assets/10990929/17688834/31e9ec60-6383-11e6-8ea0-fb79d10fb4c5.png)

- numbers
![screenshot](https://cloud.githubusercontent.com/assets/10990929/17688843/46566a2a-6383-11e6-95cd-ed599717bfc7.png)

So everything you need to do is change the "Desktop labels:" setting in `Desktop switcher` settings.

**Comment by wattahay** [comment]
Thank you, I am sorry to write that up.

I will delete it if someone hasn't already.


Taylor

**Comment by wattahay** [comment]
This was not actually an issue, but a matter of not seeing a configuration feature to show the names of the desktops instead of the numbers.

Thank you for the timely assistance on this.
