### ISSUE TITLE
lximage-qt: Support opening directories

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#1117]
Please support directories as valid targets for CLI arguments and Open dialog. Opening directory would in fact mean open first file in that directory according to current sorting order.

**Comment by asnt** [comment]
I propose a PR there: https://github.com/lxde/lximage-qt/pull/72

**Comment by tsujan** [comment]
Closed by https://github.com/lxde/lximage-qt/commit/7e496df8e69d06f9bd606e8120c8b17cb3cff4ec
