### ISSUE TITLE
Czech localization files for LXQt

### ISSUE THREAD

**Issue by pafri** [lxde/lxqt#1119]
As Pootle seems to be on zero for some time, I've downloaded the localization files from here on Git, and made the updates/creation of translation files if needed. Attached. Zipped. 
[lxqt-l10n-master.zip](https://github.com/lxde/lxqt/files/418188/lxqt-l10n-master.zip)
Stored in the folders according the used directories structure. Please commit them.

**Comment by palinek** [comment]
Why don't you commit the changes on your own and create PR? Don't you want the credit for it?

**Comment by pmattern** [comment]
Indeed. There's a wiki page [Translation](https://github.com/lxde/lxqt/wiki/Translation) which may help you get along with this.
You could simply copy the files you've already prepared in the Git clone acquired that way.

**Comment by pafri** [comment]
Hi,
I've translated Razor-qt, then after merge with LXDE worked with Pootle, then followed those discussions about problems with it - for years, until now. The work with Git isn't for me, I had to do it several years ago, and it wasn't fun for me.
Also when the LXQt team has problems with ensuring 1) the translation service (Pootle, Transifex, or similar), it should accept 2) the files, as it would be the common way seen at many other projects (that haven't the Pootle, Transifex etc. solutions present.
Greetings, Pavel Fric
 

    On Monday, August 15, 2016 4:49 PM, Peter Mattern <notifications@github.com> wrote:
 

 Indeed. There's a wiki page Translation which may help you get along with this.
You could simply copy the files you've already prepared in the Git clone acquired that way.—

**Comment by palinek** [comment]
@pafri, we have no problem accepting the translation this way. My consern was about the credit for you for your work. I'll do the commit for you with the credentials as e.g. [here](https://github.com/OpenOrienteering/mapper/commit/d16f9abc52089d923be13f848f6b76179a60cb71).

**Comment by palinek** [comment]
@pafri, please review the lxde/lxqt-l10n#77 and give a go to merge it.
I made minor changes in the .ts files:
- changed version 2.0 -> 2.1
- changed language cs_CZ -> cs

**Comment by pafri** [comment]
Fine, very well. 
[lxqt-powermanagement.zip](https://github.com/lxde/lxqt/files/420574/lxqt-powermanagement.zip)
I made some little change(s) of that string in the files, where it's surely visible: **lxqt-powermanagement_cs.ts**, and lxqt-config-powermanagement_cs.ts. I think, that step would make the joy to Petr.

I quite (exactly without making a search) don't know, what to expect from that function, what I could use: Hibernate - I use (if at all) just _Suspend_ (and one

interesting thing: German translation uses the word used in Czech for Suspend for Hibernate, and for "suspend" - the equivalent, simply the word we could find in vocabulary).

That thing with difference between folder - directory, and practical meaning for usage: yes, I translate simply "folder" as folder and "directory" as directory, but if I remember I am not sure with the usage in some files, if there is any little problem with it.

And one more mention: I didn't checked the files completely, just completed it to serve better the purpose.

Please replace those two files and make commit (maybe Petr send some other suggestions - or could make changes in the future himself).

Thanks and greetings, Pavel

**Comment by palinek** [comment]
> I made some little change(s) of that string in the files, where it's surely visible: lxqt-powermanagement_cs.ts, and lxqt-config-powermanagement_cs.ts. I think, that step would make the joy to Petr.

Pushed as lxde/lxqt-l10n@0e860a7

**Comment by pmattern** [comment]
Any particular reason to leave this open then?
