### ISSUE TITLE
Wallpaper Rendering Issue

### ISSUE THREAD

**Issue by isaki-x** [lxde/lxqt#1120]
When attempting to setup my wallpaper on my brand new LXQT install on Arch, I get really strange behavior. This is best shown through images.

This is the image I am attempting to use:

![taliyah-699055](https://cloud.githubusercontent.com/assets/10616227/17676993/d121c472-62fe-11e6-9ce0-06e9b36cb88c.jpg)

This is what happens when any "stretch" setting is chosen. You see it looks like it is tiled, but it isn't really, as the "tile" overwrites part of the image. Additionally centering it seems to cause a wrap effect.

Actually choosing "Tile" seems to be the only way the entire image is rendered. I have tried this same test with multiple images.

<img width="1440" alt="screen shot 2016-08-15 at 3 40 40 pm" src="https://cloud.githubusercontent.com/assets/10616227/17677013/e67c9d2e-62fe-11e6-867a-28c73a8f2a37.png">
<img width="1440" alt="screen shot 2016-08-15 at 3 40 46 pm" src="https://cloud.githubusercontent.com/assets/10616227/17677014/e67dd7d4-62fe-11e6-8215-20db8bcb5bae.png">
<img width="1440" alt="screen shot 2016-08-15 at 3 40 54 pm" src="https://cloud.githubusercontent.com/assets/10616227/17677015/e67fefec-62fe-11e6-896d-734da69e281c.png">
<img width="1440" alt="screen shot 2016-08-15 at 3 41 00 pm" src="https://cloud.githubusercontent.com/assets/10616227/17677016/e68180e6-62fe-11e6-8414-b138c8e06f9b.png">

My resolution is 2880x1800. This particular LXQT session was spawned from SDDM. Both SDDM and LXQT run the requisite vmware wrapper to allow VMWare Fusion to dynamically change the resolution on resize.

Arch details:

```
Linux kk-archvm 4.7.0-1-ARCH #1 SMP PREEMPT Mon Aug 8 22:05:58 CEST 2016 x86_64 GNU/Linux
```

**Comment by palinek** [comment]
Is this the same as in #1027?

**Comment by tsujan** [comment]
Yes, this is the same as https://github.com/lxde/pcmanfm-qt/issues/346 and https://github.com/lxde/lxqt/issues/1027: a Qt bug (https://bugreports.qt.io/browse/QTBUG-54384), which isn't fixed yet.

**Comment by isaki-x** [comment]
That bug is for dual monitor setups; this is a single monitor instance.
