### ISSUE TITLE
[Feature Request] customise window control positions + display

### ISSUE THREAD

**Issue by Gibbz** [lxde/lxqt#1122]
would love to see a way to swap window control buttons and toggle their visibility.
Ive been using ubuntu and used to having the close button on the left. 
And to remove the extra clutter from the window frame.

**Comment by Vladimir-csp** [comment]
It is already possible via obconf-qt (if you are using openbox).

**Comment by tsujan** [comment]
This depends on the WM you use and isn't under LXQt's control. For Openbox, for example, do as @Vladimir-csp said.
