### ISSUE TITLE
Desktop: Stretch to fit doesn't work -- it tiles the image

### ISSUE THREAD

**Issue by eriknstr** [lxde/lxqt#1123]
Hello, when I set a background image as "stretch to fit" for my desktop using LXQt version 0.10.0 on Fedora 23, the background image is tiled. It's been like this for quite long now. When I originally installed Fedora 23 with LXQt, "stretch to fit" worked as expected, but some time quite a while ago it stopped working and has been broken ever since that.

**Comment by eriknstr** [comment]
![desktop 1_001](https://cloud.githubusercontent.com/assets/385688/17710068/f36924ec-63eb-11e6-9113-cbc3c761145f.png)

**Comment by palinek** [comment]
see lxde/lxqt#1027
