### ISSUE TITLE
lxqt-policykit "Authentication failed for some reason"

### ISSUE THREAD

**Issue by nbvcxz** [lxde/lxqt#1126]
I have an issue with **lxqt-policykit** agent, which occurs in 2 of distros I use (both Arch Linux - git packages and Ubuntu 16.04 - main repo packages and previously 14.04):
I noticed when I have few users added (and also added to **sudo** group if it matters) when the polkit action is being done (eg. I try to install package with pacaur in Arch Linux only pam or synaptics in Ubuntu with sssd) it starts dialog **Authentication Required** (yes - the ugly unix-user:user_name). The problem is the user_name is not your current user, but the user with lowest uid. Then after ~ 1-2 sec. it appears another dialog with Authentication failed **Authentication failed for some reason**. This makes lxqt-policykit useless for now.
Summarizing: when you use 1 user (or first added user probably) there is no problem. If you have more users and you try to use lxqt-policykit with another user (with higher uid) it uses 1st user and fails.
ps. tried with no polkit agent and legacy gnome polkit agent on Arch Linux (with lxqt) and it works fine (for pacmac-instll it asks about user to select and credentials, then runs program with no issue).
_Issue is like #284  thread_

**Comment by stefonarch** [comment]
Same here (always been, thought it was m, but I think it's not ordered by lowest uuid and neither alfabetically, but   by creation time;  the last added is shown first and the others are ordered by creation time too, I made some test and changing uid does never affect order.

**Comment by aldobelus0** [comment]
I have the same, same problem at my "very free" Trisquel Belenos (7.0), Ubuntu(14.04)-based (if you don't know yet), and I don't know what to do. I started the installation with Gnome as desktop environment, and installed later the LxQt one. 

I always add an user, so I can rescue the system if eventually there's a problem. You can realize that this user have to be with "sudo powers"...if not, it will result useless. 

So, any ideas to solve this problem using this distribution?

**Comment by stefonarch** [comment]
One solution could be activating user root and keep only one user with admin/sudo privileges until this is fixed.

**Comment by aldobelus0** [comment]
And there's no an appropiated solution? 'Cause this looks like a bit "fudge"... With all respect, stefonarch...

**Comment by aldobelus0** [comment]
Well, you said 

> untill this is fixed


but...

**Comment by palinek** [comment]
See if the lxde/lxqt-policykit#24 helps...
