### ISSUE TITLE
Problem with main menu search and app installation

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#1127]
This isn't an important bug but I've seen it several times, both on Debian and on Manjaro.

With `Filter menu entries`, `Show matching entries` and `Hide menu entries while searching` checked, if the search line-edit of the main menu has some text in it, the menu will get scrambled after an app with desktop file is installed or uninstalled. If the text is cleared, the menu will get normal again. The scrambled state is such that the search result is shown on the lower part of the menu, i.e. the menu and the search result are both shown.

**Comment by tsujan** [comment]
A screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/981076/17834342/d4f056da-6750-11e6-99a9-a4a88e748dfe.jpg)

**Comment by palinek** [comment]
Please, check, if lxde/lxqt-panel#367 fixes this.
