### ISSUE TITLE
lxqt-panel: clock is not updating when rotated

### ISSUE THREAD

**Issue by atorkhov** [lxde/lxqt#1128]
Date/time widget on panel does not update the time. It changes only when changing the preferences (for ex. - switch 12/24 hours mode). I'm using version 0.10.0 on Fedora Linux. I have vertical panel and incorrect behaviour is present only when clock is rotated.

**Comment by AdShea** [comment]
This looks to be a repeat of bug [#883](https://github.com/lxde/lxqt/issues/883) which is already closed and is fixed in git.

**Comment by palinek** [comment]
@atorkhov If the problem persists in current master, please, reopen...
