### ISSUE TITLE
No option to disable tap to click in the Input Device Preferences!

### ISSUE THREAD

**Issue by CraftedPixel** [lxde/lxqt#1130]
When I play video games, I touch the trackpad on accident.
Or click on something by accident.
There should be an option to disable tap to click in the Input Device Preferences.

**Comment by tsujan** [comment]
Use
````
synclient TouchpadOff=1
````
You could give it a shortcut. And you could add another shortcut for enabling it:
````
synclient TouchpadOff=0
````

**Comment by CraftedPixel** [comment]
No, I don't want to disable the touchpad all together, I want to disable the touch click. While still being able to move the mouse cursor with the trackpad.

**Comment by tsujan** [comment]
Then use the `-t` option. Please read `man syndaemon`.

**Comment by paulolieuthier** [comment]
`synclient TapButton1=0`

**Comment by stefonarch** [comment]
With 
synclient TouchpadOff=2
Only tapping and scrolling is switched off

**Comment by Vladimir-csp** [comment]
This also should go to #337.
The proper way of doing it via xinput is to set "Synaptics Tap Action":
```
# to list devices
xinput list
#to disable click tap:
xinput set-prop "$YOUR_DEVICE" "Synaptics Tap Action" 0 0 0 0 0 2 3
#to enable click tap:
xinput set-prop "$YOUR_DEVICE" "Synaptics Tap Action" 0 0 0 0 1 2 3
```
The property itself stands for which button to emulate when tapping on: top right corner, bottom right corner, top left corner, bottom left corner, non-corner one finger, non-corner two finger, non-corner three finger

**Comment by pmattern** [comment]
Binaries `synclient` and `synaptics` are geared towards driver `xf86-input-synaptics` only and hence cannot be used with some other driver like `xf86-input-libinput`.
`synclient` is accepting X org options in a modified syntax, e. g. setting `TouchpadOff=2` which was rightly stated above is corresponding to an X option `TouchpadOff 2`.

To figure out which driver is in use you may look for string `Using input driver` in `/var/log/Xorg.0.log`.

Binary `xinput` is adjusting settings by the concept of "Device Properties". It can be used with all drivers `xf86-input-{evdev,libinput,synaptics}` as all or them are supporting the concept (but provide different Device Properties respectively).
The particular Device Properties stated in the previous comment are specific to `xf86-input-synaptics`. If you should happen to use this driver I'd rather go with Device Property `SynapticsOff 2` which just disables tapping but leaves all other settings like they are.

Valid Device Properties can be found out by running `xinput --list` and next `xinput --list-props <device as shown by 'xinput --list'>`.
Also, both X options and Device Properties are very well explained in man pages `<driver>` of section `4`, so you may want to look at e. g. `man 4 libinput`.

That aside this should really go to one of the preexisting issues, probably #92.
