### ISSUE TITLE
Trying to compile 0.10 on Debian jessie fails with an error.

### ISSUE THREAD

**Issue by zor1984qq** [lxde/lxqt#1131]
LIB_SUFFIX=64 ./build_all.sh
./build_all_autotools_projects.sh: 17: ./build_all_autotools_projects.sh: [[: not found
Make job number: 4

Building: libfm extras into <default>

You need gtk-doc to build this package.
http://www.gtk.org/gtk-doc/
Make job number: 4

Building: libqtxdg using externally specified options: -DCMAKE_BUILD_TYPE=debug  -DLIB_SUFFIX=64 

-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Building with Qt 5.3.2
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- 
-- For building tests use -DBUILD_TESTS=Yes option.
-- 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    LIB_SUFFIX

-- Build files have been written to: /home/sergey/git/lxqt/libqtxdg/build
Scanning dependencies of target Qt5XdgIconLoader
[  3%] Building CXX object xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/xdgiconloader.cpp.o                
In file included from /home/sergey/git/lxqt/libqtxdg/xdgiconloader/xdgiconloader.cpp:34:0:                  
/home/sergey/git/lxqt/libqtxdg/xdgiconloader/xdgiconloader_p.h:56:29: fatal error: private/qicon_p.h: Нет такого файла или каталога
 #include <private/qicon_p.h>
                             ^
compilation terminated.
xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/build.make:54: ошибка выполнения рецепта для цели «xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/xdgiconloader.cpp.o»
make[2]: *** [xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/xdgiconloader.cpp.o] Ошибка 1
CMakeFiles/Makefile2:106: ошибка выполнения рецепта для цели «xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/all»
make[1]: *** [xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/all] Ошибка 2
Makefile:137: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

================OR======================================================
~/git/lxqt$ CMAKE_BUILD_TYPE=debug CMAKE_GENERATOR=Ninja CC=clang CXX=clang++ ./build_all.sh
./build_all_autotools_projects.sh: 17: ./build_all_autotools_projects.sh: [[: not found
Make job number: 4

Building: libfm extras into <default>

You need gtk-doc to build this package.
http://www.gtk.org/gtk-doc/
Make job number: 4

Building: libqtxdg using externally specified options: -DCMAKE_BUILD_TYPE=debug   -G Ninja -DCMAKE_MAKE_PROGRAM=ninja

-- The C compiler identification is Clang 3.5.0
-- The CXX compiler identification is Clang 3.5.0
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Building with Qt 5.3.2
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- 
-- For building tests use -DBUILD_TESTS=Yes option.
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sergey/git/lxqt/libqtxdg/build
[1/32] Building CXX object xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/xdgiconloader.cpp.o
FAILED: /usr/bin/clang++   -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_URL_CAST_FROM_STRING -DQT_SVG_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQt5XdgIconLoader_EXPORTS -std=c++11 -fno-exceptions -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.3.2 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.3.2/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.3.2 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.3.2/QtCore -IInTreeBuild/include/qt5xdgiconloader -IInTreeBuild/include -IInTreeBuild/include/qt5xdgiconloader/1.3.0 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets    -Wall -MMD -MT xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/xdgiconloader.cpp.o -MF xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/xdgiconloader.cpp.o.d -o xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/xdgiconloader.cpp.o -c ../xdgiconloader/xdgiconloader.cpp
In file included from ../xdgiconloader/xdgiconloader.cpp:34:
../xdgiconloader/xdgiconloader_p.h:56:10: fatal error: 'private/qicon_p.h' file not found
#include <private/qicon_p.h>
         ^
1 error generated.
ninja: build stopped: subcommand failed.

I also used experimental debian repository but can't install qt5-default qt5-qmake from it since qtchooser package has version conflicts and if I trying to remove it to install new it wan't to remove to much packages so it can damage whole system and I can not afford it since then more simple way is to upgrade whole system to stretch and got these components out of the box.

An /etc/apt/sources.list entry for experimental is:
deb http://httpredir.debian.org/debian experimental main

 I did all these kind of things so I update everything 100% and everything fine and updated:
git clone --recursive https://github.com/lxde/lxqt
cd lxqt
git submodule init
git submodule update --remote --rebase
git submodule foreach git pull --rebase

The problem is the experimental debian repository does not contain for now following package libkf5guiaddons-dev. There is simple no such package but anyway error is related to these file:
In file included from ../xdgiconloader/xdgiconloader.cpp:34:
../xdgiconloader/xdgiconloader_p.h:56:10: fatal error: 'private/qicon_p.h' file not found
#include <private/qicon_p.h>

I think I already did installed all of the lxqt dependencies but not sure for 100% since 
dpkg-checkbuilddeps: giving me error of  debian/control: no such file or catalog.

I really giving up since I already readen 3 web pages of guides and README.md + and build_all.sh instructions + tons of man pages through these process:
https://github.com/lxde/lxqt
https://github.com/lxde/lxqt/wiki/Building-From-Source
https://wiki.debian.org/DebianExperimental

$ LIB_SUFFIX=64 ./build_all.sh
# or
# $ CMAKE_BUILD_TYPE=debug CMAKE_GENERATOR=Ninja CC=clang CXX=clang++ ./build_all.sh

Now I try to combine these two to look further but really think it wont help since these file is simply missing:

In file included from ../xdgiconloader/xdgiconloader.cpp:34:
../xdgiconloader/xdgiconloader_p.h:56:10: fatal error: 'private/qicon_p.h' file not found
#include <private/qicon_p.h>

Call for help but no hope for solving these problem on jessie, I think for 0.10 is better way to just wait for siduction repository updates that already have in my sources.list with 0.9 lxqt installed. Or moving to stretch or any none stable rolling debian version since these needed packages was already presented there in debian main repo's...

**Comment by zor1984qq** [comment]
apt search libxdg gives the following on these package
libqt5xdgiconloader-dev/experimental 1.3.1~50-g4fde773-4 amd64
  Development files for libqtxdgiconloader

it was properly installed from experimental but gives the same error even on stable version of these package.

**Comment by agaida** [comment]
../xdgiconloader/xdgiconloader_p.h:56:10: fatal error: 'private/qicon_p.h' file not found

apt-file search private/qicon_p.h - please make sure that all build dependencies are installed - to be true i would not recommend to build LXQt in debian that way - get the sources and rebuild  the packages seems like a better idea. At least i would try it that way.

**Comment by szg0000** [comment]
`apt-get install qtbase5-private-dev`

**Comment by GermanAizek** [comment]
for Qt6 need: `apt install qtbase6-private-dev`
