### ISSUE TITLE
Adopt Release Schedule

### ISSUE THREAD

**Issue by maverick74** [lxde/lxqt#1132]
This is a proposal for discussion:

As LXQt is getting better and better i believe that would be good to have a Release Schedule. 
Something that would work whit the time developers have (since this is done in their free time) but that would allow distros to plan implementations (and avoid anxiety from them and from users as well).

E.g.: 
a) Every month of _______
b) Every month _______ for a major release followed by a bug-fixer release (X months later)
c) Twice a year (Every _______ and _______)
d) ...

Ideas? (no aggressions allowed :P )

**Comment by intialonso** [comment]
Is a nice idea, but the project is lacking man power and setting fixed
dates for releases will not guarantee the release. On the other hand is
true that many users are thinking that LXQT is dead or inactive (take a
look at reddit or phoronix),maybe we can make unstable development
snapshots as some kind of preview releases, just to keep the people
interested. Somethink like LTS vs development. (Well thats what PPAs and
AUR are for, but something more official?)

We need to reclute people! I called for artist sometime ago in Reddit, but
didnt get any answers:(

2016-08-31 11:37 GMT-05:00 maverick74 <notifications@github.com>:

**Comment by jleclanche** [comment]
I used to do a lot of outreach but I don't have the time for it anymore.

I agree with @intialonso, setting fixed dates doesn't just make releases happen. I tried calling for releases multiple times this round and it's not happening.

I put @agaida in charge of releases and coordination the other day but you guys will need to help him as well. Post on reddit, communicate with the users, and yeah we should absolutely do releases simply more frequently, be less scared of releasing even with "fewer" features.

**Comment by maverick74** [comment]
My humble 2 cents as a simple "user":

I  - personally - prefer to have a release where just one bug is fixed or just one new feature is implemented, than not having any release at all.

It doesn't mean that developers have to change much of their life or that they'll be forced to give more than what they're already giving (which is very much already and everyone should be thankful for all your "free" work!!!). But from my point of view a new release with, for example just one simple bug fixed, has a lot of good things:

a) it shows the project is not dead (as already mentioned)
b) the persons affected by that bug will be happy (even if it's just one guy)
c) it will be mentioned in a few websites > which will get noticed by viewers, from which some might get interested enough to help > which might help the project grow...


So, new releases keeps the flame burning, gives users hope and gets some publicity. I think it's a nice trade (weighing against the work that has to be done to get a new release out...)

**Comment by micrococo** [comment]
Hi.

As a former LXDE packager, I'd like to have some kind of release cycle. Too spaced releases lead to packagers adding a lot of bug fix patches on top of the stable release version if they cannot submit full snapshots of the packages (as it was my case). On the long run this becomes very annoying (I remember a package with more than 30 patches fixing different bugs), so a release cycle of 3 or 4 months would be ideal in my opinion. You can call it a bug fix release and increase just the minor version numbers, and eventually you can bump to a new mayor version when it is considered that it is the moment. No releases for a long time lends to "the project is dead" comments. It happened with LXDE even when it had an amazingly fast development pace thanks to Andriy because even then releases were sparse.

In brief, release frequently even if the changes are not big. Packagers (and end users) will appreciate.

Greetings.

**Comment by agaida** [comment]
First: We will have a release soon - second - we should will release more often in the future. I'm against a Release Schedule right now, but we should try to release more often. As i wrote - we will.

**Comment by maverick74** [comment]
I honestly believe most people don't even read the changes between versions!
If there is a new version than it means something got improved even if it is a small bug or a small feature. Users, i believe, love when things get better (even when they don't know what has actually become better :p)

Of course there's those exceptional new features that really have an impact (e.g.: the new 0.11 search feature in the menu) and that really get users attention...

I really think LXQt needs to say everyone: "hey i made this" and "oh, i fixed that" (basically: "we're alive and kicking") more frequently

My point: I totally agree whit @micrococo. Frequent releases would be much much better even if the changes are "just a small dot".
Now, i don't have a clue about the work developers have to put together a new version and i think that is what will approve or invalidate this idea... (sorry for adding more 2cents - i'll try to shut up now... :)

**Comment by someguy27** [comment]
i don't think without a release schedule you'll get anywhere, to be honest.
v0.10 was released almost a year ago now and v0.11 is tied for just one bug which don't even has an owner.
it was supposed to get released months ago and we still have nothing out...
this will keep going and the project will sadly die this way. But that's just my opinion... we shall wait and see... :(

**Comment by agaida** [comment]
we all will die sooner or later - but before we will have a release or two

**Comment by paulolieuthier** [comment]
I think we should at least aim at a 6-month cycle.

**Comment by jleclanche** [comment]
@someguy27 the release is ready, and has been ready for a long time. I can't do releases anymore though, I don't have the time, so *right now* it's blocked on a release maintainer stepping up or more people helping.

**Comment by paulolieuthier** [comment]
I'd do the release. I'm waiting on the last bug to be fixed.

**Comment by yan12125** [comment]
I guess "the last bug" refers to #973?

**Comment by paulolieuthier** [comment]
Yes, it's the last remaining bug in the milestone list.

**Comment by yan12125** [comment]
Thanks!

**Comment by maverick74** [comment]
> I think we should at least aim at a 6-month cycle.

This would be good.

@paulolieuthier now that the last bug was fixed, is there any ETA for v0.11?

**Comment by paulolieuthier** [comment]
Next days. If you want to make it happen sooner, yell it to @agaida. 😉

**Comment by jubalh** [comment]
Yay! Last bug fixed! :)

**Comment by maverick74** [comment]
@paulolieuthier i prefer to wait!!! He seems to have bad temper ahahah (Just joking! No offence meant!) ;)

**Comment by agaida** [comment]
@paulolieuthier but you know this very special and ancient rule: Any question about an eta adds a minimum of one week to the eta ... :D

**Comment by palinek** [comment]
>Yay! Last bug fixed! :)

Are we going to move some other to 0.11milestone? :-)
