### ISSUE TITLE
FreeBSD power. (liblxqt lxqtpowerproviders.cpp)

### ISSUE THREAD

**Issue by jsm222** [lxde/lxqt#1133]
Poweroff and reboot (by lxqt-leave) has not been working on the BSDs. I've been looking briefly into it, and I have a working [hack](https://gist.github.com/jsm222/97a06c04a34dc89ee798625b0ae09941) for FreeBSD. I cannot find a way to test whether the actions are available, so I just return true in canAction of the `ConsoleKitProvider::canAction`. Then since systemd is not on FreeBSD I use dbuscall instead of dbusCallSystemd. The commands on FreeBSD are restart and stop and not reboot and poweroff. They can be tested with  
`dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart`

`dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop`

```
dbusCall(CONSOLEKIT_SERVICE,
                    CONSOLEKIT_PATH,
                    CONSOLEKIT_INTERFACE,
                    QDBusConnection::systemBus(),
                    command)
```
This is just FYI, I hope this issue can be resolved in an elegant way. Does anybody no a way to test via dbus/programmatically if an action is able to be performed, and that the user is permitted to perfom it...?

**Comment by paulolieuthier** [comment]
Hi, @jsm222. I'm really excited to see/get LXQt working well on the BSDs. For what I can see, you are using the original ConsoleKit, right? The project is dead for three years now. LXQt supports SystemD and ConsoleKit2, a ConsoleKit fork. Is it possible to install ConsoleKit2 and try again?

**Comment by jsm222** [comment]
Yes it was an old one, was not aware of the two console kits .. Xfce seems to have a port of ConsoleKit2 : https://subversion.assembla.com/svn/xfce4/trunk/sysutils/consolekit/ and https://wiki.freebsd.org/Xfce?highlight=%28ConsoleKit2%29 see the FAQ. I will give that one a try.

**Comment by jsm222** [comment]
@paulolieuthier It does indeed work with ConsoleKit2 ported by Xfce. It just needs a rules file for regular users to be authorized for the power actions. 
I have supplied an example here, allowing members of wheel to stop and restart the system (my desktopboard does not hibernate well so i did not add that):
The path is  
/usr/local/share/polkit-1/rules.d/
and the name is 10-system-power.rules
```
if(action.id == "org.freedesktop.consolekit.system.restart" || action.id == "org.freedesktop.consolekit.system.stop") {  
 if (subject.isInGroup("wheel")) {
        return polkit.Result.YES;
    }
 }
});

```

**Comment by paulolieuthier** [comment]
It's a shame this is not used by default. We need to create a wiki page for that. Closing this.
