### ISSUE TITLE
no conexion with http://pootle.lxde.org/

### ISSUE THREAD

**Issue by bakeiro** [lxde/lxqt#1134]
Try to colaborate with translation at [pootle.lxde](http://pootle.lxde.org/) but i simply cant create account and login in, so in cant help with translations, also for foundation.lxde.org or join.lxde.org... are broke liks (all the liks at [pootle.lxde](http://blog.lxde.org/)  )

**Comment by pmattern** [comment]
Basically pootle.lxde.org has never really been working. It's an issue we badly need to address but as such well-known.

To help with translations we can only offer a manual approach for now which is described in wiki page [Translation](https://github.com/lxde/lxqt/wiki/Translation).
