### ISSUE TITLE
custom action sub-menu only displays one item

### ISSUE THREAD

**Issue by seefenix** [lxde/lxqt#1135]
After numerous attempts, following examples, using Nautilus-Actions Configuration Tool
I tested the sub-menu in pcmanfm and it works as expected.
Actions do work and show up as expected, only the submenu is not working as expected.

this is what happens

[Desktop Entry]
Type = Menu
Name = Menu
Icon = arrow-right  <--- custom icon works
ItemsList = action1; action2;

Menu
  -> action2

Note: last item is displayed

----------

What is expected, and shows up in pcmanfm:

Menu
  -> action1
  -> action2

Desktop is lxqt,
pcmanfm-qt version 0.10.0

**Comment by tsujan** [comment]
Yes! I saw the same thing last year: submenu actions didn't work, so I used simple actions. I forgot to report this bug because there were several important bugs that I wanted to fix (and fixed).

The bug may be in libfm. It seems that many LXQt users aren't aware of custom actions and their power!

**Comment by tsujan** [comment]
Found the cause. Will make a PR. The problem is in libfm-qt.

@seefenix, thanks for reminding me of this!
