### ISSUE TITLE
Main Menu Is Not Updated Properly

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#1137]
I explain this bug with an example:

I uninstalled lxqt-session inadvertently and, after a few minutes, reinstalled it. But log-out, shut-down and the other related icons didn’t show up in the `Leave` submenu; in fact, although the `Leave` menu-item existed, it had no submenu. I fixed the issue by removing an item from `~/.local/share/applications` and then, readding it.

I remember that this problem has occurred several times before.

**Comment by pmattern** [comment]
If I'm not mistaken this a duplicate of #65.

**Comment by tsujan** [comment]
> If I'm not mistaken this a duplicate of #65.

You're right.
