### ISSUE TITLE
battery widget in panel widgets not found

### ISSUE THREAD

**Issue by finjulhich** [lxde/lxqt#1139]
I use fedora-lxqt 24 spin, and I cannot find anymore the battery status widget for lxpanel.
It used to work before.

**Comment by paulolieuthier** [comment]
There is no battery widget. You'll have to run lxqt-powermanagement, which adds an icon to your status notifier (or system tray) plugin.

**Comment by finjulhich** [comment]
I see lxqt-powermanagement running indeed, yet I don't any icon in the panel (in the bottom of the screen: I have it on auto-hide)
What is the "status notifier" or "system tray" plugin? How do I see if it is "running" ?

**Comment by paulolieuthier** [comment]
Open lxqt-powermanagement's settings and mark the option "Show icon". Then, right-click a unused area in lxqt-panel and select "Manage widgets". There you'll be able to see (or add) both the system tray and the status notifier plugins.

**Comment by pmattern** [comment]
> What is the "status notifier" or "system tray" plugin?

→ https://github.com/lxde/lxqt-panel#status-notifier-plugin-plugin-statusnotifier--system-tray-plugin-tray

> How do I see if it is "running" ?

Open the dialogue mentioned by @paulolieuthier. There you'll see which plugins (widgets) are running. Also, you can ad plugins and place all which are running at a particular position within the panel.

**Comment by finjulhich** [comment]
hmm, I see the "system tray" and the "notifier" plugin but they are both sort of greyed out and I can't select and add them. There's a comment "only one instance can run at a time"

**Comment by pmattern** [comment]
Then both are already running (which is the default) and you should select "Widgets" in the dialogues left to look where they are in your panel.

**Comment by finjulhich** [comment]
yes i see lxqt-panel running.
That is very strange: This is the currently selected list of widgets when I select "Widgets"
Application Menu
Task Manager
CPU Monitor
Network Montior
Volume Control
Date & Time

but I don't see "system tray" nor "system notifier"
ANd when I go to add them, they're colored differently as I said.

**Comment by pmattern** [comment]
Well, then I'd say there's something seriously screwed on your system. You could quit the LXQt session, remove `~/.config/lxqt` of the user in question as root and start over.
Of course all your *LXQt* configuration is lost that way but it is probably the quickest way to figure out what's wrong.

**Comment by finjulhich** [comment]
will try, thanks

**Comment by pmattern** [comment]
Both plugin statusnotifier and tray are behaving exactly as expected running Fedora 24 and LXQt from Fedora's official repositories here. I cannot test the battery icon as this is in a virtual machine only which isn't featuring a battery. Yet it seems pretty obvious that the problem you're facing is affecting your particular system only.

Thus closing as invalid to indicate there's nothing to do at our side. You're still free to post additional comments or questions here.
