### ISSUE TITLE
LXtask does not handle unknown uid

### ISSUE THREAD

**Issue by jucrouzet** [lxde/lxqt#1141]
Process running under an unknown (not in passwd) uid show some strange text in the User column : 

![virtualbox_2016-09-14_19-21-19](https://cloud.githubusercontent.com/assets/471070/18522500/9b8d1f86-7ab0-11e6-81c3-6d729e2f703f.png)

In this example, postgresql is running in a docker container (that's why the uid is unknown)

**Comment by agaida** [comment]
lxtask is no part of LXQt

**Comment by jubalh** [comment]
@jucrouzet I am not familiar with LXDE. But maybe you were looking for https://sourceforge.net/p/lxde/bugs/
