### ISSUE TITLE
liblxqt WITH_XDG_DIRS_FALLBACK requires qt >=5.6

### ISSUE THREAD

**Issue by jsm222** [lxde/lxqt#1143]
I found the following in [liblxqt b1b249e](https://github.com/lxde/liblxqt/commit/b1b249e5e7aa7f85dd929ae4d0d32b50316aa774)
While the wiki states that QT 5.4 is the minimum.

> Qt version ≥5.4 is required

https://github.com/lxde/liblxqt/blob/b1b249e5e7aa7f85dd929ae4d0d32b50316aa774/lxqtsettings.cpp#L68 uses rend and rbegin, which [is QT 5.6 only](http://doc.qt.io/qt-5/qlist.html#rend)
I had to manually set 
`option(WITH_XDG_DIRS_FALLBACK "Use our XDG_CONFIG_DIRS fallback" OFF)`
in CMakeLists.txt. Furthermore `#include <cerrno>` is missng in lxqtapplication.cpp

**Comment by palinek** [comment]
Addressed in lxde/liblxqt@5942c3b and lxde/liblxqt@686212f0d
