### ISSUE TITLE
LXQt-panel fails build

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#1145]
Recompiled all components except panel:`error:

>  [ 96%] Building CXX object panel/CMakeFiles/lxqt-panel.dir/pluginmoveprocessor.cpp.o
> /home/stef/git/lxqt-panel/panel/pluginsettings.cpp: In constructor ‘PluginSettings::PluginSettings(LXQt::Settings*, const QString&, QObject*)’:
> /home/stef/git/lxqt-panel/panel/pluginsettings.cpp:66:28: error: ‘settingsChangedFromExternal’ is not a member of ‘LXQt::Settings’
>      connect(d->mSettings, &LXQt::Settings::settingsChangedFromExternal, this, &PluginSettings::settingsChanged);
>                             ^~~~
> make[2]: *** [panel/CMakeFiles/lxqt-panel.dir/build.make:231: panel/CMakeFiles/lxqt-panel.dir/pluginsettings.cpp.o] Error 1

related to https://github.com/lxde/lxqt/issues/156 https://github.com/lxde/lxqt-config/pull/103

**Comment by pmattern** [comment]
Did you re-compile *all* LXQt components? I'm asking as I happened to recompile them just some minutes ago and did not run into that error.

**Comment by stefonarch** [comment]
First  I updated the 2 AUR packages whcih were released, than I ran my script that updates other  packages via  AUR, all got the version error 1.3><2.0 m than I started to build manually from git in different orders, from git I compiled libqtxdg, libsysstat, config, liblxqt, common, config, pcman-qt and libfm several times in different order.  I'll build the rest from source and retry.

**Comment by stefonarch** [comment]
Compiled everything now directly from source, same error. 
I'm updating arch now, but I don'think it helps.

**Comment by jubalh** [comment]
For openSUSE Tumbleweed all the git packages compile and work without any problem.

**Comment by palinek** [comment]
My two cents...cmake does cache many things in the build directory. You can try to remove the build dir completely and try to build/compile from scratch

**Comment by stefonarch** [comment]
my script does rm -r build && mkdir build ...
`#! /usr/bin/bash

for i in \
        liblxqt/ \
        libqtxdg/ \
        lxqt-common/ \
        lxqt-runner/ \
        libfm-qt/ \
        lxqt-config/ \
        pcmanfm-qt/ \
        lxqt-policykit/ \
        libsysstat/ \
        lxqt-notificationd/ \
        lxqt-appswitcher/ \
        lxqt-sudo/ \
        lxqt-session/ \
        lxqt-panel/ \
        lxqt-globalkeys/ \
        lxqt-powermanagement/ \
        lxqt-qtplugin/ \
        lxqt-admin/ \
        translations/

do
        cd $i echo $i && git fetch origin && git merge origin/master && rm -rf build && mkdir build && cd build && cmake ..  -DCMAKE_INSTALL_PREFIX=/usr  -DCMAKE_BUILD_TYPE=Debug && make -j5 && sudo make install && cd ../../
/tmp/update-from-lxqt.log
done
`

**Comment by stefonarch** [comment]
After compiling lxqt-panel in /tmp and it stopped there even  at 65% I cloned everything in a new directory and this time all compiled well.

**Comment by pmattern** [comment]
This
```
for i in \
liblxqt/ \
libqtxdg/ \
```
should be changed. `liblxqt` is depending on `libqtxdg` so following this order it is compiled against the preexisting version of the latter.

**Comment by stefonarch** [comment]
I noticed that too yesterday, I thought liblxqt was base dependency, thanks.

**Comment by pmattern** [comment]
Btw. an overview about the order is currently available [here](https://github.com/lxde/lxqt/wiki/Building-from-source#compiling).
