### ISSUE TITLE
plugin-volume: Two issue in dependency checking

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#1148]
There does not seem to be any dependency checking of OSS. 
OSS support is always declared as available by plugin-volume's UI, even when the panel was compiled on systems which completely lack support of OSS.
This should be handled the same way as Alsa and PulseAudio, the dependencies of which are checked and which do not appear in the UI when support wasn't compiled in plugin-volume. 

When Alsa or PulseAudio are disabled by setting `-DVOLUME_USE_ALSA=OFF` or `-DVOLUME_USE_PULSEAUDIO=OFF` the corresponding messages in CMake's summary are

```
-- Volume plugin will be built
--     ALSA:
--     PulseAudio:
```

IMO this isn't meaningful and it would be better to display `FALSE` as counterpart of `TRUE` that's displayed when support of those backends is built in.

**Comment by agaida** [comment]
GTM
