### ISSUE TITLE
Scroll wheel in task manager panel cycles windows instead of restoring or minimizing

### ISSUE THREAD

**Issue by alexhenrie** [lxde/lxqt#1149]
In LXDE, when I hovered over a button in the task manager panel and flicked the scroll wheel up, the corresponding window was restored. When I flicked the scroll wheel down, the window was minimized. I really liked this; the gestures were quick and easy on my laptop's touchpad. Now the scroll wheel just moves between windows, and there doesn't seem to be a way to get the old behavior back or disable it. If I want to cycle through windows I'll use Alt+Tab, so it's a shame that I can't just point at the window I want and flick anymore.

**Comment by palinek** [comment]
Sorry, but from my point of view, there is no benefit to raise the window by scrolling. Window can be raised by single (left)click.

**Comment by alexhenrie** [comment]
@palinek If using the scroll wheel to restore a window makes no sense, using the scroll wheel to flip through windows makes even less sense. Can we compromise and have the scroll wheel do nothing?

**Comment by palinek** [comment]
> Can we compromise and have the scroll wheel do nothing?

Of course... there is a PR on the way, see lxde/lxqt#379

**Comment by alexhenrie** [comment]
I'm sorry, I don't see what lxde/lxqt#379 has to do with this.

**Comment by palinek** [comment]
Sorry ... bad link, updated

**Comment by palinek** [comment]
The mentioned PR was merged. @alexhenrie, is it enough to close this?

**Comment by alexhenrie** [comment]
Yep, that's fine. Thanks!
