### ISSUE TITLE
Tag LXQt 0.11.0

### ISSUE THREAD

**Issue by Conan-Kudo** [lxde/lxqt#1151]
Some tools are tracking released versions of the desktop by tracking the Releases of this project. Please tag 0.11.0 here after updating all the submodules.

**Comment by pmattern** [comment]
This sounds like something we probably should do, yes.

But there's one thing in your post I found confusing:
> after updating all the submodules.

By that you mean that this repository should be tagged after a new release of the various parts of LXQt was made in their respective repository like github.com/lxde/lxqt-{about,admin,config,...}, right? I'm asking as term "submodule" refers to git here and the submodules of repository github.com/lxde/lxqt aren't normally updated in the repository itself but only in local checkouts.

**Comment by Conan-Kudo** [comment]
@pmattern Oh, I thought the submodules were usually updated to match their latest releases when it is tagged...

**Comment by agaida** [comment]
@Conan-Kudo - the submodules are fine. Thats the nature of git. Please have a look at https://github.com/lxde/lxqt/commit/d4081609e58d5c96418c5b58d289be2b2cd55f37

**Comment by agaida** [comment]
@Conan-Kudo - but anyways - thanks for pointing us on the missed tag. I will tag and close this now.

**Comment by paulolieuthier** [comment]
That's the nature of git, but we could update them at least to match releases. Most of them are pointing to 2 years old code.
