### ISSUE TITLE
Localization - pavucontrol-qt Czech translation completion

### ISSUE THREAD

**Issue by pafri** [lxde/lxqt#1157]
After the new release of LXQt I´ve noticed the occassion to complete the translation file for pavucontrol-qt.

Please commit the file.

[LXQt - pavucontrol.zip](https://github.com/lxde/lxqt/files/495722/LXQt.-.pavucontrol.zip)

Best regards, Pavel Fric

**Comment by palinek** [comment]
Submitted as PR lxde/lxqt-l10n#88. Let the (optional) discussion be there...
