### ISSUE TITLE
lxqt-rc.xml is not used by openbox

### ISSUE THREAD

**Issue by renegat** [lxde/lxqt#1161]
4.7.5-1-ARCH x86_64 GNU/Linux
libfm-qt 0.11.1-1 (lxqt)
liblxqt 0.11.0-2
lximage-qt 0.4.0-1 (lxqt)
lxqt-about 0.11.0-5 (lxqt)
lxqt-common 0.11.0-1 (lxqt)
lxqt-config 0.11.0-2 (lxqt)
lxqt-globalkeys 0.11.0-1 (lxqt)
lxqt-notificationd 0.11.0-1 (lxqt)
lxqt-openssh-askpass 0.10.0-3 (lxqt)
lxqt-panel 0.11.0-1 (lxqt)
lxqt-policykit 0.11.0-1 (lxqt)
lxqt-powermanagement 0.11.0-1 (lxqt)
lxqt-qtplugin 0.11.0-1 (lxqt)
lxqt-runner 0.10.0-5 (lxqt)
lxqt-session 0.10.0-4 (lxqt)
lxqt-sudo 0.11.0-1 (lxqt)
openbox 3.6.1-3 (lxde lxde-gtk3 lxqt)
pcmanfm-qt 0.11.1-1 (lxqt)
qterminal 0.7.0-1 (lxqt)
qtermwidget 0.7.0-1 (lxqt)

On first start of LXQt 0.11 the lxqt-rc.xml is created in ~./.config/openbox as described in the release note as copy of  ~./.config/rc.xml if it exists.
But it is totally useless: Every change made to this file is ignored by openbox which continues to use rc.xml only.
Any changes made with obconf are still written to rc.xml not lxqt-rc.xml.
Removing rc.xml will result in opbenbox creating a new rc.xml.

Expected behaviour:
Changes made to openbox settings while using LXQt should be written to lxqt-rc.xml only and not to the openbox settings file rc.xml.

**Comment by palinek** [comment]
A quick workaround for you can be: create a sym link `rc.xml -> lxqt-rc.xml`

**Comment by stefonarch** [comment]
Confirmed but only with official arch packages, I guess it's the fault of lxqt-session 0.10.0-4 , git checkout works as espected.

**Comment by pmattern** [comment]
> I guess it's the fault of lxqt-session 0.10.0-4

Exactly.
Among other the LXQt specific configuration of Openbox involves binary `lxqt-session` of [lxqt-session](https://github.com/lxde/lxqt-session). Package lxqt-session was upgraded to 0.11 in Arch Linux community with delay hence the problem which reproducibly ceases after upgrading to current master or 0.11.
