### ISSUE TITLE
Move common cmake things to lxqt-build-tools

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#1164]
Reasons: The translation scripts, some compiler settings and similar things should be in a separated small tools (scripts) package. It would ease the development and take away some pain from distribution packagers. Far more important it would prevent build dependencies to liblxqt esp in obconf-qt, compton-conf, pcmanfm-qt and so on.

@luis-pereira  @palinek @paulolieuthier @PCMan - What do you think?

**Comment by PCMan** [comment]
Good idea, but the name is a little bit misleading.
It's not quite obvious what the package does.

**Comment by pmattern** [comment]
> Good idea, but the name is a little bit misleading.
It's not quite obvious what the package does.

Exactly my thoughts. How about something like `lxqt-build-tools`?

**Comment by agaida** [comment]
i borrowed the name from debian kde - on debian systems: apt show pkg-kde-tools
So i'm not insist on the proposed name :)

**Comment by agaida** [comment]
lxqt-build-tools is fine i think

**Comment by luis-pereira** [comment]
@agaida I'm in favor. Actually that was my initial idea.  @jleclanche pointed out that packager hated that kind of stuff. I'm no packager, so it stayed the way it is today.
`lxqt-build-tools` is fine to me.

**Comment by PCMan** [comment]
+1 on lxqt-build-tools.
@luis-pereira I don't think packagers hate it that much.
With this, it's quite clear that the package is a "build-time" dependency rather than a runtime one.
In our current condition, packagers tend to set dependency on liblxqt for all packages that use it during compilation. Having to check which packages only need liblxqt on compile-time and which ones require it during runtime can be very annoying to the packagers. It's definitely better to have a separate package for it and that's also what gnome and KDE did.

**Comment by agaida** [comment]
For the packaging thing: The current situation was: We had to release liblxqt first - only after that we was able to release normally independent packages like obconf, compton, pcmanfm, qterm* - because we needed the scripts in the library package. Not the best situation. Regardig the packager; But both sides are true in that case - most packagers really hate micro packages, complex dependencies and so on. But i guess in this special case they will love it :)

**Comment by palinek** [comment]
I'm also a fan of lxqt-build-tools...

**Comment by agaida** [comment]
ok, the repo is created - initial load is the cmake stuff from liblxqt - History is cleaned up

I don't know if i set all the normal settings proper, so it would be good if someone could check this

**Comment by paulolieuthier** [comment]
Checked. Can we close this?

**Comment by agaida** [comment]
yes

**Comment by pmattern** [comment]
This repository doesn't compile yet and so far the components it features were copied only but not scrubbed from the repositories they belonged to before.
Not sure whether it was such a good idea to close this already.

**Comment by luis-pereira** [comment]
@pmattern I think it should stay open as lxqt-build-tools is not usable yet.
I'm working on it.

**Comment by pmattern** [comment]
> I think it should stay open as lxqt-build-tools is not usable yet.

That was exactly my point when sending the previous comment. No hurry or anything. But this issue should be closed only when the new repository is fully implemented and working as expected.

**Comment by luis-pereira** [comment]
Taking shape [here](https://github.com/lxde/lxqt-build-tools/tree/make-it-work)

**Comment by paulolieuthier** [comment]
Sure, sorry. I thought only a repository settings check was missing. I haven't followed this one.

**Comment by luis-pereira** [comment]
Finished by https://github.com/lxde/lxqt-build-tools/commit/6ef6ecfc775332477e3f0ecf25027064b50c7eef.
