### ISSUE TITLE
lxqt-config does not compile anymore

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#1166]
Stops at 

> lrelease error: Unexpected tag at /home/stef/git/lxqt-config/lxqt-config-input/translations/lxqt-config/lxqt-config-input/lxqt-config-input_fr.ts:222:20
make[2]: *** [lxqt-config-input/CMakeFiles/lxqt-config-input.dir/build.make:123: lxqt-config-input/lxqt-config-input_fr.qm] Error 1

https://github.com/lxde/lxqt-l10n/pull/93
(opened first in lxqt-l10n, but it does not show up in https://github.com/lxde/lxqt/issues)

**Comment by PCMan** [comment]
Already fixed.
