### ISSUE TITLE
No way to check errors in translation files pushed into lxqt-l10n

### ISSUE THREAD

**Issue by PCMan** [lxde/lxqt#1167]
After the migration to the new translation infrastructure, we encountered some failure to build caused by incorrect file formats of the *.ts files. In the past, the *.ts files are part of the build process of each package so it's easy to check if the files are well-formed. Now since the *.ts files are put outside the source tree, there is no easy way to test the newly contributed *.ts files.
We need some kind of git commit hooks to run lrelease or other Qt linguist tools to ensure that the translation files contain no errors.
@palinek @luis-pereira @jleclanche any good ideas?

**Comment by palinek** [comment]
How is that? The l10n repo can be built on its own (the build process consists of creating the .qm files...).

The recent problems/build failures/ was my fault as i didn't check sucessfulness of the build process before merging the PRs. Sorry for inconvenience...

**Comment by paulolieuthier** [comment]
@palinek the idea is to automate the validity check of the translation files. Maybe Travis can do it for each PR.

**Comment by palinek** [comment]
> the idea is to automate the validity check of the translation files. Maybe Travis can do it for each PR.

I don't think @PCMan did mean that. But we can set the Travis CI easily. Do we want it?

**Comment by paulolieuthier** [comment]
IMHO we do (or should).

**Comment by agaida** [comment]
we shoulld

**Comment by luis-pereira** [comment]
@palinek We should.

**Comment by palinek** [comment]
done in lxde/lxqt-l10n#96
