### ISSUE TITLE
LXQt, can't use META+E as global shortcut?

### ISSUE THREAD

**Issue by talbym** [lxde/lxqt#1168]
I would like to use META+e (using the small letter "e"; but the issue is with both: META+E and META+e) as my global shortcut to open my editor of choice. But in the Shortcut Keyboard Settings this key combination cannot be registered. Many others (i.e. META+f for opening PCManFM-qt) do work. Why is META+e not allowed? Or, even of more importance to me: How can I make this shortcut META+e work for me?

I run a fresh Debian Stretch (= Debian Testing) or a fresh SparkyLinux system. I can confirm that on both systems (original Debian, or the SparkyLinux flavoured Debian Testing) the META+e combination is not allowed.

LXQt Desktop Toolbox - Technical Info<p>
  Version:                0.10.0
  Qt:                     5.6.1
  Build type:             Release
  System Configuration:   /etc/xdg
  Share Directory:        /usr/share/lxqt
  Translations:           /usr/share/lxqt/translations<br>
/home/mm/.local/share/lxqt/translations<br>
/usr/local/share/lxqt/translations

User Directories
  Xdg Data Home:          /home/mm/.local/share
  Xdg Config Home:        /home/mm/.config
  Xdg Data Dirs:          /home/mm/.local/share:/usr/local/share:/usr/share
  Xdg Cache Home:         /home/mm/.cache
  Xdg Runtime Home:       /run/user/1000
  Xdg Autostart Dirs:     /etc/xdg/autostart
  Xdg Autostart Home:     /home/mm/.config/autostart

**Comment by palinek** [comment]
What window manager are you using? Isn't the said shortcut already registered by WM?

**Comment by talbym** [comment]
I am using openbox, no compton. Wouldn't know by now how (where) to check for openbox shortcuts. At least applying META+e has no obvious effect. It appears to be not in use, but maybe it is jsut that I do not see its effect.

**Comment by stefonarch** [comment]
They are in ~/.config/openbox/rc.xml (in lxqt.xml in actual version)
But you should get a messagge that it is already in use.

**Comment by talbym** [comment]
Thanks! Indeed, the shortcut was registered alreay by openbox (~/.config/openbox/rc.xml). It originally tried to call Konquerer, but as I do not have Konquerer installed, it was failing to load Konquerer. I thought it would not do anything. Actually, it even throws an error message which I have ignored. Please excuse my bad attention to this, don't know why I didn't mention that message when writing about my issue, I so far ignored it because thinking it would just mean that META+e is by now not defined by LXQt - but I didn't realize that it refered to a failing openbox configuration: "Failed to excecute child process "kfmclient" (No such file or directory)", with "openbox" in the titel of the error message window. I commented it out and now LXQt alowed me to use the shortcut!
