### ISSUE TITLE
Desktop wallpaper settings should have "zoomed fill"/"stretch while keeping aspect" option

### ISSUE THREAD

**Issue by v-fox** [lxde/lxqt#1169]
Right now if you use pcmanfm-qt's wallpapers settings but your wallpaper isn't of the same aspect ration as your monitor (like 4:3 image on 16:9), you're screwed, it will look ugly with any settings. The only thing the actually fixes it and can replace all other useless settings is something like [nitrogen](https://github.com/l3ib/nitrogen)'s "zoomed fill" option which fills the screen by scaling while preserving aspect ration. That way there is no ugly "empty", unfilled space on screen and picture isn't ruined by stretching but part of it is outside the screen.

It also should be capable of setting wallpapers for each screen independently as nitrogen does. I worked around that for myself by manually replacing pcmanfm-qt with nitrogen in `~/.config/autostart/lxqt-desktop.desktop` but it only works under openbox and not kwin.

**Comment by tsujan** [comment]
> Right now if you use pcmanfm-qt's wallpapers settings but your wallpaper isn't of the same aspect rati..

You mean adding an option for resizing such wallpapers so that they fill the screen without any change in their aspect ratios (in which case, parts of them wouldn't be hidden)?

**Comment by v-fox** [comment]
> You mean adding an option for resizing such wallpapers so that they fill the screen without any change in their aspect ratios (in which case, parts of them would be hidden)?

Yeah, better have a small portion of borders cut-off than ugly black borders added or stretching.

**Comment by tsujan** [comment]
OK! It shouldn't be difficult and seems to be a good option. I'll look into it.

**Comment by tsujan** [comment]
@v-fox 
If you can compile from the source, please check https://github.com/lxde/pcmanfm-qt/pull/406; otherwise, wait until it's merged and entered your distro.

**Comment by v-fox** [comment]
Patched version 0.11.1, seems alright !
Now the only thing that's left is proper multi-screen handling: not treating all screens as a single giant one and allowing separate wallpapers for each screen. Or is it done already ? I couldn't find issue report about that.

**Comment by tsujan** [comment]
@v-fox 
This issue will be closed when https://github.com/lxde/pcmanfm-qt/pull/406 is merged. Please open a separate issue for your second feature request!

**Comment by v-fox** [comment]
Ok, here's #1175
