### ISSUE TITLE
LXQT_TRANSLATIONSDIR should be set in lxqt-build-tools, not in liblxqt

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#1172]
With LXQT_TRANSLATIONSDIR set in lxqt-build-tools we can remove the lxqt dependency from lxqt-l10n 

@palinek Could you please take care of?

**Comment by luis-pereira** [comment]
@agaida I'm aware of that. And it's probably not the only one.

**Comment by luis-pereira** [comment]
@agaida @palinek IMO all definitions of that kind should me moved to `lxqt-build-tools`.
Al the build configurations should be made on `lxqt-build-tools`.
I will make a PR for that.

**Comment by palinek** [comment]
>  IMO all definitions of that kind should me moved to lxqt-build-tools.

I thought that the `lxqt-build-tools` will contain only the needed cmake build scripts and all the configuration will be left in `liblxqt`.

So do you want to move all the *LXQT_*\* into `lxqt-build-tools`? I personaly would leave them in `liblxqt`. (the configuration should be used/needed only by components which already depend on `liblxqt`)

**Comment by luis-pereira** [comment]
@palinek That's also an viable option, of course.
My arguments to do it are:

- Every component depends on `lxqt-build-tools` but not on `liblxqt`.
 
- `lxqt-build-tools` must be compiled before all others.

- `lxqt-common` depends on `liblxqt` in an **artificial** way. It only depends on liblxqt to get the needed definitions.

**Comment by palinek** [comment]
> Every component depends on `lxqt-build-tools` but not on `liblxqt`.

Yes, and every component that does not depend on 'liblxqt`, does not need the lxqt configuration variables.

> `lxqt-build-tools` must be compiled before all others.

Yes, but this is neither pro nor con, but rather a normal dependency.

> `lxqt-common` depends on `liblxqt` in an artificial way. It only depends on liblxqt to get the needed definitions.

Truth... but what's the difference if the definitions are moved into `lxqt-build-tools`? Then it will depend on `lxqt-build-tools` ... All of these are just "build dependencies". The built binary package doesn't need neither `liblxqt` nor `lxqt-build-tools`.


Anyway... I'm not strictly for leaving the configuration vars in `liblxqt`, just that it seems to me to be more proper place for them.

**Comment by paulolieuthier** [comment]
I'm not expert in packaging or build systems, but I think @palinek is right. lxqt-build-tools should contain tools. Configuration and parameters should continue in liblxqt IMO.

**Comment by luis-pereira** [comment]
@palinek The bottom line of my proposal is to put all the build time dependencies in one single place.

With the new `lxqt-build-tools` we will have two build time dependencies: `lxqt-build-tools` and `liblxqt`, instead of the current one.
The reasoning behind `lxqt-build-tools` was to decrease build time dependencies not increase it. One of  the arguments for creating `lxqt-build-tools` was to stop the not so logical thing of having to build `liblxqt` just to get build time sutff. 

For me it seems logical to have all build time dependencies in `lxqt-build-tools`. Even the name suggests that. Having a repository `lxqt-build-tools` and then some of the build configurations are located in other repo seems not logical to me. One just have to build lxqt-build-tools and all build dependencies are taken care.

That's my two cents. I'm happy with it anyway, as I said before: I'm no packager :wink:

**Comment by palinek** [comment]
> The reasoning behind lxqt-build-tools was to decrease build time dependencies not increase it.

Good point.

Do you want to create a new cmake module e.g. `LXQtConfigVars.cmake` with all the configuration variables and then pull it like
```
find_package(lxqt-build-tools)
include(LXQtConfigVars)
```
?

**Comment by luis-pereira** [comment]
@palinek Precisely, although I thought of
```include(LXQtCompileDefinitions)``` to state that they are build time definitions.

Independently of the name, that's the idea.

**Comment by agaida** [comment]
@luis-pereira @palinek @paulolieuthier - could you please descide _now_. Two things - for those guys who get their translations at build time everything is allright - the tools are a build dependency so the settings are readed in every possible case. For those of us who get the translations repo it would be better only to throw in the tools.

**Comment by agaida** [comment]
Foget one thing - if lxqt-l10n really should depend on liblxqt that would mean that obconf-qt-l10n hard  depends on liblxqt - i would tend to consider that as not so nice

**Comment by palinek** [comment]
I'm OK with moving the LXQT_ config vars into `lxqt-build-tools`... after all it sounds reasonably.

**Comment by luis-pereira** [comment]
@agaida @palinek I will take care of it. After it `lxqt-l10n` (for example) will only depend on `lxqt-build-tools`

**Comment by agaida** [comment]
cool, thank you very much

**Comment by luis-pereira** [comment]
Done by https://github.com/lxde/lxqt-build-tools/commit/6ef6ecfc775332477e3f0ecf25027064b50c7eef and https://github.com/lxde/liblxqt/commit/012716c5205aecd1a2412ab9ef44a0a47c5ebd32.
