### ISSUE TITLE
Libfm fails to recognise rar files due to mime type change

### ISSUE THREAD

**Issue by milksleisure** [lxde/lxqt#1173]
This issue might related to this one.
https://forum.manjaro.org/t/ark-16-08-1-1-regression-with-rar-files-cant-open-or-extract-them/9622
(from "application/x-rar" to "application/vnd.rar") 
related file: libfm/data/archivers.list
On latest archlinux, the "extract here" and "extract to" are missing from the menu. The icon for rar file is not shown correctly as well.
![archlinux](https://cloud.githubusercontent.com/assets/2565790/19242279/117d1072-8f45-11e6-8963-ebbc9835805b.png)

**Comment by agaida** [comment]
@milksleisure please explain why this is a problem of libfm as i don't understand it

**Comment by tsujan** [comment]
@agaida, I think it isn't. As the reporter said, it may be related to https://forum.manjaro.org/t/ark-16-08-1-1-regression-with-rar-files-cant-open-or-extract-them/9622

**Comment by LStranger** [comment]
Well, in fact, LibFM has a file archivers.list, feel free to add
mentioned application/vnd.rar into mime_type field for Ark.

**Comment by tsujan** [comment]
@LStranger
Thanks! If the rar mimetype string is changed, shouldn't we update it in (or add it to) libfm? If so, I was wrong sayiing that this problem may not be in libfm.

**Comment by milksleisure** [comment]
@agaida @tsujan 
I am not sure, but "fm_archiver_is_mime_type_supported" (https://github.com/lxde/libfm/blob/master/src/base/fm-archiver.c#L58) might be using the file (https://github.com/lxde/libfm/blob/master/data/archivers.list#L34) to decide whether a file should be handled by archiver wrapper.
ARK itself can actually open & extract the file without issue. It is simply "Extract Here..." option missing from the right click menu

**Comment by tsujan** [comment]
@milksleisure 
I downloaded a rar sample and yes, `application/x-rar` has changed to `application/vnd.rar`. Hence the `unknown` icon and the missing "Extract Here...". `archivers.list` uses the older string.

Please change all occurrences of `application/x-rar` to `application/vnd.rar` in '/usr/share/libfm/archivers.list', restart pcmanfm-qt and see if the problem is fixed!

**Comment by stefonarch** [comment]
For me using ark this works fine.

**Comment by tsujan** [comment]
Yes, it works here too, with engrampa.

As for the icon, do `ln -s application-x-rar.png application-vnd.rar.png` in `mimetypes` folders of your icon theme (or `ln -s application-x-rar.svg application-vnd.rar.svg` if you use an svg set).

**Comment by stefonarch** [comment]
Btw: what is the situation of the hard-coded list for archivers in pcmanfm-qt? It would be to prefer only offer to select between applications that are installed in the system.

**Comment by tsujan** [comment]
>  It would be to prefer only offer to select between applications that are installed in the system.

The list shows the user what he/she could use and is useful if the archiver isn't installed yet. For example, I don't like Ark and that list helped me know there's a good archiver called "engrampa".

**Comment by stefonarch** [comment]
That is a point, a solution could be to have only installed apps selectable and blur out the rest. Now a user can just select something that  does not work.

**Comment by tsujan** [comment]
I hadn't though of disabling (blurring) menu-items. So, you're right. But I don't think it's an urgent problem. The user knows what he/she has installed because he's a *Linux* user ;)

**Comment by stefonarch** [comment]
Not urgent, but   offering options for things that eventually do not even exist in the system is something to fix sooner or later IMHO. This was discussed already but I cannot find the issue.

**Comment by milksleisure** [comment]
Hi @tsujan, I can confirm that it works as intended by provided method. Thanks for your help.
About the list, I would suggest using wiki or "man" to provide user the config file location, and allow users to custom it under ~/.local/share or somewhere. (for example I can already add custom action this way, which is really a handy feature)

**Comment by stefonarch** [comment]
> for example I can already add custom action this way, which is really a handy feature)

There is already the folder  ~/.local/share/file-manager/actions for .desktop files
https://wiki.lxde.org/en/PCManFM#Add_own_options_to_the_files_context_menu

**Comment by tsujan** [comment]
> There is already the folder ~/.local/share/file-manager/actions

Yes! *That's* the place for custom actions. Items like "Extract Here" are fixed actions.
