### ISSUE TITLE
repository lxqt: faulty CMake settings

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#1177]
The current CMake settings in repository lxqt seem a bit faulty.

In `CMakeLists.txt` lxqt-build-tools, libfm-qt, qtermwidget, qterminal and pavucontrol-qt are missing.
Even when a line like `add_subdirectory(lxqt-build-tools)` is added to `CMakeLists.txt` invoking `cmake` the usual way still fails as lxqt-build-tools aren't found.

Not sure about the exact purpose of CMake in this repository. But as I understand it the aim should be to compile LXQt from the sources using CMake similarly as it can be achieved by running the build scripts provided by the repository. And if so the problems depicted above should be fixed.

**Comment by luis-pereira** [comment]
@pmattern It's outdated.
That `CMakeLists.txt` provides another way of building LXQt (the CMake repos). It's called the `superbuild mode`. One can can simply do:
`cmake ..`
`make`

`libfm-qt` and `qtermwidget` are lacking superbuild support. https://github.com/lxde/lxqt-build-tools/commit/8aaaf029a2365ea87ef4ada0aff7bdabef208771 adds superbuild support to `lxqt-build-tools`.
Hoping to finish the job in the next few days.

**Comment by agaida** [comment]
@luis-pereira - is this issue still valid?

**Comment by luis-pereira** [comment]
No. It's fixed.
