### ISSUE TITLE
HELP: How can lxqt-panel refresh the menu after it has been edited?

### ISSUE THREAD

**Issue by vonHabsi** [lxde/lxqt#1178]
I used MenuLibre to edit the menu but it seems that the changes will not take until I logout and log back in, but I have too many open windows now.

Is there a way to change the menu without logging out or restarting?

**Comment by stefonarch** [comment]
killall lxqt-panel && lxqt-panel &

**Comment by pmattern** [comment]
This is a long-standing, known bug, see #65.
Aside from restarting the panel you can also update the time stamp of the desktop entry file `*.menu` that's used to build the menu. Using the default one e. g. by running `# touch /etc/xdg/menus/lxqt-applications.menu`, has to be invoked by root.
Restarting the panel, which indeed represents another means, can also be handled by GUI [LXQt Session Settings](https://github.com/lxde/lxqt-session#lxqt-session-settings).

**Comment by wellington1993** [comment]
@pmattern Worked for me calling individually the commands using the Alt+F2 Shortcut...

Alt+F2 =>  ```killall lxqt-panel```
Alt+F2 =>  ```lxqt-panel```

In my case the panel freeze after try to adjust sound volume.

Thanks!

**Comment by stefonarch** [comment]
> `killall` lxqt-panel && lxqt-panel & `

This has the downside that the panel module seems not running. Better:
```
qdbus org.lxqt.session /LXQtSession org.lxqt.session.stopModule lxqt-panel.desktop
sleep 1
qdbus org.lxqt.session /LXQtSession org.lxqt.session.startModule lxqt-panel.desktop
```
