### ISSUE TITLE
Cannot be installed from PPA

### ISSUE THREAD

**Issue by notorand-it** [lxde/lxqt#1180]
I added the suggested PPA (lxqt/ppa).
Then ,after the usual update, I have got this:

```
[user@Feynman ~] sudo apt install lxqt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lxqt : Depends: lxqt-core (= 4.2~ubuntu16.04.1) but it is not going to be installed
        Depends: lxqt-openssh-askpass but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
I am running Kubuntu 16.04 on `amd64` architecture:

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

**Comment by palinek** [comment]
@gilir ?

**Comment by gilir** [comment]
This PPA is not a supported way to install LXQt. See https://wiki.ubuntu.com/Lubuntu/LXQt

**Comment by notorand-it** [comment]
I removed the repo file from `/etc/apt/sources.list.d` and then run `apt update`.

```
[user@Feynman ~] sudo apt install lubuntu-qt-desktop
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package lubuntu-qt-desktop
```

Now what?

**Comment by palinek** [comment]
Based on the ubuntu's package search, it's only in 16.10: http://packages.ubuntu.com/search?keywords=lubuntu-qt-desktop&searchon=names&suite=all&section=all

**Comment by notorand-it** [comment]
So this means that none with 16.06 LTS can test LxQt. Right?

**Comment by palinek** [comment]
> So this means that none with 16.06 LTS can test LxQt. Right?

Why? The packages are there: http://packages.ubuntu.com/search?keywords=lxqt&searchon=names&suite=all&section=all

**Comment by notorand-it** [comment]
The wiki gilir has been mentioning says to install `sudo apt install lubuntu-qt-desktop` which is not available for 16.04.
Would you please suggest me which package would pull all the needed stuff or which package list should I install on my 16.04 in order to test LxQt?

**Comment by palinek** [comment]
> Would you please suggest me which package would pull all the needed stuff or which package list should I install on my 16.04 in order to test LxQt?

IMO `sudo apt install lxqt lxqt-common` should be enough, try & see (I'm not an ubuntu user).

Note that all  LXQt packages in ubuntu are `0.10`, not the recently released `0.11`

**Comment by palinek** [comment]
It shouldn't affect network manager in any way. Did you uninstall any packages?

**Comment by notorand-it** [comment]
Nope. Just installed lxqt and at the end the KDE nm plasma widget was gone along with connectivity!

**Comment by jubalh** [comment]
Doesn't apt-get ask before it removes stuff? I think it does

**Comment by tsujan** [comment]
> Nope. Just installed lxqt and at the end the KDE nm plasma widget was gone along with connectivity!

If you didn't touch any other package, that should be a downstream dependency problem. LXQt doesn't remove any KDE component.

**Comment by palinek** [comment]
> > Nope. Just installed lxqt and at the end the KDE nm plasma widget was gone along with connectivity!

> If you didn't touch any other package, that should be a downstream dependency problem. LXQt doesn't remove any KDE component.

But he doesn't see the KDE applet of course.

@notorand-it you need to isntall the nm-applet, package `network-manager-gnome`

**Comment by tsujan** [comment]
> But in LXQt he doesn't see the KDE applet of course.

That's true. Connman and CMST work perfectly everywhere, especially under LXQt. Maybe Connman was among "Recommends" and removed nm.

**Comment by notorand-it** [comment]
I didn't switch to lxqt yet.
At the installation there's only a request to perform whatever the installation requires, like pulling extra packages.
I just asked to install lxqt and confirmed so.

**Comment by notorand-it** [comment]
@palinek I need to manually configure the wireless network or find an Ethernet cable long enough to reach the switch upstairs...

**Comment by tsujan** [comment]
> At the installation there's only a request to perform whatever the installation requires, like pulling extra packages

... and, sometimes, removing some other packages.

**Comment by notorand-it** [comment]
Correct, tsujan. I trusted the package lxqt to leave a usable system...

**Comment by agaida** [comment]
notorand-it - LXQt is a fast moving target so i guess you would be better with xenial - btw - what is the reason for the try to couple an LTS release with at least old cutting edge stuff? In other words: Install sid and the latest release or wait until the LXQt packages will hit the x-named ubuntu repositories.

**Comment by pmattern** [comment]
@notorand-it

Attempting to reproduce your findings on Ubuntu 16.04 I ran into the initial error message caused by `ppa:lxqt/ppa` as well but cannot confirm the various dependency problems you've been describing in the course of this issue. In particular the LXQt packages from the official repositories could be installed alongside KDE including Plasma Applet for NetworkManager (plasna-nm) flawlessly.
Have you by any chance forgotten to run `apt-get update` or something similar after removing the PPA from the Apt sources?

You may find the official upstream documentation how to install LXQt in our [wiki](https://github.com/lxde/lxqt/wiki/Installation-Introduction) including notes on the *buntu binary packages.

Depending on your needs compiling the sources may be an alternative. Scripts to handle this are described in the wiki, too. Also, you may just consider switching to another distribution. E. g. the upcoming openSUSE Leap is targeted at a similar audience but will provide release 0.11 already.

**Comment by notorand-it** [comment]
I did the only available option to install LxQt on my Kubuntu 16.04: install the LxQt package from the official repository.
I ended up with an offline PC.
I should have reviewed the installation list and deny the action. But then I wouldn't have tried the lxqt.
There's indeed something broken in the package.

**Comment by tsujan** [comment]
> There's indeed something broken in the package.

I remembered that I had a Kubuntu LTS on VirtualBox. I ran Synaptic and selected the meta-package "lxqt". It wanted to remove network-manager and plasma-mn and install connman instead. So, the same thing should have happened to you.

There are two problems here:

(1) LXQt does NOT depend on connman but can use it. (Personally, I prefer connman over nm);

(2) If you have connman, you could set it up and have a good connection but when Ubuntu enforces connman, it should not only install it completely (not just the package "connman") but also install a frontend for it, so that the user could easily set it up with an interface.

IMO, you could report both problems at Launchpad.

**Comment by tsujan** [comment]
I also remember that I had once a similar problem in a KDE-only Debian. So, the root of this problem may be in Debian and its package management.

**Comment by notorand-it** [comment]
The problems are two, in my opinion:

1. Canonical/Ubuntu Team cannot blindly pull any package that's in Debian without a minimum testing (the package cannot break a working system!)
2. LxQt needs a front-end to network-manager or use either network-manager-gnome or plasma-nm, with the former my personally preferred solution

My report is here:
https://bugs.launchpad.net/ubuntu/+source/lxqt-metapackages/+bug/1635801

**Comment by notorand-it** [comment]
> In Arch based systems, connman never removes network-manager.

This is good news, despite I prefer to only use one.

**Comment by agaida** [comment]
apt show lxqt
```
Priority: optional
Section: metapackages
Source: lxqt-metapackages
Maintainer: LXQt Packaging Team <pkg-lxqt-devel@lists.alioth.debian.org>
Installed-Size: 9.216 B
Depends: lxqt-core (= 6), lxqt-about, lxqt-admin, lxqt-config, lxqt-globalkeys, lxqt-notificationd, lxqt-openssh-askpass, lxqt-policykit, lxqt-powermanagement, lxqt-qtplugin, lxqt-runner
Recommends: cmst, connman | network-manager, lximage-qt, lxqt-sudo | gksu, pavucontrol, smplayer, smtube, qlipper, qpdfview, qps, qterminal, gucharmap, firefox | www-browser, sddm | lightdm | x-display-manager, audacious | clementine | qmmp, xarchiver
Suggests: calibre, compton, compton-conf, juffed, nomacs, obconf-qt, openbox, qtpass, quassel | quassel-client | hexchat, screengrab | shutter, claws-mail, vokoscreen, zim
Homepage: http://www.lxqt.org/
```
So there should be no problem with the current version - hmm - xenial uses version 4, that really depends on connman instead connman | network-manager - one could use yakkety or look for some backports. In general i would not recommend 16.04 with lxqt.

**Comment by notorand-it** [comment]
@agaida The packages for xenial are either to be made fully working and functional or they need to be pulled from the repository. 
I cannot read anywhere about this "recommendation" you are talking about.
In the beginning I want for the PPA, then I've been said that the PPA was for Yakkety only. So I went for the official repository and got my system broken.

Of course, if you check things under a different environment, you'll probably get different answers:

```
[user@Feynman ~] apt show lxqt
Package: lxqt
Version: 4
Priority: optional
Section: universe/metapackages
Source: lxqt-metapackages
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: LXQt Packaging Team <pkg-lxqt-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 9.216 B
Depends: lximage-qt, lxqt-core (= 4), lxqt-about, lxqt-admin, lxqt-config, lxqt-globalkeys, lxqt-notificationd, lxqt-openssh-askpass, lxqt-policykit, lxqt-powermanagement, lxqt-qtplugin, lxqt-runner, lxqt-sudo, qterminal, xarchiver
Recommends: cmst, compton, compton-conf, obconf-qt, pavucontrol, screengrab, smplayer, smtube, qlipper, qpdfview, qps, gucharmap, qupzilla | x-www-browser, sddm | lightdm | x-display-manager, audacious | clementine | qmmp
Suggests: calibre, juffed, nomacs, qtpass, quassel | quassel-client, trojita | claws-mail, vokoscreen, zim
Homepage: http://www.lxqt.org/
Download-Size: 2.104 B
APT-Sources: http://it.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Description: Metapackage for LXQt
 LXQt is an advanced, easy-to-use, and fast desktop environment based on Qt
 technologies. It has been tailored for users who value simplicity, speed, and
 an intuitive interface. Unlike most desktop environments, LXQt also works
 fine with less powerful machines.
 .
 This package is a metapackage meant to provide the core components
 of LXQt plus some recommended components. These include lxqt-core,
 lxqt-appearance, lxqt-input, qterminal, lxqt-config and xarchiver.

```
It implicitly recommends connman through cmst! The package v4 is broken as it will wipe whatever is alternative to connman and, my guess, without porting network-manager configuration to it.

**Comment by agaida** [comment]
Hint: it is not broken, it is not very sensible - and i know the version 4 and i know the author. Ubuntu has taken the meta-packages from sid. And i don't think they will change a bit in the LTS repo, maybe the make more current packages available in backports. And another time - LTS and a desktop environment in rapid development don't match well.

**Comment by notorand-it** [comment]
lxqt needs to be pulled away from LTS repos if it doesn't match the TLS definition.

**Comment by agaida** [comment]
another time - We are upstream, we are not responsible for downstream descisions.

**Comment by notorand-it** [comment]
@agaida This is why I filed the bug to Ubuntu, not LxQt devs!

**Comment by pmattern** [comment]
@notorand-it 
Did you bother reading my previous post? The dependency issue involving NetworkManager and Plasma Applet for NetworkManager is not as general as you claim. Ubuntu 16.04:
```
# apt-get install network-manager plasma-nm
[...]
# apt-get install lxqt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  audacious audacious-plugins audacious-plugins-data compton compton-conf gtk2-engines-pixbuf libaudcore3 libaudgui3 libaudtag2 libbinio1v5 libbonobo2-0
  libbonobo2-common libbonoboui2-0 libbonoboui2-common libcddb2 libconfig9 libcue1 libfluidsynth1 libfm-data libfm-extra4 libfm-gtk-data libfm-gtk4
  libfm-modules libfm-qt2 libfm4 libglade2-0 libgnome-2-0 libgnome2-0 libgnome2-bin libgnome2-common libgnomecanvas2-0 libgnomecanvas2-common libgnomeui-0
  libgnomeui-common libgnomevfs2-0 libgnomevfs2-common libid3tag0 libimlib2 libjpeg-progs libjpeg9 libkf5screen6 liblxqt-data liblxqt-globalkeys-ui0
  liblxqt-globalkeys0 liblxqt0 libmenu-cache-bin libmenu-cache3 libmms0 libobrender32 libobt2 liboobs-1-5 liborbit-2-0 libpoppler-qt5-1 libqt5xdg1
  libqtermwidget5-0 libqupzilla1 libsidplayfp4 libstatgrab10 libsysstat-qt5-0 libxcb-dpms0 libxcb-screensaver0 lximage-qt lxmenu-data lxqt-about lxqt-admin
  lxqt-common lxqt-config lxqt-core lxqt-globalkeys lxqt-notificationd lxqt-openssh-askpass lxqt-panel lxqt-policykit lxqt-powermanagement lxqt-qtplugin
  lxqt-runner lxqt-session lxqt-sudo obconf-qt oxygen-icon-theme oxygen5-icon-theme p7zip-full pcmanfm-qt qlipper qpdfview qpdfview-djvu-plugin
  qpdfview-ps-plugin qpdfview-translations qps qterminal qtermwidget5-data qupzilla screengrab smplayer smplayer-l10n smplayer-themes smtube
  system-tools-backends xarchiver xscreensaver xscreensaver-data
Suggested packages:
  libbonobo2-bin libfm-tools nautilus-actions desktop-base gnome-icon-theme libgnomevfs2-bin libgnomevfs2-extra gamin | fam gnome-mime-data sidplayfp
  calibre juffed nomacs qtpass quassel | quassel-client trojita | claws-mail vokoscreen zim p7zip-rar arj lhasa rar rpm unar xfishtank xdaliclock
  xscreensaver-gl fortune qcam | streamer gdm3 | kdm-gdmcompat
Recommended packages:
  cmst perl5
The following NEW packages will be installed:
  audacious audacious-plugins audacious-plugins-data compton compton-conf gtk2-engines-pixbuf libaudcore3 libaudgui3 libaudtag2 libbinio1v5 libbonobo2-0
  libbonobo2-common libbonoboui2-0 libbonoboui2-common libcddb2 libconfig9 libcue1 libfluidsynth1 libfm-data libfm-extra4 libfm-gtk-data libfm-gtk4
  libfm-modules libfm-qt2 libfm4 libglade2-0 libgnome-2-0 libgnome2-0 libgnome2-bin libgnome2-common libgnomecanvas2-0 libgnomecanvas2-common libgnomeui-0
  libgnomeui-common libgnomevfs2-0 libgnomevfs2-common libid3tag0 libimlib2 libjpeg-progs libjpeg9 libkf5screen6 liblxqt-data liblxqt-globalkeys-ui0
  liblxqt-globalkeys0 liblxqt0 libmenu-cache-bin libmenu-cache3 libmms0 libobrender32 libobt2 liboobs-1-5 liborbit-2-0 libpoppler-qt5-1 libqt5xdg1
  libqtermwidget5-0 libqupzilla1 libsidplayfp4 libstatgrab10 libsysstat-qt5-0 libxcb-dpms0 libxcb-screensaver0 lximage-qt lxmenu-data lxqt lxqt-about
  lxqt-admin lxqt-common lxqt-config lxqt-core lxqt-globalkeys lxqt-notificationd lxqt-openssh-askpass lxqt-panel lxqt-policykit lxqt-powermanagement
  lxqt-qtplugin lxqt-runner lxqt-session lxqt-sudo obconf-qt oxygen-icon-theme oxygen5-icon-theme p7zip-full pcmanfm-qt qlipper qpdfview
  qpdfview-djvu-plugin qpdfview-ps-plugin qpdfview-translations qps qterminal qtermwidget5-data qupzilla screengrab smplayer smplayer-l10n smplayer-themes
  smtube system-tools-backends xarchiver xscreensaver xscreensaver-data
0 upgraded, 102 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/51.6 MB of archives.
After this operation, 120 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```
So it's either a problem at your side or something Kubuntu specific. The latter would be in accordance with the experience of @tsujan mentioned [above](https://github.com/lxde/lxqt/issues/1180#issuecomment-255513453) but you don't mention Kubuntu in your launchpad report.

> LxQt needs a front-end to network-manager

→ [nm-tray](https://github.com/palinek/nm-tray). Not strictly geared towards LXQt but Qt only and hence working flawlessly in LXQt sessions. Early alpha status yet pretty usable already. Binary packages not really wide-spread but installing from the sources can be done without downside as it's just a single binary and some QM (translation) files only for now.

**Comment by tsujan** [comment]
@agaida  @notorand-it 
I strongly believe that *this problem is all about packaging of connman under Debian* and its derivatives.

As I said above, under Arch based systems, when you install connman, NetworkManager is untouched and no connction is lost. That's because, under Arch systems, it's up to the user to enable/disable systemd services. Under Debian, on the contrary, connman is packaged such that it has conflict with network-manager because Debian automatically enables (forces) systemd services.

We can blame neither lxqt nor connman but Debian's policy. The only way out of this problem is making an exception to that policy. But that should be done by Debian or Ubuntu.

**Comment by tsujan** [comment]
@pmattern 
Perhasps Ubuntu tries to do a favor and installs Connman because CMST is very compatible with LXQt. But connman removes network-manager and plasma-nm because of the way Debian works.

**Comment by pmattern** [comment]
Whatever Debian or Ubuntu do the crucial point is that metapackage `lxqt` does by default *not* pull ConnMan on Ubuntu 16.04 so there must be an issue either on the OPs system or in Kubuntu.

**Comment by tsujan** [comment]
@pmattern 
You're right; Connman should have been among "recomends" at most. My point is that, apart from LXQt, if an Ubuntu/Debian user wants to try Connman, they same thing might happen -- it happened to me years ago.

**Comment by agaida** [comment]
hey @tsujan and @pmattern - lxqt is a metapackage - and version 4 is in a very early state of the package. So it works just fine in a single installation - nobody has claimed that installing more than one DE in on installation is the best idea. Some of these "issues" are addressed in later versions. But 4 was the only available version at this time, i changed the metapackage in 2016/9

@tsujan - an lxqt-core installation would prevent such situations with 16.04 - but that need a little bit of understanding how apt works - and apt installs recommends by default in debian and ubuntu. so the only way to fulfill the dependeny of the meta-package are alternatives like connman | network-manager

If one have a look into the yakkety packages - it is there. And again: A LTS is probably  not the best thing to run bleeding or cutting edge stuff. So what, no yakkety user will have that problem. solved.

**Comment by tsujan** [comment]
> and apt installs recommends by default in debian and ubuntu. so the only way to fulfill the dependeny of the meta-package are alternatives like connman | network-manager

When I tested in Kubuntu LTS on VirtualBox, I unchecked Recommends in Synaptic and still network-manager was going to be uninstalled. And even if it didn't, suppose that I wanted Connman; network-manager would be gone and as a newbie, I wouldn't know what happened.

**Comment by agaida** [comment]
and yes - connman has a Conflicts: network-manager in it - and this is fine. The keyword is education - one should read what happend when installing packages, synaptic might not be the best tool in that case. But this is known for years and should be no problem. I get the advise to only use apt-get if i want to stay a happy ubuntu user longterm back in 2010 in ubuntuusers.de. And yes, these guys was right.

**Comment by agaida** [comment]
/me listen to Cher: If i could turn back times

**Comment by tsujan** [comment]
> nd yes - connman has a Conflicts: network-manager in it - and this is fine. The keyword is education...

It's not about education; Connman and network-manager could be installed side by side without conflict if Debian didn't enable their services automatically -- the user could enable one and disable the other at will without installation/uninstalling But let's not bother ourselves with things outside LXQt ;)

**Comment by pmattern** [comment]
@agaida 
Metapackage `lxqt` [is not the culprit](https://github.com/lxde/lxqt/issues/1180#issuecomment-255530507) anyway.


>> nd yes - connman has a Conflicts: network-manager in it - and this is fine. The keyword is education...

> It's not about education; [...]

Definitely. If a simple `apt-get install foobar` is yielding chaos as Debian and friends insist on launching services upon installation then there's something rotten in the system itself.

**Comment by agaida** [comment]
wrong, but we should not discuss this here. But hey, become involved and make it better, it's still foss.

**Comment by tsujan** [comment]
> Definitely. If a simple apt-get install foobar is yielding chaos as Debian and friends insist on launching services upon installation then there's something rotten in the system itself.

As a very old Debian user that uses an Arch-based system now (Manjaro), I completely agree!

**Comment by tsujan** [comment]
>  But hey, become involved and make it better, it's still foss.

If they listened, I might still be a Debian user.

> we should not discuss this here.

Agreed!

**Comment by agaida** [comment]
Different philosophy i guess. And different kind of users as target - it all has it pros and cons. I love both arch and debian
