### ISSUE TITLE
[Feature] Symbolic Icons

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#1181]
Under KDE, if the `index.theme` of an icon theme includes "FollowsColorScheme=true" (as Breeze does), its "symbolic icons" will become white on dark backgrounds and black on light backgrounds, provided that the style engine supports such a color change (Breeze supports it and I've included a more advanced form of it in Kvantum). Can this feature be implemented for LXQt without KDE dependency?

**Comment by agaida** [comment]
It would be nice :)

**Comment by tsujan** [comment]
I need a little more free time to start working on it -- don't like a good KDE feature be missing from LXQt.

**Comment by palinek** [comment]
@tsujan do you have any reference/documentation, what should be done on LXQt side?

**Comment by tsujan** [comment]
@palinek 
No, I don't know of any documentation; I'll have attack the problem "wildly".

**Comment by palinek** [comment]
Google revealed something like this:

https://api.kde.org/frameworks/kiconthemes/html/classKIconTheme.html#ad23ad90feb0c04dcc6e2758a171f936d

```
Returns
true if the SVG will be colorized with a stylesheet.
```

https://github.com/KDE/kiconthemes/blob/master/src/kiconloader.cpp#L921

https://github.com/KDE/kiconthemes/blob/master/src/kiconloader.cpp#L871

**Comment by palinek** [comment]
... so in KDE they are injecting the .svg with the particular CSS based on current pallete...

**Comment by palinek** [comment]
@tsujan so in kvantum (or any style engine) ... do you somehow select the "class" ?

**Comment by tsujan** [comment]
> so in kvantum (or any style engine) ... do you somehow select the "class" ?

Kvantum sets `QIcon::Mode` to `QIcon::Selected` when there's a high contrast between the widget text color and the color of `QPalette::WindowText`. That was one of the suggestions of the original author of QtCurve (he told me about it in an email -- he doesn't work on QtCurve anymore) and it worked. I think Breeze does something similar but, of course, there are big differences.

As for the SVG icons, yes, they should have a simple stylesheet. An example:
````
<svg width=...>
<defs id="defs3051">
<style type="text/css" id="current-color-scheme">
.ColorScheme-Text {
color:#4d4d4d;
}
</style>
</defs>
<path style="fill:currentColor;fill-opacity:1;stroke:none" id="..." d="..." class="ColorScheme-Text"/>
</svg>
````
All symbolic icons of breeze have a similar structure.

**Comment by tsujan** [comment]
@palinek 
Would you do it or should I work on it?

**Comment by palinek** [comment]
> Would you do it or should I work on it?

Actually, I'm a bit worried about the performance hit if the iconengine would parse/process the .svg stream twice...

**Comment by tsujan** [comment]
So, you won't work on it? I ask because there's no reason for both of us to work on the same thing, free time being a luxury. As for the performance hit, (1) we'll see when the work is done and (2) we might be able to make it optional.

**Comment by tsujan** [comment]
BTW, at first glance, it seems to be easy to implement.

**Comment by palinek** [comment]
> BTW, at first glance, it seems to be easy to implement.

Especially, when we have the KDE source code :)

**Comment by palinek** [comment]
> So, you won't work on it? I ask because there's no reason for both of us to work on the same thing, free time being a luxury. As for the performance hit, (1) we'll see when the work is done and (2) we might be able to make it optional.

It depends how hurry are you with this feature. I may have time for it later this week...

**Comment by tsujan** [comment]
> It depends how hurry are you with this feature. I may have time for it later this week...

No hurry at all! I just like LXQt to have nice features of KDE.

**Comment by palinek** [comment]
Just to update status... I'm not sure about having time to look into this ...

**Comment by tsujan** [comment]
OK. I'll do it.

**Comment by tsujan** [comment]
Did it by using simplified versions of some nice KDE methods as inline functions :) These screenshots are taken under LXQt:

![symbolic1](https://cloud.githubusercontent.com/assets/981076/24353701/0d07fc6c-1304-11e7-813c-6c4aa4607894.png)

![symbolic2](https://cloud.githubusercontent.com/assets/981076/24353706/12af5ade-1304-11e7-9284-7cdfe1bf7c6d.png)


I'll make a PR if I find some time to polish the code so that @palinek and @luis-pereira won't disagree with it -- which always seems impossible but it's OK ;)

**Comment by tsujan** [comment]
OK, it works with everything *except for LXQt apps that are styled by stylesheets* -- including the panel. The reason is simple: it relies on `qApp->palette()`; so, unless the panel is left to the active style engine, the value of `qApp->palette()` isn't equal to its stylesheet palette, while previously (in fact, currently), the value of `qApp->palette()` didn't have anything to do with icon colors.

Therefore, the panel and other stylable parts of LXQt should be  patched before this. I think that's possible because the author of Cantata has done the same thing -- but without stylesheets. KDE devs should have done it for the Plasma too.

However, I really have no time to work on the panel too. So, should I make a PR or not? I'll wait for a reply. Back to KDE for now.

**Comment by tsujan** [comment]
I took another look into panel's code. It's a shame that its structure is so dissonant with symbolic icons. All Qt5 apps show symbolic icons correctly under LXQt (with the patch, of course), as they do under KDE; the panel doesn't because it can't set its *app* text palette color according to its stylesheet. It's the same with lxqt-runner when using a stylesheet (= LXQT theme).

**Comment by palinek** [comment]
> However, I really have no time to work on the panel too. So, should I make a PR or not? 

Definitely yes. So anyone else can look into the problems with panel/runner...
