### ISSUE TITLE
lxqt-leave: enter key action

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#1183]
I have this problem in lxqt-session 0.11: 
In lxqt-leave enter key cancels the action, no matter which button is in focus. Space key works though.

Also, left and right keys move focus up and down between buttons.

**Comment by pmattern** [comment]
Confirmed as depicted above running lxde/lxqt-session@e69714a on Arch Linux.

The various options seem to be circled in an order top → bottom, left → right and backwards when arrow keys down / right or up / left respectively are hit.

The problem with the enter key cannot be seen in the GUIs of the various invocations `lxqt-leave --foobar` (which I still think should be visually adjusted to `lxqt-leave`).

**Comment by pmattern** [comment]
Besides strictly speaking an addendum to this issue only I still think the behaviour of the arrow keys is worth having another look at.
As discussed in lxde/lxqt-session#93 it simply makes for a pretty bad UX when e. g. hitting `Down` in the upper of two rows yields a move to the right.

**Comment by palinek** [comment]
Have a look in lxde/lxqt-session#95

**Comment by pmattern** [comment]
@palinek 
Any chance we can implement this with enabling the arrow keys to select button "Cancel" as well (see https://github.com/lxde/lxqt-session/pull/100#issuecomment-289555342)?
Not to turn this into an endless story, but I sill think this would improve the UX. If feasible probably best like a single item of a third row.

**Comment by palinek** [comment]
> Not to turn this into an endless story,

It already is :(

You may have a look in lxde/lxqt-session@6bc1a26, but this leads to next inconsistencies....
