### ISSUE TITLE
Update lxqt-l10n Travis

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#1185]
With the new lxqt-build-tools merged Travis is failing.
The needed `LXQtConfigVars.cmake` is generated at build time. Possible solutions:

- Build and install `lxqt-build-tools` before building lxqt-l10n.
- Use some script to create `LXQtConfigVars.came` from `LXQtConfigVars.cmake.in`.

@palinek What's your opinion ?

**Comment by palinek** [comment]
@luis-pereira we don't need the `LXQtConfigVars` at all for travis build. As we're already modifying the CMakeLists.txt in travis, we will also avoid pulling this dependency.

**Comment by luis-pereira** [comment]
@palinek How is `LXQT_TRANSLATIONS_DIR` set ?

**Comment by palinek** [comment]
> How is LXQT_TRANSLATIONS_DIR set ?

It isn't at all, but we aren't `make install`-ing in travis, so no need for having it defined...

**Comment by luis-pereira** [comment]
@palinek Sure. I was thinking in having the travis build as close as the "real".
