### ISSUE TITLE
Error dialog on startup (Unable to create an interface to connman-vpn on the system bus) CMST - Critical Error

### ISSUE THREAD

**Issue by Dai-trying** [lxde/lxqt#1187]
I am getting this error dialog when i first start LxQt, I have checked "Enable Autostart" in the preferences tab of "Connman UI Setup" as I wanted to have the icon in the system tray which otherwise doesn't show. On closing the error dialog the main setup window opens and the vpn tab is disabled. I do not use vpn but cannot see any options to disable it (or the checks for it).
I only want to have the icon display and do not need the setup to display on startup and I thought maybe I am not setting this correctly but cannot see another way to do it.
[Screenshot of error dialog](http://i.imgur.com/VCaDurb.png)
I am using LxQt Vesion 0.11.0-3 and Debian stretch, and if you require any log information or system info please ask and I will post it here.
Thanks for looking.
Dai

**Comment by agaida** [comment]
Ok, your question is not related to LXQt - its a CMST setting - please enable wait time, 3-5s might be enough. https://github.com/andrew-bibb/cmst/pull/123

**Comment by Dai-trying** [comment]
The value was already set to -w5 I changed it to -w10 and it still gave the dialog

**Comment by tsujan** [comment]
@Dai-trying 
If you use a Debian based system, install all cmst packages! This is my setting and I have no problem with auto-start:
![cmst](https://cloud.githubusercontent.com/assets/981076/19788371/c3f9467c-9cb4-11e6-8358-7633f8d54ec0.png)

**Comment by agaida** [comment]
@tsujan - there is only one cmst package (one can leave out cmst-dbgsym) 
@Dai-trying - please check if conman is really started - second guess: connman from sid

anyways - i don't know the installation (network-manager enabled and active, ifupdown?) - but i'm pretty sure that this problem has nothing to do with LXQt. But who knows, maybe i should learn a little bit about both debian and LXQt.

**Comment by tsujan** [comment]
@agaida 
My bad! I'm not on Debian now but remembered that the same problem happened to me almost a year ago and I fixed it by installing connman-vpn. It should be added to "recommends", imo. (Debian's package management again!)

@Dai-trying, test after installing connman-vpn!

**Comment by tsujan** [comment]
> but i'm pretty sure that this problem has nothing to do with LXQt

It isn't related to LXQt, of course! I just wanted to help a user. You rightly closed the issue.

**Comment by Dai-trying** [comment]
@tsujan Thank you, that screenshot gave me the clues to figure this one out, I don't need (or want) the vpn package as I don't use it. What fixed it was setting the "Use Start Options" at the top left of the preference settings, then I could disable vpn and everything is great now.I was just using the "EnableAutostart" from the "Program Control" so I couldn't access the disable vpn option.
Thanks to both of you for helping me. I've only just started using LxQt recently and I am liking what I see so far!
And my apologies for thinking this was a LxQt problem I have never seen CMST before and wrongly assumed it was part of LxQt.

**Comment by agaida** [comment]
glad you solve that - hmm - a not configured connman-vpn should not behave like this - the new connman 1.33 migrate in 4 days to testing i guess. The 1.32 might have some problems in that regard, never noticed it with connman 1.33 and newer.

**Comment by agaida** [comment]
@Dai-trying: Could you be so kind try the sid packages of connman and connman-vpn? And write a bug against connman if this happend with 1.33?

**Comment by agaida** [comment]
@tsujan - connman was long time not in the best shape in debian - now we catch up. And i have high hopes in the upcoming 1.34 release that should be released soon. One could consider 1.32 the very first version which was nearly ready for daily use (the vpn-part was new and buggy iirc) - might sound harsh, but the connman crew made great steps forward since April 16. So it is a fast moving target.

**Comment by Dai-trying** [comment]
@agaida Yes I will do that tomorrow, 1am here and got an early start in the morning :)

**Comment by tsujan** [comment]
@agaida, yes, I remember https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813647. Glad to hear that connman's status will become better on Debian!

**Comment by agaida** [comment]
you might read the latest changelog :p

**Comment by tsujan** [comment]
@agaida 
Congratulations!! It's a great improvment. Where were you when I used Debian ;)

**Comment by agaida** [comment]
thats easy - i was a happy Windows user :)

**Comment by Dai-trying** [comment]
@agaida I tried the sid package and the result was the same, I have reported this on the debian bug tracker #842444. Thanks for your help with this.

**Comment by agaida** [comment]
@tsujan @Dai-trying - fwiw - https://github.com/andrew-bibb/cmst/issues/155 :)

**Comment by Dai-trying** [comment]
Thanks, I know it's not a major bug, but every little improvement should help. :)

**Comment by agaida** [comment]
less annoying things means less support needed and better user experience - and we don't have to "waste" time on it again and again - so we have to thank you :+1:
