### ISSUE TITLE
lxqt-panel removable media widget pops up tooltip without reason irregulary

### ISSUE THREAD

**Issue by renegat** [lxde/lxqt#1190]
lxqt-panel 0.11.0-1
linux 4.8.6-1-ARCH x86_64 GNU/Linux

Every now and then the 'removable media / device management' widget of the lxqt-panel pops up a tool tip telling 'no media found' without reason - even without having anything done related to any kind of media. While doing so it steals the focus from every other application like browser or word-processing e.g. and disrupts your working flow.
This issue seems to be unrelated to any running application. There are no removable media devices attached.

**Comment by ckoenig** [comment]
I seem to experience the same problem. This seems to mainly occur while building docker containers. I don't really care about the message itself, but the fact, that the focus is lost is quite annoying.

**Comment by tsujan** [comment]
Removable media manager just connects to `Solid::DeviceNotifier::deviceAdded`, which Docker may trigger.

@palinek, do you know about Docker?

**Comment by renegat** [comment]
The 'removalbe media/devices management' widget also triggers regularly on mounted nfs exports mounted with autofs and spams its 'no devices found' into videos played with kodi or browser.

**Comment by tsujan** [comment]
> The 'removalbe media/devices management' widget also triggers regularly on mounted nfs exports mounted with autofs and spams its 'no devices found' into videos played with kodi or browser.

The slot `doDeviceAdded()` may need to be more selective in showing messages. Or, maybe, extra options should be added to the widget.

**Comment by tsujan** [comment]
@renegat @ckoenig 
If you problem is the stolen focus, you could set the setting to "Show info" and uncheck `Mount removable media automatically when they are inserted` in pcmanfm-qt's preferences:

![setting1](https://cloud.githubusercontent.com/assets/981076/21611352/c2ab526c-d1e1-11e6-9301-0f0614952a73.png)
![setting2](https://cloud.githubusercontent.com/assets/981076/21611357/c8e50e98-d1e1-11e6-93df-e4f2d4c7446c.png)

**Comment by palinek** [comment]
@renegat @ckoenig please, have a look on the lxde/lxqt-panel#389
