### ISSUE TITLE
Can't log into lxqt after installing with apt (lubuntu 16.04)

### ISSUE THREAD

**Issue by Serkan-devel** [lxde/lxqt#1194]
I tried to install lxqt via <code>sudo apt-get install lxqt openbox</code> but after reboot there was no selection to log into lxqt.

I've adressed this issue <a href='http://askubuntu.com/questions/838768/installed-lxqt-on-lubuntu-16-04-but-cant-log-into-it'>here</a> but with no help. I contacted Walter Lapchynski per email as told there but he still didn't respond.

What is the contents of a lxqt.desktop-file for lubuntu?

<strong>EDIT</strong>
lxqt-session is btw installed

**Comment by palinek** [comment]
You need the `/usr/share/xsessions/lxqt.desktop` which is in [`lxqt-common`](http://packages.ubuntu.com/xenial/lxqt-common)

**Comment by stefonarch** [comment]
On ubuntu in some cases (example lubuntu 16.04) lxqt-common conflicts with Lubuntu-default-session and else, so you cannot have both sessions.

**Comment by Serkan-devel** [comment]
Then do I need to uninstall Lubuntu-default-session or install lxqt-common beside it and tweak something?

**Comment by stefonarch** [comment]
Just do` apt install lxqt-common`, this should remove conflicting packages, you can reinstall lxde-common so you will have both LXDE and LXQt session avalaible, it is only  lubuntu-default-settings and lubuntu-default-session which conflicts with lxqt-common.

**Comment by slipttees** [comment]
Yes. lxqt-common conflicts with lubuntu-default-settings and lubuntu-default-session. Lubuntu 16.04.3 fresh install!

**Comment by agaida** [comment]
@sliptees - and what should we do about housemade downstream problems - btw. try a current release.

**Comment by Serkan-devel** [comment]
Installing lxqt-common already fixed it a long time ago. Maybe because 16.04 is a long term support release but I'm currently now switching to debian 9 testing. Are the standard packages there out of date?

**Comment by agaida** [comment]
ok, true answer - one should not switch to testing without knowing the basics - second thing - it might make more sense to switch to sid - maybe it will sometimes harder to handle, but it is faster fixed than testing. Both debian distributions has one thing in common - expect no help nor spoon feeding - you should be able to run these beasts alone without help. This might contain a steep learning curve in the beginning. 

In the end i would suggest debian sid, some time to learn and good nerves - and one should like terminals to maintain the installation.

**Comment by Serkan-devel** [comment]
What about debian stabke? I heard the packages are out of date and security fixes come later.

**Comment by jubalh** [comment]
out of date is a very variable term.

**Comment by agaida** [comment]
If you are really interested in current development - stable is not what you want. Rule of thumb: Current LXQt without much maintenance burden means Arch or Arch derivatives and AUR - or to an extend Debian Sid (and an insane inofficial repository named lxqt.debian.net/debian). Or other rolling distributions.

**Comment by tsujan** [comment]
As someone who'd used Debian for 8-9 years, I'd recommend testing + selecting from unstable and, sometimes, even from experimental. Debian is flexible in that regard. Testing is very stable and, with a little unstable, it's issues are fixed fast. However, as @agaida truly mentioned, that needs learning.

**Comment by tsujan** [comment]
To show how Debian Testing + Unstable can be stable, I should say that I never installed Debian twice in 8 years. I even cloned it from an old desktop computer to a new laptop and it continued working flawlessly.

**Comment by agaida** [comment]
Not exacly what i would suggest - but I'm a sid user. Especially transitions are faster in sid with less fallout - it might be a little bit rough some times, but is at all easier to handle, because new things come in directly - and the distance to experimental is not so much. But to be true, experimental is as the name says, a complete different beast. So one should *really* know what to pick from and why - and live with the consequences. I try to avoid it as much as i can :)

**Comment by tsujan** [comment]
> So one should really know what to pick from and why

I agree completely. There are so many choices in Debian's territory; perhaps, more than any distro. Oh, I feel nostalgic... but no return to Debian ;)

**Comment by agaida** [comment]
clever :P

**Comment by jubalh** [comment]
@Serkan-devel what you want is an easy distro which still brings you new packages, check out openSUSE Tumbleweed ;p

**Comment by tsujan** [comment]
> check out openSUSE Tumbleweed

Yes, yet another good option! I don't know why Debian users usually have a good opinion about OpenSUSE but I was among them. It (Tumbleweed) is stable, easy-to-use and almost up-to-date.
