### ISSUE TITLE
lxqt-idleness watcher failed to start

### ISSUE THREAD

**Issue by Baltasarq** [lxde/lxqt#1195]
I installed the last Lubuntu 16.10, and then installed lxqt using "sudo apt install lxqt". So far, I have been using lxqt without much problems (most were easily solved), apart from a bothering issue on startup. A notification balloon always shows up, complaining about:

"lxqt-powermanager
lxqt-idleness watcher failed to start
D-Bus Interface org.freedesktop.ScreenSaver is already registered"

I don't know how to solve this one. XScreenSaver is installed, but I just use light-locker, which blanks the screen.

**Comment by rogerfranz** [comment]
I've been getting this one as well. Actually, I've been getting it for quite some time, on 16.04.

Linux version 4.4.0-47-generic (buildd@lcy01-03) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016

Not sure where to look for more information about this.

**Comment by pmattern** [comment]
As of release 0.11 the Idleness Watcher of [lxqt-powermanagement](https://github.com/lxde/lxqt-powermanagement) is using KIdleTime instead of XCB which represents a major change. Ubuntu is the only major distribution the stable version of which still ships LXQt 0.10. So please understand that it's rather pointless for us to try and track this very special downstream issue.
Unfortunately I don't see any really good solution as far as Ubuntu is concerned. The quality of the PPAs providing recent LXQt is notoriously poor so these cannot be recommended on production systems. You may want to consider switching to another distribution which is geared towards a similar target audience but already providing 0.11 like e. g. openSUSE Leap 42.1. Also, you could consider [installing from the sources](https://github.com/lxde/lxqt/wiki/Building-from-source). Other than that you'll probably have to wait until 0.11 makes it to *buntu, which to my surprise won't necessarily be in 17.04.

**Comment by Baltasarq** [comment]
Many thanks for your answer.
I don't understand, however. Shouldn't *Lubuntu* (Ubuntu with LXDE) have the last versions of lxQt?
Do you mean that in version 17.04 Lubuntu won't change to lxQt?
This is really surprising to me. I will try to install from sources.

**Comment by pmattern** [comment]
> Many thanks for your answer.

You're welcome.

> Shouldn't Lubuntu (Ubuntu with LXDE) have the last versions of lxQt? Do you mean that in version 17.04 Lubuntu won't change to lxQt?

I'm not too familiar with the details of the planned transition. Given that LXQt 0.11 was released in September only I can understand they didn't get it into 16.10. The topic was discussed e. g. in [this thread](https://lists.ubuntu.com/archives/lubuntu-devel/2016-October/000893.html). Also, one of their team members was [questioning](https://lists.ubuntu.com/archives/lubuntu-devel/2016-November/000904.html) whether they should switch to LXQt at all recently. (His arguments are pretty odd but that's a different story.)

> I will try to install from sources.

I'd be all ears about your experiences. Feel free to use this issue or the [mailing list](https://github.com/lxde/lxqt/wiki/Contact) to report them.

**Comment by tsujan** [comment]
> I will try to install from sources.

@Baltasarq If you're familiar with making deb packages, make and install them in the order explained at https://github.com/lxde/lxqt/wiki/Building-from-source. That's a cleaner approach for Debian based systems. You could use the compilation date as the version so that your packages won't be overwritten by updates.

**Comment by agaida** [comment]
erm - getting the lates debian sources and rebuild them should not be rocket science if one has basic knowledge in packaging - in that case i would get the sid sources and rebuild them - with the same number or trailing -#.1 - done, the next official version should be higher

**Comment by tsujan** [comment]
@agaida 
It would be great if you could make Ubuntu deb packages too. In that way, we could refer Ubuntu/Mint users to your packages. However, I know it wouldn't be easy to maintain them.

**Comment by pmattern** [comment]
@tsujan 
Wiki page [Building-from-source](https://github.com/lxde/lxqt/wiki/Building-from-source) is not explaining how to create DEB packages but how to semi-automatically install all components from the sources. This does not include packaging at all which obviously represents the main drawback of those instructions.

**Comment by tsujan** [comment]
> Wiki page Building-from-source is not explaining how to create DEB packages...

I know but anyone familiar enough with deb packaging could use it to know the order of compilation/installation and even to make debian/rules (I did when I used Debian) -- and the same for rpm and pkg.tar.xz.

**Comment by tsujan** [comment]
BTW, I hope the order is correct at https://github.com/lxde/lxqt/wiki/Building-from-source - it was in its older versions; actually, the older version of that page was a little more informative.

**Comment by Baltasarq** [comment]
I was able to build from sources successfully. The instructions were really clear.
I'm afraid that my lxqt desktop system is unable to start, though. Actually, it seems impossible to launch any component, since it complains about missing symbols in libraries.
I will force the resintallation of lxqt.

**Comment by pmattern** [comment]
@Baltasarq 
Did you thoroughly remove all preexisting LXQt components before launching the script? This represents a crucial step.

@tsujan 
Is it versions like [this one](https://github.com/pmattern/lxqt/wiki/Building-From-Source/beba210173de403d38d7b2ac02bcc073096783d1) you have in mind when talking of "older versions"? If so could you elaborate what exactly you think was more informative?

**Comment by tsujan** [comment]
@Baltasarq, did you made deb packages? One of the advantages of deb packaging is that the new package will be installed on the top of the older one and such problems won't happen usually.

@pmattern 
Yes! Instructions like this were helpful for packaging, IMO:
````
$ mkdir build && cd build
$ cmake ..
$ make
$ sudo make install
````

**Comment by tsujan** [comment]
In general and on any Linux distro, making installable packages is really preferable to installing with `sudo make install`, especially when it's about several sources. When ``sudo make install` is used, you couldn't track the installed files, there might be conflicts with the packages that are already installed, etc.

I highly recommend this piece of info is included in https://github.com/lxde/lxqt/wiki/Building-from-source and emphasized.

**Comment by pmattern** [comment]
@tsujan 
The instructions how to build weren't dropped but transferred to files `README.md` of the various components' GitHub repositories. The rationale was to have these instructions as well as information about dependencies sort of tied to the source code as this allows for easy updating in association with corresponding commits.
The drawbacks of not using binary packages should be totally obvious for everybody.
Sure enough what we're discussing here points to a whole different problem: Right now there's no really suitable place to discuss the wiki, the GitHub wiki doesn't feature PRs and the mailing list doesn't seem really suitable either. E. g. I wasn't really happy when I made those major changes to "Building from Sources" a while ago but the old version just had too many flaws so I thought making those changes without thorough discussion is better than leaving the page as-is with regards to the then upcoming release 0.11. But maybe we'll have a forum or some other means to discuss stuff like that in the not too distant future.

**Comment by tsujan** [comment]
@pmattern 
Sorry! That info is factored out in the new version of that page. Anyhow, the older version was really helpful to me, when I wanted to try LXQt for the first time: clean deb packages were made based on it and no problem happened.

IMHO, two things are missing in the new version at least: an explanation about how to compile libfm and libfm-extra (which was clearly explained in the older version) and the above-mentioned emphasis about making installable packages -- I don't think it's obvious for many and a short sentence in italics will be enough.

**Comment by tsujan** [comment]
What I mean is that the new version is good but could be better with the above-mentioned additions.

**Comment by agaida** [comment]
@tsujan - we could setup a working ppa with latest checkouts - but that would require constant maintainance - and to be true it would be the third repo of this kind

**Comment by tsujan** [comment]
@agaida, I understand. It seems that, for now, Ubuntu isn't a good distro for trying LXQt.

**Comment by Baltasarq** [comment]
Fantastic!
I repeated the steps, but before that, I executed:
`sudo apt purge *lxqt*`
...and now, it works perfectly. Version 0.11 is a huge step and deserves to be in the [L]Ubuntu repositories. Why is still not there?

**Comment by pmattern** [comment]
That's nice to hear.

Note the script is not installing 0.11 but the current master (development) branch of all components. IMO this does not represent a problem at all, though. Large parts of the LXQt team are running those versions on their production systems in order to test elaborately. So they are pretty stable unless you happen to pick up a commit where a FTBFS takes place which you obviously didn't.

Aside from the obvious drawbacks of using such a script, in particular not being able to remove the software the same way as when it had been installed via binary packages, we didn't test updating the software by re-running the script thoroughly so far. So if you should update that way from time to time your feedback may help us improve the script if needed.

**Comment by Baltasarq** [comment]
I'm at the bleeding edge!
Okay, I'll tell what happens when rerunning the script. I guess I'll use "git status" in order to know whether something has changed.

**Comment by jotasprout** [comment]
For whatever it's worth, I installed Lubuntu 16.04 recently and installed LXQt in the last 48 hours. I get this message each time I start up as well.

**Comment by tsujan** [comment]
@jotasprout Lubuntu 16.04 is archaic; it's LXQt is so too.

**Comment by jotasprout** [comment]
@tsujan My Dell Vostro 1000 is even more ancient and based on my research, I started with 14.04 and after much more research (and a burning desire for a couple things requiring at least 16.04) only just recently "upgraded" to 16.04.

**Comment by tsujan** [comment]
> only just recently "upgraded" to 16.04.

If I were you, I'd search the Internet to see if it's possible to upgrade to 18.10 on that machine. Linux is always evolving fast.
