### ISSUE TITLE
lxqt-admin-user does not save shell change

### ISSUE THREAD

**Issue by jsm222** [lxde/lxqt#1199]
Under advanced in a users properties, one can change the shell.
But it is not passed to the usermod command.
[patch.txt](https://github.com/lxde/lxqt/files/629836/diff.txt)

`

**Comment by pmattern** [comment]
Confirming both the issue itself and that it's fixed by the patch linked above. Any particular why you didn't submit the patch as regular PR in lxqt-admin?

**Comment by pmattern** [comment]
@jsm222 
Once more, this issue is certainly valid and fixed by your patch, so you deserve the credit.
Don't you want to submit a PR?

**Comment by jsm222** [comment]
Submitted as https://github.com/lxde/lxqt-admin/pull/45.

**Comment by pmattern** [comment]
> Submitted as lxde/lxqt-admin#45.

Great. Thanks again.
