### ISSUE TITLE
I can not change the background image

### ISSUE THREAD

**Issue by garilla22** [lxde/lxqt#1201]
I did everything according to your instructions. 
I have made lightdm-razor-greeter.
I changed the file lightdm-razor-greeter.conf for such content:
`lightdm-razor-greeter.conf

 General configuration
 
 greeter-background = /path/to/background/image to set a background image for the login screen
 loginform-offset-x = how far from the left edge of the screen should the loginform be placed. 
      Can be given in pixes, e.g. loginform-offset-x=60px, or in percentage of screen width, e.g. loginform-offset-x=20%.
 loginform-offset-y = how far from the left edge of the screen should the loginform be placed. 
      Can be given in pixels, e.g. loginform-offset-y=60px, or in percentage of screen width, e.g. loginform-offset-y=20%.

[General]
greeter-background-image=/home/admin/lightdm.png
loginform-offset-x=50%
loginform-offset-y=50%`

The background is not changed! Attached is log /var/log/lightdm/lightdm.log
`[+0.09s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.09s] DEBUG: Starting Light Display Manager 1.10.3, UID=0 PID=744
[+0.09s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.09s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/01_debian.conf
[+0.09s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.09s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.09s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.09s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.09s] DEBUG: Registered seat module xlocal
[+0.09s] DEBUG: Registered seat module xremote
[+0.09s] DEBUG: Registered seat module unity
[+0.09s] DEBUG: Registered seat module surfaceflinger
[+1.18s] DEBUG: Adding default seat
[+1.18s] DEBUG: Seat: Starting
[+1.18s] DEBUG: Seat: Creating greeter session
[+1.46s] DEBUG: Seat: Creating display server of type x
[+1.46s] DEBUG: Could not run plymouth --ping: Failed to execute child process "plymouth" (No such file or directory)
[+1.46s] DEBUG: Using VT 7
[+1.46s] DEBUG: Seat: Starting local X display on VT 7
[+1.46s] DEBUG: DisplayServer x-0: Logging to /var/log/lightdm/x-0.log
[+1.51s] DEBUG: DisplayServer x-0: Writing X server authority to /var/run/lightdm/root/:0
[+1.51s] DEBUG: DisplayServer x-0: Launching X Server
[+1.56s] DEBUG: Launching process 778: /usr/bin/X :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
[+1.56s] DEBUG: DisplayServer x-0: Waiting for ready signal from X server :0
[+1.56s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+1.56s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+1.70s] WARNING: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
[+1.71s] DEBUG: Loading user config from /etc/lightdm/users.conf
[+2.08s] DEBUG: User user added
[+2.08s] DEBUG: User admin added
[+7.08s] DEBUG: Got signal 10 from process 778
[+7.08s] DEBUG: DisplayServer x-0: Got signal from X server :0
[+7.08s] DEBUG: DisplayServer x-0: Connecting to XServer :0
[+7.08s] DEBUG: Seat: Display server ready, starting session authentication
[+7.08s] DEBUG: Session pid=845: Started with service 'lightdm-greeter', username 'lightdm'
[+7.26s] DEBUG: Session pid=845: Authentication complete with return value 0: Success
[+7.26s] DEBUG: Seat: Session authenticated, running command
[+7.26s] DEBUG: Session pid=845: Running command /usr/bin/razor-lightdm-greeter
[+7.26s] DEBUG: Creating shared data directory /var/lib/lightdm/data/lightdm
[+7.26s] DEBUG: Session pid=845: Logging to /var/log/lightdm/x-0-greeter.log
[+7.44s] DEBUG: Activating VT 7
[+7.44s] DEBUG: Activating login1 session c1
[+9.91s] DEBUG: Session pid=845: Greeter connected version=1.10.3
[+32.51s] DEBUG: Session pid=845: Greeter start authentication for admin
[+32.52s] DEBUG: Session pid=856: Started with service 'lightdm', username 'admin'
[+32.56s] DEBUG: Session pid=856: Got 1 message(s) from PAM
[+32.56s] DEBUG: Session pid=845: Prompt greeter with 1 message(s)
[+32.56s] DEBUG: Session pid=845: Continue authentication
[+32.58s] DEBUG: Session pid=856: Authentication complete with return value 0: Success
[+32.58s] DEBUG: Session pid=845: Authenticate result for user admin: Success
[+32.58s] DEBUG: Session pid=845: User admin authorized
[+32.58s] DEBUG: Session pid=845: Greeter requests session LXDE
[+32.58s] DEBUG: Seat: Stopping greeter; display server will be re-used for user session
[+32.58s] DEBUG: Session pid=845: Sending SIGTERM
[+32.64s] DEBUG: Session pid=845: Greeter closed communication channel
[+32.64s] DEBUG: Session pid=845: Exited with return value 15
[+32.64s] DEBUG: Seat: Session stopped
[+32.64s] DEBUG: Seat: Greeter stopped, running session
[+32.64s] DEBUG: Registering session with bus path /org/freedesktop/DisplayManager/Session0
[+32.66s] DEBUG: Session pid=856: Running command /etc/X11/Xsession /usr/bin/startlxde
[+32.66s] DEBUG: Creating shared data directory /var/lib/lightdm/data/admin
[+32.66s] DEBUG: Session pid=856: Logging to .xsession-errors
[+32.89s] DEBUG: Activating VT 7
[+32.89s] DEBUG: Activating login1 session 1`

Attached is log /var/log/lightdm/x-0-greeter.log
`
** (process:851): WARNING **: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
Could not resolve property : linearGradient4248
Could not resolve property : pattern6290
Could not resolve property : pattern6192
Could not resolve property : pattern6992
`

**Comment by palinek** [comment]
> I did everything according to your instructions.

...according to what instructions?

> I have made lightdm-razor-greeter.
I changed the file lightdm-razor-greeter.conf for such content:

Do we (LXQt) recomend to use it?

**Comment by pmattern** [comment]
As @palinek already pointed out the LXQt project does not maintain a display manager on its own but recommends using SDDM.

[Unlike Razor-Qt](https://github.com/Razor-qt/razor-qt/wiki/LightDM-Greeter-Setup) it does not maintain a LightDM theme either. Btw. this greeter seems to be superseeded by [qt-lightdm-greeter](https://github.com/surlykke/qt-lightdm-greeter).

This issue represents a [cross-post](https://github.com/Razor-qt/razor-qt/issues/666), the other issue probably does not make sense either as Razor-Qt is not maintained any longer since it was merged into LXQt.

So all in all I'd say you really have to try and address this elsewhere. If so, you should always state the OS you're running and the versions of all software involved.

**Comment by garilla22** [comment]
> ..according to what instructions?
They are written here: https://github.com/Razor-qt/razor-qt/blob/master/razorqt-lightdm-greeter/resources/lightdm-razor-greeter.conf

> Do we (LXQt) recomend to use it?
I do not like LXQt. I would like to stay on LXDE but continue to Use razor-qt

**Comment by garilla22** [comment]
> So all in all I'd say you really have to try and address this elsewhere if at all. If so, you should always state the OS you're running and the versions of all software involved.
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
I understand everything better and put the other greeter.
