### ISSUE TITLE
lxqt-runner does not respect country settings in calculator mode

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#1202]
In Italy numbers use the comma for decimals, runner does not read at all comma but only dot instead. Dot is used for thousands.
See screens.
![schermata02](https://cloud.githubusercontent.com/assets/10681413/21060123/1663ed9c-be46-11e6-912c-0ea386bad666.png)
![schermata01](https://cloud.githubusercontent.com/assets/10681413/21060124/166a21b2-be46-11e6-9a90-3f8b402bf16f.png)
![schermata](https://cloud.githubusercontent.com/assets/10681413/21060125/167219bc-be46-11e6-8b31-1f745b6f5b7e.png)

**Comment by pmattern** [comment]
Confirmed. Exactly the same findings with locale `de_DE.UTF-8`. lxde/lxqt-runner@05e5370 on Arch Linux.

Did we document that calculator feature somewhere already?

Also, to my knowledge it's not the dot but a blank space that's used for digit grouping in German. Different story, of course.

**Comment by palinek** [comment]
Have a look on lxde/lxqt-runner#52..

**Comment by stefonarch** [comment]
Works well in italian, thanks!
