### ISSUE TITLE
lxqt-common 0.11.1 unbuildable with lxqt-build-tools

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#1204]
```
CMake Error at CMakeLists.txt:7 (find_package):
  Could not find a configuration file for package "lxqt-build-tools" that is
  compatible with requested version "0.1.0".

  The following configuration files were considered but not accepted:

    /usr/share/cmake/lxqt-build-tools/lxqt-build-tools-config.cmake, version: 0.20 (64bit)
```

**Comment by agaida** [comment]
Right - unrfortunally you are to fast  - the first batch of released components now no longer depend on liblxqt - so one has to change the build dependencies for those packages from liblxqt to lxqt-build-tools.

Same changes will be needed for the second batch (qtermwidget, qterminal, libfm-qt, pcmanfm-qt, lximage-qt) - these packages will no longer depend on liblxqt too.
