### ISSUE TITLE
Program uses translation from /usr folder not custom built folder

### ISSUE THREAD

**Issue by scootergrisen** [lxde/lxqt#1205]
I have built LXQt and if i now run ./bin/lxqt-about from the custom folder i have selected with LXQT_PREFIX it uses the translation from /usr folder:
/usr/share/lxqt/translations/lxqt-about/lxqt-about_da.qm

But i want the program to use the translation where i built it.
./share/lxqt/translations/lxqt-about/lxqt-about_da.qm

**Comment by palinek** [comment]
The translation path is built into the [`liblxqt` library](https://github.com/lxde/liblxqt/blob/master/lxqttranslator.cpp#L54). This path is defined based on 'lxqt-build-tools'. If you want the the translations to be taken from your local install, you should build & install lxqt-build-tool, liblxqt, lxqt-_component_ (and of course use the locally installed packages during the build).

But this lead me to a question... shouldn't we been prioritizing the XDG_DATA_DIRS and use the _prebuilt_ static path just as a fallback => that means move the [xdg](https://github.com/lxde/liblxqt/blob/master/lxqttranslator.cpp#L55) before the [static](https://github.com/lxde/liblxqt/blob/master/lxqttranslator.cpp#L54) ?
@luis-pereira @agaida @tsujan @pmattern @PCMan

**Comment by tsujan** [comment]
@palinek, moving xdg before static seems more standard to me.

**Comment by luis-pereira** [comment]
@palinek @tsujan 
The `LXQT_SHARE_TRANSLATIONS_DIR` was put at the list top to allow custom paths to be used.

**Comment by tsujan** [comment]
@luis-pereira 
It's not a big deal at all but wouldn't it be better if custom paths came after more standard ones?

**Comment by palinek** [comment]
> The LXQT_SHARE_TRANSLATIONS_DIR was put at the list top to allow custom paths to be used.

But we are talking about priorities. IMO current environment vars (XDG_DATA_DIRS) should have higher priority than the built int path.

**Comment by luis-pereira** [comment]
@tsujan If they come after, they don't override the standard location.
I also don't want to make a fuzz about this.

**Comment by palinek** [comment]
> If they come after, they don't override the standard location.
I also don't want to make a fuzz about this.

I don't get this. Should the LXQT_SHARE_TRANSLATIONS_DIR (set during build) have higher priority than the XDG_DATA_DIRS (got in run time) or vice versa?

**Comment by palinek** [comment]
Let's discuss this in the proposed PR -> lxde/liblxqt#116
