### ISSUE TITLE
Multiple sound issues on debian 8.5 and lubuntu 16.04

### ISSUE THREAD

**Issue by Serkan-devel** [lxde/lxqt#1206]
I've encountered multiple issues with sound mostly on lxqt.

I screen recorded it because it's getting more and more unusable.
(issues apply both to debian and lubuntu)
https://a.pomf.cat/gmbjou.mkv

Switching from lxde to lxqt on lubuntu made the volume controls broken.

Changing the volume with <kbd>F1</kbd> or <kbd>F2</kbd> never worked on lubuntu or debian (but on default ubuntu and kubuntu).
It actually controlled my HDMI port that never was connected to anything.

Today the sound on my headphones got muted and I couldn't control it manually to make it louder.

**Comment by yan12125** [comment]
Could you try this: right-click on the volume icon, choose ```Configure "Volume Control"``` and choose the correct device.

**Comment by palinek** [comment]
Based on the video, you're controlling the HDM/DisplayPort with the volume plugin in lxqt-panel. Try to change it the volume plugin configuration..

**Comment by palinek** [comment]
> Changing the volume with F1 or F2 never worked on lubuntu or debian (but on default ubuntu and kubuntu).

You can change/edit shortcuts of LXQt components in `lxqt-config-globalkeyshortcuts`

**Comment by Serkan-devel** [comment]
![2016-12-14-183255_1366x768_scrot](https://cloud.githubusercontent.com/assets/16866642/21193282/0c8cd916-c22c-11e6-94e6-926284cc43ed.png)

I can't screenshot it properly but the top selection only gives me HDMI-selections and the bottom one input,output and duplex

But thanks for responding

**Comment by yan12125** [comment]
Well, what you need is this:
![lxqt-volume](https://cloud.githubusercontent.com/assets/1937689/21194154/dc0e2f2c-c269-11e6-8fc2-b1d8acda9839.png)

**Comment by tsujan** [comment]
@Serkan-devel 
My pavucontrol's configuration is the same as yours and this is my Volume Control Settings:

![vcs](https://cloud.githubusercontent.com/assets/981076/21194844/acb54026-c246-11e6-86ca-b314656e7a38.png)

**Comment by Serkan-devel** [comment]
@yan12125 I read your comment again and managed to fix ma sound settings to not-HDMI

Thank you all for helping me here.
