### ISSUE TITLE
lxmenu - settings overkill

### ISSUE THREAD

**Issue by sixsixfive** [lxde/lxqt#1213]
Is there any reason why lxqt lists every single settings desktopentry in the menu? there are already all displayed on the settings manager so can we not just replace the settings submenu with a linkt to lxqt config?

this is how it looks on SuSE:

![screenshot_20161218_181915](https://cloud.githubusercontent.com/assets/3780774/21295330/0f8a6c6c-c553-11e6-8fa9-e5b2057263c1.png)
![screenshot_20161218_182046](https://cloud.githubusercontent.com/assets/3780774/21295331/149badb0-c553-11e6-8555-073f864ecedc.png)

**Comment by tsujan** [comment]
Preferences (Einstellungen) is for all settings you have. If you want any of them hidden, hide it in its desktop file!

**Comment by sixsixfive** [comment]
>Preferences (Einstellungen) is for all settings you have.

and where is the point to show them all on the menu if they are already all displayed on the settings manager? 

>If you want any of them hidden, hide it in its desktop file! 

and then there are hidden in settings manager too - so no point here 

it works on other desktops so its clearly an lxqt bug on how it builds the menu!

**Comment by agaida** [comment]
nope - it isn't - otherwise we wouldn't close this bug again. Maybe our descisions are not the best ones, but again, this is not a bug
