### ISSUE TITLE
Would be nice if Lxqt got :

### ISSUE THREAD

**Issue by ringo32** [lxde/lxqt#1218]
Hi, it would be nice if Lxqt got quicktile option,

currently using https://aur.archlinux.org/packages/quicktile-git/ , is nice, since openbox got no keymoving ? Also would be nice if on Session setting also a Lock session configuration that people can choose which lock screen people want?

**Comment by agaida** [comment]
why should a desktop environment that is WM agnostic have such an option - this is a WM thing, Regarding the session lock - we rely on xdg-screensaver, which is agnostic to the locking provider - so the configurations should be made in the configuration util of the choosen lock app
