### ISSUE TITLE
lxqt-config-appearance > Icon Theme do not update it's own icons

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#1220]
It started happening after: https://github.com/lxde/lxqt-config/commit/1cac4ae0977cdbf240934b62fab94cfe44347c1a
A hack to do it was removed. 

![screen-2016-12-23-13-04-44](https://cloud.githubusercontent.com/assets/62877/21454459/b6237d78-c910-11e6-8e88-f5791ce7088d.png)
![screen-2016-12-23-13-05-10](https://cloud.githubusercontent.com/assets/62877/21454461/bbc4892a-c910-11e6-9428-88c664327eae.png)

**Comment by agaida** [comment]
@luis-pereira - we should revert it asap - sorry, didn't understand the impotance of this bug first place, but i don't get the bug on my local machine - and this has a reason. I forget about that i have a qtbase with the proposed changes for 5.9 running locally - so i couldn't reproduce this regression. 

With this bug the complains about some missed icons form several users make sense

**Comment by agaida** [comment]
@luis-pereira - i think we have an better way to solve that - right now the qtplugin don't pick up the platform things without fixed Qt - so if we fix the qtplugin (with a dummy function that calls the right now not so private Qt stuff) this issue should be gone too
