### ISSUE TITLE
lxqt-panel should give an option to slide windows under it while fullscreen 

### ISSUE THREAD

**Issue by Serkan-devel** [lxde/lxqt#1221]
There is no option for letting windows slide under the panel when full screen.
This then show the desktop background when 100% space isn't used

![image](https://cloud.githubusercontent.com/assets/16866642/21456178/5f228ddc-c926-11e6-8f27-338771acac69.png)

\+ It would be nice if the panel re-sizes automatically when icons are added or removed

**Comment by tsujan** [comment]
"Fullscreen" means covering the whole screen, so, IMO, going behind panel would be a bug, not a feature.

But your second suggestion is about a feature. Task manager should be re-written sooner or later and it'll be nice to consider this feature then.

**Comment by tsujan** [comment]
BTW, fullscreen works OK here: the fullscreen window covers the whole screen and the panel doesn't keep any space for itself. Isn't that so for you?

**Comment by Serkan-devel** [comment]
I'm trying to theme my desktop just like the youtuber <a href='https://www.youtube.com/user/quidsup'>quidsup</a> on kde https://www.youtube.com/watch?v=rxtxcQYWmeY .
It shows how windows in 'fullscreen' slide under the top panel (which is in my case at the bottom).
I actually managed to replicate the desktop from the video (but with some more personalizing) with the panel setting 'let windows slide under it while fullscreen'.

**Comment by palinek** [comment]
@Serkan-devel have a look on lxde/lxqt-panel#389

**Comment by tsujan** [comment]
It's https://github.com/lxde/lxqt-panel/pull/391. It seems @Serkan-devel meant "maximized" by "fullscreen".

**Comment by palinek** [comment]
> It's lxde/lxqt-panel#391.

Of course ... sorry for the typo

**Comment by tsujan** [comment]
It's a good feature, IMO.

**Comment by stefonarch** [comment]
Compiled it but I actually failed first  to understand the effect it does with my openbox configuration, could not find  any different behaviour. Then I remembered  that I had the panel's  amount of pixels  reserved for bottom border in obconf. 

So checking the box will do that, but for all wm's, true?

**Comment by palinek** [comment]
> So checking the box will do that, but for all wm's, true?

All WMs that support the "_NET_WM_PARTIAL_STRUT and _NET_WM_STRUT" ...
