### ISSUE TITLE
How to disable autoplay for removable media?

### ISSUE THREAD

**Issue by HeikoTietze** [lxde/lxqt#1223]
My configuration is to "Show info" when a device is connected. But mounting a SD card loads the default audio player, which is quite annoying when listening to music. System is Arch Linux with KDE that might also have a finger in the pie.

**Comment by palinek** [comment]
> System is Arch Linux with KDE that might also have a finger in the pie.

Probably, as lxqt-panel does not provide such kind of functionality.

**Comment by agaida** [comment]
mime-type fun?

**Comment by HeikoTietze** [comment]
KDE has a system setting 'device actions' with mtp stuff. While it's not possible to delete this entry it can be hacked in the solid config file (cf. https://wiki.archlinux.org/index.php/MTP#kio-mtp but /usr/share/solid/actions/solid_mtp.desktop). The config entry disappears after commenting out the mtp exec line but my audio player still starts.
Second try was to remove libmtp (plus kio-extras and dolphin), which also didn't solve my problem. Removing kio would delete everything, that's not an option.
Mime types are controlled via File Associations. I removed every association for audio and video (actually cleared the application preference order) but KDE ignores me and starts mplayer now instead of qmmp.
