### ISSUE TITLE
"Open as root" on pcmanfm does not seem to work for me. 

### ISSUE THREAD

**Issue by Folatt** [lxde/lxqt#1224]
`System:    Host: MyComputer Kernel: 4.8.14-gnu-1 x86_64 (64 bit)
           Desktop: LXQt Distro: Parabola GNU/Linux-libre `

When I try "Open as Root" I get to enter a password, but then nothing happens after.

**Comment by tsujan** [comment]
What do you have in `Preferences → Advanced → Switch user command`? And what is the version of your installed pcmanfm-qt (`Help → About`)?

**Comment by stefonarch** [comment]
Is "open as root" a service menu (in the menu you get with right-click on file or folder)?
If so what is the content of  the  corresponding *.desktop file in ~/.local/share/file-manager/actions/  ?

**Comment by tsujan** [comment]
@stefonarch I think @Folatt means "Open as root" on the Tool menu.

**Comment by Folatt** [comment]
Yes, I mean in the tool menu.

qterminal.
It's version 0.11.1

**Comment by tsujan** [comment]
> qterminal, switching back to xterm and logging in and out doesn't seem to help

`Switch user command` can be something like `lxsudo %s` (if you have lxsudo) but never `qterminal`. You need a privilege granting program like lxsudo, gksu or kdesu to open GUI apps as root (kdesu is mostly used under KDE).

Yes, "Open as root" on the Tool menu should open a root instance of pcmanfm-qt.

**Comment by Folatt** [comment]
My bad. I accidentaly stated the terminal emulator. 
It was in fact `lxqt-sudo %s`, recently changed back to `lxsudo %s`.

![screenshot from 2016-12-30 16-26-00](https://cloud.githubusercontent.com/assets/9342090/21567480/b45bd5c0-ceac-11e6-97ac-435a9500a025.png)

**Comment by tsujan** [comment]
It's OK. What happens when you put this command into a terminal and press Enter:
````
lxsudo pcmanfm-qt
````

**Comment by Folatt** [comment]
```bash
[folatt@MyComputer ~]$ lxsudo pcmanfm-qt
QXcbConnection: XCB error: 3 (BadWindow), sequence: 704, resource id: 4196563, major code: 40 (TranslateCoords), minor code: 0
```

**Comment by tsujan** [comment]
So, you can't open pcmanfm-qt as root at all?

If that's the case, and since Parabola is based on Arch, you may have got a dbus problem after an update. Please (re-)install `dbus-x11` and try again!

**Comment by stefonarch** [comment]
I noticed similar behaviour on arch,  pcman does start only with 
`lxsudo dbus-launch  pcmanfm-qt `

There was an [issue](https://bugs.archlinux.org/task/50543#comment150936) with dbus change, will do some research, it affects only pcmanfm-qt as I can see.

**Comment by tsujan** [comment]
@stefonarch, yes, I encountered it too. It was because of a bad Arch dbus update months ago. It affected not only pcmanfm-qt but also konsole and some other apps. For me, the simple solution was dbus-x11.

**Comment by stefonarch** [comment]
Uhm, don't like replace dbus with an orfan an outdated package at all, konsole starts well here with lxsudo.
It's more for tracking down the problem, personally I never use the filemanager for changes in the system.

**Comment by Folatt** [comment]
It works with `dbus-x11`. Thanks!

**Comment by tsujan** [comment]
> It works with dbus-x11. 

OK, I think all such problems are caused by and old Arch update.

@stefonarch 
At least in Manjaro, dbus and dbus-x11 have the same version, namely 1.10.14-1; so, dbus-x11 isn't outdated a all. I don't know why Arch dropped dbus-x11 but that decision has caused confusions and problems for so many users.

**Comment by agaida** [comment]
erm - isn't dbus-x11 in arch superseeded by a systemd dbus user session?

**Comment by tsujan** [comment]
dbus is a dependency of systemd and is provided by either dbus or dbus-x11 (they are in conflict with each other). For some reason unknown to me, Arch dropped dbus-x11 but Manjaro (which is Arch based) didn't.

**Comment by tsujan** [comment]
See this, for example: https://www.reddit.com/r/archlinux/comments/50zbdt/dbus_no_longer_compiled_with_x11_support/

**Comment by agaida** [comment]
yeah - found it out myself just now - had to boot my Arch:
```
# dbus-update-activation-environment --systemd --all
dbus-update-activation-environment: error: unable to connect to D-Bus:
 Using X11 for dbus-daemon autolaunch was disabled at compile time,
 set your DBUS_SESSION_BUS_ADDRESS instead
```
no comment :)
