### ISSUE TITLE
Dual monitor settings keep going back to second screen monitor only on every boot.

### ISSUE THREAD

**Issue by Folatt** [lxde/lxqt#1225]
```
System:    Host: MyComputer Kernel: 4.8.14-gnu-1 x86_64 (64 bit)
           Desktop: LXQt (0.11.0-2) Distro: Parabola GNU/Linux-libre 
```

I have two monitors. One connected via HDMI, one to DVI.

My setup is that they are both enabled, the HDMI being my primary display. Res: 1920x1080.
DVI is my extended display, with x=1920, y=0, Res: 1920x1080.

What happens is that when I do a reboot, only the second screen appears and when I open op Monitor settings, the settings for the DVI screen is selected as primary.

**Comment by selairi** [comment]
I will try to fix this issue. Which version of lxqt are you working with?
Is it git version?

Thanks

**Comment by Folatt** [comment]
No, I'm just a regular user who installed LXQt after installing Parabola.

**Comment by selairi** [comment]
Please, I need you do the next test:
1- Boot your system.
2- Open a terminal and write:
   `lxqt-config-monitor -l`
Are the settings now right?
3- Then open lxqt-config-monitor and show me  the "Settings" dialog (Settings button at bottom left). Please double click over your configuration.

I have no idea what is happening, but I think it could be:
_lxqt-config-monitor sends orders to KScreen, but KScreen is sometimes very slow in boot and it is detecting hardware when lxqt-config-monitor starts to send orders to KScreen._
This test could help me in order to find the bug. Please, do it.

**Comment by Folatt** [comment]
```bash
[folatt@MyComputer ~]$ lxqt-config-monitor -l
Output:  "HDMI-0"
Output:  "DVI-0"
[folatt@MyComputer ~]$ lxqt-config-monitor
Connecting to KScreen...
Width x Height 2.59109 x 1.66924
Width x Height 2.59109 x 1.66924
Output:  "HDMI-0"
Width x Height 2.59109 x 1.66924
Output:  "DVI-0"
```

1. Right screen displays screen n1. (Usually this would have been n2)
2. Changes nothing.
3. Makes it go back to normal. 1n1 2n2.

**Comment by fedelibre** [comment]
@selairi Your guess seems to explain my problem.

I have a guest which runs LxQT (version 0.11 of Fedora 27 repository). I noticed that each time I boot the guest, it does not remember the monitor settings I had manually adjusted in previous sessions. (BTW, applications seem to remember: e.g. when I launch a terminal, it opens in a huge window compared to the default small monitor size)
However, when I run `lxqt-config-monitor -l` the monitor resolution becomes correct.

I do have this file in autostart:

     ls -l .config/autostart/lxqt-config-monitor-autostart.desktop 
    -rw-rw-r-- 1 dev dev 183 Jan  3 16:26 .config/autostart/lxqt-config-monitor-autostart.desktop

```
$ cat .config/autostart/lxqt-config-monitor-autostart.desktop 
[Desktop Entry]
Comment=Autostart monitor settings for LXQt-config-monitor
Exec=lxqt-config-monitor -l
Name=lxqt-config-monitor-autostart
OnlyShowIn=LXQt
Type=Application
Version=1.0
```

This is the settings I see in the preferences:

```
Virtual-0:
 Mode: 1920x1080
 Rate: 59.9996 Hz
 Rotation: None
 Position: 0x0
 Primary: True
 Enabled: True
```

Let me know if you need other information.

**Comment by Folatt** [comment]
It's no longer needed. I found out a couple of days ago that I had a newer computer laying around that I forgot all about, so my old computer is going into the trash. I'm closing this issue.

**Comment by MLXQt** [comment]
```
System:
Kernel: 6.1.23-1-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 12.2.1 Desktop: LXQt v: 1.2.1 tk: Qt v: 5.15.8
info: lxqt-panel wm: Openbox v: 3.6.1 vt: 1 dm: SDDM Distro: Manjaro Linux base: Arch Linux
```

Hi,
i have this issue: [https://forum.manjaro.org/t/dual-monitors-issue/138429](https://forum.manjaro.org/t/dual-monitors-issue/138429), that's similar to this one.
I don't know if it's **LXQt** or **Manjaro**, but after the last update the 2 monitors switches.
It seems that the 2 monitors are saved as both `primary=true`.
Any ideas or helps?
Thanks.

**Comment by tsujan** [comment]
> Any ideas or helps?

→ https://github.com/lxqt/lxqt-config/issues/925#issuecomment-1465060151
