### ISSUE TITLE
Question: what push-notification-service is this

### ISSUE THREAD

**Issue by Serkan-devel** [lxde/lxqt#1229]
I have lubuntu 16.04, installed lxqt and deleted lubuntu desktop (somewhat).
I once installed kwin as window manager, but deleted it afterwards.

![auswahl_186](https://cloud.githubusercontent.com/assets/16866642/21587069/75c987c0-d0d8-11e6-80e6-7bb7a6cf0727.png)

But somtimes I get push notifications that look more from lxde (or kde) than from lxqt (which is squareformed and has a close button)

I actually prefer the lxde-notification style and wanted to ask how to set it that way that it always uses it.

**Comment by jleclanche** [comment]
What's the app in question? It looks like it could be coming from a web browser.

**Comment by Serkan-devel** [comment]
I meant with it any app, that hooks up to the system push notifications. The app I used for example is discord, a messaging app. Chrome uses their own push notifications.

**Comment by Serkan-devel** [comment]
![image](https://cloud.githubusercontent.com/assets/16866642/21594822/7f4c5d6e-d127-11e6-9105-0d3bccbe3584.png)
Here some more proof, that also system apps communicate that way

**Comment by palinek** [comment]
The notifications are shown by the `lxqt-notificationd`, which is a LXQt daemon implementing the [_Desktop Notification Specification_](https://developer.gnome.org/notification-spec/).

If you don't like the LXQt's presentation of notifications, you are free to use any other daemon implementing the said specification (as you are running \*buntu... you can choose from packages providing `notification-daemon`).

**Comment by Serkan-devel** [comment]
Trying to delete <code>lxqt-notificationd</code> would also delete <code>lxqt</code> all together.
The package that I want to use is <code>libkf5notifications5</code> that was installed, together with kwin. Is there a way to set that as the notification service from a conf-file?

**Comment by yan12125** [comment]
You may want to disable lxqt-notificationd from lxqt-config-session and start libkf5notifications5 manually.
