### ISSUE TITLE
The network manager application doesn't even works !

### ISSUE THREAD

**Issue by christhegreek** [lxde/lxqt#1230]
The network manager application doesn't even works !
I need to exit and relaunch it for it to work, also when i reboot it doesn't connect to my wifi automatically !
Of course i removed it straight away and installed the nm-applet and everything works fine .
I suggest you to remove this network manager application ASAP !
First thing you are going to do tomorow morning !!
-I like very much the style of ubuntuqt its everything i ever wanted ! THANK YOU !!

PS1: You can add the gnome-do launcher its of great help .

**Comment by tsujan** [comment]
LXQt has no network manager application as far as I know. CMST is the recommended app and works ok here, but it doesn't belong to LXQt. Which app do you mean?

**Comment by christhegreek** [comment]
You don't even know your own distro ?
wow that exceeds my understanding.

2017-01-02 20:53 GMT+02:00 tsujan <notifications@github.com>:

**Comment by palinek** [comment]
> You don't even know your own distro ?

LXQt isn't any distro. LXQt is a bunch of components providing desktop environment and is packaged/provided by many distributions.
1. You didn't specify your distribution or how did you install LXQt, so we aren't able to help you.
2. Style of your post is ... as is and I wouldn't call it _polite_, so don't expect others to do more than is really needed (to be polite) to answer your issue.

**Comment by christhegreek** [comment]
i send it in the wrong repicient then ,sorry but it had your link.

2017-01-03 12:39 GMT+02:00 palinek <notifications@github.com>:

**Comment by palinek** [comment]
> but it had your link.

Please, check what application/component it is (or paste a screenshot of the application), because, as @tsujan said, LXQt doesn't have any network manager application.

**Comment by christhegreek** [comment]
Yes i should be more carefull i talk about the ubuntuqt project a very good
project that uses lxqt and has kde 3d effects it used kdwm or something .
Sorry for any inconvience.

2017-01-03 12:50 GMT+02:00 palinek <notifications@github.com>:
