### ISSUE TITLE
LXQt takes over a minute to start with KWin

### ISSUE THREAD

**Issue by wbsgit** [lxde/lxqt#1231]
I think the problem is kglobalaccel5.
`journalctl -p 3 -xb`
shows: http://pastebin.com/fnzTfT5V

Global hotkeys aren't working after booting, not even ALT+Tab. I had to create my own ~/.config/kglobalshortcutsrc. I found that out here: https://bbs.archlinux.org/viewtopic.php?id=213208

I'm using Arch Linux and lxqt 0.11.0

**Comment by palinek** [comment]
> I think the problem is kglobalaccel5.

> Global hotkeys aren't working after booting, not even ALT+Tab. I had to create my own ~/.config/kglobalshortcutsrc. 

Sorry, but what do you expect the LXQt people to do here?

**Comment by tsujan** [comment]
> I found that out here: https://bbs.archlinux.org/viewtopic.php?id=213208

But that's old, isn't it? I use kwin with LXQt and see no delay at all on Manjaro. Since Manjaro mostly uses Arch packages, there should be no problem on Arch either.

**Comment by wbsgit** [comment]
Well in that case I don't get it. I thought that problem would be related to LXQt.

How did you install kwin? https://wiki.manjaro.org/index.php?title=LXQt_with_kwin

I'm didn't install Oxygen, maybe that's the problem.

**Comment by tsujan** [comment]
> How did you install kwin?

I had a kde-based system and installed LXQt on it. I didn't remove KDE after that because I needed it for testing some apps.

I assure you that LXQt can't have problem with any modular WM. I've tested it with KWin, openbox and even Compiz.

**Comment by tsujan** [comment]
This issue can be closed; as @palinek mentioned, it isn't related to LXQt.

@wbsgit, feel free to add comments or ask questions here!

**Comment by wbsgit** [comment]
Ok, I installed sddm and the error is gone, LXQt is starting much faster. Thank you for your input.

I'd still prefer not using a display manager. I used getty to login: https://wiki.archlinux.org/index.php/Getty#Virtual_console and had exec startlxqt in my .xinitrc.

It's not a LXQt problem though.

**Comment by tsujan** [comment]
> Ok, I installed sddm and the error is gone

Glad to know that your problem is solved! Perhaps sddm has a dependency that kwin needs for its proper functioning... Anyway, KWin isn't 100% modular, although it works quite well with LXQt.

**Comment by wbsgit** [comment]
I guess the problem is that kglobalaccel cannot start before X is started so it provokes this error and tries to start that often as seen in the logfile.
