### ISSUE TITLE
Idea: Delete text in search after starting app via Application menu

### ISSUE THREAD

**Issue by wbsgit** [lxde/lxqt#1233]
It's pretty annoying to delete the search text manually after starting an application. Is this supposed to be this way or is it a bug?

**Comment by tsujan** [comment]
The user may want to run an app several times. It's hard to type app name each time but it's easy to press 'ESC' once (to delete text).

**Comment by tsujan** [comment]
What's annoying with pressing 'ESC'?

**Comment by wbsgit** [comment]
The menu closes when pressing 'ESC' and I have to start it again.

**Comment by tsujan** [comment]
I you want the menu to remain open, you could simply click the "clear button" inside the line-edit.

**Comment by wbsgit** [comment]
Ok, a keyboard shortcut would be nice though.

**Comment by palinek** [comment]
> The menu closes when pressing 'ESC' and I have to start it again.

Does it? On my system the "Search" line edit is focused upon showing the menu and hitting `Esc` clears the contents of it. Only if the line edit is empty, it closes the menu.  So for non-empty "Search" line edit the hitting the `Esc` twice closes the menu.

**Comment by wbsgit** [comment]
Well... I don't know how this happened, but now it isn't closing anymore, I have to press 'ESC' twice to close it...

**Comment by tsujan** [comment]
> Well... I don't know how this happened 

As @palinek explained, focus the search line-edit before pressing `ESC` -- if you don't want to use mouse, just use `Tab` to focus it.

**Comment by ThellraAK** [comment]
I wonder if a tooltip suggestion could be added, this thread is the first it for "lxqt clear search text on start menu" it's really not apparent that escape is going to clear it.

**Comment by stefonarch** [comment]
Check also the settings (right click on menu), default is  not checked "clear search field after action! and many distros don't change that.

**Comment by ThellraAK** [comment]
@stefonarch Thank you so very much.
