### ISSUE TITLE
Get rid of lxqt-common

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#1234]
Really - no joke. lxqt-common is right now a place for files that would fit better in other repositories.

### autostart
lxqt-compton.desktop.in --> compton-conf
lxqt-desktop.desktop.in	--> ()
lxqt-globalkeyshortcuts.desktop.in -->	lxqt-globalkeys
lxqt-notifications.desktop.in -->	lxqt-notificationd
lxqt-panel.desktop.in -->	lxqt-panel
lxqt-policykit-agent.desktop.in	remove dead -->	lxqt-policykit
lxqt-powermanagement.desktop.in -->	lxqt-powermanagement	
lxqt-qlipper-autostart.desktop.in -->	qlipper
lxqt-runner.desktop.in	->	lxqt-runner
lxqt-xscreensaver-autostart.desktop.in

### config
openbox	--> maybe lxqt.config
pcmanfm-qt/lxqt --> maybe lxqt-config
globalkeyshortcuts.conf	-> lxqt-globalkeys
lxqt.conf  --> lxqt-config or lxqt-session
session.conf --> lxqt-session
windowmanagers.conf --> lxqt-session or lxqt-config

### lxqt-panel
menu -- or lxqt-config i guess

### lxqt-themes
graphics
icons
themes

### lxqt-session
xsession - dir	
startlxqt.1	                          
startlxqt.in

**Comment by agaida** [comment]
btw - that would solve problems with downstreams like lubuntu -- they install lxqt-common by default, for which reason ever, maybe inherited from LXDE. As I don't have any problems which packages, that don't work as expected because of, i don't have the enthusiasm and nerves anymore to redirect the fallout because of it in lubuntus direction.

**Comment by luis-pereira** [comment]
I'm in favor of this move.

**Comment by palinek** [comment]
I'm also a fan of this.

**Comment by tsujan** [comment]
Every time I compiled LXQt, lxqt-common seemed a little out of place to me but I thought it was hard to move its elements to other packages. So, if that's possible, I'll like it.

**Comment by agaida** [comment]
ok, some downstreams will hate us, moving things between packages isn't that trivial - but it is better to solve it now than to live with this mess forever.

(for debian and derivatives one has to add Breaks/Replaces in the right packages and places - but this is a one time job)

**Comment by tsujan** [comment]
I guess it'll be a lot of work. Do you want to do it at once or repository by repository? I mean, first moving what should belong to lxqt-config, then lxqt-session then lxqt-panel, etc?

**Comment by agaida** [comment]
na - it isn't a lot of work for us - but i think we should move the files with history - we have done this before with the translations. And yes - i would do this step by step  - simple things first.

**Comment by agaida** [comment]
superseeded by lxde/lxqt#1274
