### ISSUE TITLE
lxqt-build-tools: Move back patch version to liblxqt and components

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#1236]
##### Expected Behavior

liblxqt should provide the own patch version

##### Current Behavior

lxqt-build-tools provide the version - sorry, i noticed this before, but dont see the possible consequences
We need the liblxqt version only in liblxqt - the dependend packages can take the version from liblxqt.
If we use the liblxqt version to mark the release cycle we should only use $major and $minor to do so.
Each binary should handle the own patch version .

##### Possible Solution
Implement the patch version in all packages

##### Context
I would like to see the lxqt-build-tools as a great step forward regarding maintainance and packaging - they work well and ease some things much.  But the centralization has its downsides - especially if we implement proper versions and a cli interface in every component.  Lets have a look at the System information:

##### System Information

* Distribution & Version: obvious 
* Kernel: `uname -a`
* Qt Version: $QtVersion
* liblxqt Version:  0.11.**1**
* Package version:  0.11.**2**

**Comment by agaida** [comment]
Sorry, noticed this first with all consequeces within the release process, my bad.

**Comment by luis-pereira** [comment]
I've got no objections.

**Comment by agaida** [comment]
fixed with lxde/lxqt-build-tools/commit/26eb73cd85
