### ISSUE TITLE
Qt QIcon on lxqt not working

### ISSUE THREAD

**Issue by floatflower** [lxde/lxqt#1237]
##### Expected Behavior
I am developing an app with Qt, and using `QIcon::fromTheme()`, which can make the icons in app change automatically when system icon theme changes.

##### Current Behavior
After calling the function, the icons from theme not work, then I try `QIcon::themeName()` and it shows that the current theme I am using is **hicolor** theme but I am using **breeze** theme. The icons can be change when using `QIcon::setThemeName()`, It seems that Qt cannot get the current theme from lxqt.

##### Possible Solution
I have no idea, but I am tracing Qt source code and lxqt source code now.

##### Steps to Reproduce (for bugs)
```cpp
QPushButton *button = new QPushButton ;
qDebug() << QIcon::themeName () ;
button -> setIcon( QIcon::fromTheme( "accessories-text-editor" ) ) ;
button -> setIconSize ( QSize ( 48 , 48 ) ) ;
ui -> verticalLayout_2 -> addWidget( button ) ; // verticalLayout_2 is custom layout in my app.
```
The console will show `hicolor`, and showing no icon because there is no accessories-text-editor icon in hicolor.
 ```cpp
QPushButton *button = new QPushButton ;
QIcon::setThemeName( "breeze" ) ;
qDebug() << QIcon::themeName () ;
button -> setIcon( QIcon::fromTheme( "accessories-text-editor" ) ) ;
button -> setIconSize ( QSize ( 48 , 48 ) ) ;
ui -> verticalLayout_2 -> addWidget( button ) ; // verticalLayout_2 is custom layout in my app.
```
After adding `QIcon::setThemeName()`, and it works.
In KDE, the icons change with icon theme, and no need to call this function.

##### Context
Actually, it doesn't matter if the function not works, however, after user change their system icon theme, they will find the icon in my app is different from the system.

##### System Information

* Distribution & Version: Ubuntu 16.04.1
* Kernel: 4.4.0-57-generic
* Qt Version: Qt 5.7.1
* liblxqt Version: 0.10.0-1ubuntu1
* Package version:

**Comment by tsujan** [comment]
I can't confirm your finding. Here, `qDebug() << QIcon::themeName();` shows the actual icon name in use.

The problem may be the version of your installed liblxqt: 0.10.0 is old.

**Comment by floatflower** [comment]
Thank you, I will try again later. The stable version of liblxqt0 on Ubuntu is 0.10 and v0.11 is only available on Ubuntu 17.04. I try to update the lib from ppa, however, the dependent package are also too old.
Thank you.

**Comment by floatflower** [comment]
After I update the lib to 0.11.1, it doesn't work neither.

**Comment by tsujan** [comment]
What is `echo $QT_QPA_PLATFORMTHEME` for you? It should be `lxqt`.

**Comment by luis-pereira** [comment]
@floatflower Make sure you have:

- libqtxdg properly installed
- lxqt-plugin properly installed
- QT_QPA_PLATFORMTHEME environment variable set to lxqt

**Comment by palinek** [comment]
> - libqtxdg properly installed
> - lxqt-plugin properly installed

Yes, IMO this is a consequence of libqtxdg (libxdgiconloader) and the lxqt-qtplugin versions discrepancy -> a packaging/building problem.

**Comment by tsujan** [comment]
I'm also sure that this is either a downstream (Ubuntu) issue or caused by an incomplete installation. Ubuntu hasn't provided the best LXQt packages so far.

BTW, @agaida, this was an example of a clear report with the new format :)

**Comment by agaida** [comment]
:) - only one hint - the upcoming zesty might be a good way to try LXQt and develop for it - they was really fast in picking up the new packages.

**Comment by floatflower** [comment]
I changed the url in source.list from Xenial to devel version, and I got the newest version of liblxqt(0.11.1), futhermore, I found that I didn't set $QT_QPA_PLATFORMTHEME variable, I will try later, thanks for your helping.
