### ISSUE TITLE
connman and cmst broken on debian stretch

### ISSUE THREAD

**Issue by Timgit2** [lxde/lxqt#1240]
weekly build of debian stretch, noticed one other thread with others having same issue. 

Seems like connman or cmst is not being built right during installation, cmst ends up being 'broken' and connman doesn't respond at all and blocks network card usage. 

workaround has been to uninstall cmst and connman and i am using WICD instead.

**Comment by luis-pereira** [comment]
@Timgit2 I don't understand what's the relation with LXQt.

**Comment by tsujan** [comment]
This is an old debian issue. Use cmst from Unstable if possible (connman is already in Testing). If not, use your workaround until cmst comes to Testing!

**Comment by tsujan** [comment]
@Timgit2 
As @luis-pereira mentioned, neither connman nor cmst belong to LXQt, although both of them are recommended for use with LXQt.

**Comment by agaida** [comment]
hmm - i would like to know which iso was broken - btw connman and cmst entered testing on Jan. 05 - thy was removed on 2016-12-25 ... (Only for the records - connman was broken because of an incident with a not declared iptables transition - and it took a little bit of time to repair this)

**Comment by Timgit2** [comment]
Sorry, these are installed by default it seems on debian(well, LXQT is only available for testing/unstable branches)

http://forums.debian.net/viewtopic.php?f=20&t=130739 second to last post, solution for OP of thread. i used that iso. but also had same issue with most recently weekly build as of posting the original post.
