### ISSUE TITLE
lxqt-panel: Behavior of bottom panels on multi-monitor setup not intuitive

### ISSUE THREAD

**Issue by kuleszdl** [lxde/lxqt#1241]
When running in multimonitor-mode with differents on the screens, the bottom panels are behaving oddly: Moving the cursor to the buttom leads to the cursor disappearing from the screen instead of stopping at the bottom of the panel.

##### Expected Behavior
Just dragging the mouse down to the task bar and clicking should open the selected app in the task bar.

##### Current Behavior
The user has to "aim" at the element in the taskbar vertically, otherwise the cursor is out of the screen and clicking on an element in the task bar does not have any effect.

As a workaround, the screens can be re-arranged so there is no space below the screen (layout1) but this is not what you want when the physical monitors are not placed like that.

##### Possible Solution
as described

##### Steps to Reproduce (for bugs)
- set monitor layout as in "Layout 1"
- move the cursor to the bottom of a task bar, where an minimized application resides
- click the mouse button to open the application

##### Context
see the attached screenshots

Layout 1 (unaffected, but not the physical layout I want):
![layout1](https://cloud.githubusercontent.com/assets/1338148/21745739/45f6cec8-d532-11e6-9e09-8c534b4cbb9b.png)

Layout 2 (bug occurs):
![layout2](https://cloud.githubusercontent.com/assets/1338148/21745737/33366a28-d532-11e6-9fe1-1e7e3f7130ca.png)

##### System Information
* Distribution & Version: Debian Stretch
* Kernel: 4.8.0-2-amd64
* Qt Version: 5.7.1
* liblxqt Version:  0.11.0
* Package version: 0.11.0-2

**Comment by kuleszdl** [comment]
I just noticed that this might be somehow interrelated with #1197.

**Comment by palinek** [comment]
`lxqt-panel` doesn't anyhow limit mouse cursor movement. That's the job of window manager. So if you wish behavior, as you've described, report it to WM guys.

**Comment by kuleszdl** [comment]
Okay I see. Sorry for the false positive then.

**Comment by pmattern** [comment]
While I agree this probably isn't an upstream LXQt issue I don't see how the window manager should be involved either.

This screenshot
![lxqt-panel_cursor-goes-below](https://cloud.githubusercontent.com/assets/9860801/23318726/dbfd5330-fad3-11e6-88c0-c64149572dc1.png)
is representing a dual-monitor system, the two outputs DVI-0 and VGA-0 are configured as seen in the terminal emulator and marked by light and dark blue respectively. If I've got it right this is a setup similar to the one of the OP when facing the problem.

But when I move the mouse pointer below plugin-taskbar, hypothetically into the area marked by a red border, and click, the corresponding application comes up at once. Same findings with Openbox, KWin and Xfwm4.

So no clue what could have caused the problem but again, I don't see how the window manager should be to blame.

@agaida
Any chance some Debian-specific bits are involved here?

@kuleszdl
At what resolution are your devices running? I'm asking as #1197 seems to affect 4k devices only.
