### ISSUE TITLE
Update clock on wakeup

### ISSUE THREAD

**Issue by ypnos** [lxde/lxqt#1245]
##### Expected Behavior
The world clock always displays the current time.

##### Current Behavior
When waking up from suspend, it can take up to one minute for the clock to display the current time. Before that it shows the time the machine went to sleep.

##### System Information
* Distribution & Version: Arch Linux
* Package version: 0.11.0

**Comment by palinek** [comment]
Does anyone know how to detect the "resume" situation?

**Comment by tsujan** [comment]
I can't confirm this. Here, World Clock is updated in about a second after the laptop lid is opened. Actually, I have an analog Conky clock (written in LUA and Cairo) too but it's updated almost a second after LXQt's World Clock.

IMO, this isn't an LXQt bug.

**Comment by ypnos** [comment]
My CPU is basically idle after wakeup. Which I can see in the sensors plugin, which runs smoothly.

**Comment by tsujan** [comment]
@ypnos, you don't have seconds in your clock, do you? I removed seconds from the clock and saw what you said.

So, this *is* a bug. The fix shouldn't be difficult. The timeout could be set to 1sec and the clock text could be updated according to its settings (not necessarily with timeout). @palinek?

**Comment by palinek** [comment]
> The timeout could be set to 1sec and the clock text could be updated according to its settings (not necessarily with timeout). @palinek?

Actually the timeout is set to exactly fire when the change is needed, that mean 60 seconds if seconds aren't shown. Yes, the easiest way would be to set the timeout to 1 sec no matter if it is needed or not...but that would violate the existing approach to do as few wake-ups as it is necessary.

**Comment by tsujan** [comment]
> Actually the timeout is set to exactly fire when the change is needed, that mean 60 seconds if seconds aren't shown. 

I know, and that's the problem. The timeout can be simply 1sec but the clock text doesn't need to be updated after 1sec. IMO, that's possible with a conditional inside `LXQtWorldClock::timeout()`. I don't think watching suspend/resume is needed -- if possible at all.

**Comment by luis-pereira** [comment]
@tsujan Setting the timeout to 1 sec will trigger not needed computing, IMO.

@palinek 

It should be possible to listen for that kind of signals:
Reference: https://www.freedesktop.org/wiki/Software/systemd/logind/

>  Signals
> 
> Whenever the inhibition state or idle hint changes daemon PropertyChanged signals are sent out to which clients can subscribe.
> 
> The SessionNew(), SessionRemoved(), UserNew(), UserRemoved(), SeatNew(), SeatRemoved() signals are sent each time a session is created or removed, a user logs in or out, or a seat is added or removed. They each contain the ID of the object plus the object path.
> 
> The PrepareForShutdown() resp. PrepareForSleep() signals are sent right before (with the argument True) and after (with the argument False) the system goes down for reboot/poweroff, resp. suspend/hibernate. This may be used by applications for saving data on disk, releasing memory or doing other jobs that shall be done shortly before shutdown/sleep, in conjunction with delay inhibitor locks. After completion of this work they should release their inhibition locks in order not to delay the operation any further. For more information see Inhibitor Locks.

**Comment by tsujan** [comment]
> Setting the timeout to 1 sec will trigger not needed computing, IMO.

How?! It's just about a simple conditional for not updating the clock text unnecessarily?

**Comment by tsujan** [comment]
Moreover, setting timeout to 1sec without clock having the seconds section needs less calculation that using a clock with the seconds section (as I do) -- and even a weak CPU is happy with the seconds section.

**Comment by palinek** [comment]
> It should be possible to listen for that kind of signals:
Reference: https://www.freedesktop.org/wiki/Software/systemd/logind/

And for systems w/o systemd ?

**Comment by luis-pereira** [comment]
@palinek UPower **had** the `Resuming` signal. But it was removed. Newer upower versions no longer emit that signal .It's handled by systemd. Check the [remove commit](https://cgit.freedesktop.org/upower/commit/?id=1ee642e705a63f5ad56a6b55e4bf5c4a64c959b8)
Reference: https://upower.freedesktop.org/docs/UPower.html

For ConsoleKit.... I really don't know. I have to check.

**Comment by luis-pereira** [comment]
@tsujan If we can avoid it, why not ? Actually, it raises an interesting question: how to detect resumes.

> Moreover, setting timeout to 1sec without clock having the seconds section needs less calculation that using a clock with the seconds section (as I do) -- and even a weak CPU is happy with the seconds section.

That's a user choice.

**Comment by tsujan** [comment]
@luis-pereira, the word "avoid" is used for something troublesome. I really don't understand what kind of micro-optimization you're after. I'm just sure that *practically* there's no extra CPU usage with the above-mentioned solution.

**Comment by tsujan** [comment]
I took a quick look at the code again. A sketch:

For an update interval of one minute, `lxqtworldclock.cpp` would keep track of the shown time (not just its text). Then, `setTimeText()` could compare it with the actual time every second and if `|QDateTime::secsTo()| ≥ 1 min`, the label would be updated. `QDateTime::secsTo()` isn't a serious computation; or is it?

Now, apart from theoretical curiosities (which are valid in themselves), if keeping track of suspend/resume has a simpler logic, is more maintainable, and requires less computation, why not.

**Comment by ypnos** [comment]
Since I reported this problem, a small discussion was had and somebody proposed to implement a solution as outlined above. Thanks @tsujan!

@luis-pereira, @palinek I would suggest a pramatic approach here which is to accept the proposed solution (if tsujan is still keen to implement it) and keep optimizations of wakeups as a possible future improvement. In powertop, my system shows roughly 1000 wakeups / second, I am sure one more will not make a significant difference in battery usage.

**Comment by tsujan** [comment]
> it is now time to pick this up again before it starts to rot :)

I agree but @luis-pereira was against my suggestion and preferred tracking resume/suspend instead. Although I still don't think a single clock needs to know about resume/suspend, I'll wait for @luis-pereira's solution.

**Comment by ypnos** [comment]
After several suspends/wakeups (my system is now up for three weeks) my clock is now lagging behind for about 30 seconds.

![clock](https://user-images.githubusercontent.com/8481470/30547161-d85f4e88-9c8e-11e7-8696-c98ac185bc0b.png)

**Comment by agaida** [comment]
@ypnos - please elaborate why it is a LXQt problem if your clock lags.

**Comment by ypnos** [comment]
@agaida It is the clock in lxqt-panel that is lagging behind the system clock. As shown in the screenshot.

**Comment by agaida** [comment]
hmm - i display seconds in every system that is capable to do so (this exclude Windows :P) - so i don't have such problems - and i really think we should check for repaint every second - this should not cause any harms, not even on my oldest machines. 

Additional: I will close any bug immediatly that might come up with lags < 1s :D 

@tsujan, @luis-pereira - what do you think?

**Comment by tsujan** [comment]
@ypnos add seconds to the clock and it won't lag behind.

Yes, this is an issue, whose solution seems easy. I don't know why it isn't fixed yet.

**Comment by tsujan** [comment]
> and i really think we should check for repaint every second - this should not cause any harms, not even on my oldest machines.

That was my suggestion on this same page. And no, that doesn't cause any harm.

**Comment by agaida** [comment]
so let's do this, it's a low hanging fruit

**Comment by tsujan** [comment]
OK. I might add a PR if not busy with other parts of LXQt. After such a long time, this should be fixed; users might not want seconds in their clocks.

**Comment by agaida** [comment]
right

**Comment by tsujan** [comment]
Why do we still have 2 clocks? Didn't we agree that only the world clock should remain? I'll only fix the world clock.

**Comment by palinek** [comment]
> Why do we still have 2 clocks?

It was never finished.... @tsimonq2 did a WIP in lxde/lxqt-panel#408... but it seems abandoned since then.

**Comment by tsujan** [comment]
@palinek Added a comment there -- told my opinion.

**Comment by tsujan** [comment]
@ypnos This should be fixed by https://github.com/lxde/lxqt-panel/pull/425. If you compile lxqt-panel, please test it!

**Comment by ypnos** [comment]
Really have no idea what is going on here:

```
In file included from /usr/include/qt/QtCore/qcoreapplication.h:44:0,
                 from /usr/include/qt/QtWidgets/qapplication.h:44,
                 from /usr/include/qt/QtWidgets/QApplication:1,
                 from /usr/include/lxqt/LXQt/lxqtapplication.h:31,
                 from /usr/include/lxqt/LXQt/Application:1,
                 from /home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.h:32,
                 from /home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:29:
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp: In lambda function:
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:82:29: error: expected primary-expression before ‘enum’
     const QString VERINFO = QStringLiteral(LXQT_PANEL_VERSION
                             ^
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:83:59: error: expected ‘}’ before ‘LXQT_VERSION’
                                            "\nliblxqt   " LXQT_VERSION
                                                           ^
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:83:59: error: initializer-string for array of chars is too long [-fpermissive]
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:83:59: error: expected ‘,’ or ‘;’ before ‘LXQT_VERSION’
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp: In constructor ‘LXQtPanelApplication::LXQtPanelApplication(int&, char**)’:
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:82:29: error: expected ‘)’ before ‘;’ token
     const QString VERINFO = QStringLiteral(LXQT_PANEL_VERSION
                             ^
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:82:29: error: conversion from ‘LXQtPanelApplication::LXQtPanelApplication(int&, char**)::<lambda()>’
to non-scalar type ‘const QString’ requested
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:82:29: error: ‘qstring_literal’ was not declared in this scope
     const QString VERINFO = QStringLiteral(LXQT_PANEL_VERSION
                             ^
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:82:29: note: suggested alternative: ‘QStringLiteral’
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:82:29: error: returning a value from a constructor
     const QString VERINFO = QStringLiteral(LXQT_PANEL_VERSION
                             ^
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp: At global scope:
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:82:29: error: expected unqualified-id before ‘)’ token
     const QString VERINFO = QStringLiteral(LXQT_PANEL_VERSION
                             ^
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:86:44: error: expected constructor, destructor, or type conversion before ‘(’ token
     QCoreApplication::setApplicationVersion(VERINFO);
                                            ^
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:89:5: error: ‘parser’ does not name a type
     parser.setApplicationDescription(QLatin1String("LXQt Panel"));
     ^~~~~~
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:90:5: error: ‘parser’ does not name a type
     parser.addHelpOption();
     ^~~~~~
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:91:5: error: ‘parser’ does not name a type
     parser.addVersionOption();
     ^~~~~~
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:97:5: error: ‘parser’ does not name a type
     parser.addOption(configFileOption);
     ^~~~~~
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:99:5: error: ‘parser’ does not name a type
     parser.process(*this);
     ^~~~~~
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:103:5: error: expected unqualified-id before ‘if’
     if (configFile.isEmpty())
     ^~
/home/johannes/.cache/pacaur/lxqt-panel-git/src/lxqt-panel/panel/lxqtpanelapplication.cpp:105:5: error: expected unqualified-id before ‘else’
     else
     ^~~~
```

**Comment by tsujan** [comment]
It isn't related to the PR. Maybe a `pacaur` issue. I don't see a problem with `makepkg`.

**Comment by ypnos** [comment]
Your patch also looks very reasonable to me. The git just doesn't compile on my system right now so I'm afraid I can't test it. Maybe it's because I only built `lxqt-build-tools` and `lxqt-panel` and the rest is still 0.11.1.

**Comment by tsujan** [comment]
> Maybe it's because I only built lxqt-build-tools and lxqt-panel and the rest is still 0.11.1.

Oh, that may really be the case!

I'm 99% sure that the patch fixes the incorrect time after resume. There's no extra CPU usage because the clock is updated only when needed.

**Comment by tsimonq2** [comment]
@palinek Oh, didn't get any follow-up emails and I didn't think to check, before the end of this weekend I'll have that finished up.

After that, we'll have one clock panel applet, that'll make things so much easier.

**Comment by tsujan** [comment]
@ypnos The patch is merged. Whenever it comes to your system, please tell us if there's still a problem with clock's time after resume -- although it shouldn't be any.
