### ISSUE TITLE
LXQT volume icon doesn work

### ISSUE THREAD

**Issue by szg0000** [lxde/lxqt#1247]
LXQT volume icon on panel does not work on my computer. I can set the percentage of the volume value, but the volume remains the same. I installed LXQt on another computers, and on another computers the volume icon works. Only my PC is affected.

![lxqt_volume_problem](https://cloud.githubusercontent.com/assets/18247040/22073059/90d7b00e-dda4-11e6-9beb-e81226d1ef41.png)

lxqt version: 0.11.1

**Comment by agaida** [comment]
Is the issue template really that hard to use? But i guess that one should make the right settings in the panel plugin configuration page.

**Comment by stefonarch** [comment]
Right click on icon, what did you selectbetween  alsa | pulseaudio | oss ?

**Comment by szg0000** [comment]
Thanks, it works now.
"Pulseaudio" was selected, but within pulseaudio there are two output options. Digital Stereo (HDMI ) and analog stereo. Digital Stereo (HDMI ) was selected by default, this was the problem. The solution was to set to analog stereo.
