### ISSUE TITLE
Freezing caused by fcitx restarting from systray in lxqt-panel

### ISSUE THREAD

**Issue by knokmki612** [lxde/lxqt#1248]
Preparation:

* Install fcitx(IME) in advance

Reproduce step:

1. Execute `fcitx-autostart` in terminal
2. Right click on the fcitx icon from systray in lxqt-panel
3. Click "Restart" entry in context menu

![fcitx context menu](https://i.gyazo.com/e39b2c4b3b98a1a0a6a55ae1e04b7737.png)!

What happens:

* Able to move mouse cursor
* It doesn't reaction to click anyplace
  * systray
  * Applicaiton menu
  * Background(It doesn't appear reqtangle selection when drag the mouse on background)
  * Other application etc.
* Shell doesn't startup when press Ctrl + Alt + f1 for switch to terminal
* I have no idea to shutdown without hard shutdown(long press a power button)

Expected behavior:

Doesn't occur freeze in spite of restarting fcitx, and re-add fcitx icon to systray in lxqt-panel

Environment:

* Gentoo Linux x86_64
* Lxqt 0.11.0
* CPU( `cat /proc/cpuinfo` ) Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz

**Comment by palinek** [comment]
> Shell doesn't startup when press Ctrl + Alt + f1 for switch to terminal

This indicates, that the problem can be even in display manager or X. Because this functionality isn't provided by any of the LXQt components.

**Comment by yan12125** [comment]
Do you use openbox? I've once hit by a bug in openbox that it freezes with XIM. Try to disable XIM in fcitx.

**Comment by knokmki612** [comment]
> Do you use openbox? I've once hit by a bug in openbox that it freezes with XIM. Try to disable XIM in fcitx.

Yes, I'm using lxqt with openbox
I made the following changes in .xprofile

```
  export GTK_IM_MODULE=fcitx                                                      
  export QT_IM_MODULE=fcitx
- export XMODIFIERS=@im=fcitx
+ export XMODIFIERS=@im=none
```

After, It hasn't been reproduced.
I understand this problem was made by xim

Thank you everyone

**Comment by yan12125** [comment]
Glad to see you got a workaround. Openbox is not maintained by LXQt, so if you need a real fix, go to http://openbox.org/wiki/Openbox:Contribute#Bug_reports and report a bug there.
