### ISSUE TITLE
Panel setting - allow it to be covered by apps

### ISSUE THREAD

**Issue by Gibbz** [lxde/lxqt#1253]
##### Expected Behavior
As in kde plasma, it would be good to have an option for the panel to be able to have apps placed in front of it. Then as you mouse over the top of the screen, it comes to the front. Similar to autohide, but without hiding.

##### Current Behavior
This aint possible currently...

##### System Information

* Distribution & Version: qtubuntu 16.04
* Kernel: 4.4
* Qt Version: 
* liblxqt Version:  
* Package version: 0.10

**Comment by palinek** [comment]
Already implemented in lxde/lxqt-panel#391, closing...
