### ISSUE TITLE
LXQT time and date font sizes problem

### ISSUE THREAD

**Issue by szg0000** [lxde/lxqt#1256]
If I want to view the time and the date, the date is not fully visible. Picture attached.
![lxqt_date_time_problems](https://cloud.githubusercontent.com/assets/18247040/22865127/e8dc49dc-f15d-11e6-8be5-555b9c4573d4.png)

##### Possible Solution

**Adding a feature to set the font size of the time and set the font size of the date separately.**

##### Steps to Reproduce (for bugs)

1.  Right Click on the clock
2.  click on Clock settings
3. change the date and time in new line
4.  

##### System Information

* Distribution & Version: Debian stretch
* Kernel: 4.10.0-rc3
* Qt Version: 5.7.1
* liblxqt Version:  
* Package version: lxqt 0.11.1

**Comment by pmattern** [comment]
Allowing for custom font sizes of particular panel plugins is already discussed in #997.

Also, note that #632 may be involved here. In some plugins text happens to get cropped besides sufficient space would be available.

**Comment by stefonarch** [comment]
a) Change panel height
b) choose in clock settings to show it in one line
