### ISSUE TITLE
Faulty focussing due to compiling against Qt 5.8

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#1257]
##### Current Behavior

Auto-hiding is problematic with Qt-5.8.
##### Steps to Reproduce:

(1) Enable auto-hide for a panel;
(2) Show it by putting the cursor on the 4-pix zone and then right click to open its config menu;
(3) Close the menu only by moving the cursor outside the panel and clicking somewhere else;
(4) Put the cursor on the 4-pix zone again to show panel and then move the cursor away.

The Panel doesn't hide here after that. To hide it, I have to click on it first.
##### Context
This issue started to happen after Qt was upgraded to 5.8. I recompiled the latest git version against Qt-5.8 to no avail.

I'm almost sure that this is a regression in Qt (or its x11 support) because I encountered a "focus" problem in Kvantum's x11-drag too (and worked around it by x11-independent drag).

##### System Information

* Distribution & Version: Manjaro Testing (up-to-date)
* Qt Version:  5.8.0-5
* liblxqt Version:  Latest git
* Package version:  Latest git.

EDIT: This problem isn't just in auto-hiding; it's a "lost focus" problem.

**Comment by tsujan** [comment]
I forgot to add that I use kwin; didn't test with openbox but don't think it would make a difference. I also tested with Fusion and different LXQt themes but nothing changed.

The worst part of this problem is that the panel may hide and never show again. Changing desktop can help in such cases.

**Comment by stefonarch** [comment]
I think it's kwin-related, repeating procedure  as above with openbox is fine and works as expected.

**Comment by palinek** [comment]
Just a note: something similar I've reported a while ago https://bugreports.qt.io/browse/QTBUG-51573

**Comment by tsujan** [comment]
@palinek Yes, it's that bug or something very similar to it. Qt5 has been very unkind to x11 :( Should we report the issue at https://bugreports.qt.io/browse/QTBUG-51573 ?

@stefonarch Thanks for confirming with openbox!

**Comment by tsujan** [comment]
Another example: close the main menu by clicking somewhere *outside* panel; then to open the menu again you'll have click on its button twice!

**Comment by pmattern** [comment]
Given this problem probably involves focussing the following findings which I've made since switching to Qt 5.8 may be related, too:

Objects in SDDM's greeter react upon second click only.
This is e. g. affecting all within that horizontal bar at the top of theme maui. The buttons to shut down or reboot as well as the drop-down menu to select the session at the left react upon second click only. 100% reproducible running "bar metal", not within a virtual machine (KVM/QEMU accessed via SPICE), the latter maybe as it's within an X window.

Context menus of panel plugins (LXQt) open upon the second click only.
Steps to reproduce
* Right click on some arbitrary panel plugin, say plugin-volume. Most of the time the context menu will open.
* Click somewhere on the desktop to close the menu.
* Right click the plugin again. The context menu won't open but only upon right clicking another time.

100% reproducible here as well.

The highlighting of buttons in plugin-taskbar as depicted right at the beginning of #971 sometimes persists for apparently no reason.
Here I failed to figure out both when exactly this takes place and how exactly to get rid of it again.

Maybe we should adjust this issue's title.

**Comment by tsujan** [comment]
> Maybe we should adjust this issue's title.

Yes. Please do it -- I can't find the correct words.

This isn't exactly QTBUG-51573. I haven't looked into it deeply (will do when I have time) but the code that fixed QTBUG-51573 isn't removed from `qxcbwindow.cpp`. We should report this bug as soon as possible.

**Comment by tsujan** [comment]
I did some rudimentary tests and concluded that the problem was NOT in qtbase → `qxcbwindow.cpp` → `QXcbWindow::requestActivateWindow()` (that function was suspicious to me at first). The second candidate can be `QXcbWindow::handleButtonPressEvent()`.

**Comment by pmattern** [comment]
Assigning milestone 0.12. I figure we cannot release when compiling against Qt 5.8 causes annoying UX regressions.

**Comment by tsujan** [comment]
Found the cause :) It was `void QXcbWindow::handleXIMouseEvent()` (belonging to `qtbase` → `qxcbwindow.cpp`). I just reversed it to what it was in Qt-5.7.1 (without touching `QXcbWindow::handleXIMouseButtonState()` above it, although it didn't seem needed), recompiled qtbase and the problem disappeared completely -- and not only this problem but also the problem with resizing windows from their size grips. No side effect so far.

@pmattern Can this be proposed as an Arch patch until the problem is (reported and) fixed in Qt?

**Comment by tsujan** [comment]
A handmade diff:
````
diff -ruNp qtbase-opensource-src-5.8.0-orig/src/plugins/platforms/xcb/qxcbwindow.cpp qtbase-opensource-src-5.8.0/src/plugins/platforms/xcb/qxcbwindow.cpp
--- qtbase-opensource-src-5.8.0-orig/src/plugins/platforms/xcb/qxcbwindow.cpp	2017-01-18 17:50:58.000000000 +0330
+++ qtbase-opensource-src-5.8.0/src/plugins/platforms/xcb/qxcbwindow.cpp	2017-02-13 20:26:24.479088468 +0330
@@ -2449,6 +2449,12 @@ void QXcbWindow::handleXIMouseEvent(xcb_
 
     const Qt::MouseButton button = conn->xiToQtMouseButton(ev->detail);
 
+    if (ev->buttons_len > 0) {
+        unsigned char *buttonMask = (unsigned char *) &ev[1];
+        for (int i = 1; i <= 15; ++i)
+            conn->setButton(conn->translateMouseButton(i), XIMaskIsSet(buttonMask, i));
+    }
+
     const char *sourceName = 0;
     if (Q_UNLIKELY(lcQpaXInputEvents().isDebugEnabled())) {
         const QMetaObject *metaObject = qt_getEnumMetaObject(source);
@@ -2458,23 +2464,18 @@ void QXcbWindow::handleXIMouseEvent(xcb_
 
     switch (ev->evtype) {
     case XI_ButtonPress:
-        handleXIMouseButtonState(event);
         if (Q_UNLIKELY(lcQpaXInputEvents().isDebugEnabled()))
             qCDebug(lcQpaXInputEvents, "XI2 mouse press, button %d, time %d, source %s", button, ev->time, sourceName);
         conn->setButton(button, true);
         handleButtonPressEvent(event_x, event_y, root_x, root_y, ev->detail, modifiers, ev->time, source);
         break;
     case XI_ButtonRelease:
-        handleXIMouseButtonState(event);
         if (Q_UNLIKELY(lcQpaXInputEvents().isDebugEnabled()))
             qCDebug(lcQpaXInputEvents, "XI2 mouse release, button %d, time %d, source %s", button, ev->time, sourceName);
         conn->setButton(button, false);
         handleButtonReleaseEvent(event_x, event_y, root_x, root_y, ev->detail, modifiers, ev->time, source);
         break;
     case XI_Motion:
-        // Here we do NOT call handleXIMouseButtonState because we don't expect button state change to be bundled with motion.
-        // When a touchscreen is pressed, an XI_Motion event occurs in which XIMaskIsSet says the left button is pressed,
-        // but we don't want QGuiApplicationPrivate::processMouseEvent() to react by generating a mouse press event.
         if (Q_UNLIKELY(lcQpaXInputEvents().isDebugEnabled()))
             qCDebug(lcQpaXInputEvents, "XI2 mouse motion %d,%d, time %d, source %s", event_x, event_y, ev->time, sourceName);
         handleMotionNotifyEvent(event_x, event_y, root_x, root_y, modifiers, ev->time, source);

````

**Comment by tsujan** [comment]
Reported the problem here: https://bugreports.qt.io/browse/QTBUG-58850

**Comment by tsujan** [comment]
Please comment at the Qt report page if you have additional info -- since I patched Qt on my system, I can't reproduce the problem.

**Comment by tsujan** [comment]
@pmattern I don't think its about compilation *against* Qt-5.8. As far as I remember, the problems happened once Qt was upgraded here but, since I recompiled everything against Qt-5.8 later, I'm not sure.

BTW, I'm alone in QTBUG-58850? It would be overlooked (with an "Incomplete" label) if I didn't persist. Do I see this in a wrong way? Isn't it an annoying bug that affects UX badly?

**Comment by pmattern** [comment]
> I don't think it's about compilation against Qt-5.8.

You mean the problem could also be triggered by upgrading Qt to 5.8 and continuing to use the applications affected by the problem without recompiling them against the new Qt version? If this is what you have in mind, then I can't tell either for similar reasons as you've stated as well: I've rebuilt all applications in question against Qt 5.8 right after installing the latter, and all of them are already rebuilt against Qt 5.8 in the official Arch Linux repositories, too. So it would take quite some effort to test this.
Honestly, I think this isn't worth the pain and we should just wait until the fix mentioned in [QTBUG-58850](https://bugreports.qt.io/browse/QTBUG-58850) makes it into a stable Qt release.

A pity Qt doesn't plan a point release 5.8.1, in particular with regards to an optional next release 0.12 of LXQt.

**Comment by tsujan** [comment]
> Honestly, I think this isn't worth the pain and we should just wait until the fix mentioned...

I agree. I wrongly thought the fix wouldn't come soon (because of the first reply I received  on the report page).

> A pity Qt doesn't plan a point release 5.8.1

But, on the report page, it's written, "Fix Version/s: 5.8.1, 5.9.0 Alpha".

Anyhow, patching is easy and the compilation took only ~15 min here, so anyone can do it until the fixed version comes.

**Comment by tsujan** [comment]
It's got longer than I thought. With every new subversion of Qt-5.8.0 from Arch, I have to recompile qtbase and give it a higher subversion to get rid of those problems and to fool pacman.

**Comment by tsujan** [comment]
Closing this -- it isn't an LXQt issue.
