### ISSUE TITLE
[lxqt-globalkeys] Creating shortcut with only meta key

### ISSUE THREAD

**Issue by jajmo** [lxde/lxqt#1259]
lxqt-globalkeys doesn't allow for the creation of a shortcut with _only_ the meta key. It must be meta + some other key. This is inconvenient, as my meta key isn't currently bound to anything.

**Comment by ralienpp** [comment]
I was about to request the same thing in another issue. The meta-key is in a very handy physical location and it is a shame that it cannot be used on its own.

A default behaviour for this key could be `show main menu`, as this leverages the fact that people are used to this on other platforms (e.g. Windows, Linux Mint).

**Comment by klundry** [comment]
Yes please.  This should be a standard option in all desktop environments in my opinion.

**Comment by tsujan** [comment]
The Meta key is a modifier key; so it should be followed by a non-modifier key.

That being said, I don't think opening the main menu with just the Meta key is impossible. It's a relatively new feature in KDE; maybe we should see how they did it.

Apart from using Meta for the main menu, I don't think it's possible to make a modifier key behave like an ordinary shortcut.

**Comment by stefonarch** [comment]
>  I don't think it's possible to make a modifier key behave like an ordinary shortcut.

Actually I'm using it to change keyboard layout, it is present in the list.
What one can do is execute on login

`xmodmap -e 'keycode 133 = F13`

and assing F13 in mainmenu settings as shortcut.
`

**Comment by tsujan** [comment]
@stefonarch That's another thing. You modify keymaps.

**Comment by stefonarch** [comment]
I know it's a workaround, but I wonder then how only the win key or other modifiers are handled for switching keyboard layouts.
![schermata07](https://cloud.githubusercontent.com/assets/10681413/25526068/35afa2b0-2c12-11e7-8ce9-c2166c2e74d9.png)

**Comment by tsujan** [comment]
>  how only the win key or other modifiers are handled for switching keyboard layouts

Yes but it isn't used as a `QShortcut` that can be assigned freely.

**Comment by ska67** [comment]
I have made a few changes to lxqt-globalkeysd, the daemon. Now the main menu opens with just the super/meta key.
At the moment this is only hard coded, but if there is any interest, maybe I could make it even better.

**Comment by tsujan** [comment]
> if there is any interest, maybe I could make it even better.

Yes, please! It's good to have meta for the main menu.

**Comment by stefonarch** [comment]
meta (left/right win) is also hardcoded for switching keyboard layouts and I'm using this, keep an eye on that.

**Comment by tsujan** [comment]
> meta (left/right win) is also hardcoded for switching keyboard layouts

I use the "menu" key for that but it' a valid point, which means that meta, as the key for calling the main menu, should be configurable. Yet another thing:

*Pressing* meta shouldn't call the menu because meta is a modifier that can be used with other shortcuts. Only its *release* can call the menu.

**Comment by ska67** [comment]
> ..., which means that meta, as the key for calling the main menu, should be configurable.

I'm trying to implement that.

> Only its release can call the menu.

Sure, that is the only way it can work properly. Sorry, I forgot to mention that I have already implemented this on my system.

**Comment by ska67** [comment]
The configuration values are currently saved with the key names from the X11 system. But the X11 function returns the name "Super," not "Meta". I found an interesting post about it: [Mod, Meta, Super … keys?](https://unix.stackexchange.com/a/119219)

Can I use the returned name of the X11 function, or do I have to query the result and change "Super" to "Meta" if necessary. In other words, which name should I prefer for the LXQt system?

**Comment by tsujan** [comment]
I'm with "Meta" but you and other devs know better.

**Comment by ska67** [comment]
What do you think the two Meta-Keys "Super_L" and "Super_R" should be used separately?
The same applies to the keys "Shift_L", "Shift_R", "Control_L", "Control_R", "Alt_L", ...

**Comment by tsujan** [comment]
I don't think such a distinction is needed.

**Comment by ska67** [comment]
Without the distinction, the whole thing is a little more complicated. One shortcut must be triggered on two different key events. This has not been implemented yet.

Should combinations be possible, e.g. Shift+Control+Alt or Alt+Meta and Meta+Alt ?

**Comment by ska67** [comment]
Now I have a working version to use single modifier keys as shortcuts!

But there are still a few inconsistencies. There are key combinations that do not trigger in the program, e.g. Shift+A to write a capital A. However, if the Shift_L key has been registered for a shortcut, the Shift_L+A, Shift_L+B, ... key combinations trigger this shortcut. Not with KeyPress for Shift+A, but with KeyRelease for Shift_L. I do not think it can be changed, because XGrabKey does not provide any information on KeyRelease, if there was a key combination in the KeyPress event before.
Another example would be Control+C if the Control_R or Control_L key were registered for a shortcut.

One possible solution might be to accept only Alt_L, Alt_R, Super_L, and Super_R. But maybe a power user wants to have the possibility to register a shortcut on the right control key. This could be a setting in the configuration file.

Anyway, should I create a pull request? The open questions could then be discussed in other issues.

**Comment by ska67** [comment]
Considering the described side effect, I see the following solutions:

1. Only the super keys should trigger shortcuts on KeyRelease event.
Shift, Control, and Alt modifier keys can be handled by applications. Only the super keys are meant to be used by the operating system.
The changes of the source code could be more specific to the super keys and the KeyRelease event.

1.1. Both super keys, left and right, are treated as single meta key.
Some keyboards do not have two different super keys.

1.2. Left and right super keys can be registered separately.
Normal users may already be overwhelmed.
Integrated actions can not be registered twice, see issue #94. So you can not register the main menu for both super keys.

2. All shift keys should be configurable for shortcuts on the KeyRelease event.
LXQt is used by power users and they know what they are doing.

2.1. The user receives a warning message when registering one of the additional shift keys.
Normal users need to read the warning message: "The use of this key may have unwanted side effects".

2.2. By default, the Shift, Control and Alt keys are disabled
Power users make changes to the settings file to enable the registration of additional shift keys.

2.3. Combinations of shift keys should be possible.
Power users want to register Alt + Super_L and Meta + Alt_R for shortcuts.

**Please vote for a solution or present another!**

**Comment by ska67** [comment]
Should this issue be closed, after the code has been merged?

**Comment by tsujan** [comment]
@ska67 Yes, it should. If the first line of the commit comment is like "Fixes ...", the corresponding issue will be closed automatically after merging.

Looking forward to more PRs from you!
