### ISSUE TITLE
LXQT built-in calculator needed

### ISSUE THREAD

**Issue by szg0000** [lxde/lxqt#1261]
LXQT needs a built-in calculator.
http://extcalc-linux.sourceforge.net/ can be an option.

**Comment by palinek** [comment]
There are many calculators out there. You are free to choose which ever you want. We aren't going to develop next one.

IMO http://www.speedcrunch.org/ is a good choice, as it depends only on Qt.

If you need a pre-installed calculator in your distro, please contact your disro maintainers.

**Comment by pmattern** [comment]
Absolutely agree. We shouldn't make an attempt to re-invent the wheel, and in particular SpeedCrunch is really a good tool.

But note that some basic functionality like this is already provided by lxqt-runner, see e. g. discussion in #1202. (Besides I personally still wonder whether there is some documentation about this available as I only got aware of that feature by stumbling upon #1202.)
