### ISSUE TITLE
Volume Control behaves erratically

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#1263]
##### Expected Behavior
Volume-up/down should increase/decrease volume according to the volume adjust step.

##### Current Behavior
The behavior is erratic, both with shortcut and with mouse wheel:
(1) Volume-up/down doesn't increase/decrease volume by the chosen step. For example, if the step is 5, volume is increased sometimes by 4, sometimes by 3, 5,...
(2) If the volume is increased by the shortcut and then decreased, it won't go back to its previous value.
(3) Mouse wheel doesn't obey the step setting at all.

##### Possible Solution
Actually, I tried to fix the mouse behavior with a simple code but found the general problem.

##### Steps to Reproduce (for bugs)

1. Increase volume by one step by using the shortcut;
2. Decrease it by one step;

Then the volume isn't restored to its previous value. As mentioned above, this is just one example of the erratic behavior.

I found this problem a long time ago and, as a result, never used the Volume Control plugin to set volume; hence forgetting the problem.

##### System Information

* Distribution & Version: Manjaro Testing
* Kernel: 
* Qt Version: 5.8 (but makes no difference)
* liblxqt Version:  Latest git
* Package version: Latest git

**Comment by palinek** [comment]
Which backend are we talking about? ... pulse?

**Comment by tsujan** [comment]
> Which backend are we talking about? ... pulse?

Yes!

I think the root of the problem may be in `audioengine.cpp` and/or `audiodevice.cpp`.

**Comment by tsujan** [comment]
The mouse wheel problem could be easily fixed once the more general problem is fixed.

**Comment by palinek** [comment]
Please, have a look on lxde/lxqt-panel#396

**Comment by pmattern** [comment]
I can confirm the commit proposed in lxde/lxqt-panel#396 is fixing the problem PulseAudio vs. keyboard as depicted in this issue.
But the very same problem is affecting Alsa as well. Any chance this can be fixed, too? IMO this would make a lot of sense as the number of users declining to use PulseAudio is not that small.

**Comment by palinek** [comment]
> The very same problem is affecting Alsa as well, though. Any chance this can be fixed, too? IMO this would make a lot of sense as the number of users declining to use PulseAudio is not that small.

This was a kind of different problem. I tried to fix it in lxde/lxqt-panel#398
