### ISSUE TITLE
./build_all.sh build script stops with Sensors plugin requires lm_sensors message.

### ISSUE THREAD

**Issue by szg0000** [lxde/lxqt#1266]
./build_all.sh build script stops with **Sensors plugin requires lm_sensors** message.
Which dev package do I need to install? I am under Debian.

**Comment by stefonarch** [comment]
Install lm_sensors

Il 08/03/2017 22:59, szg0000 ha scritto:
> *Sensors plugin requires lm_sensors*

**Comment by pmattern** [comment]
All prerequisites to build LXQt from sources are covered by the [corresponding section](https://github.com/lxde/lxqt/wiki/Building-from-source#prerequisites) of wiki page [Building from source](https://github.com/lxde/lxqt/wiki/Building-from-source).

I just gave this another shot on an up-to-date Debian testing system. Everything was building and running flawlessly.

As for Debian, @agaida is maintaining some repositories providing snapshots from current master as well. But I don't know their current status. Also, documentation how to use them doesn't seem to exist.
