### ISSUE TITLE
LXImage charactercoding error

### ISSUE THREAD

**Issue by szg0000** [lxde/lxqt#1269]
LXImage viewer open file panel character coding error. Picture attached.
![lximageviewer_charactercoding_fails](https://cloud.githubusercontent.com/assets/18247040/23832251/8cf12d7e-0731-11e7-802d-880b4ca28372.png)

**Comment by pmattern** [comment]
This should be discussed on the [LXImage-Qt tracker](https://github.com/lxde/lximage-qt/issues).

When opening an issue on the said tracker please include
* all relevant information requested by this tracker's template, besides it isn't implemented there yet. Note we are asking users to provide this information for a reason.
* whether you made some particular setting in "LXQt Locale Configuration" (binary `lxqt-config-locale`)
* which locale is set according to `echo $LANG` when you run into the problem

**Comment by tsujan** [comment]
I think this is a Qt bug I'd encountered elsewhere too. I made a workaround in that case -- only if I could remember what it was ;)

**Comment by szg0000** [comment]
@tsujan 
If you can find where the bug is, I can open an issue in https://bugreports.qt.io

**Comment by tsujan** [comment]
@szg0000 
You correctly opened the issue as https://github.com/lxde/lximage-qt/issues/89. I'll make a PR and tell you there if I find how I fixed the problem in that other case.

**Comment by szg0000** [comment]
I found the solution. The problem was with the "LXQt Locale Configuration". Maybe other program overwrited the country setting. I am closing this issue and open an another with relevant title.
Thanks.
