### ISSUE TITLE
LXQt missing dev package

### ISSUE THREAD

**Issue by szg0000** [lxde/lxqt#1272]
After `git clone --recursive https://github.com/lxde/lxqt.git` 
`./build_all.sh` stops with missing dev package error, but there is no information which package is missing.

```
Building: lxqt-runner using externally specified options: -DCMAKE_BUILD_TYPE=debug   

-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building with Qt5.7.1
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
CMake Error at /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  CMakeLists.txt:42 (pkg_check_modules)



-- Configuring incomplete, errors occurred!
See also "/home/szg/lxqt/lxqt-runner/build/CMakeFiles/CMakeOutput.log".
szg@debian:~/lxqt$
```
* Distribution & Version: Latest git checkout.
* Kernel: 4.10
* Qt Version: 
* liblxqt Version:  
* Package version:

**Comment by yan12125** [comment]
> Building: lxqt-runner using externally specified options: -DCMAKE_BUILD_TYPE=debug

> CMakeLists.txt:42

From the two lines menu-cache is missing: https://github.com/lxde/lxqt-runner/blob/ad6321d/CMakeLists.txt#L42

(From https://github.com/lxde/lxqt, there's an item lxqt-runner @ ad6321d)

The relevant line is replaced in commit https://github.com/lxde/lxqt-runner/commit/05e537073e76b7a1e6e9bcca8df6a91bdf4fb6cf, so the latest commit will tell you what's missing. IMO, in general, it's good to run ```git submodule --remote --merge``` after ```git clone``` for the first time.

At this point the OP's issue should have been resolved. Beyond this specific issue, a more general question is: when to use ```QUIET``` in ```CMakeLists.txt```? For example, in https://github.com/lxde/lxqt-runner/blob/master/CMakeLists.txt, some package finding statements are decorated with QUIET and some others not. Personally I don't use QUIET unless there are too much noise. Maybe we can drop almost all QUIET declarations to make developers' lives easier?

**Comment by szg0000** [comment]
Thanks.
`git submodule update --remote --rebase` helped, we can close this issue. 

I don't know what about using `QUIET` in CMakeLists.txt, need to open another issue for this.

But I had an another problem with compiling:#1273

**Comment by luis-pereira** [comment]
Is this solved ? What was the issue ?

**Comment by szg0000** [comment]
The solution was:`git submodule update --remote --rebase`

**Comment by yan12125** [comment]
Another issue here was some find_package() calls are decorated with QUIET, which is a problem when debugging problems related to missing system packages.

**Comment by luis-pereira** [comment]
@yan12125 commit https://github.com/lxde/lxqt-runner/commit/05e537073e76b7a1e6e9bcca8df6a91bdf4fb6cf changed that.

**Comment by yan12125** [comment]
@luis-pereira Yes. How about removing all other QUIET decorations?

**Comment by luis-pereira** [comment]
@yan12125 I'm not against it.

**Comment by agaida** [comment]
i would prefer this too

**Comment by yan12125** [comment]
Thanks. I don't have time to check all components for now, so I opened an issue #1276 as a reminder.
