### ISSUE TITLE
LXQt missing XCB

### ISSUE THREAD

**Issue by szg0000** [lxde/lxqt#1273]
### LXQt missing XCB development package, but I don't know which package is missing exactly.

```
Building: lxqt-config using externally specified options: -DCMAKE_BUILD_TYPE=debug   

-- Pulling the translations...
From https://github.com/lxde/lxqt-l10n
 * branch              master     -> FETCH_HEAD
Already up-to-date.
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find XCB (missing: XCB_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake/lxqt-build-tools/find-modules/FindXCB.cmake:52 (find_package_handle_standard_args)
  liblxqt-config-cursor/CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/szg/lxqt/lxqt-config/build/CMakeFiles/CMakeOutput.log".
szg@debian:~/lxqt$
```

**Comment by palinek** [comment]
Sorry, but I'm a bit confused about your attitude. Are you going to open an issue for every problem you will face during the build?
If you are trying to compile on you own, you need some knowledge (or need to gain it). To get a build working, many times you need to look into the build recipes and/or source code and keep investigating...

Did you try to look into https://github.com/lxde/lxqt-build-tools/blob/master/cmake/find-modules/FindXCB.cmake#L52 ? And then https://github.com/lxde/lxqt-build-tools/blob/master/cmake/find-modules/FindXCB.cmake#L41.

So the find module is searching `xcb/xcb.h`. E.g. in debian you can find the missing package pretty easily by:
```
$ apt-file search xcb/xcb.h
libxcb1-dev: /usr/include/xcb/xcb.h
```
...in other distros there are similar tools for sure.

**Comment by szg0000** [comment]
My problem is libxcb1-dev already installed, but not found by the compiler.
`locate xcb.h` gives back `/usr/include/xcb/xcb.h`

**Comment by palinek** [comment]
> My problem is libxcb1-dev already installed, but not found by the compiler.
locate xcb.h gives back /usr/include/xcb/xcb.h

Well...that's strange... @luis-pereira?

**Comment by agaida** [comment]
Which distribution?

**Comment by szg0000** [comment]
Debian stretch (sid)

**Comment by agaida** [comment]
sorry, no clue about unstable :p

**Comment by szg0000** [comment]
Are you sure, this issue can be closed with: "sorry, no clue about unstable :p"?
What are the requirements of the compiler to find the XCB dev package?

**Comment by agaida** [comment]
I'm very sure - and i offered you help - in #debian-lxqt - and btw. i maintain the debian packages

**Comment by agaida** [comment]
@szg0000 - have a look into lxqt-build-tools, esp. the cmake modules - so the build tools are needed to find some packages. Without you are lost - distribution indipendend.

**Comment by szg0000** [comment]
Thanks, I have found it in /lxqt/lxqt-build-tools/cmake/find-modules/FindXCB.cmake

```
include(FeatureSummary)
set_package_properties(XCB PROPERTIES
   URL "http://xcb.freedesktop.org/"
   DESCRIPTION "X protocol C-language Binding")

find_package(PkgConfig)
pkg_check_modules(PC_XCB QUIET xcb ${XCB_FIND_COMPONENTS})

find_library(XCB_LIBRARIES xcb HINTS ${PC_XCB_LIBRARY_DIRS})
find_path(XCB_INCLUDE_DIRS xcb/xcb.h PATH_SUFFIXES xcb HINTS ${PC_XCB_INCLUDE_DIRS})

foreach(COMPONENT ${XCB_FIND_COMPONENTS})
	find_library(XCB_LIBRARIES_${COMPONENT} ${COMPONENT} HINTS ${PC_XCB_LIBRARY_DIRS})
	list(APPEND XCB_LIBRARIES ${XCB_LIBRARIES_${COMPONENT}})
	mark_as_advanced(XCB_LIBRARIES_${COMPONENT})
endforeach(COMPONENT ${XCB_FIND_COMPONENTS})

set(XCB_DEFINITIONS ${PC_XCB_CFLAGS_OTHER})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(XCB DEFAULT_MSG XCB_LIBRARIES XCB_INCLUDE_DIRS)
mark_as_advanced(XCB_INCLUDE_DIRS XCB_LIBRARIES XCB_DEFINITIONS)
```

But I don't know how to debug why this module can't find the xcb package. How to modify this module to have a detailed printout to debug where is the problem?

**Comment by agaida** [comment]
only another hint - for debian - you do it the wrong way. But hey, it's linux, so everything is allowed although not recommend - and maybe the build and installtion order as described in the wiki might help.

**Comment by luis-pereira** [comment]
Is this solved ? What was the issue ?
I also have `/usr/include/xcb/xcb.h` and it works fine.

**Comment by agaida** [comment]
@luis-pereira i closed this twelve days before because of now solved lack of understanding how debian dev packages work - if there are any open questions, this is a downstream problem :)

**Comment by luis-pereira** [comment]
@agaida Good to know.
I was away for more than two weeks. Catching up now.
