### ISSUE TITLE
Split up lxqt-common and move some files

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#1274]
Nearly done now, the packages build, install and run as expected. There was some remarks by @palinek about components in cmake - i would suggest to merge it as is and polish later.

This bug superseeds: lxde/lxqt#1234

Pull Requests:
* lxde/compton-conf#41
* lxde/lxqt-panel#405
* lxde/lxqt-notificationd#60
* lxde/lxqt-policykit#28
* lxde/lxqt-powermanagement#50
* lxde/lxqt-runner#54
* lxde/lxqt-session#101
* lxde/pcmanfm-qt#464

**Comment by agaida** [comment]
@luis-pereira - could you have a look?

**Comment by agaida** [comment]
@luis-pereira @tsujan @palinek @jleclanche - any objections to merge this?

**Comment by palinek** [comment]
no objections here

**Comment by tsujan** [comment]
None at all.

**Comment by agaida** [comment]
OK, done - now to the not so nice part. I think, that at least the Arch AUR packages need some adjustment (Conflicting with lxqt-common should be enough) - done this for Debian weeks ago, so it just should work fine with the next release

**Comment by luis-pereira** [comment]
@agaida Where are the themes now ?

**Comment by agaida** [comment]
https://github.com/lxde/lxqt-themes/issues/1

**Comment by tsujan** [comment]
IMHO, it's really good to have a separate package for themes.

**Comment by tsujan** [comment]
A README is missing though.

**Comment by agaida** [comment]
yeah, there are some things to do, but it's a good start

**Comment by tsujan** [comment]
This may be a silly question but is there a simple way to make all packagers aware of this change? Another silly question (I use my own PKGBUILDs): is AUR updated?

**Comment by agaida** [comment]
The nice thing about is, that for the AUR only cosmetic changes are needed. The changed packages compile and build without any change, the only thing is that the relevant packages should mention the conflict to lxqt-common. Otherwise an AUR upgrade will throw an error about files in other package - lxqt-common in that case. So if one remove lxqt-common or lxqt-common-git everything is fine. And i guess thats not to hard to figure out for the common AUR user.

**Comment by tsujan** [comment]
> Otherwise an AUR upgrade will throw an error about files in other package

Yes! I did it by uninstalling and PKGBUILDing from inside KDE and then logged into my new LXQt.
