### ISSUE TITLE
lxqt-runner: view and search by GenericName/Comment

### ISSUE THREAD

**Issue by abika** [lxde/lxqt#1278]
##### Expected Behavior
Search by "screenshot" -> show "Spectacle" as result.

##### Current Behavior
Search by "screenshot" -> no results.

##### Possible Solution
Actually two wishes: 
1. Many (KDE) applications don't have a "Comment" entry in desktop files(*). Please show "GenericName" as fallback. (I guess the code is shared with applications menu and is not only related to runner).
2. Make "Comment" and "GenericName" text searchable. Currently typing "browse" has no results even though Firefox, Opera and Chrome are installed.

(*) [Desktop entry specs](https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s05.html)

Thanks!

**Comment by palinek** [comment]
Actually we are using men-cache here and it currently doesn't provide API for getting the `genericName` key. We need to wait for (the newly created) lxde/menu-cache#15

**Comment by agaida** [comment]
@palinek - lxde/menu-cache#15 is merged, so what does it mean - will we need a new menu cache to use the functionality and it just don't work with an old menu-cache - or need we the new menu cache to use the runner with the changes?

**Comment by palinek** [comment]
>  lxde/menu-cache#15 is merged, so what does it mean

lxde/lxqt-runner#55 can't be compiled with "old" menu-cache... so the second is correct

**Comment by agaida** [comment]
that means in other words - menu-cache must be available in the distributions before we release LXQt - right?
