### ISSUE TITLE
allow window behind task bar option

### ISSUE THREAD

**Issue by Gibbz** [lxde/lxqt#1279]
Currently there is no way to use the task bar like a dock. In that windows full screen or minimised cannot go behind the task bar. Would be good to have an option to enable this feature.

**Comment by palinek** [comment]
1. already reported/requested -> https://github.com/lxde/lxqt/issues/1221
2. already implemented -> https://github.com/lxde/lxqt-panel/commit/4ba40f198781afcaafe01173ffd700ce8812839f

@Gibbz why don't you use the predefined template for reporting issues?
