### ISSUE TITLE
left align window titles

### ISSUE THREAD

**Issue by Gibbz** [lxde/lxqt#1280]
Like ubuntu, KDE etc., would be very good to have an option for left aligned window titles. They look cleaner, and work with a centered top of the screen dock.

**Comment by palinek** [comment]
What do you mean by "left aligned window titles" ?

again: why aren't you using the predefined template for reporting issues?

**Comment by Gibbz** [comment]
i assume the template is only for bug reports. Sorry my bad.

Example here: http://zdnet2.cbsistatic.com/hub/i/r/2016/07/13/35bbdf69-f8d1-45b8-b029-ca64262ff5d6/thumbnail/770x578/76b627b283a3ff27e27a1d86b0c4f5d1/ubuntu-unity-on-windows-10.jpg

The window title "Details" is aligned to the left.

**Comment by palinek** [comment]
That's a window manager job...if the one you're using doesn't support it, you have to report it to its developers.
