### ISSUE TITLE
Build-All Failing

### ISSUE THREAD

**Issue by ferronrsmith** [lxde/lxqt#1281]
Getting the following error when trying to build the entire project

CMakeFiles/Makefile2:174: recipe for target 'src/CMakeFiles/fm-qt.dir/all' failed
make[1]: *** [src/CMakeFiles/fm-qt.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Qt 5.8.0
Ubuntu 16.04.2 LTS

**Comment by luis-pereira** [comment]
Confirmed.

**Comment by agaida** [comment]
With the latest merges (lxqt-common) i think i wrecked the superbuild too, i will take care of that.
