### ISSUE TITLE
Desktop shortcut icon change possibility needed

### ISSUE THREAD

**Issue by szg0000** [lxde/lxqt#1292]
New feature request to have possibility to change the shortcut icons on the desktop.

**Comment by tsujan** [comment]
Could you please be more specific? Where? Shortcut to what?

**Comment by szg0000** [comment]
My problem is I can't change the shortcut icon of firefox.
Picture attached.
![shortcut_icon_change](https://cloud.githubusercontent.com/assets/18247040/25774681/9de18ca8-3294-11e7-8189-3a5823da6c33.png)

**Comment by tsujan** [comment]
You could right-click that symlink to see what's its target an why it doesn't have a proper icon. This isn't related to LXQt desktop.

**Comment by tsujan** [comment]
Symlinks always have the icons of their targets plus a small emblem. To have a good Firefox launcher on your desktop, drag and drop it either from the main menu or from `/usr/share/applications`.
