### ISSUE TITLE
lxqt-about "Build time and date"

### ISSUE THREAD

**Issue by szg0000** [lxde/lxqt#1294]
lxqt-about needs a new information which shows the time&date of the build.

**Comment by yan12125** [comment]
I guess you got the idea from #1293? I think there are better solutions. First, not everyone use lxqt-about, and all components may not be built at the same time. I propose ```--version```, which shows the built git revision of an application and used libraries. Here's a fake example:
```
$ pcmanfm-qt --version
pcmanfm-qt 0.11.3.55.g925541c

Used libraries:
libfm-qt 0.11.2.115.gcd7e750-1
```

**Comment by szg0000** [comment]
Sure. Thanks. But I have a little bit different output:

```
szg@debian:~$ pcmanfm-qt --version
** Message: x-terminal-emulator has very limited support, consider choose another terminal
pcmanfm-qt 0.11.3


```

**Comment by yan12125** [comment]
That's a fake example - nothing are really done yet :)

**Comment by szg0000** [comment]
Ok. But some binaries doesn't accept the `--version` command switch.
In the LXQT about window a new tab would be good to list all the component's versions.
Like this:

## LXQT component versions:
```
compton : ?
libfm : ?
libfm-qt : ?
liblxqt : ?
libqtxdg : ?
libsysstat : ?
lximage-qt : 0.5.1
lxmenu-data  :?
lxqt-about : ?
lxqt-admin : ?
lxqt-build-tools : ?
lxqt-config : ?
lxqt-globalkeys : ?
lxqt-notificationd :?
lxqt-openssh-askpass :?
lxqt-panel : ?
lxqt-policykit : ?
lxqt-powermanagement : ?
lxqt-qtplugin : ?
lxqt-runner : ?
lxqt-session : ?
lxqt-sudo : 0.11.1
lxqt-themes : ?
menu-cache : ?
obconf-qt : ?
pavucontrol-qt : ?
pcmanfm-qt : 0.11.1
qterminal : 0.7.1
qtermwidget : ?
```

**Comment by yan12125** [comment]
> But some binaries doesn't accept the ```--version``` command switch.

It's good to add it, IMO.

By the way, compton is not part of LXQt (the configuration frontend compton-conf is).

**Comment by agaida** [comment]
buildtime and date says absolutly nothing about nothing - but proper version informations would help a lot. And this is true for all of our binaries.

**Comment by agaida** [comment]
the successor of this bug is /lxde/lxqt/issues/1309
