### ISSUE TITLE
lxqt-panel: cannot edit panel to stop crashing

### ISSUE THREAD

**Issue by ScreamingTaco** [lxde/lxqt#1297]
##### Expected Behavior

 
I would like to suggest that you add a way to edit the panel widgets through the main setting configuration menu instead of only by right clicking the panel.

##### Current Behavior

If (or in my case when) I make a change to the panel that causes the panel to crash, there is no way for me to fix it.

##### Context

 I tried to edit the menu entry on lxqt-panel to include entries from Blackarch. However, I am a dumb user who doesn't know what he is doing. After changing the path in the menu configuration section of widget configuration, the panel would only flash for a second, then crash. Since the only way I could find to edit it was via right clicking the panel, there was no way for me to change it back to how it was before. I tried uninstalling lxqt-panel and lxqt itself, but it didn't work. I also tried finding a config file to change the directory the panel looked to, but to no avail.

##### System Information

* Distribution & Version: Arch
* Kernel:  x86_64 Linux 4.10.13-1-ARCH
* Qt Version: 5.8.0-11
* liblxqt Version:  0.11.1-1

**Comment by tsujan** [comment]
> I make a change to the panel that causes the panel to crash, there is no way for me to fix it.

A backtrace, please!

> I would like to suggest that you add a way to edit the panel widgets through the main setting configuration 

There can be more than one panel and each of them can have a separate config; so, the best way of accessing the config dialog of each panel is through right clicking that panel.

> I tried uninstalling lxqt-panel and lxqt itself, but it didn't work

It shouldn't work because the config isn't changed. Try this:

(1) Stop the panel in Configuration Center (lxqt-config) → Session Settings;
(2) Back up and remove `~/.config/lxqt/panel.conf`;
(3) Start the panel in Configuration Center → Session Settings.

But before doing so, please give us a backtrace of the current crash!

**Comment by ScreamingTaco** [comment]
>(1) Stop the panel in Configuration Center (lxqt-config) → Session Settings;
>(2) Back up and remove ~/.config/lxqt/panel.conf;
>(3) Start the panel in Configuration Center → Session Settings.

The above worked. Thanks for your time. Here is the original backtrace if you still want it:

~~~Starting program: /usr/bin/lxqt-panel 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe946d700 (LWP 4948)]
[New Thread 0x7fffe3320700 (LWP 4949)]
[New Thread 0x7fffe2916700 (LWP 4950)]
[New Thread 0x7fffe18d7700 (LWP 4951)]
[Thread 0x7fffe2916700 (LWP 4950) exited]
""
()
[New Thread 0x7fffd36a0700 (LWP 4952)]
WinIdChange 2e00007 handle QWidgetWindow(0x909c00, name="LXQtPanel panel1Window") QScreen(0x72b940, name="LVDS-1")
Another systray is running
link SVGCleanerId_0 hasn't been detected!
link SVGCleanerId_0 hasn't been detected!
link SVGCleanerId_0 hasn't been detected!

Thread 1 "lxqt-panel" received signal SIGSEGV, Segmentation fault.
0x00007ffff79cedb3 in menu_cache_item_ref ()
   from /usr/lib/libmenu-cache.so.3
(gdb) bt full
#0  0x00007ffff79cedb3 in menu_cache_item_ref ()
    at /usr/lib/libmenu-cache.so.3
#1  0x00007ffff79d02a9 in menu_cache_dir_get_children ()
    at /usr/lib/libmenu-cache.so.3
#2  0x000000000047787c in  ()
#3  0x0000000000477adf in  ()
#4  0x000000000046fe03 in  ()
#5  0x00007ffff79ce5c4 in  () at /usr/lib/libmenu-cache.so.3
#6  0x00007ffff770166a in g_main_context_dispatch ()
    at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff7701a20 in  () at /usr/lib/libglib-2.0.so.0
#8  0x00007ffff7701acc in g_main_context_iteration ()
    at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff4a1e07f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#10 0x00007ffff49c78ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#11 0x00007ffff49cfe14 in QCoreApplication::exec() ()
    at /usr/lib/libQt5Core.so.5
#12 0x0000000000434e74 in  ()~~~
