### ISSUE TITLE
Improve lock screen error message if xscreensaver is missing

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#13]
See last comment in razor-qt/razor-qt#320

**Comment by ufukkilicaslan** [comment]
I think it's also the case for lxqt-powermanagement, Lid and idleness watcher setting. The Lock Screen option on lid close does not work and Lock Screen option in idleness watcher does not work, too. Package lxqt in Arch Linux does not offer any screensaver, screenlocker package when installing. Also, I have xscreensaver installed, the daemon is running but these options still do not work. I wonder why.
