### ISSUE TITLE
New UbuntuQT - dvd is not displayed in UEFI mode

### ISSUE THREAD

**Issue by Pepano** [lxde/lxqt#1302]
only start in legacy mode. Ubuntu-desktop Zesty DVD worked wihout problem in UEFI. Any idea?

**Comment by intialonso** [comment]
Did you tried booting from USB? My system is UEFI and the iso boot fine.

2017-05-18 16:35 GMT-05:00 Pepano <notifications@github.com>:

**Comment by Pepano** [comment]
Sri no worked. I testing also more usb creator without success. This iso worked fine only in legacy mode dvd/usb.
In UEFI only mode on my Asus Prime Z270-P:
CD/DVD - no load no boot
Etcher - no load no boot
Easy2Boot/create uefi-.imgPTN - boot but impossible correctly install
Rufus/create uefi USB - boot but impossible correctly install

Iso official Ubuntu 17.04 Zesty always worked from dvd/usb fine and install is without problem in uefi mode.
New UbuntuQT is nice, but I do not know install un uefi mode only...

**Comment by agaida** [comment]
and where is the relation to LXQt?

**Comment by intialonso** [comment]
Oh I didn't noticed this was posted in the lxqt page, please post it in the ISO project page (the links are there). I'm on mobile and can't paste the link.
