### ISSUE TITLE
lxqt-admin-user shows double users and groups entries in Fedora

### ISSUE THREAD

**Issue by TruboXL** [lxde/lxqt#1308]
![duplicate_u_g](https://user-images.githubusercontent.com/12658589/26915106-436cbf54-4c57-11e7-9f75-54aaedf9c3ca.png)
![duplicate_u_g_2](https://user-images.githubusercontent.com/12658589/26915108-4545438c-4c57-11e7-8117-f0ce9a415117.png)

Fedora 26 LXQt

https://bugzilla.redhat.com/show_bug.cgi?id=1459642

Please take a look at Raphael Groner's comments in RHBZ report above...

**Comment by palinek** [comment]
What version of `lxqt-admin` are we talking about? Does "Fedora 26 LXQt" include the last git version of `lxqt-admin`?

**Comment by TruboXL** [comment]
Is there an easy way to check version number? `lxqt-admin-user` and `lxqt-admin-user-helper` doesn't include useful CLI, GUI, nor `man` help page at all to check version numbers, abouts and as such... :dizzy:

Or they are in sync with the entire LXQt DE and components?

Currently from `dnf`, it shows `lxqt-admin-0.11.1-4.fc26.x86_64`

**Comment by palinek** [comment]
> Currently from dnf, it shows lxqt-admin-0.11.1-4.fc26.x86_64

This is enough.... as there are only 2 commits after the 0.11.1 release and non of them touches something reported here.

As I can't reproduce the duplication here.... please, give me a link for some iso, where this behavior can be manifested.

**Comment by TruboXL** [comment]
> please, give me a link for some iso, where this behavior can be manifested.
https://dl.fedoraproject.org/pub/fedora/linux/development/26/Spins/x86_64/iso/Fedora-LXQt-Live-x86_64-26-20170605.n.0.iso

**Comment by palinek** [comment]
I see the problem manifested in virtual machine with the beforementioned iso. I may be doing something wrong, bu t I'm not able to install the system (to make some other testing).... anaconda always freezes after selecting the HDD

**Comment by palinek** [comment]
Some google search gave this debian report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=32370

Can this be also the case for the new fedora?

**Comment by palinek** [comment]
> Can this be also the case for the new fedora?

After editing the /etc/nsswitch.conf, the duplication has gone:
![screenshot](https://user-images.githubusercontent.com/10990929/26963935-9fa2e8aa-4cef-11e7-916f-c7ab3a523966.png)

... also some man pages for `getpwent` on the web are stating that the reported users can be duplicated for multiple sources.... so maybe we should do the check and remove duplicates ourselves.

Btw. the very same applies for SDDM -> https://github.com/sddm/sddm/blob/develop/src/greeter/UserModel.cpp#L58

**Comment by palinek** [comment]
@TruboXL can you, please, check if the lxde/lxqt-admin#47 makes it better for fedora?

**Comment by rapgro** [comment]
@palinek "anaconda always freezes after selecting the HDD"
How much RAM does your VM have? It's a known issue of anaconda to eat your memory, recommendation is to use >2GB at least.

**Comment by palinek** [comment]
> How much RAM does your VM have? It's a known issue of anaconda to eat your memory, recommendation is to use >2GB at least.

Huh... so that's the case... I gave it only 512MB.
