### ISSUE TITLE
Basic CLI-Interface for our binaries

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#1309]
All binaries should provide a basic cli interface. The implementation should use QCommandLineParser.

Help and version should be enough for the first implementation

**Comment by agaida** [comment]
Binaries:
* compton-conf   <br> .. to do ..
* lximage-qt <br> ok
* lxqt-about   <br> .. to do ..
* lxqt-admin-time  <br> .. to do ..
* lxqt-admin-user   <br> .. to do ..        
* lxqt-admin-user-helper   <br> .. to do ..
* lxqt-config  <br> .. to do ..
* lxqt-config-appearance   <br> .. to do ..                                  
* lxqt-config-brightness <br> ok
* lxqt-config-file-associations   <br> .. to do ..                                
* lxqt-config-globalkeyshortcuts  <br> .. to do ..
* lxqt-config-input  <br> .. to do ..
* lxqt-config-locale  <br> .. to do ..
* lxqt-config-monitor  <br> .. to do ..
* lxqt-config-notificationd  <br> .. to do ..
* lxqt-config-powermanagement  <br> .. to do ..
* lxqt-config-session  <br> .. to do ..
* lxqt-globalkeysd <br> ok
* lxqt-leave <br> ok
* lxqt-notificationd <br> .. to do ..
* lxqt-openssh-askpass  <br> .. to do ..
* lxqt-panel <br> ok
* lxqt-policykit-agent  <br> .. to do ..
* lxqt-powermanagement  <br> .. to do ..
* lxqt-runner  <br> .. to do ..
* lxqt-session <br> .. to do ..
* lxqt-sudo <br> ok
* obconf-qt <bt> ok
* pavucontrol-qt <br> ok
* pcmanfm-qt <br> ok
* qterminal <br> ok

**Comment by tsimonq2** [comment]
:+1:

**Comment by agaida** [comment]
done for now
