### ISSUE TITLE
Bump the version of lxqt-build-tools

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#1313]
With the latest changes in lxqt-build-tools we should bump the build-tools-version and depend on the bumped version - and of course send a mail to the list.

##### Expected Behavior
create less havoc

##### Current Behavior
building with the wong version of build tools can create FTBFS 

@luis-pereira - what do you think? I guess we are done with the tools, there are no open issues for it afaik.

**Comment by agaida** [comment]
Thinking about again - just bumping would be enough for now

**Comment by luis-pereira** [comment]
If bumping it is enough, bump it.
I wasn't aware of lxde/lxqt-build-tools@fc0d7970033f8e61f3facca49641ec6311712f07. Im my view it's more a workaround than a "final" fix.

**Comment by agaida** [comment]
You are right - but if we bump the tools version and the needed versions in the single repos we made sure that the new code couldn't be built with old tools anymore. But that isn't the real problem - the real problem is that old code could be built with new tools  - and the new tools don't provide the LXQt Version anymore. But thats a case for the maintainers to figure out - we should mention it in the release notes.

**Comment by agaida** [comment]
You are right, but it does the trick for now - second important change is that the handling of LXQt major and minor is back in liblxqt.
