### ISSUE TITLE
Suggestion + Question

### ISSUE THREAD

**Issue by Berserk82** [lxde/lxqt#1316]
Suggestion: I would like something like this: [The table of equivalents](http://www.linuxrsp.ru/win-lin-soft/table-eng.html), but for LXQt

Question: How can I obtain the latest LXQt on Debian SID (current)?
Is there a package or do I have to build it?

Thanks in advance for either.

Bye, Marco.

**Comment by tsujan** [comment]
For Debian sid, see [here](https://packages.4sid.eu/).

LXQt is designed to be a comfortable, lightweight, classic Qt-based DE. It provides a file manager, panel, image viewer, etc. but, contrary to KDE, it isn't supposed to have a software suite. All Linux programs work fine and can be used under LXQt, although Qt5 ones feel more native.

**Comment by agaida** [comment]
^^ - not sid - snapshots :)

**Comment by Berserk82** [comment]
Well, in truth the suggestion was not about creating a software suite, but just to catalog relevant Qt software (which have little dependencies if possible) to be used with LXQt.

**Comment by tsujan** [comment]
> ... just to catalog relevant Qt software...

I think there's a list but don't remember where. @pmattern made it? (He hasn't been active for a long time -- I miss his accuracy in testing and seeing issues and hope he's fine). There's also a Manjaro list, that can be used under LXQt with any distro: https://wiki.manjaro.org/index.php?title=List_of_Qt_Applications

**Comment by Berserk82** [comment]
Thanks, this is exactly what I were looking for.
