### ISSUE TITLE
There's no option for New Private Window for Firefox

### ISSUE THREAD

**Issue by adnan360** [lxde/lxqt#1319]
_Maybe this is more like a feature request. (I am not sure how to post one so creating an issue.)_

I have added Firefox icon in the lxqt panel's Quicklaunch widget and right clicked it.

##### Expected Behavior
I expect the menu to have an option for New Private Window.

##### Current Behavior
The menu does not have an option for opening a private window.

![firefox-lxqt-2 Screenshot](https://user-images.githubusercontent.com/7857310/27772792-274f5b64-5f8b-11e7-8c9d-7831c7c392e3.png)

Running:
`cat /usr/share/applications/firefox.desktop | grep private`
shows that there are lines related to private window action:
```
Actions=new-window;new-private-window;
[Desktop Action new-private-window]
Name[de]=Neues privates Fenster
Exec=/usr/lib/firefox/firefox --private-window %u
```
But still it does not show such an option.

##### Possible Solution
Maybe to implement such a feature to respect the Actions in the .desktop file.

##### Steps to Reproduce (for bugs)
1. Install Firefox (if not installed already)
2. Open the Application menu and go to Internet section
3. Drag the Firefox icon to the Quick launch widget area
4. Right click on the Firefox icon

##### Context
I love LXQt so far. It has come a long way.

I use private window sometimes. And to load a private window, now I have to start a Firefox normal window and then open a new window. To fight this, I have created a seperate .desktop file for launching the Private window.

But if I install Chromium now, I will have to create a shortcut for it too for Incognito Window, which would be annoying to create and filling up the App menu with unnecessary entries.

I would love to see this feature get implemented to give it a more complete feature set for a usable desktop. This could be also helpful to other things that may enhance the user experience (for example PCManfm-qt opening user folders by right clicking the launchers or LXImage-qt screenshot having options to take screenshots for whole screen or current window or 3 seconds later etc.) This would hopefully make us productive as well.

##### System Information
I am running LXQt 0.11.0 on Manjaro Linux.
* Distribution & Version: Manjaro 17 with LXQt (32 bit)
* Kernel: 4.9.34-1-MANJARO
* Qt Version: 5.9.0
* liblxqt Version:  0.11.1-1
* Package version:

**Comment by agaida** [comment]
My first reaction was "WTF?" - but it would be nice to have. I see some problems in it - the desktop files have to provide the actions, right now i don't know about much Applications that provide these things. But it would be nice to have to react on such actions if defined in the desktop file.

**Comment by tsujan** [comment]
This would be a good feature indeed. @palinek, any idea?

**Comment by palinek** [comment]
> This would be a good feature indeed. @palinek, any idea?

@tsujan Have a look into lxde/lxqt-panel#435 and state your opinion about "enriching" the libqtxdg, please.

**Comment by tsujan** [comment]
@palinek Thanks! So, fast! I'll read the patches soon.

**Comment by tsujan** [comment]
@adnan360, if you compile from git sources, you could try https://github.com/lxde/libqtxdg/pull/142 and https://github.com/lxde/lxqt-panel/pull/435, in that order. With @palinek's patches, all actions should be shown in right-click menus.

**Comment by stefonarch** [comment]
In fact it works flawless:
![schermata-14-11-43-53](https://user-images.githubusercontent.com/10681413/31574710-1d561ae4-b0d5-11e7-9bef-f0aec326df27.png)
