### ISSUE TITLE
Task manager application grouping

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#132]
Split from lxde/lxqt-panel#33. We want an option to group different windows of the same app into one task manager item. Tentative mstone 0.8.

**Comment by paulolieuthier** [comment]
I'm sorry I'm late on this. I'll still to make comments about things I'm not liking. I think this is a very good feature for 0.9, and should block it.

**Comment by jleclanche** [comment]
Agreed, we have a PR that has seen plenty of work.

**Comment by jleclanche** [comment]
@paulolieuthier Status on this!

**Comment by kubanecxxx** [comment]
I am sorry but I am really busy

**Comment by paulolieuthier** [comment]
@jleclanche I think I can handle it before the end of the month.

**Comment by jleclanche** [comment]
@paulolieuthier I'm not comfortable with this PR landing so shortly before a release. I was hoping it would have a full week of testing at least... And at the same time, I don't really want it to be dropped either. Do we need to delay?

**Comment by paulolieuthier** [comment]
Having played more deeply with @kubanecxxx's code, now I don't think it should change that much. It still needs refactoring, though, as IMO it's desorganized (but not its design). But that could wait. What is actually blocking now, and it's of more concern, is the UX/UI. Everybody should test it and give their opinions, and anyone could take this.

**Comment by jleclanche** [comment]
Moved to 1.0 milestone.
