### ISSUE TITLE
Provide the issue template to all repositories with own bug tracker

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#1322]
##### Expected Behavior
I want the issue form in every bugtracker :)

##### Current Behavior
It isn't there

##### Possible Solution
copy it :)

**Comment by agaida** [comment]
* libfm-qt
* pcmanfm-qt
* lxqt-release-foo
* lxqt-themes
* lximage-qt
* obconf-qt
* qterminal
* libqtxdg
* libsysstat
* lxqt-l10n
* compton-conf
* pavucontrol-qt
* lxqt-connman-applet
* qtermwidget
* lxde.github.io

**Comment by tsujan** [comment]
I agree. Recently, I encountered several reports that were hard to decipher even with telepathy, which I don't have.

**Comment by agaida** [comment]
:)

**Comment by agaida** [comment]
so the basics should be there, maybe we must change some sentences before merge but nothing important i guess

**Comment by tsujan** [comment]
I just checked https://github.com/lxde/libfm-qt/commit/aae3b226922eb63f665e23a398f037ddb8e81ecb. Everything is OK. The template is suitable for all. If I had OCD, I might say some sentences could be removed. *But I don't have OCD.* So, GTM for all.

**Comment by tsujan** [comment]
@agaida Can this be closed or do you want to work on the templates further?
