### ISSUE TITLE
PCManFM: Hide files and folders without rename

### ISSUE THREAD

**Issue by mooooonbaby** [lxde/lxqt#1323]
I miss the opportunity to hide some (for me useless) files and folders in pcmanfm that i can't rename. This is the 'lost+found' folder on ext partitions and the folders '$RECYCLE.BIN' and 'System Volume Information' on ntfs partitions. With dolphin i can do this by creating a file '.hidden' with the folders in the directory. is there a feature for that in pcmanfm?

**Comment by stefonarch** [comment]
A .hidden file in the folder with folder names(s) to hide works in pcmanfm-qt too (and may in most file managers)

**Comment by mooooonbaby** [comment]
Yes, it works with pcmanfm-qt, i use the 'non-qt-version'. But it doesn't work with the lost+found folder on ext4 partitions.

**Comment by mooooonbaby** [comment]
Its only half the truth. When i use the tree view the lost+found folder is hidden in the right window (where the subfolders and files are displayed), but not in the left windows. I'm working very intensively with that tree view.

**Comment by tsujan** [comment]
As @stefonarch said, the feature already exists -- I use it for 2 years at least. Closing this.

**Comment by stefonarch** [comment]
I always delete the lost+found folder after formatting, if once you'll need fsck and it  finds any stuff it will recreate it as far as I know.

**Comment by tsujan** [comment]
@stefonarch I always put its name in `.hidden` ;) That's completely harmless. Deleting root owned files/folders is not recommended -- although there are exceptions.

**Comment by mooooonbaby** [comment]
i tested this function again with the last version for pcmanfm-qt on ubuntu 17.04 (before i used pcmanfm-qt 0.10.x on ubuntu 16.04) and it doesn't work. i created the .hidden in my home directory with 'videos'. after f2 the folder 'videos' is hidden in the right panel but not in the left.

are there settings that i have to do? pcmanfm-qt is installed using the lxqt ppa here https://launchpad.net/~lxqt/+archive/ubuntu/ppa

**Comment by agaida** [comment]
@mooooonbaby - we will not support outdated pps's - never ever. try the current code.

**Comment by tsujan** [comment]
As @agaida said and moreover: the tree-view of older versions of pcmanfm-qt had bad bugs, which are fixed in the latest version.

**Comment by mooooonbaby** [comment]
but this is the latest version or not?

**Comment by tsujan** [comment]
@mooooonbaby The packages on that ppa are archaic.
