### ISSUE TITLE
Changing pcmanfm-qt folder font size

### ISSUE THREAD

**Issue by ferronrsmith** [lxde/lxqt#1324]
I am using a 21:9 monitor and pcmanfm-qt font-size way too small. I increased the font in gtkrc and `/.config/pcmanfm-qt/lxqt/settings.conf`, but it doesn't seem to do anything.

Is there something I am missing ? How do you increase the font ? Everything except pcmanfm-qt font-size is increased when gtkrc is modified....

![2017-07-12-205933_4160x1080_scrot](https://user-images.githubusercontent.com/159764/28146069-1a8ab6e6-6745-11e7-9225-918381209016.png)

**Comment by 12471220** [comment]
Hey there, I met the problem too, how did you fix it?
