### ISSUE TITLE
Deal with Q_FOREACH

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#1325]
This isn't a bug but is somehow like https://github.com/lxde/lxqt/issues/1318. Qt doc says about `Q_FOREACH()`:

"Since Qt 5.7, the use of this macro is discouraged. It will be removed in a future version of Qt. Please use C++11 range-for, possibly with qAsConst(), as needed."

It's unfortunate because `Q_FOREACH` is really handy but apparently it should be replaced everywhere. Am I missing something here?

**Comment by fulalas** [comment]
A good explanation: https://www.kdab.com/goodbye-q_foreach/

**Comment by tsujan** [comment]
Done for libqtxdg by @luis-pereira: https://github.com/lxde/libqtxdg/pull/137

**Comment by luis-pereira** [comment]
liblxqt https://github.com/lxde/liblxqt/pull/127

**Comment by tsujan** [comment]
@luis-pereira, @agaida I'll do it for libfm-qt (in the way we agreed on) if you don't mind -- I don't want it to interfere with my non-merged PRs and, also, I want to do some cleanup after the PRs in question are merged.

**Comment by tsujan** [comment]
Oh, sorry, it's already done at https://github.com/lxde/libfm-qt/pull/156 but needs changes (`static_cast`).

**Comment by luis-pereira** [comment]
@tsujan I have a revised https://github.com/lxde/libfm-qt/pull/156.
Will push it after New Year. Can't access it right now.

**Comment by tsujan** [comment]
@luis-pereira No haste! My mind was busy with other things when I wrote that [comment](https://github.com/lxde/lxqt/issues/1325#issuecomment-354619287). Sorry!

**Comment by luis-pereira** [comment]
@tsujan I did not read your post concerning the not merged commits. I have it ready, but if you think it  will be easier to you... please go ahead.

**Comment by tsujan** [comment]
@luis-pereira Please ignore that comment of mine and make any changes you see appropriate! I'll rebase my non-merged PRs if needed.

**Comment by luis-pereira** [comment]
@tsujan PR updated.

**Comment by luis-pereira** [comment]
All repos are now foreach-free.

**Comment by tsujan** [comment]
@luis-pereira Thanks a lot! It was a hard work for sure.

**Comment by luis-pereira** [comment]
@tsujan Not all merged, yet. Check the list https://github.com/lxde/lxqt/issues/1325#issuecomment-353693004
