### ISSUE TITLE
feature request: lxqt-runner could parse also  ~/bin

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#1328]
I've a lot of scripts in ~/bin and cannot launch them with lxqt-runner, would be nice if it would read also this directory.

**Comment by Vladimir-csp** [comment]
Is ~/bin present in $PATH?

**Comment by stefonarch** [comment]
For my user in  ~/.bashrc
`export PATH=$PATH:~/bin/
`

**Comment by agaida** [comment]
one could do this with /$HOME/bin i guess

**Comment by tsujan** [comment]
@stefonarch You use Arch, don't you? Put these lines in `~/.xprofile` and log out/in:
```sh
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
```

**Comment by stefonarch** [comment]
Just tried with full path `PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/home/stef/bin:"` and restarted the session, does not work, tested also ~/.xprofile, no effect in runner either.

**Comment by tsujan** [comment]
Strange again ;) Runner runs all my `~/bin` scripts correctly. I use Manajro, which is exactly like Arch is this respect. Are you sure that your scripts are executable?

**Comment by stefonarch** [comment]
Sure they are executable ;) It's years I use them in terminal windows and there they are found.
Just tested in a clean arch virtualbox, no parsing with ~/.xprofile too.

**Comment by tsujan** [comment]
> Sure they are executable ;)

Sorry for the silly question! I asked it because this was so weird to me and nothing else came to my mind ;)

**Comment by stefonarch** [comment]
You should find out why runner in your installation parses ~/bin instead ;)

**Comment by tsujan** [comment]
Ha ha... :) I've never had problem with `~/bin` in Debian or Manjaro, although Debian and Arch based systems are a little different in this respect if I correctly recall.

**Comment by tsujan** [comment]
A screenshot if it may be of help. If I press Enter, the script will be executed:

![runner](https://user-images.githubusercontent.com/981076/28500684-cb07b6e6-6fe1-11e7-9f7b-44a7092db7af.png)

This is under Manjaro but under Debian, I had the same thing.

I compile and install LXQt with my offline PKGBUILDs (because I need to test my patches).

**Comment by stefonarch** [comment]
That's what I would like, but here only items in /usr/bin are listed.

**Comment by tsujan** [comment]
@palinek might have an answer.

**Comment by palinek** [comment]
This is the part of code, where the check is done... https://github.com/lxde/lxqt-runner/blob/master/providers.cpp#L86

Note: the `CustomCommandProvider` provider doesn't include "search" functionality.... so it only shows the command if you type the whole name

**Comment by stefonarch** [comment]
> Note: the CustomCommandProvider provider doesn't include "search" functionality.... so it only shows the command if you type the whole name

That was it... closing.
