### ISSUE TITLE
Tagging a pre release

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#1329]
##### Context
We should tag a pre-release to give downstreams something at hand to prepare the real release. I would suggest a tag like 0.11.96 - (KDE like). Reason: We killed lxqt-common (packaging changes) and introduced some things that downstreams most likely want to put in separated packages (qtxdg-dev-tools). 

In preparation it would be useful to make the needed ABI bumps right now - as the pre-release is not meant to go into production there should be no further ABI bumps until released, even when the ABI change again.

##### System Information
* Distribution & Version: debian current git
* not relevant

@PCMan @luis-pereira @jleclanche @jubalh @paulolieuthier @tsujan @tsimonq2 @palinek @pmattern and all i should had mentioned but missed.

**Comment by tsujan** [comment]
X.Y.99 is usual for pre-releases.

**Comment by agaida** [comment]
or call it beta or somewhat - having a few numbers left under 100 isn't that bad, just in case ... :)

**Comment by tsujan** [comment]
> having a few numbers left under 100 isn't that bad, just in case

It's good IMO. When I see X.Y.96 for any app, I know that Y will be increased soon. The third number could even go above 100 if needed. "alpha" and "beta" are good too. I agree on either ways.

**Comment by palinek** [comment]
Agreed.

**Comment by luis-pereira** [comment]
Agreed.

**Comment by tsimonq2** [comment]
Agreed.

**Comment by kamilion** [comment]
> When I see X.Y.96 for any app, I know that Y will be increased soon.

I too, share that perception. In addition, it also gives me the expectation that a few more prereleases may or may not occur before a final.

But hey, commit early, test often. :+1:

**Comment by jleclanche** [comment]
I used .9x for the 0.6 line IIRC and it was actually more of a pain than anything else. I recommend just the usual `0.12.0a1`, `0.12.0b1`, `0.12.0rc1` etc like Python does (semver essentially).

**Comment by agaida** [comment]
long done
