### ISSUE TITLE
Panel autohide option

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#134]
Popular feature request, mstone 0.8.

**Comment by paulolieuthier** [comment]
@jleclanche this will probably have to wait, because there are Qt issues with panel's widget activation/deactivation. Maybe @rootzrich is going to figure it out, I couldn't.

**Comment by rootzrich** [comment]
https://github.com/rootzrich/lxqt-panel/commit/ae1888597246e608c5327fccd4fa68273017b8b8
this is my latest. the current state is that all is working fine but some problems are starting when the systray plugin is activated in the panel. so maybe there is a bug there or there is something I haven't understood so far.

**Comment by jleclanche** [comment]
I think we're out of time on this. I'm bumping it off the milestone tomorrow unless a miracle happens :-)
