### ISSUE TITLE
"Aero Glass" like effects / Frosted glass

### ISSUE THREAD

**Issue by StrangeGamerHD** [lxde/lxqt#1344]
The lxqt panel can only be transparent, but I´d really like if you could make these "frosty"
In the pictures, you can clearly see the effect.
While in Plasma, Windows, etc all the panels are made out of frosted glass, so they are less striking.
I´d really like if theme creators would have an option.

![ggg](https://user-images.githubusercontent.com/14961554/29938167-2e206916-8e88-11e7-9de1-de0ee64f3f51.png)
![windows-10-clear-glass-tansparency-e1433766340402](https://user-images.githubusercontent.com/14961554/29938306-a269e2ca-8e88-11e7-9839-d35773a3f364.jpg)

**Comment by StrangeGamerHD** [comment]
(The bottom picture is from Windows)

**Comment by tsujan** [comment]
That's called blurring and depends on the compositor and widget style. Kvantum can make the translucent panel blurred under KWin. On the other hand, Compiz can blur and give a shadow to the panel with any widget style, as the following screenshot shows. In short, this isn't related to LXQt.

![compiz](https://user-images.githubusercontent.com/981076/29940523-c97b1458-8ea4-11e7-8c1d-b2fe09d3f23a.png)

**Comment by tsujan** [comment]
A simple compositor like compton can also do it with appropriate settings.
