### ISSUE TITLE
No folder icon appears in desktop

### ISSUE THREAD

**Issue by mfdzerohour** [lxde/lxqt#1346]
Distribution Manjaro
LXDE 0.11.0
When creating a folder in the Desktop, it creates the folder without icon, only with the name of the folder, to create file it shows the icon.
The same thing only happens on the desktop, in other applications the same is normal.

Image of the same:
https://mega.nz/#!gEoRTJgK!anG_TDOFtSudzZc9lxjBbwUGqX7j5910Es3mmj-ph6g

**Comment by tsujan** [comment]
This can be a problem in your icon theme.

(1) Which icon theme do you use?
(2) What's the icon size on desktop? 48 px?

**Comment by tsujan** [comment]
And you mean LXQt? We don't develop LXDE here.

**Comment by agaida** [comment]
Let's close this. Maybe next time even a manjaro user is able to fill out the bug template - it is there for a reason.

**Comment by tsujan** [comment]
Agreed.

BTW, I'm a Manjaro user ;)

**Comment by agaida** [comment]
@tsujan - but you can fill out forms and much more :D
