### ISSUE TITLE
Project lxqt-qtplugin should be built after libfm-qt

### ISSUE THREAD

**Issue by fulalas** [lxde/lxqt#1347]
Since lxqt-qtplugin now depends on libfm-qt, we should change cmake_repos.list to reflect this modification. Just need to put  line 8 (lxqt-qtplugin \) after line 18 (lxqt-runner \)

**Comment by tsujan** [comment]
@agaida ?

**Comment by agaida** [comment]
i'm make a complete rebuild of my repo right now - and @fualas is right, i will take care of in the next two days.s

**Comment by agaida** [comment]
i just reorderd the repo list and committed it untested - should work, is in the same order as the wiki now. i leave this open until tested.

**Comment by fulalas** [comment]
I've just built from scratch and it's working nice now :)

**Comment by stefonarch** [comment]
Just built all too without issues, deleted a double entry for qtplugin in the wiki build list.

**Comment by agaida** [comment]
thanks, i had to move it - debris :)
