### ISSUE TITLE
"unknown" icon instead of newly installed icons (of apps)

### ISSUE THREAD

**Issue by thx1111** [lxde/lxqt#1349]
For instance, after installing vivaldi-snapshot, for vivaldi there is only the generic gear icon on the panel, and no icon shown in the menu, even though there are vivaldi-snapshot icons in /usr/share/icons/hicolor/.

$ find /usr/share/icons/hicolor/ -iname '*vivaldi*'
/usr/share/icons/hicolor/48x48/apps/vivaldi-snapshot.png
/usr/share/icons/hicolor/256x256/apps/vivaldi-snapshot.png
/usr/share/icons/hicolor/22x22/apps/vivaldi-snapshot.png
/usr/share/icons/hicolor/128x128/apps/vivaldi-snapshot.png
/usr/share/icons/hicolor/32x32/apps/vivaldi-snapshot.png
/usr/share/icons/hicolor/16x16/apps/vivaldi-snapshot.png
/usr/share/icons/hicolor/24x24/apps/vivaldi-snapshot.png
/usr/share/icons/hicolor/64x64/apps/vivaldi-snapshot.png

In contrast, for instance, the opera-developer and firefox icons display properly.

So, what might cause lxqt-panel to not find the correct icon for the application?

$ grep -v 'Comment\|Generic'  /usr/share/applications/vivaldi-snapshot.desktop
[Desktop Entry]
Version=1.0
Name=Vivaldi (snapshot)
...
Exec=/usr/bin/vivaldi-snapshot %U
Terminal=false
Icon=vivaldi-snapshot
Type=Application
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;image/webp;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;

$cat .config/lxqt/panel.conf
...
[quicklaunch]
alignment=Left
apps\1\desktop=/usr/share/applications/org.kde.konsole.desktop
apps\2\desktop=/usr/share/applications/org.kde.kstars.desktop
apps\3\desktop=/usr/share/applications/thunderbird.desktop
apps\4\desktop=/usr/share/applications/pavucontrol.desktop
apps\5\desktop=/usr/share/applications/firefox.desktop
apps\6\desktop=/usr/share/applications/opera-developer.desktop
apps\7\desktop=/usr/share/applications/vivaldi-snapshot.desktop
apps\size=7
type=quicklaunch
...

$ ps wax|grep lxqt
  765 tty1     Sl     0:04 lxqt-session
  812 tty1     S      0:07 openbox --config-file /home/james/.config/openbox/lxqt-rc.xml
  816 tty1     Sl     0:07 pcmanfm-qt --desktop --profile=lxqt
  817 tty1     Sl     0:03 lxqt-globalkeysd
  818 tty1     Sl     0:03 lxqt-notificationd
  819 tty1     Sl     3:48 lxqt-panel
  820 tty1     Sl     0:02 lxqt-policykit-agent
  821 tty1     Sl     0:04 lxqt-runner
  899 tty1     Sl     0:03 lxqt-powermanagement

##### System Information
* Distribution & Version:  Arch
* Kernel:  linux 4.13.1-1
* Qt Version: qt5-base 5.9.1-3
* liblxqt Version:  liblxqt 0.11.1-1
* Package version: lxqt-panel 0.11.1-1

**Comment by stefonarch** [comment]
Cannot reproduce this on  arch with up-to-date git packages.
![schermata-16-16-14-34](https://user-images.githubusercontent.com/10681413/30512929-449938d4-9afa-11e7-9587-9252c945d188.png)

**Comment by thx1111** [comment]
Hmm - so, I notice that after restarting lxqt, the icon shows normally.

Is this the way it should work, that the icon is not found until after an lxqt restart?

If that is "normal", then please close this bug.

Or, is this something that was a little quirky, and that likely has been addressed in the up-to-date git packages?

**Comment by stefonarch** [comment]
No idea, I just installed vivaldi-snapshot and icons and menu entries were present as ever, immediately without reboot, so I guess this is a problem of your configuration. You could try disinstalling, reboot, and reinstalling to verify if it happens again. Sometimes using a clean user/home directory for testing  is useful to exclude personal configuration influences.

**Comment by tsujan** [comment]
I saw something similar once -- a few days ago -- but it wasn't about installation or package removal but about changing the icon theme: the Reboot icon was shown as "unknown", while it existed in the theme. It was fixed after restarting the panel.

I don't know if the cause is the same but I think there's a problem somewhere. In our icon engine? Or in Appearance dialog?

That being said, like @stefonarch, I cannot reproduce the issue reported *here*.

@thx1111 Arch non-git packages aren't up-to-date; Arch lxqt-panel isn't updated since 2017-01-30.

**Comment by thx1111** [comment]
Way off on a tangent - when does lxqt decide to bump the release,  to 0.11.2?  That would trigger an Arch update.

If I stumble onto this icon problem again, is there some simple way to poke at this *while* it's happening?  Is this sort of thing likely to be in lxqt-panel itself?  Or, are the icon engine and Appearance dialog distinct and separate?  Does the icon update magic happen from the panel's "plugin-statusnotifier"?

**Comment by tsujan** [comment]
@thx1111 If you see *this* problem -- in contrast to the issue I mentioned above -- after the new release, please report back here! As we said, we can't reproduce it with the latest git LXQt.

**Comment by tsujan** [comment]
@thx1111 Never mind! Strangely enough, I encountered exactly the same issue after installing `onboard` (a gtk app). Its icon was "unknown" both in pcmanfm-qt and on the main menu at first. I restarted them and the icon became OK.

This *is* a bug.

@palinek Any idea why this happens? `onboard` puts its icons in `hicolor`.

**Comment by tsujan** [comment]
Somewhere in the code, "unknown" is picked up instead of the correct icon *when the latter is added during a session*. After the session is restarted, the correct icon will be picked up.

**Comment by palinek** [comment]
> @palinek Any idea why this happens? onboard puts its icons in hicolor.

Can it be connected to the gtk icon cache, which is used for speeding up finding the icon?

**Comment by tsujan** [comment]
> Can it be connected to the gtk icon cache, which is used for speeding up finding the icon?

Yes, that's possible. I should find a way to test without it. Maybe later.

**Comment by tsujan** [comment]
IMO, this is a serious issue. Showing newly installed icons "on the fly" is a basic functionality that LXQt should provide.

**Comment by agaida** [comment]
but we should solve it after the release i guess - thats what point releases are for.

**Comment by tsujan** [comment]
> but we should solve it after the release i guess

OK. I guess most LXQt members use comprehensive icon sets and, because of that, this problem has been remained hidden for a long time.

**Comment by agaida** [comment]
Right.

**Comment by tsujan** [comment]
This is most probably related to the gtk icon cache, as @palinek said. Although it's hard to be sure, apparently, it doesn't happen when I remove the lines related to cache from `XdgIconLoader::findIconHelper()`.

I tested with an app, whose icon didn't exist in any icon set I had, namely Retext. With the cache lines, its icon was "unknown" when I installed it. Then I removed it, removed the cache lines, compiled and installed the changed `libqtxdg`, logged out and in, and at last, installed Retext. This time, its icon was shown correctly.

After that, I removed Retext, installed the default `libqtxdg`, logged out and in, and installed Retext: the "unknown" icon again!

There are always apps whose icons can't found in *any* icon set. So, this a bad bug. Our way of consulting the gtk icon cache should be wrong somehow.

**Comment by luis-pereira** [comment]
I was unaware of this.
@tsujan After you install the app, is the icon cache rebuilt ?

**Comment by tsujan** [comment]
@luis-pereira I don't know but this happens with all apps whose icons doesn't exist yet. Please test with Retext or calibre from AUR -- hopefully their icons aren't anywhere except in their packages.

**Comment by luis-pereira** [comment]
@tsujan I can't reproduce it.
What's the output of `qtxdg-iconfinder retext` ?

**Comment by tsujan** [comment]
@luis-pereira  I think I found the mistake that causes this issue.... it needs some tests.

**Comment by tsujan** [comment]
Ha ha.. I'm just searching for a small AUR app (other than retext), whose icon doesn't exist here and I've never installed before ;) Testing retext gave a positive result.

**Comment by tsujan** [comment]
OK, it doesn't happen after https://github.com/lxde/libqtxdg/pull/148.

**Comment by luis-pereira** [comment]
@tsujan mmm That's a bug imported from Qt QIconLoader.

**Comment by tsujan** [comment]
> That's a bug imported from Qt QIconLoader.

I thought it was *our* typo.

**Comment by luis-pereira** [comment]
It's code "imported" from Qt own qiconloader.I'm not completely sure about what it is. 
I can't test it right now. I don't have a development setup in this machine. Just look at code. 

`QIconCacheGtkReader::lookup()` can modify `m_isValid`, so checking if the cache is valid again might not be a bad idea.
What's your thoughts about `if (cache->isValid() && !result.isEmpty())` ?

**Comment by tsujan** [comment]
@luis-pereira Although it'll be strange if a function with the name of `lookup` changes a variable (bad naming?), you might be right. Actually, that came to my mind too but I didn't take it seriously.

I should read the code and compare it to `/qt5/qtbase/src/gui/image/qiconloader.cpp` to be sure about that (read that file a long time ago but have forgotten its contents). Will do so tomorrow.

**Comment by tsujan** [comment]
@luis-pereira I tool a look at it  a few minutes ago. Nothing will be appended to the variable `ret` inside `QIconCacheGtkReader::lookup()` if `m_isValid` is set by that function, which means `result` will be empty if `m_isValid` is set to `false` by `lookup()`. So, no other condition is needed.

BTW, the name `lookup` is suitable.

**Comment by tsujan** [comment]
The [Qt bug](https://bugreports.qt.io/browse/QTBUG-65720) I opened was closed after a long and futile discussion. A Qt dev saw my pacth as disabling the icon cache altogether and believed it was a very bad thing to do. You should be waiting for your computers to explode...

I repeat my argument here, just once:

That patch is only about icons that don't exist in the cache yet. The process is like before when the icon is in that goddamn gtk cache. The patch prevents the cache from hiding the icons that aren't in it yet by using an iota of the CPU time for finding it. If an icon theme lacks 100 icons, it'll be small enough to not waste CPU time. If it lacks 10 icons *that are actually used*, we shouldn't worry about CPU, IMO.

Now, if you're ready to tell our users, "restart the panel and pcmanfm-qt after installing every app or we might show you the 'unknown' icon", you could reverse the patch but, in that case, I'll take users' side ;)

**Comment by agaida** [comment]
how is the procedure to get an icon into the cache?

**Comment by tsujan** [comment]
@agaida I don't know exactly but, as I told that Qt dev, IMO, a utility like gtk icon cache shouldn't be used to *hide* existing icons. It's used so by Qt, in the name of CPU. They don't care about the current critical bugs that aren't fixed or are denied for a long time but they care about our CPUs.

**Comment by tsujan** [comment]
FYI, every time you put your mouse cursor on a Qt window, several updates happen. If the same reasoning was applied to Qt widgets, Qt would be like motif ;)

**Comment by agaida** [comment]
ihmo you are wrong - he is Qt/KDE, he can't be wrong - really, it is your fault ... 
(https://behindkde.org/olivier-goffart - the wisdom of 21 years speaks clearly for him)

**Comment by tsujan** [comment]
@agaida Thanks a lot! I mean it. It's a while that I feel some Qt devs are too young. Not that being young is a bad thing in itself  -- I was young for a long time ;) -- but their responses sometimes reflect immaturity... I've talked a lot with experienced programmers too -- like the original author of QtCurve or the author of Bespin (the latter is disillusioned with Qt) -- and know the difference.

**Comment by luis-pereira** [comment]
@tsujan @agaida The saddest part of the discussion, was IMO, that the bug was closed (and it's really a bug), without any mention about fixing the underlying issue: ensuring that the cache is up to date.

**Comment by agaida** [comment]
@luis-pereira - thats make me angry too - ok, we do software, so bugs are normal. But damn it, they should be fixed from time to time.

**Comment by tsujan** [comment]
@luis-pereira I think he told that updating the cache was a costly job. I don't know but if so, searching for a few non-cached icons can't be costly by any standard.

**Comment by agaida** [comment]
it is costly and is mostly done as part of the installation routine (at least in debian afaik) - should have a look at - at least gtk-update-icon-cache should issued if a theme is installed. Maybe after that from time to time, had to look into some hooks. So the only place that is not updated on a regular base might be hicolor - and i guess it is not so costly to search through one theme dir

**Comment by tsujan** [comment]
@agaida As for leaving bugs unfixed, the "scroll jump" bug is an old Qt5 curse -- no one wants to fix it and I have a feeling that, maybe, no Qt dev actually knows how to fix it. All I've seen about that critical bug has been denial after denial. And the same for what I call the "state bug" (sometimes, "hover bug") and can be seen with LXQt panel easily.

**Comment by tsujan** [comment]
@agaida I think the cache is updated but running apps -- pcmanfm-qt and lxat-panel -- couldn't "see" it. If they were restarted, they would "see" it. The merged patch is rather a temporary workaround and, IMO, we should search for an elegant solution here, without waiting for Qt devs for eternity.

**Comment by agaida** [comment]
i have absolutly no problems with searching a few icons until the cache is regenerated - if it is so that some applications see the missed things after a restart - fine, in that case searching until a restart is a fine solution if i read the code right.

**Comment by tsujan** [comment]
> if it is so that some applications see the missed things after a restart

That's true. I suspect Qt doesn't update its cache *reader* on time. If that's costly too, the problem is deeper.

**Comment by luis-pereira** [comment]
@tsujan The reason why we don't rely on Qt Icon Loader is that: not wait eternally
There were some good patches submitted and refused without a good reason.

@tsujan If I remember correctly the  Qt icon cache isn't updated.

**Comment by agaida** [comment]
omfg

**Comment by tsujan** [comment]
@luis-pereira OK. Let's fix this ourselves! We have the most appropriate DE for finding and fixing Qt bugs :)
