### ISSUE TITLE
Complex shortcut wont work

### ISSUE THREAD

**Issue by HeikoTietze** [lxde/lxqt#1352]
I'm trying to bind the following command to the shortcut Alt+Print

spectacle --activewindow --background --output /tmp/spectacle.png && xclip -sel clip -t image/png /tmp/spectacle.png

'Print' is bound to spectacle (works) and the invoking the command from the shell works too.

##### Expected Behavior
Take a screenshot of the active window and load that into the clipboard

##### Current Behavior
Clipboard is cleared; short flicker sometimes looks like the command is initiated

##### System Information
* Distribution & Version: Arch Linux
* Kernel, Qt Version, liblxqt: official versions always up to date

**Comment by stefonarch** [comment]
Maybe shlash / is not supported, I would try making a executable script bash containing the command and creating a shortcut to the script.

screengrab can save to clipboard as well.

**Comment by HeikoTietze** [comment]
Script works; I always miss debug info in LXQt. As much paint in the ass systemd/journalctl is, without any info it's hard to understand what's going on.

**Comment by tsujan** [comment]
> I always miss debug info in LXQt

→ `~/.config/lxqt/debug.log`.

**Comment by HeikoTietze** [comment]
>  ~/.config/lxqt/debug.log

Not existing on my system.

**Comment by tsujan** [comment]
> Not existing on my system.

Have no idea why. To eliminate redundant writes, I linked it to `dev/null` (I prefer manual debugging).

**Comment by tsujan** [comment]
BTW, since I think our users' hard drives aren't our backyard, I'm against the existence of such files -- systemd enormous writes or sddm/gdm debugging files can't be a good example for anyone. IMO, debugging should be always a decision.

**Comment by palinek** [comment]
> Current Behavior

> Clipboard is cleared; short flicker sometimes looks like the command is initiated

So the shortcut does trigger, right? Then everything is OK. The global shortcut daemon doesn't support any shell's expansions/processing. You can configure just command and it's arguments.

In your case, you're trying to `execve(2)` 'spectacle', '--activewindow', '--background', '--output' '/tmp/spectacle.png', '&&', 'xclip -sel', 'clip', '-t', 'image/png', '/tmp/spectacle.png'. You can check it in the configuration `~/.config/lxqt/globalkeyshortcuts.conf` (the `Exec` keys).

IMO better approach is to put everything more complicated than running a command with parameters into a script file and execute that. Or if you insist in putting everything into the configuration of `lxqt-globalkeysd`, then you need something like:
```
/bin/sh -c 'spectacle --activewindow --background --output /tmp/spectacle.png && xclip -sel clip -t image/png /tmp/spectacle.png'
```
