### ISSUE TITLE
Issues and pull requests to compton-conf

### ISSUE THREAD

**Issue by ska67** [lxde/lxqt#1353]
I have set an issue and a pull request to lxde/compton-conf repository, but so far nothing has happened.
Was this the wrong place, do I have to use the lxde/lxqt repository?

**Comment by tsujan** [comment]
That's the right place. For various reasons (lack of manpower, priorities, limited free times,... ), it might take a while until a PR is reviewed but, as far as I've seen, no PR will be forgotten.
