### ISSUE TITLE
Recommending Qarma

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#1355]
This isn't an issue report but just a suggestion. IMHO, [Qarma](https://github.com/luebking/qarma) is missing from the list of apps recommended by LXQt in `/wiki/Third-party-apps`.

I use Qarma (with small modifications) for 3 years. It's a very handy -- but undervalued -- Qt5 dialog set. It's so good that I used it instead of kdialog under KDE too. It's light and can be used for all jobs that can be done by kdialog, Zenity,...

**Comment by agaida** [comment]
ACK - please add it

**Comment by tsujan** [comment]
OK.

**Comment by tsujan** [comment]
Done.

**Comment by agaida** [comment]
hmm - the next package that would be nice to have in debian - but LXQt first

**Comment by tsujan** [comment]
> the next package that would be nice to have in debian

Yes! A Debian package could also make it more known. Actually, I discovered it when I was a Debian user but, instead of packaging it, I did `qmake && make`, `strip qarma` and put it inside `~/bin`. Then I enjoyed purely Qt5 dialogs with pcmanfm-qt's custom actions :)

**Comment by agaida** [comment]
:D
