### ISSUE TITLE
Remembering view mode in file dialog

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#1358]
Should LXQt file dialog remember the last used view?

I think it should but only when the view mode isn't set to the list-view by the app code -- because that's the only non-default mode Qt provides.

KDE's file dialog remembers the view. I have a simple patch for LXQt file dialog.

**Comment by agaida** [comment]
Yes - please

**Comment by tsujan** [comment]
I chose the KDE approach at https://github.com/lxde/lxqt-qtplugin/pull/28 : always remember the view mode because the Qt dialog is very poor in that regard.

**Comment by agaida** [comment]
GTM
