### ISSUE TITLE
Alternative or easier accessible documentation for Digital Clock formats

### ISSUE THREAD

**Issue by PanderMusubi** [lxde/lxqt#1363]
##### Expected Behavior

When I open "Digital Clock" Settings by right clicking on the clock in the bottom right of my screen, I expect alternative or easier accessible documentation for the Digital Clock formats.

##### Current Behavior

Now there is the text _Format codes: man 3 strftime; %n for line break_ but for the average normal user this is too difficult. Additionally, one has to have the package `manpages-dev` installed. Which for even experienced users is not trivial (to get to that package name) and/or installing this package only for this documentation is unwanted.

##### Possible Solution

Add a link on the only the text `man 3 strftime` that opens the default web browser to http://manpages.org/strftime/3 (or perhaps http://man7.org/linux/man-pages/man3/strftime.3.html ). This will greatly easy the way non-experienced users can find this documentation and reduces the need to install a package to get this documentation. It gives the user more freedom and easier to access documentation.

##### Steps to Reproduce (for bugs)

1. richt click the clock on the bottom right of the screen and choose `"Digital Clock" Settings`

##### Context

n/a

##### System Information

* Distribution & Version: Lubuntu 17.10
* Kernel: 4.13.0.16.17
* Qt Version: 5.9.1+dfsg-10ubuntu1
* liblxqt Version:  0.11.1-2
* Package version: 0.9.3-1ubuntu2

**Comment by palinek** [comment]
Hi, the `clock` plugin is deprecated in 0.12 and people are encouraged to use the `worldclock` plugin (there 
 is also the help incorporated inside)

**Comment by palinek** [comment]
Heh... read the description once again carefully.
@PanderMusubi there is no "Digital clock" plugin in lxqt-panel. What application are you talking about?

**Comment by PanderMusubi** [comment]
See screenshot

![screenshot](https://user-images.githubusercontent.com/198964/32048143-c1f01416-ba48-11e7-840a-537077de07ee.png)

**Comment by palinek** [comment]
Assuming you are talking about the `lxpanel` ([code](https://git.lxde.org/gitweb/?p=lxde/lxpanel.git;a=blob;f=plugins/dclock.c;h=d9344273f167909c616aeb583e4bd351a910df9c;hb=HEAD#l431))... this is definitely the wrong place this report. You (probably) should report that to sourceforge -> https://sourceforge.net/p/lxde/bugs/

**Comment by PanderMusubi** [comment]
Ah thanks, will report it there. I followed the website listed in `apt-cache show lxpanel`, which is http://www.lxde.org and that brought me via `Website source code` in the footer to this repo. Perhaps improve the information on where to report if you think that is needed.

**Comment by PanderMusubi** [comment]
Reported there as https://sourceforge.net/p/lxde/bugs/885/ Thanks for your help.
