### ISSUE TITLE
run lxqt-sudo <cmd> from lxqt-runner : nothing happens

### ISSUE THREAD

**Issue by jsm222** [lxde/lxqt#1365]
ALT-F2 starts lxqt-runner -> type lxqt-sudo qterminal -> nothing happens.

##### Expected Behavior
password prompt and running qterminal as root, after successful authentication.

##### Current Behavior
No password prompt comes up.

##### Possible Solution
Not provided by me right know..

##### Steps to Reproduce (for bugs)

1. ALT-F2 (or start lxqt-runner somehow)
2. type lxqt-sudo qterminal
3. pres enter
4. nothing happens

##### Context
using lxqt-runner as a shortcut to start a qterminal or any program as root.

##### System Information

* Distribution & Version: 
* Kernel: FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017
* Qt Version: 54.7.1
* liblxqt Version: 0.12.0 
* Package version: 0.12.0
NOTE:
I have not tested it on any Linux so I do not know expected behavior, it worked on lxqt 0.11 though.

**Comment by tsujan** [comment]
For the record, recently I can't even run pcmanfm-qt as root -- I use LXQt file dialog instead.

**Comment by jsm222** [comment]
After the steps mentioned:
ps auxw 
```
root       1034  1.1  0.4  46428   3776  4  Ss+  21:57   0:00.00 sudo -E qterminal
jesper      980  0.0  6.0 267256  60632  -  S    21:52   0:00.08 /usr/local/bin/lxqt-sudo ls
```

But nothing shows up.

ps:: pcmanfm-qt runs for me as root.

**Comment by tsujan** [comment]
I think this may about the old dbus problem...

**Comment by stefonarch** [comment]
Cannot reproduce it on arch, qterminal opens fine as root.

**Comment by jsm222** [comment]
Could not reproduce after a build in poudriere.. weird. But thanks for the comments.. 👍
