### ISSUE TITLE
plugin-worldclock does not update widget size on change

### ISSUE THREAD

**Issue by AlfredoRamos** [lxde/lxqt#1366]
I've seen recently that `plugin-clock` will be replaced by `plugin-wordlclock`, however when I change the date or time format, it looks cropped.

[Video](https://i.imgur.com/GVcYhX1.mp4)

##### Expected Behavior

When changing date/time format using the check boxes or the manual format, it should change its size to show all the text correctly.

##### Current Behavior

It shows a cropped portion of the text after changing date/time format.

##### Possible Solution

Not sure if related, but there was a similar issue with `plugin-clock`, a fix was provided in lxde/lxqt-panel@eae99f5 for #687

##### Steps to Reproduce (for bugs)

1. Add a the `wordlclock` widget
2. Change the date/time format

##### System Information

* Distribution & Version: Arch Linux x64
* Kernel: 4.13.9-1-ARCH
* Qt Version: 5.9.2
* liblxqt Version:  0.12.0
* Package version: 0.12.0 (lxqt-panel)

**Comment by tsujan** [comment]
Already fixed in https://github.com/lxde/lxqt-panel/commit/310140f842b8b809b1165106154f93833a269802. Please update your lxqt-panel installation!
