### ISSUE TITLE
Infinite loop after choosing the gtk2 widget style

### ISSUE THREAD

**Issue by pourpier** [lxde/lxqt#1367]
##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: Artix LXQt
* Kernel: 4.9.44-1-lts
* Qt Version: 0.12
* liblxqt Version:  
* Package version: 
After choosing the widget style gtk2 and clicking on Apply and OK, I was immediately redirected to the login screen of the DM and even after giving the correct credentials I was redirected to the login DM.
The only way I found was to edit the line at boot and put init=/bin/bash and I edited ~/.config/lxqt/lxqt.conf and took another style like Fusion for instance.

**Comment by agaida** [comment]
sounds like a downstream problem

**Comment by pourpier** [comment]
What do you mean ?

2017-10-28 22:50 GMT+02:00 Alf Gaida <notifications@github.com>:

**Comment by agaida** [comment]
exactly what i wrote - it sounds like a downstream problem aka Artix problem

**Comment by tsujan** [comment]
This cannot be an LXQt issue. Either it's a downstream problem (as @agaida said) or a problem in the installed/active style engine.

**Comment by tsujan** [comment]
> Qt Version: 0.12

??!!
