### ISSUE TITLE
QT_QPA_PLATFORMTHEME not correctly defined

### ISSUE THREAD

**Issue by pourpier** [lxde/lxqt#1368]
##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: Artix LXQt
* Kernel: 4.9.44-1-lts
* Qt Version: 0.12
* liblxqt Version:  
* Package version: 
I installed qt5ct and I wanted to launch the Qt5 Settings GUI and I got the error message of the title of this issue. I defined the variable and gave the value qt5ct. But even giving the value lxqt generates the same error and I can't launch the Qt5 Settings GUI.

**Comment by tsujan** [comment]
Again, a downstream problem.

**Comment by tsujan** [comment]
BTW, you don't need (and should not use) qt5ct under LXQt.

**Comment by tsujan** [comment]
It seems that you other problem (https://github.com/lxde/lxqt/issues/1367) is caused by this. A short explanation:

qt5ct is needed only when there's no native Qt5 plugin. Both KDE and LXQt provide nice Qt5 plugins (actually, LXQt's plugin can be used outside LXQt too). Your LXQt installation seems NOT OK/complete.

**Comment by stefonarch** [comment]
Once I played around with qt5ct, there were 2 parameters to be set before using it in session configuration > advanced, then restart session. One was 
QT_QPA_PLATFORMTHEME=qt5ct
the other I don't remember. 
But as said here before : it's  only good to create a mess.

**Comment by tsujan** [comment]
@stefonarch When one has LXQt's plugin, one doesn't need qt5ct -- not even outside LXQt. The former is far more advanced than the latter. For example, under a weird environment like Enlightenment, setting the environment variable `QT_QPA_PLATFORMTHEME` to `lxqt` is much better than setting it to `qt5ct`. Moreover, qt5ct has unfixed issues.
