### ISSUE TITLE
Workaround to launch JuffEd on 64-bit LXQt (Lubuntu 14.04)

### ISSUE THREAD

**Issue by vasa1** [lxde/lxqt#137]
In case Juffed Text Editor (v0.9.1137) on **64**-bit LXQt  doesn't run and the terminal displays:  
`juffed: error while loading shared libraries: libjuff.so.0.9: cannot open shared object file: No such file or directory`  
see  
  - https://bugs.launchpad.net/ubuntu/+source/juffed/+bug/874479/comments/3 from 2011-11-11 or  
  - https://bugs.launchpad.net/ubuntu/+source/juffed/+bug/881211/comments/6 from 2013-10-08

The latter worked for me.

**Comment by jleclanche** [comment]
@paulolieuthier actually fixed that in recent commits.
