### ISSUE TITLE
  issue : compiling pcmanfm-qt from qt creator

### ISSUE THREAD

**Issue by rahmanshaber** [lxde/lxqt#1372]
when i tried to build pcmanfm-qt with qt-creator it shows me this error 
    /usr/include/libfm/fm-app-info.h:26:10: fatal error: gio/gio.h: No such file or directory
     #include <gio/gio.h>
              ^~~~~~~~~~~
          compilation terminated.
      make: *** [Makefile:769: application.o] Error 1
      11:17:40: The process "/usr/bin/make" exited with code 2.

i istalled pcmanfm-qt,vresion 12 in my pc.if it can run ,why pcmanfm-qt not building??

please help me . i need a qt based file manager for my touch based project.
thanks.

**Comment by tsujan** [comment]
GIO belongs to GLib. For whatever reason, Qt Creator can't see it in the above case. How can that be an LXQt issue?!

**Comment by rahmanshaber** [comment]
requesting project file of pacmanfm qt

**Comment by agaida** [comment]
no further processing - you missed elementary informations - thats why we created the issue template - and goodl luck with your problem, some distries provide header files in separate packages.
