### ISSUE TITLE
Change multiple shortcuts with "lxqt-globalkeys"

### ISSUE THREAD

**Issue by ska67** [lxde/lxqt#1376]
If I change several shortcuts at the same time without closing the window in between, not all changes will be applied. The first change is always applied, but even the second change can sometimes be rejected.
Can anybody confirm this?

I checked this on two different systems.

##### System Information (bare metal)
* Distribution & Version:  Debian 9 stretch (stable)
* Kernel: 4.9
* Qt Version: 5.7
* liblxqt Version:  0.11.1
* Package version: 0.11.1

##### System Information (kvm guest (spiced))
* Distribution & Version:  Manjaro (stable)
* Kernel: 4.9
* Qt Version: 5.9
* liblxqt Version:  build from source
* Package version: build from source

**Comment by ska67** [comment]
Okay, I found the error!
It happens when you first change a shortcut of type "command" and then a shortcut of type "client".
The configuration client app distinguishes only the types "command" and "method", not the type "client".

**Comment by ska67** [comment]
Please merge my PR so I can proceed with the next change.

BTW, perhaps someone could merge my other PR for lxqt-admin and compton-conf?

**Comment by palinek** [comment]
fixed by lxde/lxqt-globalkeys#58
