### ISSUE TITLE
Yocto packagegroup-lxqt-base Failed tasks kwidgetsaddons do_compile

### ISSUE THREAD

**Issue by denyste** [lxde/lxqt#1377]
Yocto packagegroup-lxqt-base Failed tasks kwidgetsaddons do_compile:

Hi,
I am building an image with Yocto Project (morty). The layer "meta-qt5-extra" includes the recipe "packagegroup-lxqt-base" in my project. However the building generated the following failed tasks:

/*
2 errors

oe_runmake failed

Function failed: do_compile (log file is located at /home/user-test/poky-morty/build-toaster-2/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/kwidgetsaddons/5.30.0-r0/temp/log.do_compile.20270)
*/

Why "kwidgetsaddons" generated these errors and how do I resolve this issue?

See below the build log for more details:

NOTE: Logging error 2: {'pathname': '/home/user-test/poky-morty/_toaster_clones/_git___git.yoctoproject.org_poky_morty/bitbake/lib/bb/init.py', 'lineno': 100, 'build': <Build: 105 Project object distro-with-lxqt>, 'message': 'oe_runmake failed', 'level': 2}
ERROR: oe_runmake failed
NOTE: Logging error 2: {'pathname': '/home/user-test/poky-morty/_toaster_clones/_git___git.yoctoproject.org_poky_morty/bitbake/lib/bb/build.py', 'lineno': 589, 'build': <Build: 105 Project object distro-with-lxqt>, 'message': 'Function failed: do_compile (log file is located at /home/user-test/poky-morty/build-toaster-2/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/kwidgetsaddons/5.30.0-r0/temp/log.do_compile.20270)', 'level': 2}
ERROR: Function failed: do_compile (log file is located at /home/user-test/poky-morty/build-toaster-2/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/kwidgetsaddons/5.30.0-r0/temp/log.do_compile.20270)
NOTE: recipe kwidgetsaddons-5.30.0-r0: task do_compile: Failed
ERROR: Task (/home/user-test/poky-morty/_toaster_clones/_git___github.com_schnitzeltony_meta-qt5-extra.git_morty/recipes-kde/kf5/tier1/kwidgetsaddons/kwidgetsaddons.bb:do_compile) failed with exit code '1'
NOTE: Logfile for task /home/user-test/poky-morty/build-toaster-2/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/polkit-qt-1/0.112.0-r0/temp/log.do_populate_sysroot.22244
NOTE: Logfile for task /home/user-test/poky-morty/build-toaster-2/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/polkit-qt-1/0.112.0-r0/temp/log.do_populate_sysroot.22244
NOTE: Logfile for task /home/user-test/poky-morty/build-toaster-2/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/kguiaddons/5.30.0-r0/temp/log.do_configure.22142
NOTE: Tasks Summary: Attempted 2115 tasks of which 2110 didn't need to be rerun and 1 failed.
NOTE: No package dependencies created
NOTE: No package dependencies created
WARNING: KeyError in save_target_file_information'dirs'

Would you please help me resolve them?
I thank you in advance.

**Comment by tsujan** [comment]
Please don't report downstream or distro specific problems here! Thanks in advance!
