### ISSUE TITLE
Remember config settings for monitor

### ISSUE THREAD

**Issue by 9034725985** [lxde/lxqt#1379]
hi guys, in fedora 26 lxqt 0.11.1 I want to set it so i only ever use my second display (laptop LCD is cracked and doesn't work). https://gist.github.com/anonymous/918fc81618aadbbc15c3d08ba640337c 

##### Expected Behavior
I think if I set a second monitor (such as VGA) to be my only display, lxqt should honor this request on next boot (as long as the second monitor is present). 

##### Current Behavior
Right now, I get second display extends main laptop display. 

##### Possible Solution
If we can't fix this bug, I think we should not extend by default. We should mirror by default and let users change this setting (which I'm sure 90%+ will do because who wants mirror?). 

##### Steps to Reproduce (for bugs)
1. Get a Thinkpad T61 laptop with a broken built in display (or any other laptop computer) 
2. Install Fedora 26 with lxqt 
3. Set the lxqt-config-monitor to second only 
4. Reboot 

##### Context
My laptop LCD is broken. 
I think this helps anyone who has a broken built-in display. 

![monitorsettings](https://user-images.githubusercontent.com/1676445/32411874-2d499310-c1bd-11e7-9e03-7f4ec98dd4f5.png)

##### System Information

* Distribution & Version: Fedora 26
* Kernel: 4.11.8-300.fc26.x86_64
* Qt Version: 5.7.1
* liblxqt Version: ? 
* Package version: ?

**Comment by tsujan** [comment]
First, lxqt 0.11.1 is old (but that doesn't make any difference; see below).

Second, by chance, I have an Asus laptop with a broken monitor too (an old problem with Asus graphic cables). Therefore, I use a second display with it and my choice is *always* respected -- whether after reboot or logging out/in.

The interesting thing is that I also have an old LXQt 0.11 under a Debian installation on the same laptop (to test some apps with old libraries) and the display setting is respected too.

**Comment by tsujan** [comment]
Anyhow, since lxqt 0.11.1 isn't supported, this can't remain open.
