### ISSUE TITLE
lxqt-panel buildsystem include should find xkbcommon-x11.h for kbindicator plugin

### ISSUE THREAD

**Issue by jubalh** [lxde/lxqt#1381]
When I compile lxqt-panel I call `export CXXFLAGS="%{optflags} $(pkg-config --cflags xkbcommon-x11)"` before calling cmake because otherwise it will abort with:

```
lxqt-panel-0.12.0/plugin-kbindicator/src/x11/kbdlayout.cpp:34:10: fatal error:  xkbcommon/xkbcommon-x11.h: No such file or directory
```

I do this as a workaround and suppose this should be done via cmake, am I right?
##### Expected Behavior
Compile without additional tweaking.

##### Current Behavior
Need to specify extra include path.

##### Possible Solution
Fix in CMake file.

##### Steps to Reproduce (for bugs)
1.  Compile ;)

##### Context
Not sure if this also happens on other Distributions. For me this also was the case for the 0.11 release.

##### System Information
* Distribution & Version: openSUSE Tumbleweed
* Kernel: 4.13.10
* Qt Version: 5.9.2-2.1
* liblxqt Version:  0.12.0
* Package version:  0.12.0

**Comment by luis-pereira** [comment]
Please provide paths of headers and libs.
I don't have a side installation to test it.

**Comment by jubalh** [comment]
Not sure why the paths would matter. Can paste them tomorrow.
You want to know what pkg-config --cflags xkbcommon-x11 evaluates to on my system?
@luis-pereira did you see https://github.com/lxde/lxqt-panel/pull/439 ?

**Comment by luis-pereira** [comment]
@jubalh 
I saw lxde/lxqt-panel#439. I'm trying to find out why ```find_package(XCB REQUIRED COMPONENTS xkbcommon-x11 xkbcommon xcb xcb-xkb)``` isn't cutting it.
I do not have a Suse installation. Pls provide ```pkg-config --cflags xkbcommon-x11 ``` and the actual paths to libs and headers.

**Comment by jubalh** [comment]
```
$ pkg-config --cflags xkbcommon-x11
-I/usr/include/libxkbcommon
```

**Comment by luis-pereira** [comment]
@jubalh And the `xkbcommon-x11.h` file is at `/usr/include/libxkbcommon` right ? It may seem a dumm question... but just in case.
I will write some debug code. I need you to run it. Ok ?

**Comment by jubalh** [comment]
It's in a subfolder:
```
$ tree /usr/include/libxkbcommon
/usr/include/libxkbcommon
└── xkbcommon
    ├── xkbcommon-compat.h
    ├── xkbcommon-compose.h
    ├── xkbcommon.h
    ├── xkbcommon-keysyms.h
    ├── xkbcommon-names.h
    └── xkbcommon-x11.h
```

**Comment by luis-pereira** [comment]
I already figured out, why it fails on Suse and works on Arch.
Will fix it.

**Comment by luis-pereira** [comment]
@jubalh Thanks for you help.

**Comment by jubalh** [comment]
> I already figured out, why it fails on Suse and works on Arch.

Why? :)

**Comment by luis-pereira** [comment]
@jubalh We were simply abusing it.
It only worked on Arch because the include dir was ```/usr/include```.

The conjunction of:
https://github.com/lxde/lxqt-build-tools/pull/23
https://github.com/lxde/lxqt-panel/pull/442
should fix it.
