### ISSUE TITLE
build help

### ISSUE THREAD

**Issue by rahmanshaber** [lxde/lxqt#1384]
first.
is there any legal issue if I use the code,and modify it and use it.(i know GPL,and i read it,but i am confused) 
second.
i am changing the icon of lx-image.it shows on design editor,but when i compile no icon was shown(blank).
how to solve this problem.
third,
please add a forum in lxqt's name.where everyone could discuss this type of mater.
sorry for asking help by pulling new issue.
thanks.

**Comment by tsujan** [comment]
> is there any legal issue if I use the code

You could use the code *under GPL*. Add a link to it in your code ( "adapted from..", "taken from...", etc.).

> i am changing the icon of lx-image.it shows on design editor,but when i compile no icon was shown(blank). how to solve this problem.

No support for changed codes.

**Comment by rahmanshaber** [comment]
ok.thanks for the ans.
ant forum to ask??
can't i change the defult theme??

**Comment by rahmanshaber** [comment]
thanks again.i have done most of the changes in visual,and made the lximage-qt more simple.
if visual changes will accepted I will PR.will visual effect be approved??

**Comment by tsujan** [comment]
For a PR, it doesn't make any difference what the changes are but they should be about one and the same subject in each PR. Usually, two developers should approve of the changes before the PR is merged and that may take a while. Anyhow, you're welcome to make PR's :)

I think this can be closed.
