### ISSUE TITLE
Keyboard and mouse settings miss a tap-to-click on/off toggle for touchpads

### ISSUE THREAD

**Issue by EinarMostad** [lxde/lxqt#1393]
I use a laptop with a touchpad and an external mouse. When I use the touchpad, I prefer to turn tap-to-click off and use the physical buttons instead. There is no option to set this in LXQt Keyboard and mouse settings. (I know a lot of people like to turn tap-to-click off. Some years ago I had a blog with a how-to for turning tap-to-click off in LXDE and it was the most popular blog post I had on that blog.)

![missing tap-to-click setting for touchpads i have both a touchpad and a mouse hooked up](https://user-images.githubusercontent.com/33556631/32677019-1e4f1390-c65d-11e7-83af-179d723073cf.png)

##### Expected Behavior
A tap-to-click on/off button for touchpads

##### Current Behavior
No such button

##### Possible Solution
Add a button that switches off/on tap-to-click

##### Steps to Reproduce (for bugs)
Open Keyboard and Mouse settings in the Mouse tab.

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version:  
* Package version:

**Comment by yan12125** [comment]
This is already discussed in #92

**Comment by EinarMostad** [comment]
Sorry!
