### ISSUE TITLE
PCManFM-Qt Places column too narrow for the names of most places

### ISSUE THREAD

**Issue by EinarMostad** [lxde/lxqt#1395]
The column for the names of places is too narrow for many of the default places names like "Computer" and "Applications".

![places too narrow by default for name of folders](https://user-images.githubusercontent.com/33556631/32677318-428b68f2-c65e-11e7-8e0b-450f9aab7d52.png)

##### Expected Behavior
Wide enough to show the name of most places if not extremely long.

##### Current Behavior
Too narrow for most names

##### Possible Solution
Make it wider by default, maybe also make the default window size wider

##### Steps to Reproduce (for bugs)
Open PCManFM-Qt

##### System Information

* Distribution & Version:  Arch Linux
* Kernel: 
* Qt Version: 
* liblxqt Version:   0.12.0-1
* Package version:  0.12.0-1

**Comment by tsujan** [comment]
pcmanfm-qt can remember the splitter position; just drag the splitter to the right. It's impossible to know which items will be added there or which localization is used.
