### ISSUE TITLE
LXQt Session Settings. Terminal emulator setting should be set to Qterminal by default

### ISSUE THREAD

**Issue by EinarMostad** [lxde/lxqt#1397]
I think the default setting should be Qterminal, not nothing. When a user installs LXQt, the user generally wants to use Qterminal. If not, the setting is easy to change, but it should not be left unpopulated by default in my opinion.

![terminal emulator setting should be populated by qterminal by default](https://user-images.githubusercontent.com/33556631/32677596-51fb3366-c65f-11e7-9ff9-9683aecfaf49.png)

##### Expected Behavior
Qterminal as default terminal emulator.

##### Current Behavior
Nothing as default terminal emulator.

##### Steps to Reproduce (for bugs)
Open LXQt Session Settings and have a look.

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 
* Qt Version: 
* liblxqt Version:   0.12.0-1
* Package version:  0.12.0-1

**Comment by yan12125** [comment]
This topic is already discussed extensively in #433. Feel free to express your ideas there.

**Comment by EinarMostad** [comment]
Thank you. I will. :-)
