### ISSUE TITLE
PCManFM-Qt Preferences should have Qterminal as default terminal emulator

### ISSUE THREAD

**Issue by EinarMostad** [lxde/lxqt#1398]
The default terminal emulator in PCManFM-Qt should be Qterminal in my opinion.

![terminal emulator should be qterminal by default](https://user-images.githubusercontent.com/33556631/32677743-e5cfb99a-c65f-11e7-8920-79df44f6344c.png)

##### Expected Behavior
Qterminal should be default

##### Current Behavior
xterm is default

##### Steps to Reproduce (for bugs)
Open PCManFM-Qt
Open Preferences
Go to Advanced tab

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 
* Qt Version: 
* liblxqt Version:   0.12.0-1
* Package version:  0.12.0-1

**Comment by dotmagic** [comment]
I don't agree, Qterminal is a optional part and not installed on any system. But xterm is almost on any linux installation. It's still my prefered choice since I don't need tabs or other fancy features.

**Comment by agaida** [comment]
it's up to the distributors to set this - so no bug
