### ISSUE TITLE
Search in menu is kept even after item is launched.

### ISSUE THREAD

**Issue by EinarMostad** [lxde/lxqt#1400]
If I use the search in the menu to launch something and open the menu again, the search is still there and I have to delete it before searching again. This means I have to press many more keys to launch a file or program than I would have if the search deleted itself after launch.

![last search is kept in menu even after being launched i have to delete everything before writing a new search](https://user-images.githubusercontent.com/33556631/32677989-dc342802-c660-11e7-8397-110d336aa633.png)

##### Expected Behavior
Search is deleted after launch.

##### Current Behavior
Search is kept.

##### Steps to Reproduce (for bugs)
Open menu.
Search for something.
Launch it.
Open menu again.

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 
* Qt Version: 
* liblxqt Version:   0.12.0-1
* Package version:  0.12.0-1

**Comment by tsujan** [comment]
Exactly like https://github.com/lxde/lxqt/issues/1399 -- my last response to useless reports.

**Comment by EinarMostad** [comment]
Sorry!

**Comment by palinek** [comment]
This behavior can be configured...
