### ISSUE TITLE
[feature-request] The ability to create a taskbar.

### ISSUE THREAD

**Issue by Cybermaxrus** [lxde/lxqt#1405]
Greetings! I would like to be able to create a taskbar. You specify the folder from which you would like the taskbar and get the shortcut menu.
http://www.watchingthenet.com/wp-content/uploads//tbtaskbar4.jpg
https://www.groovypost.com/wp-content/uploads/2017/02/sshot-3.png
https://www.eightforums.com/attachments/customization/1746d1316186636t-add-desktop-toolbar-task-bar-additional-functionality-dsktp_toolbar.png?s=a2a8bec575ac672b12e0aeed4685b230
https://www.tenforums.com/attachments/tutorials/107057d1485973246-add-toolbars-taskbar-windows-10-a-desktop_toolbar.jpg?s=0d0a3ea25ea99f5cbf248aeba3714846

**Comment by tjbrn** [comment]
`directorymenu` and `quicklaunch2` widgets do something like that

**Comment by palinek** [comment]
> directorymenu and quicklaunch widgets do something like that

Exactly....
