### ISSUE TITLE
[Feature-Request] could you consider to support globalmenu?

### ISSUE THREAD

**Issue by hosxy** [lxde/lxqt#1408]
As the title say，could you consider to support globalmenu like unity and kde plasma 5.9 ?
I think it can make screen used effectively for small screen computer especially.

**Comment by tsimonq2** [comment]
I don't see why not, but who's going to volunteer to implement it? :wink:

**Comment by yan12125** [comment]
Looks like the same as #133?

**Comment by palinek** [comment]
duplicate of #133
