### ISSUE TITLE
Volume and mounted devices apps are not visible on black background

### ISSUE THREAD

**Issue by drencrom** [lxde/lxqt#1409]
I updated lxqt to 0.12 (Arch) and now the volume and mounted devices apps are not visible on a dark toolbar (default dark theme)

##### Expected Behavior
I used to see them before updating

##### Current Behavior
They can't be seen 

##### Possible Solution
The color of the app should change according to the background or be selectable by the user

**Comment by tsujan** [comment]
Please attach a small screenshot.

**Comment by tsujan** [comment]
With a little telepathy, I guess you used an icon theme like Breeze and a light widget style but a dark panel with LXQt < 0.12. In LXQt 0.12, symbolic SVG icons follow the widget style; if you use a light widget style, Breeze's small icons will become dark on the panel.

You have 2 ways out of this: either use a dark widget style and log out/in, or use an icon theme that doesn't have SVG symbolic icons. (There's also a third way but not supported by style engines like Breeze or Fusion.)

**Comment by drencrom** [comment]
Here is the screenshot:

![sample](https://user-images.githubusercontent.com/1243394/33021998-6aa07040-cde2-11e7-9b5e-07bbdcbb54a0.png)

I solved it unmarking the checkbox labeled _Colorize icons based on widget style_

I'm using breeze as icon theme and fusion as widget style. If I don't uncheck the box the problem is the same using Breeze and Breeze dark as icon theme.

**Comment by tsujan** [comment]
> I solved it unmarking the checkbox labeled Colorize icons based on widget style

Yes, that's the fourth way missing from my previous comment (the third way was assigning a dark widget style only to lxqt-panel --  Kvantum supports that).

This is the case with KDE too but, as far as I remember, KDE doesn't have an option for it.
