### ISSUE TITLE
second menu widget does not open a working menu lxqt-panel

### ISSUE THREAD

**Issue by ianorlin** [lxde/lxqt#141]
If I add a menu second menu in lxqt panel and left click on it does not open to a readable menu. 

The version I am using is 
lxqt-panel:
  Installed: 0.7.0+bzr572+201405151553~ubuntu14.04.1
  Candidate: 0.7.0+bzr572+201405151553~ubuntu14.04.1
  Version table:
 *** 0.7.0+bzr572+201405151553~ubuntu14.04.1 0
        500 http://ppa.launchpad.net/lubuntu-dev/lubuntu-daily/ubuntu/ trusty/main i386 Packages
        100 /var/lib/dpkg/status

**Comment by palinek** [comment]
fixed in lxde/lxqt-panel/#145
