### ISSUE TITLE
lxqt themes are broken

### ISSUE THREAD

**Issue by gsaga** [lxde/lxqt#1413]
##### Current Behavior

I've installed lxqt from source on my pc and the themes appear to be broken. The appearance configuration shows 5 themes corresponding to the 5 subdirectories in the themes directory but changing them doesn't affect anything. `lxqt-panel` upon execution gives the following output:

    > lxqt-panel
     (0x7ffdfabdcf60) Debug: ()
     (0x7ffdfabdcf60) Debug: WinIdChange 1600007 handle QWidgetWindow(0x558cbf050490, name="LXQtPanel panel1Window") QScreen(0x7fa04c006680, name="eDP1")
     (0x7ffdfabdcf60) Warning: void DBusMenuImporter::slotGetLayoutFinished(QDBusPendingCallWatcher*): "No such object path '/NO_DBUSMENU'"

`lxqt-configuration-appearance` doesn't give any warnings or errors.

* Distribution & Version: Arch linux
* Kernel: 4.13.12-1
* Qt Version: 5.9.3.1
* liblxqt Version:  0.12.0
* Package version: 0.12.0

**Comment by gsaga** [comment]
Update :

The themes work as expected if I symlink `$HOME/.local/share/lxqt` to `/usr/local/share/lxqt`(install location). What could be the reason?

**Comment by stefonarch** [comment]
You have installed all in /usr/local true? I always compile and install with
 -DCMAKE_INSTALL_PREFIX=/usr

**Comment by agaida** [comment]
when building from source i suggest the AUR packaging - download the recipe. build and install the packages - they work.
