### ISSUE TITLE
Panel has memory leak

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#1415]
This isn't necessarily a bug but I'm a little concerned about the Panel memory usage. In a 2-day session, the panel uses 87 MiB of memory, while it only has a task manager, main menu button and these items:

![panel](https://user-images.githubusercontent.com/981076/33374960-82faf1fa-d51d-11e7-9174-d83a47534780.png)

Isn't the memory usage high?

**Comment by tsujan** [comment]
In comparison, pcmanfm-qt -- with so many windows opened and closed and with its desktop, whose items are added and deleted continuously and whose wallpaper changes every hour -- might use 60 MiB of memory in 3 days of work.

How can the panel use more memory?!

**Comment by stefonarch** [comment]
I've usually long uptime. actually  5 days, 2 panel use 24880kb

**Comment by tsujan** [comment]
> I've usually long uptimes, actually 5 days : 2 panels use 24880kb

I forgot to say that I have 2 panels too. However, 87 MiB doesn't seem normal. It may depend on the plugins added to the panel. It started from 22 MiB on logging in.

And now, it's 88 MiB! There're a memory leak somewhere, maybe in one of the plugins. I have another LXQt installation and might test there by adding/removing plugins.

**Comment by stefonarch** [comment]
a list of the plugins involved?
Actually for me it's faster to tell which plugin I'm not using: showdesktop and colourpicker, the other are all present. On my old 32 bit laptop, uptime 6 days with suspend and hibernate my only panel uses  10.8kb 
I see that ksysguard has this feature of details,it continues to libraries ecc:
```
The process lxqt-panel (with pid 5095) is using approximately 14.7 MB of memory.
It is using 12.3 MB privately, 9.0 KB for pixmaps, and a further 21.2 MB that is, or could be, shared with other programs.
Dividing up the shared memory between all the processes sharing that memory we get a reduced shared memory usage of 2.4 MB. Adding that to the private and pixmap usage, we get the above mentioned total memory footprint of 14.7 MB.
2.9 MB is swapped out to disk, probably due to a low amount of available memory left.


```
 
I think I've no issues in this direction.

**Comment by tsujan** [comment]
It's 91MiB now. I can't close my eyes to this ;)

I did `cat /proc/$PANEL_ID/smaps`, did it again 10 minutes later, and this part of the diff worries me:
```diff
-5651717df000-5651767fb000 rw-p 00000000 00:00 0                          [heap]
-Size:              82032 kB
+5651717df000-5651768cf000 rw-p 00000000 00:00 0                          [heap]
+Size:              82880 kB
 KernelPageSize:        4 kB
 MMUPageSize:           4 kB
-Rss:               81944 kB
-Pss:               81944 kB
+Rss:               82672 kB
+Pss:               82672 kB
 Shared_Clean:          0 kB
 Shared_Dirty:          0 kB
 Private_Clean:         0 kB
-Private_Dirty:     81944 kB
-Referenced:        81924 kB
-Anonymous:         81944 kB
+Private_Dirty:     82672 kB
+Referenced:        82652 kB
+Anonymous:         82672 kB
 LazyFree:              0 kB
 AnonHugePages:     79872 kB
 ShmemPmdMapped:        0 kB
@@ -80,7 +80,7 @@
 Private_Hugetlb:       0 kB
 Swap:                  0 kB
 SwapPss:               0 kB
-Locked:            81944 kB
+Locked:            82672 kB
```
If I find something like this in a program of mine, I consider it as a serious problem and try to find the cause. But I'm not familiar enough with lxqt-panel.

**Comment by tsujan** [comment]
> a list of the plugins involved?

Main menu
Task manager
Status notifier
Old tray (without anything in it but for Skype)
Removable media
CPU monitor
System statistics
World clock
Volume control

And on the other panel, only Quick Launch.

I'm suspicious of CPU monitor and System statistics...

**Comment by tsujan** [comment]
BTW, high memory usage, per se, isn't important to me -- I have 16 GiB of RAM -- but a memory leak is a bug.

**Comment by tsujan** [comment]
It's 110 MiB now. Changed the title for it to reflect the fact.

**Comment by palinek** [comment]
With help of `valgrind` I was able to identify some leaks... they are adressed in lxde/lxqt-panel#444 & lxde/menu-cache#18

Please, test with those patches... but you're probably suffering by something else also...

**Comment by tsujan** [comment]
@palinek 
I think the leak is in system statistics and/or cpu monitor. After I removed them, the memory usage has stopped increasing at 111.8 MiB for 2 hours.

sysstat → `data\source=wlp8s0` and `data\type=Network`
cpuload → `showText=true` and `type=cpuload`

**Comment by tsujan** [comment]
I narrowed it down to System Statistics --re-added CPU Monitor and the memory usage is still 111.8 MiB. The leak can be related to libsysstat.

**Comment by tsujan** [comment]
I may be wrong but it isn't in System Statistics either. I looked into the codes of LXQtSysStat and SysStat but found nothing suspicious.

BTW, it can't be about menu-cache either because, although I have the main menu, I only use it rarely.

Taskbar? It creates buttons and other widgets; does it remove them correctly?

**Comment by tsujan** [comment]
Didn't find a memory allocation issue in the codes of  taskbar and mount plugin either.

@palinek's patches may have fixed the issue -- the memory usage seems stable -- but I don't know how a menu-cache leak could continue if the main menu isn't used more than once.

**Comment by palinek** [comment]
If you are installing/removing/changing .desktop files and/or .menu etc...each change should trigger a reload (and the leak), but i also think it shouldn't have had such impact

**Comment by tsujan** [comment]
> but i also think it shouldn't have had such impact

Panel's behavior is weird. Its memory usage always grows, although slowly. I thought it would stop growing with your patches but it didn't. I compare it to pcmanfm-qt, whose memory usage may become high with the desktop module but it'll be reduced after a while.

The next suspect can be `libqtxdg`.

**Comment by stefonarch** [comment]
But is there anyone with the same issue? On my 2 machines panel usage is stable for weeks.
May testing on a clean new user?

**Comment by tsujan** [comment]
> On my 2 machines panel memory usage is stable for weeks.

If only we can find the difference between your case and mine...

Here, the memory usage is suspicious. When all menus are shown, all plugins are right clicked, all tooltips and dialogs are shown 10 times, and especially, when the frequently used apps are run 10 times, for example, then the memory usage shouldn't increase by 0.1 MiB on opening the windows of the same apps for the 11th time. However, it does increase here, although by a small amount.

**Comment by tsujan** [comment]
There's a possibility that what I see may not be a memory leak but how Linux manages memory. In that case, it may be related to the total memory; my RAM is 16 GiB. @stefonarch what's yours?

However, I'm not sure yet because the memory usage shouldn't grow after a while.

**Comment by stefonarch** [comment]
8gb on my 64bit PC, 2gb on the 32bit laptop.

**Comment by tsujan** [comment]
For the record, ksysguard's info:
```
Process 19337 - lxqt-panel

Summary

The process lxqt-panel (with pid 19337) is using approximately 57.1 MB of memory.
It is using 53.0 MB privately, 105.3 KB for pixmaps, and a further 42.9 MB that is, or could be, shared with other programs.
Dividing up the shared memory between all the processes sharing that memory we get a reduced shared memory usage of 4.0 MB. Adding that to the private and pixmap usage, we get the above mentioned total memory footprint of 57.1 MB.

Library Usage

The memory usage of a process is found by adding up the memory usage of each of its libraries, plus the process's own heap, stack and any other mappings, plus the stack of its 6 threads. 

Private

49168 KB	[heap]
984 KB	/usr/bin/lxqt-panel
344 KB	/usr/lib/xorg/modules/dri/i965_dri.so
200 KB	/usr/lib/libQt5Widgets.so.5.9.3
168 KB	/usr/lib/lxqt-panel/libsysstat.so

Shared

4168 KB	/usr/lib/libQt5Gui.so.5.9.3
4156 KB	/usr/lib/libQt5Widgets.so.5.9.3
3928 KB	/usr/lib/libQt5Core.so.5.9.3
1920 KB	/usr/lib/xorg/modules/dri/i965_dri.so
1636 KB	/SYSV00000000 (deleted)

Totals

Pixmap	105 KB	(Might be stored in the graphics card's memory)
Private	54280 KB	(= 1808 KB clean + 52472 KB dirty)
Shared	43952 KB	(= 42256 KB clean + 1696 KB dirty)
Rss	98232 KB	(= Private + Shared)
Pss	58390 KB	(= Private + Shared/Number of Processes)
Swap	0 KB
```

**Comment by tsujan** [comment]
Couldn't find a definite leak in ~33000 lines of valgrind log. Closing this.

**Comment by tsujan** [comment]
For the sake of completeness:

I said, "[The next suspect can be libqtxdg](https://github.com/lxqt/lxqt/issues/1415#issuecomment-348603322)," but didn't look into `libqtxdg` in 2017 because `valgrind` didn't show anything to me. However, `valgrind` might not show a leak if its user doesn't interact with the app.

Long story short, the (big) leak was in `libqtxdg` and is fixed by https://github.com/lxqt/libqtxdg/pull/221.
