### ISSUE TITLE
Hot-swapping keyboards loses xmodmap settings

### ISSUE THREAD

**Issue by Geremia** [lxde/lxqt#1417]
Whenever I add an additional keyboard under LXQt and then remove the keyboard, the layout settings for all keyboards, as defined in my `~/.Xmodmap`, disappear. I have to constantly re-run `xmodmap ~/.Xmodmap` to get my layout settings back.

(I frequently plug in and remove a hardware authentication device, which is basically a fancy keyboard, and I have to re-run `xmodmap ~/.Xmodmap` after removing it.)

I never experienced this issue when using KDE, but it's been a persistent problem since I switched to LXQt a few years ago.

**Comment by palinek** [comment]
LXQt doesn't handle/use `.Xmodmap` anyhow. It is loaded by `xinitrc` or by your display manager. If you want it to be reloaded, you probably need to add some `udev` rule.

(it can be, that KDE somehow reloads `.Xmodmap` after keyboard plug)
