### ISSUE TITLE
Start Menu shortcut cannot be used to close the menu

### ISSUE THREAD

**Issue by RyanBram** [lxde/lxqt#142]
In Mate DE, shortcut button for Start Menu can be used for launching and closing it. In LXQt shortcut button only for launching Start Menu, but for closing it I should use esc.
I hope shortcut button can also be used for closing the menu.

Thanks.

**Comment by PCMan** [comment]
Weird. I can no longer reproduce this with the latest git + qt 5.4 even after removing the fix in https://github.com/lxde/lxqt-panel/commit/b4533cc53939fe5d0d83fbd43b4f840e3cc0ab51 .

**Comment by paulolieuthier** [comment]
I couldn't reproduce either, as I said before. What about #401?

**Comment by PCMan** [comment]
A new PR for it.
https://github.com/lxde/lxqt-panel/pull/131
@paulolieuthier please help review.
Thanks!

**Comment by PCMan** [comment]
fixed in git.
