### ISSUE TITLE
CMAKE 3.10 Warnings

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#1420]
CMAKE 3.10 gives this warning message with libfm-qt and, perhaps, other LXQt programs:

```
  Policy CMP0071 is not set: Let AUTOMOC and AUTOUIC process GENERATED files.                                      
  Run "cmake --help-policy CMP0071" for policy details.  Use the cmake_policy                                      
  command to set the policy and suppress this warning.
```
The "fix" can be:
```
if(POLICY CMP0071)
  cmake_policy(SET CMP0071 NEW)
endif()
```
@luis-pereira, @agaida , would you please look into this?

**Comment by luis-pereira** [comment]
It might not be the best solution in some cases.
Will look into it.

**Comment by tsujan** [comment]
> It might not be the best solution in some cases.

Exactly why I didn't do anything ;) Looking forward to your solution.

**Comment by luis-pereira** [comment]
@tsujan 
It also affects other repos. I will address them all.
For libfm-qt. pls try, https://github.com/lxde/libfm-qt/pull/144

**Comment by tsujan** [comment]
@luis-pereira Thanks!

**Comment by luis-pereira** [comment]
@tsujan @agaida CMP0071 is handled in all repos.

**Comment by tsujan** [comment]
@luis-pereira Thanks for fixing this!

**Comment by agaida** [comment]
@luis-pereira thanks a lot
