### ISSUE TITLE
Change default mixer command in lxqt-panel

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#1421]
right now it is 
```
lxqtvolumeconfiguration.h:    #define SETTINGS_DEFAULT_MIXER_COMMAND      "pavucontrol"
```
should be `pavucontrol-qt` i think.

**Comment by luis-pereira** [comment]
Yes, it should.

**Comment by stefonarch** [comment]
Just installed a fresh archlinux lxqt, pavucontrol-qt is set in mixer but is not installed, so it should be a dependency, not sure where this has to be introduced.

**Comment by tsujan** [comment]
> so it should be a dependency

pavucontrol-qt is an external app, not a dependency. The Arch lxqt-panel package can just recommend it.

**Comment by tsujan** [comment]
@jleclanche, would you please add `pavucontrol-qt` to `optdepends` of lxqt-panel's PKGBUILD?

**Comment by Vladimir-csp** [comment]
pavucontrol-qt depends on pulseaudio, so adding it as a dependency would unconditionally bring ~~death and sorrow~~ pulseaudio with it.
Add `recommends: qasmixer | pavucontrol-qt` and make lxqt-panel autodetect default mixer command among a list of expected variants.
