### ISSUE TITLE
Problem with SVG symbolic icons + Qt5-5.10

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#1425]
After I recompiled the whole LXQt (including libqtxdg) against Qt5-5.10.0, the SVG symbolic icons didn't follow widget palettes anymore. I also did another recompilation to no avail.

A change in private functions of Qt-5.10? I haven't looked into the Qt-5.10 source yet.

**Comment by tsujan** [comment]
Right now, I'm too sleepy to know why my old method https://github.com/lxde/libqtxdg/pull/119/files, which was a copy of KDE's method and superseded by @palinek's, works fine!!

**Comment by tsujan** [comment]
In case someone wants to try it: : [fix_symbolic_icons.diff.zip](https://github.com/lxde/lxqt/files/1566715/fix_symbolic_icons.diff.zip)

**Comment by palinek** [comment]
The Qt v5.10 didn't get it into debian (unstable/testing) yet.... and I don't have time to compile from source and debug it right now....

**Comment by tsujan** [comment]
I know -- it came into manjaro only 2 days ago. However, the attached patch should be OK with all versions.

**Comment by yan12125** [comment]
fix_symbolic_icons.diff.zip works for me, thanks @tsujan!

Environment: Arch Linux latest with git-master for all LXQt packages

**Comment by tsujan** [comment]
@yan12125 Thanks for testing! I'm using it too.

**Comment by yan12125** [comment]
Have been using that patch for one week and everything goes fine. Mind a pull request? @tsujan

**Comment by tsujan** [comment]
Oh, thanks for reminding me of the patch! I'd totally forgotten about it after applying it. Yes, I'll make a PR soon.

**Comment by palinek** [comment]
FYI ... also fixed in upstream https://github.com/qt/qtsvg/commit/b9cddbd84b74fdda30190800ed827dc80aa65f6c

**Comment by tsujan** [comment]
> FYI ... also fixed in upstream

But your current method (https://github.com/lxde/libqtxdg/pull/145) is better than before; isn't it?

**Comment by palinek** [comment]
> But your current method (lxde/libqtxdg#145) is better than before; isn't it?

Right. And we also avoid usage of the `QIcon::isNull()`, so the upstream should have no impact on it.

**Comment by tsujan** [comment]
Good to know that :)

BTW, `QIcon::isNull()` has always been problematic and should be used with care.

**Comment by luis-pereira** [comment]
Ok. Will install kvantum.

**Comment by tsujan** [comment]
@luis-pereira The patch is OK now.

**Comment by luis-pereira** [comment]
@tsujan Good. So , ship it!
