### ISSUE TITLE
pcmanfm-qt: Drap-and-drop doesn't work between directory-tree pane and directory contents pane

### ISSUE THREAD

**Issue by aramazano** [lxde/lxqt#1429]
![pcmanfm-qt-shot](https://user-images.githubusercontent.com/34963702/34455752-ab16b336-ed96-11e7-8f15-4979c7a064cd.png)
I use the stock pcmanfm-qt (v 0.11.3) included in Debian Strecth and I don't know if this is solved in the newer releases. I have skimmed over both open and closed issues list and couldn't find an issue regarding this, so I hope this is not duplicate.

DND works only inside the directory contents pane and also between the tabs, but not between a tab and the directory-tree pane. So, if want to copy/move/symlink a file from different branches of a directory tree, I can still open the source and destination directories in different tabs and do the operation between the tabs.

##### Expected Behavior

It would be more convenient if I could do the copy/move/symlink operation by dragging an item from directory contents (tab in the right pane) to an arbitrary directory in the directory-tree at the left pane.

##### Steps to Reproduce (for bugs)

1. Here is a screenshot and a use case:
	
Suppose you want to symlink the file "/home/aramazan/skala.txt" into the directory "/home/aramazan/ar/msd/"
As shown in the screen shot, you can open two tabs, one being /home/aramazan/" and the other being "/home/aramazan/ar/msd/". Then you can drag the file "skala.txt" in one tab, into the directory /home/aramazan/ar/msd/ in another tab. But this is cumbersome and not very intuitive.

I think it would enhance usability if I could just drag "skala.txt" from within /home/aramazan/ directory listing tab (right pane) to any arbitrary directory shown in the directory-tree (left pane).

##### System Information

* Distribution & Version: Debian 9.3 Stretch
* Kernel: 4.9.0-4-amd64 (Debian 4.9.65-3+deb9u1)
* Qt Version: 5.7.1
* liblxqt Version:  0.11.1-1
* Package version: PCManFM-Qt 0.11.3

**Comment by tsujan** [comment]
> But this is cumbersome and not very intuitive.

With the latest version of pcmanfm-qt, if you drag a file from one page into the *tab* of another page, the tab will be switched to the latter and you could drop the file. It's neither cumbersome -- actually, it's very easy -- nor counter-intuitive.

That being said, it's better to add DND support to the left-pane tree-view -- a feature for future.

**Comment by aramazano** [comment]
If I understand correctly, it is already implemented in v 0.11.3 - I can drag and drop between tabs already. But, as a preparation for DND, I have to open the tabs beforehand (which is what I referred to as "cumbersome").

**Comment by tsujan** [comment]
Opened https://github.com/lxde/pcmanfm-qt/issues/631 in pcmanfm-qt's issue tracker. Closing this.

BTW, if you encounter any problem with the latest version of pcmanfm-qt or have a feature request, please open an issue at https://github.com/lxde/pcmanfm-qt/issues
