### ISSUE TITLE
lxqt-panel segfault in search box

### ISSUE THREAD

**Issue by fenugrec** [lxde/lxqt#1430]
##### Expected Behavior
shouldn't segfault : )

##### Debug info
Having difficulty getting a backtrace from gdb, for the moment I only know the segfault is somewhere in QTextEngine::itemize() 

##### Steps to Reproduce
1. click on the "start menu" (for lack of better name) icon
2. In the "Search" text field, start typing the name of an existing program
3. As soon as the second letter is typed, lxqt-panel crashes

##### System Information
* Distribution & Version: artix rolling
* Kernel: 4.9.70-1-lts
* Qt Version: 5.10.0-1
* liblxqt Version:  0.12.0-1
* lxqt-panel  version: 0.12.0-1

**Comment by tsujan** [comment]
Can't confirm, using the search frequently without problem. Is the panel recompiled against Qt 5.10?

**Comment by fenugrec** [comment]
It appears not :
```
$ lxqt-panel -v
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-q'
lxqt-panel 0.12.0
liblxqt   0.12.0
Qt        5.9.2
```

**Comment by tsujan** [comment]
OK, a downstream problem. When Qt's second version number increases, all LXQt packages should be rebuilt against the new version -- as is the case with KDE too.

**Comment by agaida** [comment]
erm - not exactly right
The private Qt ABI might change even with patch versions :D (major-minor-patch) - so even changed patch versions might justify a rebuild of the relevant packages.

**Comment by tsujan** [comment]
@agaida Maybe, but I've never encountered such an extreme case -- as far as I remember.

**Comment by fenugrec** [comment]
Bleh... thanks for the reply. Hadn't realized Qt was this volatile.

**Comment by tsujan** [comment]
> Bleh... thanks for the reply. Hadn't realized Qt was this volatile.

Actually, we use its private functions. If a Qt app doesn't use them, *usually* it won't need a recompilation, although I prefer to do so, for the sake of certainty.

**Comment by agaida** [comment]
only the private things are volatile - unfortunally we rely on platform things ... (which are private)
> Package: libfm-qt3
> Depends: libc6 (>= 2.14), libexif12 (>= 0.6.21-1~), libfm4, libglib2.0-0 (>= 2.49.3), libmenu-cache3, libqt5core5a (>= 5.9.0~beta), libqt5gui5 (>= 5.7.0), libqt5widgets5 (>= 5.6.0~beta), libqt5x11extras5 (>= 5.6.0), libstdc++6 (>= 5.2), libxcb1, qtbase-abi-5-9-2, shared-mime-info

> Package: libqt5xdgiconloader3
> Depends: libc6 (>= 2.14), libqt5core5a (>= 5.9.0~beta), libqt5gui5 (>= 5.8.0), libstdc++6 (>= 4.1.1), qtbase-abi-5-9-2

> Package: lxqt-qtplugin
> Depends: libc6 (>= 2.14), libdbusmenu-qt5-2 (>= 0.3.2), libfm-qt3 (>= 0.12.0), libglib2.0-0 (>= 2.12.0), libqt5core5a (>= 5.9.0~beta), libqt5dbus5 (>= 5.0.2), libqt5gui5 (>= 5.9.0~beta), libqt5widgets5 (>= 5.0.2), libqt5xdgiconloader3 (>= 3.0.0), libstdc++6 (>= 4.1.1), qtbase-abi-5-9-2

**Comment by tsujan** [comment]
> we rely on platform things

Absolutely right. We need those things to do fundamental jobs, like KDE does.

**Comment by agaida** [comment]
right - so at least these thing should be rebuilt with every new Qt version
