### ISSUE TITLE
Problem with gtk icon cache

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#1435]
The problem was found at https://github.com/lxde/lxqt/issues/1349:

When a new icon is installed (with a package), running apps --pcmanfm-qt and lxqt-panel -- don't see it until they're restarted. As a workaround, missing icons are searched beyond the cache [for now](https://github.com/lxde/libqtxdg/commit/ec711de83cd84193cf0283be65c0bb6ba8a3bb01). I thought it was about a typo but the problem seems to be deeper than that. It seems that the gtk icon cache is updated correctly but Qt doesn't read it.

I opened this issue for us to think about a real solution because, apparently, the problem isn't going to be fixed [in Qt](https://bugreports.qt.io/browse/QTBUG-65720).

Please discuss the issue here!

**Comment by palinek** [comment]
The problem with the GTK cache files is that they are removed and recreated upon the cache rebuild. But each Qt app holds open file descriptor for the "old" file. So after adding an icon the cache file size is increased and the app requiring such data (beyond the previous file size) invalidates its cache and it is never going to revalidate.

I addressed this in the lxde/libqtxdg#149 with the usage of `QFileSystemWatcher`.

Note: for scenarios like looking at the `/usr/share/applications` in pcmanfm-qt and installing a new app with its icon it most probably will not work, because the .desktop file is created sooner than the icon cache refresh is done. (in this case e.g. icon theme is needed to invalidate all `*IconLoaderEngine` objects and force refresh.

**Comment by tsujan** [comment]
> for scenarios like looking at the /usr/share/applications in pcmanfm-qt and installing a new app with its icon it most probably will not work,

Checking "result" works in all scenarios. If something is going to replace it, it should also work everywhere, IMO.

**Comment by palinek** [comment]
> Checking "result" works in all scenarios. If something is going to replace it, it should also work everywhere, IMO.

It won't work e.g.:
- create .desktop file with icon `nonexisting`
- navigate in pcmanfm-qt to the directory with the newly created .desktop file
- create the icon  `/usr/share/icons/hicolor/scalable/apps/nonexisting.svg`
- the icon showed in pcmanfm-qt will still be the "unknown" one
- restart the pcmanfm-qt and navigate to the .desktop file.... you will see the "nonexisting" icon
(or it is enough to change the icon theme and the entries will be re-searched)

It is a race, if the .desktop file is created sooner than the icon file, most probably you will not get the correct icon in pcmanfm-qt - if you are looking in the particular directory while the .desktop file is created.

This can easily happen while the application package is installed (and the files extracted).

**Comment by tsujan** [comment]
@palinek My goal was only that when a new app was installed by the package manager, its icon should be seen in all apps, including `pcmanfm-qt`. Checking "result" does that. I tested that with 3 apps, whose icons didn't exist in any theme I had before installation.

**Comment by tsujan** [comment]
Your reasoning is quite right. But when an app is installed, the menu isn't shown yet and there's no reason for the folder /usr/share/applications to be open -- although I tested with that folder open ;)

**Comment by palinek** [comment]
> But when an app is installed, the menu isn't shown yet and there's no reason for the folder /usr/share/applications to be open

Exactly... so in 99.5% :) you will get the icon correctly with the lxde/libqtxdg#149.

The difference between the `cache.isValid()` vs. `result.isEmpty()` is a performacne penalty for non-existing icons or icons found in parents...
With the `result.isEmpty()` check we only presume that **icons MAY be in the cache** and if not we do stat all the files.
With the `cache.isValid()` check we presume that if cache is valid **icon MUST be in the cache** and if not it will not be found in directories traversal.

That's the difference as I see it and I tend to say that Olivier's concerns about performance are valid.

**Comment by tsujan** [comment]
Please read https://github.com/lxde/libqtxdg/pull/149#issuecomment-357706163 for now. Whenever a *working* solution comes up, I'll tell you. Fears about "performance" really doesn't concern me.

**Comment by tsujan** [comment]
> With the result.isEmpty() check we only presume that icon **MAY be in the cache** and if not we do stat all the files.

Why do you and that Qt dev think I don't understand what you made bold in the above comment?! That Qt dev doesn't say what you said; he thinks that checking "result" is equivalent to not using the cache at all -- or, at least, he likes to exaggerate the situation in that way -- as if a holy cliche is contradicted. My 9-year-old computer doesn't feel a difference. And who opened this issue?

**Comment by tsujan** [comment]
Back to this:

The current code is as simple as this: If a compulsive usage of the cache (reader) hides icons, use it only when it behaves well!

It's an obvious thing that if the cache (reader) is unreliable, the code should search for the missing icons. Fix the cache (reader) and no extra search will be necessary; hence this tracker.

Instead of discussing these matters again and again, I should see how KDE does it because it does it right  -- and has a good authority ;)

**Comment by tsujan** [comment]
`KIconLoader::loadIcon()` has a comment that explains how it works:

1. Sanity checks.
2. Convert _name, group, size, etc. to a key name.
3. Check if the key is already cached.
4. If not, initialize the theme and find/load the icon.
   4a Apply overlays
   4b Re-add to cache.

Step 3 uses `KIconLoaderPrivate::findCachedPixmapWithPath()` to find the icon in the cache and if it isn't found:
```cpp
// Image is not cached... go find it and apply effects.
...
// First we look for non-User icons. If we don't find one we'd search in
// the User space anyways...
```

The [Qt dev in question](https://woboq.com/blog/qicon-reads-gtk-icon-cache-in-qt57.html) "decided against the KDE pixmap cache because the cache is, in [his] opinion, at the wrong level." Nothing wrong in that. However, he adds: 

"Every time you install an application that adds or removes icons from one of the themes, the cache needs to be updated. Qt looks at the modification time of the directories, if any directory is newer than the cache, the cache will not be used."

For whatever reason, his code doesn't work and he doesn't accept that.

So far:

(1) The KDE way isn't ours (probably).

(2) The bug should be found and fixed in Qt's code. Adding the fix to LXQt may be possible but it's too soon to be sure about that.

**Comment by tsujan** [comment]
My conclusion after hours:

● Qt doc says about `QFileSystemWatcher`:
````
The act of monitoring files and directories for modifications consumes system resources..."
````
As it should because it's a continuous job.

● Checking timestamps -- as is done in the c-tor of `QIconCacheGtkReader` -- each time an icon is searched, is, at least, equally bad.

● But searching the theme only for icons that aren't in the gtk cache -- as is already done -- seems more resource-friendly to me.

Anyhow, I've come to the conclusion that, with the current design of Qt icon cache, there's no other way. If the cache was under our control -- as is the case with KDE -- there would be a difference but, still, the code should search for icons that weren't in the cache, as KDE does.

Reopen this if you find a 5th way.

**Comment by agaida** [comment]
@tsujan - i might be wrong - but ... - there was a dependency to libfam in former KDE - so it might help to have a look if fam is still used in KDE and how - and if not maybe we could use fam or similar mechanisms for the cache - feel free to ignore this, if i tell some nonsense here :D

**Comment by tsujan** [comment]
@agaida `fam` and `gamin` are both like `QFileSystemWatcher`. IMHO, that's too much for finding icons.

All in all, icons should always be searched beyond that cache. In this regard, the difference between KDE's code and the current code is that KDE adds the found icons to its cache while we can't add anything to the gtk icon cache but should search the theme for the new icons until the next session.

This is so obvious that I'm sure that Olivier Goffart had known it from start. He may not have thought that his code might be used by a Qt based DE.

**Comment by agaida** [comment]
:D
