### ISSUE TITLE
Start lxqt-panel widgets separately?

### ISSUE THREAD

**Issue by hyiltiz** [lxde/lxqt#1437]
Is there any way to isolate and only start the "Application Menu" without the rest of the lxqt-panel getting started?

##### Expected Behavior
When using lxqt with i3wm, I prever using i3bar over lxqt-panel. However, the "Application Menu" widget that comes along the panel is very useful. In KDE, you can start the widgets using `plasmawindow`. I am wondering is somewhing like that is also feasible in lxqt. If not, maybe I'll create a lxqt-panel with only the "Application Menu" widget added, then somehow ask i3wm to resize it and put it in the corner of the i3bar. Ideally, if we could put the lxqt "Application Menu" in the i3bar that would be awesome.

##### System Information
* Distribution & Version: Debian Testing
* Kernel: Linux version 4.14.0-amd64 (gcc version 7.2.0 (Debian 7.2.0-18)) 
* Qt Version: libqt5core5a 5.9.2+dfsg-6
* liblxqt Version:  0.12.0-5
* Package version: lxqt 23, lxqt-panel 0.12.0-8

**Comment by tsujan** [comment]
No, it isn't possible. See `man lxqt-panel`.

**Comment by c-cesar** [comment]
But you can configure the panel to have only the application menu widget amd configure the size and position to not use a whole side of the desktop.

The only limitation is that the panel have to be in a border of the desktop.

**Comment by tsujan** [comment]
By playing with the settings of the panel, you could choose its size, make its background transparent, select an icon for its menu button, put it at a screen corner or anywhere on a screen edge, etc.

**Comment by hyiltiz** [comment]
Oh, I couldn't really make in into "float" state so I can move it around using `xrandr`. I think I should be able to leave only the wanted widget in the bar, then make the bar only as large as the icon, then put its state as "always on top" of other windows. Not quite sure how to do all that from within the bar settings. If I could float it, xrandr could do the rest.
