### ISSUE TITLE
lxqt-powermanagement system tray not always showing up on a new session

### ISSUE THREAD

**Issue by je-vv** [lxde/lxqt#1443]
When starting a new session, although "Power Management" is set as a LXQT module to start, most of the time the system tray icon for "Power Management" doesn't show up.

I can't tell if this is because of issue #724, or not.  But the workaround is to go to preferences, session setting, and there restart "Power Management" (stop followed by start).

##### System Information
* Distribution & Version:  Arch GNU/Linux (up to date)
* Kernel:  4.15.1
* Qt Version:  5.10.0
* liblxqt Version:  0.12.0

**Comment by palinek** [comment]
Hi, to see if the `lxqt-powermanagement` is started before panel, you can enable the debug output for `lxqt-session` and then check it's stdout/stderr.

To enable debug messages set&export QT_LOGGING_RULES before starting the `lxqt-session` to e.g.: `QT_LOGGING_RULES='lxqt-session.debug=true'`. You can do it in e.g. starting script `/usr/bin/startlxqt`

**Comment by je-vv** [comment]
Well, currently the power management icon is not on the panel (as majority of times), but it doesn't seem it's due to ordering between panel and powermanagement:

+++
0x7ffe17cc2a00) Debug: `/build/lxqt-session/src/lxqt-session-0.12.0/lxqt-session/src/sessionapplication.cpp` : 75 Session "session" about to launch (default 'session')
(0x7ffe17cc2a00) Debug: Environment variable BROWSER = firefox
(0x7ffe17cc2a00) Debug: Environment variable GTK_CSD = 1 
(0x7ffe17cc2a00) Debug: Environment variable GTK_OVERLAY_SCROLLING = 0 
(0x7ffe17cc2a00) Debug: Environment variable QEMU_AUDIO_DRV = pa
(0x7ffe17cc2a00) Debug: Environment variable QEMU_PA_SERVER = /run/user/1000/pulse/native
(0x7ffe17cc2a00) Debug: Environment variable QT_QPA_PLATFORMTHEME = qt5ct
(0x7ffe17cc2a00) Debug: Environment variable TERM = qterminal
(0x7ffe17cc2a00) Debug: "/home/vasqueja/.config/lxqt/session.conf"
(0x7ffe17cc2a00) Debug: xrdb: Xcursor.theme:Adwaita
Xcursor.size:18
Xcursor.theme_core:true

(0x7ffe17cc2a00) Debug: LockScreenManager: LogindProvider will be used
(0x7ffe17cc2a00) Debug: LockScreenManager started successfully
(0x7ffe17cc2a00) Debug: System Tray started
(0x7ffe17cc2a00) Debug: start "/home/vasqueja/.config/autostart/autocutsel-no-sel.desktop"
(0x7ffe17cc2a00) Debug: start "/home/vasqueja/.config/autostart/autocutsel-sel-pri.desktop"
(0x7ffe17cc2a00) Debug: start "/home/vasqueja/.config/autostart/conky.desktop"
(0x7ffe17cc2a00) Debug: start "/home/vasqueja/.config/autostart/cutegram.desktop"
(0x7ffe17cc2a00) Debug: start "/home/vasqueja/.config/autostart/lxqt-compton.desktop"
(0x7ffe17cc2a00) Debug: start "/home/vasqueja/.config/autostart/udiskie.desktop"
(0x7ffe17cc2a00) Debug: start "/home/vasqueja/.config/autostart/xautolock.desktop"
(0x7ffe17cc2a00) Debug: start "/etc/xdg/autostart/lxqt-globalkeyshortcuts.desktop"
(0x7ffe17cc2a00) Debug: start "/etc/xdg/autostart/lxqt-notifications.desktop"
(0x7ffe17cc2a00) Debug: start "/etc/xdg/autostart/lxqt-panel.desktop"
(0x7ffe17cc2a00) Debug: start "/etc/xdg/autostart/lxqt-policykit-agent.desktop"
(0x7ffe17cc2a00) Debug: start "/etc/xdg/autostart/lxqt-runner.desktop"
(0x7ffe17cc2a00) Debug: start "/etc/xdg/autostart/pulseaudio.desktop"
(0x7ffe17cc2a00) Debug: start tray app "/etc/xdg/autostart/lxqt-powermanagement.desktop"
+++

And:

+++
% cat /etc/xdg/autostart/lxqt-powermanagement.desktop                                                                                                                                                                                        
[Desktop Entry]
Type=Application
Version=1.0
Name=Power Management
TryExec=lxqt-powermanagement
Exec=lxqt-powermanagement
OnlyShowIn=LXQt;
X-LXQt-Need-Tray=true
X-LXQt-Module=true

Name[da]=Strømstyring
Name[de]=LXQt-Energieverwaltung
Name[el]=Διαχείριση ενέργειας
Name[fr]=Gestion de l'énergie
Name[it]=Gestore energia
Name[lt]=Maitinimo valdymas
Name[pl]=Zarządzanie energią
Name[pt]=Gestor de energia do LXQt
+++

I see the call for powermanagement (as a tray app) after the call for the panel.

So honestly, no clue as to why powermanagement doesn't show up on the tray...

**Comment by je-vv** [comment]
Well, if all  "start" instructions execute on their own threads, it might be there's a raise condition still.  That is, if panel is not up and running, fully working, when powermanagment gets started...

**Comment by je-vv** [comment]
BTW, I see something weird though, notice all autostart applications are started prior to panel, and that might be the reason one that I attempted to load on tray only, "quimup", when autostarting it, it doesn't show up on tray...  I'm wondering if autostarted applications should be called after all session modules are already up and running, or at least the panel one.  As for the powermanagement, the might still be a raise condition as mentioned before...

**Comment by tsujan** [comment]
My 2 cents: even if an app with a systray is started before the panel -- and why not? there are so many --  it should have a time-out (1-2 min., for example) to determine whether a systray is available or not. If the panel/tray is there before the time-out expires, the icon should be shown.

If Power Management isn't so, that should be seen as a bug in it. Panel is OK, IMO.

**Comment by palinek** [comment]
Based on your debug output, you have "tray" available even before lxqt-panel started:
```
...
(0x7ffe17cc2a00) Debug: System Tray started
...
(0x7ffe17cc2a00) Debug: start "/etc/xdg/autostart/lxqt-panel.desktop"
...
```
... so I believe the problem here is with your configuration.

Is some other app providing the tray even before launching the lxqt-session?

BTW, I don't see the "Window Manager started" log message in your output. What WM do you use and how do you start it?

**Comment by je-vv** [comment]
I use fluxbox, and I start it through:

% grep fluxbox .config/lxqt/session.conf 
window_manager=fluxbox

I do have the fluxbox toolbar invisible:

% grep toolbar .fluxbox/init                                                                                                                                                                                                                  
session.screen0.toolbar.visible:     false

But it might be though not visible, the systemtray is getting in the way.  I'll recompile fluxbox without it, and see if I can get consistent behavior from powermanagement, and other tray applications.

**Comment by je-vv** [comment]
OK, using fluxbox withoty system tray, without toolbar, and without slit, looks much better.  A couple of times of logging out and logging back in, keeps powermanagement on tray.  It also brought back legacy application icons, which I was missing.

However, "quimup" still doesn't show up on the tray when included in the autostart directory.  Though when I call it after the WM and LXQT are up and running, there's no problem getting it into the tray.  Here it's the new session debug output:

+++
(0x7ffef6031190) Debug: /build/lxqt-session/src/lxqt-session-0.12.0/lxqt-session/src/sessionapplication.cpp : 75 Session "session" about to launch (default 'session')
(0x7ffef6031190) Debug: Environment variable BROWSER = firefox
(0x7ffef6031190) Debug: Environment variable GTK_CSD = 1 
(0x7ffef6031190) Debug: Environment variable GTK_OVERLAY_SCROLLING = 0 
(0x7ffef6031190) Debug: Environment variable QEMU_AUDIO_DRV = pa
(0x7ffef6031190) Debug: Environment variable QEMU_PA_SERVER = /run/user/1000/pulse/native
(0x7ffef6031190) Debug: Environment variable QT_QPA_PLATFORMTHEME = qt5ct
(0x7ffef6031190) Debug: Environment variable TERM = qterminal
(0x7ffef6031190) Debug: "/home/vasqueja/.config/lxqt/session.conf"
(0x7ffef6031190) Debug: xrdb: Xcursor.theme:Adwaita
Xcursor.size:18
Xcursor.theme_core:true

(0x7ffef6031190) Debug: LockScreenManager: LogindProvider will be used
(0x7ffef6031190) Debug: LockScreenManager started successfully
(0x7ffef6031190) Debug: Window Manager started
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/autocutsel-no-sel.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/autocutsel-sel-pri.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/conky.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/cutegram.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/lxqt-compton.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/quimup.desktop"
conky: desktop window (147) is root window
conky: window type - override
conky: drawing to created window (0x1200002)
(0x7ffef6031190) Debug: start "/usr/share/applications/signal-tray.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/udiskie.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/xautolock.desktop"
(0x7ffef6031190) Debug: start "/etc/xdg/autostart/lxqt-globalkeyshortcuts.desktop"
(0x7ffef6031190) Debug: start "/etc/xdg/autostart/lxqt-notifications.desktop"
conky: drawing to double buffer
(0x7ffef6031190) Debug: start "/etc/xdg/autostart/lxqt-panel.desktop"
(0x7ffef6031190) Debug: start "/etc/xdg/autostart/lxqt-policykit-agent.desktop"
(0x7ffef6031190) Debug: start "/etc/xdg/autostart/lxqt-runner.desktop"
(0x7ffef6031190) Debug: start "/etc/xdg/autostart/pulseaudio.desktop"
(0x7ffef6031190) Debug: System Tray started
(0x7ffef6031190) Debug: start tray app "/etc/xdg/autostart/lxqt-powermanagement.desktop"
+++

**Comment by je-vv** [comment]
OK, using fluxbox withoty system tray, without toolbar, and without slit, looks much better.  A couple of times of logging out and logging back in, keeps powermanagement on tray.  It also brought back legacy application icons, which I was missing.

However, "quimup" still doesn't show up on the tray when included in the autostart directory.  Though when I call it after the WM and LXQT are up and running, there's no problem getting it into the tray.  Here it's the new session debug output:

+++
(0x7ffef6031190) Debug: /build/lxqt-session/src/lxqt-session-0.12.0/lxqt-session/src/sessionapplication.cpp : 75 Session "session" about to launch (default 'session')
(0x7ffef6031190) Debug: Environment variable BROWSER = firefox
(0x7ffef6031190) Debug: Environment variable GTK_CSD = 1 
(0x7ffef6031190) Debug: Environment variable GTK_OVERLAY_SCROLLING = 0 
(0x7ffef6031190) Debug: Environment variable QEMU_AUDIO_DRV = pa
(0x7ffef6031190) Debug: Environment variable QEMU_PA_SERVER = /run/user/1000/pulse/native
(0x7ffef6031190) Debug: Environment variable QT_QPA_PLATFORMTHEME = qt5ct
(0x7ffef6031190) Debug: Environment variable TERM = qterminal
(0x7ffef6031190) Debug: "/home/vasqueja/.config/lxqt/session.conf"
(0x7ffef6031190) Debug: xrdb: Xcursor.theme:Adwaita
Xcursor.size:18
Xcursor.theme_core:true

(0x7ffef6031190) Debug: LockScreenManager: LogindProvider will be used
(0x7ffef6031190) Debug: LockScreenManager started successfully
(0x7ffef6031190) Debug: Window Manager started
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/autocutsel-no-sel.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/autocutsel-sel-pri.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/conky.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/cutegram.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/lxqt-compton.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/quimup.desktop"
conky: desktop window (147) is root window
conky: window type - override
conky: drawing to created window (0x1200002)
(0x7ffef6031190) Debug: start "/usr/share/applications/signal-tray.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/udiskie.desktop"
(0x7ffef6031190) Debug: start "/home/vasqueja/.config/autostart/xautolock.desktop"
(0x7ffef6031190) Debug: start "/etc/xdg/autostart/lxqt-globalkeyshortcuts.desktop"
(0x7ffef6031190) Debug: start "/etc/xdg/autostart/lxqt-notifications.desktop"
conky: drawing to double buffer
(0x7ffef6031190) Debug: start "/etc/xdg/autostart/lxqt-panel.desktop"
(0x7ffef6031190) Debug: start "/etc/xdg/autostart/lxqt-policykit-agent.desktop"
(0x7ffef6031190) Debug: start "/etc/xdg/autostart/lxqt-runner.desktop"
(0x7ffef6031190) Debug: start "/etc/xdg/autostart/pulseaudio.desktop"
(0x7ffef6031190) Debug: System Tray started
(0x7ffef6031190) Debug: start tray app "/etc/xdg/autostart/lxqt-powermanagement.desktop"
+++

**Comment by je-vv** [comment]
BTW, I see from quimup command line:

+++
 quimup
qt5ct: using qt5ct plugin
Quimup : starting new instance
Locale : using none
libpng warning: iCCP: known incorrect sRGB profile
Getting settings : OK
qt5ct: D-Bus system tray: yes
MPD's config : Tried /etc/default/mpd but it does not exist
Auto-detecting MPD's config file(s) :  /etc/mpd.conf 
Local default server address
Auto-connecting, as configured
MPD is already running
Connected to MPD on try 1
No password provided (probably not required)
Disallowed MPD commands : none reported
MPD errors: none reported
MPD's music dir : looking in /etc/mpd.conf
MPD's music dir : /var/lib/mpd/music
MPD's music dir : appears to be accessible
Replaygain mode set to "album"
Playlist : updated
+++

Where the relevant part is:

+++
qt5ct: D-Bus system tray: yes
+++

It might be quimup doesn't wait for system tray to show up and decide to go on the background...  Not sure, but what's certain is that the system tray shows up later than quimup is started...

**Comment by je-vv** [comment]
Seems like it...  Quimup perhaps is not waiting for the tray to be up and running.  I changed the autostart desktop file to use:

+++
% grep Exec .config/autostart/quimup.desktop 
Exec=sh -c "sleep 5 ; quimup"
+++

And it works (with some delay of course)...  Is there a bash (dbus perhaps) to just wait for the tray to be up and running before calling the misbehaving app?  I guess depending on the system the delay should need adjustment, :(.  According to [https://stackoverflow.com/questions/5290611/qt-app-fails-to-create-the-tray-icon-when-it-runs-on-startup](url), on QT one could use "QSystemTrayIcon::isSystemTrayAvailable()", but that of course is modifying the app, but I'm looking to workaround the misbehavior without touching the app 1st...

BTW, there's no issues with LXQT, so I'm closing.  However is someone can help with the workaround I'm looking for, please let me know...

Thanks !

**Comment by palinek** [comment]
> And it works (with some delay of course)... Is there a bash (dbus perhaps) to just wait for the tray to be up and running before calling the misbehaving app?

lxqt-session uses the extension .desktop key `X-LXQt-Need-Tray`... so you can add following into yours quimup.desktop:
```
X-LXQt-Need-Tray=true
```
...and starting of `quimup` will be delayed automatically by `lxqt-session`

**Comment by je-vv** [comment]
X-LXQt-Need-Tray=true works flawlessly, thanks a lot :+1:  !
