### ISSUE TITLE
For all gog games always the same icon is displayed in 'main menu' and 'runner dialog' 

### ISSUE THREAD

**Issue by robschi** [lxde/lxqt#1444]
##### Expected Behavior
Each gog game has a separate icon an this icon should be displayed in 'main menu --> Games' or in the 'runner dialog' 

##### Current Behavior
For all of my gog games only one icon is displayed, and I think this is because the name of every icon is "icon.png" and therefore only the icon from the alphabetically first game under "~/.local/share/applications" is displayed, which is in my case "Icon=/home/<username>/GOG Games/Besiege/support/icon.png" from "gog_com-Besiege_1.desktop"

Although, the icons are correctly displayed in PCManFM-QT when i navigate to "~/.local/share/applications"

##### Possible Solution
????

##### Steps to Reproduce (for bugs)
You can install a bunch of gog games ;-) .
Or I think creating some .desktop files with different "Icon=" in different folders with the name "icon.png" will show you this behavior.

##### Context
---

##### System Information
* Distribution & Version: Debian Testing
* Kernel: Linux 4.14.0-3-amd64 #1 SMP Debian 4.14.13-1 (2018-01-14) x86_64 GNU/Linux
* Qt Version: 5.9.2
* liblxqt Version:  0.12.0
* Package version:  lxqt-metapackages 23

**Comment by palinek** [comment]
The caching mechanism is screwed in the `XdgIcon::fromTheme()' and both - panels mainmenu & lxqt-runner - are using it. I'll make PRs...

**Comment by palinek** [comment]
Both PRs are merged..
