### ISSUE TITLE
Request: LXDE Menu Plugin Needs Rework and Redesign

### ISSUE THREAD

**Issue by That-Random-Guy** [lxde/lxqt#1448]
##### Expected Behavior
The menu plugin should allow for it to be resizable. That is, its dimensions should be allowed to be tweaked with without resorting to theme-ing or direct code manipulation. The menu plugin should be fixed to a certain size that takes up MORE than 5% of the screen (both horizontal & vertical). Currently, the thing only takes up a minimal portion of the screen. While this can be attributed to the things the actual menu list items can contain (text), that is no excuse for that lacking, half-done design. Additionally, the menu only harbors launchers and them some, but nothing but that! It doesn't have graphical spaces to make it easier to hit something, it doesn't have buttons, it doesn't have a search box, and it doesn't have proper ease of access to critical or favorite apps. This is ludicrous!

##### Current Behavior
The menu plugin for the LXPanel has ridiculously small dimensions by default and lacks the necessary arrangement/style to be used efficiently. It also lacks many items which are pretty much de facto for any modern Linux distro--regardless of its strategic intent. See above for some examples of what I want.

##### Context
**"How has this issue affected you? What are you trying to accomplish?"**

I didn't think menu components for panels was something I even cared about until I used Lubuntu. It was only until then when I realized how much I despised a poorly designed menu. I use it on occasion, and when I do use it, I expect it to be designed well enough to find utility in it. That means having buttons, that means having easier access to applications of my choice when opening the menu, and that means having a search function of some sort. LXDE AND LXqt BOTH fail at this and I can't fathom why.

**"Providing context helps us come up with a solution that is most useful in the real world"**

If anyone who actually developed this took a course on HCI and relevant design schooling, they'd never have gone through and distributed such a poor menu design. By default, its atrocious and it lacks so many things that could be useful to the user.

I'm using Lubuntu 17, so go figure on the versions for everything else.

My real gripe with this is that the standard that this plugin is based on is openbox. OB seems to be the most restricted window manager of all time and it haunts me to think that this is acceptable by any means. Openbox either needs to be updated or replaced as it lacks way too much for the user to add in.

We can't even get a search option? How sad is that? It's 2018!

**Comment by tsujan** [comment]
> its dimensions should be allowed to be tweaked with without resorting to theme-ing

Why?! The stylesheet is there for such things.

> they'd never have gone through and distributed such a poor menu design.

The menu itself has no special design -- it's simply a `QMenu`.

If all the provided stylesheets (LXQt themes) look ugly to you, you could make a stylesheet according to your taste and share it with others.

> My real gripe with this is that the standard that this plugin is based on is openbox.

You're wrong. Nothing is based on openbox in LXQt.

The look of LXQt can be ugly or superb, depending on the Qt style + stylesheet you use.

**Comment by tsujan** [comment]
> and that means having a search function of some sort.

Do you really use LXQt?!

**Comment by agaida** [comment]
No, he don't - otherwise he had written lubuntu next - not that i'm supriesed

**Comment by That-Random-Guy** [comment]
@tsujan 

You're both right in assuming I've never used LXqt, although I've seen snapshots of it from their own page.

I was under the impression that they were sister projects and therefore assumed they both had that same weakness.

Lastly, what style sheet? If you're referring to the gktrc file, then that is not a viable solution.

I shouldn't have to rely on that for every instance I want the menu altered. By design, the menu should come with some config menu that allows me to alter its properties from a front-end. Not to mention the above mentioned file only allows so much to be configured. I've managed to get increase the size of the menu by increasing the font size of the list items.

According to [this](https://sourceforge.net/p/lxde/feature-requests/310/#a00f) person, he suggested I do just that but I find that a silly solution.

The wiki-page I was directed to in order to find the specific selectors I could manipulate where minimal.

AKAIK, there's no actual way to manipulate the menu's width or height unless one makes changes to the font size for the menu items.

**Comment by That-Random-Guy** [comment]
Might I add that the closing of this issue was premature and without legitimate reason.

**Comment by agaida** [comment]
Might i add that you are in the wrong issue tracker (and the wrong project)? So i don't think that the closing was not premature ...

**Comment by tsujan** [comment]
@That-Random-Guy

Like @agaida, I think you've mistaken LXDE for LXQt. Mentioning `gktrc` confirms my suspicion.

LXDE and LXQt are separate projects. The first one is based on GTK, the second on Qt. Their file managers, panels and desktop are quite different.

Our main menu (as well as panel)  is highly configurable, has a good search, and can be styled in any way the user wants, provided that he/she knows how to work with stylesheets. It doesn't have a favorite section though and we're aware of that (lack of time).

Also, OpenBox is optional. I use Compiz-reloaded with LXQt. Previously, I used KWin.

**Comment by tsujan** [comment]
>  Might I add that the closing of this issue was premature and without legitimate reason.

I think you see now that @agaida had a good reason to close this.

**Comment by tsujan** [comment]
@agaida I use this page to ask you:

Do you have a plan for new releases of pcmanfm-qt and libfm-qt. They have been quite stable and the sooner users have them, the more feedback we'll get.

**Comment by agaida** [comment]
@tsujan - i want to have the whole things out asap - and iirc that will need a libfm release before. I hope that @LStranger will find the needed time:
```
 2018-02-10  00:14:31 <LStranger> tsimonq2: oh, thank you very much, will look at it when time permits, have to find time for it, also few other packages need attention, libfm and others. Hope to get to it next week.
```

**Comment by That-Random-Guy** [comment]
@agaida 

Do you know why then LXDE is so limited as far as the panel is considered?

I'm asking legitimately, not rhetorically. Why can Qt do what you're saying it can but not LXDE or openbox for that matter? Why did they decide to make it so limited without thinking about the future?

**Comment by agaida** [comment]
Good question - menues (or better:  every kind of navigation or org components) highly depend on the intentions and likes of the developers. In case of LXDE one can also add that it is mature - so longtime users like and rely on certain behaviour and functionality - and that make it sometimes hard to change things without breaking things for long term users.

Different underlying frameworks can lead to different and improved solutions - otherwise it might be that functionality from LXDE (GTK) is hard or nearly impossible to implement. And LXQt is the new approach, so we try hard not to implement the same shortcomings LXDE have in LXQt. :)

**Comment by tsujan** [comment]
I like to add that GTK+ is a powerful toolkit too. I remember that LXQt was started after Gnome devs made suspicious changes to GTK+ with disregard for the GTK based DEs other than Gnome (one of them pretended he didn't know about XFce). As a result of this strange behavior, many developers couldn't trust GTK+ anymore. So, we may owe LXQt to that state of affairs.

There are signs of stability in GTK3 development. Either Gnome devs have finally found what they want or they're planning yet another sabotage ;)

BTW, you couldn't expect heavy changes in LXDE anymore.
