### ISSUE TITLE
lxqt-panel can no longer show SVG icons specified as absolute paths

### ISSUE THREAD

**Issue by yan12125** [lxde/lxqt#1451]
##### Expected Behavior
![default](https://user-images.githubusercontent.com/1937689/36627509-ea1d4e5a-197e-11e8-9700-200d0a697b91.png)

The screenshot is taken after reverting https://github.com/lxde/lxqt-panel/commit/286eff468846f484baca7e84710e545b6de7c849

##### Current Behavior
![default](https://user-images.githubusercontent.com/1937689/36627492-8fb74c72-197e-11e8-9ff3-6beb8bfdf121.png)
The highlighted item is missing its blue "P" icon.

##### Possible Solution
Reverting https://github.com/lxde/lxqt-panel/commit/286eff468846f484baca7e84710e545b6de7c849

##### Steps to Reproduce (for bugs)
1. Installing PCManX. I use the [AUR package](https://aur.archlinux.org/packages/pcmanx-gtk2). You can also [install from sources](https://github.com/pcman-bbs/pcmanx#how-to-build-)
2. Check the Internet category of the main menu

##### Context
I observed this after an occasional update

##### System Information
* Distribution & Version: Arch Linux x86_64
* Kernel: 4.15.4-1-ARCH
* Qt Version: 5.10.1-2
* liblxqt Version: git master
* Package version: git master

**Comment by tsujan** [comment]
@yan12125 In your screenshot, aren't the other icons -- like the Leave icon --  SVG too?

**Comment by yan12125** [comment]
> In your screenshot, aren't the other icons -- like the Leave icon -- SVG too?

Hey good point! I do more tests and find something interesting: SVG icons don't work _only if_ they are specified as absolute paths.

In /usr/share/applications/pcmanx.desktop, if I change the following line
```
Icon=/usr/share/pixmaps/pcmanx.svg
```
to
```
Icon=pcmanx
```
The P icon is correctly shown even with https://github.com/lxde/lxqt-panel/commit/286eff468846f484baca7e84710e545b6de7c849.

On the other hand, if I change the following line in /usr/share/desktop-directories/lxqt-leave.directory
```
Icon=system-shutdown
```
to
```
Icon=/usr/share/icons/breeze/actions/32/system-shutdown.svg
```
The leave icon is gone.

As a reference, absolute paths for ```Icon``` are allowed in the XDG specification: https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

BTW, seems only SVG icons are affected. Change ```Icon=dropbox``` to ```Icon=/usr/share/pixmaps/dropbox.png``` in /usr/share/applications/dropbox.desktop does not break the Dropbox icon.

**Comment by yan12125** [comment]
OK I found the cause. Here's the code in QIcon::fromTheme
```C++
QIcon QIcon::fromTheme(const QString &name, const QIcon &fallback)
{
    QIcon icon = fromTheme(name);

    if (icon.isNull() || icon.availableSizes().isEmpty())
        return fallback;

    return icon;
}
```
When ```name``` is an absolute path pointing to an SVG image, ```icon.availableSizes()``` is empty. XdgIcon can handle it as [it has absolute paths in mind](https://github.com/lxde/libqtxdg/blob/master/qtxdg/xdgicon.cpp#L107).

**Comment by yan12125** [comment]
A possible fix for lxqt-panel => https://github.com/lxde/lxqt-panel/pull/458

I'm not sure if lxqt-runner has similar issues or not. I don't use that.

**Comment by yan12125** [comment]
OK, there's already a Qt bug report https://bugreports.qt.io/browse/QTBUG-63187

/cc @palinek

**Comment by palinek** [comment]
> When name is an absolute path pointing to an SVG image, icon.availableSizes() is empty. XdgIcon can handle it as it has absolute paths in mind.

Right... I didn't realized that. We should: 
1. not "abuse" the `QIcon::fromTheme()` to look for absolute paths
2. use just the `QIcon::isNull()` check... (the `isNull` hook was [recently added](https://github.com/qt/qtsvg/commit/4a9470e55ce08752501868c60762268fdf2c44af) to the qtsvgiconengine)

**Comment by palinek** [comment]
> 1. not "abuse" the QIcon::fromTheme() to look for absolute paths

... or update our `XdgIconLoaderEngine` to handle also absolute paths (as name) correctly

@lxde/lxqt  What do you think is better?

**Comment by yan12125** [comment]
> ... or update our XdgIconLoaderEngine to handle also absolute paths (as name) correctly

Do you mean going back to XdgIcon::fromTheme?

**Comment by palinek** [comment]
> > ... or update our XdgIconLoaderEngine to handle also absolute paths (as name) correctly

> Do you mean going back to XdgIcon::fromTheme?

No, I didn't.... but I was wrong...as the `QIcon::fromTheme()` does handle absolute file paths:
```c++
  QIcon QIcon::fromTheme(const QString &name)
  {
      QIcon icon;
  
      if (qtIconCache()->contains(name)) {
          icon = *qtIconCache()->object(name);
      } else if (QDir::isAbsolutePath(name)) {
          return QIcon(name);
      } else {
          QPlatformTheme * const platformTheme = QGuiApplicationPrivate::platformTheme();
          bool hasUserTheme = QIconLoader::instance()->hasUserTheme();
          QIconEngine * const engine = (platformTheme && !hasUserTheme) ? platformTheme->createIconEngine(name)
                                                     : new QIconLoaderEngine(name);
          QIcon *cachedIcon  = new QIcon(engine);
          icon = *cachedIcon;
          qtIconCache()->insert(name, cachedIcon);
      }
  
      return icon;
  }
```
... so we don't need to handle the absolute paths file names in our engine.

The problem here is the "fallback" overload, which checks also the `availableSizes()` (as @yan12125 correctly pointed to the qt bug).

**Comment by palinek** [comment]
And for the record... `lxqt-runner` should not suffer from this issue as it is calling the "right" overload of `QIcon::fromTheme()` already.
