### ISSUE TITLE
unsupported $HOME enviroment by pcmanfm-qt

### ISSUE THREAD

**Issue by ianamk** [lxde/lxqt#1452]
I'm running opensuse LEAP 42.2 with lxqt 0.11.0 and the Home desktop icon carried over from KDE is shown as a text file and it can not be opened by pcmanfm-qt
as I browsed thru the Home.desktop file I came across these lines
```
URL[$e]=$HOME
Icon=user-home
Type=Link

```
I tried pasting $HOME in pcmanfm-qt but instead of opening my home directory it opens the root /
pasting ~ in the address bar pcmanfm-qt goes to my home
##### Expected Behavior
the Home.desktop file to be shown as user-home icon and to be opened with pcmanfm-qt and $HOME environment variable to point to ~ or /home/<user>
the fact that  pcmanfm-qt does not support URL[$e]=$HOME I'm guessing is the reason Home.desktop is shown as a text file and not a launcher for my /home/<me> in pcmanfm-qt 
##### Current Behavior
pcmanfm-qt does not support the $HOME variable when pasting $HOME in the address bar pcman-fm opens the / folder (I'm not root) and the Home.desktop file is shown as a plain text file not a launcher
##### Steps to Reproduce (for bugs)
1. if you're running plasma 5 just log off plasma 5 and login to lxqt the Home.desktop file should be shown as a text file
2. paste $HOME in pcmanfm-qt address bar it should open your home it opens the root /
##### Context
the display of Home.desktop is annoying it's a cosmetic bug, the lack of $HOME support in pcman-fm is an issue
##### System Information

* Distribution & Version: OpenSUSE LEAP 42.3 
* Kernel: 4.4.114
* Qt Version: 5.6.2
* liblxqt Version:  0.11.0-3.2
* Package version: 0.11.0
![2](https://user-images.githubusercontent.com/28848990/36674684-03aa625c-1b07-11e8-9a59-0d13fce85db6.png)

**Comment by Vladimir-csp** [comment]
`URL[$e]=$HOME` this notation sure is weird.
I do not see it anywhere in XDG Desktop Entry spec.
First, `$HOME` as an argument to URL is pretty dubious, second what does `[$e]` stand for?

**Comment by palinek** [comment]
Third, where does it come from pcmanfm-qt should support interpreting `$` variables inserted into the path bar?

**Comment by ianamk** [comment]
> URL[$e]=$HOME

was not done by me but by the kde devs
I'm not sure what the [$e] stands for, removing the [$e] displays the desktop icon as a launcher but it does not open it with anything
$HOME should be supported by pcmanfm-qt it's not something new
I tried replacing the $HOME with ~ but that doesn't work either I'm looking for a way for lxqt to open my home from my home in pcmanfm-qt the same way it opens the trash?

**Comment by ianamk** [comment]
a google search revealed an old kde thread
https://forum.kde.org/viewtopic.php?t=32909
if I understood that thread correctly
URL[$e] means that the url contains the $ so it should be passed to the application without it the passed url would be DESKTOP not $DESKTOP
but as I said 
URL=$HOME
does not work, on my setup that does nothing

**Comment by ianamk** [comment]
I tried editing that desktop file so instead of an Type=Link it's a Type=Application and Exec=xdg-open $HOME
I now get a new error
```
>xdg-open $HOME
/usr/bin/xdg-open: line 885: pcmanfm: command not found

```I don't have pcmanfm: installed I never did is this a new bug?

**Comment by tsujan** [comment]
It may be possible to change the code so that $HOME and some other EVs are supported for URL but the code is inside `libfm`, whose development is inhibited  -- I for one have got tired of fighting this situation, at least for now.

**Comment by Vladimir-csp** [comment]
This syntax not only violates the spec but also ignores extension mechanism provided by the spec. 
Correct ways of doing this would be:

- adding something like `X-rich-URL=$HOME` to Link type entry and interpret that in implementation.
- make Applicaton type entry relying on some opener `Exec=sh -c "xdg-open \"$HOME\""`.

**Comment by tsujan** [comment]
> Whatever KDE devs did, if it isn't in the specs, there is no point in spreading it.

That was good news to me :)

And yes, KDE does nonstandard things, maybe, because of its history or because those standards were set after KDE did those jobs in its own way....

**Comment by agaida** [comment]
and 
```
>xdg-open $HOME
/usr/bin/xdg-open: line 885: pcmanfm: command not found
```
is the result of the reliable and fast (as lightspeed) work of the XDG guys:
https://bugs.freedesktop.org/show_bug.cgi?id=103146

**Comment by agaida** [comment]
And yes - i know how to make good friends:
Processing control commands:

> severity -1 grave

> Bug #884436 [xdg-utils] xdg-open: wrongly handled file/URL in LXQt
> Bug #887027 [xdg-utils] xdg-open: "Open destination folder" doesn't work with PCManFM
> Severity set to 'grave' from 'normal'
> Severity set to 'grave' from 'normal'
> 
> -- 
> 884436: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884436
> 887027: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887027
> Debian Bug Tracking System

**Comment by agaida** [comment]
ok, a 'little' bit ranting seems to help sometimes - at least the xdg-open patch is landed in Debian. Let's pray a little bit that upstream merge this too in this century. :imp:

**Comment by tsujan** [comment]
> ok, a 'little' bit ranting seems to help sometimes

I'd call it "aggressive feedback" :D
