### ISSUE TITLE
Segmentation fault on start.

### ISSUE THREAD

**Issue by Pedro-MC** [lxde/lxqt#1453]
##### Expected Behavior

No segmentation fault on start. :)

##### Current Behavior

Segmentation fault on start.

##### Steps to Reproduce (for bugs)
1. Just run lxqt-panel

##### System Information
* Distribution & Version: Mageia 6
* Kernel: 4.14.20-desktop-1.mga6
* Qt Version: 5.9.3
* liblxqt Version: 0.11.1
* Package version: 3.mga6

Backtrace from gdb is in attached file.
[lxqt-panel_gdb_output.log](https://github.com/lxde/lxqt/files/1764205/lxqt-panel_gdb_output.log)

**Comment by tsujan** [comment]
Your installed liblxqt is old and I guess you have an old version of the panel too.

**Comment by agaida** [comment]
right - Downstream problem, they should upgrade their stuff.

**Comment by Pedro-MC** [comment]
liblxqt 0.11.1 is old? What is the most recent release version?

**Comment by agaida** [comment]
@Pedro-MC - current version is 0.12.0, we are planning the next release right now - depending on some things we don't have any influence it might be April/May. It was planned as 0.12.1 in Feb/March, but unfortunately we are blocked by some dependencies right now. So we are eager to release, i guess we will name it 0.13.0 - no ETA, but asap.
