### ISSUE TITLE
My Computer, My Docs, My Network, Trash Bin icons on Desktop.

### ISSUE THREAD

**Issue by Cybermaxrus** [lxde/lxqt#1454]
Hello! I would like to have icons on the desktop: My Computer, My Documents, My Network, Trash Bin. So that you can choose which icons to display.
Something like that - https://yabaso.files.wordpress.com/2011/01/09_desktop_icon_settings_dialog_thumb.png
I think this feature would be very convenient, thanks in advance.

**Comment by agaida** [comment]
This is not a feature.
