### ISSUE TITLE
Directory Menu widget doesn't open the dirs.

### ISSUE THREAD

**Issue by githubtefo** [lxde/lxqt#1455]
I can navigate trough the dirs, but when I click on "Open", nothing happens.

##### System Information

* Distribution & Version: Arch x64.
* Kernel: 4.15
* Qt Version: 5.10.1
* liblxqt Version:  0.12.0
* Package version:

**Comment by tsujan** [comment]
Right now, I added Directory Menu widget to the panel and the "Open" menu-item always opened directories correctly with pcmanfm-qt. LXQt version is the latest git.

My guess: a bad [xdg-utils](https://github.com/lxde/lxqt/issues/1298) in your case (although the upstream should have been fixed).

**Comment by stefonarch** [comment]
What responds this?
`xdg-mime query default inode/directory`

**Comment by githubtefo** [comment]
@stefonarch, the output is:
```
Checking /home/USER/.config/mimeapps.list
Checking /home/USER/.local/share/applications/lxqt-defaults.list and /home/USER/.local/share/applications/lxqt-mimeinfo.cache
Checking /home/USER/.local/share/applications/defaults.list and /home/USER/.local/share/applications/mimeinfo.cache
Checking /home/USER/.local/share/applications/lxqt-defaults.list and /home/USER/.local/share/applications/lxqt-mimeinfo.cache
Checking /home/USER/.local/share/applications/defaults.list and /home/USER/.local/share/applications/mimeinfo.cache
Checking /usr/local/share/applications/lxqt-defaults.list and /usr/local/share/applications/lxqt-mimeinfo.cache
Checking /usr/local/share/applications/defaults.list and /usr/local/share/applications/mimeinfo.cache
Checking /usr/share/applications/lxqt-defaults.list and /usr/share/applications/lxqt-mimeinfo.cache
Checking /usr/share/applications/defaults.list and /usr/share/applications/mimeinfo.cache
pcmanfm-qt.desktop
```

**Comment by stefonarch** [comment]
Uhm, I had that issue, not sure how I solved though,  dirty hack
```
ls -l /usr/bin/xdg-open
lrwxrwxrwx 1 root root 9 Oct 14 20:18 /usr/bin/xdg-open -> kde-open5
```

**Comment by tsujan** [comment]
> Uhm, I had that issue, not sure how I solved though, dirty hack

Or add the symlink `pcmanfm` to the binary `pcmanfm-qt` until the fix comes into Arch (strange! Arch should get it sooner than other distros).

Anyhow, this isn't an LXQt bug. Closing.
