### ISSUE TITLE
lxqt monitor settings are not opening either from GUI or from lxqt-config-monitor

### ISSUE THREAD

**Issue by adithya604** [lxde/lxqt#1457]
Hi all,

I am new user of lxqt. I have faced couple of issues. I am not sure whether they are resolved it or not. If they are resolved please direct me to the solution page.

1. I'm not able to configure monitor settings either from GUI or lxqt-config-monitor. Uploaded is the screenshot when I run from terminal.
![selection_086](https://user-images.githubusercontent.com/24271764/37218810-94db55cc-23e7-11e8-869e-65e7601349c0.jpg)
Actually, I want to setup 2 monitors and expect the similar behaviour as traditional Ubuntu.
2. When I installed lxqt and purge and autoremove, it seems setting got changed and I can't see the launcher on desktop, title bars with minimize, maximize and close buttons for opened windows and some other unexpected behaviour after uninstalling lxqt. Can someone explain the issue and how to resolve it? 
When I uninstall lxqt, I expect the system to be in the same state and behave in the same manner before I install lxqt.

##### System Information
Ubuntu 16.04 64 bit OS

**Comment by tsujan** [comment]
Most probably, your problems are caused by Ubuntu (downstream). You didn't tell about the LXQt version you have but it should be very old with Ubuntu 16.04.

Moreover, LXQt isn't responsible for how packages are installed/uninstalled on your system. That's a package manager job.

**Comment by adithya604** [comment]
@tsujan 
1. Can u explain what is the error when I run lxqt-config-monitor? The error shared in screenshot is when lxqt is live and working in Ubuntu 16.04. 
2.
I installed using the commands 
  sudo apt update
  sudo apt install lxqt lxqt-session* openbox

and uninstalled lxqt using the commands
  sudo apt remove --purge lxqt lxqt-session*
  sudo apt update && sudo apt autoremove && sudo apt autoclean

When installing lxqt, it changes configuration files, isn't it is expected to restore the configuration settings when I uninstall lxqt? How can it be a package manager job?

**Comment by tsujan** [comment]
> When installing lxqt, it changes configuration files, isn't it is expected ...

You should ask Ubuntu LXQt maintainers. We don't make installable packages for any distro here.

As for your problem with lxqt-config-monitor, we don't support ancient versions. 2016?!
