### ISSUE TITLE
Panel transparency no longer works, after installing lxqt-desktop-git (g8dcc49aa)

### ISSUE THREAD

**Issue by jeremywh7** [lxde/lxqt#1461]
##### Expected Behavior
Panel transparency with compton-git shows as adjusted with the slider in the panel settings.

##### Current Behavior
This worked with the Arch 0.12.0-1 lxqt, but not with the latest git.  lxqt-panel shows black, and I tried adjusting the transparency slider.  I even tried installing compton-conf-git, to no avail.

##### Possible Solution
I tried Stopping/Starting compton from lxqt-session settings, and had no effect, like compton couldn't start at all.  Normally I'd expect to see some 'flickering' when doing this.

##### Steps to Reproduce (for bugs)
1. Be running lxqt 0.12 with compon enabled
2. Adjust panel transparency to verify success
3. Update to git builds
4. Note lack of panel transparency

##### Context
I am unhappy to have no panel transparency.  My cat seems upset too.

##### System Information
* Distribution & Version: Archlinux, latest updates
* Kernel: 4.15.9-1-ARCH SMP PREEMPT Sun Mar 11 2018 x86_64 GNU/Linux
* Qt Version: qt5-base 5.10.1-5
* liblxqt Version: liblxqt-git 0.12.0.6.g0c93a6d-1
* Package version: lxqt-panel-git 0.12.0.24.g8dcc49aa-1
* Compton version: compton-git 0.1_beta2.87.g316eac0-1

**Comment by agaida** [comment]
seems to be a compton problem - not our business - i would try https://github.com/chjj/compton/issues - but i don't think it will help a lot ... Bad luck :(

**Comment by jeremywh7** [comment]
Why would only updating from the latest release to the latest git break it?

**Comment by tsujan** [comment]
> I am unhappy to have no panel transparency.

I would be unhappy without window+menu translucency too ;) Use `glxgears` to check compositing. LXQt works with all window managers+compositors that are DE-independent. Moreover, LXQt cannot affect compositing.

**Comment by jeremywh7** [comment]
>Moreover, LXQt cannot affect compositing.

But lxqt-session has a facility to auto-start (and/or manually start and stop) Compton (which is why I'm using it), so if lxqt-session is failing to auto-start, stop, or start Compton, then that directly affects it.  As I noted before, using lxqt-session auto-start settings to stop and start Compton had no effect, but I will investigate in more detail tonight.

**Comment by tsujan** [comment]
> But lxqt-session has a facility to auto-start

Yes, that's correct, but whether compton *can* be started or not is out of LXQt's control. In your report you said, "like compton couldn't start at all".

**Comment by agaida** [comment]
one can start compton by hand and see whats happend - but i guess compton is as dead as the compton-development

**Comment by tsujan** [comment]
@agaida It works on the computer I use for testing such things.

**Comment by agaida** [comment]
latest git in arch for compton?

**Comment by tsujan** [comment]
compton 0.1_beta2.5-10 but I don't use it on this laptop, which is equipped with compiz-reloaded.
