### ISSUE TITLE
Decouple wallpapers and themes and improve wallpaper handling

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#156]
Three point plan:

1) Do not ship wallpapers within themes themselves; ship them in a separate "wallpapers" directory. Either in `/usr/share/wallpapers/lxqt` or `/usr/share/lxqt/wallpapers`.
2) Do not update the wallpaper when changing theme if it's not the one provided by the theme by default
3) Offer an option to reset the wallpaper to the current theme's if it has been changed.

We should also provide an option from pcmanfm-qt's desktop preferences to launch lxqt-config-appearance if running in LXQt.

**Comment by jleclanche** [comment]
It's too late for this to make it into 0.9. Very bummed out about this. Dropping to 1.0.

**Comment by intialonso** [comment]
Anybody working on this?

**Comment by intialonso** [comment]
Bump.

We need to detach wallpapers from themes.

**Comment by agaida** [comment]
second this

**Comment by intialonso** [comment]
We can delete the wallpapers (image and config file) for now. If there is no wallpaper when changing the theme, the previous wallpaper stays unmodified. Is a little rough solution, but it works.

I think that we need to preserve just one wallpaper for our default theme (to avoid a black desktop in clean installs).

Tell me what you think.

**Comment by palinek** [comment]
> I think that we need to preserve just one wallpaper for our default theme (to avoid a black desktop in clean installs).

IMO wallpapers should not be coupled with themes at all. We should provide only one *default* wallpaper picture which will be set in clean install. No theme should provide any wallpaper. We should not provide any extra set of wallpapers.
It's the user's choice and responsibility to find (download) and use wallpaper of his/her wish (theme change should not change wallpaper in any way).

That's my opinion on this.

**Comment by intialonso** [comment]
@palinek I agree.

So Ithe road is to design a default wallpaper, put it in **lxqt-common/graphics/** and set it in  **lxqt-common/config/pcmanfm-qt/lxqt/settings.conf.in**

Once this is done we can delete all the wallpapers and the wallpaper.cfg files from the themes.

 Is that correct?

**Comment by palinek** [comment]
> So the road is to design a default wallpaper, put it in lxqt-common/graphics/ and set it in lxqt-common/config/pcmanfm-qt/lxqt/settings.conf.in
>
> Once this is done we can delete all the wallpapers and the wallpaper.cfg files from the themes.

Agreed.

**Comment by intialonso** [comment]
Some wallpapers I have working on for the default. Im thinking in something minimal, lightweight, something with the hummingbird.

![lxqt-wall01](https://cloud.githubusercontent.com/assets/7544231/13370266/c0717fdc-dcd0-11e5-90ca-8700aeb9a698.png)
![lxqt-wall02](https://cloud.githubusercontent.com/assets/7544231/13370267/c37a7a12-dcd0-11e5-90c0-b8de6ea7c52b.png)
![lxqt-wall03](https://cloud.githubusercontent.com/assets/7544231/13370265/bff1637e-dcd0-11e5-8277-60aa94bbd8f7.png)
![lxqt-wall04](https://cloud.githubusercontent.com/assets/7544231/13370268/c3809a32-dcd0-11e5-8336-81552faf1fc0.png)

**Comment by paulolieuthier** [comment]
@intialonso: awesome!

**Comment by jleclanche** [comment]
Loving it Inti. They would all make kickass defaults.

**Comment by intialonso** [comment]
But we need just one :(

**Comment by jleclanche** [comment]
We need just one, but we don't have to have just one. We can have multiple defaults for people to choose from.

Like I said in a comment above, too, one matching (default) wallpaper per theme would be a good idea. It would give each theme a lot more identity.

**Comment by palinek** [comment]
> Like I said in a comment above, too, one matching (default) wallpaper per theme would be a good idea. It would give each theme a lot more identity.

But then changing theme will also change the wallpaper...and we want to avoid that.

**Comment by intialonso** [comment]
So, I suggest to put, lets say 3 defaults, all of them in  lxqt-common/graphics/ and when the user open the dialog to change the wallpaper it will open that same directory, so the option to choose one of those defaults will be there.

The wallpapers will not be "tie" to any theme. Besides that, almost everybody changes the default within minutes :D

**Comment by pmattern** [comment]
On a side note I for one found it a pity if the wallpapers currently provided got lost, in particular the one of Ambiance.
So couldn't we just keep the files themselves but use them the new way discussed in this issue? Otherwise I think it would be nice if they were still available as an option somehow.

**Comment by intialonso** [comment]
@pmattern I like that idea. So thats 5 wallpapers, plus maybe one more.

For this to be perfect I hope #391 get fixed.

**Comment by jleclanche** [comment]
> But then changing theme will also change the wallpaper...and we want to avoid that.

No, I suggested how to handle this in the original post:

>  2) Do not update the wallpaper when changing theme **if it's not the one provided by the theme by default**

**Comment by intialonso** [comment]
What @jleclanche proposes require some changes in the code, right?

We came up with a simplest approach some comments before, but I thought that to achieve a codeless solution (as every designer :D). So I will leave to you guys to decide what is the better and cleanest approach to this. 

Im more inclined to @palinek solution, and remove completly the theme-wallpaper relation, provide a sane default and let the users set what they want (as everyones do).

**Comment by jleclanche** [comment]
Personally I'm strongly in favour of adding a default wallpaper per theme. Like I said, it gives themes an identity and  the user more choice on basic customization.

**Comment by pmattern** [comment]
> Personally I'm strongly in favour of adding a default wallpaper per theme. Like I said, it gives themes an identity and the user more choice on basic customization.

Agree. The UX is probably better when wallpapers matching the themes are used by default on a new user profile and the decoupling takes place only once a different wallpaper has been chosen manually.

**Comment by intialonso** [comment]
I dont fully understand how will this work. Lets say someone install LXQT, the default is Frost with the matching wallpaper, this person changes the wallpaper to his liking. Some days later he decides to change the theme to Ambiance. Does the wallpaper change then to the Ambiance default?

If not, then shipping defaults for every theme will be pointless, because with the first user change they will never be visible again. If yes, then we will have the same situation that now.

**Comment by jleclanche** [comment]
> If not, then shipping defaults for every theme will be pointless, because with the first user change they will never be visible again.

That's right, but I don't see how you reach the conclusion that it's pointless. A lot of users do not change their wallpaper.

**Comment by pmattern** [comment]
Couldn't we eventually introduce a switch to toggle whether or not the themes' wallpapers are used?
Something like this:
* Each theme still comes with a genuine corresponding wallpapers. The way to implement this could very well be changed, e. g. all wallpapers could be summarized in a directory like `/usr/share/wallpapers` and no longer in the themes' directories.
* As long as the switch is unchecked LXQt keeps using the theme's wallpapers and switches wallpaper each time another theme gets selected. When the switch is active users can set arbitrary wallpapers and the active wallpapers remains the same when a theme gets changed.

**Comment by intialonso** [comment]
I feel like we are overcomplicating this. No other desktop environment have wallpapers attached to themes, there is no need for that, and we have been discussing this for almost two years.

Why a switch for something as trivial as setting a wallpaper? If we ship all the wallpapers together, they will be there whenever someone wants to use them. We will be the DE where I need to click an option to be able to put my cat as a background.

If we want an "identity" for every theme, then the problem goes beyond the wallpaper, we will need to control the WM, widgets theme, icon theme and even the typography. What do we gain having a "matching" wallpaper for a theme if everything else looks alien? The wallpaper-theme is not a irreversible marriage, every theme could (and most) work with any wallpaper.

But, as I said before, Im talking from a designer perspective, I dont know what all of this implies from the code perspective. Is it easy to be done?

I will support whatever you guys decide. But we need to solve this as soon as possible.

**Comment by Vladimir-csp** [comment]
I would like to support this issue. Coupling wallpapers and widget themes is an overcomplication. Not to mention that DE is modular and something other than pcmanfm can govern root window. Without hypothetical XDG wallpaper spec, throwing additional ties from wallpaper to anything else would be premature.

**Comment by jleclanche** [comment]
Alright, let's clarify a couple of things...

Currently, we have themes *coupled* with the wallpaper in that if you change the theme, your wallpaper changes with it. What we want here is for the wallpaper *not* to change if it was *already* set to something different by the user.

We do not need a switch/toggle/whatever for this, it's implicit behaviour that covers the majority of use cases. The wallpaper can still be changed manually afterwards, which covers the remaining use cases.

Regarding XDG specs: I'd love for there to be one but it's unlikely to ever happen. After following the xdg list for years I can honestly say it is a failed project and while it has given the Linux ecosystem some useful standards, everything it stands for is essentially dead in the water. Emails/proposals go unanswered, nobody chimes in, the only active bits are developed within the context of a single desktop environment (usually gnome). But there has been no effort on cross-desktop polishing which is really sad (eg. wallpapers, extended opens, generic configuration, etc).

**Comment by agaida** [comment]
and what hinder us to put the wallpapers to a different repo and install them to /usr/share/wallpapers/$theme - they would be in a place where everyone would search. And if we provide some kind of makefile we could build and provide them in different resolutions if we want to. Right now i'm doing this for siduction that way - i provide only the links to the real wallpapers in my themes.

**Comment by Vladimir-csp** [comment]
By "supporting this issue" I've meant what it says in the title: "Decouple wallpapers and themes".

Regarding XDG, that is why I said "hypothetical". And even if XDG is out of business, modularity should be preserved by keeping DE from getting into way in areas that can be cross-desktop.

**Comment by intialonso** [comment]
A couple of polls I found about wallpapers. This are a little old (I wasnt able to find something more recent) and have little samples, but I think they can light our little debate:

![poll01](https://cloud.githubusercontent.com/assets/7544231/13466263/2de7a3e0-e067-11e5-8295-1854d5e3dc94.jpg)

This one is from kde-look.org, 2005. In this one 9% of the 662 votes keep the default wallpaper.

![poll02](https://cloud.githubusercontent.com/assets/7544231/13466264/2de84bec-e067-11e5-91b4-bded53305c8b.jpg)

This is from deviantart in 2010, the 3% of 118 votes doesnt change the default wallpaper.

**Comment by jubalh** [comment]
@intialonso awesome wallpapers indeed!

**Comment by jleclanche** [comment]
> the 3% of 118 votes doesnt change the default wallpaper.

Yes, from a deviantart community :) I'd wager it's a lot higher outside of that. By no means a majority but nothing negligible.

My main concern is also with eg. reviewers who will be testing various themes, all of which will appear in "promo" type media. We want good first impressions and that's part of that.

**Comment by intialonso** [comment]
> My main concern is also with eg. reviewers who will be testing various themes, all of which will appear in "promo" type media. We want good first impressions and that's part of that.

Uhmmm I hadn´t though of that, makes a lot of sense.

**Comment by pmattern** [comment]
Didn't follow this discussion thoroughly and hence this may be the wrong place to post, but:

As of VCS checkouts 2016-04-01 the first session on a new user profile starts with just a black background
![lxqt_theming_initial-black-background](https://cloud.githubusercontent.com/assets/9860801/14214062/436d143e-f83b-11e5-8219-5da2abb638ae.png)
which certainly isn't intended, is it?

On a subjective side not I think the bird of `lxqt-origami-light.png` is somehow mismatching the one in plugin-mainmenu in the panel as both represent the same kind of object but are drawn in a totally different style.

**Comment by intialonso** [comment]
> On a subjective side not I think the bird of lxqt-origami-light.png is somehow mismatching the one in plugin-mainmenu in the panel as both represent the same kind of object but are drawn in a totally different style.

Yeah, thats exactly the intention, not to use the logo as wallpaper, a common rule to avoid overexposing the brand.

**Comment by jleclanche** [comment]
I like it.

**Comment by stefonarch** [comment]
I see this is still open, it's quite annoying changing themes and they change the wallpaper too.
One thing we could think about IMHO is adding by default this custom action in ~/.local/share/file-manager/actions/wallpaper.desktop

[Desktop Entry]
Type=Action
Name=Set as wallpaper
Icon=user-desktop
Profiles=profile-zero;

[X-Action-Profile profile-zero]
MimeTypes=image/*;
Exec=pcmanfm-qt -w %f
Name=Default profile
[Desktop Entry]
Type=Action
Name[it]=Usa come sfondo
Name[de]=...
Icon=user-desktop
Profiles=profile-zero;

[X-Action-Profile profile-zero]
MimeTypes=image/*;
Exec=pcmanfm-qt -w %f
Name=Default profile

**Comment by palinek** [comment]
Guys, have a look on the lxde/lxqt-config#99 (it needs the lxde/pcmafm-qt#396)

**Comment by stefonarch** [comment]
One little  issue:  the checkbox is never checked which is not bad, a user could have selected it before, it acts  actually like a button, maybe a real button would be better? Like "Use wallpaper from theme"?

Everything else seems working, it's not active before the user selects a custum wallpaper in pcmanfm-qt and changing themes do not affect wallpaper. Thanks!

**Comment by Serkan-devel** [comment]
@intialonso where can I get the second wallpaper of your post?

**Comment by Serkan-devel** [comment]
Oh and is there an `lxqt-origami-dark.png`?

**Comment by agaida** [comment]
@Serkan-devel - if there is such thing, you would want a svg.

**Comment by Serkan-devel** [comment]
Yes pls
