### ISSUE TITLE
Show applications in panel on a per desktop basis?

### ISSUE THREAD

**Issue by DaveDay** [lxde/lxqt#169]
Generally very pleased with the direction of lxqt.  One thing I definitely miss from fbpanel is the ability to show apps in the panel of only the apps running in the current desktop.

Have I overlooked how to configure this?  Or is it just not available?

I use 8 desktops and can have multiple apps per desktop, so showing them globally is very
cluttered and confusing.

Thanks,
Dave

**Comment by jleclanche** [comment]
Looks like we are dropping this from 0.9.

**Comment by palinek** [comment]
fixed in https://github.com/lxde/lxqt-panel/compare/f06970a76b32...9b46323700d2
