### ISSUE TITLE
lxqt-admin-users adding users makes only able to log into x as guest session in lightdm

### ISSUE THREAD

**Issue by ianorlin** [lxde/lxqt#196]
To reproduce launch lxqt-admin-users on an ubuntu base then click on the button to add another user named something like sockpuppet. Then have the main group be the default name of the new user an leave userid to be 1001. Then click ok.
![lxqtnologin](https://cloud.githubusercontent.com/assets/7546640/3334525/0cfefaca-f801-11e3-8c9b-0dbc00e07d05.png)
 Then if I logout I can see the new users but if I select restart I get a login screen with only a guest login. If I switch to a tty I can still login and both the original graphical users and new user have data in /home. 

I also notice after doing this that etc/lightdm/users.conf file is made into an empty file.

**Comment by palinek** [comment]
Does this have something to do with LxQt? (not sure, but adding/changing a user only afects /etc/passwd|group|shadow and has nothing to do with DM)
@jleclanche, @paulolieuthier should this be closed/rejected?

**Comment by paulolieuthier** [comment]
@palinek if I understood it correctly, lxqt-admin-users is not creating logable users.

**Comment by paulolieuthier** [comment]
@ianorlin does it happen with other display manager, like GDM or SDDM?

**Comment by ianorlin** [comment]
With lxdm another display manager I get the users listed but cannot login as them into a graphical session. With sddm with the current development version of ubuntu brought up a white screen and I could not log in but that might be a problem with the version in ubuntu repos with sddm. I am going to make a virtual machine of siduction and then try to install it and see if it this is specific to ubuntu.

**Comment by ianorlin** [comment]
On a working lightdm on siduction lxqt-admin users seems to work.

**Comment by palinek** [comment]
So can we close this?
