### ISSUE TITLE
Lxqt-panel - volume does not respect 100% limit and selecting changes the volume

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxde/lxqt#252]
The volume setting for lxqt-panel in combination with PulseAudio seems to be fixed, see #246 

However, the volume regulator does not respect the "Allow volume above 100%" setting.

Also, the volume for a certain number (ie. volume 30) seems to change when (de)selecting this option, which I guess is related.

![2014-08-05-180637_320x434_scrot](https://cloud.githubusercontent.com/assets/6639859/3814339/826601d6-1cba-11e4-9050-791333b3bf9a.png)

**Comment by jleclanche** [comment]
With nobody working on this (and this not being critical), moving to 1.0 mstone.

**Comment by paulolieuthier** [comment]
@ArthurBorsboom is this still an issues for you?

**Comment by ArthurBorsboom** [comment]
Hi Paul,

It is only an issue for me when it can damage the hardware. For example when the volume is (by accident set to 1100%) and my audiocard or laptop speakers get damaged, it is an issue. If it cannot, I don't mind.

**Comment by paulolieuthier** [comment]
@ArthurBorsboom I agree. What I'm asking is whether the bug still happens.

**Comment by ArthurBorsboom** [comment]
Yes, it still happens.

I can turn up the volume (or at least the volume indicator), above 1000, by just holding the volume up button, even with the allow volume above 100% setting turned off, see screenshot first post.

**Comment by pmattern** [comment]
Confirmed.
Ruler in panel plugin itself is limited to 0-100%, but hitting multimedia keys allows for values >>100% according to the desktop notification. Both independent of whether 'Allow volume beyond 100%' is checked or not.
lxqt-panel 5e24a99.

**Comment by ArthurBorsboom** [comment]
Darn your fast! :)
