### ISSUE TITLE
pcmanfm-qt: general protection ip in dmesg

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxde/lxqt#256]
Although not sure what the impact is, in general it is not good to have errors in the dmesg.

traps: pcmanfm-qt[663] general protection ip:7fa0086a1fd9 sp:7fff37233a40 error:0 in libQt5Widgets.so.5.3.1[7fa00852d000+61f000]

If it is nothing, please close the issue. It is just an FYI.

**Comment by PCMan** [comment]
I don't really know what's the exact cause of this. :(

**Comment by ArthurBorsboom** [comment]
No problem. Can I be of any assistance for debugging and/or providing information?

**Comment by ArthurBorsboom** [comment]
Haven't seen this issue anymore since v0.9.
