### ISSUE TITLE
Add icons to panel plugins

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#257]
From razor-qt/razor-qt#358

**Comment by luis-pereira** [comment]
@jleclanche This can also be done in the plugin desktop file.
I had to kill some time and played a bit with it. Here is the result. Comments welcome. 
<a href="http://imgur.com/Ja2vKq5"><img src="http://i.imgur.com/Ja2vKq5.png" title="source: imgur.com" /></a>

**Comment by agaida** [comment]
cool, i'd like it

**Comment by intialonso** [comment]
Nice!

**Comment by luis-pereira** [comment]
@intialonso @jleclanche @paulolieuthier @PCMan @agaida 
Running on top of lxde/liblxqt#35
Could not find an suitable icon to:
* Sensors (BTW it's working for you guys ?)
* System tray

The desktop switcher and show desktop are using the same icon.
Created an start-here-lxqt.svg icon (from the frost mainmenu.svg) for the main menu.

That's the result.
![screen-2015-01-29-14-59-42](https://cloud.githubusercontent.com/assets/62877/5968095/b287a2e0-a7c8-11e4-9234-e8fcc835b70b.jpg)
![screen-2015-01-29-15-00-20](https://cloud.githubusercontent.com/assets/62877/5968094/b283cc92-a7c8-11e4-8de6-79a5a1f4af78.png)

**Comment by paulolieuthier** [comment]
Man, really nice work there! Sensors is working here, apparently. About the missing icons, I've got no idea as well.

**Comment by jleclanche** [comment]
This looks great. @luis-pereira if it's not invasive, use your own judgement to figure out if it's suitable for 0.9. There's still five days of testing left.

**Comment by luis-pereira** [comment]
@jleclanche I know. I did it because today might my last day before the release.
