### ISSUE TITLE
cannot set theme for root pcmanfm-qt

### ISSUE THREAD

**Issue by ghost** [lxde/lxqt#261]
running lxqt-config-appearance as root
setting style to gtk+ or windows has no effect
fusion is used each time

**Comment by PCMan** [comment]
I guess I have to check the config file of lxqt-qtplugin. It might loads the wrong one?

**Comment by PCMan** [comment]
This is fixed by https://github.com/lxde/lxqt-qtplugin/commit/f1a07120b6d74068c5d3a14babbd5d05f44d2750
