### ISSUE TITLE
lxqt-config-input has a few shortcomings

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#267]
- Mouse: Left handed is respected systemwide, Wheel scroll lines not - to set Qt4 Wheel scroll lines i must install the lxqt-config-input for Qt4, not so nice because the Qt4 and Qt5 packages conflict.

This behaviour is easy to test with quassel (Qt4) or qterminal (Qt4)

**Comment by PCMan** [comment]
@jleclanche @agaida support for Qt4 was completely removed previously during the migration to Qt5.
So I'm closing this issue because it is out of date.
However, I personally believe that we should restore Qt4 support later since many users are still using Qt4 programs.
