### ISSUE TITLE
Lxqt powermanagemnt doesn't read /sys directories

### ISSUE THREAD

**Issue by 5paceToast** [lxde/lxqt#282]
Upon logging into lxqt, I get a notification that Lxqt-powermanagement cannot find a battery.
However, `/sys/class/power_supply/BAT1/` exists and is fully functional (I use it to check my battery status for now).
I'm guessing that powermanagement still uses old conventions that are deprecated in recent kernels (3.13+ if I'm not mistaken).

**Comment by xsacha** [comment]
I just came across this issue and discovered upower is a dependency for lxqt-powermanagement to work.
After installing upower the issue went away.
Looks like a Lubuntu issue.

Thanks!

**Comment by agaida** [comment]
Nope - it wasn't a lubuntu bug - this was changed with https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828697 and is in ubuntu since the yak

**Comment by xsacha** [comment]
I am using Lubuntu-next Arty daily build from June 3rd. Should this have been fixed by now?

**Comment by agaida** [comment]
it is "fixed" since yakkety yak - if one use the standard ubuntu apt configuration and install recommends.

**Comment by xsacha** [comment]
Ok, since lxqt came pre-installed in Lubuntu-next, I guess it is a bug in their preinstalled set up.
Not a lxqt bug though so this can be closed.
