### ISSUE TITLE
Add Service Hooks for OBS

### ISSUE THREAD

**Issue by sfalken** [lxde/lxqt#286]
Hey guys, this isn't really an issue, so much as a request, and requires no actual coding on the part of the developers.   If I get you the tokens, can I get you to add them to the service hooks here on github, so when things are updated it kicks off a build on OBS for the openSUSE unstable packages?

Per http://openbuildservice.org/2013/11/22/Source-Update-Via_Token/

**Comment by jleclanche** [comment]
I'm closing this, it's not really a scalable way for us to do this.
