### ISSUE TITLE
[lxqt-panel] bad ELF symbols in libpanelkbindicator.so

### ISSUE THREAD

**Issue by ghost** [lxde/lxqt#304]
ALT Linux build system complains:

```
x86_64: NEW bad_elf_symbols detected:
```

lxqt-panel-0.8.0-alt1.x86_64.rpm    /usr/lib64/lxqt-panel/libpanelkbindicator.so    U   _ZN28LxQtKbIndicatorConfiguration12selectColourERK7QString
lxqt-panel-0.8.0-alt1.x86_64.rpm    /usr/lib64/lxqt-panel/libpanelkbindicator.so    U   _ZN28LxQtKbIndicatorConfiguration16on_fontB_clickedEv
lxqt-panel-0.8.0-alt1.x86_64.rpm    /usr/lib64/lxqt-panel/libpanelkbindicator.so    U   _ZN28LxQtKbIndicatorConfiguration25on_maximumHS_valueChangedEi
lxqt-panel-0.8.0-alt1.x86_64.rpm    /usr/lib64/lxqt-panel/libpanelkbindicator.so    U   _ZN28LxQtKbIndicatorConfiguration30on_typeCOB_currentIndexChangedEi
lxqt-panel-0.8.0-alt1.x86_64.rpm    /usr/lib64/lxqt-panel/libpanelkbindicator.so    U   _ZN28LxQtKbIndicatorConfiguration32on_sourceCOB_currentIndexChangedEi

**Comment by agaida** [comment]
should be done now. outdated.
