### ISSUE TITLE
Move libfm-qt away from pcmanf-qt dir

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#31]
It's not pcmanfm-qt specific anymore. lximage-qt  is using it.
@PCMan Should be taken in account when defining repo layout.

**Comment by jleclanche** [comment]
libfm-qt should be part of the libfm repository somehow, rather than the pcmanfm-qt one. @LStranger thoughts welcome

**Comment by LStranger** [comment]
>libfm-qt should be part of the libfm repository somehow, rather than the pcmanfm-qt one. @LStranger thoughts welcome

I agree with you, if libfm-qt and pcmanfm-qt are splitted out then that should be
easier to support.

Well, it might be good to merge it with libfm and libfm-gtk although currently it's
not possible because libfm-qt uses CMake and Qt i18n while libfm uses autotools and
gettext i18n, those are too different and would be conflicting if used in a single
project tree.

**Comment by PCMan** [comment]
I plan to split them at some point when the APIs and ABIs become stable.
Currently it's still a work in progress and the API/ABI might be changed frequently.
So I put them in the same package just for ease of development.
Later I'll try to split them.

**Comment by jleclanche** [comment]
@PCMan I think we should do this for next release. Even though the API isn't stable, that's still OK in the 0.x branch.

**Comment by PCMan** [comment]
I'll consider that.
BTW, if we're going to do that, it's better to do re-license to LGPL at the same time.
The upstream libfm is LGPL now, so if all contributors agree, libfm-qt can be changed to LGPL, too.

**Comment by jleclanche** [comment]
@PCMan That's fine by me, bring it up on the ML and we can confirm it there.

**Comment by luis-pereira** [comment]
Closed by:
* https://github.com/lxde/libfm-qt/commit/330464165d1bc9d73173f4d7de0402d3c0558d7f 
* https://github.com/lxde/pcmanfm-qt/commit/7cff9ef1c74dbfadf23948ed6a441863500bf241
