### ISSUE TITLE
Merge World Clock and Date/Time plugins

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#312]
Good cleanup now that we no longer support qt < 5.3

**Comment by kuzmas** [comment]
@pepa65 I'm not sure what you mean. Worldclock has the list of all timezones in configuration. It can show time of all selected timezones, it can show the calendar and the calendar (current day and the first day of the week) depends on the shown timezone.

**Comment by kuzmas** [comment]
UX is in another issue: https://github.com/lxde/lxqt/issues/416

**Comment by pepa65** [comment]
I was just checking again what I meant. I seem to remember that the timezones + times were all in the balloon-popup. I'm just now running lxqt-panel 0.8.0 and I think the configuration is great, but I can't see any way to show the timezones; hovering does nothing, left-click just shows the calendar.

**Comment by kuzmas** [comment]
@pepa65 ah, I see. It's middle click.

**Comment by pepa65** [comment]
OK, middle click does show the configured times, but there is no label, and no mention of which timezone, just a list of times. (But I hope -assume- this is fixed now.)

**Comment by pepa65** [comment]
(Sorry, that's just in the default Short form. It is very configurable! The only thing that some other world clock widgets allow me to do is define my own label for each zone...)

**Comment by kuzmas** [comment]
In 0.8.0 it shows time for all selected timezones exactly as it shows in panel it self.
Now I'm changing it so the timezone is appended.

**Comment by kuzmas** [comment]
>allow me to do is define my own label for each zone

this sounds like something I'd like for myslef as well ;-)

**Comment by kuzmas** [comment]
>me: Now I'm changing it so the timezone is appended anyway.

Time zone IANA id is appended to each label in the popup window unless time zone is already shown in some way.

**Comment by pmattern** [comment]
This issue was closed without getting resolved besides everyone involved agreed that the problem that's addressed is valid, stating #416 as successor is wrong as that one was only about improving plugin-worldclock.
Hence reopening.

Right now both plugins are basically providing the same features, in particular the actual display in panel is the same as well as the calendar that comes up by (left) clicking. plugin-worldclock offers the features reflected in its name in addition but lacks the tooltip displaying date and time on hovering.

What I'd suggest is adding the tooltip feature to plugin-worldclock and then rename it to plugin-clock. The latter seems reasonable to me as I figure terms like "clock" or "Date & Time" are rather what users unaware of the naming will look for.

**Comment by jleclanche** [comment]
@pmattern Can you take the issue?

**Comment by pmattern** [comment]
@jleclanche 
Given my pretty limited programming skills I cannot handle this in a reasonable amount of time right now. So no, sorry.

**Comment by jleclanche** [comment]
@palinek @paulolieuthier @luis-pereira I need one of you guys to take it if it's to land in 0.10.

**Comment by palinek** [comment]
IMO it's too late to merge it until 0.10. I am not in mood to do such merging. I am not a fan of the worldclock plugin at all (altough I don't see any evident reason for such antipathy :smile:).

**Comment by jleclanche** [comment]
Moving to 0.11. I think we'll need to have a discussion about this, I was hoping they were closer to each other.

**Comment by pmattern** [comment]
> [...] not in mood to do such merging [...] not a fan of the worldclock plugin at all

Not quite following here, tbh.
If we handled the plugins as stated in my second to last comment (of course a suggestion only) there would just be one plugin "Clock" or "Date & Time" or whatever that happens to provide some world-clock stuff in additon. But neither would there be any need to make use of the latter nor would the plugin be called `plugin-<foo...bar...world-clock somehow included here>`.
And what would be so bad about this? Or am I missing something?

**Comment by jleclanche** [comment]
@pmattern in the end it's up to whether people are actually willing to do it, it's not enough to ideally want it. anyway we have a release in a week, so let's focus.

**Comment by pmattern** [comment]
If this should get implemented one day I think it would be pretty good if the "new" plugin could feature the tooltip displaying the complete date upon hovering
![lxqt-panel_plugin-clock-popup](https://cloud.githubusercontent.com/assets/9860801/13056031/07c9c39c-d413-11e5-97bc-4fbd51c3800b.png)
which is provided by plugin-clock but missing in plugin-worldclock right now.

**Comment by pepa65** [comment]
Worldclock in 0.10 has all functionality I could wish for, and is very configurable. Indeed, the only welcome addition would be a configurable popup. Then I would only show the time, but hover to see the date. And the world clock functionality is very important to me. At this point, LXQt is fully usable! (except the small matter of actually remembering the arandr configuration for a session...)

**Comment by tsimonq2** [comment]
I'm going to attempt to get this done. I'll work on it more in the next few days.

**Comment by tsimonq2** [comment]
Bump on this, this is now a WIP and [available on my repo fork](https://github.com/tsimonq2/lxqt-panel/tree/new-clock-plugin).

I expect to have this done by the middle of June, late June at the latest.

**Comment by tsimonq2** [comment]
Actually, I made a lot of progress tonight, and [I just submitted a PR](https://github.com/lxde/lxqt-panel/pull/408).

I look forward to feedback on it. :)

**Comment by palinek** [comment]
Closing this as the plugin-clock was deprecated in lxde/lxqt-panel#426 and the follow-up is stated in #1356
