### ISSUE TITLE
lxqt-panel startup blocked by registration of volume shortcuts

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#314]
Critical. I don't know why the shortcuts are not registered, but they should not block the startup.

**Comment by palinek** [comment]
Isn't this already solved?
1. shortcuts are registered asynchronously
2. all registering was moved away from plugin/widget's constructors (to methods triggered right after event loop start)

**Comment by paulolieuthier** [comment]
I was having the issue even after the fix. Then I removed the volume plugin from my panel and started using a dedicated pulseaudio tray applet. One day I went back to the volume plugin to debug it, and the problem was gone. I guess a cleanup is needed.

**Comment by palinek** [comment]
> I guess a cleanup is needed.

Cleanup of what?

**Comment by paulolieuthier** [comment]
When I readded the plugin, a new shortcut was registered, you see? I don't know much of lxqt-globalkeysd's source code, though. I'm just guessing. Maybe it was a problem with the first registered shortcut.

**Comment by palinek** [comment]
> When I readded the plugin, a new shortcut was registered, you see? 

Isn't that a mess in plugin naming?
If you used the predefined `/etc/xdg/lxqt/panel.conf` (or manualy edited the conf) then the plugin name == plugin id (e.g. volume.desktop -> volume, tray.desktop -> tray...)... then the component identifier for the shortcut is e.g. `/panel/volume/up`.

But if you add a plugin manualy then the name is <id><n> (e.g. volume.desktop -> volume2, tray.desktop -> tray2; note: the <n> 2 or more -> lowest not used) ... then the component identifier for the shortut is e.g. `/panel/volume2/up`.

The shortcut for components are stored in lxqt-globalkeys' configuration permanently to allow the end user to change it -> If you change the shortcut manualy in `lxqt-config-globalkeyshortcuts` then the component will use this assigned shortcut (also after next spawn).

**Comment by paulolieuthier** [comment]
I moved from `volume` to `volume2`. But now, even back to `volume`, I can't reproduce the issue anymore. @jleclanche if you still reproduce it, can you try on a fresh setup?

**Comment by jleclanche** [comment]
@paulolieuthier no, it happened under very specific circumstances. Maybe there is a way to force a sleep(5) when registering shortcuts, which could showcase the issue.

**Comment by paulolieuthier** [comment]
@ypnos can you reproduce the bug on a fresh setup?

**Comment by ypnos** [comment]
No I cannot reproduce it anymore.
