### ISSUE TITLE
Centralize all the repeated CMake modules

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#332]
We have repeated and sometimes slightly different cmake modules in almost all repos.
They should be centralized. Fixing a bug or adding a feature in lot's of places is an PITA.

Candidates:
QtTranslate (The new module to handle .ts stuff)
lxqt_translate_desktop()
create_pkgconfig_file.cmake()
create_portable_headers.cmake()
etc etc

**Comment by jleclanche** [comment]
Moving to 1.0 per @luis-pereira's comments on the ML

**Comment by jleclanche** [comment]
@luis-pereira this needs a new review for 0.10 now that we're moving to cmake 3.0

**Comment by jleclanche** [comment]
@luis-pereira ping, what's left to do here?

**Comment by luis-pereira** [comment]
Not really sure. I have to check.

**Comment by jleclanche** [comment]
@luis-pereira can you move this to 0.11 if there's anything left to do?

**Comment by luis-pereira** [comment]
@jleclanche There are minor stuff to do. Moving it.

**Comment by paulolieuthier** [comment]
@luis-pereira what is left to do here?

**Comment by luis-pereira** [comment]
@paulolieuthier not sure, yet.

**Comment by paulolieuthier** [comment]
Let's move it to 0.11 then.

**Comment by luis-pereira** [comment]
lxqt-build-tools 0.3.0 nailed it.
