### ISSUE TITLE
lxqt doesn't read the correct settings for multiple XDG_CONFIG_DIRS

### ISSUE THREAD

**Issue by gilir** [lxde/lxqt#349]
lxqt always read the settings from /etc/xdg/lxqt, even if others directories are set on XDG_CONFIG_DIRS

For example, on Lubuntu, we have : 
XDG_CONFIG_DIRS=/etc/xdg/lubuntu:/etc/xdg/xdg-QLubuntu:/etc/xdg
Custom settings on /etc/xdg/lubuntu/lxqt
lxqt default settings on /etc/xdg/lxqt

On a fresh start, the settings on /etc/xdg/lxqt are set, instead of /etc/xdg/lubuntu/lxqt

One weird note, pcmanfm-qt works, but we have : 
XDG_CONFIG_DIRS=/etc/xdg/lubuntu:/etc/xdg/xdg-QLubuntu:/etc/xdg
Custom settings on /etc/xdg/lubuntu/pcmanfm-qt
No default settings on /etc/xdg/pcmanfm-qt

Maybe it's the last directory (with a content) on XDG_CONFIG_DIRS which is set, instead of the first one ?

**Comment by gilir** [comment]
To add more information on this, according to : https://github.com/NixOS/nixpkgs/pull/7525/files, QSettings itself has the problem, and the patch "fix" it.

**Comment by palinek** [comment]
Have a look on the lxde/liblxqt#104 ...

**Comment by palinek** [comment]
The Qt patches bringing correct support for XDG_CONFIG_DIRS to QSettings were merged (qt/qtbase@ee35fbb, qt/qtbase@4758555). 

So I'd like to close this. Does anyone insist to leave this issue open?

**Comment by paulolieuthier** [comment]
Let's close it.
