### ISSUE TITLE
Taskbar doesn't show anything

### ISSUE THREAD

**Issue by ypnos** [lxde/lxqt#354]
Since lxqt 0.8, the taskbar just stays empty. Whatever I do, no tasks are shown.
It does, however, react to focus changes. Very indirectly, though. See #353 

Using Arch Linux, herbstluftwm, lxqt 0.8.

**Comment by jleclanche** [comment]
@ypnos Please report the issue to the hlwm project. It's very unlikely to be an issue on our side..

**Comment by ypnos** [comment]
Well, there was no change in hlwm version that caused this bug to appear but a change in lxqt version. HLWM maintainer told me to post the output of `xprop -root` for you. Could you point out that might be wrong in the info provided by the window manager on the root window? It shows a completely fine client list as I see it.

````
jordan@lme51:~$ xprop -root
CUT_BUFFER0(STRING) = "nice ~/code/wuerfl/build/bin/gerbil edge_detect --algorithm rcmg --similarity.measure MOD_SPEC_ANGLE --input.file /net/cv/multispectral//cave-508/egyptian_statue.txt  -O egyptian_statue --prefix rcmg_sa  2>&1 | tee egyptian_statue/edge_rcmg_sa_output.txt\n"
InterpRegistry(STRING) = "7800001 cssh"
AT_SPI_BUS(STRING) = "unix:abstract=/tmp/dbus-ukVq00HuAh,guid=15e1ec4da59b354a4ea25a6654b68dce"
_SCREENSAVER_STATUS(INTEGER) = 0, 1421413684, 23
_QT_CLIPBOARD_SENTINEL(WINDOW): window id # 0x3e00002, 0x5600413
_QT_SELECTION_SENTINEL(WINDOW): window id # 0x9200002, 0x960251d
WM_HINTS(WM_HINTS):
                bitmap id # to use for icon: 0x920000d
_NET_WM_ICON(CARDINAL) =        [[[[[ I omit this data here ]]]]
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x6e00005
PULSE_COOKIE(STRING) = "1b0d6a555bb903bc98e9498b39bc78bb0d391b39b2d4ad167e2a9d37622eeef77d1d5e0bbdb2532992591ed9fb49caf9702c57cebaaaaee36d59d69334b90dae78b36c6c56ac805007e3299e223ec8ec10c974403d873048063d5e35ad5ac7f907a9ab8bf2ca2d59909c0707c015fa19615f8752d2e992dc18fbc9d477ec0db5c1926b21f8b414191af34072f7d7229bf9f137cb2c1a91b63236600cdf7405de0c35c4711f5593d36011e6bc168525331cc1587fcf4847d8ad86a3c88b127f32fe1c53ab7f0d80a3f38970f1ed33f9ed900ab6bb9217c948c400f7d63843374e81af20799d8f5ba6e3f2742b95867d138bf29bb4acbaf1d05f95d60f237e023c"
PULSE_SERVER(STRING) = "{4e0a200904714f8188562484dbbb48c9}unix:/run/user/30491/pulse/native"
PULSE_SESSION_ID(STRING) = "c4"
PULSE_ID(STRING) = "30491@4e0a200904714f8188562484dbbb48c9/980"
_NET_CURRENT_DESKTOP(CARDINAL) = 0
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x7e00022, 0x8000022, 0x780002c, 0x8600022, 0x7a00022, 0x7400003, 0x6800005, 0x6c00003, 0x3000546, 0x3000541, 0x7c00005, 0x4a00005, 0x4e00005, 0x8c00003, 0x4600005, 0x9200012, 0x8e00005, 0x9600003, 0x5c00005, 0x3c00009, 0x560008d, 0x1800005, 0x3000048, 0x3000001, 0x3e00012, 0x6e00005
_NET_CLIENT_LIST(WINDOW): window id # 0x3000001, 0x3000048, 0x3e00012, 0x4600005, 0x4a00005, 0x4e00005, 0x3c00009, 0x560008d, 0x5c00005, 0x6800005, 0x6c00003, 0x7a00022, 0x8000022, 0x7e00022, 0x8600022, 0x780002c, 0x7400003, 0x7c00005, 0x3000541, 0x3000546, 0x8c00003, 0x8e00005, 0x9200012, 0x9600003, 0x1800005, 0x6e00005
_NET_DESKTOP_NAMES(UTF8_STRING) = "browse", "mail", "main_trois", "ide", "foo", "bar", "tex", "write_deux", "write_trois", "admin_un", "root", "admin_trois", "tests_un", "tests_deux", "tests_trois"
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 15
__HERBST_HOOK_WIN_ID(ATOM) = undefined atom # 0xa00007
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 4391888
_NET_WM_NAME(UTF8_STRING) = "herbstluftwm"
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0xa00001
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_NUMBER_OF_DESKTOPS, _NET_CURRENT_DESKTOP, _NET_DESKTOP_NAMES, _NET_WM_DESKTOP, _NET_DESKTOP_VIEWPORT, _NET_ACTIVE_WINDOW, _NET_WM_NAME, _NET_SUPPORTING_WM_CHECK, _NET_WM_WINDOW_TYPE, _NET_WM_STATE, _NET_WM_WINDOW_OPACITY, _NET_MOVERESIZE_WINDOW, _NET_WM_MOVERESIZE, _NET_FRAME_EXTENTS, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_DROPDOWN_MENU, _NET_WM_WINDOW_TYPE_POPUP_MENU, _NET_WM_WINDOW_TYPE_TOOLTIP, _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_COMBO, _NET_WM_WINDOW_TYPE_DND, _NET_WM_WINDOW_TYPE_NORMAL
RESOURCE_MANAGER(STRING) = "Xcursor.size:\t18\nXcursor.theme:\tNeutral++\nXcursor.theme_core:\ttrue\nXft.antialias:\t1\nXft.autohint:\t0\nXft.dpi:\t96\nXft.hinting:\t1\nXft.hintstyle:\thintfull\nXft.lcdfilter:\tlcddefault\nXft.rgba:\trgb\nxclock*Foreground:\t#e04613\nxclock*Hands:\t#e04613\nxclock*height:\t500\nxclock*hourcolor:\t#e04613\nxclock*minutecolor:\t#e04613\nxclock*render:\ttrue\nxclock*width:\t500\n"
_XKB_RULES_NAMES(STRING) = "evdev", "pc104", "de,us", "nodeadkeys,", ""
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 7

````

**Comment by jleclanche** [comment]
You say since lxqt 0.8, do you mean lxqt 0.8 stable? Shortly after the release of 0.8 in git we moved to kwindowsystem which could be the culprit. Did you test in latest master?

**Comment by ypnos** [comment]
So I went ahead and tried to test my own, very simple, KWindowSystem application. It doesn't work at all (even with OpenBox), the hell why. During that I went through the taskbar code in question and I couldn't think of any problem there. So I tend to believe it is a problem of KWindowSystem.

**Comment by jsm222** [comment]
I can confirm this behaviour on FreeBSD 10.2-RELEASE and build from latest git c4733655fa9a03ae77909a4c818f9511acabc93d. The task manager stays emtpy.

**Comment by paulolieuthier** [comment]
@jsm222 which window manager?

**Comment by ypnos** [comment]
I had fixed the problem with herbstluftwm. KWindowSystem seems to be very picky with everything to function properly. This might be fine, however it also just silently fails.

I might be able to help with the debugging after I did it for hlwm. I also don't think this is a problem of lxqt.

**Comment by paulolieuthier** [comment]
@ypnos how did you fix it? Yeah, KWindowSystem is tested under KWin and Openbox, but no more than that AFAIK.

**Comment by agaida** [comment]
xfwm4 works without problems too

**Comment by ypnos** [comment]
@paulolieuthier https://github.com/herbstluftwm/herbstluftwm/commit/a50457335091cd990d0146e5008ca3b3db1cc574

**Comment by paulolieuthier** [comment]
Awesome.

**Comment by jsm222** [comment]
I just rebuild on a clean install of FreeBSD 10.2-RELEASE #0 r286666. (in a VirtualBox). The problem persists e.g taskbar stays empty. Attached a screenshot (what artwork does it use btw. the images/icons are missing).  The WM is openbox.

![lxqt](https://cloud.githubusercontent.com/assets/4705090/10111896/8000bd18-63d7-11e5-8d54-fbd25af155b7.png)

**Comment by palinek** [comment]
@jsm222 What is the configuration of the taskbar plugin? And how many desktops do you have?
(there is a configuration option in taskbar plugin to show only windows from particular desktop)

**Comment by paulolieuthier** [comment]
I'm downloading FreeBSD right now.

**Comment by palinek** [comment]
@paulolieuthier oh boy... you're really going into it :)

**Comment by paulolieuthier** [comment]
I always wanted to try it but always postponed. Now I have a compelling reason. :smile:

**Comment by agaida** [comment]
@paulolieuthier - don't take freebsd - take debians kfreebsd - sid on bsd is cool and you could probably fix two annyoing bugs :D

**Comment by jsm222** [comment]
Only one desktop. Some tips for building on FreeBSD. (As i loosely remember).
on Freebsd there is no libudev.
no pty.h for lxqt-sudo. but forkpty is available see man forkpty http://www.freebsd.org/cgi/man.cgi?query=openpty&apropos=0&sektion=3&manpath=FreeBSD+10.2-RELEASE&arch=default&format=html
lxqt-panel menus  use gmake for that one.
I installed solid an kwindowsystem from kdeframework 5.14, from source. Remeber extra-cmake-modules from kde framework.
![settings](https://cloud.githubusercontent.com/assets/4705090/10113361/ded255ca-63e3-11e5-8ab8-5235aed4d357.png)

**Comment by paulolieuthier** [comment]
@jsm222 FreeBSD is awesome. Everything was good until I got to lxqt-session. It won't link to libxcb, even though I have it installed and CMake detects it.

```
Linking CXX executable file lxqt-session
/usr/bin/ld: cannot find -lxcb
```

**Comment by paulolieuthier** [comment]
@krytarowski can you help me?

**Comment by krytarowski** [comment]
@paulolieuthier xcb should be a part of FreeBSD base and accessible. If you like you can try to help you to build lxqt on FreeBSD with pkgsrc, but I never tried it before personally.

**Comment by palinek** [comment]
@paulolieuthier what is the command line for linking the executable (`make VERBOSE=1` to see it)?

**Comment by jsm222** [comment]
@paulolieuthier Actually I had to edit the link.txt files, I do not know cmake to well, so I had to add -L/usr/local/lib manually to the generated linking text files. It might be possibly to set the libprefix to  /usr/local pr /usr/local/lib in a smarter way... but I did it manually.

**Comment by paulolieuthier** [comment]
> @paulolieuthier xcb should be a part of FreeBSD base and accessible. If you like I can try to help you to build lxqt on FreeBSD with pkgsrc, but I never tried it before personally.

Are you sure? I'm a noob, but I think xcb is in the port tree.

> @paulolieuthier what is the command line for linking the executable (make VERBOSE=1 to see it)?

I'll post here.

> @paulolieuthier Actually I had to edit the link.txt files, I do not know cmake to well, so I had to add -L/usr/local/lib manually to the generated linking text files. It might be possibly to set the libprefix to /usr/local or /usr/local/lib in a smarter way... but I did it manually.

Worked.

**Comment by paulolieuthier** [comment]
@palinek there seems to be an issue with CMake integration with pkg-config in FreeBSD. This is the error output:

```
Linking CXX executable lxqt-session
cd /home/paulo/src/lxqt/lxqt-session/build/lxqt-session && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/lxqt-session.dir/link.txt --verbose=1
/usr/bin/CC -fno-exceptions -Wall -std=c++11 -O3 -DNDEBUG CMakeFiles/lxqt-session.dir/src/main.cpp.o CMakeFiles/lxqt-session/dir/src/lxqtmodman.cpp.o CMakeFiles/lxqt-session/dir/src/wmselectdialo.cpp.o CMakeFiles/lxqt-session/dir/src/windowmanager.cpp.o CMakeFiles/lxqt-session/dir/src/sessionapplication.cpp.o CMakeFiles/lxqt-session/dir/src/numlock.cpp.o CMakeFiles/lxqt-session/dir/src/LXQtAppTranslationLoader.cpp.o CMakeFiles/lxqt-session/dir/src/lxqt-session_automoc.cpp.o -o lxqt-session -lxcb /usr/local/lib/libSM.co /usr/local/lib/libICE.so /usr/local/lib/libX11.so /usr/local/lib/libXext.so /usr/local/lib/liblxqt.so.0.9.0 /usr/local/lib/libKF5WindowSystem.so.5.15.0 /usr/local/lib/libQt5X11Extras.so.5.4.1 /usr/local/lib/libQt5Xdg.so.1.2.0 /usr/local/lib/libQt5Widgets.so.5.4.1 /usr/local/lib/libQt5Gui.so.5.4.1 /usr/local/lib/libQt4DBus.so.5.4.1 /usr/local/lib/libQt5Xml.so.5.4.1 /usr/local/lib/libQt5Core.so.5.4.1 -Wl,-rpath,/usr/local/lib: -Wl,-rpath-link,/usr/local/lib
*** Error code 1
```

You can see every library is referenced with its absolute path, except libxcb, which is the one not found. That is weird, because pkg-config specifies it:

```
$ pkg-config --libs xcb
-L/usr/local/lib -lxcb
```

Editing the `link.txt` files and adding `-L/usr/local/lib` solved my problem.

@jsm222 you see no icons because there are no icons installed. Installing `x11-themes/kde4-icons-oxygen` will fix that, as LXQt defaults to the Oxygen icon theme. I confirm the taskbar is empty, and will be digging into that.

**Comment by jsm222** [comment]
Great. :-)

**Comment by palinek** [comment]
@paulolieuthier, @jsm222 Can you also try to run the `cmake` in debug mode e.g.: `cmake .. --trace --debug-output -Wdev` (of course in a clean build dir) and see if there is something like this:
```
/usr/share/cmake-3.3/Modules/FindPkgConfig.cmake(371):  _pkgconfig_invoke_dyn(${_pkg_check_modules_packages} XCB LDFLAGS  --libs )
   Called from: [1] /home/palco/work/oss/lxqt/lxqt-session/CMakeLists.txt
/usr/share/cmake-3.3/Modules/FindPkgConfig.cmake(97):  _pkgconfig_invoke(xcb XCB LDFLAGS  --libs )
   Called from: [1] /home/palco/work/oss/lxqt/lxqt-session/CMakeLists.txt
/usr/share/cmake-3.3/Modules/FindPkgConfig.cmake(68):  set(_pkgconfig_invoke_result )
   Called from: [1] /home/palco/work/oss/lxqt/lxqt-session/CMakeLists.txt
/usr/share/cmake-3.3/Modules/FindPkgConfig.cmake(70):  execute_process(COMMAND ${PKG_CONFIG_EXECUTABLE} --libs xcb OUTPUT_VARIABLE _pkgconfig_invoke_result RESULT_VARIABLE _pkgconfig_failed )
   Called from: [1] /home/palco/work/oss/lxqt/lxqt-session/CMakeLists.txt
/usr/share/cmake-3.3/Modules/FindPkgConfig.cmake(75):  if(_pkgconfig_failed )
   Called from: [1] /home/palco/work/oss/lxqt/lxqt-session/CMakeLists.txt
/usr/share/cmake-3.3/Modules/FindPkgConfig.cmake(78):  else()
   Called from: [1] /home/palco/work/oss/lxqt/lxqt-session/CMakeLists.txt
/usr/share/cmake-3.3/Modules/FindPkgConfig.cmake(79):  string(REGEX REPLACE [\r\n]   _pkgconfig_invoke_result ${_pkgconfig_invoke_result} )
   Called from: [1] /home/palco/work/oss/lxqt/lxqt-session/CMakeLists.txt
/usr/share/cmake-3.3/Modules/FindPkgConfig.cmake(80):  string(REGEX REPLACE  +$  _pkgconfig_invoke_result ${_pkgconfig_invoke_result} )
   Called from: [1] /home/palco/work/oss/lxqt/lxqt-session/CMakeLists.txt
/usr/share/cmake-3.3/Modules/FindPkgConfig.cmake(82):  if(NOT  STREQUAL  )
   Called from: [1] /home/palco/work/oss/lxqt/lxqt-session/CMakeLists.txt
/usr/share/cmake-3.3/Modules/FindPkgConfig.cmake(86):  separate_arguments(_pkgconfig_invoke_result )
   Called from: [1] /home/palco/work/oss/lxqt/lxqt-session/CMakeLists.txt
/usr/share/cmake-3.3/Modules/FindPkgConfig.cmake(89):  set(_pkgconfig_LDFLAGS ${_pkgconfig_invoke_result} )
   Called from: [1] /home/palco/work/oss/lxqt/lxqt-session/CMakeLists.txt
/usr/share/cmake-3.3/Modules/FindPkgConfig.cmake(90):  _pkgconfig_set(XCB_LDFLAGS ${_pkgconfig_invoke_result} )
   Called from: [1] /home/palco/work/oss/lxqt/lxqt-session/CMakeLists.txt
/usr/share/cmake-3.3/Modules/FindPkgConfig.cmake(63):  set(XCB_LDFLAGS -lxcb CACHE INTERNAL  )
   Called from: [1] /home/palco/work/oss/lxqt/lxqt-session/CMakeLists.txt
```
... so basicaly see what's in the `XCB_LDFLAGS` variable:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e07debb..38c3231 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -24,6 +24,7 @@ include(LXQtTranslate)
 
 find_package(PkgConfig REQUIRED QUIET)
 pkg_check_modules(XCB REQUIRED xcb)
+message("----------------------XCB_LDFLAGS='${XCB_LDFLAGS}'-----------")
 find_package(X11 REQUIRED)
 
 add_subdirectory(lxqt-session)
```

If there is also the `-L/usr/loca/lib` then something wrong is with cmake and the PkgConfig module on FreeBSD.

**Comment by palinek** [comment]
... or shouldn't we be using `pkg_search_module` instead of `pkg_check_modules`?

**Comment by paulolieuthier** [comment]
```
----------------------XCB_LDFLAGS=-L/usr/local/lib;-lxcb-----------
```

So yes, looks like something is broken.

> ... or shouldn't we be using pkg_search_module instead of pkg_check_modules?

I don't think so.

**Comment by ypnos** [comment]
Maybe it is better to open a separate issue for the freebsd building stuff?

**Comment by paulolieuthier** [comment]
@ypnos someone should build a minimal example and report to CMake.

**Comment by palinek** [comment]
> ----------------------XCB_LDFLAGS=-L/usr/local/lib;-lxcb-----------
So yes, looks like something is broken.

Hm... but it seems exacly the same as here (when I intentionaly changed the `xcb.pc`):
```
--   found xcb, version 1.10
----------------------XCB_LDFLAGS='-L/home/palco/test;-lxcb'-----------
```
...but the directory gets never used in the linking time:
```
/usr/bin/c++    -fno-exceptions -Wall -std=c++11 -O3 -DNDEBUG   CMakeFiles/lxqt-session.dir/src/main.cpp.o CMakeFiles/lxqt-session.dir/src/lxqtmodman.cpp.o CMakeFiles/lxqt-session.dir/src/wmselectdialog.cpp.o CMakeFiles/lxqt-session.dir/src/windowmanager.cpp.o CMakeFiles/lxqt-session.dir/src/sessionapplication.cpp.o CMakeFiles/lxqt-session.dir/src/numlock.cpp.o CMakeFiles/lxqt-session.dir/src/UdevNotifier.cpp.o CMakeFiles/lxqt-session.dir/LXQtAppTranslationLoader.cpp.o CMakeFiles/lxqt-session.dir/lxqt-session_automoc.cpp.o  -o lxqt-session -rdynamic -lxcb -lSM -lICE -lX11 -lXext /usr/lib/x86_64-linux-gnu/liblxqt.so.0.9.0 /usr/lib/x86_64-linux-gnu/libKF5WindowSystem.so.5.14.0 -lxcb -ludev -lSM -lICE -lX11 -lXext -ludev /usr/lib/x86_64-linux-gnu/libQt5X11Extras.so.5.4.2 /home/palco/opt/lib/libQt5Xdg.so.1.2.0 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.4.2 /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.4.2 /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5.4.2 /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5.4.2 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.4.2 -Wl,-rpath,/home/palco/opt/lib:
```
Yes, we probably should ask the cmake people what are we doing wrong....

**Comment by palinek** [comment]
@paulolieuthier 
Try to see the linking command of this simple example:
- CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.0.2)
project(xcb-test)

find_package(PkgConfig)
pkg_check_modules(XCB REQUIRED xcb)
message("-------------------XCB_LDFLAGS='${XCB_LDFLAGS}'-------------")


set(SRCS
        main.cpp
)

add_executable(xcb-test
        ${SRCS}
)

target_link_libraries(
        xcb-test
        xcb
)

install(TARGETS
        xcb-test
        RUNTIME DESTINATION "${CMAKE_INSTALL_PREFIX}/bin"
        COMPONENT Runtime
)
```
- main.cpp
```c++
#include <iostream>
#include <string>

int main(int argc, char **argv)
{
        std::cout << "Hello world!" << std::endl;

        return 0;
}
```

This should be simple enough to report, not?

**Comment by paulolieuthier** [comment]
@jsm222 I found the problem. KWindowSystem in FreeBSD installs its platform plugins in `/usr/local/lib/plugins` but Qt does not include this path in `QCoreApplication::libraryPaths()`. The solution is to `export QT_PLUGIN_PATH=/usr/local/lib/plugins`. Besides the taskbar, the desktop switch will work as well.

**Comment by jsm222** [comment]
Confirmed. I added export `QT_PLUGIN_PATH=/usr/local/lib/plugins` to /usr/local/bin/startlxqt.Thanks a lot @paulolieuthier  :-)

**Comment by agaida** [comment]
erm - really /usr/local???? - i don't know FreeBSD that much, but /usr/local is wrong by definition - and it should be fixed in FreeBSD, not by us.

**Comment by paulolieuthier** [comment]
@agaida every thing that is not part of the base system is installed in /usr/local. I find that very nice.

**Comment by krytarowski** [comment]
`/usr/local` is perfectly fine, with pkgsrc we use by default `/usr/pkg` or `/opt/pkg` (recent MacOSX)

**Comment by agaida** [comment]
ok - no objections
