### ISSUE TITLE
lxqt desktop

### ISSUE THREAD

**Issue by thor480** [lxde/lxqt#358]
Every program on desktop, you have click on before you can use the keyboard

**Comment by PCMan** [comment]
Would you please make the bug description more detailed including the step to reproduce it?
I did not understand your problem well.
Thank you.

**Comment by thor480** [comment]
Desktop takes over as first priority if you have to enter the password. So its a pcmanfm problem.

**Comment by jleclanche** [comment]
@thor480 without a clearer description of what the actual problem is, this bug report is of no use and will be closed.

**Comment by thor480** [comment]
The Desktop take's first priority over all the program, so you have click on the program before you can use it. As i wrote before. if you not satisfy with this. please close it.

**Comment by mika-k** [comment]
@thor480 
This is a matter of Openbox configuration.
Install obconf-qt and run it, this config option is in Window.
