### ISSUE TITLE
Backlight control in power management

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#36]
We should offer a backlight control app for devices on battery.

To consider:
- Keybind handling (most devices come with brightness controls, cf XF86 BRIGHTNESS input)
- A brightness slider as a panel plugin (like the volume control plugin)
- Automatic brightness adjustments depending on battery state. Should be configurable in power management config.

**Comment by paulolieuthier** [comment]
@PCMan are you sure lxqt-config-randr has backlight control? I think it has only brightness, which is different.

**Comment by selairi** [comment]
Actual lxqt-config-monitor (xrandr based) can control backlight and brightness.

The future lxqt-config-monitor (kscreen based) will not control or
backlight or brightness.

2015-06-16 17:32 GMT+02:00, Paulo Lieuthier <notifications@github.com>:

**Comment by paulolieuthier** [comment]
For future reference, this is how KDE does:
* [Brightness](http://quickgit.kde.org/?p=powerdevil.git&a=blob&h=0abcefe866ac5dc9d8bbe06457e3a597a1d426cd&hb=ecf23564bc81a418ebc6d45a97f0792097d4e5f5&f=daemon%2Fbackends%2Fupower%2Fxrandrbrightness.cpp)
* [Backlight](http://quickgit.kde.org/?p=powerdevil.git&a=blob&h=83efec1fdfa73cd5c6ae2c3d22c60f9f0029d358&hb=ecf23564bc81a418ebc6d45a97f0792097d4e5f5&f=daemon%2Fbackends%2Fupower%2Fbacklighthelper.cpp)

**Comment by palinek** [comment]
we already have the `lxqt-config-brightness`
