### ISSUE TITLE
Panel issues.

### ISSUE THREAD

**Issue by easyaspi314** [lxde/lxqt#365]
1. I seem to be unable to find/add the power manager indicator as of recent updates.

2. Sound control is useless on my laptop. I see this at boot:
![screenshot from 2014-11-04 16 09 52](https://cloud.githubusercontent.com/assets/6258309/4908207/c24bfc0c-6467-11e4-935d-adc95571771f.png)
and using the audio buttons on the front of my laptop do nothing. The only app that can control sound is `unity-control-center sound`.

3. Icons change size when the task manager windows are selected or hovered.

**Comment by jleclanche** [comment]
Guess this is irrelevant now.
