### ISSUE TITLE
Num Lock at Start-up

### ISSUE THREAD

**Issue by ovidiub13** [lxde/lxqt#368]
A menu setting to choose whether Num Lock should be on or off at start-up, would be extremely useful.

I think this should be implemented in the Keyboard settings.

**Comment by pmattern** [comment]
*"available switches"*
Disagree here: I think all three options on, off and "leave as is" are definitely needed and the latter has to be the default.
The rationale is the interaction with display managers handling num lock themselves as well which is a context LXQt will launched from very frequently.
As the settings made by a display manager are global it would be good if a user can have num lock disabled on purpose if it's enabled by the display manager. "leave as is" should be the default so as to adopt any eventual display manager setting by default.

*"backend"*
I doubt that it makes sense to use numlockx, mainly for the reasons already stated: difficult to handle downstream and limited to the X Window System.
SDDM can very well handle num lock key and LED without numlockx. I don't know which backend it's using, but maybe this would be an option, too?

**Comment by pmattern** [comment]
*"available switches"*
Disagree with what's stated in #37 : I think all three options on, off and "leave as is" are definitely needed and the latter has to be the default.
The rationale is the interaction with display managers handling num lock themselves as well which is a context LXQt will launched from very frequently.
As the settings made by a display manager are global it would be good if a user can have num lock disabled on purpose if it's enabled by the display manager. "leave as is" should be the default so as to adopt any eventual display manager setting by default.

*"backend"*
I doubt that it makes sense to use numlockx, mainly for the reasons already stated: difficult to handle downstream and limited to the X Window System.
SDDM can very well handle num lock key and LED without numlockx. I don't know which backend it's using, but maybe this would be an option, too?

**Comment by PCMan** [comment]
Fixed.
