### ISSUE TITLE
Write a pulseaudio mixer in Qt

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#369]
qasmixer isn't good enough for pulse. We need something as powerful as pavucontrol, but with a better UI.

**Comment by pranavg189** [comment]
Hi!! You can see the ongoing development of Qt fork of pavucontrol at https://github.com/pranavg189/lxmixer.
I hope to complete it in 2-3 weeks.

**Comment by Esclapion** [comment]
lxmixer has not changed since 8 months. What is its current state ?

**Comment by stefonarch** [comment]
I stumpled up on it just today, compiles well but all fields are empty...
<img src="http://i.imgur.com/2W2dqOe.png" />


Il 11/09/2015 16:58, Esclapion ha scritto:

**Comment by rcmn** [comment]
Yeah the lxmixer project is at a complete stall. For those who are looking
for a good alternative, I have been using kmix (from the kde project) and
it needs kdelibs witch needs  Attica-, automoc, docbook-xml, docbook-xsl,
giflib, libdbusmenu-qt-, libjpeg-turbo-, libpng, phonon, strigi, and
shared-mime-info .

It look a lot like what lxmixer is trying to do (visually) but it's fully
functional. Could it be reworked to use phonon-qt etc...and be more lxqt
integrated with a minimal effort ?

On Fri, Sep 11, 2015 at 12:10 PM, Stefano Binde <notifications@github.com>
wrote:

> I stumpled up on it just today, compiles well but all fields are empty...
> <img src="http://i.imgur.com/2W2dqOe.png" />
>
>
> Il 11/09/2015 16:58, Esclapion ha scritto:
> > lxmixer has not changed since 8 months. What is its current state ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/lxde/lxqt/issues/369#issuecomment-139568245>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/369#issuecomment-139587563>.
>



-- 
R.

**Comment by JustDevZero** [comment]
I forked LXmixer from @pranavg189 as I detected him as "inactive" and added some more things on the UI...

https://github.com/JustDevZero/lxmixer

But still not functional, not a simple call to . Also, I writed an issue to him (afaik github doens't have direct messages yet).

https://github.com/pranavg189/lxmixer/issues/6

Also as I said there, tried to download source code of pavucontrol to kinda migrate the code, and also have a look on plasma-pa, but I see that both of the projects have a really poor documentation :(

I may try to download code from kmix as rcmm said, to see if there is something more understandable there...  If anybody can/want help I (and the rest of community) will apreciate it.

**Comment by palinek** [comment]
Just had a quick look at the pranavg189/lxmixer... what is there to fork? It does literaly nothing at all. Or am I missing something?

**Comment by JustDevZero** [comment]
You didn't miss a thing, the code is still not functional, only UI stuff yet :/

**Comment by pmattern** [comment]
What ever the outcome will be I doubt that `lxmixer` is a suitable name.
As a rule of thumb terms like `lx<description>` belong to LXDE while `lxqt-<description>` is used on LXQt. This is already disrespected in `lxqt-sudo` but only with regards to some symbolic links. Also, that difference may become irrelevant should LXDE get abandoned one day which won't happen that soon, though.
So all in all a term `lxqt-foobar` would be the far more suitable choice, IMO.

**Comment by thomaspierson** [comment]
Hi! Is anyone working on this?
If not maybe I will make a try. My idea is to start something from scratch and simple without forking pavucontrol or anything else. First I plan to take inspiration from kmix and see how it uses libpulse, libasound and other components to make its job.
Any advice or remark on this plan would be greatly appreciated.

**Comment by jleclanche** [comment]
Sounds good. Go ahead.

I would recommend focusing on writing something with just libpulse in mind, that has at least the basic functionality that pavucontrol offers. If you need some UI ideas when you get to that, @-me and I can chime in.

**Comment by PCMan** [comment]
@thomaspierson I personally has quite different suggestions.
Porting pavucontrol might be a good starting point.
It's gtk+, but the code base is in C++ and part of the Gtk+ stuff already used gtkmm, the c++ binding of gtk+. So, making it Qt is somewhat like translation.
With this document, it's possible to port it to Qt.
http://wiki.lxde.org/en/Migrate_from_GTK%2B_to_Qt

**Comment by PCMan** [comment]
@thomaspierson @jleclanche 
I just started an attempt to port pavucontrol to Qt 5.
https://github.com/PCMan/pavucontrol-qt/tree/qt
Just moved from automake to CMake and built the inital UI.
It's not working yet, but I think it's not too difficult.

**Comment by jleclanche** [comment]
To be honest, I think the pavucontrol UI is a disaster. I hope that if we port it, we don't attempt to replicate it too closely. But that is a great starting point; want to move it to the lxde org?

**Comment by PCMan** [comment]
@jleclanche I think I can finish the port this week since it looks quite trivial.
Then I'll move it to lxqt, but maybe qtdesktop is a better place for it since it's not LXQt only.
About UX, getting it work first, and do UI polishing later.
At least we need to have something that works.

**Comment by palinek** [comment]
> Then I'll move it to lxqt, but maybe qtdesktop is a better place for it since it's not LXQt only.

Why? For the very same reason we would move other LXQt more-or-less-standalone components (e.g. pcmanfm-qt, lximage-qt, obconf-qt, lxqt-sudo...).
IMHO it is better to put it into LXQt. It's an OSS and GPL2 (if you don't change the license somehow), so anybody can use/package/distribute/fork it...

**Comment by jleclanche** [comment]
The qtdesktop org is imho a failed experiment. I tried, but not enough people joined in - as it stands it's just a LXQt repo.

**Comment by PCMan** [comment]
OK, then let's put in in our project. I'll do it soon.

**Comment by thomaspierson** [comment]
Ok if you think it's a better way no problems. I stop my "from scratch" experiment for now.
Cheers!

**Comment by PCMan** [comment]
@jleclanche @thomaspierson @palinek 
I just finished the initial port of pavucontrol to Qt5.
https://github.com/lxde/pavucontrol-qt
Most of the basic functions work as expected, but there are still some minor bugs.
I did not do any UI polishing and the widget layouts and graphics are terrible now.
Due to lack of time, I leave the UI polishing task to other developers who are interested in it.
NOTE:
* Currently it still requires glibmm, but this can be removed later by replacing Glib::ustring class with QByteArray and QString.
* There are tons of *.po files which contain translations for the gtk+ version. We can convert them to *.ts files with tools and we can have ready to use translations. I haven't done this part.
Cheers!

**Comment by PCMan** [comment]
@jleclanche @palinek @thomaspierson @Esclapion @pmattern @paulolieuthier 
The Qt port of pavucontrol is almost done. I think it's time to close this issue.
https://github.com/lxde/pavucontrol-qt
The latest changes:

1. Completely removed glibmm and GNU gettext dependencies.
2. Convert the original gettext *.po translation files to Qt *.ts format with some manual fixes.
3. The translations are uploaded to lxqt-l10n already

The only things we need to do before the first release.

1. UI polishing. Some QBoxLayout are not in optimal configurations and the widgets scale in very weird and ugly ways. Someone who know how Qt layouts better please help.
2. more testing. (It works flawlessly here, but more testing is always good)

Cheers!

**Comment by pmattern** [comment]
IMO it could be discussed whether it would make sense to implement the features of `paprefs` in another Qt GUI complementing `pavucontrol-qt` but that aside this issue can sure be closed now.

Let me just mention a finding I'm not sure what to think about.
The icon to lock the channels is blank in all occurrences
![pavucontrol-qt_emtpy-lock-icon](https://cloud.githubusercontent.com/assets/9860801/18188989/fba6cd1c-70b6-11e6-9ba5-e792d7dd8986.png)
and independent of the icon theme in use (tested with Adwaita, Tangerine and Oxygen).
IIRC there's some Qt issue yielding effects like this but don't recall or find details about it right now.
So is it some Qt issue or a problem in pavucontrol-qt?

Btw. I've prepared an [AUR VCS package](https://aur.archlinux.org/packages/pavucontrol-qt-git/) providing master checkouts.

**Comment by jleclanche** [comment]
This is awesome.

Closing. Move issues to https://github.com/lxde/pavucontrol-qt/issues

**Comment by PCMan** [comment]
@pmattern The icon is empty because I did not find a suitable icon for it.
The original pavucontrol uses a gtk+ built-in icon here, but there is no such icon in the xdg icon naming spec. We need to make an alternative icon for it.

**Comment by Esclapion** [comment]
Works for me, nice :-). Please activate "volum meter" by default. 
![capture d ecran_2016-09-02_10-07-25](https://cloud.githubusercontent.com/assets/3512979/18197036/6e6f2a04-70f5-11e6-91ee-1fa544cb1fd0.png)

Some french translations to do, but it's already useable.

**Comment by palinek** [comment]
@PCMan great! The UI is a bit more stranger than the original one. But I don't know if it's worth doing some minor UI improovements if @jleclanche does want a complete UI redesing.

**Comment by jleclanche** [comment]
I like the approach of replicating pavucontrol's UI first.

**Comment by stefonarch** [comment]
Works like a charm, thanks! Looking at the translations with -DUPDATE_TRANSLATIONS=ON I find some voices which I don't find in any place in the GUI, like 

> Select a specific tab on load.
> Maximize the window.
> Rename Device...

Also some accelerators are present but not seen in GUI, example Tab titles:
&Output Device

**Comment by palinek** [comment]
> The icon is empty because I did not find a suitable icon for it.

How about using the "changes-prevent"... it's not in the XDG spec, but many themes include this icon.
