### ISSUE TITLE
Panels do not stack, and it is too easy to add one.

### ISSUE THREAD

**Issue by easyaspi314** [lxde/lxqt#373]
I was about to leave LXQT when my panel went blank. I went back to test something and I started to reorganize my panel when I accidentally right-clicked and added a new panel **exactly on top of the other**. I removed that panel and then I had one below it. By the way, this also happens in normal LXDE. **At least LXDE had a setup dialog.** This just adds a panel. Can easily be mistaken as your panel just disappearing. 
>![blankpanel](https://cloud.githubusercontent.com/assets/6258309/4962164/b6d962e6-66d9-11e4-9347-97c4481343db.png)
>*There is a panel directly below this. You can't see it, and do not really know if it is there.*

IMHO, panels should stack in rows/columns. I have a very tiny bit of C++ knowledge, so I have no idea how complex this would be, but I see **no** advantage to the current behavior.

**Comment by jeremywh7** [comment]
I got into a confusing mode where my panel appeared to get reset.  After a minute, I realized that (apparently...though I didn't think I did) when I tried to select 'Manage Widgets' I actually clicked 'Add Panel'.  The Configure window coming up in this scenario was therefore expected.  And my auto-hidden taskbar was no longer visible.  This is why I first thought my panel got reset.  Only when I tried adding widgets and seeing the numerical increments, did I realize I must have accidentally add a new panel.

I mostly wanted to bring up that 'auto-hide' might add another layer of thought to addressing this issue.  Thanks guys!

**Comment by jeremywh7** [comment]
> We try to find an not used position. If all already taken, we simply use the Bottom.
Would it be better to just not add the new panel, if there is no room for it?  I.e. have a popup indicating something like, "No free space for new panel."  Alternatively, it could still allow the option, like "No free space for new panel; add anyway?"

**Comment by tsujan** [comment]
@jeremywh7's idea seems more logical to me, i.e., not adding any panel when there's no space left.

**Comment by palinek** [comment]
> Would it be better to just not add the new panel, if there is no room for it? 

But we don't know easily, if there is a place for new panel. You can e.g. wish to have 3 panels on the bottom (left, center, right) of the same screen...

**Comment by tsujan** [comment]
> You can e.g. wish to have 3 panels on the bottom

Oh, I hadn't thought about that! It's still theoretically possible to know whether there's an empty space but the code might get too complex.
