### ISSUE TITLE
Some widgets can not be themed

### ISSUE THREAD

**Issue by intialonso** [lxde/lxqt#374]
Maybe Im missing something, but this are some little issues I have found while theming:

**LXQT Runner**

The searh results (QListView or "commandList") use the system theme, but still refuses to be styled with the lxqt-runner.qss. The last update did not change this, or I did not notice how to do it.

**Panel Plugins**

Show Desktop, Screen Saver, Volume and Mount seems to have a fixed size. If you change the size of the panel to 60px you will see that this widgets stay in a same size while all the others expand with the panel. This leads to them having non clickable areas. This happen also with the old themes.

![rect4613](https://cloud.githubusercontent.com/assets/7544231/4964509/cd7a1e68-672f-11e4-8031-3c829bb915e6.png)

I have been lurking the code searching for a way to change this behavior. From the stylesheets the only thing that seems to work is to put "height: 100%" but this is not necesary with other widgets (and this lead to other glitches), so I think that there must be something wrong with this plugins.

**Comment by palinek** [comment]
Hi guys... I was playing around with this with no luck to make the button expand (tried adding different layouts, buttons...). Finally I realized that this all is happening as a feature -> the row height in panel layout is given by configuration parameter "Icon size".
So should this behavior be changed? (user can expand the icons by configuration)

**Comment by paulolieuthier** [comment]
@palinek the problem, IMO, is when you want to click on a plugin but you move the pointer to the bottom of the panel (assuming it's on bottom). Depending on the height of the panel, the plugin won't be clicked. I use 30px as height, and I can activate the volume plugin clicking that way. That doesn't work for the systray icons, though.

**Comment by palinek** [comment]
@paulolieuthier yes, that's the discrepancy between sizes (panel size & icon size). Icons are placed into a grid (each icon centerd in its cell). If the "panel size" is bigger than "rows count" * "icon size" => there is space between icon buttons...

**Comment by palinek** [comment]
I've tried to fix this in lxde/lxqt-panel/#409 ..
