### ISSUE TITLE
lxqt-panel should respect the xdg-way of reading configurations

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#385]
it should be: 
- /usr/share/lxqt-panel/panel.conf
- /etc/xdg/lxqt/panel.conf
- /$home/.config/lxqt/panel.conf

unfortunally in 0.8.0 only ~/.config/lxqt/panel.conf is respected. The configurations should all readed and parsed, last applicable parsed value wins.

Note: ok - one can read configurations with lxqt-panel -c $configuration, but that should not the way we provide default configurations. Workaround for now: provide a configuration file via /etc/skel, but this is fugly

**Comment by paulolieuthier** [comment]
When trying to read a key from a QSettings, it'll look for the key in `$HOME/.config/lxqt/panel.conf`. If not found, then in `$HOME/.config/lxqt.conf`. Then `/etc/xdg/lxqt/panel.conf`. Then `/etc/xdg/lxqt.conf`.

@agaida can you point me to where I can find that part of XDG's spec?

**Comment by agaida** [comment]
http://standards.freedesktop.org/basedir-spec/latest/

ok - it's more than vague

**Comment by paulolieuthier** [comment]
From xdg's spec:

`$XDG_CONFIG_HOME` defines the base directory relative to which user specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used.

`$XDG_CONFIG_DIRS` defines the preference-ordered set of base directories to search for configuration files in addition to the `$XDG_CONFIG_HOME` base directory. The directories in `$XDG_CONFIG_DIRS` should be seperated with a colon ':'.

If `$XDG_CONFIG_DIRS` is either not set or empty, a value equal to `/etc/xdg` should be used.

The order of base directories denotes their importance; the first directory listed is the most important. When the same information is defined in multiple places the information defined relative to the more important base directory takes precedent. [...] The base directory defined by `$XDG_CONFIG_HOME` is considered more important than any of the base directories defined by `$XDG_CONFIG_DIRS`.

@agaida I think QSettings is pretty close to that. It doesn't read `$XDG_CONFIG_DIRS`, but it does use `/etc/xdg`. And the order is different from what you said.

**Comment by gilir** [comment]
Same that #349, actually QSettings seems not fully compliant with the xdg spec

**Comment by doktor5000** [comment]
FWIW, this is how I'm currently dealing with this issue in startlxqt itself:
http://svnweb.mageia.org/packages/cauldron/lxqt-common/current/SOURCES/lxqt-common-0.9.1-mga-add-pcmanfm-lxqt-config-files.patch?view=markup

Works fine here, at least newly created users get a complete panel and working configuration on first login, and the panel configuration from /etc/lxqt/panel.conf is respected and used.

Although a less hackish approach would be appreciated longterm :)

**Comment by luis-pereira** [comment]
@doktor5000 One less hackish way would be installing it as ```/etc/xdg/lxqt/panel.conf```  instead of ```/etc/lxqt/panel.conf ```

**Comment by doktor5000** [comment]
Well, then you would probably need to change the default target path, we don't deliberately install it there.  But yes, according to the spec that would be a better place.

**Comment by luis-pereira** [comment]
@doktor5000 We use ```qmake -query QT_INSTALL_CONFIGURATION``` to find the prefix. Do you need some kind  of override ?

**Comment by doktor5000** [comment]
@luis-pereira Expands directly to /etc here.
Would probably be better to use an option similar to -DXDG_CONFIG_HOME=/etc/xdg/ if you want it configurable, and default to /etc/xdg/lxqt.

**Comment by luis-pereira** [comment]
@doktor5000 @agaida We already have it. When configuring liblxqt one can use: ```cmake -DLXQT_ETC_XDG_DIR=/etc .. ``` to override the default value:  ```qmake -query QT_INSTALL_CONFIGURATION```

**Comment by doktor5000** [comment]
And e.g. lxqt-common uses that value from the installed liblxqt?
Does not sound logical to me, as liblxqt does not install anything below /etc, but I'll give it a try.

**Comment by luis-pereira** [comment]
@doktor5000 They should. If not, please report it.
All of LXQT_ETC_XDG_DIR here: http://pastebin.com/RpfntKjL

**Comment by palinek** [comment]
Have a look on the lxde/liblxqt#104 ...

**Comment by palinek** [comment]
The Qt patches bringing correct support for XDG_CONFIG_DIRS to QSettings were merged (qt/qtbase@ee35fbb, qt/qtbase@4758555).

So I'd like to close this. Does anyone insist to leave this issue open?
