### ISSUE TITLE
Add a panel separator 

### ISSUE THREAD

**Issue by onekk** [lxde/lxqt#394]
Please add a panel separator it's visually confusing having a launch icon and a systray icon near without the possibility to add a separator between them.

Regards

Carlo D.

**Comment by palinek** [comment]
This one seems to be an easy task. I can handle it, if you wish...
@paulolieuthier, @jleclanche: is there any special functionality that it should cover or should it only be a horizontal/vertical space with configurable width?

**Comment by jleclanche** [comment]
Have it a horizontal-only spacer with configurable width.

**Comment by palinek** [comment]
I've created PR lxde/lxqt-panel#137 for a possible fix of this issue.
