### ISSUE TITLE
Keyboard layouts are forgotten

### ISSUE THREAD

**Issue by ypnos** [lxde/lxqt#399]
Using lxqt's Keyboard & Mouse settings dialog, I add a German keyboard layout and put it in top position. It works as expected and my keyboard layout is changed.

However, seemingly randomly, my layout changes get completely lost. I.e., I am back with the English keyboard layout; and when re-opening the settings dialog, the list only shows English (US). Apparently, my setting changes are completely "forgotten".

This does not happen suddenly while I type, but always after some inactivity. It might be related to XScreensaver running. Sometimes it happens when I log-off and on again, sometimes it doesn't.

Reporting on lxqt-config-git version 0.8.0.3.gebb4c7b-1. I had this bug already with 0.7; Arch Linux system. In the journal I see these entries:

```
Dez 02 14:34:49 lme51 lxqt-config-input[32036]: iconTheme "Ubo-Icons"
Dez 02 14:34:49 lme51 lxqt-config-input[32036]: Theme: Cannot open file for reading: "/usr/share/lxqt/themes/dark/lxqt-config-input.qss"
Dez 02 14:34:49 lme51 lxqt-config-input[32036]: LxQt::Translator: Qt translations not found
Dez 02 14:34:49 lme51 lxqt-config-input[32036]: add "de" "nodeadkeys"
Dez 02 14:34:49 lme51 lxqt-config-input[32036]: add "us" ""
Dez 02 14:36:19 lme51 lxqt-notificationd[22459]: Notification "New Mail" category QVariant(QString, "email.arrived")
Dez 02 14:36:19 lme51 lxqt-notificationd[22459]: Notification "New Mail" urgency QVariant(uchar, 1)
Dez 02 14:36:19 lme51 lxqt-notificationd[22459]: Notification "New Mail" category QVariant(QString, "email.arrived")
Dez 02 14:36:19 lme51 lxqt-notificationd[22459]: Notification "New Mail" urgency QVariant(uchar, 1)
Dez 02 14:36:19 lme51 lxqt-notificationd[22459]: Notification app "New Mail" summary "From: *******" is already registered but this request is not an update. Broken app?
Dez 02 14:36:39 lme51 lxqt-panel[22463]: requestActivate() called for  QWidgetWindow(0xc06ee0, name = "LxQtPanel panel1Window")  which has Qt::WindowDoesNotAcceptFocus set.
Dez 02 14:36:43 lme51 lxqt-config-input[884]: iconTheme "Ubo-Icons"
Dez 02 14:36:43 lme51 lxqt-config-input[884]: Theme: Cannot open file for reading: "/usr/share/lxqt/themes/dark/lxqt-config-input.qss"
Dez 02 14:36:43 lme51 lxqt-config-input[884]: LxQt::Translator: Qt translations not found
Dez 02 14:36:44 lme51 lxqt-config-input[884]: add "de" "nodeadkeys"
Dez 02 14:36:44 lme51 lxqt-config-input[884]: add "us" ""
```

I don't see anything suspicious there.

**Comment by ypnos** [comment]
Is there anything to workaround this bug, like making keyboard config read-only? It is really annoying..

**Comment by PCMan** [comment]
Well, though I developed this part initially, I'm not an expert of keyboard
layout.
Actually, in our language we don't need keyboard layouts.
So when I did it, I read the source code of other projects to see how
should this be done.
If there are any problems, we need help from developers who are familiar
with keyboard layout stuff.
We have some developers from Europe so I leave this bug to them.

**Comment by gauthma** [comment]
Hello,

Are there any news about this? Or workarounds? (other than having to log out and in when plugging keyboards...). I am willing to take a look at the code and try to fix it, but I would appreciate some pointers of where to begin... I am already taking a look at the code of lxqt-session, but I am not certain the problem lies therein (because the settings the session file are always correct, even when the layout is *incorrect*!). Maybe it is some unsuspected interference from another piece of code elsewhere?

**Comment by paulolieuthier** [comment]
I'm afraid no news. I can't test it and can't imagine any possible reasons.

**Comment by gauthma** [comment]
I may have (very much accidentally) discovered a workaround... I just compiled lxqt-seesion, and (after unplugging and plugging back in the external keyboard) ran the lxqt-session binary... and the proper layout is back! So far there seems to be no nefarious effect caused by this... Thoughts?

**Comment by paulolieuthier** [comment]
Have you being able to reproduce the bug as well?

**Comment by gauthma** [comment]
Ah yes, I should have mentioned it more explicitly: I am able to reproduce the bug, just as reported. It happens with an external keyboard, and also when un- and then re-plugging the said keyboard: settings are fine after unplug, but forgotten after re-plug. I'm running lxqt 0.9, in ArchLinux.

**Comment by palinek** [comment]
The problem seems to be somewhere in xserver and/or setxkbmap. I didn't use lxqt-config-input in any way and the keyboard layout is simply set in `.xsessionrc`. And I can confirm that the keyboard layout configuration is lost after USB keyboard is plugged in.

We probably need to make a workarround by listening when new keyboard is plugged nad set layout configuration afterwards.

**Comment by palinek** [comment]
On my system keyboard layout is set by `udev` when new keyboard is plugged and is somehow connected to rules it's rules. I found following rule udev rule `64-xorg-xkb.rules`:
```sh
ACTION!="add|change", GOTO="xorg_xkb_end"
SUBSYSTEM!="input", GOTO="xorg_xkb_end"
KERNEL!="event*", GOTO="xorg_xkb_end"

# import keyboard layout from /etc/default/keyboard
ENV{ID_INPUT_KEY}=="?*", IMPORT{file}="/etc/default/keyboard"

LABEL="xorg_xkb_end"
```

That gave me a clue for `/etc/default/keyboard` -> if it is configured the same way as with the `setxkbmap` (e.g. by `lxqt-config-input`) then the layout will remain the same after keyboard plug. But I still don't know which rule is responsible for loading the layout (commenting/removing `64-xorg-xkb.rules` does not affect it).

**Comment by palinek** [comment]
Just updated lxqt-session in lxde/lxqt-session@bba7a71 to monitor input devices adding and (re)set our keyboard layout afterwards.
@gauthma, @ypnos can you, please, test it?

**Comment by gauthma** [comment]
@palinek It seems to be working! yay :D (and thank you!)

**Comment by palinek** [comment]
@gauthma thanks, merging...
