### ISSUE TITLE
More streamlined settings entry in main menu

### ISSUE THREAD

**Issue by Schwefelsaeure** [lxde/lxqt#400]
Currently, all LXQt settings are listed under "Settings" entry in start menu:

* Settings
  * Date and Time
  * File Associations
  * ...
  * Users and Groups

This clutters up the complete "Settings" entry. Why not offering only "LXQt Settings Center" like KDE does it with "KDE System Settings"? From LXQt's setting center all sub-options are available.

**Comment by paulolieuthier** [comment]
@jleclanche, @PCMan, @luis-pereira, @kuzmas, @surlykke what are your opinions on this one (I mean the original issue). I think it makes sense, it would be nice to solve it for 0.9.

**Comment by PCMan** [comment]
I think the original razorqt menu is better.
Grouping all LXQt settings tool together in their own sub directory.

**Comment by paulolieuthier** [comment]
I agree. It doesn't have to be for 0.9, but it'd be nice. I know nothing about xdg's menu spec, though.

**Comment by surlykke** [comment]
2015-01-26 14:08 GMT+01:00 PCMan <notifications@github.com>:

> I think the original razorqt menu is better.
> Grouping all LXQt settings tool together in their own sub directory.
>
>
I agree - a sub menu would seem to be a good compromise between avoiding
clutter and having direct access to functionality. (To be honest, though, I
rarely use the menu. Normally I'd access stuff from lxqt-runner...)

br. Chr.

**Comment by paulolieuthier** [comment]
That was solved sometime ago.
