### ISSUE TITLE
Expand window of Configuration Centre

### ISSUE THREAD

**Issue by hterh** [lxde/lxqt#406]
The window of the Configuration Centre (c.q. LXQt System Settings in the menu) does not show the last row of System settings, nor does it remember its prevous size after expanding. First time users may be unaware that more icons are present.

**Comment by alfredobonino** [comment]
And most of text of the settings button are cut.

**Comment by pmattern** [comment]
Text getting cut is addressed in #501 in the meantime (missing adjustment of window size etc. isn't).
