### ISSUE TITLE
Make LXQt::SingleApplication allow (or forbid) running multiples instances on runtime

### ISSUE THREAD

**Issue by paulolieuthier** [lxde/lxqt#407]
It would be useful to have the option to allow or forbid running multiple instances of an application whenever the user wants (in the application's config dialog, for example).

**Comment by PCMan** [comment]
What's the status of this issue?

**Comment by paulolieuthier** [comment]
It's not really needed now,

**Comment by luis-pereira** [comment]
@PCMan I can "port" from liblxqt. It's no big deal. But I agree with @paulolieuthier, it's not important for now.

**Comment by jleclanche** [comment]
Closing this.
