### ISSUE TITLE
LXQt panel: several translations of plugin Network Monitor faulty

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#409]
In many of the files ./plugin-networkmonitor/translations/networkmonitor_*.desktop section '# Translations' states plugins other than Network Monitor.
As a result Network Monitor is referred as something completely different in the panel's dialog window to add plugins.

Following continuously edited list summarizes affected languages, based upon what I thought I could judge only, so possibly wrong or incomplete
* as of 2015-07-12 all fixed: Czech (lxde/lxqt-panel@9ea6f33), Dutch (lxde/lxqt-panel@7b74523), Esperanto (lxde/lxqt-panel@3f4396e), French / German (lxde/lxqt-panel@46426b6), , Italian (lxde/lxqt-panel@94248db, lxde/lxqt-panel@1deb6a7), Polish (lxde/lxqt-panel@d9b517f), Portuguese (lxde/lxqt-panel@44dd662, "_BR" only affected), Romanian (lxde/lxqt-panel@76ae0fa), Spanish (lxde/lxqt-panel@a6646aa)

**Comment by paulolieuthier** [comment]
@pmattern is this still valid?

**Comment by pmattern** [comment]
Yes. Including list in first posting.

**Comment by palinek** [comment]
@pmattern updated your first comment for the Czech

**Comment by pmattern** [comment]
@stefonarch
Could you have a look at the Italian files corresponding to this issue? I don't speak Italian but IMHO those are crap, too.
Also, I'm not sure whether the country-specific flavour ("_IT") is needed in Italian in the first place.

**Comment by stefonarch** [comment]
@Mattern: There are two  main italian regional flavours  (italian and
swiss which are very few people)  as I know, but I couldn't tell if
there are any significant differences, I think using only _it_It will do
 for the moment, if there will be a swiss-italian translater he could
create it_CH.

The translations were completely different, and different in both files,
on my system it said "Change desktop (exit)"... I didn't even notice
that there was a network monitor plugin...




Il 21/05/2015 15:39, Peter Mattern ha scritto:

**Comment by pmattern** [comment]
@stefonarch 
All right. So I think we can drop the country-specific "_IT" as the language-specific ones seem to get used whenever a country-specific is missing.
E. g. foobar_de.ts (strictly speaking what it was translated to when compiling) gets used when locale is set to de_DE.UTF-8 but foobar_de_DE.ts doesn't exist.
But no hurry. Maybe we should even wait until pootle.lxde.org is ready for production use.

**Comment by paulolieuthier** [comment]
News on this one?

**Comment by pmattern** [comment]
@paulolieuthier  updated initial comment

**Comment by stefonarch** [comment]
As I see faulty  are:
ar,zh,tr,sr@latin,sl,ro_RO,pl_PL,pl,nl,lt,id_ID,hu,es,eo
For spain and dutch I've some friends to ask, maybe just delete all
faulty one's? Better in english than a mess.

I would say

Il 14/06/2015 19:54, Peter Mattern ha scritto:

**Comment by paulolieuthier** [comment]
> Maybe just delete all faulty one's? Better in english than a mess.

I agree.

**Comment by palinek** [comment]
> > Maybe just delete all faulty one's? Better in english than a mess.

> I agree.

Should I remove all the: ar,zh,tr,sr@latin,sl,ro_RO,pl_PL,pl,nl,lt,id_ID,hu,es,eo translations?

**Comment by jubalh** [comment]
@palinek give me one more day. I might get some friends helping with polish and esperanto translation. maybe es and tr too.

**Comment by palinek** [comment]
@jubalh OK... after you're finished, please, clean all the messy ones and close the issue.

**Comment by jubalh** [comment]
* Couldn't we just use the same for es and ar until someone comes up with a specific ar one. I suppose they will understand anyway. and for them european spanish might still be easier than english.

* What is id_ID and sr@latin?

**Comment by palinek** [comment]
> - What is id_ID and sr@latin?

indonesian and serbian (don't know much about the @ notation)

[ref](http://www.science.co.il/Language/Locale-codes.asp)

**Comment by luis-pereira** [comment]
@jubalh sr@latin it's Serbian written in Latin characters instead of the Cyrillic characters.

**Comment by jubalh** [comment]
thanks for info and link @palinek and @luis-pereira

**Comment by jubalh** [comment]
I will later take care of
* ro_RO
* tr (desktop file already done)
* sr@latin (maybe in some weeks)

But cannot help with
* ar
* zh
* sl
* lt
* id_ID
* hu

And what is the difference between?
* pl_PL
* pl

**Comment by palinek** [comment]
> And what is the difference between?
- pl_PL
- pl

There were a discussion somewhere in issues if the country specific (xx_YY) file should be provided or just language (xx) when there's no difference (no specific translation for country/location). I don't remember the decicion now. @luis-pereira @jleclanche @pmattern ?

**Comment by jubalh** [comment]
That's why I asked. I am not too familiar with pl, but I thought its only spoken in one country?

**Comment by palinek** [comment]
> I am not too familiar with pl, but I thought its only spoken in one country?

The second biggest city of Poland is Chicago :-), but I think you're right there's no other specific region dialect.

**Comment by pmattern** [comment]
@palinek
Regarding country specific files which apparently aren't necessary: not sure whether there's been an agreement. But very often those were just dropped which seems to work exactly as expected, that is the language specific one is picked automatically.
E. g. if locale is de_CH.UTF-8 and files foo_de_CH.* aren't available but foo_de.* only the latter are picked automatically.

While at it let me briefly state that (unlike I first thought) languages do exist where country specific files are definitely needed, e. g. Portuguese.

**Comment by jubalh** [comment]
Fixed desktop files for Dutch, Esperanto, Polish, Romanian and Spanish.
Still some .ts files are missing, but like @pmattern pointed out to me, this is not part of this issue.

**Comment by luis-pereira** [comment]
@pmattern @jubalh @palinek I don't recall any agreement. There were discussions but no agreement AFAIK.

I'm an native Portuguese speaker. Portuguese needs country specific files.

**Comment by pmattern** [comment]
All languages suspected to be faulty are fixed as of 2015-07-12. This does not mean that all languages in general are fixed due to the reasons stated in the first post.
I think two alternatives exist: (i) Delete all translations that haven't been checked yet. That way we'd follow the idea "better English only than a mess" as stated by stefonarch above (ii) Leave all remaining ones as is.
Personally, I'm not sure what's the better approach.

Also, the question how to deal with those country-specific translations that are probably unneeded is still open.
But actually this is something we stumbled upon while discussing here, but not this issue's topic.

**Comment by paulolieuthier** [comment]
I agree we should remove all mess and call translators when we get to string freeze.

**Comment by palinek** [comment]
What't the status of this?

**Comment by palinek** [comment]
job done, thanks @jubalh
