### ISSUE TITLE
World clock 

### ISSUE THREAD

**Issue by ianorlin** [lxde/lxqt#416]
In LXQt from the ubuntu ppa which gets updated fairly soon and imports the git versions the world clock plugin has a custom option with a nice help dialog but the problem is I can't really read the dialog without having to scroll many times to read it makes it a bit diffcult to customize even though the documenation in the plugin explains it well. Also resizing the window to make the top part bigger if I want more room to read how to customize it more. Right now it is trying to print 15 lines in about 3 lines of space. 

![worldclockhardtoread](https://cloud.githubusercontent.com/assets/7546640/5530263/b713ce4c-89d2-11e4-8eb8-155a2dca4f46.png)

**Comment by kuzmas** [comment]
Status update: I'm rewriting the configuration dialog. Work in progress, finishing soon.

**Comment by kuzmas** [comment]
Done in https://github.com/lxde/lxqt-panel/commit/5ecdd576539bcca84189a28489a12417c3150937

@jleclanche Please review it and if you're happy with the new configuration dialog - close this issue.

**Comment by jleclanche** [comment]
Thanks, I'll review on tuesday.

**Comment by paulolieuthier** [comment]
I don't see a difference. I'm not a UX expert, but I think the UI still needs some love.

**Comment by kuzmas** [comment]
Well I see. Compare the current UX:
![new_ux](https://cloud.githubusercontent.com/assets/1858553/5694641/577542d2-99d5-11e4-8dc7-bccc2446a7fa.png)
with the old one in the first message in this issue (https://github.com/lxde/lxqt/issues/416#issue-52685037)

**Comment by jleclanche** [comment]
Ok some late feedback. Great work, btw.

Time:
- Rename "Use AM/PM" to "Use 12-hour format". This is to be more easily understood by users who are not accustomed to AM/PM notation.

Time zones:
- Timezone section can be merged with time. Can remove Position altogether and replace with a checkbox in time "Show time zone". The format dropdown can then be renamed to "Time zone format" and be disabled if "Show time zone" is unchecked.
- Time zone format "Custom name" is not showing if you don't have a timezone configured (default). Super weird. I'm in favour of removing Custom name functionality altogether.
- Remove "Abbreviation" as it's the same as short (and if it's not in some obscure locale, it doesn't really matter, imo. As it stands it's clutter.)
- Rename "IANA id" to "Location identifier"

I'm still not a fan of the advanced section. I still believe it's not worth keeping it in the GUI, to be honest. Oh well, your call.

Time zones tab should have a small intro text that explains how adding/removing timezones actually affects the display of the plugin in the panel. I still am not sure how that works.

Have you considered merging the General and Time zones tabs instead now? I really want the General tab to be left-most and default, but it's too empty right now. And the time zones tab feels too large/clunky for the functionality it offers (especially if we remove custom name).

**Comment by paulolieuthier** [comment]
@kuzmas, it's much better. I'm sorry, I updated the panel but didn't get the plugin or something. Nice work.

**Comment by kuzmas** [comment]
@jleclanche 

> Time:
> 
> Rename "Use AM/PM" to "Use 12-hour format". This is to be more easily understood by users who  > are not accustomed to AM/PM notation.

done

> Time zones:
> 
> Timezone section can be merged with time.

not really as timezone section gets disabled if **Long** time format is selected (it already contains timezone information)

> Can remove Position altogether and replace with a checkbox in time "Show time zone". The format dropdown can then be renamed to "Time zone format" and be disabled if "Show time zone" is unchecked.

I prefer to give more flexibility in positioning. I personally like it to be in a separate line. Other people would like it be after the time. To support all possible variant I've added 'before' and 'above' items. Also 'before' potentially can be usefull for people who use to RTL writing direction.
Anyway this option cannot be just a checkbox :-( .

> Time zone format "Custom name" is not showing if you don't have a timezone configured (default). Super weird.

Agree that it's not ideal to have Custom name empty by default.
We could show **_bright blinking magenta clickable warning ;-)_** if Custom name is selected but not filled in at least one of used timezones. What do you think?

> I'm in favour of removing Custom name functionality altogether.
It was just recently added as a response to request in https://github.com/lxde/lxqt/issues/312#issuecomment-68588776

> Remove "Abbreviation" as it's the same as short (and if it's not in some obscure locale, it doesn't really matter, imo. As it stands it's clutter.)

It depends on the system I presume. I get "GMT+13" for the Short and "NZDT" for the Abbreviation.

> Rename "IANA id" to "Location identifier"

done

> I'm still not a fan of the advanced section. I still believe it's not worth keeping it in the GUI, to be honest. Oh well, your call.

If we remove it from GUI then we cannot show the help which is crucial. See https://github.com/lxde/lxqt/issues/416#issuecomment-68156477

> Time zones tab should have a small intro text that explains how adding/removing timezones actually affects the display of the plugin in the panel. I still am not sure how that works.

I'll have to think about it

> Have you considered merging the General and Time zones tabs instead now? I really want the General tab to be left-most and default, but it's too empty right now.

Maybe we should rename "General" to something different so it'll stop asking to be the main tab?

> And the time zones tab feels too large/clunky for the functionality it offers (especially if we remove custom name).

IMHO not a major issue especially if we leave Custom name.

**Comment by jleclanche** [comment]
> It depends on the system I presume. I get "GMT+13" for the Short and "NZDT" for the Abbreviation.

I'd be in favour of keeping only abbreviation then, and renaming it to "Short".

> not really as timezone section gets disabled if Long time format is selected (it already contains timezone information)

Yes, I saw, I like it; but with less checkboxes/fields as suggested, you can simply disable those fields instead.

> We could show bright blinking magenta clickable warning ;-) if Custom name is selected but not filled in at least one of used timezones. What do you think?

Sell me on the use case: Why would a user bother setting a custom name for a timezone? I'm very unconvinced; it seems like extra complexity, extra checkboxes and fields, for very little gain and very, very few users. 

> Maybe we should rename "General" to something different so it'll stop asking to be the main tab?

A tab with just one element isn't great either way.

**Comment by kuzmas** [comment]
@jleclanche I feel it currently has pretty good balance on configurable / easy-to-use. Let's not remove features just because someone does not need them.
After all we can revive old simple clock plugin.

Closing this issue as configuration was rewritten.

**Comment by jleclanche** [comment]
Alright. Thanks!
