### ISSUE TITLE
Multilanguage and Input method support

### ISSUE THREAD

**Issue by peyoot** [lxde/lxqt#417]
I install lxqt on ubuntu 14.04 server and make language and input tool ready
```
#sudo apt-get install language-pack-zh-hans
#sudo apt-get install ttf-arphic-uming
#sudo apt-get install fcitx-table-wbpy
```

it simply can't work. we cant switch input method. and in the system configuration ,the input method item.  It seem input method configuration tool are not ready for this.

the font seems not work and the language for simplified chinese are not work as well. so when install a internet browser it gets out all block chars.

**Comment by jleclanche** [comment]
Dup of #26

**Comment by peyoot** [comment]
This problem is still there. In LXDE we don't encounter this problem. But lxqt 0.9. I still can't make it work.  My environment is ubuntu server 14.04, 
sudo add-apt-repository -y ppa:lubuntu-dev/lubuntu-daily
sudo apt-get update
sudo apt-get install lxqt-metapackage openbox
sudo apt-get install language-pack-zh-hans
sudo apt-get install fonts-arphic-uming
sudo apt-get install fcitx-table-wbpy

OK, if you try to configure fcitx, it actually doesn't able to write to ~/.config/fcitx, In this file every lines are noted. So even CTRL+SPACE by default can't call out fcitx. There's no way to change input method

**Comment by sequoiar** [comment]
any update on fcitx ?

**Comment by PCMan** [comment]
if you're using ubuntu, try im-switch command.
