### ISSUE TITLE
application menu sometimes not working after reboot 

### ISSUE THREAD

**Issue by pertplus** [lxde/lxqt#419]
After reboot if I left click the application menu, no menu comes up. I can still right click it and move/disable, and even if I disable/enable or add a second menu widget, left clicking on them has no effect. The only way to fix seems to be to reboot again or logout/login, and sometimes it doesnt work. I am on arch linux

**Comment by doktor5000** [comment]
If the menu would not open at all (never), it might be an issue with underlying menu-cache-gen. But as it only seems to happen intermittently, that's probably not the case. To see if the menu cache generation works, run the following command to see if e.g. it segfaults or crashes:

```LC_ALL=C G_MESSAGES_DEBUG=all /usr/libexec/menu-cache/menu-cache-gen -v -i /etc/xdg/menus/lxde-applications.menu -o /dev/null```

**Comment by pertplus** [comment]
with latest version issue hasnt happened again

**Comment by pietrondo** [comment]
same problem..

**Comment by pmattern** [comment]
@pietrondo 
You always have to let us know which OS you're running and how LXQt was installed.

**Comment by ArthurBorsboom** [comment]
I have the same issue with Lxqt 0.10/0.11 on Arch.
Also right-click on the applications in the taskbar gives me a white (empty?) menu.

I have noticed that if I kill lxqt-panel and restart it, everything works again.

So, the issue seems to be only after a reboot.

**Comment by pmattern** [comment]
@ArthurBorsboom 
Any chance you can try and verify this on a system running all LXQt components from latest VCS checkouts? Plenty of changes have been taking place since release 0.10.

**Comment by ArthurBorsboom** [comment]
I have been replacing so many objects lxqt and non lxqt, that the issue has been resolved. Unfortunately I am not sure what the solution was, so I guess we can close this issue until it happens again. Then I will perform a better debugging session.

**Comment by pmattern** [comment]
@ArthurBorsboom 
Alright then and thanks for helping improve LXQt. We can handle this as you proposed (except we don't need to close this issue which is already closed :blush: ).
