### ISSUE TITLE
Lid watcher: Disable by default

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#42]
This has to be double-checked but I believe it is usually handled by the kernel.

**Comment by paulolieuthier** [comment]
When I reopen the lid on my laptop I see SDDM's login form :disappointed:. Regarding the discussion, I agree with @surlykke. We should initially disable systemd's lid watching (and perhaps UPower's as well) and handle it ourselves.

As @surlykke said, logind has a dbus interface which we can use to set this behaviour. UPower has a dbus interface that can be used to get the state of the lid, but it doesn't have methods for setting the desired behaviour.

Perhaps a systemd-only approach is enough, for that reason and also [others](http://lists.freedesktop.org/archives/devkit-devel/2014-March/001575.html).

**Comment by paulolieuthier** [comment]
My notes:
*I didn't see @surlykke's commit 87eb88bfddd8f4c4d64906b5b8fd48dd9181ed1b that tells systemd not to handle the lid close event.
* The only way to change UPower's setting is editing the file `/etc/UPower/UPower.conf` and modifing the line where there is `IgnoreLid=false`.
* UPower has [recently](http://cgit.freedesktop.org/upower/commit/?id=0010e9325110e5a70a0d2381c84f88e7fb044ce4) removed the signal used to detect the lid close event, in favor of the "PropertiesChanged signals (on the daemon side) and notify signals (on the client side)", which I can't find. So in my system both [attempts to connect to UPower through DBus](https://github.com/lxde/lxqt-powermanagement/blob/master/src/lid.cpp#L41) fail.
* Recently, KDE's PowerDevil [has gained](https://quickgit.kde.org/?p=powerdevil.git&a=commitdiff&h=b5a1e1bec3052460ff8c87764a065cc61cdeba47&hp=ffe4d5f6a6f83138577a52fc6af924ba4a9d9d6b) the ability to notify lid closing/opening. That looks very promising. However, PowerDevil has an awful lot of [dependencies](https://quickgit.kde.org/?p=powerdevil.git&a=blob&h=ce13aa353345643a8961269aca0def43138ba415&hb=c8ec91a8097d676f9a35e18431b1a212359aeffe&f=CMakeLists.txt).

**Comment by paulolieuthier** [comment]
Sorry for the noise here. The Lid watcher **is working** on my system, even though I **still can't** find org.freedesktop.UPower's PropertiesChanged signal in DBus. @nesnera what version of LXQt are you using (if still)? How did you install it? I'm not sure how the last stable version is handling it, as I'm getting LXQt directly from git's master.

@jleclanche I'm not sure I agree that we should disable the lid watcher. I agree with @surlykke. Do you still think the same?

**Comment by jleclanche** [comment]
I'll give it a test on my laptop and think about it.

**Comment by stalkerg** [comment]
Not working for me  :( 
OpenRC (without systemd)+last UPower

**Comment by paulolieuthier** [comment]
Let's close this, the lid watcher is fine. @stalkerg, please open a new issue describing your problem.
