### ISSUE TITLE
 cannot add applications to quick launch

### ISSUE THREAD

**Issue by hifi25nl** [lxde/lxqt#420]
I cannot add applications to quick launch at the bottom bar. Is this a known bug?

**Comment by jleclanche** [comment]
Can you try again in master? There were issues fixed somewhat recently regarding this.

**Comment by hifi25nl** [comment]
I am using archlinux lxqt stable AUR  package. Should I switch to lxqt-panel-git (and  lxqt-desktop-git)?

**Comment by jleclanche** [comment]
Don't bother - if you are using stable then this was fixed a while back. Thanks.
