### ISSUE TITLE
RTL layout support

### ISSUE THREAD

**Issue by SafaAlfulaij** [lxde/lxqt#421]
LxQt should reverse it's layout if it's locale is a RTL locale. I tested some of the configuration applications with the --reverse option and didn't see any problem.
I think that the panel will take some time.
Hope it got fixed in 1.0 :)

**Comment by PCMan** [comment]
@SafaAlfulaij would you please be more specific and list apps that have RTL problems?
Thanks!

**Comment by SafaAlfulaij** [comment]
All the lxQt apps Non of them reverse because of this https://bugreports.qt.io/browse/QTBUG-43447
The panel also doesn't reverse even If I used the --reverse option, Just the widgets themselves (The apps menu for example) switch the icons with the text. I think the panel isn't affected that much with the bug :)

**Comment by tsujan** [comment]
Since QTBUG-43447 is fixed in Qt-5.6, we can close this.

**Comment by SafaAlfulaij** [comment]
Application layout mirroring got solved in Qt5.6, yes.
But the panel stll have some problems with RTL.
First of all, the paint order of the widgets is still from the left.
The applications in the task bar aren't aligned to right as well (The order of the widgets are changed manually).
![Screenshot](http://i.imgur.com/16ZJMao.png)
You can see also that "Pager" pages aren't reorderd as well.
New widgets are created to the right while they should be created to the left.

**Comment by palinek** [comment]
@SafaAlfulaij can you, please, test with the lxde/liblxqt#96

The pager should be fixed by that, e.g.:
![screenshot](https://cloud.githubusercontent.com/assets/10990929/16283090/a451aa96-38cb-11e6-8b7b-b37c7cc55d67.png)

**Comment by SafaAlfulaij** [comment]
@palinek Yes, the pager pages and the alignment of applications in the task bar got fixed!
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/16283368/25562546-38d5-11e6-9f83-5b102df0a2b5.png)
Others still need work...

**Comment by palinek** [comment]
Note that now moving buttons/windows in task manager is broken for RTL :(

**Comment by tsujan** [comment]
@SafaAlfulaij Numbers (and all mathematical expressions) are written from left to right in RTL writing systems. Why the pager direction should be reversed with RTL? I understand that the order of widgets and taskbar alignment should be RTL, but why pager?

**Comment by palinek** [comment]
> Note that now moving buttons/windows in task manager is broken for RTL :(

This should now be fixed by lxde/lxqt-panel@86be1eac43a0ae1c1660ec5d5dac2ad0b40cc976

**Comment by palinek** [comment]
@SafaAlfulaij please, next testing with lxde/lxqt-panel#356 will be appreciated (this should reorder the plugins correctly in RTL)

**Comment by palinek** [comment]
> Why the pager direction should be reversed with RTL?

I don't know. If window managers behave like that in RTL locale (desktop1 is on the rithgt of destkop2...), then we should show it that way... but didn't test that. @SafaAlfulaij Can you check it?

**Comment by SafaAlfulaij** [comment]
Great!
First the moving of windows: Now I can't move any window (or I don't know how it is supposed to be moved).

Then the widgets. Widgets got reordered, but some problems came up:
1. I added a Color Picker, But it didn't shaw/paint. Hovering over that space changes the cursor shape and right clicking the place supposed to be a lineedit opens the lineedit context menu. Clicking the button swich the cursor to the pick sign. (Same behaviour goes with other widgets)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/16287528/94521466-38ec-11e6-9398-60c4341b1644.png)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/16287568/e3618762-38ec-11e6-8149-8ff663cef60a.png)

2. Right clicking anything on the panel gets the context menu up the screen. Minimizing or maximizing windows shows the effect that the panel is on top of the screen and not the bottom of it.
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/16287569/e6f631de-38ec-11e6-96f9-ac4852e69320.png)
_I have one panel only_

Will get back later for Pager..

**Comment by palinek** [comment]
> 1. I added a Color Picker, But it didn't shaw/paint. Hovering over that space changes the cursor shape and right clicking the place supposed to be a lineedit opens the lineedit context menu. Clicking the button swich the cursor to the pick sign. (Same behaviour goes with other widgets)

I do not observe such weird behaviour...

**Comment by SafaAlfulaij** [comment]
> I do not observe such weird behaviour...

I do. And this behaviour didn't change even after restarting the machine several times.

@tsujan :
About Pager. Well, yes. Numbers are written from left to right. But here it's not the numbers, but the buttons (or some sort of tabs). It's odd if the first button is on the left while the overall layout is RTL. Also the pager can show the desktop name rather than it's index/number, and displaying the first page is on the left side is not a beautiful thing at all.
I'll test the window manager and come back.

**Comment by tsujan** [comment]
@SafaAlfulaij 
OK, but is desktop2 really on the left of desktop1 with kwin, for example, when RTL is chosen?

**Comment by SafaAlfulaij** [comment]
@tsujan Don't get it wrong, but the answer currently is no (KWin). Desktop 2 is on the right of 1. But! Migrating from Qt4 to Qt5 caused some problems with layout stuff. I'll check KDE4 first!

**Comment by SafaAlfulaij** [comment]
So I checked KDE4, and that's a **no** as well. In this case, we should leave only the Pager untouched while others are mirrored.
Thanks!

**Comment by SafaAlfulaij** [comment]
My configuration was a miss. Everything works as it should now!
Thank you all! :)

**Comment by palinek** [comment]
> My configuration was a miss. Everything works as it should now!

Please, tell us more... what was wrong?

**Comment by palinek** [comment]
After a talk with @mgraesslin ... the spec gives the pager option to configure the desktop layout: https://standards.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472688048

With the (updated) lxde/lxqt-panel#356 the navigation around desktop (left/right/up/down) works correctly in openbox. Kwin does not support it, though.

**Comment by palinek** [comment]
Is there anyone who can test all the PRs and confirm if it's working? (I've made all the test just with the `--reverse` option)

Or should I merge them and let all the comunity test?

**Comment by tsujan** [comment]
@palinek 
Testing with `--reverse` should be enough and you could merge them, IMO.

**Comment by paulolieuthier** [comment]
Agreed.

**Comment by paulolieuthier** [comment]
@palinek: just tested it. There is only a problem with plugins overlapping the left adjacent ones (this is easy too notice when using Light theme, which has handles).

![screenshot_20160628_082605](https://cloud.githubusercontent.com/assets/1238157/16413707/fc38089e-3d09-11e6-8d98-bec97cd67947.png)

**Comment by palinek** [comment]
>  There is only a problem with plugins overlapping the left adjacent ones (this is easy too notice when using Light theme, which has handles).

fixed in lxde/lxqt-common@4181c11

**Comment by paulolieuthier** [comment]
Awesome.

**Comment by palinek** [comment]
everything merged, are we closing this?

**Comment by paulolieuthier** [comment]
Yes, do it.
