### ISSUE TITLE
lxqt-config: Monitor Settings shouldn't save settings that haven't been applied yet

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#423]
Monitor Settings silently save settings that haven't been applied yet and thus aren't known to work.
This may cause problems such as blank screens the next time a session is started.

Personally, I think best solution would be to have a dialogue window ask the user whether he's sure about saving this kind of setting and that might offer a switch to apply settings first.

For the record this issue came up while discussing #191 which was actually covering something different and hence got closed.

**Comment by selairi** [comment]
> Personally, I think best solution would be to have a dialog window ask 
> the user whether he's sure about saving this kind of setting and that 
> might offer a switch to apply settings first.
>
>

This is logic. I am going to implement that feature.

**Comment by selairi** [comment]
> Personally, I think best solution would be to have a dialog window ask 
> the user whether he's sure about saving this kind of setting and that 
> might offer a switch to apply settings first.
>
>

I have just implemented a simple dialog before saving. Check it, please.

**Comment by pmattern** [comment]
Actually everything works as expected. Some suggestions:

I think the message should say 'saving' instead of 'to save' , but I'm not a native speaker either.

The new dialogue window *always* pops up if "Save" is clicked, hence also if the settings to save are known to work. This isn't desirable, imo.
But neither do I know the effort needed to implement a solution nor am I completely sure which was the best way to go.
First I thought it would be nice if Monitor Settings had some kind of per session list comprising all settings that have been confirmed to work (a list like this should never be kept permanently as users may plug their devices to different monitors, imo). All settings on a list like this could then be saved without confirmation. But maybe it was both sufficient as well and way easier to implement if the confirmation dialogue upon saving was only omitted if the setting currently in use is about to be saved which obviously has already been confirmed to work, too.

Implementing the latter could also be useful to stop something else I stumbled upon: "Apply" brings up its dialogue window also if no changes have been made since the last time a setting was confirmed as "OK" which doesn't make perfect sense. Maybe it could be shown grayed as long as nothing has changed.

Aside from this there's another minor improvement unrelated to this issue that I'd like to suggest briefly: imo it would be better and more intuitive if the order of the buttons at the bottom was Apply - Save - Close (l --> r).

**Comment by jleclanche** [comment]
This isnt highly important, dropping off the 0.9 milestone.

**Comment by selairi** [comment]
Hi,

> Aside from this there's another minor improvement unrelated to this issue
> that I'd like to suggest briefly: imo it would be better and more intuitive
> if the order of the buttons at the bottom was Apply - Save - Close (l -->
> r).

It seems correct. I will implement it.

> I think the message should say 'saving' instead of 'to save' , but I'm not a
> native speaker either.

Upps. Sorry.

> First I thought it would be nice if Monitor Settings had some kind of per
> session list comprising all settings that have been confirmed to work (a
> list like this should never be kept permanently as users may plug their
> devices to different monitors, imo). All settings on a list like this could
> then be saved without confirmation.

I think that it is a good idea. But I need some time to implement it.

Thanks

**Comment by pmattern** [comment]
@selairi 
Just FYI / in case you didn't take note yet: this issue probably should be postponed, see https://github.com/lxde/lxqt/issues/502.

**Comment by palinek** [comment]
Shouldn't we close this as in the 0.10.0 there will be the new `libkscreen` lxqt-config-monitor?

**Comment by paulolieuthier** [comment]
Yes.
