### ISSUE TITLE
pulseaudio mixer goes over 100% even when unchecked

### ISSUE THREAD

**Issue by elmo-on-github** [lxde/lxqt#427]
Hi, I'm a new LXQT user on Arch Linux and I have a problem. Whenever I change the volume, if it is at 100% it can even go over 100% even when unchecked.

Kernel: 3.17.6-1-ARCH 

EDIT: using pulseaudio this bug happens, on alsa it goes up to 100% and doesn't go over, but I want the problem to be fixed for pulseaudio.

**Comment by paulolieuthier** [comment]
Closing as duplicate of lxde/lxqt#252.
