### ISSUE TITLE
LIB_SUFFIX vs CMAKE_INSTALL_LIBDIR usage in lxqt-panel

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#428]
Why are we using `LIB_SUFFIX` in lxqt-panel? Can we safely switch to `CMAKE_INSTALL_LIBDIR`?

**Comment by jleclanche** [comment]
@luis-pereira @paulolieuthier thoughts!

**Comment by paulolieuthier** [comment]
I'll fix it.
