### ISSUE TITLE
lxqt-panel reboot / shutdown error

### ISSUE THREAD

**Issue by rcmn** [lxde/lxqt#430]
Had the exact same issue with an old install ubuntu 14.04, it appeared after an update about 2 weeks ago. So i decided to reinstall with mini.iso 14.10 thinking it was the fault of a dirty old install.But the issue persisted.

If I try to logout or shutdown here the message given by lxqt-panel

Error with Reboot:

lxqt-panel
Power Manager Error (D-BUS Call) org.freedesktop.DBus.Err Rejected send message, 2 matched rules; type="method_call",sender=":1.38" (uid=1000 pid=1871 comm="lxqt-panel") interface="org.freedesktop.DBus.Err" member="Reboot" error name="(unset)"

Error with shutdown:

lxqt-panel
Power Manager Error (D-BUS Call) org.freedesktop.DBus.Err Rejected send message, 2 matched rules; type="method_call",sender=":1.38" (uid=1000 pid=1871 comm="lxqt-panel") interface="org.freedesktop.DBus.Err" member="PowerOff" error name="(unset)"

**Comment by hossni** [comment]
http://www5.0zz0.com/2015/01/11/00/522855827.png

**Comment by rcmn** [comment]
yes that's the one !

**Comment by hterh** [comment]
Same problem with LXQt installed on Xubuntu 15.04 Vivid Vervet.
Logout functions OK after which reboot is possible.
![screenshot - 11-01-15 - 17-49-05-select](https://cloud.githubusercontent.com/assets/9549846/5696016/2292e776-99bd-11e4-8094-a28e35f67b31.png)

**Comment by ilag11111** [comment]
[This commit](https://github.com/lxde/liblxqt/commit/34232018eb532b7e1d06ce155faaa4fd618aa7d0) in liblxqt changes the commands used by the shutdown and reboot buttons to ones only present in new enough versions of ConsoleKit2, versions newer than Ubuntu 14.04 provides [and probably 14.10 based on rcmn's comment].  According to [ConsoleKit2's Documentation](https://consolekit2.github.io/ConsoleKit2/), the older commands from ConsoleKit1 are not deprecated, so I don't understand the reason for this compatibility-breaking change.

Reverting commit 34232018eb532b7e1d06ce155faaa4fd618aa7d0 in liblxqt should restore the old functionality, but at the expense of the suspend and hibernate buttons (which won't work with ConsoleKit1 anyway).  A more ideal fix would detect which version of ConsoleKit is present on the installed system and use the proper commands, and use Upower for suspend and hibernate if ConsoleKit2 is not present.

**Comment by surlykke** [comment]
2015-01-11 18:17 GMT+01:00 ilag11111 <notifications@github.com>:

> This commit
> <https://github.com/lxde/liblxqt/commit/34232018eb532b7e1d06ce155faaa4fd618aa7d0>
> in liblxqt changes the commands used by the shutdown and reboot buttons to
> ones only present in new enough versions of ConsoleKit2, versions newer
> than Ubuntu 14.04 provides [and probably 14.10 based on rcmn's comment].
> According to ConsoleKit2's Documentation
> <https://consolekit2.github.io/ConsoleKit2/>, the older commands from
> ConsoleKit1 are not deprecated, so I don't understand the reason for this
> compatibility-breaking change.
>
> Reverting commit 34232018eb532b7e1d06ce155faaa4fd618aa7d0 in liblxqt
> should restore the old functionality, but at the expense of the suspend and
> hibernate buttons (which won't work with ConsoleKit1 anyway). A more ideal
> fix would detect which version of ConsoleKit is present on the installed
> system and use the proper commands, and use Upower for suspend and
> hibernate if ConsoleKit2 is not present.
>

Sorry, my bad. I hadn't realized that my version of consolekit was not
backwards compatible. I'll fix asap.

- Chr.

**Comment by surlykke** [comment]
Reverted commit. Will come up with something better.
