### ISSUE TITLE
Allow icons in "add panel widgets" dialog

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#432]
cc @intialonso as we will need actual icons for them. I'm not sure if it's best to allow theme icons or to ship our own (or both).

**Comment by intialonso** [comment]
Let the icon theme set them, I we put our own we can run into readability, overall style and palette problems. 

For example, if the user set a system icon theme (say Oxigen) our icons could look out of place.

**Comment by jleclanche** [comment]
Yay we did it
