### ISSUE TITLE
Usage of modern C++11 features

### ISSUE THREAD

**Issue by paulolieuthier** [lxde/lxqt#434]
I've been thinking on this topic for some time now, and I see a lot of places in our code where using **lambdas**, **nullptr** and **smart pointers**, for example, would simplify it and make it more understandable (I'm specially talking about lambdas and nullptr, as Qt offers smart pointers). There is a [simple list](http://www.codeproject.com/Articles/570638/Ten-Cplusplus-Features-Every-Cplusplus-Developer) with these and other features from C++11 (std::move looks great as well).

The discussion here is whether it would be a problem to use those features in our codebase. If we can use it, I'd like to start using it straight a way.

**Comment by jleclanche** [comment]
Well not for 0.9 anyway. But I don't think we can start discussing this until we at least have a proper overview of which compilers we need to support on which distros.

**Comment by PCMan** [comment]
I'd like to use C++ 11, too. Nevertheless, it might not be the right time to introduce this change.
I'd say it's better to make our code base more stable and feature complete.
Full migration to Qt5, especially using new signal/slot syntax, might be done first.
Later, when toolchain support for C++11 is more complete, we can start use it.
Currently, gcc only has partial C++11 support and its STL implementation is incomplete.
LLVM clang and libc++ do this better, but they're less popular among Linux distros.
It's something good to have, but should not have high priority IMHO.

**Comment by paulolieuthier** [comment]
I didn't know that.

**Comment by ypnos** [comment]
I worked with C++11 features recently with GCC and I think the support is pretty good. There is nothing I missed so far (using gcc 4.9) and the features I used so far really help the code readibility a lot. That is: lambdas, nullptr, shared ptrs, auto, move-constructor, delegating constructors, foreach, some new std functionality (e.g. std::stoul).

**Comment by paulolieuthier** [comment]
There is also exceptions.

**Comment by paulolieuthier** [comment]
By "exceptions" here I meant **try-catch** blocks, which are awesome IMO. After some time I realized the ambiguity here :D.

**Comment by PCMan** [comment]
Gcc does not have complete C++11 support.
However, after some surveys, it seems that the most frequently used features are supported.
Since clang also has good C++ 11 support, I guess it's safe to use it.
Maybe it's a good idea to introducing C++11 gradually after 0.9 release?

**Comment by paulolieuthier** [comment]
>  Maybe it's a good idea to introducing C++11 gradually after 0.9 release?

Yeah, that's my idea.

**Comment by heliocastro** [comment]
For the current version matrix:

https://gcc.gnu.org/gcc-4.8/cxx0x_status.html - Fully supported
https://gcc.gnu.org/gcc-4.7/cxx0x_status.html - Partially supported

In the case of BSD like releases, if are versions changed to clang/llvm,
then is fully supported

So is safe to go with gradual introduction but even on 0.9 will be fine.

Btw, i will try compile with clang on Linux today to see how the status of
0.9.

**Comment by paulolieuthier** [comment]
Now that we are sure we can use C++11 features and there is a [wiki page](https://github.com/lxde/lxqt/wiki/CPP11-usage-in-LXQt) about it, let's close this issue?

**Comment by paulolieuthier** [comment]
Closing.
