### ISSUE TITLE
Dropbox 3.0.3 icon in LXQt panel

### ISSUE THREAD

**Issue by vasa1** [lxde/lxqt#435]
I am not using LXQt currently but I want to ask people here whether they've experienced any problems with Dropbox 3.0.3 not displaying its icon correctly or even at all in the systray. 

It seems to be a problem across various Linux desktop environments. For example, https://plus.google.com/110771891366288664482/posts/e5oE2pQdgeG.

**Comment by hterh** [comment]
As I saw the dropbox icon was absent on Manjaro/LXQt with Nuovex T2Z icon-theme and possibly one more theme. However today there was a Manjaro system update which included latest version Dropbox 3.0.5. The icon has come back in the systray and it looks like this has been resolved now.

**Comment by hterh** [comment]
Dropbox icon still shown in all themes of Xubuntu/LXQt as well as Manjaro/LXQt so may no longer be an issue with dropbox 3.0.5.

**Comment by hterh** [comment]
In Xubuntu/LXQt there is no dropcox-icon in the systray after a reboot. After logout and change to Xfce DE the icon appears and stays when switching back to LXQt.

**Comment by jleclanche** [comment]
The dropbox icon is known to be problematic (upstream problem). In any case, we'll be removing xembed support next release most likely so this won't be a consideration anymore.

**Comment by hterh** [comment]
The dropbox icon is permanently shown again after the recent panel updates, both on Xubuntu/LXQt and Kubuntu/LXQt. Also the icon appearance responds to change in theme. Looks like this has been resolved.

**Comment by paulolieuthier** [comment]
Good news. @vasa1, can you confirm that?

**Comment by vasa1** [comment]
@paulolieuthier , as I mentioned in the first post, I'm currently not on LXQt. I'm using vanilla Lubuntu 14.04 LTS. I solved my problem by arranging the order in which Compton, Dropbox and tint2 loaded in the autostart. I also added "sleep" between each step and a final reload of tint2.

**Comment by paulolieuthier** [comment]
@vasa1 ok, thanks. Closing it then.
