### ISSUE TITLE
Hover issues on panel since recently

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#436]
The hover effects on the panel aren't right since my most recent rebuild (so could be a new commit within the last 2-3 weeks). I don't think it's a theme issue, it seems like the hover isn't being registered.

**Comment by PCMan** [comment]
I believe this one is also caused by regression bugs of Qt 5.4.
The same problem happens to all Qt 5 programs.
Choose any Qt5 program and try to open a popup menu by mouse click.
Then, click on an area "outside" the window.
The menu is closed, but all hover events of that window are not received.
Click on any place again, and hover effect in the theme becomes normal.

**Comment by PCMan** [comment]
Just reported the bug to Qt devs.
https://bugreports.qt.io/browse/QTBUG-44231

**Comment by PCMan** [comment]
@jleclanche @paulolieuthier It's a good idea to put a warning in our release note telling people not to use Qt 5.4 with LXQt. I really hate upstream bugs. :-(

**Comment by paulolieuthier** [comment]
@PCMan I believe that's something very close to what is happening to the main menu of lxqt-panel, as @agaida reported in #460.

About your idea, I totally agree. Qt 5.4 was a very poor quality release.

**Comment by pmattern** [comment]
Under certain conditions, panel items get only activated when clicked the second time which is a somehow related finding, I suppose.

Example of how to reproduce: open Application menu by clicking  - hover over one of the topics featuring a sub-menu, say "Accessories", next over one of the sub-menu's items, say "PCManFM" next somewhere outside Application menu, desktop or application, doesn't matter - click to close Applications menu - click on some panel element, e. g. Application menu's icon or some application in Task Manager. The latter will only work on second click.

**Comment by goetzc** [comment]
It seems this will be fixes in Qt 5.4.2.

**Comment by palinek** [comment]
@paulolieuthier can you, please, check if this issue persists wit QT 5.4.2 ?

**Comment by paulolieuthier** [comment]
I believe it was fixed.
