### ISSUE TITLE
new introduced lxqt-leave create clutter in MainMenu

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#437]
we have the old, static implementation - which works good
https://mediacru.sh/G/Gq7VIASDzDUS.png
and we have a new set of icons in Misc
https://mediacru.sh/A/AXBcum9ROycr.png

My suggestion is to improve the second - these are the menu entries that can be placed in the panel and drop the first.   @lstranger @pcman

**Comment by paulolieuthier** [comment]
The main menu offers those options on the bottom. Maybe it should get those

**Comment by paulolieuthier** [comment]
Sorry.

**Comment by dbluelle** [comment]
AFAIK there is no section for "leave session" in the freedesktop menu specs, so the entries
are put in the "other" category.
I'm not that familiar with the *.desktop file syntax, so is there possibility to make a .desktop entry not appear in the menu?

**Comment by jleclanche** [comment]
Yes, NoDisplay=true. We should add that and specifically look for desktop files with like X-LXQt-LeaveAction=true or something in the menu.

Can someone pick it up?

**Comment by PCMan** [comment]
Wouldn't it be better to just edit the menu file to add them? We can add
our own categories.
Btw, I'm not really a fan of adding desktop file for every item. We're
going to have a whisker menu in the future, but it might not need the
desktop files. That's the problem.
2015/1/17 上午3:28 於 "Jerome Leclanche" <notifications@github.com> 寫道：

**Comment by jleclanche** [comment]
That'd be fine as well.

We can review how we can do it better after 0.9 imo; it's too long a discussion to have right now I think.

**Comment by agaida** [comment]
hmm - i'm biased about the desktop files. I like them, one can simply place them on the desktop, add them to docks, into panels - and its standard

**Comment by dbluelle** [comment]
@PCMan do you think of editing lxmenu-data? 
Maybe something like a reworked version of this: https://github.com/lxde/lxmenu-data/pull/3 ?

**Comment by PCMan** [comment]
There might be some different solutions.
1. Add this to lxmenu-data and set OnlyShowIn=LXQt.
  Pros: very  easy
  Cons: add some unused stuff to lxde gtk+ version.

2. Copy lxmenu-data and put it into lxqt-common, so we can have a set of
lxqt-specific menu files.
  Pros: We can make the menu layout of lxqt different from that of lxde. So
we can use a layout similar to the original one in razor-qt. Besides, any
change to them do not affect lxde gtk+ versions or others who are using
lxmenu-data.
  Cons: Duplicated translation work.

3. Use "merge file" feature provided by xdg menu spec. Then we can add
items to the menu without touching the original menu files, but this is
more complicated.

**Comment by jleclanche** [comment]
If we add this stuff to lxmenu-data we will need a synchronous lxmenu-data release, correct?

**Comment by dbluelle** [comment]
I would vote for option 2.
With this we don't always have to look if any changes in lxqt menu break anything on lxde gtk.
As a bonus we get rid of the dependency on lxmenu-data (I'm always in favor of reducing dependencies)

**Comment by jleclanche** [comment]
I think I'd go with 2 (the translation issues can be sorted out with pootle) but it's too late for that to fix this issue in time for 0.9.

@PCMan @dbluelle thoughts on `X-LXQt-LeaveAction=shutdown` and such? This needs to be fixed asap, we're releasing this month.

**Comment by dbluelle** [comment]
With https://github.com/lxde/lxqt-session/pull/12 the entries are removed from the "other" section for now.
This probably has to be reverted if we decide to use option 2.
About X-LXQt-LeaveAction:
The lxqt-leave desktop files currently belong to the categories LXQt and X-leave, maybe that's enough.

**Comment by jleclanche** [comment]
Yeah I just noticed. I'm fine with it. Though X-Leave as a category is really weird.

**Comment by dbluelle** [comment]
Yeah, I'm still new to the desktop files stuff, so I don't know the proper naming conventions here.

**Comment by dbluelle** [comment]
What about this as option 4:
We just add lxqt-application.menu (a modified copy of lxde-application.menu) to lxmenu-data
and edit startlxqt to use "lxqt-"  as XDG_MENU_PREFIX.
With this we can make a menu specifically for LXQt that doesn't affect lxde 
and we don't have to take care of the translations.

**Comment by PCMan** [comment]
Sounds like a good idea.
But we have to document that lxqt-common depends on lxmenu-data.
So packagers can set the dependency correctly.

**Comment by mika-k** [comment]
I have been using patched lxmenu-data (named as lxqt-menu-data) and patched lxqt-common,
because I'd like to use LXDE and LXQt as completely different environments.
 This is a hybrid of options 2 and 4 above.
https://github.com/mika-k/wjn-overlay/blob/master/lxqt-base/lxqt-menu-data/lxqt-menu-data-9999.ebuild#L38-L41
https://github.com/mika-k/wjn-overlay/blob/master/lxqt-base/lxqt-menu-data/files/lxde-to-lxqt.patch
https://github.com/mika-k/wjn-overlay/blob/master/lxqt-base/lxqt-common/files/lxqt-common-9999-xdgmenuprefix.patch
(I'm installing to Gentoo.)

 By the way,
Simply copying (forking) lxmenu-data to (such as) lxqt-menu-data, 
we can diff, merge or rebase them.
So, it is easier to port translations, I think.

 Additionally,
lxmenu-data is documented as a component of LXDE (not LXQt).
Do you think it's a problem also?

**Comment by dbluelle** [comment]
I've just implemented "option 4" in my repo.
see :
https://github.com/dbluelle/lxqt-common/commit/e400c79738b7251526d5e5317926f30a70d61801
and 
https://github.com/dbluelle/lxqt-panel/commit/1f5a982d69eeed41ce50493db1fc72c26fe43d42

IMHO this seems to be best and easiest solution.
This still is dependant on lxmenu-data.

**Comment by jleclanche** [comment]
@dbluelle Are there tested PRs for this?

**Comment by dbluelle** [comment]
I've created the PRs and reverted the commit in https://github.com/lxde/lxqt-session/pull/12

**Comment by jleclanche** [comment]
Landed everything. Let's get testing.

**Comment by pmattern** [comment]
Err, right now (2015-01-25) it's like so:
Menu "X-Leave" as defined in lxqt-applications.menu relies on file lxde-leave.directory which doesn't exist (at least not in /usr/share/desktop-directories where it belongs). All files /usr/share/applications/*.desktop stating lxqt-leave in line "Exec" have NoDisplay set. All in all this yields an empty entry at the bottom of Application menu's top level with an empty sub-menu.
I was having a hard time trying to understand how that session stuff is about to be handled in the long run. But the current situation is hardly intended isn't it?

**Comment by jleclanche** [comment]
What needs to happen is in this comment: https://github.com/lxde/lxqt-session/pull/12#issuecomment-70705935

**Comment by jleclanche** [comment]
Ok, I see the issue.

**Comment by jleclanche** [comment]
I should not have merged the PR in lxqt-session. I have now reverted it. My apologies.

As you said, we're missing a .directory file (lxqt-leave.directory). Maybe it is best to actually make it lxde-leave.directory and ship it as part of lxmenu-data, even if lxde classic does not use it. I'll ping @LStranger.

**Comment by dbluelle** [comment]
Sorry, I forgot the lxqt-leave.directory file.
Maybe it's better to add that to lxqt-common, otherwise everyone needs to also update lxmenu-data.

**Comment by jleclanche** [comment]
Yes, but requiring an lxmenu-data update is OK.

**Comment by paulolieuthier** [comment]
It's all working very here now, after having updated everything. Except for that:

![screen](https://cloud.githubusercontent.com/assets/1238157/5901071/24d0f95a-a54e-11e4-9854-c8053e5c8444.jpg)

**Comment by paulolieuthier** [comment]
Bug here: lxde/lxqt#454.

**Comment by pmattern** [comment]
@paulolieuthier 
You're probably missing /usr/share/desktop-directories/lxde-leave.directory as it didn't make it into one of the official repos yet.
See the comments above.

**Comment by paulolieuthier** [comment]
We should land `lxde-leave.directory` in lxqt-common, now `lxqt-applications.menu` is already there, right? But wouldn't that also mean we must ship all menu-related files in lxqt-common? How should we do it?

**Comment by pmattern** [comment]
@paulolieuthier 
I've been discussing something similar with jleclanche on freenode yesterday evening (about 21:35 UTC). He said he'd prefer to have all files *.directory in lxmenu-data so as only one set of these has to be maintained, in particular with regards to translations.

**Comment by paulolieuthier** [comment]
Oh, that's definitely right. I hadn't think of that. I'll wait until @dbluelle files his PR.

**Comment by dbluelle** [comment]
hmm, as @jleclanche pointed out here https://github.com/lxde/lxmenu-data/pull/3#issuecomment-62356959 , lxmenu-data should not contain lxqt-specific stuff, so I still think this should be put into lxqt-common.
It has to be freshly translated anyway, so this also can be done using the lxqt translation techniques.
And with this approach we're independent of lxmenu-data releases.

**Comment by paulolieuthier** [comment]
@dbluelle yes, that's what we discussed. I meant a new PR to add the new file to lxqt-common. Do you want to do it?

**Comment by jleclanche** [comment]
I was saying on IRC that I actually think it's fine to add the lxqt-leave.directory file to lxmenu-data.

For 0.9 I'm guessing this won't happen, so let's just add it to lxqt-common temporarily and I'll keep pinging to see if we can get it to lxmenu-data.

**Comment by dbluelle** [comment]
PR is available: https://github.com/lxde/lxqt-common/pull/15

**Comment by urbanomad64** [comment]
Sorry to report this but after having updated to 0.9.0 on Manjaro today, I am having this no Leave menu text issue. LXQt 0.9.0, Kwin 5.2.0.1, openrc 0.13.9, eudev 
![leavemenu](https://cloud.githubusercontent.com/assets/1598573/6109410/ec91b9e8-b07a-11e4-9568-f21cebd2255f.png)

**Comment by paulolieuthier** [comment]
@urbanomad64 you have to update lxqt-common.

**Comment by heliocastro** [comment]
Still, lxqt-common tarball is missing the latest commits, that
includes lxqt-leave.directory and start-here-lxqt.svg

**Comment by jleclanche** [comment]
Looks like the exact same issue that hit lxqt-qtplugin is hitting lxqt-common.

This isn't as critical though as it doesn't prevent compiling so we'll do a 0.9.1 in a day or two.

**Comment by heliocastro** [comment]
Agreed. Packages can cut the corners to survive :-)

**Comment by doktor5000** [comment]
Not sure if to report this here, but it probably fits: lxqt-common 0.9.1 will install lxqt-applications.menu into the wrong directory, which leads to all the entries intended to be shown in "Leave" submenu ending up in "Misc".

lxqt-applications.menu is installed to /etc/menus but should go to /etc/xdg/menus/lxqt-applications.menu.
After manually copying to /etc/xdg/menus/ menu will show just fine:
![bildschirmfoto2_139](https://cloud.githubusercontent.com/assets/7667040/6427697/93c0caf8-bf88-11e4-967e-0c9b811924d6.png)
