### ISSUE TITLE
application shortcut ctrl-d not working

### ISSUE THREAD

**Issue by cyberbeat** [lxde/lxqt#438]
I have above problem with hotkeys. for example kdevelop uses the shortcut ctrl-d for toggling comments. but this does not work in lxqt-0.8. in lxqt hotkey-configuration there is not other shortcut defined for that key-combination

**Comment by paulolieuthier** [comment]
By lxqt 0.8 you mean your not using current git's current master, correct? Have you tried with it? Well, Ctrl+D always worked for me on KDevelop.
