### ISSUE TITLE
Idle -> Enable Idleness Watcher when disabled doesn't disable until logout

### ISSUE THREAD

**Issue by urbanomad64** [lxde/lxqt#440]
LXQt System Settings -> Powermanagement Configuration -> Idle

When I activate idleness to suspend or hibernate after x time, it all works flawlessly and immediately but when I want to deactivate it to watch a film or something then it doesn't deactivate until logout. Is that something that can be fixed?

My configuration: Manjaro 0.8.11, LXQt + Kwin + Openrc +eudev, Kernel 3.18.2

**Comment by surlykke** [comment]
2015-01-18 17:34 GMT+01:00 Sean Sloane <notifications@github.com>:

> LXQt System Settings -> Powermanagement Configuration -> Idle
>
> When I activate idleness to suspend or hibernate after x time, it all
> works flawlessly and immediately but when I want to deactivate it to watch
> a film or something then it doesn't deactivate until logout. Is that
> something that can be fixed?
>
>
I believe this to be caused by #441
