### ISSUE TITLE
lxqt-panel reads panel.conf repeatedly for 10 times during startup.

### ISSUE THREAD

**Issue by PCMan** [lxde/lxqt#443]
Every lxqt-panel plugin creates its own new instance of LXQt::Setting object for panel.conf.
So we did parsing and file-alteration monitoring of the same config file for more than 10 times.
Actually, they should share the object instance from LxQtPanelApplication.
This slows down startup, increases memory usage, causes potential inconsistency between config values, and consume unnecessary system resources monitoring the config file for many times.

**Comment by PCMan** [comment]
@paulolieuthier , @luis-pereira , @jleclanche , @kuzmas any thoughts?
I found this bug while trying to fix the broken filesystem watch in liblxqt.
The same fileChange() slot is called more than 10 times during startup of lxqt-panel.

**Comment by kuzmas** [comment]
@PCMan Without looking at the code I suspect that some plugins are modifying their settings (most probably to the same values) during loading. We should:
1. make sure plugins do not write when they are supposed only to read settings.
2. make sure values are not touched (and therefore fileChanged() is not emitted) when storing a value if the new value equals to the old one.
Either of solutions would help but IMO it's better to have both.

**Comment by PCMan** [comment]
@kuzmas Not really. Please see this:
https://github.com/lxde/lxqt-panel/blob/master/panel/plugin.cpp#L66
In Plugin::Plugin(), a new LXQt::Settings object is always created.
So there is one object per plugin, but actually they all belongs to the same config file.
Hence we have 10 or more duplicated objects which parse, load, and monitor the same file.

**Comment by PCMan** [comment]
OK, frequent writing of config files is another issue.
@kuzmas you're right. During startup, every plugin tries to write the config file.
This part really needs some re-design and cleanup. Any thoughts?

**Comment by kuzmas** [comment]
@PCMan In my opinion it's not a major issue to fix for 0.9. It does not cause a crash, memory leak or data loss. So I think it can wait for 1.0. If everybody else is busy, I could look at it.

**Comment by PCMan** [comment]
OK, cool!
I just think that it's easy to fix so we can do it before 0.9.
However, I read all of the related code yesterday and found that it
requires more redesign.
Let's move it to 1.0.

**Comment by paulolieuthier** [comment]
@PCMan making every plugin get the settings object from `reinterpret_cast<LxQtPanelApplication*>(qApp)->settings()` instead of creating new ones would solve it, right?

**Comment by paulolieuthier** [comment]
```diff
diff --git a/panel/plugin.cpp b/panel/plugin.cpp
index 87f9b40..aaea1de 100644
--- a/panel/plugin.cpp
+++ b/panel/plugin.cpp
@@ -29,6 +29,8 @@
 #include "plugin.h"
 #include "ilxqtpanelplugin.h"
 #include "lxqtpanel.h"
+#include "lxqtpanelapplication.h"
+
 #include <QDebug>
 #include <QProcessEnvironment>
 #include <QStringList>
@@ -73,8 +75,7 @@ Plugin::Plugin(const LxQt::PluginInfo &desktopFile, const QString &settingsFile,
     mSettingsGroup(settingsGroup),
     mPanel(panel)
 {
-
-    mSettings = new LxQt::Settings(settingsFile, QSettings::IniFormat, this);
+    mSettings = reinterpret_cast<LxQtPanelApplication*>(qApp)->settings();
     connect(mSettings, SIGNAL(settingsChanged()), this, SLOT(settingsChanged()));
     mSettings->beginGroup(settingsGroup);
 
@@ -148,6 +149,7 @@ Plugin::Plugin(const LxQt::PluginInfo &desktopFile, const QString &settingsFile,
         layout->addWidget(mPluginWidget, 0, 0);
     }
 
+    mSettings->endGroup();
     saveSettings();
 }
 
@@ -310,10 +312,11 @@ void Plugin::settingsChanged()
  ************************************************/
 void Plugin::saveSettings()
 {
+    mSettings->beginGroup(mSettingsGroup);
     mSettings->setValue("alignment", (mAlignment == AlignLeft) ? "Left" : "Right");
     mSettings->setValue("type", mDesktopFile.id());
     mSettings->sync();
-
+    mSettings->endGroup();
 }
```

**Comment by paulolieuthier** [comment]
@PCMan I'll be pushing the patch to our master as valgrind says it made the number of calls to `fileChanged()` 10 times less. That way more people can test it easier and sooner.

**Comment by paulolieuthier** [comment]
Actually, there is a problem with the patch. I haven't merged it. Every plugin treat the QSettings object as it was already defined to work on the plugin's setting group.

**Comment by paulolieuthier** [comment]
Also, if a plugin modifies a key, the QSettings object will emit fileChanged() and every plugin will read settings again. @PCMan does it have anything to do with your thinking that this needs redesign?

**Comment by PCMan** [comment]
AFAIK, there are some issues that needed to be considered.
1. Should we allow a plugin to use a separate config file other than
panel.conf? (If yes, then we should still support the old API that receives
a file name).
2. If someone calls beginGroup() on the shared settings object and does not
call endGroup(), then every plugin will fail to read their own config
values since they're now in the wrong group. If we share the settings
object among all plugins, then we need to make sure every pieces of code
using the Settings object, including third party plugins, call endGroup()
properly.
3. It's fine for every plugin to read the settings again since the settings
are in memory. With the fix, we only do the file I/O once.
4. Currently, lxqt-panel calculates MD5 hash values for every config
sections to detect changes, which is not useful. With the hash, you only
know that something in the section is changed, but you don't know which key
is changed. So we still need to read every keys/values and check them. In
addition, to calculate the MD5 sum, we read all of the config values and
concatenate them, which is even more expensive than just re-read every
config values.  So IMHO we should drop the MD5 stuff altogether.

**Comment by paulolieuthier** [comment]
1. That's a good question that brings other questions. What comes to my mind is "no". If a plugin really wants to use a separate config file, it will have to have its own QSetting object. Keeping the default configuration for the plugins in panel.conf is simpler, faster, and needs only one filesystem monitor. However, if a plugin changes settings, every plugin is notified. The other option that comes to my mind is to create a `panel.conf.d` folder. That would make a plugin be notified only when it's settings changes, for every plugin would have its config file. But now we have multiple filesystem monitors.

2. Yes, that's what I tried to describe before. We shouldn't rely on that.

4. I didn't know about that until recently. Totally agree with you.

**Comment by heliocastro** [comment]
For number 4, why not lxqt register a signal/slot mechanism that can be
called by Settings object ?
Can be a dbus call, a qt regular signal/slot, doesn't matter. ust kill the
polling.

**Comment by palinek** [comment]
I thik of solution where the plugin will not get the main ```QSettings``` object but just a new class (let's call it e.g. ```SettingsReader```) -> in constructor it stores it's ```section``` and will provide only ```value``` & ```setValue``` methods. In these it will:
- prepend the ```section``` into the key and call ```value``` or ```setValue``` of the underlying ```QSettings``` object
- or call ```beginGroup```,  ```value``` or ```setValue```, ```endGroup```

This wrapped read/write has little or no performace impact, because the ```value```/```setValue``` in ```QSettings``` are implemented in the same way.
``SettingsReader`` will also forward needed signals of the underlying object.
With this we can also simplify the "configuration settingsChanged" behavior and provide the signal only for particular plugin (not all of them).

**Comment by jleclanche** [comment]
> 2. If someone calls beginGroup() on the shared settings object and does not
call endGroup(), then every plugin will fail to read their own config
values since they're now in the wrong group. If we share the settings
object among all plugins, then we need to make sure every pieces of code
using the Settings object, including third party plugins, call endGroup()
properly.

This is a bit of a concern for third party plugins.

Would it be possible for the panel itself to read its plugins' config, and pass it to its plugins during their initialization?

**Comment by palinek** [comment]
> Would it be possible for the panel itself to read its plugins' config, and pass it to its plugins during their initialization?

@jleclanche my proposal will solve also this, not?

**Comment by paulolieuthier** [comment]
@palinek I had thought on something similar to that, and I think this is the way to go. But how the main QSettings object would tell the specific SettingsReader objects about the changes made only to the specific plugins' settings?

**Comment by palinek** [comment]
> But how the main QSettings object would tell the specific SettingsReader objects about the changes made only to the specific plugins' settings?

@paulolieuthier well ... that depends - should the plugin be notified if user change settings file directly? 
- If not, only the paritcular SettingsReader object will emit settingsChanged signal connected to particular plugin
- If yes, some work on LxQt::Setting is needed -> add other 2 signals, e.g. "settingsChangedByFile" & "settingsChangedByApp". SettingsReader will register itself for settingsChangedByFile and foward this to plugin. (logic from first branch remains the same)

**Comment by PCMan** [comment]
It might be better to just keep it simple and stupid.
After loading a plugin, the plugin should cache the config value it reads
from the settings object. After that, it should not touch the settings
object.
Monitor the changes of the config files in the panel.
If the config file is changed, just notify all plugins.
Every plugin compares the previously cached values with the current config
values and see if they are changed and update their UIs as needed.
When the config file needs to be saved, every plugin is given a pointer to
QSettings object and writes its cached config values to it.
In any other cases, the plugins should not access the settings object
directly.

**Comment by paulolieuthier** [comment]
@PCMan OK, but how to force the plugin to save to the right settings group?

**Comment by PCMan** [comment]
It seems to be easier to just prohibit them from touching the "group".
For example, if we have the following API.

Plugin::loadSettings(const LXQt::Settings& settings) {
  // read all config values, and cache them.
}

Plugin::saveSettings(LXQt::Settings& settings) {
  // write the current config values to settings.
}

Before calling loadSettings or saveSettings, we change to the group owned
by the plugin by calling beginGroup().
After that, we do endGroup() inside the code of the panel on behave of the
plugin.
Then the plugin does not need to know what the setting group is.
There is, however, an obvious problem.
The code used to load the config values in loadSettings() is duplicated
with that in settingsChanged() handler.
So it's better to merge them into something like reloadSettings(), I guess.
Since we can compare the new config values with the cached ones inside
reloadSettings,
we can know if the values are really changed and prevent unnecessary UI
updates.
Then the MD5 hash stuff can be dropped completely.
Not sure if there are better ways.

**Comment by paulolieuthier** [comment]
I would like to propose having a `panel.conf.d` folder in both `/etc/xdg/lxqt` and `~/.config/lxqt/`, with a config file for each plugin, and the main `panel.conf` file containing settings for the panel only. The reason is that I don't like idea of reloading every plugin because of a file change. We would still have multiple file monitors, though.

**Comment by paulolieuthier** [comment]
And the main settings object should not be available for the plugins, as can be easily done (see the patch above).
