### ISSUE TITLE
Segmentation Fault in Qt Apps

### ISSUE THREAD

**Issue by hawkeyed** [lxde/lxqt#444]
Hi, I had a problem after I had updated lxqt yesterday. I think it's caused because of lxqt-session. I installed lxqt with Ubuntu Trusty from lubuntu daily ppa. Whenever i open a qt app it crashes. Apps like smplayer, qstardict, qupzilla... Lxqt apps works fine. Then, i fixed the problem myself. I created xinitrc file and typed necessary things like lxqt-panel, the desktop, lxqt-runner. Everything except lxqt-session. Now, there isn't any segmentation error. But i couldnt figure out why. I hope you could solve it. Thank you for the great de.

**Comment by jleclanche** [comment]
Kinda sounds like an issue with your setup or libraries. I'd reinstall all of it if I were you. But ping @gilir just in case.

**Comment by PCMan** [comment]
I believe that you have to rebuild lxqt-qtplugin with Qt 5.4.

**Comment by ypnos** [comment]
I have this problem with every Qt update since Qt 5. You have to rebuild at least the plugin because it is not binary-compatible.
