### ISSUE TITLE
LXQt panel: desktop switcher should allow for more than a single line

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#449]
It should be possible to have Desktop switcher arrange the virtual desktops in more than one line only, much as it can be done by its counterparts in e. g. KDE or Xfce, imho.

Necessities like this probably are a matter of taste. But to me this is a show stopper preventing me from using LXQt on production systems.

**Comment by palinek** [comment]
Currently there is support to have desktops arranged in multiple rows. The rows count is deduced from from panel's configuration.

@jleclanche: Should that be changed (allow configuration for desktopswitch plugin)?

**Comment by pmattern** [comment]
Technically those apparent multiple rows seen in desktop switcher after setting panel's row number >1 seem to be just one row that gets wrapped.
At least keyboard shortcuts to switch to the virtual desktop on top/bottom of the current one, e. g. Ctrl+Alt+{Up,Down} using Openbox, and the likes don't work.

If panel features more than one row some panel plugins automatically get arranged on top of each other and not side by side only any more.
This shouldn't be associated inevitably with having more than a single row in desktop switcher.

Also waste of space can be a matter, see screenshot, taken on a system where both icon and font size make perfect sense as long panel is set to one row only.
![lxqt panel rows 1](https://cloud.githubusercontent.com/assets/9860801/6273973/0c443012-b874-11e4-8f22-6c488f1191f8.png)
Font isn't readable in task manger any more, some of the plugins arranged on top of each other are overlaying.

So all in all I still think there should be real rows in desktop switcher with a number configurable independently from the one of panel's rows.

**Comment by palinek** [comment]
For me this is reasonable... If owners agree with this (separate configuration of rows for desktopswitch), I can implement it.

**Comment by jleclanche** [comment]
@palinek Go ahead. But make sure to make it configurable.

**Comment by palinek** [comment]
@pmattern, @jleclanche implemented in lxde/lxqt-panel#141

**Comment by pmattern** [comment]
Issue got fixed by lxde/lxqt-panel#141. Closing.

**Comment by michaldybczak** [comment]
OK, I know that's not what the topic is about, but how do I set virtual desktops in lxqt? There's nothing in panel settings or anything in any settings about it. I set desktop switcher on the panel and it shows 1 and clicking on it brings nothing, There is no second desktop. How can I set it?
This is really frustrating. Can't find anything on google.

**Comment by jleclanche** [comment]
@michaldybczak Virtual desktops are usually handled by your window manager. If you're using openbox, try `obconf`.

**Comment by michaldybczak** [comment]
Thanks, got it. Forgot it's wm that controls it.

**Comment by mardy** [comment]
Is there a bug about the Up/down shortcuts not working?
