### ISSUE TITLE
Panel should not lose plugin configuration if the plugins are not found

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#451]
If lxqt-panel is started and some of the plugins the user added are missing, the plugins are permanently removed from the panel. This should not happen.

**Comment by palinek** [comment]
I've created PR #136 for a possible fix of this issue.

**Comment by paulolieuthier** [comment]
@jleclanche what do you mean by missing plugins? I want to reproduce it.

**Comment by jleclanche** [comment]
@paulolieuthier this happened to me by running a panel locally using the config of the systemwide panel. it didnt find any of the .so files.

**Comment by palinek** [comment]
@paulolieuthier it can also happen if the particular .desktop (describing the plugin) file is not found.

**Comment by palinek** [comment]
fixed in lxde/lxqt-panel#136
