### ISSUE TITLE
qterminal preferences does not save checkbox status

### ISSUE THREAD

**Issue by lula123** [lxde/lxqt#452]
Status of checkbox Actions -> Preferences -> Look and Feel -> Highligh(t) Current Terminal With Border is not saved. If you uncheck it, it is checked again after a restart of the program. I wasn't able to find any reference to the checkbox in .config/qterminal.org/qterminal.ini. As a side note: There's a "t" missing at the end of Highlight in the UI. 

Edit: Version 0.4.0, Mageia Cauldron

**Comment by pmattern** [comment]
QTerminal is the recommended terminal emulator in LXQt only. But its development takes place in an independent project.

You may want to file your issue on https://github.com/qterminal/qterminal/issues

**Comment by jleclanche** [comment]
Moved to https://github.com/qterminal/qterminal/issues/108
