### ISSUE TITLE
lxqt-appswitcher assertion

### ISSUE THREAD

**Issue by antis81** [lxde/lxqt#453]
On my system `lxqt-appswitcher` is not starting at all. Any hint on what's wrong?

Screenshots:
![lxqt-appswitcher-crash](https://cloud.githubusercontent.com/assets/440517/5897208/9a6a1ed8-a541-11e4-90c8-b14880ff2961.png)
![lxqt-appswitcher-crash-report](https://cloud.githubusercontent.com/assets/440517/5897210/9d9a7b02-a541-11e4-85bf-01261c036352.png)

**Comment by jleclanche** [comment]
lxqt-appswitcher is no longer supported. If you're on a WM which has built-in alt-tab functionality (which covers 99% of WMs), you won't need it anyway.

**Comment by antis81** [comment]
Thanks. I just removed it!
