### ISSUE TITLE
Menu entry for Leave not shown

### ISSUE THREAD

**Issue by hterh** [lxde/lxqt#454]
After latest update the description and icon for 'Leave' has disappeared. The submenu is still OK.
![screenshot-menu-leave-26-01-2015](https://cloud.githubusercontent.com/assets/9549846/5901309/d58e09fe-a571-11e4-8848-ed72acc21e17.png)

**Comment by pmattern** [comment]
@hterh 
You may want to look for a file /usr/share/desktop-directories/lxde-leave.directory. If it's missing, create it (root) with content
>[Desktop Entry]
>Name=Leave
>Comment=Leave Session
>Icon=system-shutdown
>Type=Directory
>
>Comment[de]=Sitzung verlassen
>Name[de]=Verlassen

If this fixes your problem then it's a know issue as this file is missing in the official repos atm due to some transition.

**Comment by hterh** [comment]
Thanks, that fixed it.
