### ISSUE TITLE
Setting desktop dir only applies to desktop manager.

### ISSUE THREAD

**Issue by PCMan** [lxde/lxqt#457]
Setting desktop dir path from the desktop preferences dialog only applies to the desktop manager.
Other places, such as libfm and the places view still use the old desktop path.
We need a mechanism to reload these paths.
@LStranger can libfm reload ~/.config/user-dirs.dirs when it's changed?
Do we need to do that? Or we can add an API to FmPath to reload the file manually?
glib provides g_reload_user_special_dirs_cache() since 2.22.

**Comment by paulolieuthier** [comment]
Fixed in 36cb841b6541bfa1683823128c2b75d4b1b5f87b.
