### ISSUE TITLE
[regression] Opening files using DnD is broken.

### ISSUE THREAD

**Issue by PCMan** [lxde/lxqt#458]
This is critical and needs to be fixed ASAP.
https://github.com/lxde/pcmanfm-qt/issues/100

**Comment by PCMan** [comment]
Just tested another Qt5 file manager "qtfm" and its DnD is broken, too.
So, it's obvious that this is not my bug.
@jleclanche I need some time to workaround this.
Once I confirm the cause of the bug, I need to give Qt developers yet another bug report.

**Comment by jleclanche** [comment]
Ok.

**Comment by PCMan** [comment]
All Dnd to other programs failed and this error message is shown in the console.
"QXcbDrag::handleFinished - drop data has expired"

**Comment by PCMan** [comment]
Bad news. It seems that cross-process DND is broken in Qt 5.4.
Even the Dnd example shipped with the Qt source code does not work.
I could not find any workarounds or create a fix after hacking for one day.
Well, I'm afraid that we need to release a DE without working DND this time.
Just list this one as a "known issue" in the release note.
I'll report this to Qt developers and link this issue to the Qt bug.

**Comment by jleclanche** [comment]
Sounds like something that could get fixed in a 5.4.x release, so that's ok.

The LXQt release is still delayed until the 4th or 5th, though, so keep bugfixing until then!

**Comment by paulolieuthier** [comment]
It could be helpful to know how the KDE guys are handling this.

**Comment by PCMan** [comment]
https://bugreports.qt.io/browse/QTBUG-44201

**Comment by heliocastro** [comment]
I will ask some people on out KDE internal irc.

[]'s

**Comment by PCMan** [comment]
It seems that KDE5 suffers from the same bug.
I just tested kate with Qt5. Dragging text from kate to other editors no longer works.
Only the error message: "QXcbDrag::handleFinished - drop data has expired" was shown in the console.
I'm not able to test KDE Dolphin since it's still in Qt 4.

**Comment by heliocastro** [comment]
This is a regression bug on Qt 5.4.0

Eike Hein, from KDE confirmed. Here's the bug entry and will be fixed on
5.4.1

https://bugreports.qt.io/browse/QTBUG-43436

**Comment by heliocastro** [comment]
More info, direct link for code review ( btw, i hate Gerrit interface )

https://codereview.qt-project.org/#/c/103056/

**Comment by PCMan** [comment]
Thank you for the info.
Let's wait for Qt 5.4.1 then.
Really glad to know it's not my bug. :-)

**Comment by PCMan** [comment]
We should add this to the release note of LXQt 0.9.
Since it's already fixed in upstream, I close this issue.
