### ISSUE TITLE
[regression] The newly added "Leave" menu has wrong position.

### ISSUE THREAD

**Issue by PCMan** [lxde/lxqt#459]
This is a usability regression bug noted after adding the "Leave" menu to lxqt-panel.
It never happened in the past. Please see the screenshot.
https://drive.google.com/file/d/0B4BhmC8V2mivQS10cE96cWEtTkk/view?usp=sharing

After login, when you open the main menu for the "first time", and move the cursor to the "Leave" menu, you can see this. When you switch to other submenu and go back, it becomes normal.
I can always reproduce this bug with the preceding steps. Confirmed on two desktop PC and one laptop all of which are running ArchLinux with Qt 5.4.

**Comment by paulolieuthier** [comment]
Can't reproduce it, running ArchLinux with Qt 5.4 as well.

**Comment by PCMan** [comment]
This only happens when you open the main menu for "the first time".

**Comment by jleclanche** [comment]
I can repro but have no idea why it happens.

**Comment by dbluelle** [comment]
I can reproduce it, too.
It even happens if I start lxqt-panel from a terminal.
It's not bound to the "leave" menu, it happens with the first menu you move the mouse to.
Every submenu seems to appear moved up by the same fixed amount of pixels

**Comment by dbluelle** [comment]
This fixes it for me, but maybe it doesn't work on older Qt versions or other WMs (I'm using OpenBox and Qt 5.4.0) :
```
--- a/plugin-mainmenu/lxqtmainmenu.cpp
+++ b/plugin-mainmenu/lxqtmainmenu.cpp
@@ -240,7 +240,7 @@ void LxQtMainMenu::showMenu()
 
     // Just using Qt`s activateWindow() won't work on some WMs like Kwin.
     // Solution is to execute menu 1ms later using timer
-    mButton.activateWindow();
+    //mButton.activateWindow();
     mMenu->exec(QPoint(x, y));
 }
 ```

**Comment by agaida** [comment]
its reproducable for the first time - but happend at some point again, stays normal, happend again and so on - can't see a pattern in the behaviour yet

**Comment by PCMan** [comment]
This bug is induced by 9eb97419255a60bfe2a855c5e6767050834fcc95 .
@paulolieuthier would you please take a look?

**Comment by PCMan** [comment]
@paulolieuthier  What's the problem this commit trying to fix?
https://github.com/lxde/lxqt-panel/commit/9eb97419255a60bfe2a855c5e6767050834fcc95

**Comment by jleclanche** [comment]
@PCMan it says it fixes #142 and #401.

**Comment by paulolieuthier** [comment]
@PCMan do you think I should revert it?

**Comment by PCMan** [comment]
@paulolieuthier maybe it's a good idea to revert it temporarily.
Not only the position of the menu is incorrect.
In dual monitor setup, the sub menu is shown on the other monitor, which is not acceptable.
We still have some time so let's come up with a better solution that works.
What do you think?

**Comment by paulolieuthier** [comment]
I'm trying to fix the other bugs without causing this one (and btw, I couldn't reproduce it yet). If I don't achieve it, I'll revert the commit.

**Comment by PCMan** [comment]
@paulolieuthier Do you have any progress so far?
Or you can leave this one to me.
I can 100% reproduce this bug here so testing and debugging might be easier.

**Comment by paulolieuthier** [comment]
@PCMan go ahead! :smile:

**Comment by PCMan** [comment]
OK, I take this one. :)

**Comment by PCMan** [comment]
Part of the problem is caused by the limitation of lxqt-globalkeys.
While the shortcut key is pressed, the current focused window still gets the key event and grab it sometimes. So our menu cannot get the keyboard focus and stop working.
Another possible mechanism I guess is when we're called by the global key daemon, our menu tries to grab the focus, but we failed because we don't have an activated window.
Or our menu can get the focus, but soon after this, the original target window of the key event also gets the event and grab it, so our focus is stolen.
Anyway, a useful quick hack is to delay the popup of the menu if it's triggered by Alt + F1 shortcut.
If we delay menu->exec() for about 500 ms, the problem disappears in most cases.
As we don't fix the real cause, this is only a hack and does not work reliably.
The number 500 ms is arbitrary but after some experiments it seems to work most of the time.
I'll try to create a PR based on this hack later.

**Comment by PCMan** [comment]
Delay the showing of the menu is bad for UX, but this is definitely better than having a broken menu.

**Comment by PCMan** [comment]
A new PR for it.
https://github.com/lxde/lxqt-panel/pull/131
@paulolieuthier please help review.
Thanks!
