### ISSUE TITLE
[regression] menu stays open in some cases

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#460]
* reproducable with Qt 5.4 and Qt 5.3.2 (arch and siduction)
* if the menu is open and one drag the mouse out of the menu (menuentry with submenu) the  menu remains open and disappears on first mouseclick out of the menu
* if the menu is leave via a menuentry without submenu (Screensaver) or one move the mouse from menu to the panel the menu remains open regardless on any clicks - going back over a menuentry with submenu, leave and click then - the menu disappears

sorry, could not describe it better

**Comment by paulolieuthier** [comment]
That was introduced in lxde/lxqt-panel@9eb97419255a60bfe2a855c5e6767050834fcc95 and I have no idea how not to trigger it and keep my fix. Maybe we should revert it. The panel is very buggy when it comes to focus/widget activation because of Qt 5 bugs.

**Comment by paulolieuthier** [comment]
Fixed in lxde/lxqt-panel#131.
