### ISSUE TITLE
Ok button not cliccable in file associations dialog

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#466]
Mostly the ok button is ready for click only after changing and selecting  one or more times other applications and then reselecting the first one.
![schermata02](https://cloud.githubusercontent.com/assets/10681413/5973510/a9d79a64-a869-11e4-847e-c3baa8aa9db6.png)

**Comment by jleclanche** [comment]
@luis-pereira can you take a look?

**Comment by luis-pereira** [comment]
@jleclanche sure.

**Comment by luis-pereira** [comment]
@stefonarch The Ok button isn't clickable because of ongoing backgound computing. Added a busy indicator to make the user aware of it. The first application is selected by default (if it exists).

The performance must be improved anyway, but IMO that's not critical to the 0.9 release.
Filled https://github.com/lxde/lxqt/issues/467

**Comment by stefonarch** [comment]
Upgraded lxqt-config and it works fine. You're fast, thank you!

Il 30/01/2015 18:32, Luís Pereira ha scritto:
> @stefonarch <https://github.com/stefonarch> The Ok button isn't
> clickable because of ongoing backgound computing. Added a busy indicator
> to make the user aware of it. The first application is selected by
> default (if it exists).
> 
> The performance must be improved anyway, but IMO that's not critical to
> the 0.9 release.
> Filled #467 <https://github.com/lxde/lxqt/issues/467>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/466#issuecomment-72238353>.
> 

-- 
********************************
Stef Binde
via della pieve 2
I-56024 Corazzano PI

Tel: ++39 0571 17 30 104
PGP: 0x728D9707

stef.binde@riseup.net
*******************************
