### ISSUE TITLE
Pcmanfm-git does not load italian translation

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#468]
First I thought it is not translated at all, but it seems that it does simply not respect the system language.
Lximage-qt-git does the same (it's not translated but does not use _it.qm file.)
Same on siduction in german: pcmanfm-qt_de.qm is present but not used.

**Comment by PCMan** [comment]
It works here. See the screenshot please.
https://drive.google.com/file/d/0B4BhmC8V2mivSWdwSmpuek8zaEk/view?usp=sharing
What's your locale setting and which git version are you using?
Are you using a patched version from your distro?
I fixed a translation issue in recent two days so it should work now.

**Comment by stefonarch** [comment]
Updated git just now, version  was 2 days old, it works now but only
after restarting the  session.
pcmanfm-qt-git 0.8.0.38.g5eb5314-1
it_IT.UTF-8
Arch linux, updated and not patched

On siduction in qemu with german language it's the same, LXQt 0.8

Thanks for your work!

stefano


Il 31/01/2015 06:53, PCMan ha scritto:
> It works here. See the screenshot please.
> https://drive.google.com/file/d/0B4BhmC8V2mivSWdwSmpuek8zaEk/view?usp=sharing
> What's your locale setting and which git version are you using?
> Are you using a patched version from your distro?
> I fixed a translation issue in recent two days so it should work now.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/468#issuecomment-72306091>.
> 

-- 
********************************
Stef Binde
via della pieve 2
I-56024 Corazzano PI

Tel: ++39 0571 17 30 104
PGP: 0x728D9707

stef.binde@riseup.net
*******************************

**Comment by PCMan** [comment]
Thanks for testing.

**Comment by agaida** [comment]
@stefonarch: for siduction you should consider to use 
deb http://packages.siduction.org/extra experimental main

Thats the current development and eventually pin the experimental kernel and other things you don't like really bleeding down :D

**Comment by stefonarch** [comment]
Thanks, but for the bleeding edge stuff I have my arch box :)
I'm having a look at siduction for my friends with old computers,
usually I  proposed them xubuntu.


Il 31/01/2015 13:45, Alf Gaida ha scritto:

**Comment by agaida** [comment]
@stefonarch - siduction has a special adventage - same as current ubuntu: Qt 5.3.2 :D
