### ISSUE TITLE
Supporting DBusActivatable apps

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#47]
I don't believe we support those yet. We should. (Ping me with any questions regarding this)

**Comment by palinek** [comment]
@jleclanche what's needed to do here? Isn't that already here:
![screenshot](https://cloud.githubusercontent.com/assets/10990929/6676211/734e2108-cc26-11e4-91bf-145cfef5bbb0.png)
?

**Comment by jleclanche** [comment]
No, it's about the runner, supporting launching apps which specify the DBusActivatable key.
