### ISSUE TITLE
qps no root access

### ISSUE THREAD

**Issue by thor480** [lxde/lxqt#472]
qps need super-user access, like gnome system manager 
![qps](https://cloud.githubusercontent.com/assets/7660057/6000600/00ef9072-aae0-11e4-8800-b4260d57fe55.png)

**Comment by pmattern** [comment]
According to your screenshot qps is basically running fine, see its main window. Same applies to my local system where I've got qps 1.10.16 running flawlessly on LXQt compiled from latest Git (Arch Linux). To my knowledge qps is *not* meant to run with root privileges by default, much as ps isn't if invoked on CLI. It doesn't belong to LXQt.
The only apparent problem is affecting aptd which is a distribution-specific tool and not a LXQt component either.

So for now I can't see how LXQt should be related to your problem and I think you need to post further findings providing evidence of that relation, e. g. something like "problem appears on LXQt but neither on desktop environments foo or bar".

Also, further information regarding your system - distribution, version and so on - would be helpful.

**Comment by agaida** [comment]
tested this in sid and can't see no bug - i can modify the processes, where i have sufficient rights. Maybe qps should be improved to act like another user (process owner) - but thats the buisness of the qps devs.

**Comment by thor480** [comment]
agaida QPS is a dead project, so I was nice if lxqt dev took over project

**Comment by jleclanche** [comment]
Qps is not part of lxqt. You can file a bug here if you like, but it is indeed a dead project.

**Comment by jleclanche** [comment]
We should probably just fork it into lxtask-qt if the license allows it.
