### ISSUE TITLE
pcmanfm-qt --desktop --profile=lxqt segfault

### ISSUE THREAD

**Issue by robwoj** [lxde/lxqt#474]
Hi,

I use recent master version of lxqt. Recently I noticed in my dmesg that pcmanfm-qt segfaults, I crated a coredump of that:

Core was generated by `pcmanfm-qt --desktop --profile=lxqt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fcb6a732938 in Fm::isUriSchemeSupported (uriScheme=0x458a19 "trash")
    at /home/robert/work/lxqt/pcmanfm-qt/libfm-qt/utilities.cpp:295
295	  for(const gchar * const * scheme = schemes; *scheme; ++scheme)

Cheers,
Robert

**Comment by PCMan** [comment]
I just added more null checks to that part.
Would you please try the latest code in git?
Thanks!

**Comment by robwoj** [comment]
Fixed, thx!
