### ISSUE TITLE
LXQt runner: migrate session handling and lock screen to lxqt-leave

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#476]
Within the menu opened by clicking the icon between form and icon to close (icon varying with icon theme and LXQt theme as set in lxqt-config-appearance, wrench with Oxygen and Frost)
![runner gesamtansicht](https://cloud.githubusercontent.com/assets/9860801/6473744/a8d0383c-c1fb-11e4-88d2-2d1a4a23d5fd.png)
entries regarding the session (Hibernate, ..., Logout) are QActions provided by LXQt::PowerManager, "Lock Screen" is a QAction provided by LXQt::ScreenSaver, both in liblxqt, see files lxqtpowermanager.cpp, lxqtscreensaver.cpp and translations/liblxqt*.ts.
Regarding Application menu it was agreed in #437 to use lxqt-leave and its corresponding desktop entry files /usr/share/applications/lxqt-{hibernate,...,logout,lockscreen}.desktop only, which all are provided by lxqt-session.
So right now the very same kind of entry is deduced in two different ways by different LXQt components which isn't desirable regarding maintenance effort. Given the choice made regarding Application menu I think lxqt-leave and its corresponding desktop entry files should be used in runner's menu as well.

There's another, probably related finding: upon filing corresponding terms in runner's form two entries are shown, e. g.
![runner hibernate](https://cloud.githubusercontent.com/assets/9860801/6473754/b940a8b4-c1fb-11e4-93c1-10070410870d.png)
where "Power Management" is deduced from liblxqt and "hibernate the machine" from /usr/share/applications/lxqt-hibernate.desktop.
Not sure where this belongs, though: If that "liblxqt" entry is tied to runner's menu, then it belongs to this issue. If it's derived independently from runner's menu then it's a variant of #478.

**Comment by paulolieuthier** [comment]
Both lxqt-runner's menu actions and lxqt-leave depend on liblxqt to get the power actions, so they work the same way. The difference is that lxqt-leave is bundled in lxqt-session, so it might be absent. IMO the fix for this is not to show lxqt-leave suggestions here.

**Comment by paulolieuthier** [comment]
@jleclanche @luis-pereira @agaida @PCMan @heliocastro description updated. What do you think of this issue?

**Comment by jleclanche** [comment]
Yes, someone needs to pick it up.

**Comment by paulolieuthier** [comment]
I'm not sure how to fix it.

**Comment by jleclanche** [comment]
@paulolieuthier we ship desktop files with lxqt-leave now. so whatever code is specific to lxqt-runner needs to be removed in favour of just making sure our desktop files are listed.

**Comment by paulolieuthier** [comment]
@jleclanche what if the user wants to use lxqt-runner but not lxqt-session? lxqt-leave is shiped in lxqt-session.

**Comment by jleclanche** [comment]
That's fine, then lxqt-leave integration won't be in lxqt-runner.

**Comment by paulolieuthier** [comment]
OK.
