### ISSUE TITLE
lxqt-qtplugin build issues

### ISSUE THREAD

**Issue by Thorn-Inurcide** [lxde/lxqt#480]
CMakeList.txt is looking for suffix qt5 on lxqt

**Comment by Thorn-Inurcide** [comment]
When trying to compile lxqt-qtplugin it would error looking for lxqt-qt5, I removed the suffix -qt5 from CMakeList and it compiled for me

**Comment by jleclanche** [comment]
So what's the actual error you're getting?

**Comment by Thorn-Inurcide** [comment]
CMake Error at CMakeLists.txt:11 (find_package):
  By not providing "Findlxqt-qt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "lxqt-qt5",
  but CMake did not find one.

  Could not find a package configuration file provided by "lxqt-qt5" with any
  of the following names:

    lxqt-qt5Config.cmake
    lxqt-qt5-config.cmake

  Add the installation prefix of "lxqt-qt5" to CMAKE_PREFIX_PATH or set
  "lxqt-qt5_DIR" to a directory containing one of the above files.  If
  "lxqt-qt5" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by Thorn-Inurcide** [comment]
find_package(lxqt-qt5 REQUIRED QUIET)  

i removed the -qt5 from here and it compiled

**Comment by Thorn-Inurcide** [comment]
Building ...
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Qt5 plugin directory:/usr/lib64/qt5/plugins
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/build/tmp-lxqt-qtplugin/lxqt-qtplugin-0.9.0/build-lxqt-qtplugin
Scanning dependencies of target qtlxqt_automoc
[ 25%] Automoc for target qtlxqt
Generating main.moc
Generating moc_lxqtplatformtheme.cpp
[ 25%] Built target qtlxqt_automoc
Scanning dependencies of target qtlxqt
[ 50%] Building CXX object src/CMakeFiles/qtlxqt.dir/main.cpp.o
[ 75%] Building CXX object src/CMakeFiles/qtlxqt.dir/lxqtplatformtheme.cpp.o
[100%] Building CXX object src/CMakeFiles/qtlxqt.dir/qtlxqt_automoc.cpp.o
Linking CXX shared library libqtlxqt.so
[100%] Built target qtlxqt
[ 25%] Automoc for target qtlxqt
[ 25%] Built target qtlxqt_automoc
[100%] Built target qtlxqt
Install the project...
-- Install configuration: "Release"
-- Installing: /tmp/build/package-lxqt-qtplugin/usr/lib64/qt5/plugins/platformthemes/libqtlxqt.so
/tmp/build/tmp-lxqt-qtplugin/lxqt-qtplugin-0.9.0

Slackware package maker, version 3.14159.

Searching for symbolic links:

No symbolic links were found, so we won't make an installation script.
You can make your own later in ./install/doinst.sh and rebuild the
package if you like.

This next step is optional - you can set the directories in your package
to some sane permissions. If any of the directories in your package have
special permissions, then DO NOT reset them here!

Would you like to reset all directory permissions to 755 (drwxr-xr-x) and
directory ownerships to root.root ([y]es, [n]o)? n

Creating Slackware package:  /tmp/lxqt-qtplugin-0.9.0-x86_64-2_thorn.txz

./
install/
install/slack-desc
usr/
usr/lib64/
usr/lib64/qt5/
usr/lib64/qt5/plugins/
usr/lib64/qt5/plugins/platformthemes/
usr/lib64/qt5/plugins/platformthemes/libqtlxqt.so
usr/doc/
usr/doc/lxqt-qtplugin-0.9.0/
usr/doc/lxqt-qtplugin-0.9.0/AUTHORS
usr/doc/lxqt-qtplugin-0.9.0/COPYING
usr/doc/lxqt-qtplugin-0.9.0/lxqt-qtplugin.SlackBuild

Slackware package /tmp/lxqt-qtplugin-0.9.0-x86_64-2_thorn.txz created.

**Comment by heliocastro** [comment]
Indeed the upstream tarball missed the last commits.

I attached the patch that i used on Fedora ones if helps.

**Comment by jleclanche** [comment]
@heliocastro Patches don't get processed by github. Can you gist it?

**Comment by heliocastro** [comment]
Done https://gist.github.com/heliocastro/2598c71c0aa7b20e16aa

**Comment by Thorn-Inurcide** [comment]
Thanks =]

**Comment by jleclanche** [comment]
Guys, i re-released lxqt-qtplugin, see the announcement on the ML. If you're still seeing the old files, add ?nocache at the end of the url while it's still propagating.
