### ISSUE TITLE
lxqt-config: appearance settings are not saved

### ISSUE THREAD

**Issue by orschiro** [lxde/lxqt#481]
Dear all,

Thank you for your efforts regarding lxqt!

I am a plain Openbox user with predominantly GTK3 apps installed. However, I have some Qt apps for which I wanted to adjust the font settings. I installed `lxqt-config 0.8.0-2` on Arch Linux and ran it from the terminal:

```
$ lxqt-config
Theme: Cannot open file for reading: "/lxqt-config.qss"
LxQt::Translator: Qt translations not found
```

However, whenever I change the settings, close `lxqt-config` and start it again, it falls back to some default settings. Do you have any idea why this is happening?

Thankfully,

Robert

**Comment by pmattern** [comment]
There's a regression affecting Qt 5.4, a workaround was introduced only recently. As you're using 0.8 on Arch Linux chances are it's what you're suffering from. For further information see https://github.com/lxde/lxqt/issues/441 (issue) and https://github.com/lxde/liblxqt/pull/33 (pull request of workaround).

To track your problem I'd suggest you first compile a recent version against Qt 5.4. Packages of Git code are available as AUR packages on Arch Linux. As an alternative, you could also compile 0.8 against Qt 5.3. More cumbersome to handle on Arch, obviously.

**Comment by jleclanche** [comment]
dup then

**Comment by orschiro** [comment]
Thanks for your comments. Now I installed the latest git version `lxqt-config-git 0.9.0-1`.

However, still my changes are not saved, If you are correct that my error messages have nothing to do with the issue, then how can I further debug why my font settings are not saved?

```
❯ lxqt-config
LxQt::Translator: Qt translations not found
Theme: Cannot open file for reading: "/lxqt-config.qss"
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
```

**Comment by paulolieuthier** [comment]
@orschiro, you need to install lxqt-qtplugin from git as well to get it to work.

**Comment by orschiro** [comment]
@paulolieuthier 

Thank you! After installing the qtplugin, my font settings are saved. The only remaining issue is that my custom icon theme is not found by lxqt but well found by lxappearance (GTK).

![image](https://cloud.githubusercontent.com/assets/170947/6108629/fbc4b916-b074-11e4-90de-5f57f1269a46.png)

**Comment by paulolieuthier** [comment]
@orschiro that should have its own issue.

**Comment by orschiro** [comment]
Apologises. I will file a separate issue. Thank you for your help!
