### ISSUE TITLE
liblxqt-mount is outside the liblxqt releases - so we should release it separated

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#482]
CMakeLists.txt is still 0.8.0 - dropping qt4 and the -qt5 suffix should justify a 0.9 release

**Comment by jleclanche** [comment]
Urgh. I forgot they are separate.

We should move to solid to be honest anyway, so I don't see liblxqt-mount
surviving much longer. Any takers?

**Comment by agaida** [comment]
if solid work solid - we should use it. But we should release liblxqt-mount now as 0.9. i didn't think that there is any harm in it. Liblxqt-mount can be packaged as separated package, there will be no need to rebuild any packages depending on liblxqt-mount.

**Comment by jleclanche** [comment]
liblxqt-mount *did* get a release, but its internal version wasn't updated. It's not a real world issue seeing as we are the only user of lxqt-mount and there is no feature difference between the two other than qt4 compatibility.

I don't think this warrants a 0.9.1 if we plan to drop it anyway... And I would really like to drop it in favour of solid.

**Comment by jleclanche** [comment]
Closing as dup of #301
