### ISSUE TITLE
new panel widget: space / spacer / gap

### ISSUE THREAD

**Issue by excalibur1234** [lxde/lxqt#483]
thanks a lot for the new panel widgets included in lxqt 0.9. i really like them!

i am missing one really simple widget: an empty widget, which occupies a little panel space. 
ideally, the amount of space occupied can be adjusted in the properties, but this is not mandatory.

**Comment by pmattern** [comment]
This has been asked for in https://github.com/lxde/lxqt/issues/394 already.

**Comment by excalibur1234** [comment]
thx
