### ISSUE TITLE
Look into forking qps into lxtask-qt

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#484]
See #472

**Comment by PCMan** [comment]
Are there anything that need to be "improved" in qps that cannot go upstream?
I don't really see the point for a fork unless we have a clear roadmap about what to improve in addition to renaming.

**Comment by jleclanche** [comment]
Yeah, for one thing it's not suitable as a newbie-friendly task manager. It's far too advanced, shows root tasks etc.
I remember discussing Qt 5 support with the guy as well, he did (start?) it in the qtdesktop/qps repo but never got back to it and doesn't reply to emails.

But the main issue is that it has no support. As a project, it's dead...

**Comment by jleclanche** [comment]
It's worth noting that when we brought up the topic of the screengrab fork into lxqt-screenshot, lots of improvements were made and the original author came back to work on it more. So it revived the project, and the fork didn't happen.

**Comment by paulolieuthier** [comment]
Good point, this one. But tbh, I think we shouldn't comprimise lxqt's man power.

**Comment by jleclanche** [comment]
This is open for takers, really.

**Comment by agaida** [comment]
@jleclanche, @paulolieuthier - i managed to build with qt5 a few weeks ago - should sort it out. Runs without problems but will need a review - so you can assign me.

**Comment by paulolieuthier** [comment]
Fork it on QtDesktop. I was thinking in porting EasyPaint as well.

**Comment by jleclanche** [comment]
EasyPaint is a lost cause tbh. qps is already on qtdesktop btw.

**Comment by paulolieuthier** [comment]
I just ported both qps and EasyPaint to Qt5 in QtDesktop (in PRs).
