### ISSUE TITLE
remove gtk2-dependency of libfm

### ISSUE THREAD

**Issue by excalibur1234** [lxde/lxqt#485]
pcmanfm-qt is dependent on libfm and libfm is dependent on gtk2.

libfm is the last part in lxqt, which depends on gtk.
is it possible to remove gtk2-dependency of libfm and therefore making lxqt independent of gtk2 ?

**Comment by Thorn-Inurcide** [comment]
you can compile libfm without gtk =]
--without-gtk

**Comment by jleclanche** [comment]
libfm doesn't depend on gtk, your distro maintainer should split it off.
