### ISSUE TITLE
Move kwindowsystem dependency away from liblxqt

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#486]
liblxqt really shouldnt depend on it. we should move the dep to the appropriate components.

**Comment by paulolieuthier** [comment]
The only use of it is in lxqtsingleapplication.cpp, in `SingleApplication::activateWindow()`.

**Comment by paulolieuthier** [comment]
I don't see how to remove it. Qt can't handle it by itself.

**Comment by luis-pereira** [comment]
@paulolieuthier Neither do I.

**Comment by palinek** [comment]
Do we close this?

**Comment by paulolieuthier** [comment]
I guess so.
