### ISSUE TITLE
lxqt-panel: desktop switching with mouse wheel is broken

### ISSUE THREAD

**Issue by novist** [lxde/lxqt#491]
When we have multiple desktops we can switch to previous desktop by scrolling mouse wheel up. However scrolling mouse wheel down does not switch to next workspace. Mouse click is required in that case.

EDIT:
Also i noticed that when i click desktop button switch will not happen until mouse is moved.

**Comment by paulolieuthier** [comment]
Fixed in lxde/lxqt-panel#133.
