### ISSUE TITLE
lxqt-panel: system tray should not show networking icon when NetworkManager service is not running

### ISSUE THREAD

**Issue by novist** [lxde/lxqt#492]
As title says. Some people (including me) do not use network manager. There is no reason to keep icon indicating state of disabled service. It is even misleading because networking is just fine but is displayed as disconnected.

**Comment by PCMan** [comment]
That icon is shown by nm-applet, not lxqt-panel.
Just uninstall nm-applet if you don't use it and the icon will disappear.
It's not the problem of lxqt-panel.
