### ISSUE TITLE
Panel will disappear when using double screen.

### ISSUE THREAD

**Issue by ken-kuang** [lxde/lxqt#496]
I got 2 panel on the bottom when I am using double screen.Sometimes one panel disappear when I am working.Please check the bug.

**Comment by jleclanche** [comment]
Gonna need more info than "sometimes".

**Comment by rapgro** [comment]
I do not have an automatic panel at all, even with one screen. Usage is lightdm, lxqt-session and openbox.

**Comment by paulolieuthier** [comment]
O

**Comment by pmattern** [comment]
@ken-kuang 
You may want to verify whether your findings are related to RandR settings as described [here](https://github.com/lxde/lxqt/issues/650#issuecomment-107385604).

@rapgro 
I'm not aware of any way to start LXQt sessions where binary lxqt-session is invoked directly so your description seems a bit vague to me.
Could you please provide information about the OS you're using, how exactly you are launching your session and the versions of all components involved?

**Comment by rapgro** [comment]
My bug is gone and I can not reproduce, it seems to went away with a newer version. I use Fedora and the official packages from heliocastro (version 0.9.0). Thanks for caring.

**Comment by palinek** [comment]
Closing as no further information to reproduce the bug were gotten from the originator...

@ken-kuang if the problem persists for you, please reopen the issue and share steps for reproducing it.
