### ISSUE TITLE
Panel items don't always respond on first click

### ISSUE THREAD

**Issue by silvernode** [lxde/lxqt#503]
For starters this occurrence is random but not random enough to spare annoyance. To attempt to reproduce, browse the internet or use some other application as normal for a decent amount of time (i'd say 10 minutes roughly) then quickly point your mouse to an icon shortcut on the panel. What's happening to me is I'll go to click an icon and nothing happens until I click once more. It's one of those small annoyances that gets really monotonous  over time.  It confuses my brain for a split second even though it's happened on plenty of occasions. It's as if the panel is out of focus or something.

I'd like to know if anyone has experienced this or if it's just my installation. I'm running Void Linux with LXQT 0.9.0 straight from the official repositories. It may be entirely possible that it's distro related but I wanted to bring my issue here to make everyone aware.

**Comment by Esclapion** [comment]
Hi,

Same problem on a Manjaro, especially after a first installation or a
reboot.

2015-02-17 13:28 GMT+01:00 silvernode <notifications@github.com>:

**Comment by silvernode** [comment]
Ok so it's not just me! Thanks for the comment, it hasn't happened to me in a few hours but then again I haven't rebooted in awhile. Time for sleep, we shall see how it reacts on the next boot.

**Comment by Spacesurfer** [comment]
I've had the same issue since 0.8.0 on Manjaro. My cursor will be over the icon, it won't 'light up' and won't respond when I click it. Have to move it off and on some times before it will register a click.

**Comment by rcmn** [comment]
Same here .And it has been for a long time now. ubuntu .

On Tue, Feb 17, 2015 at 9:39 PM, Richard K. <notifications@github.com>
wrote:

> I've had the same issue since 0.8.0 on Manjaro. My cursor will be over the
> icon, it won't 'light up' and won't respond when I click it. Have to move
> it off and on some times before it will register a click.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/503#issuecomment-74693559>.
>



-- 
R.

**Comment by hterh** [comment]
Also I observed this on the start icon both on Xubuntu/LXQt 64 and on Manjaro/LXQt 32 on another PC. In Xubuntu hovering over the start button changes the background color of the icon but sometimes this is not happening and then the first click gives no response. In Manjaro there is no hovering effect at all of any icons and here almost all first clicks on the start icon have no response. But for me no problems with desktop icons.

**Comment by pmattern** [comment]
This problem has been described both in https://github.com/lxde/lxqt/issues/436#issuecomment-72373045 and https://github.com/lxde/lxqt-panel/pull/131#issuecomment-72385553 and is due to a Qt bug. See link to Qt bug as stated in pull request 131.

**Comment by silvernode** [comment]
Since this issue is not caused by lxqt and is already open somewhere else, I am closing it.

**Comment by Esclapion** [comment]
It's for the moment the main remaining problem. A workaround ?

**Comment by pmattern** [comment]
@Esclapion 
To my knowledge no, unfortunately. Looks as if we have to wait until it's fixed upstream. Totally agree it's something pretty annoying trying to use LXQt on production systems.
