### ISSUE TITLE
on dual-monitor setup, lxqt menus stay out of the left part of the screen

### ISSUE THREAD

**Issue by fbreitwieser** [lxde/lxqt#508]
Hi, thanks a lot for this nice desktop!

I have an issue on my dual-monitor setup: All menus stay out of the left 20% of the screen for any window and the panel. See the attached screenshots:
![menu](https://cloud.githubusercontent.com/assets/516060/6287048/0187121c-b8dc-11e4-880a-6e6aa361d400.png)
![menu-pcmanfm](https://cloud.githubusercontent.com/assets/516060/6287049/0188f046-b8dc-11e4-9c93-e0b7ed98ee2c.png)

I have a dual-monitor setup with catalyst drivers (Radeon 5450), where the left monitor is primary, and the right monitor is pivoted on its side.

    DFP1 connected primary 1920x1080+0+416 (normal left inverted right x axis y axis) 531mm x 299mm
    DFP2 connected 1080x1920+1920+0 left (normal left inverted right x axis y axis) 531mm x 299mm

**Comment by fbreitwieser** [comment]
I found the reason: When I started terminology (which I did when starting), the terminal in fact did not show up. Terminating it solves the problem.

**Comment by jleclanche** [comment]
@fbreitwieser is that issue with terminology fully reproducible? Do you know what causes it?

**Comment by fbreitwieser** [comment]
Yes, same thing happens every time when I start it without arguments. I also tried it now with only one monitor, and then it appeared like this:

![terminology-1monitor](https://cloud.githubusercontent.com/assets/516060/6288420/efcc6152-b8e6-11e4-8e30-a0e92e679be6.png)

The terminology window resizes the active desktop area to the part right from it. So when I maximize any window (for example firefox on the right), it only covers the part up to the edge of terminology.

I found a workaround: Starting terminology with -I to have it iconic. Then it behaves just like a window as it should do, and maximizing also works fine. Starting it with no parameters, or -M for maximized or -F for fullscreen, the issue appears.

**Comment by fbreitwieser** [comment]
It seems to be an openbox issue. With kwin, it works w/o a problem.

**Comment by jleclanche** [comment]
ill try to reproduce it later

**Comment by antis81** [comment]
Same here. Seeing mispositioned menus on dual-monitor setup.

Also `lxqt-runner` is configured to be shown centered on the monitor with the mouse focus. When focus is on configured "first" monitor, everything works as expected. When mouse pointer is on the second monitor, the dialog shows in center of both screens (appears half on each screen). Seems like it has the same reasoning, as sometimes it works correctly and both, menus and the lxqt-runner dialog are shown at the right positions.

Sample (on second monitor):
![lxqt-wrong-menu](https://cloud.githubusercontent.com/assets/440517/7102031/a17eac44-e073-11e4-8298-98f188889dbb.png)

**Comment by antis81** [comment]
This issue relates to [lxqt-panel issue 230](https://github.com/lxde/lxqt-panel/pull/230).

**Comment by antis81** [comment]
Looks like the merge of [lxqt-panel PR 230](https://github.com/lxde/lxqt-panel/pull/230) also fixes these problems.

Needs verification, but on my system, also `lxqt-runner` appears centred on screen with mouse cursor. This should be completely unrelated of the QMenu positioning, shouldn't it? Anyway -> :+1:

**Comment by jleclanche** [comment]
I think this was fixed, I haven't had this issue in ages. I do see the menu sometimes appearing in the topleft corner of the primary display but it's very hard to repro.

**Comment by pmattern** [comment]
@jleclanche 
> I do see the menu sometimes appearing in the topleft corner of the primary display but it's very hard to repro.

Exactly the same here - both finding and problems trying to reproduce.
Seems this mainly happens on new user profiles where no LXQt settings have been tweaked before, though.

**Comment by aevernum** [comment]
![screenshot](https://user-images.githubusercontent.com/9028087/36022531-1e8afe60-0d92-11e8-876b-02c06b3eaf75.png)
fedora 27. lxqt Version | 0.11.1. Qt v - 5.9.4
