### ISSUE TITLE
lxqt-config: remove empty category from lxqt-config-monitor.desktop

### ISSUE THREAD

**Issue by doktor5000** [lxde/lxqt#509]
This small cosmetic issue exists at least since lxqt-config 0.8.  lxqt-config-monitor.desktop contains an empty category ( two ;; consecutively) maybe something adds a spurious ; in there:

<pre>┌─[doktor5000@Mageia5]─[14:58:39]─[~/lxqt-config-0.9.0]
└──╼ find . -iname "*desktop*" -exec grep ';;' {} +
./lxqt-config-monitor/lxqt-config-monitor.desktop.in:Categories=Settings;DesktopSettings;Qt;LXQt<b>;;</b>HardwareSettings;</pre>

Patch looks like this:

<pre>
--- lxqt-config-0.9.0/lxqt-config-monitor/lxqt-config-monitor.desktop.in
+++ lxqt-config-0.9.0/lxqt-config-monitor/lxqt-config-monitor.desktop.in        2015-02-20 14:53:57.779536503 +0100
@@ -5,7 +5,7 @@
 Comment=Configure monitors
 Exec=lxqt-config-monitor
 Icon=preferences-desktop-display
-Categories=Settings;DesktopSettings;Qt;LXQt;;HardwareSettings;
+Categories=Settings;DesktopSettings;Qt;LXQt;HardwareSettings;
 OnlyShowIn=LXQt;
 
 #TRANSLATIONS_DIR=translations</pre>

Or fix via sed: 
```sed -i 's/;;/;/' lxqt-config-monitor/lxqt-config-monitor.desktop.in```

**Comment by paulolieuthier** [comment]
Fixed in lxde/lxqt-config@19c378828ed8dbc714a2901c8a43b52f7a2a9ff3. Please update.

**Comment by doktor5000** [comment]
Thanks, for the pointer, just mentioned it because it's not in 0.9.0.

**Comment by paulolieuthier** [comment]
@doktor5000 thanks.
