### ISSUE TITLE
lxqt-admin-user: new group ID

### ISSUE THREAD

**Issue by goetzc** [lxde/lxqt#510]
When adding a new group, the lowest available ID is chosen by default. Adding users hasn't this problem. This could interfere with distros post-installation scripts.

As explained in ```groupmod``` manual page:  
http://linux.die.net/man/8/groupmod 
```Values between 0 and 999 are typically reserved for system groups.```

**Comment by palinek** [comment]
On first sight .... everything that is needed to fix this problem is this line in lxqt-admin/lxqt-admin-user/groupdialog.cpp:
```c++
        ui.gid->setValue(oobs_groups_config_find_free_gid(groupsConfig, 0, 32768));
```
@jleclanche what should be the minimum number for new group? (for adding user there is 1000)

**Comment by jleclanche** [comment]
1000 as well afaik

**Comment by jleclanche** [comment]
@palinek go ahead and land this

**Comment by palinek** [comment]
merged
