### ISSUE TITLE
LXQt notificationd: approve longer duration

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#515]
Right now lxqt-config-notificationd allows for setting durations ≤ 99s only. I think it would be good if longer periods could be configured. Actually I think even arbitrary values should be possible.

**Comment by palinek** [comment]
That's the default maximum value for QSpinBox. It can be overriden easily. What should I put there for the maximum (must be set)?

**Comment by pmattern** [comment]
Personally I just wanted to have a bit more time to read a bunch of plugin messages popping up recently upon login after tweaking some keyboard shortcuts. Maybe it wouldn't be bad to have messages still readable if someone is afk for a bit longer as well. On the other hand real long durations won't be needed any more at all should https://github.com/lxde/lxqt/issues/149 get implemented (which I'd definitely appreciate).

So if there's no downside I'd suggest 7200s ≈ 2h for the time being.

**Comment by Vladimir-csp** [comment]
Also see here: https://github.com/lxde/lxqt/issues/149#issuecomment-44012590
Idle timeout could be of use here. Freeze notifications` timeouts when user is idle.
