### ISSUE TITLE
lxqt-about: shows invalid path ~/local/sharelxqt/translations

### ISSUE THREAD

**Issue by doktor5000** [lxde/lxqt#518]
This is the output of the "Technical Info" tab:

LXQt Desktop Toolbox - Technical Info<p>
  Version:                0.9.0
  Qt:                     5.4.0
  Build type:             Release
  System Configuration:   /etc
  Share Directory:        /usr/share/lxqt
  Translations:           /usr/share/lxqt/translations<br>
/home/user2/.local/**sharelxqt**/translations<br>
/usr/local/share/lxqt/translations

User Directories
  Xdg Data Home:          /home/user2/.local/share
  Xdg Config Home:        /home/user2/.config
  Xdg Data Dirs:          /home/user2/.local/share:/usr/local/share/:/usr/share/
  Xdg Cache Home:         /home/user2/.cache
  Xdg Runtime Home:       /run/user/1001
  Xdg Autostart Dirs:     /etc/xdg/autostart<br>
/autostart
  Xdg Autostart Home:     /home/user2/.config/autostart

***

Is that only a cosmetic issue in the lxqt-about dialog, or is that invalid path really used?

**Comment by jleclanche** [comment]
@surlykke @luis-pereira either of you can look at this?
