### ISSUE TITLE
World Clock doesn't immediately reflect timezone changes

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#519]
Test with `timedatectl set-timezone Europe/London` and switching between timezones. Going in the config and toggling "Set timezone" once fixes that.

This contrasts with the old clock plugin which reflected changes immediately. cc @kuzmas

**Comment by goetzc** [comment]
Related, the World Clock is also one seconds behind the system clock, but I opened issue #525 for that.

**Comment by kuzmas** [comment]
@goetzc 
Just a note: these issues are unrelated

**Comment by jleclanche** [comment]
@kuzmas I don't understand how 352c439 fixes this?

**Comment by kuzmas** [comment]
Before that there was no way to track system timezone. Plugin used only list of selected timezones.
So if no timezone is selected the plugin asked current system timezone when configuration dialog saved settings or on the plugin start and used it as the default. Now I've added special case - a fake "local" timezone which is replaced with current system timezone every time when the time string is formatted.
So now, if no timezone is selected the plugin uses new "local" timezone. (Or you can manually select it from the timezone list, it's in the group "Other")
