### ISSUE TITLE
lxqt-panel menus not shown after enabling second monitor for first time

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#520]
```xrandr --output HDMI --auto --above LVDS1```

No menus are shown for lxqt-panel, including main menu and context menus for plugins.
Menus for pcmanfm-qt, tray items and other apps are shown correctly, only lxqt-panel is affected.

switching second monitor off and on resolves the issue, although after that main menu is stretched vertically when shown for the first time

**Comment by Vladimir-csp** [comment]
Another menu-related problem:
If you call some menu on the panel, then click on desktop, next click on the panel will be ignored.

**Comment by Vladimir-csp** [comment]
Clicking on any other window when menu from lxqt-panel is visible results in next panel click ignored.

**Comment by palinek** [comment]
...there is a typo in the commit message lxde/lxqt-panel@7cc17a0 (wrong issue reference).

**Comment by pmattern** [comment]
@Vladimir-csp 
The problem that clicking elements in panel has an effect the second click only was discussed among other in https://github.com/lxde/lxqt/issues/436#issuecomment-72373045 and is due to a [Qt bug](https://bugreports.qt.io/browse/QTBUG-44231). In particular see the steps to reproduce provided by PCManFM in the Qt bug report.

**Comment by palinek** [comment]
@pmattern  lxde/lxqt-panel@7cc17a0  is not connected anyhow to this issue (it's a wrong reference in commit message)

**Comment by paulolieuthier** [comment]
@Vladimir-csp can you please test if the references PR solves it?

**Comment by Vladimir-csp** [comment]
OK, finally I've built it.
Menus are shown after toying with monitors. That is fixed.
One time panel lost it's sticky status, showing only on first desktop, but I could not reproduce it second time and can not tell what triggered it.

**Comment by paulolieuthier** [comment]
Awesome. @Vladimir-csp if the issue persists, please file it.
