### ISSUE TITLE
lxqt-globalkeysd: pwd is '/'

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#521]
I've created a shortcut for launching terminal. It launches with ```/``` as working dir. Should be ```$HOME```.

**Comment by paulolieuthier** [comment]
Can't reproduce it here.

**Comment by Vladimir-csp** [comment]
lxqt-globalkeys 0.9.0-1 
Corresponding config part:
```
[Meta%2BT.9]
Comment=Launch terminal
Enabled=true
Exec=x-terminal-emulator
```

**Comment by paulolieuthier** [comment]
I can reproduce it using xterm, but not konsole.

**Comment by Vladimir-csp** [comment]
I've got this bug with qterminal and sakura. Didn't check with the rest.
But when using the same shortcut and command via openbox keybindings terminal is launched in ```$HOME```
