### ISSUE TITLE
Volume control widget cannot be displayed if only alsa-lib is installed (without libpulse)

### ISSUE THREAD

**Issue by polomi** [lxde/lxqt#522]
If only alsa-lib is installed (and libpulse is not installed) the volume contorl widget can't be displayed.

In the Add Panel Widgets window, if I try to add the volume control widget it doesn't appear anywhere. '(1 active)' becomes temporarily written next to the volume control entry in the Add Panel Widgets window, but it disappears if I close and open that window again.

If libpulse is installed in addition (no need to install pulseaudio, just libpulse is enough), the widget appears properly. It appears but it doesn't control the audio by default if pulseaudio isn't installed, it is initially configured to use PulseAudio. I have to go in the Configure "Volume Control" window and select ALSA for it to work properly and control the audio.

So the workaround is to install libpulse to make the widget appear, and then to configure it to use ALSA.

The behavior that I expected from the widget is that it shouldn't want libpulse just in order to be displayed and that it should be able to be displayed with only alsa-lib. But it's not the case.

**Comment by paulolieuthier** [comment]
lxqt-panel links to both alsa and pulseaudio by default. If you don't want pulseaudio, run `cmake .. -DVOLUME_USE_PULSEAUDIO=OFF && make install`.
