### ISSUE TITLE
lxqt-panel: positional monitor options

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#523]
Please add ability to choose monitor for panel positionally, i.e.: "leftmost monitor", "bottom monitor", etc.
Although it may require changing current fused position+monitor widget.

**Comment by jleclanche** [comment]
I don't understand the request.

**Comment by Vladimir-csp** [comment]
"first" or "second" monitor can be anywhere, depending on the workplace setup. Think of moving with your laptop from home to work, etc.
Assigning panel to monitor positionally is more predictable. You choose "Rightmost monitor", and the panel will be placed on the rightmost monitor, no matter if it is first or fifth or whatever.
The only problem is how to prioritize among evenly (for chosen direction) placed monitors. Although, 9 directions should be enough.

**Comment by jleclanche** [comment]
Seeing as the panel gives immediate feedback and this isn't easy to do at all (even on a literary level), I'm rejecting this.
