### ISSUE TITLE
Some apps with tray icon crash when lxqt-panel is killed

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#524]
I thought, I reported this bug some time ago, but now I can not find it.

When lxqt-panel is killed, most of the apps with tray icon are crashed. These include: gxkb, nm-applet, parcellite.
This bug does not affect old lxpanel.

parcellite terminal output:
```
(parcellite:10569): Gdk-WARNING **: GdkWindow 0x2a0001f unexpectedly destroyed
The program 'parcellite' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 365 error_code 3 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by palinek** [comment]
I also realized that this is happening, but thought it's a failure of the client applications...

...anyway tried to connect cleanup to aboutToQuit signal and this helps.

lxde/lxqt-panel#146
