### ISSUE TITLE
lxqt-powermanagement: tray's tooltip doesn't popup

### ISSUE THREAD

**Issue by paulolieuthier** [lxde/lxqt#526]
Introduced with lxqt-powermanagement's port to KF5's Solid. Before it used to get a signal when the tooltip's text had to be updated and called `setTooltip` for it. Now, there is no such signal anymore. Setting the tooltip text in the tooltip event has no effect. @surlykke @PCMan

**Comment by jleclanche** [comment]
What did the tooltip display?

**Comment by paulolieuthier** [comment]
The current percentage and charging state.

**Comment by palinek** [comment]
@jleclanche we was already discussing this with @paulolieuthier while you were assigning me ... and Paulo took that
