### ISSUE TITLE
lxqt-config-globalkeysd: list current soft grabs

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#528]
Feature request: in keybindings dialog show list of soft grabs (which are not issued by globalkeysd) with their respective processes (hide it under spoiler or something). This would help in determining which applications hold keybindings.

**Comment by jleclanche** [comment]
I don't think this is possible.

**Comment by kuzmas** [comment]
We can determine whether particular combination of modifiers and a key is already registered by trying to register it to us and then releasing. More than 100 keys (plus multimedia keys for any possible keyboard) multiply by at least Ctrl | Alt | Shift | Meta | Level3 | Level5 … modifiers in all combination more than 10 000 combinations. And in addition there is no way to figure out which app registered particular combination.

**Comment by Vladimir-csp** [comment]
Aren't there any X11 calls to return the list?

**Comment by kuzmas** [comment]
Tell me if you know

**Comment by Vladimir-csp** [comment]
Unfortunately, I do not.
