### ISSUE TITLE
Status Notifier plugin to automatically register items

### ISSUE THREAD

**Issue by paulolieuthier** [lxde/lxqt#531]
Since the most recent changes of @equeim to his plugin, the status notifier watcher doesn't automatically register new items. I have to open Qt's QDBusViewer and call the watcher's `RegisterStatusNotifierItem` manually.

I'm no dbus jedi. @PCMan @luis-pereira @surlykke @kuzmas I believe some little thing is missing. Please take a look at the [plugin](https://github.com/lxde/lxqt-panel/tree/master/plugin-statusnotifier).

**Comment by palinek** [comment]
@paulolieuthier tried to run the new plugin and for me blueman-applet landed immediately in it

**Comment by paulolieuthier** [comment]
Fixed.
