### ISSUE TITLE
Status Notifier plugin's license

### ISSUE THREAD

**Issue by paulolieuthier** [lxde/lxqt#532]
I don't know much about licensing. The original plugin is [GPLv3'd](https://github.com/equeim/lxqt-panel-plugin-snw/blob/master/LICENSE). Is that compatible? What about the license notes we add to the files? There should be a README in the plugin's folder explaining it's a fork or something?

**Comment by jleclanche** [comment]
@PCMan knows better than I.

**Comment by jleclanche** [comment]
We could ask the original author to relicense?

**Comment by paulolieuthier** [comment]
@equeim ping.

**Comment by PCMan** [comment]
Our lxqt-panel is "LGPL2", but the original author of this plugin made the plugin GPL'd.
So, if it becomes part of lxqt-panel, which makes lxqt-panel a derived work of that GPL'd plugin, our code will be "upgraded" to GPL, too.
It's better to:
1. Ask if the author is willing to relicense the plugin in LGPL instead.
2. Move the module out of lxqt-panel source tree and make it a separate package.

BTW, copyright notice and license declaration, which are required by either GPL or LGPL, are missing from the headers of all source files. We need to update the file headers before moving this stuff to "master".

**Comment by jleclanche** [comment]
> BTW, copyright notice and license declaration, which are required by either GPL or LGPL, are missing from the headers of all source files.

Quick correction: License headers are *recommended*, not required. I'm currently dealing with license header issues in Pootle and once I'm done with them, I'd like to do a header review in lxqt as well.

**Comment by equeim** [comment]
I won't continue to work on this plugin, so that I could change the license.

**Comment by jleclanche** [comment]
@equeim does that mean you are OK with relicensing LGPL2?

**Comment by equeim** [comment]
Yes.

**Comment by jleclanche** [comment]
Great. @paulolieuthier do you want to take care of relicensing? Just need to add the headers as the LICENSE files already makes everything lgpl2

**Comment by paulolieuthier** [comment]
@jleclanche what LICENSE file are you talking about? https://github.com/lxde/lxqt-panel/blob/master/plugin-statusnotifier/LICENSE is GPL.

**Comment by jleclanche** [comment]
That file needs to be dropped.

**Comment by paulolieuthier** [comment]
Will do.

**Comment by paulolieuthier** [comment]
Done.
