### ISSUE TITLE
LXQt panel: don't manage plugins from their context menu only

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#536]
Both opening a plugin's configuration window and changing plugins' order within panel ("Move") can be achieved by opening the context menu of a plugin itself only.
![panel plugin configuration](https://cloud.githubusercontent.com/assets/9860801/6623596/29df9dc0-c8e4-11e4-8a40-67e1cbfecdac.png)
This can be quite a tricky task in many situations. E. g. panel plugins may be invisible right after adding such as spacer by default or both Status Notifier and System Tray if they happen to be empty. If Task Manager is using all horizontal space available it's not exactly easy to access its context menu either. Quick launch's context menu seems to get lost as well as soon as only a single icon is added.

Thus I think an additional way both to open configuration dialog windows and move plugins within the panel should be established.

At a glance I was wondering whether this could be achieved by modifying dialog window "Add Panel Widget":
E. g. the UI could be changed to use two tabs. One providing the available plugins, hence the content as is right now. The other tab could summarize all plugins that have been added already. That second tab could hence provide both access to those configuration windows and allow for changing the plugins' order.
Something roughly similar can e. g. be found in Xfce.

**Comment by Vladimir-csp** [comment]
I second this.
LXpanel plugins dialog was very handy at adding/removing/reordering/configuring plugins, all in one place.
XFCE's highlighting in panel editing mode is also a thing to consider.

**Comment by excalibur1234** [comment]
i think this is important.

when you create multiple quick launch icons on the panel (with multiple quick launch widgets) it is really hard to move/arrange them the way you want.
please add an right-click "move" option to quick launch widget or do as pmattern suggested.

**Comment by palinek** [comment]
@pmattern @Vladimir-csp can you, please, test if the new "manage plugins dialog" is good enough for your requests?

**Comment by pmattern** [comment]
The dialog you're proposing works and the main problem addressed in this issue is solved. Yet I'd like to propose two changes:

I doesn't seem too intuitive to me that there's a context menu that can be used to configure plugins added already.
Maybe it would be good to add another button "Configure" or so next to "Add Widget" that provides the same items as those context menus. A button like this could be greyed by default and made usable only if a plugin already added to the panel is selected in the dialog window's list.

I think it would really be better if the list was displaying only plugins that have been added already, each instance represented by a separate line.
The idea is that this change would make configuring plugins from the dialog window much easier. Right now users have to scroll through a list comprising all plugins in an order totally independent from the one of those already added to the panel. This can be a bit cumbersome, in particular if one doesn't remember a plugin's name. If on the other hand the list was comprising only the plugins added to the panel in their respective order it would be pretty easy to find a plugin that should be configured.
To add plugins to the panel button "Add Widget" could be changed to bring up another dialog window.
All this is roughly implemented in Xfce
![xfce4 panel configuration](https://cloud.githubusercontent.com/assets/9860801/7005115/4d03ee88-dc75-11e4-87b7-8cbd61211c11.png)
(Note this screenshot is meant as an example implementing the changes proposed in this paragraph only. I do *not* think all the rest should be adapted to Xfce. E. g. I do not think panel configuration as a whole should be handled by a single dialog window providing tabs or so. Rather, I think dialog window "Manage Panel Plugins" should basically just stay as is right now.)
As a side effect moving plugins could be made easier that way, too. In addition to the means available by now plugins could be re-arranged by dragging & dropping in the list or introducing arrow buttons as seen in the screenshot.

**Comment by palinek** [comment]
@pmattern I've just added the 'Manage widget(s)' (because there all actions that the plugin is providing, not just the configure dialog) button in lxde/liblxqt@a844118.
I would suggest to close this issue and discuss all "next" design \& behaviour suggestions in new issue.

**Comment by pmattern** [comment]
> I would suggest to close this issue and discuss all "next" design & behaviour suggestions in new issue.

Agree. In particular as I'm not that sure any more whether dialogues "Configure panel" and "Manage panel widgets" shouldn't be unified after all.
