### ISSUE TITLE
graphical sudo/su

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#537]
Right now there are no viable independent graphical sudo/su. Kdesudo pulls a lot of KDE dependencies, gksu requires gconf. For a modular QT based DE there should exist simple lightweight graphical sudo/su tool.

**Comment by palinek** [comment]
How about pkexec(http://www.freedesktop.org/software/polkit/docs/0.105/pkexec.1.html)?

**Comment by Vladimir-csp** [comment]
It is a component of policykit. And is it QT?

**Comment by Vladimir-csp** [comment]
And it also restricts launch of GUI apps by default, only with exceptions.

**Comment by Esclapion** [comment]
It's an important question, because in my lxqt there are only 3
dependencies to gtk3 : gnome-keyring and gksu, lightdm (can be replaced by
sddm), and network-manager-applet.

I tried in the past gtksu, bu no success, it's more a su than a sudo, and
the gui is not nice.

2015-03-13 7:54 GMT+01:00 Vladimir-csp <notifications@github.com>:

**Comment by alfredobonino** [comment]
I'm writing a graphical sudo, soon I will publish the source code and will make a pull request

**Comment by alfredobonino** [comment]
Assign me this

**Comment by alfredobonino** [comment]
I publish the code to https://www.github.com/alfredobonino/qsudo

**Comment by paulolieuthier** [comment]
@alfredobonino that's very good news. I'll take a look at that as soon as I can.

**Comment by Esclapion** [comment]
Works for me, thanks :-)

2 little things : the password must be hidden by default, I think, and I
must press Enter to leave, else it never finish.

2015-05-15 18:57 GMT+02:00 Paulo Lieuthier <notifications@github.com>:

**Comment by alfredobonino** [comment]
Now, the password is hidden.

**Comment by alfredobonino** [comment]
Pcmanfm-qt use gtksu, Why when qsudo are stable, use qsudo instead of gtksu?

**Comment by paulolieuthier** [comment]
@PCMan what do you think?

**Comment by alfredobonino** [comment]
The only function to implement are the focus to the "ok" button and display the name of the program that ask for root.

**Comment by alfredobonino** [comment]
qsudo funzionando in modo simile a gksu, se voi create un link simbolico da qsudo a gksu, quindi gksu diventa un link simbolico, tutti i programmi che usano gksu, in automatico usano qsudo, l'ho testato con pcmanfm-qt, e funziona molto bene, basta un link simbolico. 
nel frattempo che @PCMan decida se inserire o no qsudo.
Queste sono immagini, con pcmanfm-qt che usa qsudo:

![1](https://cloud.githubusercontent.com/assets/7737749/7669710/5081adde-fc82-11e4-8868-8911bb60a838.png)
![2](https://cloud.githubusercontent.com/assets/7737749/7669711/585416e6-fc82-11e4-9be9-3189b384aa9a.png)

**Comment by alfredobonino** [comment]
@Esclapion, all of the feature you requested are added.

**Comment by Esclapion** [comment]
Nice, thanks. :-)

2015-05-17 14:20 GMT+02:00 Alfredo Bonino <notifications@github.com>:

**Comment by alfredobonino** [comment]
I am available as a developer, if there is something going on, are available, lxqt is a very interesting project.

**Comment by alfredobonino** [comment]
I have make bugfix in qsudo

**Comment by alfredobonino** [comment]
@Vladimir-csp, what do you think?
You have opened this issue.

**Comment by Vladimir-csp** [comment]
It is looking great!
If everything is fine from security standpoint, then the issue is resolved.

**Comment by palinek** [comment]
I've just had a quick look into the source code and IMHO this easy tool doesn't provide everything what is needed for a "GUI sudo". This just reads a password and starts a detached process (`bash`) to run command we need, but it doesn't provide any feedback upon wrongly typed password.

**Comment by Vladimir-csp** [comment]
Mmissed that.

**Comment by alfredobonino** [comment]
@palinek, I am aware of the problems, in fact I have to implement these two functions, qsudo should also show the program that asks root permissions.

**Comment by alfredobonino** [comment]
However, as I said before, qsudo works similarly to gksu, then to run a program with parameters just run as: 
qsudo "uname -a"

**Comment by palinek** [comment]
```c++
    QProcess *process;
    process = new QProcess();
    QString command = "echo " + ui->rootPassword->text() + " | sudo -S " + program;
    process->startDetached("/bin/bash", QStringList() << "-c" << command);
    process->close();
```
This implementation is obviously not good:
1. `QProcess` instance is needles here (just a leak) as `startDetached()` is a static method
2. in case there are special charactes (from `bash` point of view) in password it can fail

As I see it, you need to directly write/read to child's (`sudo`) stdin/stdout...

And maybe (don't know exactly how `sudo` behaves) after identifying a success, let the `QProcess` object leak (destuctor can't be executed because it will kill the spawned child)..see [here](https://bugreports.qt.io/browse/QTBUG-9328)

**Comment by alfredobonino** [comment]
you written this:
"As I see it, you need to directly write/read to child's (sudo) stdin/stdout...

And maybe (don't know exactly how sudo behaves) after identifying a success, let the QProcess object leak (destuctor can't be executed because it will kill the spawned child)..see here"
But, the source code of kdesudo, use qprocess, kprocess and xauth, but for execute use the program use qprocess->start()...

**Comment by alfredobonino** [comment]
qsudo è un semplice tool. ma credo che non sia implementato male:
1. funziona, il processo si avvia.
2. non ci sono problemi di sicurezza, usa direttamente il comando sudo.
3. qprocess, viene usato anche da kdesudo.
Poi, che ci sono poche funzioni non lo metto in dubbio.

**Comment by pmattern** [comment]
Regarding the installation the final make invocation doesn't seem to accept the usual variable DESTDIR but INSTALL_ROOT only. Is this intended?
FWIW I quickly wrote an Arch Linux [PKGBUILD](https://gist.github.com/pmattern/3a6086cc21fd32e4d8ce) providing latest Git versions of qsudo.

If I'm not mistaken su can't be used as backend but sudo only. This would be a major difference compared to gksu.
The behaviour regarding PCManFM-Qt is quite different. gksu seems to be invoked via its su backend functionality which means it works without any configuration. Unlike this qsudo seems to work only if the user in question had been allowed to run binary pcmanfm-qt as root via sudo. Also, the PCManFM-Qt window opened as root seems to run in a different environment. If gksu is used the window is fine. But if qsudo is used no icons are displayed in the actual panes and the fonts look a bit condensed here.

Even if qsudo works as expected there's still a password prompt on the shell here. E. g. when user peter is allowed to run juffed as root in /etc/sudoers I get
```
$ qsudo juffed 
$ [sudo] password for peter:
```
qsudo's GUI isn't configured to be always on top which would imho make sense. lxqt-openssh-askpass does behave like this, btw. Similarly the cursor isn't automatically placed in the form.
If a program is launched via sudo it's the password of the user who invoked qsudo that has to be provided, not the root password as claimed by the GUI.

Aside from this I have to agree with palinek that pkexec is something that should be considered, too. I mean the configuration isn't exactly trivial but the sudo configuration isn't either if it comes to a bit more sophisticated permissions.
The best thing to have would actually be a GUI that can use any of sudo, su and pkexec as backend. Not sure whether hacking a tool like this is worth the pain, though...

All findings on Arch Linux x86_64 running latest Git versions of qsudo and all LXQt components.

**Comment by palinek** [comment]
> 2. there are no safety issues, use directly the command sudo.

Really? Try to insert `; rm -Rf ~` as the password

> 3. qprocess, is also used by kdesudo

I didn't say it shouldn't be used.

**Comment by alfredobonino** [comment]
Yes, I am aware that if one writes that command (they are also aware that if you start that command all system files are deleted :)), but only if you start qsudo twice through terminal.

**Comment by palinek** [comment]
> Yes, I am aware that if one writes that command (they are also aware that if you start that command all system files are deleted :)), but only if you start qsudo twice through terminal.

Sorry, but I don't follow this...

**Comment by alfredobonino** [comment]
Howewer, i rewrite qsudo with popen.

**Comment by palinek** [comment]
> Howewer, i rewrite qsudo with popen.

Why do you want to do that?
```man
The popen() function opens a process by creating a pipe, forking, and invoking the shell. 
Since a pipe is by definition unidirectional, the type argument may specify only reading or writing, not both;
the resulting stream is correspondingly read-only or write-only.
```
`QProcess` is perfectly suitable for your pupose (just that the object's destructor can't be invoked to not kill the child).

**Comment by alfredobonino** [comment]
And, what is the problem of quasi?

**Comment by alfredobonino** [comment]
I rewrite qsudo with qprocess()->start(),and qprocess->write(password).
Now, With thai method, there aren't securi ty issues.
I publish che code, when che code are stable andò fully functional.

**Comment by alfredobonino** [comment]
@palinek, now what do you think? i have published the new code to https://www.github.com/alfredobonino/qsudo

**Comment by palinek** [comment]
@alfredobonino it's better. But:
- there is still no (negative) feedback -> you also need to read (and parse) sudo's output
- is it actualy working? sudo normaly tries to read password from terminal, but you are writing the password into stdin, AFAIK -S should be used in such case:
```
     -S, --stdin
                 Write the prompt to the standard error and read the password from the standard input instead of using the terminal device.  The password must be fol‐
                 lowed by a newline character.
```

**Comment by alfredobonino** [comment]
It is a feature to implement, it is complicated, because the output of sudo changes for each language, (i'm Italian). However it also works without "-S", before I had entered, but then I saw which it worked without it, so I took it off .... However, it should not work in some particular configuration, the inside again. Now, I think there are no problems of security, right?

**Comment by alfredobonino** [comment]
@pmattern, thank you for the PKGBUILD, your issue are now corrected.
@palinek,Now, qsudo use "-S" sudo argument.

**Comment by palinek** [comment]
> it is complicated, because the output of sudo changes for each language
That's true, but you can set the locale for the child.... nevertheless I personaly would implement it in other way round: using the sudo's -A parameter (which would invoke our `qsudo` process with other name) and -b parameter. Maybe this will be a bit complicated because of IPC, but in this way we don't need to parse sudo's output.

> Now, I think there are no problems of security, right?

I can't say that. I just can say that the previous "bash injection" problem is gone and I currently don't see any security issue in the code.

**Comment by palinek** [comment]
I've just pushed a commit with lxqt-sudo into https://github.com/lxde/lxqt-admin/tree/sudo implemented as I mentioned before.
@Vladimir-csp, @paulolieuthier, @pmattern, @alfredobonino  what's your opinion on that?

**Comment by paulolieuthier** [comment]
As I commented in the commit page, it looks very good. Please file the PR.

**Comment by renaldi2108** [comment]
the purpose of the "program=QCoreApplication::arguments().at(1);" then what? And there are parts qlist error that states"index out of range". Please enlightenment on this issue.

**Comment by palinek** [comment]
> the purpose of the "program=QCoreApplication::arguments().at(1);" then what? And there are parts qlist error that states"index out of range". Please enlightenment on this issue.

@renaldi2108 If you wish to discuss about https://www.github.com/alfredobonino/qsudo, please, make it there. That project isn't covered by LXQt.

**Comment by alfredobonino** [comment]
The project qsudo are been abbandoned. please move to lxqt-sudo.
