### ISSUE TITLE
LXQt panel/Volume control: UI improvements

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#538]
Both string "Mixer" and the speaker icon can be recognized as buttons only on hovering. By default they look like some ordinary text and icon.
![volume control](https://cloud.githubusercontent.com/assets/9860801/6639991/a8ded112-c994-11e4-92fb-8eb514d22c72.png)
I think it would be better to have them recognizable as button by default.

Using theme Light their appearance even doesn't change on hovering.

It would be good if the actual volume was displayed as percentage. This affects hovering over the panel icon as well as hovering over or moving the actual UI's ruler.

The area set aside for string "Mixer" seems to be way fixed. Hence larger fonts get cut, see screenshot.

**Comment by intialonso** [comment]
Hello. The look of this buttons is set in consonance with the rest of the panel theme, I will look for a way to make them more obvious.

The Light theme need an update in this, thank you for he report.

I dont know how this percentage will work, may be is not a theme thing.

The issue with the "Mixer" button is a know problem, Im looking for a way to solve that.

**Comment by paulolieuthier** [comment]
The Mixer button is a QPushButton with `flat` set to true. See the [docs](http://doc.qt.io/qt-5/qpushbutton.html#flat-prop). That can be changed, of course.

**Comment by palinek** [comment]
The commit just takes care of the tooltips... reopening

**Comment by palinek** [comment]
@pmattern can you, please, check if lxde/lxqt-panel@9bc1ea7 together with lxde/lxqt-common@e08aa2b fix this?

**Comment by pmattern** [comment]
The actual issue is fixed in all themes shipping with lxqt-common. There are just some minor details left, improving these could make things look even a bit better, imo:

The frames around string `Mixer` and the speaker icon seem to behave differently regarding their horizontal size. Thus if rather large fonts are chosen, the former is wider than the latter which doesn't look good.
In themes Ambiance, Dark and Light the corners of those frames aren't rounded any longer if highlighted which looks a bit odd. This is particularly striking in themes Ambiance and Light due to the colors of the frames (which themselves don't need to be changed).
The speaker icon seems to be of constant size. It would look better if this could somehow be adjusted according to the front size of string `Mixer` which of course wouldn't have to be done continuously.

**Comment by palinek** [comment]
> In themes Ambiance, Dark and Light the corners of those frames aren't rounded any longer if highlighted 

changed in lxde/lxqt-common@7645bbc
