### ISSUE TITLE
StatusNotifierItems' menus are broken

### ISSUE THREAD

**Issue by paulolieuthier** [lxde/lxqt#539]
We are probably not using DBusMenuImporter broken.

**Comment by MttCastelli** [comment]
No more icons (removable device and mixer volume too)!

(Lubuntu vivid + lubuntu-dev PPA + lxqt-metapackage - both qt4 and gtk stacks removed as possible)

![lxqt_session_13031015update](https://cloud.githubusercontent.com/assets/11462157/6641926/38f143aa-c9a1-11e4-9aa1-818f38db1a18.jpg)
 !first post on github!

**Comment by paulolieuthier** [comment]
@MttCastelli that's a different issue.

**Comment by MttCastelli** [comment]
sorry, I'm new here...

**Comment by palinek** [comment]
Fixed by lxde/lxqt-panel@aed01a20eb4b4503ccc7bfa87a86573d4fe48163
