### ISSUE TITLE
sni-qt created invalid StatusNotifierItems

### ISSUE THREAD

**Issue by paulolieuthier** [lxde/lxqt#540]
sni-qt creates StatusNotifierItems that does not have the `org.kde.StatusNotifierItem` field to get the StatusNotifierItem information from. I don't know much of DBus yet, I don't know how to check if the field exists.

**Comment by paulolieuthier** [comment]
I cannot reproduce it anymore, but the bug may still exist, as it depends on the applications being run. Closing.

**Comment by palinek** [comment]
...and this https://github.com/lxde/lxqt-panel/blob/master/plugin-statusnotifier/statusnotifierbutton.cpp#L55 is still needed ?

**Comment by paulolieuthier** [comment]
Well, that is needed to be future-proof. It protects us for showing corrupted status notifier items. But doesn't solve the whole problem. And the problem was that those corrupted items hanged the plugin for some seconds, blocking the UI thread.
