### ISSUE TITLE
lxqt-panel won't compile when disabling statically linked plugins

### ISSUE THREAD

**Issue by hashashini** [lxde/lxqt#542]
lxqt-panel won't compile when disabling statically linked plugins, e.g. with -DCLOCK_PLUGIN=OFF:
Linking CXX executable lxqt-panel
CMakeFiles/lxqt-panel.dir/plugin.cpp.o: In function LxQtClockPluginLibrary::LxQtClockPluginLibrary()':
[...]/lxqt-panel/panel/../plugin-clock/lxqtclock.h:95: undefined reference to `vtable for LxQtClockPluginLibrary'

**Comment by paulolieuthier** [comment]
@hashashini please confirm it.

**Comment by hashashini** [comment]
confirmed; compilation successful with -DCLOCK_PLUGIN=OFF -DDESKTOPSWITCH_PLUGIN=OFF  -DMAINMENU_PLUGIN=OFF -DQUICKLAUNCH_PLUGIN=OFF -DSHOWDESKTOP_PLUGIN=OFF -DSTATUSNOTIFIER_PLUGIN=OFF -DTASKBAR_PLUGIN=OFF -DTRAY_PLUGIN=OFF -DWORLDCLOCK_PLUGIN=OFF
