### ISSUE TITLE
LXQt notificationd: improvements regarding messages

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#543]
LXQt notificationd doesn't consider control characters indicating line breaks in messages' body.
E. g. compare the output of Arch Linux update notification tool aarchup which is using '\n' on Xfce
![notificationd xfce](https://cloud.githubusercontent.com/assets/9860801/6686938/544b3068-cca6-11e4-83db-830a9e0cc1eb.png)
and on LXQt
![notificationd lxqt 10px](https://cloud.githubusercontent.com/assets/9860801/6686940/5c6e3380-cca6-11e4-83a0-6febad4a4476.png)
(the additional line "New Updates" is simply the "Application Name" as defined in the underlying [Desktop Notifications Specification](http://www.galago-project.org/specs/notification/0.9/x81.html) which is skipped by Xfce's daemon)
Tests involving binary notify-send indicate that Xfce's implementation is considering '\r' as well which LXQt notificationd doesn't either. Not sure whether considering '\r' on *ix systems makes any sense, though.
According to the said Specification handling line breaks in message bodies seems to be up to the server implementations. But I can't figure any downside due to respecting control characters explicitly stated within the message body and hence think it's something that should be done.

There's some interference between "Spacing" as set in lxqt-config-notificationd's Advanced settings and the portion of the message body that gets displayed.
E. g. LXQt screenshot seen above was taken with 10px and shows a part of the list only. To have this particular message shown completely spacing had to be set to about 70px
![notificationd lxqt 70px](https://cloud.githubusercontent.com/assets/9860801/6687321/6336629c-ccaa-11e4-892a-56734b832464.png)
I'm not sure about the purpose of spacing in the first place. But it seems to correspond to the spacing between pop-up and display borders and as such shouldn't have any impact on the message itself.

**Comment by palinek** [comment]
Body in the notification area is a ```QLabel``` which actualy support plain text and also rich text (some markdown - subset of HTML).
Currently the label's ```textFormat``` is ```RichText``` and therefore `\n` is just treated as a white space.
IMO there are 2 possible ways:
- change label to be ```AutoText``` -> Qt decites if the string is a rich text formatted or not (tested with e.g. ```"<b>test-bold</b>\ntest"``` and this is treated as plain text)
- manualy translate '\n' into "<br/>" if there is no markdown
