### ISSUE TITLE
startlxqt: LibreOffice tries to use Qt3 VCL plugin

### ISSUE THREAD

**Issue by GreatEmerald** [lxde/lxqt#544]
The startlxqt script currently exports the `SAL_USE_VCLPLUGIN` variable as `kde`. That's wrong, because that's Qt3 (KDE 3) support, and on most modern systems results in LibreOffice falling right back to the GTK2 theme (or if there's no GTK2 installed, the X11 "Redmond" theme). The value for Qt4 support, instead, is `kde4`.

The exact line that should be changed is this:
https://github.com/lxde/lxqt-common/blob/master/startlxqt.in#L27

In the mean while a workaround for this is to put `SAL_USE_VCLPLUGIN=kde4` in the LXQt session config Advanced page.

**Comment by jleclanche** [comment]
Why do we set this at all?...

**Comment by GreatEmerald** [comment]
Because the gtk2 plugin is the default:
https://wiki.archlinux.org/index.php/LibreOffice#Theme
