### ISSUE TITLE
Languages, locales and formats support

### ISSUE THREAD

**Issue by gilir** [lxde/lxqt#546]
Just for the record, I would like to work on a languages switcher for lxqt, similar to formats settings in plasma : http://vizzzion.org/blog/2014/05/locale-changes-in-plasma-next/

It will probably be a lot of copy/paste from the KDE one (since it's quite simple and based on QLocale), except maybe the exporting script.

Any comments and feedbacks are welcome :-) Since it's my first real experience in C++, Qt and lxqt-config module, don't expect it tomorrow :-)

**Comment by pmattern** [comment]
IMO this one can get closed as the feature got introduced in the meantime in lxde/lxqt-config#55 and lxde/lxqt-config#62. Some minor polish is left to be done but should better get addressed in an issue on its own.
