### ISSUE TITLE
LXQt panel/plugin desktopswitch: add option to display desktop names instead of desktop indexes

### ISSUE THREAD

**Issue by npmiller** [lxde/lxqt#553]
I've been using LXQt with i3 and given the way i3 handles desktops, I end up with things like a desktop that is displayed as 5 in the desktopswitch, but that is really the number 8 for i3. 

Hopefully, the names of the desktops (as displayed in the tooltips), match with i3's desktop numbers. So I thought it would be useful to add an option whether to display desktop names or use the current behaviour.

Apart from my use case, I believe this option might be useful to other people.

I've started looking around the code, it seems pretty straightforward to do, so I will probably try to implement it myself later.

**Comment by palinek** [comment]
fixed in lxde/lxqt-panel#157
