### ISSUE TITLE
Desktop Switcher misses desktop changes

### ISSUE THREAD

**Issue by ypnos** [lxde/lxqt#554]
This is a regression of 0.9. The desktop switcher only shows 6 desktops. However, I have twelve of them.

xprop -root shows:

    _NET_DESKTOP_NAMES(UTF8_STRING) = "browse", "mail", "main_trois", "ide", "foo", "bar", "tex", "write_deux", "write_trois", "admin_un", "root", "admin_trois"
    _NET_NUMBER_OF_DESKTOPS(CARDINAL) = 12

**Comment by palinek** [comment]
@ypnos can you, please, be more specific on what configuration the is present?
(for me (debian testing, LxQt packages from siduction, openbox) this issue is not reproducable)

**Comment by ypnos** [comment]
I use Arch Linux, lxqt-panel-git version 0.9.0.29.g33a689e-1. I use herbstluftwm as a window manager.
With version 0.8, it was working fine.

**Comment by ypnos** [comment]
I don't know what happened, but lxqt-panel now shows all 12 desktops again. Will probably make it harder to track this one down :/

**Comment by palinek** [comment]
@ypnos there were been made changes in this plugin recently (few days ago). Can you, please, test if this problem still persists?

**Comment by paulolieuthier** [comment]
herbstluftwm is known to be problematic. It's weird that it worked on 0.8 and doesn't work now.

**Comment by ypnos** [comment]
I tested and could not reproduce this problem anymore.
