### ISSUE TITLE
lxqt-panel/plugin-taskbar: Text/Icon layout issues

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#556]
One image is better than 1000 words:
![screen-2015-03-25-10-36-32 png](https://cloud.githubusercontent.com/assets/62877/6831224/237fdfc4-d2dc-11e4-937c-e0f5d535019a.jpg)

**Comment by palinek** [comment]
sure..
I'm only guesssing -> the problem is missing icon in taskbar group popup and text centered with long window title?
How to reproduce? I get no such behaviour:
![screenshot](https://cloud.githubusercontent.com/assets/10990929/6842747/c2cdd94a-d39b-11e4-8ea5-be5387cbc4cb.png)

**Comment by luis-pereira** [comment]
It happens when the text is longer that the space provided.
Example: Open this link https://github.com/lxde/lxqt-panel/commit/2c38da717f742c40c53ce8dcbcb3ba9951675689

**Comment by palinek** [comment]
As you can see in my previous comment (and the screenshot)... it doesn't happen here. Also not for browser and the provided link:
![screenshot](https://cloud.githubusercontent.com/assets/10990929/6857699/f77801c6-d408-11e4-8163-86a31ec48488.png)

**Comment by luis-pereira** [comment]
@palinek I'm seeing. What's even weirder is that my text is always centered. Will debug it when I get to my dev machine.

**Comment by luis-pereira** [comment]
@palinek It seems it happens when one have many (3 to me) windows in one desktop. Can you pls try to confirm it ?

**Comment by palinek** [comment]
@luis-pereira nope... not here:
![screenshot](https://cloud.githubusercontent.com/assets/10990929/6863691/1360125a-d456-11e4-96ba-b627d47b18e9.png)

Could it possibly be connected to version of qt used?

**Comment by luis-pereira** [comment]
@palinek Yesterday I could reproduce it. Today I can't. Running the same qt version.

**Comment by gbcox** [comment]
I don't know if this is the same issue or not but I'm noticing that chrome icon isn't showing correctly on the task switcher... I've attached a screenshot.  I haven't noticed any problems with Chrome and the task switcher on KDE so thought I would report it.  I haven't noticed an issue with any other application yet.

![screenshot - 04142015 - 01 06 43 pm](https://cloud.githubusercontent.com/assets/4543019/7146269/355b487a-e2a7-11e4-87ee-18aa43253a8d.png)

**Comment by gbcox** [comment]
I upgraded my Fedora installation to F22 which uses Kwin 5 and the problem went away.
