### ISSUE TITLE
Translation source not up to date in taskbar-plugin

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#557]
http://i.imgur.com/YUkZwjR.png 
<img src="http://i.imgur.com/7teyMOa.png" />
I find no item for window grouping  in taskbar.ts ,  taskbar_it_IT.ts ecc.
"show windows from" is    translated but does not get into the Gui.

**Comment by luis-pereira** [comment]
@stefonarch Just updated the translations sources. Update to the latest master.
Closed by lxde/lxqt-panel@d1e4ac7fbf2cc322bd9306b85b770123127283d4
