### ISSUE TITLE
"Status notifier plugin" cannot be configured, moved and removed

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#558]
With lxqt-panel-git-0.9.0.67 at startup it looks like that:
<img src="http://i.imgur.com/xVJN2bj.png" />
After a first  right-click it shows me konversation, akregator and klipper, but no way to configure or remove it. right click does nothing.
Expected behavior: Right-clicking should show menu "move, configure, remove".

**Comment by palinek** [comment]
PR for managing plugins from "add plugin dialog" was just merged -> lxde/lxqt-panel@a6554fa. So now all plugins could be moved also from this dialog.
