### ISSUE TITLE
Panel startup with auto-hide is never shown

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#559]
The panel hides before it is shown

**Comment by palinek** [comment]
Isn't that a desired behaviour?

**Comment by luis-pereira** [comment]
@palinek IMO no. The panel hides when not being used. lxqt starts and it not's get used it auto-hides. It it doesn't show a user can think that it didn't start.

**Comment by Vladimir-csp** [comment]
If default behavior is to always show the panel, then I see no problem. User switches autohide on, it is users`s decision, he is aware of it.
The other two questions are technical and cosmetic:
- panel should have a presence on screen, at least one pixel, so mouseover could be possible.
- this presence can be invisible (transparent), why not?

**Comment by luis-pereira** [comment]
@Vladimir-csp the technical and cosmetic are not related to this issue.

**Comment by palinek** [comment]
@luis-pereira you are suggesting that the panel should be fullsize after `lxqt-panel` start and hide after some time? Or should it hide after it receives-looses the mouse?

**Comment by paulolieuthier** [comment]
IMO, "should be fullsize after lxqt-panel start and hide after some time".

**Comment by luis-pereira** [comment]
IMO should be fullsize when it starts and hide after some time without being used.
