### ISSUE TITLE
XdgIcon & QIcon are very inefficient and caused slow startup.

### ISSUE THREAD

**Issue by PCMan** [lxde/lxqt#56]
In the internal implementation of QIcon::fromTheme, there is a very inefficient design.
See QThemeIconEntries QIconLoader::findIconHelper() of qiconloader.cpp for detail.
It tries to search in all icon directories with all possible filename extensions and all possible sizes for a given icon name.
This results in more than 1000 stat() system calls for _each_ icon.
The gtk+ icon theme implementation only scan the icon dir once, and use the cached info everytime so it's much faster. Gtk+ also supports its own icon cache format.
We need our own implemention of QIconEngine to replace the flawed Qt implemention.

**Comment by jleclanche** [comment]
This is about to be dropped for the 1.0 milestone. Critically needs someone to look at it.

**Comment by paulolieuthier** [comment]
It will take time. Drop it. :disappointed:

**Comment by palinek** [comment]
Isn't the usage of GTK icon cache enough (in Qt -> https://github.com/qt/qtbase/commit/e68d06714fa29f986d0fc7de324b79ea94493dfc, in libqtxdg -> https://github.com/lxde/libqtxdg/commit/81112762d6a74bd8188acf00d7a6469f5541e035) ?
