### ISSUE TITLE
Overriding Lxqt keybindings in favor of WM's

### ISSUE THREAD

**Issue by pibarnas** [lxde/lxqt#562]
It would be nice if there were a method to use openbox own keys stored in rc.xml instead of lxqt ones. I explain: I use openbox for decades, and I'm used to uncompress its backup config on each desktop I have. Some things like closing windows with "windows" key+space can't be done only uncompressing my tar file on ~/ .config, just because something in the Lxqt inner, that could be switched off, I think. I bet it is the lxqt shortcut (keybindings) app and schema. Some could say "go use lxde then", but I think, for openbox hard users, it is a good feature on the new DE.

**Comment by Vladimir-csp** [comment]
Make lxqt-globalkeys optionally use openbox as backend?

**Comment by jleclanche** [comment]
No, if we're going any route it's the kglobalaccel way.

**Comment by palinek** [comment]
@pibarnas you can override default shortcuts registered by any lxqt component in `lxqt-config-globalkeys`.
Have a look into `~/.config/lxqt/globalkeyshortcuts.conf`. If you prefer you can replace it at the same time when you replace the openbox configuration.

**Comment by pibarnas** [comment]
palinek: Excellent!! Thank you! That's what I've been looking for: some config text file to call with editor on openbox menu (I use wm menu on DE) and save on a tar file. Although the flashy new features of LXQT are much awaited and great, towards ease of use, I think it's important for the new DE don't lose it's core of minimalism and the simpathy of the box* users. Early gnome experience shows what happen to a DE that turn back to its users. Keep up the good work, and thank you once more!
