### ISSUE TITLE
Configuration center nearly empty

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#563]
Compiling latest Git code of all LXQt components the usual way results in a "Configuration center" (binary lxqt-config) that's nearly empty.

More precisely neither the items provided by lxqt-config nor lxqt-admin (repo / component) are displayed, rather only some provided by different components such as pcmanfm-qt --desktop-pref, ObConf-Qt or ComptonConf.
All items lacking in Configuration center do get displayed in Application menu and work as expected if launched that way.

IIRC problem couldn't be seen after compiling latest Git code 2015-03-23 and hence seems to be a regression introduced since. Doesn't seem to be lxqt-config's fault as downgrading to 1b6f7c6 didn't help but the problem couldn't be seen before running this commit and its successors.
Seen on Arch Linux i686 and x86_64.

**Comment by MttCastelli** [comment]
the same here whith the latest lubuntu-daily update, can see only Desktop and Monitor settings

**Comment by agaida** [comment]
the problematic code is in libqtxdg/xdgmenuapplinkprocessor.cpp:
<pre>
        XdgDesktopFile* file = fileInfo->desktopFile();

        bool show = false;
        QStringList envs = mMenu->environments();
        const int N = envs.size();
        for (int i = 0; i < N; ++i)
        {
            if (file->isShown(envs.at(i)))
            {
                show = true;
                break;
            }
        }
</pre>

unfortunally i'm to dumb to debug this. @luis-pereira, @paulolieuthier  - any ideas?

**Comment by palinek** [comment]
@agaida don't be so shy. You got it almost... IMHO the problem here is that we are testing 3 environments:
```c++
        XdgMenu xdgMenu;
        xdgMenu.setEnvironments(QStringList() << "X-LXQT" << "LXQt" << "LXDE");
        bool res = xdgMenu.read(menuFile);
```
...but the `XdgDesktopFile::isShow` is 'cashing' the result right after the first attempt. That means if the *.desktopfile does not contain `OnlyShowIn=*X-LXQT*` it caches the `false` result and fails in next call whatever the environment parameter comes in.  When I removed the false result caching, configuration window get populated well:
```c++
--- a/xdgdesktopfile.cpp
+++ b/xdgdesktopfile.cpp
@@ -1186,10 +1186,11 @@ bool XdgDesktopFile::isShow(const QString& environment) const
 
 bool XdgDesktopFile::isShown(const QString &environment) const
 {
     if (d->mIsShow != Undef)
         return d->mIsShow == True;
 
-    d->mIsShow = False;
+    //d->mIsShow = False;
     // Means "this application exists, but don't display it in the menus".
     if (value("NoDisplay").toBool())
         return false;
```

@luis-pereira If we want to cache the `XdgDesktopFile::isShow` result we probably need to cache it per environment, that means change the `mIsShow` from simpe `Triple` into `QHash<QString, Triple>`

**Comment by agaida** [comment]
@palinek - i'm not shy, but i don't know how to debug this. C++ isn't my prefered playground :)

**Comment by luis-pereira** [comment]
@palinek @agaida You are both right.
The trigger is:
```if (file->isShown(envs.at(i)))```

in conjunction with:

```
    if (d->mIsShow != Undef)
        return d->mIsShow == True;
```

The current "caching" mechanism doesn't make any sense and it makes ```XdgDesktopFile::isShown()``` unusable.
I'm fixing this.

**Comment by luis-pereira** [comment]
@agaida @palinek @pmattern https://github.com/lxde/libqtxdg/issues/55
