### ISSUE TITLE
LXQt panel: don't provide lock screen feature by two different panel objects

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#564]
Locking screen is provided by two different panel objects behaving and looking the same which is unnecessary and rather confusing.

First, there's plugin-screensaver. Development is taking place sporadically only and it indeed looks a bit outdated. E. g. all the description as displayed in dialog "Add Plugins" isn't valid any longer as the plugin allows for locking the screen only right now, not for launching a screensaver.
Second, there's invocation `lxqt-leave --lockscreen` of binary `lxqt-leave` which is maintained far more actively. The particular invocation is provided by a desktop entry file that's in turn provided by plugin-mainmenu and can hence be integrated into the panel via plugin-quicklaunch easily. In #437 it was agreed to have all actions dealing with the session handled by `lxqt-leave` and its corresponding desktop entry files.

So maybe just drop the panel plugin?

**Comment by palinek** [comment]
I'm also for dropping the plugin-screensaver

**Comment by palinek** [comment]
Are we going to drop the plugin-screensaver?

**Comment by luis-pereira** [comment]
I'm also in favor of dropping it. The only issue I foresee is that the `Lock Screen` menu entry can only be dragged to the quicklaunch area.

**Comment by paulolieuthier** [comment]
I'm in favor of dropping it as well.

**Comment by pmattern** [comment]
@luis-pereira 
If I'm getting you right eventual problems due to this can be mitigated by running several instances of plugin-quicklaunch in parallel, can't they?

**Comment by luis-pereira** [comment]
@pmattern In theory Yes. In  practice, I'm not sure if an "average" user would have the insight to add another plugin-quicklaunch to place lxqt-leave actions.

**Comment by pmattern** [comment]
@luis-pereira 
Basically agree here, too.
But considering the condition of LXQt on a new profile I guess users will understand. I mean all other items like shutdown, restart or logout have to get d&d'ed to plugin-quicklaunch as well and adding several instances of arbitrary plugins from dialog "Configure Panel" seems to be something that gets adopted quickly, too.
So all in all I think we could attempt to just drop the plugin and see what happens.

**Comment by paulolieuthier** [comment]
> In practice, I'm not sure if an "average" user would have the insight to add another plugin-quicklaunch to place lxqt-leave actions.

I agree. Ideally, we'd seek for user feedback to know how many users use the plugin.

**Comment by paulolieuthier** [comment]
* Reddit: https://www.reddit.com/r/LXQt/comments/4q9grj/about_dropping_the_lock_screen_panel_widget/
* ML: https://sourceforge.net/p/lxde/mailman/message/35187715/

**Comment by stefonarch** [comment]
My 2 cents or 2 thaughts: better offering 2 ways than one,  and what about replace it with a panel plugin which let the user include one or more items from the lxqt-leave stuff?  Creating another quicklaunch and dragging stuff needs some skills.

**Comment by maverick74** [comment]
As a user I'm not sure i'm getting the idea...

If there are 2 things doing the "same thing" i'm all in favor of dropping one of them (there's no point in having 2!).

From what i understand we're talking about the "object" that has the Leave/LogOut option in it. If that's what we're talking about, as far as i get a "start menu" entry allowing me to "leave" i'm a happy user!

(hope i understood the idea right)

**Comment by stefonarch** [comment]
No, it's about the  panel widget "screensaver",  I think you mean the "leave" window with several options. 
Actually there even are three ways to lock the screen: from menu, panel widget and the menu in runner > arrow down

**Comment by maverick74** [comment]
Yes, at home i was able to see my mistake! I'm fine with you removing it (i won't miss it :)

**Comment by maverick74** [comment]
I've been thinking about this and there is one thing - not really related - i don't understand: why isn't it under the "leave" sub-menu?

I think it would make perfect sense having it there instead of being in the "main menu"... (sorry for the Off-topic)

**Comment by palinek** [comment]
Please, have a look on the lxde/lxqt-panel#363. It implements also a simple "backward compatibility".
