### ISSUE TITLE
LXQt-panel: Saving changes in cpu-load and spacer plugin crashes panel

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#565]
I use normally 2 panels;after upgrading from git panel crashed always when trying to save changes in these two objects.
Removing ~/.config/lxqt/panel.conf solved.

**Comment by palinek** [comment]
Could you, please, provide the "failing" configuration so we are able to reproduce the crash?

**Comment by stefonarch** [comment]
Here it is:

[General]
__userfile__=true
panels=panel_{6694bbd1-2f06-4cde-8907-e480059ea869}, panel_{cac5188a-57a2-43cf-a07b-653532a2800d}

[clock2]
UTC=false
alignment=Right
autoRotate=true
customDateFormat=
dateFormat="dddd, d MMMM"
firstDayOfWeek=7
showDate=below
timeFormat=HH:mm
type=clock

[cpuload2]
alignment=Right
type=cpuload

[desktopswitch2]
alignment=Left
type=desktopswitch

[mainmenu2]
alignment=Left
type=mainmenu

[panel_%7B6694bbd1-2f06-4cde-8907-e480059ea869%7D]
alignment=0
background-color=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
iconSize=31
lineCount=1
opacity=33
panelSize=47
plugins=mainmenu2, quicklaunch2, desktopswitch2, cpuload2, taskbar2, volume2, clock2, worldclock2
position=Bottom
width=100
width-percent=true

[panel_%7Bcac5188a-57a2-43cf-a07b-653532a2800d%7D]
alignment=0
background-color=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
iconSize=39
lineCount=1
opacity=0
panelSize=44
plugins=tray2
position=Right
width=36
width-percent=true

[quicklaunch2]
alignment=Left
apps\1\desktop=/usr/share/applications/kde4/dolphin.desktop
apps\2\desktop=/home/stef/.local/share/applications/sospendi.desktop
apps\size=2
type=quicklaunch

[spacer2]
spaceType=dotted

[taskbar2]
alignment=Left
autoRotate=true
buttonStyle=IconText
buttonWidth=200
closeOnMiddleClick=true
groupingEnabled=false
showGroupOnHover=true
showOnlyCurrentDesktopTasks=true
type=taskbar

[tray2]
alignment=Right
type=tray

[volume2]
alignment=Right
type=volume

[worldclock2]
alignment=Right
autoRotate=true
customFormat="'<b>'HH:mm'</b><br/><font size=\"-2\">'ddd, d MMM yyyy'<br/>'TT'</font>'"
dateFormatType=custom
dateLongNames=false
datePadDay=false
datePosition=below
dateShowDoW=false
dateShowYear=false
defaultTimeZone=Africa/Addis_Ababa
formatType=custom-timeonly
showDate=false
showTimezone=false
timeAMPM=false
timePadHour=false
timeShowSeconds=false
timeZones\1\customName=
timeZones\1\timeZone=Africa/Addis_Ababa
timeZones\size=1
timezoneFormatType=iana
timezonePosition=below
type=worldclock
useAdvancedManualFormat=true

**Comment by palinek** [comment]
@stefonarch just tried to run panel with your config and application does not crash here (tried to configure freshly added spacer and existing cpu plugin)...

**Comment by stefonarch** [comment]
I retried with this configuration, clicking "save" in cpu-load plugin configure dialog it crashes again.
No idea what else could be related.

**Comment by palinek** [comment]
There is no "save" button in plugin-cpuload configuration ... do you mean "close"?
Did you change anything in the configuration dialog?

**Comment by stefonarch** [comment]
Sorry, I meant clicking "close".
 Same thing with spacer plugin; with   clicking elsewhere dialog disappears and panel does not crash.

**Comment by stefonarch** [comment]
I've now tested on a new user and cannot reproduce it, so there has to be  a problem with some other configuration in my home directory.

**Comment by stefonarch** [comment]
After recent updates of all packages it crashes again, with clean configuration it crashes even with "add panel"

**Comment by stefonarch** [comment]
After recent updates of all packages it crashes again, with new configuration file it crashes even with "add panel". But a test user is not affected, so it has to be connected with another setting in my home.

**Comment by paulolieuthier** [comment]
@stefonarch can you provide a backtrace?

**Comment by stefonarch** [comment]
I tried creating one at hte time, it was empty. But now I see that I
cannot reproduce the crash anymore, panel is stable.

Il 25/04/2015 21:28, Paulo Lieuthier ha scritto:

**Comment by paulolieuthier** [comment]
Let's close, then. If you reproduce it again and get the backtrace, please feel free to reopen it.
