### ISSUE TITLE
Various page link issues with lxqt website

### ISSUE THREAD

**Issue by JamesH65** [lxde/lxqt#568]
Not sure where to post this issue, so trying here!

Have been trying to get the source download (since github is currently being DDoS'd and it won't download reliably) from the lxqt website.

Broken links I have found are :` 

http://downloads.lxqt.org/
http://blog.lxde.org/

Thanks

James

**Comment by jleclanche** [comment]
We're having some dns issues.

**Comment by JamesH65** [comment]
Cool. OK to close if that is appropriate.

**Comment by jleclanche** [comment]
It's ok. I'll post on the list when I get updates. Hopefully it won't take too long.
