### ISSUE TITLE
panel: update themes for taskbar groups

### ISSUE THREAD

**Issue by palinek** [lxde/lxqt#569]
The taskbar group popup and it's buttons do not follow the overall panel look.

...will commit basic styles for some designer (@intialonso?) to see selectors where the styling should go into

**Comment by intialonso** [comment]
Hi, I sent a mail a week ago asking for a new maintainer fot the themes. Im
having some personal issues and have no time to take the job. At least for
a couple of months.

**Comment by jleclanche** [comment]
@intialonso No problem. We don't really have alternatives though unless someone proposes themselves, but you're welcome to work on it anytime you want.

**Comment by paulolieuthier** [comment]
It is going to be very difficult for me to come back to LXQt development as well. For the next months.

**Comment by palinek** [comment]
Closing this as there is nobody to enhance those styles. Should anybody be unhappy with the initial styles he/she will open new issue for it...
