### ISSUE TITLE
Clipboard manager widget for the panel

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [lxde/lxqt#570]
What do you think about it?

**Comment by Vladimir-csp** [comment]
IMHO, there is no need for panel-dependent clipboard manager. There are at least three DE-independent tools exist: clipit, parcellite, qlipper.
Qlipper is in qt, never tested it though.

**Comment by Vladimir-csp** [comment]
...just tested qlipper.
It supports global XDG configuration, this is nice!
No problems so far, except icon background glitches in menus.

**Comment by palinek** [comment]
How about [CopyQ](https://github.com/hluk/CopyQ)?

**Comment by pvanek** [comment]
I just started to port qlipper to Qt5.
I have no problem to drop qlipper in favor of anything better what runs on linux and osx for sure ;) But CopyQ isn't way to go IMHO. It's too heavy and confusing in UI for my needs.

**Comment by Vladimir-csp** [comment]
I agree, CopyQ is too heavy. Basically, clipboard manager is needed for two things:
- save clipboard content after source application is closed.
- history list (as a bonus).

Qlipper looks ideal for these. If user wants more, there are more sophisticated clipboard managers out there to find and try.

**Comment by luis-pereira** [comment]
@pvanek looking forward for that

**Comment by Esclapion** [comment]
Interesting, thanks.

2015-04-01 12:26 GMT+02:00 Luís Pereira <notifications@github.com>:

**Comment by dglent** [comment]
I agree copyQ has a confusing UI, qlipper is light and has also the feature to save entries, i use qlipper.

**Comment by maces** [comment]
Coming from Parcellite back when using LXDE, I'm now using qlipper. Compared to CopyQ it's nicely lightweight and just does it's job.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
The sticky entries are very useful for remembering complicated spam mail addresses and often-used terminal commands, but linux-like text-copy by just highlighting text does not work in qlipper.

**Comment by Vladimir-csp** [comment]
@ThebestwaytodesignJoinGitHub what do you mean by that? Selection buffer works fine while qlipper is running.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
'... Selection buffer works fine while qlipper is running.'
But qlipper does not collect it. Maybe that's ok, otherwise there's a lot to collect.

**Comment by Vladimir-csp** [comment]
if you enable 'platform specific extensions' in options, it will collect from selection buffer.

**Comment by dglent** [comment]
Thank you i was looking for this !

**Comment by rcmn** [comment]
Does anyone knows if there is an easy way to extend the limit of 30 entries
and 200 characters ?

On Thu, Apr 2, 2015 at 10:05 AM, Dimitrios Glentadakis <
notifications@github.com> wrote:

> Thank you i was looking for this !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/570#issuecomment-88729058>.
>



-- 
R.

**Comment by Vladimir-csp** [comment]
What I mistook for icon background glitch is actually buffer type indication, lol. It is hard to tell.

**Comment by jleclanche** [comment]
I'm closing this, let's support qlipper officially. @pvanek worked on it already.

**Comment by jleclanche** [comment]
@pvanek Is your work getting upstreamed? If not, you should move the fork to https://github.com/QtDesktop

**Comment by pvanek** [comment]
I'm upstream, so yes, it's upstreamed ;)

**Comment by paulolieuthier** [comment]
Closing this for we won't spend man power for something that already exists and works well.

**Comment by gbcox** [comment]
CopyQ allows you to pull and manipulate clipboard items in a script, as does klipper; but of course doesn't have all the dependencies of klipper making it a good fit to use in LXQt for those who need advanced functions. Unless I am mistaken, qlipper doesn't support this functionality.  That said, I have no issues with qlipper being the default; but it's nice to know CopyQ is available for those who need it.
