### ISSUE TITLE
Panel is blocked when there is a modal dialog open inside a config window

### ISSUE THREAD

**Issue by goetzc** [lxde/lxqt#571]
For example, open `Configure "Application menu"` then click on `...` to choose a Menu file. Then not only the `Configure "Application menu"` windows is blocked, the panel is also blocked, e.g. the task manager can't be used.  
The same happens with any modal windows from within a panel configuration window (widget or the panel itself).

**Comment by palinek** [comment]
This could be solved by not using modal dialogs. e. g.:
```diff
--- a/panel/config/configpaneldialog.cpp
+++ b/panel/config/configpaneldialog.cpp
@@ -424,10 +424,9 @@ void ConfigPanelWidget::pickBackgroundImage()
 {
     QString picturesLocation;
     picturesLocation = QStandardPaths::writableLocation(QStandardPaths::PicturesLocation);
-
-    QString file = QFileDialog::getOpenFileName(this,
-                                                "Pick image",
-                                                picturesLocation,
-                                                tr("Images (*.png *.gif *.jpg)"));
-    ui->lineEdit_customBgImage->setText(file);
+    QFileDialog* d = new QFileDialog(this, tr("Pick image"), picturesLocation, tr("Images (*.png *.gif *.jpg)"));
+    d->setAttribute(Qt::WA_DeleteOnClose);
+    d->setModal(false);
+    connect(d, &QFileDialog::fileSelected, ui->lineEdit_customBgImage, &QLineEdit::setText);
+    d->show();
 }
```
... but I don't know if we want to go this way. If yes, we have to identify all the modal dialogs and change the as shown.

**Comment by palinek** [comment]
After lxde/lxqt-panel@e6252df86a73c933691f8f99f43ffefda9fed22d all modal dialogs shown from config windows should not block user input into panel

**Comment by goetzc** [comment]
Hi, using lxde/lxqt-panel@e6252df the world clock plugin still blocks the panel. But I can not find any other widget which still does this.

**Comment by palinek** [comment]
lxde/lxqt-panel@4b61ff7d56d7a93f9d02b3563b77662fe64fa994 fixes the worldclock

**Comment by palinek** [comment]
@goetzc thank you for testing

**Comment by goetzc** [comment]
Can confirm that it doesn't block the panel! Thanks.
