### ISSUE TITLE
Panel: Directory Menu widget: difficult to change base directory

### ISSUE THREAD

**Issue by goetzc** [lxde/lxqt#574]
When trying to select a directory from the configuration dialog, the directory gets opened, showing the directories inside. So choosing a directory is difficult, to do it, the name has to be written inside the name box.

But when this is accomplished, the Directory Menu widget still displays the default directory :(  lol

**Comment by palinek** [comment]
@goetzc please, try the now... I made some changes while fiddling with the modal dialogs..

**Comment by goetzc** [comment]
Yes, that fixed it! Thanks :)
