### ISSUE TITLE
xdg-open...will not open

### ISSUE THREAD

**Issue by hifi25nl** [lxde/lxqt#577]
This is happening only in LXQt desktop.
I have problems with xdg-open in LXQt.
For example if I download a file with chromium and I select "show in folder" xdg-open will not open the folder and cpu utilization will go up. The instance of xdg-open will never close unless I kill it manually.
I have also problems with Kodi with external UPnP renderer: one or more instances of xdg-mime are starting with high cpu.
I have made some tests. From terminal xdg-open will not open a folder, where gvfs-open yes.
I have mimepps.list in /home/<user>/.local/share:

[Default Applications]
inode/directory=pcmanfm-qt.desktop

I have another mimeapps.list with the same content in .local/share/applications.
I was trying to reset mime configuration deleting all mimemapp.list files in  /home/<user>/.local and /usr/share/applications and run update-desktop-database both as user and root but the problem persists.
This is the output of printenv | grep XDG:

XDG_VTNR=1
XDG_SESSION_ID=c1
XDG_DATA_HOME=/home/audiolinux/.local/share
XDG_MENU_PREFIX=lxqt-
XDG_SESSION_CLASS=user
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_TYPE=x11
XDG_SEAT=seat0
XDG_CONFIG_HOME=/home/audiolinux/.config
XDG_SESSION_DESKTOP=
XDG_DATA_DIRS=/home/audiolinux/.local/share:/usr/local/share/:/usr/share/
XDG_RUNTIME_DIR=/run/user/1000
XDG_CURRENT_DESKTOP=LXQt

I am using LXQt stable and pcmnafm-qt-git from yesterday (for fixing "move to trash" missing). I had the same problem with pcmanfm-qt stable. Distribution is archlinux updated to today.

**Comment by pmattern** [comment]
Running either LXQt release 0.9 or latest Git on Arch Linux I can't confirm your findings. The window manager as stated by `xdg-mime query default inode/directory` comes up at once when either `xdg-open <some directory>` is invoked in a virtual terminal or "Show in folder" is clicked after downloading a file in Chromium.
Window managers compiled against Qt 5 don't seem to open the correct folder but that's a different story.

To further track the problem you describe I'd suggest you first have a look / post the output of `xdg-mime query default`. Maybe something got screwed besides the configuration files look all right. Arguments should be either inode/directory as stated above or the MIME types used by Kodi.
Also, it could be helpful to have a look at the output of `journalctl --follow --full` (run as root, exit via Ctrl+C) while invoking the said commands.

Additional notes:

Binary update-desktop-database is meant to update file mimeinfo.cache in $XDG_CONFIG_DATA/applications/ (invoked by root) and $XDG_CONFIG_HOME/applications/ (invoked by regular user) only.
The handling of that file is a bit weird. Actually it is just meant to provide some kind of overview which applications *can* handle some MIME type (aka Internet Media Type), but *not* to assign default applications to media types.
Nevertheless many applications do use it for the latter purpose. This is actually pretty stupid as there is no means to influence the order of applications in single lines when this file gets auto-built. The order can be changed by editing manually, of course. But this gets lost the next time update-desktop-database is run.

~/.local/share isn't covered by any specification regarding MIME types I knew of.

**Comment by jleclanche** [comment]
Can't repro, so it's probably not ours anyway :/ Try in 0.10 tomorrow maybe.

**Comment by Vladimir-csp** [comment]
Just for the info: by [current spec](http://standards.freedesktop.org/mime-apps-spec/latest/ar01s02.html), the top priority list is $XDG_CONFIG_HOME/mimeapps.list. 
$XDG_DATA_HOME/applicationst/mimeapps.list is left for backwards compatibility and has lesser priority.

**Comment by PCMan** [comment]
Currently xdg-open and the older versions of xdg-open shipped with some browsers are buggy.
They still reads the defaults.list file which is deprecated long time ago.
This needs to be fixed by xdg-utils upstream.

**Comment by Vladimir-csp** [comment]
Currently I find gvfs-open and gvfs-mime the best option for an opener. Surprisingly, these tools adhere to the spec and do not have a ton of dependencies, despite being GNOME-related.
On Debian testing the deps for gfvs-bin are: libc6 (>= 2.4), libglib2.0-0 (>= 2.45.7), gvfs-common (1.26.1.1-1) and desktop-file-utils for gfvs-common. So they are not pulling the whole gvfs itself.

**Comment by jleclanche** [comment]
xdg-open is the standard opener...

**Comment by Vladimir-csp** [comment]
yes, but its 'open_generic' function is lagging behind spec and it uses DE-specific openers (including gvfs-open) if it is able to identify the DE.
