### ISSUE TITLE
possible bug in XdgDirs::DataHome

### ISSUE THREAD

**Issue by surlykke** [lxde/lxqt#578]
lxqt-config-fileassociations has stopped working (as in cannot change the default application for a mimetype). It tries to write to 

 ~/.local/share/lxqt-config-fileassociations/applications/mimeapps.list 

where it should write to 

~/.local/share/applications/mimeapps.list. 

lxqt-config-fileassociations constructs this path with the help of XdgDirs::dataHome().
The documentation for XdgDirs::DataHome() states that the method returns $XDG_DATA_HOME, but according to FDO, $XDG_DATA_HOME should default to ~/.local/share and according to qt5 doc, QStandardPaths::DataLocation (which is returned by DataHome()) defaults to ~/.local/share/[APPNAME]. 

@luis-pereira : You're the master of this stuff - is this the intended behavior for XdgDirs::DataHome() ? 

If not then we could fix by just letting DataHome() return QStandardPaths::GenericLocation rather than QStandardPaths::DataLocation.. 

If yes then maybe add another method to XdgDirs. 

br. Chr.

**Comment by paulolieuthier** [comment]
Yes, using `QStandardPaths::GenericDataLocation` would fix it for default values. However, if one wants to use different data paths and set them in `$XDG_DATA_HOME`, XdgDirs wouldn't get them. It should parse the variable.
