### ISSUE TITLE
Suggestion: Application browser

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#580]
Issues #579 and #573 combined in my head into an idea: The Application browser.
Basically, it already exists as lxqt-config - application which shows filtered and categorized list of applications.
If you add a few features to it, it could become very flexible tool:
- filter bar to change displayed applications (as described in #573)
- search bar
- search-as-you-type (I like the way it implemented in [SpaceFM](https://github.com/IgnorantGuru/spacefm))
- CLI options:
 - to set window geometry and/or lock it.
 - to launch without filter bar or search bar
 - to pre-set filters.

And so lxqt-config would be transformed to: application launcher / fat menu / application browser, logout dialog, configuration center (surprise!), friendly 3-button launcher for grandma, anything you can imagine and put into filters on CLI.

**Comment by alfredobonino** [comment]
@Vladimir-csp, Similar to lxlauncher of lxde?

**Comment by Vladimir-csp** [comment]
Remotely. lxlauncher is an application browser, but it is designed for root window and it can not filter it's contents.

Well, imagine lxqt-config'ish browser, that you can turn into logout dialog by launching with proper cli arguments (omit filter bar, reduce geometry, show only lxqt-leave entries).

**Comment by ianorlin** [comment]
Isn't the browser in the application menu of pcmanfm-qt? Admitely I don't think this is searchable. 

If you want a search as you go launcher there is already lxqt-runner. Press alt-f2 is the defualt way to launch it.

**Comment by Vladimir-csp** [comment]
You're missing the point. It is mostly contained in the last paragraph of the issue text.

**Comment by jleclanche** [comment]
I'm rejecting this on the following basis:

* Nobody is working on it
* The idea is too abstract
* It can be done outside of LXQt

If a third party implementation pops up and is good enough for inclusion we can rediscuss it then.
