### ISSUE TITLE
lxqt-session package 'xcb' not found by cmake

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [lxde/lxqt#581]
debian system, have installed and reinstalled everything with xcb and x11 in its name, also tried the ubuntu repo, no avail

**Comment by palinek** [comment]
Have a look here:
https://packages.debian.org/search?searchon=contents&keywords=FindXCB.cmake&mode=path&suite=unstable&arch=any

**Comment by ThebestwaytodesignJoinGitHub** [comment]
@palinek this hasn't change anything

**Comment by palinek** [comment]
@ThebestwaytodesignJoinGitHub you need to be more specific to get reasonable help. Please, provide the `cmake` output for the beggining...

**Comment by ThebestwaytodesignJoinGitHub** [comment]
checking for module 'xcb'
  package 'xcb' not found
CMake Error at /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:341 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  CMakeLists.txt:27 (pkg_check_modules)
*********************************************************************
LIB_SUFFIX variable is not defined. It will be autodetected now
You can set it manually with -DLIB_SUFFIX=<value> (64 for example)
LIB_SUFFIX autodetected as '', libraries will be installed into /usr/local/lib
*********************************************************************
Configuring incomplete, errors occurred!
See also "/usr/src/lxqt/lxqt-session/build/CMakeFiles/CMakeOutput.log".

**Comment by palinek** [comment]
Just tried to simulate and it realy seems that on debian (testing in my case) `libxcb1-dev` package is needed:
- removedd libxcb1-dev:
```
lxqt-session/build$ sudo dpkg --force-depends --remove libxcb1-dev
dpkg: libxcb1-dev:amd64: dependency problems, but removing anyway as you requested:
 libxcb-sync-dev:amd64 depends on libxcb1-dev.
 libx11-dev:amd64 depends on libxcb1-dev.
 libxcb-present-dev:amd64 depends on libxcb1-dev.
 libxcb-glx0-dev:amd64 depends on libxcb1-dev.
 libxcb-shape0-dev:amd64 depends on libxcb1-dev.
 libxcb-damage0-dev:amd64 depends on libxcb1-dev.
 libxcb-dri3-dev:amd64 depends on libxcb1-dev.
 libxcb-render0-dev:amd64 depends on libxcb1-dev.
 libxcb-dri2-0-dev:amd64 depends on libxcb1-dev.
 libxcb-util0-dev:amd64 depends on libxcb1-dev.
 libxcb-xfixes0-dev:amd64 depends on libxcb1-dev.
 libxcb-dpms0-dev:amd64 depends on libxcb1-dev.
 libxcb-screensaver0-dev:amd64 depends on libxcb1-dev.
 libxcb-randr0-dev:amd64 depends on libxcb1-dev.
 libx11-xcb-dev:amd64 depends on libxcb1-dev (>= 0.9.92).

(Reading database ... 258910 files and directories currently installed.)
Removing libxcb1-dev:amd64 (1.10-3+b1) ...
```
- tried a fresh cmake:
```
lxqt-session/build$ cd ..
lxqt-session$ rm -R build
lxqt-session$ mkdir build
lxqt-session$ cd build
lxqt-session/build$ cmake ..
-- The C compiler identification is Clang 3.5.0
-- The CXX compiler identification is Clang 3.5.0
-- Check for working C compiler: /usr/bin/cc   
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- checking for module 'xcb'
--   package 'xcb' not found
CMake Error at /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:341 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  CMakeLists.txt:27 (pkg_check_modules)


-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- *********************************************************************
-- LIB_SUFFIX variable is not defined. It will be autodetected now
-- You can set it manually with -DLIB_SUFFIX=<value> (64 for example)
-- LIB_SUFFIX autodetected as '', libraries will be installed into /usr/local/lib
-- *********************************************************************
-- Configuring incomplete, errors occurred!
See also "/lxqt/lxqt-session/build/CMakeFiles/CMakeOutput.log".
```
- installed libxcb1-dev:
```
lxqt-session/build$ sudo aptitude install libxcb1-dev
The following NEW packages will be installed:  
  libxcb1-dev
0 packages upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 83.8 kB of archives. After unpacking 798 kB will be used.
Get: 1 http://ftp.sk.debian.org/debian/ testing/main libxcb1-dev amd64 1.10-3+b1 [83.8 kB]
Fetched 83.8 kB in 0s (547 kB/s)
Selecting previously unselected package libxcb1-dev:amd64.
(Reading database ... 258898 files and directories currently installed.)
Preparing to unpack .../libxcb1-dev_1.10-3+b1_amd64.deb ...
Unpacking libxcb1-dev:amd64 (1.10-3+b1) ...
Setting up libxcb1-dev:amd64 (1.10-3+b1) ...   

Current status: 0 broken [-15].
```
- and cmake succeded:
```
lxqt-session/build$ cmake ..
-- checking for module 'xcb'
--   found xcb, version 1.10
-- *********************************************************************
-- LIB_SUFFIX variable is not defined. It will be autodetected now
-- You can set it manually with -DLIB_SUFFIX=<value> (64 for example)
-- LIB_SUFFIX autodetected as '', libraries will be installed into /usr/local/lib
-- *********************************************************************
-- Configuring done
-- Generating done
-- Build files have been written to: /home/palco/work/oss/lxqt/lxqt-session/build
```

**Comment by ThebestwaytodesignJoinGitHub** [comment]
But I have already installed/removed/reinstalled libxcb1-dev...

**Comment by paulolieuthier** [comment]
@ThebestwaytodesignJoinGitHub remove your build directory and run cmake again.

**Comment by fguzm** [comment]
checking for module 'xcb'
  package 'xcb' not found
when trying to compile lxqt (or lxqt-session)

**Comment by palinek** [comment]
@fguzm Are you suggesting something? Or are you asking for help? Please, be more verbose if you want to continue this discussion.

**Comment by fguzm** [comment]
half a year later and another computer - same error when trying to compile

root@---:/usr/src/lxqt/lxqt-session# mkdir build && cd build
root@---:/usr/src/lxqt/lxqt-session/build# cmake ..
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- checking for module 'xcb'
--   package 'xcb' not found
CMake Error at /usr/share/cmake-3.3/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.3/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  CMakeLists.txt:26 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/usr/src/lxqt/lxqt-session/build/CMakeFiles/CMakeOutput.log"

**Comment by palinek** [comment]
Is the `libxcb1-dev` package installed?

**Comment by fguzm** [comment]
yes, this is really frustrating

**Comment by palinek** [comment]
..try the `cmake --debug-output --trace`.  It may reveal something...

**Comment by palinek** [comment]
Also the `pkg-config --debug --libs xcb` may be helpfull.

**Comment by fguzm** [comment]
http://pastebin.com/LnFSeatB
http://pastebin.com/LLPFtyxe

**Comment by palinek** [comment]
From the debug it seems that `pkg-config --exists xcb` exits with non-zero, what is the output of `pkg-config --exists xcb; echo $?`

Do you have the env variable `PKG_CONFIG` set? (`echo "$PKG_CONFIG"`)

**Comment by palinek** [comment]
And also it would be better if you run the cmake with debug output on a clean build directory...

**Comment by fguzm** [comment]
output of pkg-config --exists xcb; echo $?
1
PKG_CONFIG is not set, shouldn't it be set automatically at installation?

**Comment by palinek** [comment]
> output of pkg-config --exists xcb; echo $?
1

That's it... it should be zero. It is weird that `pkg-config --libs xcb` prints correct information, but `pkg-config --exists xcb` returns a failure. What is the output of `pkg-config --debug --exists xcb`?

=


> PKG_CONFIG is not set, shouldn't it be set automatically at installation?

I suppose not, just saw that this env variable is checked in the cmake module

**Comment by fguzm** [comment]
http://pastebin.com/ND2Wpy8N

**Comment by palinek** [comment]
> Searching for 'xcb' private requirement 'pthread-stubs'
Looking for package 'pthread-stubs'
Looking for package 'pthread-stubs-uninstalled'
root@---:~#

Seems that the pthread-stubs dependency is not found. How did you install the `libxcb1-dev`?

Because this package has the `libpthread-stubs0-dev`, `libxau-dev`, `libxdmcp-dev` dependencies (see [here](https://packages.debian.org/sid/libxcb1-dev)), whose are providing required *.pc files.

**Comment by fguzm** [comment]
I reinstalled these dependencies and after that I could compile the most parts of lxqt...
Thank you for your help!
