### ISSUE TITLE
Two X servers crashes Desktop.

### ISSUE THREAD

**Issue by edge226** [lxde/lxqt#583]
Running two monitors in a multiple X server configuration causes the desktop to crash. The background, right click functionality disappear. The Second monitor will not accept a Panel and I cannot launch programs on the second monitor.

**Comment by jleclanche** [comment]
Do you have console output?

**Comment by edge226** [comment]
I could get it if you told me what you need?

**Comment by selairi** [comment]
Could you be so kind to send me "xrandr" output?

Please execute:

xrandr --verbose

in your terminal. Maybe, it could be a problem with monitor config.

Thanks
