### ISSUE TITLE
LXQt panel/plugin desktopswitch: indicate urgent windows

### ISSUE THREAD

**Issue by npmiller** [lxde/lxqt#585]
Ok, so a nice feature to add to the desktopswitch would be a way to inform the user that a window is “urgent” on another desktop. This is extremely useful, especially if you don't use the taskbar, or use it only to display windows on the current desktop.

I've started looking into it, and especially how the urgent hint is handled in the taskbar, but I must be missing something, I can't find how to get notified when a window gets the “urgent” hint. So if you have an idea about how this could be implemented, please let me know and I'd be happy to work on this.

**Comment by paulolieuthier** [comment]
That's a very good idea. This is how it's done for the taskbar:
https://github.com/lxde/lxqt-panel/blob/master/plugin-taskbar/lxqttaskgroup.cpp#L64
https://github.com/lxde/lxqt-panel/blob/master/plugin-taskbar/lxqttaskgroup.cpp#L605

The desktop switch should listen to the signal as well, and then, once emitted, should find the desktop where the window is and highlight it.

**Comment by npmiller** [comment]
Just for the record, this doesn't work with i3, as i3 doesn't set the _NET_WM_DESKTOP attribute on the windows.

See https://github.com/i3/i3/issues/1507 for more information.

**Comment by paulolieuthier** [comment]
@npmiller plase update lxqt-panel and lxqt-common and test if it works well for you.

**Comment by npmiller** [comment]
@paulolieuthier works fine with kwin. Still some edge cases to cover though, for example if you add a desktop, you lose the highlight. Not a huge problem, but still, not the expected behaviour.
