### ISSUE TITLE
[lxqt-panel] One LibreOffice window is shown as two buttons in the taskbar.

### ISSUE THREAD

**Issue by PCMan** [lxde/lxqt#586]
Steps to reproduce:
1. Run lxqt-panel first
2. Open a LibreOffice document
Then you can see two task buttons of LibreOffice.
Expected behavior: there should be one task button only.

Possible cause:
LibreOffice changes the WM class of a window after it's created.
For example, its window class name is "LibreOffice 4.4" on start.
After I opened a Impress file, the class name of the window is changed to "libreoffice-impress".
Window class represents a group and determines which group a window belongs to.
However, in void LxQtTaskGroup::onWindowChanged(), we did not handle window class change at all.
With proper handling of window class changes, I think the bug can be fixed.

**Comment by PCMan** [comment]
@paulolieuthier since you know the tasbar manager part better, would you please take a look on this issue? Thanks a lot.

**Comment by paulolieuthier** [comment]
I can't reproduce it. Tried with KWin and Openbox. Libreoffice 4.4.2.

**Comment by PCMan** [comment]
You have to run lxqt-panel first, and then open a file with LibreOffice.
If you launch LibreOffice first, and then run lxqt-panel, the problem is gone.
I can reproduce the bug everytime. :-(

**Comment by palinek** [comment]
Tried to reproduce... and yes, it's happening, but only in case grouping is enabled. I'll have a look on it.

**Comment by paulolieuthier** [comment]
Great.

**Comment by ArthurBorsboom** [comment]
I still have this issue with lxqt-panel v0.10

**Comment by pmattern** [comment]
Confirmed.

Steps to reproduce (just to sum up what was discussed above):
* Make sure "Window grouping" is enabled in Task manger (plugin-taskbar)
* Launch LibreOffice "Startcenter" (just the empty LO window, no documents open). Open any new document by clicking one of the icons in section "Create" in left column.

Latest VCS checkouts of all LXQt components on Arch Linux i686, Libre Office Fresh 5.0.4.2 as provided by the distribution.

**Comment by palinek** [comment]
@pmattern could you check the lxde/lxqt-panel#292

**Comment by pmattern** [comment]
@palinek 
Cannot see the problem any longer in lxde/lxqt-panel@622e326.
