### ISSUE TITLE
[lxqt-panel] add "window can cover" and "window can go below"

### ISSUE THREAD

**Issue by DiscipleOfDante** [lxde/lxqt#588]
The LXQt Panel could use the ability to allow windows to cover or go below the panel. For smaller screens, specifically those one would find on a laptop, which can't be changed, could benefit from this as a means of saving screen real-estate.

For a good example, imagine placing your panel at the top, reducing the height to roughly that of your window titlebar, and then shrinking the width so that the window buttons would still be visible through the gap. If the window could go below the panel, then this would allow a maximized web browser, office program, or whatever else, to use most of the screen.

**Comment by palinek** [comment]
How about these?:
1. there is "auto-hide" functionality in panel
2. you can move (non-maximized) window into area occupied by panel as you wish

**Comment by DiscipleOfDante** [comment]
Autohide would cover one of these, but for the "windows can go below" it is really kind of a necessity for those who are trying to get the best screen economy they can. the main purpose for this function is maximized windows, while not losing the ability to see your panel (so you can always see your clock and the like)

**Comment by jleclanche** [comment]
Autohide covers this. Closing.

**Comment by jleclanche** [comment]
@DiscipleOfDante I'm sorry but I still don't understand how autohide does not cover that. Do you have a screenshot of what you're trying to say?

**Comment by DiscipleOfDante** [comment]
Like this (done in Plasma 5) http://i.imgur.com/Nc31gwg.png . You can see how I don't need to mouse-over my panel to see my top panel, yet it is not in the way of my fullscreened browser, allowing me to keep an eye on the time and the status of my computer without having to constantly mouse-up.
