### ISSUE TITLE
Clock plugin should not 'autorotate when the panel is vertical' by default

### ISSUE THREAD

**Issue by goetzc** [lxde/lxqt#59]
I think that regardless of the horizontal or vertical panel alignment, the clock text should be kept horizontal in both cases by default.

**Comment by palinek** [comment]
Is this still a valid request/issue?

**Comment by jleclanche** [comment]
I set the clock so it doesn't autorotate when the panel is vertical and it's not making the panel wider, so it's being cut off. The issue is no longer valid but there's a followup.
