### ISSUE TITLE
Chrome launches as X11 fallback rather than libappindicator

### ISSUE THREAD

**Issue by gbcox** [lxde/lxqt#591]
Chrome switched to using libappindicator in the systray.  There was a bug report on this regarding KDE Plasma here:  https://code.google.com/p/chromium/issues/detail?id=362880

I've noticed that when you launch Chrome for some reason it is using the fallback X11 icons, even though I've installed libappindicator.  However, if I go to the LXQt Appearance Configuration and re-click on a widget style libappindicator is then recognized and the correct icons are then displayed.  

The settings are correctly recognized using KDE Plasma.

**Comment by Esclapion** [comment]
libappindicator is gtk, no ? (only to know)

**Comment by paulolieuthier** [comment]
libappindicator is compatible with KDE's status notifier.

**Comment by gbcox** [comment]
Yes, the implementation used in chrome is for gtk2, but as already commented it compatible with the KDE status notifier.  It appears to work in LXQt AFTER you re-click on a widget style - you shouldn't have to do that each time you start a new application.

**Comment by paulolieuthier** [comment]
LXQt's status notifier implementation is a work in progress. Thanks for your help filing the issue.

**Comment by palinek** [comment]
I didn't get much into this... but I've just fixed a problem of showing menu in lxde/lxqt-panel@aed01a20eb4b4503ccc7bfa87a86573d4fe48163. Is it suitable also for this issue?

**Comment by palinek** [comment]
I'm wondering how to enable any tray/status notification in chromium...
I've tried `alarm-clock-applet` as an example application using `libappindicator1` and (after lxde/lxqt-panel@aed01a2) the icon is correctly showed in status notifier plugin

**Comment by gbcox** [comment]
I'm running Chrome, but should be the same...
You can go to:
https://developer.cdn.mozilla.net/media/uploads/demos/e/l/elfoxero/c17223c414d8ddafb7808972b5617d9e/html5-notifications_1400214081_demo_package/index.html

Fill out the form and it will make the notification bell appear.  
Here is what the X11 fallback looks like:
![x11](https://cloud.githubusercontent.com/assets/4543019/7148830/99895bc0-e2bb-11e4-9538-17cb5bb030bb.png)
Here is libappindicator...
![libapp](https://cloud.githubusercontent.com/assets/4543019/7148838/b9a4aba8-e2bb-11e4-9445-405d51957b3d.png)

Note the bell is smaller.  

The other thing I noticed is the behavior for hangouts, doesn't seem to be working.  When you hover over the icons they are suppose to highlight.  Left click is suppose to bring up a menu, but it instead just launches - which is fine by me, but as I understand it, that isn't the way it is suppose to work.

**Comment by paulolieuthier** [comment]
@gbcox left click by default opens the menu for every icon in Unity, right? We're following the xdg spec on the mouse clicks. We call the application telling it to handle a left mouse click when it happens (or a right click, and so on).

**Comment by gbcox** [comment]
I can't speak for Unity, I'm running Fedora - but I believe that is correct.  I get the menu on Hangouts under KDE, under LXQt it bypasses the menu and launches, same thing for the notification bell.  Also under LXQt I'm not getting the highlighting when hovering over the icons.

**Comment by paulolieuthier** [comment]
I new issue must be filed for that. Thanks for yout help.

**Comment by gbcox** [comment]
One more interesting bit of information regarding the highlighting... under KDE the Chrome, Hangouts and Notification Indicators highlight when you hover over them, no popup label.  Under LXQt what happens is when you hover over them you get a popup label:  Google Chrome, Hangouts, Chrome - Notifications and no highlighting.

**Comment by palinek** [comment]
@gbcox From the screenshot I'm assuming that you are talking "System tray" plugin all the time and *not* about "Status Notifier". I thought we are dealing with different behaviour of "System tray" & "Status Notifier"... my fault.

**Comment by gbcox** [comment]
@palinek - I'm by no means an expert on this and maybe just confused.  I had read:
http://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/

I thought the way it worked is you have the system tray area.  Within that, the icons are either using the xembed specification or the status notifier (libappindicator) specification.  In this particular instance Chrome supports both... if libappindicator is installed it uses status notifier, if not it falls back to xembed.  Under KDE, the chrome icons (hangouts, chrome and notification) are using the status notifier (highlight when you move over them, menu display, etc).  Under LXQt, the xembed icons are used at launch, when you re-click on a widget style under the appearance configuration, they immediately get refreshed to display the status notifier version.  Under Chrome, the appearance of the icons is slightly different (they are all slightly smaller and are sharper); so it's easy to see that this has occured.  However, as I noted above the behavior is different than it is under KDE.  Does this make sense?

**Comment by paulolieuthier** [comment]
@gbcox what version of KDE are you using? The new Plasma desktop does not support the xembed spec at all. In LXQt, there is a panel plugin for xembed and another one for status notifier icons. Are you using both?

**Comment by gbcox** [comment]
@paulolieuthier I'm running KDE4.  I don't see a plugin for status notifier.  I only see a widget for system tray.  If this is something that has been recently added, it probably hasn't made it into the Fedora respository yet.

**Comment by paulolieuthier** [comment]
KDE4 has both implementations under the name of "system tray", as you said. The blog post you linked to is about the new Plasma ("KDE 5"), which dropped xembed support. I just installed Chrome and I see its icon on the system tray plugin (xembed), but not on the status notifier plugin. I installed the Hangouts app and I didn't get it to show an icon, only a floating button.

> I'm wondering how to enable any tray/status notification in chromium...

@palinek open the app store and install Hangout, you'll see the icon.

**Comment by gbcox** [comment]
You can also make the notification bell appear by going here:
https://developer.cdn.mozilla.net/media/uploads/demos/e/l/elfoxero/c17223c414d8ddafb7808972b5617d9e/html5-notifications_1400214081_demo_package/index.html

**Comment by palinek** [comment]
@paulolieuthie i was able to see the notification by using @gbcox 's link (had to turn on the html5 notifications somewhere in the chromium settings). But wasn't abe to force the icon go into "status notifier" plugin.

**Comment by paulolieuthier** [comment]
> One more interesting bit of information regarding the highlighting... under KDE the Chrome, Hangouts and Notification Indicators highlight when you hover over them, no popup label. Under LXQt what happens is when you hover over them you get a popup label: Google Chrome, Hangouts, Chrome - Notifications and no highlighting.

That's the desired behaviour. Each implementation of the system tray handles the events its own way. In LXQt, there is no highlighting, and the popup is shown. If the application's developer doesn't want a popup, he must not set it. About the highlighting, there is no such thing in the spec.

> Under LXQt, the xembed icons are used at launch, when you re-click on a widget style under the appearance configuration, they immediately get refreshed to display the status notifier version.

That's not right. As I said, in LXQt both xembed and status notifier specs are implemented in different plugins. What you see is a simple visual artifact, a bug on the icon handling.

The status notifier is never used in LXQt for Chrome/Chromium, and that's the real bug here. If it's used in KDE4/Plasma, it should be supported automatically by our implementation as well.

**Comment by paulolieuthier** [comment]
@gbcox: following the discussion you linked to in the issue description, I found out Chromium's implementation is specific to KDE4, and you'll always see its icon in LXQt's xembed-based system tray plugin only (never on the status notifier plugin). I'm saying that based on a diff linked to on that discussion, I didn't see current Chromium code.

**Comment by gbcox** [comment]
@paulolieuthier Ok, I think I understand the LXQt implementation now.  I need to wait until the status notifier plug-in is available on Fedora and then test.  My question is will I need to use both plugins, one for applications that are status notifier enabled and another for those that are not?  And what happens when an application (such as Chrome) supports both?

**Comment by paulolieuthier** [comment]
Yes, I'm using both. The xembed-based one will be removed someday, xembed itself is being deprecated (it's already not supported in Plasma), probably when Wayland comes. The applications should handle it. Chrome already does it, as you can see it using the status notifier in KDE4 while KDE4 supports both implementations. Don't worry :smile:.
