### ISSUE TITLE
LXQt panel/Task Manager: disabling window grouping faulty

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#593]
If window grouping gets disabled windows' text in Task manager turns into a string of numeric characters and clicking doesn't have an effect any longer.
The latter isn't related to the various focussing issues that still exist as all other panel plugins are reacting as usual at the same time.

If "Show popup on mouse hover" had been set as well, remnants of the usual group lists comprising one element only keep popping up on hovering and work as usual.
![lxqt_panel_task-manager-disable-window-grouping](https://cloud.githubusercontent.com/assets/9860801/7143368/63b60f6a-e2df-11e4-9f93-50d9e5afc7bc.png)

Neither windows placed on the same desktop as dialogue "Task Manager Settings" right when the latter is used to disable grouping nor windows opened while the problem exists are affected.
Closing windows affected by the problem makes panel dump core. When it's restarted the problem cannot be seen on the desktop where the window had been closed but on all other desktops.

**Comment by palinek** [comment]
How did you achieve that? I'm not able to reproduce it here ...

**Comment by palinek** [comment]
@pmattern, @agaida thanks for helping/testing
