### ISSUE TITLE
Chrome Libappindicator icons, no highlighting, skips menu and launches

### ISSUE THREAD

**Issue by gbcox** [lxde/lxqt#594]
Under KDE the Chrome, Hangouts and Notification Indicators highlight when you hover over them, no popup label. Under LXQt what happens is when you hover over them you get a popup label: Google Chrome, Hangouts, Chrome - Notifications and no highlighting.

Additionally when you left click on the icons you are suppose to get a menu, then click on the item to launch.  Under LXQt the menu is skipped and the app launches.

**Comment by paulolieuthier** [comment]
Chrome's status notifier implementation is DE-specific, and LXQt is not supported. Therefore, Chrome will use standard tray icons in LXQt. Left click the app shows up, right click the menu shows up. That's the default behaviour, isn't it?

I'm closing the issue (the whole discussion can be found in #591). @gbcox feel free to reopen it if you find necessary.
