### ISSUE TITLE
[lxqt-panel] task manager: margins when vertical

### ISSUE THREAD

**Issue by vicencb** [lxde/lxqt#597]
When the panel position is "Bottom of desktop" then the mouse can be moved to the bottom and the corresponding application button will be highlighted in the task manager.
But when the panel position is "Left of desktop" then there is a margin between the left side of the screen and the application button that diminishes its usability.
Tested on version 0.9.0

**Comment by palinek** [comment]
I can have a look on it... as @intialonso is not able to work on LXQt right now.

**Comment by paulolieuthier** [comment]
Great :+1:

**Comment by palinek** [comment]
> When the panel position is "Bottom of desktop" then the mouse can be moved to the bottom and the corresponding application button will be highlighted in the task manager.

@vicencb I don't see such behaviour in any theme. All current themes have a margin on top/bottom.
But I admit it will be good to get rid of those margins.

**Comment by palinek** [comment]
I have removed margins in themes.... but there is still a problem with `LxQt::GridLayout` which I've fixed in lxde/liblxqt@bba36a0. When that goes merged, we can close this.

**Comment by vicencb** [comment]
@palinek you are right, all of them have a margin
![hor](https://cloud.githubusercontent.com/assets/8713064/7187155/a9958fc8-e466-11e4-9ffc-14018393ea48.png)
![ver](https://cloud.githubusercontent.com/assets/8713064/7187157/ac8b6374-e466-11e4-8934-ad9a0f7ffa34.png)
but the horizontal version has only a 2 pixels margin while the vertical version has 4.
I don't know why but when I move the mouse to the left edge the pointer goes to the first pixel (in the margin), but when the mouse is moved to the bottom edge, then the pointer is limited to about 3 pixels above the real bottom (outside the margin)
So here is the question: why is the mouse pointer limited? may it be related to the cursor theme xcursor-vanilla-dmz? anyway, that is outside the scope of this issue.

**Comment by palinek** [comment]
@vicencb I suppose LXQt components have nothing to do with the pointer position limitation. I believe it's connected with WM.
