### ISSUE TITLE
Manage plugins dialog design

### ISSUE THREAD

**Issue by paulolieuthier** [lxde/lxqt#598]
Continuing the discussion from #536. @jleclanche @pmattern @palinek @Vladimir-csp @excalibur1234

![4d03ee88-dc75-11e4-87b7-8cbd61211c11](https://cloud.githubusercontent.com/assets/1238157/7172453/8d8b2138-e3be-11e4-97db-b7b3aaa4a4e4.png)

I think xfce's design here is much, much better than ours. We can copy it. But we can also figure out something better. Ideas?

**Comment by Vladimir-csp** [comment]
I agree, XFCE has a solid design. Centralized plugin manager with all the obvious buttons as a tab in config window.
What can be better? Maybe two-pane list with enabled/available panes and buttons in between?

**Comment by gbcox** [comment]
Here is what Mate has which is more or less similar to the current and KDE, Gnome.  I agree, the XFCE is very nice...
![mate](https://cloud.githubusercontent.com/assets/4543019/7187570/4ef4b5de-e426-11e4-9db3-592b85ca5db8.png)

**Comment by paulolieuthier** [comment]
I've been thinking of a way to solve our problem of not having how to move/configure the plugins which handle right click by their own (that can't be moved or configured by right click, like the taskbar and the system tray).

Ths solution is to add a handle, a little widget just before those plugins. That could be a flag any plugin could set. Right-clicking this handle would present the desired options, and it could also be used to move objects in the future.

**Comment by pmattern** [comment]
My 2 cents after re-thinking that whole thing once more:

Dialog windows "Configure Panel" and "Manage Panel Widgets" should be merged into a single one. All in all I think this would make sense, also, but not only with regards to #599.
Of course this would mean that the UIs have to be tweaked somehow, e. g. by introducing tabs as in Xfce, which in turn sure meant some coding effort. But if this is feasible it should be done.

Dialog window "Manage Panel Widgets" should definitely be modified, for the most part following Xfce's concepts.
It should comprise only those plugins that have already been added to the panel, one line per added instance and in the same order as in the panel itself. Button "Add Widget" obviously had to be changed as a consequence, probably such that it brings up another dialog window used to handle the actual adding.
First, this would make configuring plugins easier. Right now one has to pick the one in question from a list comprising all available ones in an arbitrary order which can be cumbersome in particular if the name isn't remembered.
In addition another pretty easy way to move plugins in the panel could be implemented by introducing arrows like those in the Xfce screenshot that can be used after selecting plugins in the list.

Additional components of panel plugins meant only to have them always configurable from their own context menu should be optional at best.
Components like this do need additional horizontal space which frequently just looks bad. At least this is what I always thought on Xfce where they are provided as optional "handles". But I don't think they would be mandatory anyway:
Both configuration and moving can be handled from dialog "Manage Panel Widgets" as result of #536. This dialog window can't be accessed from everywhere over the panel but one can assume there will always be at least one plugin that allows for accessing from its context menus which all in all provides a both sufficiently intuitive and quick means to handle those tasks. As for moving yet another way to handle it easily could be introduced by modifying "Manage Panel Plugins" as suggested in the previous paragraph.

**Comment by paulolieuthier** [comment]
I agree with you about all you said. But the handle thing wouldn't be for moving (but it could also be). It'd be specially for accessing the context menu.

**Comment by paulolieuthier** [comment]
@luis-pereira @jleclanche @PCMan @kuzmas @surlykke do you know the reason why the `AddPluginDialog` class is in liblxqt rather than in lxqt-panel? Would it be a problem to move to lxqt-panel?

**Comment by paulolieuthier** [comment]
**Brace yourselves**:

![screen](https://cloud.githubusercontent.com/assets/1238157/7209779/3a8b13b6-e522-11e4-9e86-f7906e49c92b.png)

About the UI, I actually prefer tabs here, but I'm using `ConfigDialog` from liblxqt, and that's the default way. Tabbed config dialogs could be supported as well. Maybe another day :smile:.

**Comment by pmattern** [comment]
Wow, looks pretty promising . That side-pane at the left would do very well, imo. Definitely not essential to replace it by tabs.

**Comment by Vladimir-csp** [comment]
That looks great!
Tabs use less space though, but that is not a critical matter.

**Comment by palinek** [comment]
The desing is nice. Tabs vs. icon bar -> IMHO icons better suits the overall `lxqt-config` dialogs design.

**Comment by pmattern** [comment]
Please let's not follow the contemporary trend to be maniac about gearing each and every kind of stuff towards mobile devices.
Considering the devices LXQt is intended to be used on the little additional space needed by those icons really doesn't matter in any way.

**Comment by paulolieuthier** [comment]
> Please let's not follow the contemporary trend to be maniac about gearing each and every kind of stuff towards mobile devices.

@pmattern, don't worry about it :smile:

**Comment by paulolieuthier** [comment]
@pmattern, @Vladimir-csp now it's your turn :smile: 

![screen](https://cloud.githubusercontent.com/assets/1238157/7412043/0421d790-ef15-11e4-82a3-f2852acd80b6.jpg)

**Comment by palinek** [comment]
...as I'm looking at the screenshot now... Maybe we should put `up`,`down`,`remove`,`config` buttons into one group and `new` after the separator. Because the first are tied to concrete plugin and the last one shows `AddPluginDialog`

**Comment by excalibur1234** [comment]
this "configure panel" looks great.
i remember clearly that i did not find the "config" button the first time i searched for it in xfce, but i tried to right click on the widgets.
is there a right click menu when you right click on the widgets in your "configure panel / manage widgets" window? the right click menu should contain the same options as the buttons on the right (add widget, remove widget, move widget up, move widget down, widget properties).

**Comment by paulolieuthier** [comment]
@excalibur1234 there is a right click menu. But it's available only through the plugins that don't override the right click action to present a specific menu.

**Comment by palinek** [comment]
@paulolieuthier as I understood what @excalibur1234 meant: he would like to have the context menu in "Configure panel" window (in the list of plugins), right?

**Comment by paulolieuthier** [comment]
Oh, I see. You're right. But then I don't see the point.

**Comment by excalibur1234** [comment]
@palinek was right. i meant a right click / context menu in the window you created (and we see a screenshot).

personally, i do not care whether there is a right click menu or not.
but i described my behavior and way of thinking as a new xfce (and linux) user. a right click / context menu would definitely help these kind of users.

**Comment by pmattern** [comment]
Some notes after testing latest changes a bit longer:

The first time dialogue window "Configure Panel" got opened there was an entry "Unknown (panelvolume)" in the list on all systems I checked.
On all of them the panel had been configured individually before. Once removed that entry didn't re-appear. When ~/.config/lxqt/panel.conf was deleted before launching the LXQt session, the entry didn't appear in the first place.

That phrase "Note: changes made in the page cannot be reset." isn't quite obvious, imo.
I suppose it is meant to express something like "Changes corresponding to topic 'Manage widgets' (left pane) cannot be reset in contrast to those displayed if 'Configure panel' is selected".
If so, wouldn't it be an option to just grey button "Reset" as soon as "Manage widgets" is selected in left pane? I'd suggest to leave that explaining phrase nevertheless but change "the page" to "this page" to make the difference clear.

In panel's context menu items "Configure Panel..." and "Manage Panel Widgets..." open the very same window but just a different selection in left panel.
I'm not sure whether this is rather helpful or rather confusing. Could very well be a matter of taste, of course. Yet I wonder whether it wouldn't be better to unify them into one item, also with regards to #599.

Changing the order of added plugins in the list by drag & drop would be something nice to have.

In #614 it was stated that the standards implemented by plugin System tray allow for one plugin instance only. I don't know those standards well. But if it applies, I think it would be good to prevent adding more than one instance from dialog window "lxqt-panel" which works flawlessly right now.

@excalibur1234 
Not following here: in Xfce's counterpart a context menu does not exist either. E. g. if you clicked on "Separator" as marked in screenshot in first post, left dialog window, there would be just nothing.

@paulolieuthier 
You closed this issue but we've also been discussing that handle thing here. Just saying to avoid it gets forgotten. Maybe open a new issue covering this?

**Comment by paulolieuthier** [comment]
> The first time dialogue window "Configure Panel" got opened there was an entry "Unknown (panelvolume)" in the list on all systems I checked. On all of them the panel had been configured individually before. Once removed that entry didn't re-appear. When ~/.config/lxqt/panel.conf was deleted before launching the LXQt session, the entry didn't appear in the first place.

Fixed in lxde/lxqt-panel@6d51ebf2d6e474c422b49ce29f2eaba56c1219dc.

>  If so, wouldn't it be an option to just grey button "Reset" as soon as "Manage widgets" is selected in left pane?

Greying the button is not so simple, I left it to be done later. That's because the pages and the dialog are separate classes in separate repositories (of course can be done, but the note was simpler).

> I'd suggest to leave that explaining phrase nevertheless but change "the page" to "this page" to make the difference clear.

I thought it was that way. Will be fixed.

> Changing the order of added plugins in the list by drag & drop would be something nice to have.

Agreed!

> In panel's context menu items "Configure Panel..." and "Manage Panel Widgets..." open the very same window but just a different selection in left panel. I'm not sure whether this is rather helpful or rather confusing. Could very well be a matter of taste, of course. Yet I wonder whether it wouldn't be better to unify them into one item, also with regards to #599.

Do you think it's confusing? I don't think so. About placing the config dialog in Configuration Center, that's a good idea and will be done.

> In #614 it was stated that the standards implemented by plugin System tray allow for one plugin instance only. I don't know those standards well. But if it applies, I think it would be good to prevent adding more than one instance from dialog window "lxqt-panel" which works flawlessly right now.

You're right! All plugins should be able to say only one instance of it can be created. Please create an issue for that, it should be fixed for 0.10.

>  You closed this issue but we've also been discussing that handle thing here. Just saying to avoid it gets forgotten. Maybe open a new issue covering this?

This issue was about the dialog. Tha handle thing deserves its own issue. Thanks for your help.

**Comment by luis-pereira** [comment]
@paulolieuthier Regarding the ```AddPluginDialog``` class: In the Razor days, it was used in  razorqt-desktop and the panel, of course.

**Comment by paulolieuthier** [comment]
@luis-pereira I see, thanks.

**Comment by pmattern** [comment]
That "Configure Panel" vs. "Manage Widgets" thing in panel's context menu was just some thought. I'd be completely fine if this stayed as-is.
But I stumbled upon two more things:

String "Configure Panel" is used both to describe one of the items in left pane and as window title, the latter constantly and independently of which topic is chosen in left pane. I think this should be changed.
Not sure how exactly to put it, though. I think "Configure panel" as constant window title is all right. Maybe just rename the items in left pane to "Panel" and "Widgets"? Obviously those two words would have to appear in panel's context many as well which could be a bit confusing. But on the other hand I suppose users would understand their meaning after clicking each of them just once.

Window title "lxqt-panel" doesn't reflect what this window is about. Maybe change it to "Add plugins"?

Aside from this I agree on all you said in your second to last comment.

**Comment by paulolieuthier** [comment]
@pmattern good points, I'll update the labels.

**Comment by paulolieuthier** [comment]
@pmattern: landed in lxde/lxqt-panel@11fccf650045f0c9b1f690dfc5915a124ded3a15. The only labels I didn't change as you said were the labels in the context menu. They are only slightly different now: "Configure Panel" and "Manage Widgets". As you said yourself, i'd be confusing for the users to see only "Panel" and "Widgets" in the context menu. Hopefully, the icons will help guiding them.
