### ISSUE TITLE
Document lxqt-leave

### ISSUE THREAD

**Issue by ypnos** [lxde/lxqt#601]
The command `lxqt-leave` is a great way to suspend from console or for a keybinding. However I didn't find any documentation.

I had to look at https://github.com/lxde/lxqt-session/blob/master/lxqtleave/main.cpp to find out what arguments to pass to the command. Trying out different options is scary because you might accidentally kill your session ;)

1. Have a manpage for lxqt-leave
2. Provide -h and --help options

**Comment by paulolieuthier** [comment]
- [x] The help option command was added by @npmiller.
- [ ] Man page to be added.
