### ISSUE TITLE
feature request: keyboard layout panel switch 

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#602]
may be realized in the keyboard indicator plugin or via systray-icon

http://i.imgur.com/Ojsz2Ya.png / http://i.imgur.com/iun6DEI.png / http://i.imgur.com/pbCHRWD.png

right now i use qxkb for that - but qxkb is Qt4, mostly unmaintained and conflicts with the standard LXQt tool

**Comment by palinek** [comment]
There is a WIP on that field lxde/lxqt-panel#102. @jleclanche, @zjes what's the status on that?

**Comment by zjes** [comment]
Now it's implemented in current kbdindicator plugin, but needs to make it like third party plugin. I will try to make it asap.

**Comment by paulolieuthier** [comment]
The current keyboard indicator plugin shows the state of the modifier keys (Caps Lock, Num Lock and Scroll Lock). This issues is about the keyboard layout. I don't think Qt has support for that. We should look how KDE does it. In lxqt-config-input, the output of `setxkbmap` is parsed and information is retrieved from that. But obviously that's the wrong way to do it.

**Comment by zjes** [comment]
Layout in pull request is based of current indicator plugin. :)
First implementation in this pull request get kbd information with help of XkbGetControls, and it was standalone plugin. The second implementation read setxkbmap output also. You can choose. I dont know other ways to read info from the xkb. :(

**Comment by paulolieuthier** [comment]
@zjes I see. There is a library called [xkbcommon](http://xkbcommon.org) that can handle keyboards. It doens't look like it's simple to use it, but it supports X11 and Wayland :smile:. Anyway, I'm ok with merging your plugin using `#ifdef`s for X11.

And  lxqt-config-input must be updated to support Wayland one day as well.

**Comment by postadelmaga** [comment]
+1

**Comment by agaida** [comment]
any progress?

**Comment by dsilakov** [comment]
I have tried to build lxqt-panel with the patch suggested in https://github.com/lxde/lxqt-panel/pull/102 for ROSA Linux (https://abf.io/import/lxqt-panel/blob/rosa2014.1/lxqt-panel-0.9.0-kbd-layout-indicator.patch). In general the patched panel worked fine, but there was a serious problem - if no alternative layouts are configured in the OS then panel crashes (segfaults) if indicator plugin is enabled.

If anyone is interested in how this looks like, you can try ISO images with ROSA LXQt builds from here: https://abf.io/platforms/rosa2014.1/products/135/product_build_lists/11519

No need to install them, you can start it in Live mode. If you choose "English" language then the panel will segfault on startup (http://bugs.rosalinux.ru/show_bug.cgi?id=5752). If you choose any other language then everything works fine...

**Comment by paulolieuthier** [comment]
I missed this one. I'll take another look on the PR again. I think it must be in 0.10, since as @agaida said, there is not a Qt5 layout switcher.

**Comment by zjes** [comment]
Here https://github.com/zjes/lxqt-kbdstate initial version of the "third party" plugin. Not ready yet, missing theming, translations, installation... but it's made with xkbcommon lib, as you wish. :)

**Comment by agaida** [comment]
cool, thanks a lot

**Comment by paulolieuthier** [comment]
@zjes awesome work. I'll have time for it next week.

**Comment by paulolieuthier** [comment]
It can still make use of some polishing. And it would be very good to drop KGuiAddons dependency if xkbcommon can do what KGuiAddons is doing right now. But anyway, work is almost complete. :smile: 

I don't think this should be a third party plugin. Opinions?

**Comment by Vladimir-csp** [comment]
I vote for systray.
Right now I'm using gxkb and I like the way it Just Works, anywhere. Having similar tool in Qt would be great.

**Comment by zjes** [comment]
Yes, it needs some work... some work to simplify, bug fixing, etc. It's only initial version :)
It can be as third party plugin (for lxqt, not standalone application), this is very appetite option to make such plugins. But it's on your decision. :)

**Comment by paulolieuthier** [comment]
Fixed by lxde/lxqt-panel#223.
