### ISSUE TITLE
feature request: start lxqt-runner if typing on the desktop with no window active

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#604]
like in kde and/or gnome

**Comment by palinek** [comment]
If implemented, please, make it configurable.
(for me such behaviour will be annoying)

**Comment by jleclanche** [comment]
I'm rejecting this. It's fairly hard to do on a technical level and generally unwanted. Making it configurable as a nondefault defeats the whole point; we can encourage third party runners instead if different behaviour is wanted.
