### ISSUE TITLE
lxqt-panel FTBFS, lxqt-panel*qm missed

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#605]
may be introduced in lxde/lxqt-panel@87af5ad01

that leads to
<pre>
CMake Error at panel/cmake_install.cmake:44 (file):
  file INSTALL cannot find
  "/home/agaida/work/siduction/code/extra/500-lxqt/4-lxqt-panel/experimental/checkout/panel/lxqt-panel_fi.qm".
</pre>

**Comment by paulolieuthier** [comment]
This is not a FTBFS, right? It's a failure on install. The translations files are probably outdated, I'll take a look at that.

**Comment by paulolieuthier** [comment]
I don't know much about the Qt's translation system. Maybe @luis-pereira can help here.

**Comment by paulolieuthier** [comment]
I get it with `lxqt-panel_fi.qm` as well.

**Comment by mmetak** [comment]
lxqt-panel_ro_RO.qm as well...

**Comment by palinek** [comment]
@agaida can you try to compile/install with lxde/lxqt-panel@6604101232f8143a086b64bce8227d19aabb27fe ?

**Comment by palinek** [comment]
fixed in  lxde/lxqt-panel@6604101

**Comment by agaida** [comment]
thank you
