### ISSUE TITLE
[Feature Request] Support Wallpaper slideshows

### ISSUE THREAD

**Issue by DiscipleOfDante** [lxde/lxqt#608]
Essentially allow using a directory or selecting a series of wallpapers to cycle between, with a user-specified timer. This is something most desktops support and can really add to the aesthetic appeal of LXQt.

**Comment by rscafi** [comment]
As a workaround, you can set a cron to do this job for you, randomizing images from a given folder:

```
bash -c 'pcmanfm-qt -w "$(find /path/to/wallpapers -type f | shuf -n1)"'
```

(I grabbed this script from the internet, but I can't remeber where to give the proper credits)

**Comment by DiscipleOfDante** [comment]
I will try and figure out how to do a cron job for this in the meantime, but I think this would still make a nice feature to have before the 1.0 release.

**Comment by Vladimir-csp** [comment]
there is an xml format for such things, used by Gnome and Unity at least. IMHO lxqt implementation should use the same format.
Example of standard Debian slideshow:
```
<background>
  <static>
    <duration>8640000.0</duration>
    <file>
      <size width="1280" height="1024">/usr/share/images/desktop-base/lines-wallpaper_1280x1024.svg</size>
      <size width="1600" height="1200">/usr/share/images/desktop-base/lines-wallpaper_1600x1200.svg</size>
      <size width="1920" height="1080">/usr/share/images/desktop-base/lines-wallpaper_1920x1080.svg</size>
      <size width="1920" height="1200">/usr/share/images/desktop-base/lines-wallpaper_1920x1200.svg</size>
      <size width="2560" height="1080">/usr/share/images/desktop-base/lines-wallpaper_2560x1080.svg</size>
    </file>
  </static>
</background>
```

I do not know the origin of the spec, but here is a descriotion here: https://help.ubuntu.com/community/SlideshowWallpapers

**Comment by DiscipleOfDante** [comment]
Yes but perhaps with an auto-generator as well? Even just like a little tool that allows you to input files paths, and set a duration?

**Comment by jleclanche** [comment]
I'm ok with wallpaper slideshows going in and yes I agree we should use the same xml format as others if possible.

**Comment by tjgillies** [comment]
When I try to create cron I'm getting `QXcbConnection: Could not connect to display`

I'm on Arch

**Comment by yan12125** [comment]
Did you specify ```$DISPLAY``` in the cron script?

**Comment by tjgillies** [comment]
I didn't previously, but when I do add it, it's just silently failing heh.

**Comment by tsujan** [comment]
A startup script like this (which I call "wallpaper-changer-mine") can be used with a delay, provided that WALLPAPER_FOLDER contains JPG wallpapers:
````
#!/bin/bash
while true
do
	pcmanfm-qt --set-wallpaper "`find WALLPAPER_FOLDER -name "*.jpg" | shuf -n 1`"
	sleep 3600
done
exit
````
The script should be stopped on log-in, so it's better to have a general startup script like this:
```
#!/bin/bash
...
killall wallpaper-changer-mine
...
sleep 15
if pgrep "pcmanfm-qt" > /dev/null
then
  wallpaper-changer-mine
  ...
fi
...
exit
```

**Comment by tsujan** [comment]
My point: there is no need to an app. Something like the above script can be used in almost all DE's provided that the command for settings wallpapers is known -- only KDE doesn't need it.

**Comment by goetzc** [comment]
A way to access this from the Configuration center (settings manager or such) would be user friendly.

**Comment by tsujan** [comment]
OK! I'll see what can be done in pcmanfm-qt.

BTW, Desktop Preferences is a better place for a slideshow setting (as in KDE); isn't it?

**Comment by tsujan** [comment]
I added a wallpaper slideshow to pcmanfm-qt (not uploaded yet). IMO, the minimum interval is better to be 15 min and the maximum 48 h because less than 15 min would be disturbing (actually, I think 30 min is better for the minimum) and someone who sets it to more than 48 h doesn't need a slideshow.

I'll make a PR after finishing the code and doing some tests. It may take a while.

**Comment by tsujan** [comment]
Done by https://github.com/lxde/pcmanfm-qt/issues/423! This is the setting:

![slideshow](https://cloud.githubusercontent.com/assets/981076/21105663/46d7a9d0-c0a0-11e6-9273-c739ed2aaafe.png)

**Comment by goetzc** [comment]
Hey, nice!

**Comment by tsujan** [comment]
@goetzc 
Thanks! Do you mean the setting or did you try it? I'm using it for 2 days now and everything seems OK :)

**Comment by goetzc** [comment]
@tsujan I mean the settings screenshot, I haven't had time to try it.

**Comment by mariocarro** [comment]
Regarding the cron job: pcmanfm-qt requires both the DISPLAY and DBUS_SESSION_BUS_ADDRESS environment variables correctly initialized to be able to set the wallpaper.

**Comment by pmattern** [comment]
The approach currently discussed in lxde/pcmanfm-qt#423 no longer needs a cron job.

**Comment by tsujan** [comment]
The new patch (after C++11 port and other changes to libfm-qt) is here: https://github.com/lxde/pcmanfm-qt/pull/546
