### ISSUE TITLE
Removable media widget and pcmanfm unpredictable behavior

### ISSUE THREAD

**Issue by gbcox** [lxde/lxqt#610]
I have a btrfs usb3 drive...  when I plug it in, I get the message from the widget it is available.  I then see a popup if I want to open it with the file manager.  Sure... so pcmanfm opens, everything is working fine.  Can copy to it, read from it, delete from it, no problem.  I then close pcmanfm and do other things.  Now I decide, ok, don't want the drive anymore so I go to the widget to umount it.  I press the unmount symbol... nothing happens.  I then open pcmanfm, it shows the drive is still mounted.  I press the unmount in pcmanfm.  pcmanfm abruptly closes.  I then ask myself, is the drive still there or not, I go back to the widget... yup it shows still there.  I go back to pcmanfm to try again to unmount.  pcmanfm again just closes, no messages, nothing.   Finally, I open nautilus and use "remove drive".  I get a pop-up saying the drive has been removed.  I then go back to the widget and it says the drive is still there --- but it isn't.   I finally have to logoff and back on to reset the widget to the correct status.

**Comment by npmiller** [comment]
Gave this a quick investigation, the plugin-mount seems to be working okay on it's own, the problem is that it relies on:
http://api.kde.org/frameworks-api/frameworks5-apidocs/solid/html/classSolid_1_1DeviceNotifier.html
To get notified about the devices, and this only provides signal when a device is added or removed, so if something else than the plugin mounts (or unmounts) a volume, the plugin is not notified and it appears unchanged. That's a big part of the problem here.

**Comment by paulolieuthier** [comment]
Well, it should be notifier whenever a device changes state, no matter which program did it.

**Comment by npmiller** [comment]
Yes, but not with this api then

**Comment by paulolieuthier** [comment]
I meant with this API.

**Comment by paulolieuthier** [comment]
I can reproduce certain bugs. However, the problem is not the API, it's the misuse of it.

**Comment by palinek** [comment]
I didn't see such behaviour, but pushed handling of `accessibilityChanged` signal in lxde/lxqt-panel@0506738 -> for me this fixes changing state of 'eject' in case of manual unmount (*# umount _\<dev\>*).
@gbcox can you, please, test if this makes any difference in your scenario?

**Comment by palinek** [comment]
...and for the pcmanfm-qt. There is a configuration of what should pcmanfm-qt do when removable media is inserted/unmounted Edit->Preferences->Volume :
![screenshot](https://cloud.githubusercontent.com/assets/10990929/7285388/645abf0e-e944-11e4-8982-1511b1999890.png)
=> if you had only one tab, after unmount the whole window is closed

**Comment by paulolieuthier** [comment]
@palinek your fix didn't work for me. When I mounted a device using another application, the mount plugin didn't get it. I just commited a large refactoring with the fix: lxde/lxqt-panel@5575aaedd468b89d00fef59ae3e6d76ceeb772ca.

@gbcox can you test current master, please?

**Comment by palinek** [comment]
@paulolieuthier don't know what do you mean by 'another application', but on my system the state is correctly update after 'plain' mount e.g. *# mount -t vfat /dev/sdb1 /mnt/usb*
...why did you remove the actions? (I was using the notification...)

**Comment by gbcox** [comment]
@paulolieuthier, @palinek:  I'm running the Fedora rpms, not the github version.  I did check 
the pcmanfm-qt mount settings and saw where I had close tab checked, which is probably why pcmanfm closed.  I switched it to change folder and appears to be working correctly - although I get absolutely no messages from the  widget or pcmanfm - and the widget during the entire process showed no devices are available.

**Comment by paulolieuthier** [comment]
@palinek sorry about that. Reading the code, I thought that wasn't being used (at least KDevelop didn't show any actial use). I'll revert it and add the actions back.

**Comment by palinek** [comment]
> I'm running the Fedora rpms, not the github version.
@gbcox you are probably still using the old fashioned `plugin-mount` (based on [this](https://apps.fedoraproject.org/packages/lxqt-panel/builds/) latest packages were build 2 months ago). The plugin was buggy and on 2015-02-25 migration to new backend was commited.
