### ISSUE TITLE
[lxqt-panel] Panel doesn't hide if the 'Application menu' is clicked w/o closure

### ISSUE THREAD

**Issue by jeremywh7** [lxde/lxqt#611]
Running Arch x64, lxqt 0.9.0 but lxqt-panel from git (and dependencies) to enable autohide.  I'm not sure if this was from the initial autohide merge or a change since, but I've noticed since yesterday that:
-if you click the 'Application menu' then, even if an application is opened, click on the desktop...and keep clicking; the panel will never autohide
-...but if you move the mouse over the panel and back off of it again, it will autohide
-note, if you click to open the 'Application menu' and then click again to close it...this doesn't happen

**Comment by palinek** [comment]
@jeremywh7 can you, please, confirm that hiding is now fixed for you?

**Comment by jeremywh7** [comment]
Confirmed fixed, trying all test cases from my opening post.  And I broke my rule of no git before work to check it out.  :-P  Thanks for the quick turn-around; and can't wait for the next release!
