### ISSUE TITLE
Cannot unmute the volume after muting on 0.9

### ISSUE THREAD

**Issue by rscafi** [lxde/lxqt#612]
Related to #253, I'm experiencing the same issue on latest version.

Which additional information you guys need to track it down?

**Comment by paulolieuthier** [comment]
Which distro? How did you install LXQt? What audio backend (PulseAudio, Alsa, Oss)? Do you always reproduce the bug, or just sometimes?

**Comment by rscafi** [comment]
I'm using Lubuntu 14.10, just installed lxqt via apt-get and changed to it at login screen.
It happens everytime that I mute it. To fix it I go to Sound preferences (I guess from LXDE settings) and unmute it.
I don't know about the backend (kind newbie), how to figure it out?

**Comment by rscafi** [comment]
Is this it?

```
>>> list-sinks
2 sink(s) available.
    index: 0
	name: <alsa_output.pci-0000_00_03.0.hdmi-stereo>
	driver: <module-alsa-card.c>
	flags: HARDWARE DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: SUSPENDED
	suspend cause: IDLE 
	priority: 9950
	volume: 0: 100% 1: 100%
	        0: 0,00 dB 1: 0,00 dB
	        balance 0,00
	base volume: 100%
	             0,00 dB
	volume steps: 65537
	muted: no
	current latency: 0,00 ms
	max request: 0 KiB
	max rewind: 0 KiB
	monitor source: 0
	sample spec: s16le 2ch 44100Hz
	channel map: front-left,front-right
	             Stereo
	used by: 0
	linked by: 0
	configured latency: 0,00 ms; range is 0,50 .. 371,52 ms
	card: 0 <alsa_card.pci-0000_00_03.0>
	module: 5
	properties:
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "HDMI 0"
		alsa.id = "HDMI 0"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "3"
		alsa.card = "0"
		alsa.card_name = "HDA Intel HDMI"
		alsa.long_card_name = "HDA Intel HDMI at 0xf7e14000 irq 61"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:03.0"
		sysfs.path = "/devices/pci0000:00/0000:00:03.0/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "0a0c"
		device.product.name = "Haswell-ULT HD Audio Controller"
		device.form_factor = "internal"
		device.string = "hdmi:0"
		device.buffering.buffer_size = "65536"
		device.buffering.fragment_size = "32768"
		device.access_mode = "mmap+timer"
		device.profile.name = "hdmi-stereo"
		device.profile.description = "Digital Stereo (HDMI)"
		device.description = "Áudio interno Digital Stereo (HDMI)"
		alsa.mixer_name = "Intel Haswell HDMI"
		alsa.components = "HDA:80862807,80860101,00100000"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	ports:
		hdmi-output-0: HDMI / DisplayPort (priority 5900, latency offset 0 usec, available: no)
			properties:
				device.icon_name = "video-display"
	active port: <hdmi-output-0>
  * index: 1
	name: <alsa_output.pci-0000_00_1b.0.analog-stereo>
	driver: <module-alsa-card.c>
	flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: RUNNING
	suspend cause: 
	priority: 9959
	volume: 0:  14% 1:  14%
	        0: -52,00 dB 1: -52,00 dB
	        balance 0,00
	base volume: 100%
	             0,00 dB
	volume steps: 65537
	muted: no
	current latency: 22,61 ms
	max request: 4 KiB
	max rewind: 64 KiB
	monitor source: 1
	sample spec: s16le 2ch 44100Hz
	channel map: front-left,front-right
	             Stereo
	used by: 1
	linked by: 1
	configured latency: 23,22 ms; range is 1,00 .. 371,52 ms
	card: 1 <alsa_card.pci-0000_00_1b.0>
	module: 6
	properties:
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "CX20751/2 Analog"
		alsa.id = "CX20751/2 Analog"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "1"
		alsa.card_name = "HDA Intel PCH"
		alsa.long_card_name = "HDA Intel PCH at 0xf7e10000 irq 59"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:1b.0"
		sysfs.path = "/devices/pci0000:00/0000:00:1b.0/sound/card1"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "9c20"
		device.product.name = "8 Series HD Audio Controller"
		device.form_factor = "internal"
		device.string = "front:1"
		device.buffering.buffer_size = "65536"
		device.buffering.fragment_size = "32768"
		device.access_mode = "mmap+timer"
		device.profile.name = "analog-stereo"
		device.profile.description = "Estéreo analógico"
		device.description = "Áudio interno Estéreo analógico"
		alsa.mixer_name = "Conexant CX20751/2"
		alsa.components = "HDA:14f1510f,104311bf,00100100"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	ports:
		analog-output-speaker: Alto-falantes (priority 10000, latency offset 0 usec, available: no)
			properties:
				device.icon_name = "audio-speakers"
		analog-output-headphones: Fones de ouvido analógico (priority 9000, latency offset 0 usec, available: yes)
			properties:
				device.icon_name = "audio-headphones"
	active port: <analog-output-headphones>
```

**Comment by rscafi** [comment]
Also, the volume increment/decrement is sometimes wrong. If I use 2% increment in configs, it will most of the times increment by 2%, but sometimes will increment by 3%.
It happens with other values too.

**Comment by pmattern** [comment]
I think "backend" is referring to the settings tweaked in dialogue window "Volume Control Settings" invoked e. g. from the plugin's context menu (right click - Configure Volume Control).
![lxqt_panel-plugin-volume-control_configuration](https://cloud.githubusercontent.com/assets/9860801/7320232/6c1b89fa-ea9b-11e4-9b49-b657ac533fae.png)

**Comment by rscafi** [comment]
Oh, I see. I'm using Alsa.

**Comment by paulolieuthier** [comment]
@rscafi are you using the [lubuntu-daily](https://launchpad.net/~lubuntu-dev/+archive/ubuntu/lubuntu-daily) PPA?

**Comment by rscafi** [comment]
@paulolieuthier yes, I am.

**Comment by paulolieuthier** [comment]
@rscafi I can't reproduce the bug. Are you able to unmute using alsamixer (mute/unmute using the `M` key)?

**Comment by rscafi** [comment]
@paulolieuthier If I hit F6 inside alsamixer and choose the correct device, then the bug happens too.
So I guess it is not related to lxqt?

**Comment by paulolieuthier** [comment]
Most probably not.

**Comment by pmattern** [comment]
At least one possible reason of this problem is some weird interaction between PulseAudio and Alsa:
As soon as PulseAudio is installed muting a single control like 'Master', 'PCM' or any of those corresponding to output like Front, Side, Rear etc. will mute all controls within that group. In contrast un-muting is affecting only the channel it's applied to itself.
Neither do I know any rationale of this mode of operation nor any way to prevent it.

Possible workarounds are removing PulseAudio completely or using it by default, in particular in LXQt's respective panel plugin as well, compare screenshot above.

**Comment by tomchiverton** [comment]
I'm using Ubutnu from the daily PPA, and have this issue. My volume control settings don't have a pulseaudio option though. Am I missing a library or something ? 

pavucontrol mixer loads OK so pulse audio must be working ? But after muting with hardware button or the tray icon, I have to unmute using pavucontrol (on the output devices page).

**Comment by pmattern** [comment]
> I'm using Ubutnu from the daily PPA, [...]

Hm, probably some accidental statement and you're in fact running LXQt from a PPA on Ubuntu. Could you elaborate which version of Ubuntu you're running and how you installed LXQt?

**Comment by tomchiverton** [comment]
Yes, I meant I'm on Ubuntu 14.04, using packages from the LXQT PPA, as per https://github.com/lxde/lxqt/wiki

**Comment by pmattern** [comment]
I can confirm the lack of topic "PulseAudio" as depicted in the screenshot above on Trusty + LXQt from PPA ppa:lubuntu-dev/lubuntu-daily besides full-blown PulseAudio is available.
I can't tell you the reason and have to admit I lack both time and motivation to further look into this.
What I can tell is that running that PPA on Trusty doesn't seem like a good choice to me. Except the problem we've seen right now I ran into lots of others before like failure to save mouse cursor's theme or display resolution. If LXQt did draw your interest I personally think you'd better switch to Lubuntu or a more recent version of Ubuntu where none of these problems exists.

Nevertheless I still believe the actual problem regarding sound output is caused by the behaviour I tried to explain in my second to last post (which I've edited in the meantime to put some things more clearly).
You may want to verify by running alsamixer in a terminal emulator such that you can see it while tweaking the mute button of LXQt panel's volume plugin.

**Comment by tomchiverton** [comment]
OK, so it's only bust for Ubuntu 14.04 LTS ? 15.04, for instance, is known OK ?

**Comment by pmattern** [comment]
After updating my local systems it seems that the lack of item "PulseAudio" in the configuration dialog of LXQt panel plugin "volume" is common to all variants provided by PPA ppa:lubuntu-dev/lubuntu-daily. At least I can see it on Ubuntu 14.04 and 15.04 as well as Lubuntu 15.04.
On a side note Lubuntu 15.04 is the only one of those three where the mouse cursor's icon theme gets saved reasonably here.

Note that the actual problem of this issue, the weird interaction PulseAudio - Alsa as described above can be seen on all kinds of distributions right now. It is however not caused by LXQt in any way which is why this issue got closed.

**Comment by tomchiverton** [comment]
Does the volume control do detection at run time, or does it have to be compiled in to work ?

**Comment by pmattern** [comment]
To my knowledge it doesn't. It allows for handling those audio systems the corresponding files of which were available when lxqt-panel was compiled and it's up to the packagers to set the dependencies of the package providing the panel accordingly.
Not 100% sure, though.

**Comment by tomchiverton** [comment]
Obviously needs some more work. but it's a different issue to this : #747

**Comment by ChristianMercat** [comment]
Hi there, I do have the same kind of behavior: on my HP Elitebook with Lubuntu Linux 6.5.0-18-generic x86_64, the two buttons up/down work fine, lxqt-panel tells me that the Volume changes, the mute button does mute my sof-hda-dsp Speaker, the keyboard led lights on and off accordingly, but it actually stays muted. I have to go to the Mixer and click on the muted icon, to set it back to unmuted.
![mixer](https://github.com/lxqt/lxqt/assets/1215816/7013c4f5-bbae-4659-9109-a024578f021f)

>   * index: 3
        name: <alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink>
        driver: <module-alsa-card.c>
        flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
        state: IDLE
        suspend cause: (none)
        priority: 9032
        volume: front-left: 49145 /  75% / -7.50 dB,   front-right: 49145 /  75% / -7.50 dB
                balance 0.00
        base volume: 65536 / 100% / 0.00 dB
        volume steps: 65537
        muted: no
        current latency: 39.92 ms
        max request: 7 KiB
        max rewind: 7 KiB
        monitor source: 3
        sample spec: s16le 2ch 48000Hz
        channel map: front-left,front-right
                     Stéréo
        used by: 0
        linked by: 3
        configured latency: 40.00 ms; range is 0.50 .. 341.33 ms
        card: 0 <alsa_card.pci-0000_00_1f.3-platform-skl_hda_dsp_generic>
        module: 7
        properties:
                alsa.resolution_bits = "16"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = ""
                alsa.id = "HDA Analog (*)"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "0"
                alsa.card = "0"
                alsa.card_name = "sof-hda-dsp"
                alsa.long_card_name = "HP-HPEliteBook83013inchG10NotebookPC--8B41"
                alsa.driver_name = "snd_soc_skl_hda_dsp"
                device.bus_path = "pci-0000:00:1f.3-platform-skl_hda_dsp_generic"
                sysfs.path = "/devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0"
                device.bus = "pci"
                device.vendor.id = "8086"
                device.vendor.name = "Intel Corporation"
                device.product.id = "51ca"
                device.string = "_ucm0001.hw:sofhdadsp"
                device.buffering.buffer_size = "65536"
                device.buffering.fragment_size = "16384"
                device.access_mode = "mmap+timer"
                device.profile.name = "HiFi: hw:sofhdadsp: sink"
                device.profile.description = "Speaker + Headphones"
                alsa.mixer_device = "_ucm0001.hw:sofhdadsp"
                device.description = "sof-hda-dsp Speaker + Headphones"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card-pci"
        ports:
                [Out] Speaker: Speaker (priority 100, latency offset 0 usec, available: unknown)
                        properties:
                [Out] Headphones: Headphones (priority 200, latency offset 0 usec, available: no)
                        properties:
        active port: <[Out] Speaker>
