### ISSUE TITLE
Panel context menu shows at wrong position using two monitors with different resolutions

### ISSUE THREAD

**Issue by rscafi** [lxde/lxqt#613]
I have two different monitors and I'm using two panels, each one at the bottom of each monitor.
The context menu (right click menu) is shown at wrong position on the biggest screen, and my guess is that the position is being calculated using information from the another screen.

(I would post an screenshot, but I just realised that the printscreen button is doing nothing on lxqt)

**Comment by rscafi** [comment]
![teste](https://cloud.githubusercontent.com/assets/6104262/7305594/7fa11f9c-e9d5-11e4-8463-498596cbf084.png)

**Comment by rscafi** [comment]
Also regarding the context menu of panels, if it is open, printscreen button won't work (but works normally if the context screen is closed).

**Comment by paulolieuthier** [comment]
@rscafi you have one panel for each screen, right?

**Comment by paulolieuthier** [comment]
@rscafi can you update it and test it please?

**Comment by jleclanche** [comment]
Pretty sure I filed an issue about this a while back.

**Comment by rscafi** [comment]
@paulolieuthier I'm sorry, I've switched jobs and I'm no longer using two monitors.

**Comment by paulolieuthier** [comment]
@rscafi np, thanks for your help.

**Comment by paulolieuthier** [comment]
@jleclanche can you reproduce it?

**Comment by jleclanche** [comment]
Not right now. But with 2 monitors it's just a matter of changing the resolution of one of them.

**Comment by paulolieuthier** [comment]
But there was an attempt to fix it. Please, test it again when you can.

**Comment by palinek** [comment]
@paulolieuthier I can see such (wrong) placing here

**Comment by paulolieuthier** [comment]
This really seems like a Qt bug for me. The group popups appear normally, the title popups as well. Only the freaking right click's `QMenu` has a problem. The panel's geometry and the cursor's position are OK as well.

**Comment by palinek** [comment]
IMO we can close this.

Is anyone still experiencing wrong placing menus in lxqt-panel after lxde/lxqt-panel@29b96a3?
