### ISSUE TITLE
Cannot use more than one instance of Notification Area widget

### ISSUE THREAD

**Issue by rscafi** [lxde/lxqt#614]
If I try to add this widget to another panel, it will be blank. If I remove the widget from the other panel, then I can it. Basically, only one instance is showing up.

**Comment by palinek** [comment]
You are probably talking about `Task manager' widget.

> Basically, only one instance is showing up.

Yes, that's completely right and AFAIK it's defined in [Xembed](http://standards.freedesktop.org/xembed-spec/xembed-spec-latest.html) specification.

**Comment by rscafi** [comment]
@palinek I'm sorry, my lxqt is localized to pt_BR. The "Task Manager" widget actually works across multiple panels.
I went to the translations to see the correct name and the widget that I'm talking about is "System tray". I can only have it active at one panel. Is it right too?

**Comment by Vladimir-csp** [comment]
It is in the tray spec itself, there can be no second tray on the desktop.
