### ISSUE TITLE
configuration center and single click

### ISSUE THREAD

**Issue by Esclapion** [lxde/lxqt#616]
When single-click is enabled in pcmanfm-qt, we always must click twice to open something in the configuration center, it's a bit annoying.

**Comment by Vladimir-csp** [comment]
pcmanfm-qt and lxqt-config are totally separate applications. Why should they ever read each others` configuration?

**Comment by Esclapion** [comment]
It's a technical point-of-view that i understand, but for the user, it's really strange : if he activates one-click, he runs applications and open all with one click except in the configuration center. Difficult to understand for him. I self am annoyed by that.
It could be something common to all ? lxqt is a whole.

**Comment by paulolieuthier** [comment]
@Esclapion does single click in configuration center work after you enable it on lxqt-config-input?

**Comment by paulolieuthier** [comment]
>  It could be something common to all ? lxqt is a whole.

Yes, that should be set in the Qt plugin it self, and all Qt applications should then obey it.

**Comment by Esclapion** [comment]
Yep, it works perfect, my bad. I close for the moment, but it's a bit complicate. Centralize that would be a good idea, yes.

**Comment by paulolieuthier** [comment]
@Esclapion you're right. That should be fixed in pcmanfm-qt.
