### ISSUE TITLE
Bad french translation of lxqt-notificationd

### ISSUE THREAD

**Issue by Esclapion** [lxde/lxqt#617]
I think it's only not done, "name" and "comment' are the same than for lxqt-config-session.
Sorry to open an issue only for that, but i dont know the procedure to follow for change that.
![ess](https://cloud.githubusercontent.com/assets/3512979/7318192/6253d768-ea89-11e4-8abc-4501a2e0ee85.png)

**Comment by palinek** [comment]
@Esclapion french translation is in this file `lxde/lxqt-notificationd/config/translations/lxqt-config-notificationd_fr_FR.desktop`...

**Comment by Esclapion** [comment]
Yes, thanks, I found that, but can I change that directly in github ? The content :

# Translations
GenericName[fr_FR]=Bloc-notes
Name[fr_FR]=Paramétreur de session LxQt

**Comment by palinek** [comment]
Give me the translation and i'll put it there.

**Comment by Esclapion** [comment]
Thanks :

GenericName[fr_FR]=Paramétrage des notifications du bureau
Name[fr_FR]=Paramétrage notifications

btw, a lot of others are always in english.
