### ISSUE TITLE
lxqt-panel and Linux 4.0 kernel

### ISSUE THREAD

**Issue by flamusdiu** [lxde/lxqt#620]
I am not sure what's going on but `linux-ck` upgraded to use the 4.0 sources and the panel seems to hate it. On boot up, it's unresponsive for at least 3-5 mins then it's fine. Desktop icons (and the OpenBox stuff) seems to work but the "Volume Control" widget is no longer grabbing the XF86Audio* keys.

**Comment by paulolieuthier** [comment]
I don't see why it'd be related to the kernel. IMO it's definitely related to lxqt-notificationd's keys grabbing.

**Comment by Ilya87** [comment]
Volume Control not only not grabbing, but aplay -l shows no devices. My OS is Arch x86_64. Also with this new kernel I got full system freeze and then, obviously, installed stable kernel - all is fine.

**Comment by flamusdiu** [comment]
@Ilya87 some issues with 4.0 atm. I use the -ck kernels and 3.19 works but 4.0 does not for x86_64. We are just going have to wait for the fix.

**Comment by palinek** [comment]
Any news here?

**Comment by paulolieuthier** [comment]
Closed as invalid. See #314.
