### ISSUE TITLE
Panel's taskbar crash.

### ISSUE THREAD

**Issue by zjes** [lxde/lxqt#622]
Hi, i found small issue. Taskbar crash if you hide/close non displaying window in the current taskbar. Quickfix (maybe wrong, i don't check this logic, fixed only result, not reason :)):
```diff
diff --git a/plugin-taskbar/lxqttaskbar.cpp b/plugin-taskbar/lxqttaskbar.cpp
index d89676e..6398ec5 100644
--- a/plugin-taskbar/lxqttaskbar.cpp
+++ b/plugin-taskbar/lxqttaskbar.cpp
@@ -207,7 +207,11 @@ void LxQtTaskBar::groupBecomeEmptySlot()
     LxQtTaskGroup *group = qobject_cast<LxQtTaskGroup*>(sender());
     Q_ASSERT(group);

+    if (!group->windowId())
+        return;
+
     QString id = mGroupingEnabled ? group->groupName() : QString("%1").arg(group->windowId());
     mGroupsHash.erase(mGroupsHash.find(id));
     group->deleteLater();
 }
```

**Comment by palinek** [comment]
@zjes  thanks for reporting and giving a clue for solution. Can you, please, confirm if the issue has been fixed by  lxde/lxqt-panel@9458d0e?

**Comment by zjes** [comment]
This looks ok... 
But now i found other issue... but it depend on previous "show tasks by current desktop only" changeset. If you move window between desktops, task button doesn't move. You need hide/restore window to show task button. Create issue with clue? :)

**Comment by palinek** [comment]
I've noticed that also... Have a look on lxde/lxqt-panel@12c0ed38de7f5ced0518558d5bccb5ddf7eed35f

**Comment by zjes** [comment]
Great, thank you. :)
