### ISSUE TITLE
Translation not loaded

### ISSUE THREAD

**Issue by Ilya87** [lxde/lxqt#623]
I have installed Russian translation in the system, but it doesn't loads.
![screen](https://cloud.githubusercontent.com/assets/1446573/7363574/c072557e-ed84-11e4-947d-826992e24e2c.png)

**Comment by palinek** [comment]
What's your locale setting -> the output of `locale` in terminal?

**Comment by Ilya87** [comment]
LANG=ru_RU.utf8
LC_CTYPE="ru_RU.utf8"
LC_NUMERIC="ru_RU.utf8"
LC_TIME="ru_RU.utf8"
LC_COLLATE=C
LC_MONETARY="ru_RU.utf8"
LC_MESSAGES="ru_RU.utf8"
LC_PAPER="ru_RU.utf8"
LC_NAME="ru_RU.utf8"
LC_ADDRESS="ru_RU.utf8"
LC_TELEPHONE="ru_RU.utf8"
LC_MEASUREMENT="ru_RU.utf8"
LC_IDENTIFICATION="ru_RU.utf8"
LC_ALL=

**Comment by palinek** [comment]
Try to set also LANGUAGE into environment, to something like this:
```bash
LANGUAGE=ru_RU:ru
```

**Comment by Ilya87** [comment]
This doesn't help. Also note, I have Configure "Панель задач" option in screenshot (contex menu). Also taskbar widget options are in Russian 
![screen](https://cloud.githubusercontent.com/assets/1446573/7385461/716f09d8-ee4f-11e4-8ab9-4f4ea61f1a3b.png)

**Comment by palinek** [comment]
@Ilya87 can you, please, confirm that lxde/lxqt-panel@767d704 fixes this issue?

@paulolieuthier can you have a look if you didn't change usage of lxqt_app_translation_loader in wrong way also in other components?

**Comment by Ilya87** [comment]
Fixed
