### ISSUE TITLE
the panel menu button should have a default fallback icon

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#624]
which should used on a not configured (themed) panel: http://i.imgur.com/x1PAz8g.png

**Comment by intialonso** [comment]
In fact I think that we should not use the LXQT logo as the menu icon, it doesnt look good.

Some ideas:

* Use the system theme "start-here" icon.
* Use a more generic "menu" icon (see the Firefox menu).
![screen2](https://cloud.githubusercontent.com/assets/7544231/9744906/32adb7ba-5634-11e5-8c33-96fec9cab2b1.png)
* Give the user the option to set the icon as in xfce and kde.

**Comment by jleclanche** [comment]
The menu is the only place the LXQt logo is used. I think it looks great personally. But I wouldn't be against an option to set a custom one.

**Comment by pmattern** [comment]
Personally I'd vote for having the icon configurable but using the LXQt icon by default.
It really doesn't look bad and I think it's reasonable to have something genuine at that position.

"Configurable" doesn't necessarily mean "custom" only but could also comprise an option "Use foo-bar from theme".
Having the icon configurable is dealed with in #720 already. Sort of.

In Adwaita "start-here" is that ridiculous GNOME footprint. Just saying.

Side-note:
Among the themes provided by lxqt-common all are using the LXQt logo except "Light" which is using the one from Razor-Qt. Is this really intentional?

**Comment by jleclanche** [comment]
> Among the themes provided by lxqt-common all are using the LXQt logo except "Light" which is using the one from Razor-Qt.

Yes, the theme shouldn't be called "Light", we were going to rename it "Razor". Those names are generated from the filesystem names... Themes were supposed to have localizable names, didn't make it in time for 0.8. Would you work on this?

**Comment by pmattern** [comment]
For sure, I can have a look into this. But I'm not following right now:

Technically, no FHS object (file, directory, symbolic link) in theme Light is stating string light in terms of the theme's name (same thing with string razor, btw.). So it remains unclear how theme name Light should have been derived from some filesystem name. Also, I cannot figure a difference between "Light" and "Razor" with regards to localization.
Conceptually, I don't understand why the term Razor should be preserved as the theme is an LXQt component after all. All I could figure was having some kind of memory or something. But while I sure wouldn't call this ridiculous or so per se I still cannot see any real benefit if the manifestation is a theme's name or the icon that's actually this issue's subject.

All in all having theme Light just use the LXQt icon as well seems like the easier and more reasonable thing to do to me.

**Comment by palinek** [comment]
The mainmenu icon is already defined by panel itself (and can be overriden by theme .qss) and is also configurable. Can we close this?

**Comment by intialonso** [comment]
I agree.
Closing as this is irrelevant with options named by palinek.
