### ISSUE TITLE
pcmanfm-qt: no keyboard shortcut to create a new folder?

### ISSUE THREAD

**Issue by excalibur1234** [lxde/lxqt#626]
in dolphin and thunar you can press CTRL + SHIFT + N to create a new folder. it even works in windows. it is like a quasi-standard. but this keyboard shortcut does not work in pcmanfm-qt.

is there already another keyboard shortcut to create a new folder in pcmanfm-qt or can you add this keyboard shortcut?
it is not comfortable to keep switching between the mouse and keyboard just to create a new folder.

**Comment by pmattern** [comment]
I think this issues is definitely valid but it should be merged into lxde/pcmanfm-qt#163 as it's related closely.

@excalibur1234 
If you don't mind please copy your issue as new comment to the one stated above so that we can close this one.

**Comment by excalibur1234** [comment]
done.
