### ISSUE TITLE
[lxqt-panel] Panel doesn't hide if a 'Configure...' properties dialog is opened

### ISSUE THREAD

**Issue by jeremywh7** [lxde/lxqt#629]
Ref:  https://github.com/lxde/lxqt/issues/611

Related to the above issue, I'm not sure if I hadn't tried this before, or if I just now noticed it, but if I open any 'Configure...' properties window, w/ or w/o closing it, it remains unhidden (even clicking on the desktop), until a mouse-over.

I can see it not hiding it the Configure dialog is still open, but it was a more apparent issue that it stayed unhidden after closing it.

Update:  Actually, just right-clicking anything on the Panel then moving off of it makes it get stuck unhidden, until mouse-over.

**Comment by palinek** [comment]
> Update: Actually, just right-clicking anything on the Panel then moving off of it makes it get stuck unhidden, until mouse-over.

I think this is related to a bug in QT as discussed in lxde/lxqt#436

**Comment by jeremywh7** [comment]
Ok thanks; I will retest when Qt 5.4.2 is out.

**Comment by jeremywh7** [comment]
And it is now released...
http://download.qt.io/official_releases/qt/5.4/5.4.2/
https://wiki.qt.io/Qt_5.4.2_Known_Issues
If Arch doesn't update the package soon, I'll install it manually to retest.  There are several potential lxqt open issues that are awaiting 5.4.2 right?

**Comment by jeremywh7** [comment]
So I'm on Qt 5.4.2 now, and I do see that issue 436 is fixed, however, the issue I raised here is not.  Right clicking an item in the panel (and either selecting something or just moving off and clicking in the desktop) causes the panel to be stuck unhidden, until mousing over the panel again.

**Comment by jeremywh7** [comment]
The stuck unhide is now resolved!  I do now notice that the panel auto-hides when still hovered in the Application Menu or a right-click menu (as opposed to auto-hiding when the mouse moves off the Application or right-click menu, and obviously also not within the panel region).  I personally don't care; but I suspect others might.  Much love, @palinek :-P

**Comment by jeremywh7** [comment]
\>I do now notice that the panel auto-hides when still hovered in the Application Menu or a right-click menu

So, I see that LXDE does the same thing, so I guess most won't care.  :-)

**Comment by jeremywh7** [comment]
@palinek: I've now updated my arch setup to use an AUR helper to build lxqt-desktop-git; I was previously just manually building lxqt-panel-git and its many dependencies.  I will note that my system updated to Qt 5.5.1 today too.

It appears this issue has regressed; afaict I am building lxqt-desktop-git correctly; it picked up the lxqt-powermanagement-git change today, and lxqt-panel-git is at change 331 since the last release label.

**Comment by paulolieuthier** [comment]
In #853 now.
