### ISSUE TITLE
Add panel widgets does not have icons for adding panel widgets. 

### ISSUE THREAD

**Issue by ianorlin** [lxde/lxqt#630]
Add panel widgets does not have icons for several of the panel widgets when you right click on the icon and click add panel widgets. 

I am using siduction with the latest updates pulled in as of yesterday. 

lxqt-panel:
  Installed: 0.9.0-9a
  Candidate: 0.9.0-9a
  Version table:
 *** 0.9.0-9a 0
        500 http://ftp.spline.de/pub/siduction/extra/ unstable/main amd64 Packages
        100 /var/lib/dpkg/status

I tired several diffent icon themes and there were not icons for several of the widgets. 

![2015-05-02-020203_1920x1080_scrot](https://cloud.githubusercontent.com/assets/7546640/7440552/9600d4a6-f071-11e4-9235-b76a1bacb0f2.png)

**Comment by paulolieuthier** [comment]
All widgets now have icons, but that's on current code in git. Next version you'll get them. Thanks.
