### ISSUE TITLE
limit number of instances per plugin

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#637]
Dialog window "lxqt-panel" as invoked from "Configure Panel" (see #598) allows for adding an arbitrary number of instances of all plugins available. This is conflicting with the functionality of e. g. System tray which may only appear once due to restrictions of the specifications it's implementing. This had already to be discussed in #614.
So a way should be found to limit the maximum number of instances per plugin that may be added.

Maybe that maximum number could somehow be hard-coded in the plugins and sourced by window "lxqt-panel".

**Comment by paulolieuthier** [comment]
Maybe it doesn't make much sense to have a limit. Just a flag to forbid more than one is enough. What do you think?

**Comment by pmattern** [comment]
I had already asked this myself when opening this issue, too.
Right now I can't figure a use-case were it's indeed necessary to have some arbitrary number > 1 as limit. The idea was rather to have it available should it be needed some time.
But all in all a simple flag would probably do, yes.
