### ISSUE TITLE
Tray icon issues

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#641]
Hi everyone!
I'm using tint2 panel, and I have constant problems with lxqt-powermanagement and qlipper. Their icons disappear from tray from time to time, but processes are still alive.
No problem with any other tray applications, just these lxqt-related.

Here is the log of lxqt-powermanagement (repeated messages about screen locking, inactivity and battery are truncated): http://pastebin.com/UZmAvTW5

**Comment by pmattern** [comment]
This is just my personal opinion, but I really don't see any point in making efforts to try and support a GTK panel that hasn't seen a release since almost five years.
Are those applications supporting its system tray Qt applications as well or GTK applications?

**Comment by pmattern** [comment]
Sorry.

**Comment by Vladimir-csp** [comment]
Well, since #102 is rejected and Adeskbar is even more dead than tint2, I have no other place than tint2 to go.

Tint2 has standard systray. Other applications in tray are mostly GTK with the exception of qasmixer and goldendict - both of them do not disappear.

**Comment by paulolieuthier** [comment]
qlipper is not related to LXQt, it's just a Qt app. I have no problems with Qt apps in lxqt-panel's system tray.

**Comment by Esclapion** [comment]
I use qlipper with lxqt in my Manjaro iso, but with lxqt-panel an so on, and no problem at all.

**Comment by palinek** [comment]
..but this issue is about `tint2`'s tray and `lxqt-powermanagement` (and `qlipper`) tray icon problems. IMHO it's related to the `tint2`'s tray implementation, but not 100% sure (there is *a little* probability we are using `QSystemTrayIcon` in some bad way or QT is faulty).

**Comment by ArthurBorsboom** [comment]
Xpad, a GTK3 sticky notes application, sometimes shows the tray icon correct, sometimes the tray icon is very small, sometimes the tray icon is blurred, sometimes the tray icon is missing.

Xpad uses the (deprecated) GtkStatusIcon.

Maybe it is related?

**Comment by Vladimir-csp** [comment]
I do not have any tray issues with qlipper and lxqt-powermanagement for some time now (Debian testing). Might be LXQt, or Qt, or tint2 updates. Closing this.
