### ISSUE TITLE
lxshortcut: add search/filter option for icon dialog

### ISSUE THREAD

**Issue by goetzc** [lxde/lxqt#644]
Right now it is not possible to search for any icon name. Some way to search or filter a name would be handy.

P.D. Not sure if this is the right place for libfm bugs or features requests.

**Comment by jleclanche** [comment]
> Not sure if this is the right place for libfm bugs or features requests.

It's not, but it's fine.

**Comment by jleclanche** [comment]
ping @LStranger

**Comment by LStranger** [comment]
Added a ticket to the current official feature requests tracker:

https://sourceforge.net/p/pcmanfm/feature-requests/388/

**Comment by jleclanche** [comment]
closing as upstreamed
