### ISSUE TITLE
why not create a qt window manager, instead of openbox?

### ISSUE THREAD

**Issue by alfredobonino** [lxde/lxqt#645]
Openbox Themes are very ugly.
Why not create a qt wm, or fork a qt wm?

**Comment by jleclanche** [comment]
We don't have the manpower and it's not necessary - use kwin if you want a qt window manager, we'll fully switch to it once wayland is here.

**Comment by alfredobonino** [comment]
Ok, kwin is perfect!

**Comment by Esclapion** [comment]
For the moment,  kwin is 52 MB to download, 240 MB installed, and brings a
lot of KDE things...

Would it be more Kde-independent in the future ?

One of lxqt highlights is its lightness.

2015-05-16 12:38 GMT+02:00 Alfredo Bonino <notifications@github.com>:

**Comment by Esclapion** [comment]
Forget my message, i took the bad, sorry.

2015-05-16 14:48 GMT+02:00 Patrice Esclapion <esclapion@gmail.com>:

**Comment by alfredobonino** [comment]
kwin, is perfect, but are very big, with lot of dependency with qt5 and kf5 there is any problem, in theory.
Openbox are light but very ugly, in most of themes.
LXQt is a light desktop environment, with openbox, but in the future?
Openbox have support for Wayland?
Openbox have support for Mir?
The development of Openbox are dead.
This is a problem for me.

**Comment by alfredobonino** [comment]
in ubuntu kwin is 14,2 mb download and 90mb installed.
But is kwin 5.

**Comment by Vladimir-csp** [comment]
openbox with its libraries: 1261KB installed. Not dead, but feature complete.
Themes can be made. The only problem is Wayland support.

**Comment by alfredobonino** [comment]
kwin or xfwm themes are more beautiful, and xfwm are very light.
The very problem of openbox are wayland support, who develop openbox for wayland?
this is a very big problem.
LXQT are  a lightweight desktop environment, and if openbox not support wayland, what are the window manager of lxqt?
Kwin? Are very big and not for old computers.
Xfwm? are a gtk wm.
....

**Comment by paulolieuthier** [comment]
```shell
$ pacaur -Qii kwin | grep Size 
Installed Size :  18.46 MiB

$ pacaur -Qii kwin | grep Depends
Depends On     : qt5-multimedia  plasma-framework  knewstuff  xcb-util-cursor  kinit  hicolor-icon-theme  kwayland  libinput  kdecoration
```
Not that big. But I get it. We'll have to wait for the window managers to get ported. We're certainly not going to develop one.

**Comment by Esclapion** [comment]
I do my tries in VBox, and it's slow. It needs also a lot more Ram
resources, 80 to 100 MB more.

2015-05-16 20:40 GMT+02:00 Paulo Lieuthier <notifications@github.com>:

**Comment by alfredobonino** [comment]
Kwin ram consumption are 80mb?
This is not light.
Mah.... i have a secondary pc with 512mb ram.... with kwin, 1/2 of the ram are occupated.
And @jleclanche, il lxqt switch to kwin, lxqt be a non-light desktop environment?

**Comment by paulolieuthier** [comment]
LXQt is intended to be window manager agnostic. When Wayland comes, every window manager complient with the specs should work.

**Comment by paulolieuthier** [comment]
@Esclapion you are probably using KWin from KDE4. Is that right? The KWin version we are talking here is 5+. I'm using 5.3 now, and 5.4 is the one that will support Wayland.

**Comment by alfredobonino** [comment]
Kwin 5 reduce the kde dependencies, is right?

**Comment by paulolieuthier** [comment]
Yes.

**Comment by Esclapion** [comment]
The k-dependencies are only for me on plasma-framework
 knewstuff  kinit kwayland kdecoration.

and dependencies of dependencies, but it's no big.

2015-05-16 22:27 GMT+02:00 Paulo Lieuthier <notifications@github.com>:

**Comment by alfredobonino** [comment]
However, when I have completed qsudo, I try eggwm, a window manager in qt4.

**Comment by pvanek** [comment]
eggwm is really incomplete. But of course, try it - maybe it will suit your needs.

**Comment by alfredobonino** [comment]
yes, eggwm, are incomplete, but there is a fork, with support for qt5, however, i use openbox for my pc.

**Comment by agaida** [comment]
switched to xfwm4 (4.12) lately - nearly the same footprint as with openbox and compton - snappy, no need for compton anymore, snap-to-corner and so on - really nice

**Comment by Esclapion** [comment]
With xfwm4, you have now a xfce. xfwm4 brings libxfce4ui, who depends of gtk2, gtk3, etc... :-(

**Comment by paulolieuthier** [comment]
Actually, gtk2 and gtk3 are no problem, they are small and almost impossible to get rid of (firefox, thunderbird, nm-applet, gvim, libreoffice). The problem is libwnck, libxfce4ui, libxfce4util and xfconf. But I might try it even so. I don't find Openbox good enough and I'm having issues with KWin lately.

**Comment by alfredobonino** [comment]
Xfwm, is a good window manager, with awesome themes and are very light, but are GTK.

**Comment by Esclapion** [comment]
I suppressed gtk3 in my last ISO, not really difficult. Only gnome-keyring is missing. And yeah, for gtk2, it's not possible. I can by cons reduce the amount of applications depending of gtk2.

xfwm4 is a good wm, but imho must be done gtk3 independent, or we will have also the problems related to it.

**Comment by paulolieuthier** [comment]
@Esclapion gnome-keyring is needed for network-manager-applet passwords storing, right?

**Comment by Esclapion** [comment]
Yes, it uses  libsecret who has gnome-keyring as -optional- dependence. Not really necessary, i think.

I use connman and lxq-connman-applet, so no prob with that. But some people can't connect to their wifi with connman, nothing very characterized. nm is slower, and wicd a lot more.

**Comment by alfredobonino** [comment]
Pekwm?

**Comment by lebarondemerde** [comment]
There is [Sway](http://swaywm.org). What is intended to bring [i3wm](http://i3wm.org) to wayland.

**Comment by tsujan** [comment]
In most comments about WM and compositing, a lack of interest in quality can be felt. Although Openbox+Compton can be made very elegant, recently, I had an interesting observation that may be worth sharing.

I wanted translucent titlebars because my widget style was translucent. KWin's default decoration was opaque and Aurorae seemed too heavy. I had 12 GiB of RAM but decided to try OpenBox+Compton. After enabling Compton's blurring and changing some of its settings, everything looked superb. However, after a few minutes, the speed of the laptop cpu fan sounded unusually high. So, I did an experiment by replacing OpenBox+Compton with KWin+Auroae and enabling KWin's blur effect. As a result, the fan speed became normal again.

I'd read somewhere that KWin is optimized regarding compositing. That observation was a proof to me.

So, IMO, although KWin may be "heavy", it's a good choice when high quality compositing is needed. Being lightweight doesn't mean having a poor look. Actually, LXQt is among the most elegant desktops I've had.

Last but not least, creating a high quality Qt WM like KWin is not only a difficult task but requires years of testing and bug fixing before reaching a stable state.

**Comment by hd-scania** [comment]
Openbox is FATALLY ugly, KWin is bloat, XfWM is Gtk+, but our last resort will be mostly merging Budgie into us, which Solus has been experimenting with LXQt for its Budgie desktops, with dissatisfying against Gtk+ like how LXQt has been founded, but also Material wm from Liri desktops (QtQuick and Wayland powered) should be also recommended to LXQt.

**Comment by MggMuggins** [comment]
Budgie is being rewritten with Qt and Kwin...

**Comment by tsujan** [comment]
> Budgie is being rewritten with Qt 

A [link](https://budgie-desktop.org/2017/01/25/kicking-off-budgie-11/). But, alas, apparently they reversed a wise decision:

"~~We will not be using QML. The desktop core should not be using JS, C++ only.~~"

QML is the worst thing about Qt.

**Comment by MggMuggins** [comment]
I hadn't seen that. It makes me sad, that everyone is going to something like QML, with a much larger runtime overhead than there could be.

What I'd really like to see is a ML for creating GUIs that is compiled to something native at compile time, that way you end up with a clean codebase, and fast runtime.

**Comment by tsujan** [comment]
> with a much larger runtime overhead than there could be

Correct! And with an elementary, rectangular, Win98 look but with some colors. KDE devs should have replaced Oxygen with Breeze for that. This is about GUI and UX, after all -- a regression, IMO.

**Comment by MggMuggins** [comment]
While we're on the topic of WM's, (and moving into Wayland), what about Mir? I haven't played around with it at all, but it's still being developed (even after Canonical dropped Unity 8, and they are working hard on getting it to be a complete Wayland compositor, basically getting rid of the Mir architecture. I don't know about performance (and I realize it's also being used on mobile), but I think it would be a viable option for a rather easy way out of the Kwin v. Openbox argument (Although I assume this will now become the Kwin v. Openbox v. Mir...).

**Comment by agaida** [comment]
@MggMuggins - feel free to try it, but don't expect any line of code from us.
