### ISSUE TITLE
Compilation if lxqt-config fails

### ISSUE THREAD

**Issue by Ilya87** [lxde/lxqt#646]
My OS Arch Linux x86_64, lxqt-config commit code 454e5b4260be0a6e15b2e10a0ed4a62c6b544237.

[ 99%] Building CXX object lxqt-config-appearance/CMakeFiles/lxqt-config-appearance.dir/fontsconfig.cpp.o                                                                   
Linking CXX executable lxqt-config-input                                              
lxqt/lxqt-config-git/src/lxqt-config/lxqt-config-appearance/iconthemeinfo.cpp:134:9: error: 
      unknown type name 'QThemeIconInfo'
        QThemeIconInfo info = QIconLoader::instance()->loadIcon(i);
        ^
[ 99%] Built target lxqt-config-input                                                 
[ 99%] Building CXX object lxqt-config-appearance/CMakeFiles/lxqt-config-appearance.dir/styleconfig.cpp.o                                                                   
1 error generated.

**Comment by pmattern** [comment]
The very same commit is building flawlessly on the same platform here.
Could you provide any details about the way you're trying to build, e. g. if you're using an AUR package or building manually, which commands you're invoking and so on?

**Comment by alfredobonino** [comment]
Have you installed all of the qt developer package required for lxqt?

**Comment by Ilya87** [comment]
My libqtxdg and liblxqt libraries were a little bit outdated. Problem is fixed now.
