### ISSUE TITLE
LXQt-panel compile error

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#647]
Latest git version does not compile on my system:
..
[ 99%] Building CXX object panel/CMakeFiles/lxqt-panel.dir/config/configpaneldialog.cpp.o                                                                     
/home/stef/lxqt-panel/panel/config/configpaneldialog.cpp: In member function ‘void ConfigPanelDialog::showConfigPanelPage()’:
/home/stef/lxqt-panel/panel/config/configpaneldialog.cpp:52:24: error: ‘showPage’ was not declared in this scope
     showPage(mPanelPage);
                        ^
/home/stef/lxqt-panel/panel/config/configpaneldialog.cpp: In member function ‘void ConfigPanelDialog::showConfigPluginsPage()’:
/home/stef/lxqt-panel/panel/config/configpaneldialog.cpp:57:26: error: ‘showPage’ was not declared in this scope
     showPage(mPluginsPage);
                          ^
panel/CMakeFiles/lxqt-panel.dir/build.make:486: set di istruzioni per l'obiettivo "panel/CMakeFiles/lxqt-panel.dir/config/configpaneldialog.cpp.o" non riuscito
make[2]: *** [panel/CMakeFiles/lxqt-panel.dir/config/configpaneldialog.cpp.o] Errore 1
CMakeFiles/Makefile2:1726: set di istruzioni per l'obiettivo "panel/CMakeFiles/lxqt-panel.dir/all" non riuscito
make[1]: *** [panel/CMakeFiles/lxqt-panel.dir/all] Errore 2
Makefile:136: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2

**Comment by palinek** [comment]
The `LxQt::ConfigDialog::showPage()` method was added recently into liblxqt in lxde/liblxqt@98dd883346074dbea680bf5796942236f191ccf8.
So you need to update your liblxqt.

**Comment by stefonarch** [comment]
But I did so, was running  my script to update all my AUR git packages which first
updates liblxqt. 
For some reason compiling fails even sooner now, at 29%
[ 29%] Building CXX object plugin-mainmenu/CMakeFiles/mainmenu.dir/lxqtmainmenu.cpp.o
In file included from /home/stef/lxqt-panel-git/src/lxqt-panel/plugin-mainmenu/lxqtmainmenu.cpp:31:0:
/home/stef/lxqt-panel-git/src/lxqt-panel/plugin-mainmenu/../panel/lxqtpanel.h:38:32: fatal error: LXQt/AddPluginDialog: File o directory non esistente
 #include <LXQt/AddPluginDialog>
 does not exist.

There has to be another issue somewhere, I had  also updated liblxqt. Old panel won't start anymore now.

**Comment by pmattern** [comment]
The problem is caused by lxde/liblxqt@af98dfe.
The last message before compiling stops is
```
fatal error: LXQt/AddPluginDialog: No such file or directory
compilation terminated.
```
Compiling lxqt-panel works flawlessly when the preceding commit lxde/liblxqt@a2d6337 is installed.
According to the comment in af98dfe lxqt-panel doesn't seem to find the said "own version".

@stef
IIRC and as your nickname suggests you're on Arch Linux. So as a workaround you may want to unpack AUR archive liblxqt-git.tar.gz, change line 'source' in PKGBUILD like this
`source=("git+https://github.com/lxde/$_pkgname.git#commit=a2d6337")`
run `makepkg -s` in that directory and install the package you get by `pacman -U \<patch to package\>'.

**Comment by paulolieuthier** [comment]
The error didn't happen to me because `LXQt/AddPluginDialog` was still installed in my system. I'll fix this.

**Comment by paulolieuthier** [comment]
@stefonarch please, test it again.

**Comment by stefonarch** [comment]
Thanks it worked, in fact now I  have my panel back again :)
Very nice and clean new work with the add-plugin dialog windows!

Il 22/05/2015 13:18, Peter Mattern ha scritto:
> @stef <https://github.com/stef>
> IIRC and as your nickname suggests you're on Arch Linux. So as a
> workaround you may want to unpack AUR archive liblxqt-git.tar.gz, change
> line 'source' in PKGBUILD like this
> |source=("git+https://github.com/lxde/$_pkgname.git#commit=a2d6337")|
> run |makepkg -s| in that directory and install the package you get by
> `pacman -U <patch to package>'.

**Comment by stefonarch** [comment]
@paulolieuthier Tested the normal way, everything ok now, thanks!

**Comment by paulolieuthier** [comment]
Nice :smile:

**Comment by stefonarch** [comment]
A strange thing happend again: when I build the AUR panel package there are only two icons in add-widget dialog, when I use directly 
git clone 
 mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug .. && make && sudo make install 
all the icons are present. 
Tested with several different icon sets, all the same. 
With oxygen I have the green dummy icons everywhere exept spacer and directorymenu.

**Comment by pmattern** [comment]
Hm, can't confirm your findings here, see screenshot
![lxqt_lxqt-panel_dialog-configure-panel-vs-icons](https://cloud.githubusercontent.com/assets/9860801/7777498/d2b81ad2-00c3-11e5-9416-ce6c8d6a3561.png)
lxqt-panel installed via AUR package lxqt-panel-git and using theme Oxygen.
Maybe an outdated version of AUR package (lxqt-panel-git.tar.gz)? Some outdated LXQt components on your system or some components that were compiled against something outdated?

**Comment by stefonarch** [comment]
No idea why this happens, refreshed Aur pkgbuilds too even today.
Should try everthing on a clean system, with all the --force options and
/home/user years old I have no idea if it's a general issue, fact it
when I compile using directly git the icons are ok.

Il 22/05/2015 20:49, Peter Mattern ha scritto:

**Comment by pmattern** [comment]
You may also try in a fresh user profile first (less work than setting up a system as a whole).
