### ISSUE TITLE
lxqt-common hard-codes /etc/xdg/autostart

### ISSUE THREAD

**Issue by krytarowski** [lxde/lxqt#651]
In the ``autostart/CMakeLists.txt`` there is hard-coded path to ``xdg/autostart``.
```
install(FILES ${DESKTOP_FILES} DESTINATION /etc/xdg/autostart)
```

This is fatal for pkgsrc and needs patching for the proper prefix: ``$PREFIX/etc/xdg``

KDE as far as I know uses ``${SYSCONF_DIR_INSTALL}`` for ``/etc``.

**Comment by krytarowski** [comment]
This also involves missing  set of ``XDG_CONFIG_DIRS`` in startlxqt.in

**Comment by krytarowski** [comment]
For pkgsrc I went for this addition in ``startlxqt.in``:

```
if [ -z "$XDG_CONFIG_DIRS" ]; then
       export XDG_CONFIG_DIRS="$XDG_CONFIG_HOME:@CMAKE_INSTALL_PREFIX@/etc/xdg/"
fi
```

It can be generalized (the ``CMAKE_INSTALL_PREFIX`` part) for all platforms.

**Comment by paulolieuthier** [comment]
@krytarowski what does `qmake-qt5 -query QT_INSTALL_CONFIGURATION` outputs for you on your BSD?

**Comment by luis-pereira** [comment]
@krytarowski You can set ```LXQT_ETC_XDG_DIR``` in liblxqt.
Changing the install line to:
```install(FILES ${DESKTOP_FILES} DESTINATION "${LXQT_ETC_XDG_DIR}/autostart")```
solves the install issue. I will place an PR with that.

**Comment by paulolieuthier** [comment]
@luis-pereira I realized that yesterday, but didn't have the time. I just assigned it to you, it's good to see you back.

**Comment by luis-pereira** [comment]
@krytarowski The install issue is fixed by https://github.com/lxde/lxqt-common/commit/ee3e66d75b82dc069992c28bfe0bcc0de6e0be37 For the XDG_CONFIG_DIRS I can apply the same recipe.

@paulolieuthier It's good to be back :smile:

**Comment by krytarowski** [comment]
Sorry for delays. There is a bug in qt4 and qt5 in pkgsrc, their ``qmake -query QT_INSTALL_CONFIGURATION`` points to wrong location. Thread on the issue: https://mail-index.netbsd.org/tech-pkg/2015/05/25/msg014899.html

It should point to ``${PKG_SYSCONFDIR}/xdg`` and it's by default ``/usr/pkg/etc/xdg`` for privileged user (with ``root`` permissions) an ``$HOME/pkg/etc/xdg`` for unprivileged. These path are configurable, depending how and where is pkgsrc installed.

Your fix proposition looks correct.

**Comment by paulolieuthier** [comment]
The fix proposition uses `QT_INSTALL_CONFIGURATION`.

**Comment by krytarowski** [comment]
And this proposition looks correct.

``install(FILES ${DESKTOP_FILES} DESTINATION "${LXQT_ETC_XDG_DIR}/autostart")``

**Comment by krytarowski** [comment]
Regarding ``startlxqt.in``, does it look ok?

```
if [ -z "$XDG_CONFIG_DIRS" ]; then
       export XDG_CONFIG_DIRS="$XDG_CONFIG_HOME:@LXQT_ETC_XDG_DIR@"
fi
```

**Comment by paulolieuthier** [comment]
@krytarowski [this](https://github.com/lxde/liblxqt/blob/master/cmake/FindInstallConfigPath.cmake#L15) is what I'm talking about.

**Comment by krytarowski** [comment]
Yes, I know.

**Comment by krytarowski** [comment]
With whatever option you will go for it, I will follow you in downstream. Personally I like the `qmake`` option.

Just wondering whether we need it also in ``lxqt-globalkeys/cmake/FindInstallConfigPath.cmake``? Isn't it enough to limit this to ``lxqt-common``?

**Comment by luis-pereira** [comment]
@krytarowski It's fine to add ```LXQT_ETC_XDG_DIR``` to ```XDG_CONFIG_DIRS```.  Why  adding ```XDG_CONFIG_HOME``` to ```XDG_CONFIG_DIRS``` is needed ?

The ```lxqt-globalkeys/cmake/FindInstallConfigPath.cmake``` is an artifact and will be removed.

**Comment by krytarowski** [comment]
We just fixed our local qt[45]: ``qmake -query QT_INSTALL_CONFIGURATION`` https://mail-index.netbsd.org/pkgsrc-changes/2015/05/27/msg124962.html

I was unsure about the ``XDG_CONFIG_HOME`` entry, just ``LXQT_ETC_XDG_DIR`` is essential.

**Comment by luis-pereira** [comment]
Fixed by:
https://github.com/lxde/lxqt-common/commit/ee3e66d75b82dc069992c28bfe0bcc0de6e0be37
https://github.com/lxde/lxqt-common/commit/3b56bf2acb595a8a6776a00858cb9bf9069fab90

**Comment by krytarowski** [comment]
Thank you!
