### ISSUE TITLE
lxqt-panel build fail without world clock plugin

### ISSUE THREAD

**Issue by lefta** [lxde/lxqt#654]
lxqt-panel fails to build if -DWORLD_CLOCK_PLUGIN=OFF have been passed as CMake argument.
Here is the error:

/usr/bin/clang++   -O2 -pipe -fomit-frame-pointer -march=native  -fPIE -fPIE   -Wl,-O1 -Wl,--as-needed CMakeFiles/lxqt-panel.dir/main.cpp.o CMakeFiles/lxqt-panel.dir/lxqtpanel.cpp.o CMakeFiles/lxqt-panel.dir/lxqtpanelapplication.cpp.o CMakeFiles/lxqt-panel.dir/lxqtpanellayout.cpp.o CMakeFiles/lxqt-panel.dir/lxqtpanelpluginconfigdialog.cpp.o CMakeFiles/lxqt-panel.dir/config/configpaneldialog.cpp.o CMakeFiles/lxqt-panel.dir/plugin.cpp.o CMakeFiles/lxqt-panel.dir/popupmenu.cpp.o CMakeFiles/lxqt-panel.dir/pluginmoveprocessor.cpp.o CMakeFiles/lxqt-panel.dir/moc_lxqtpanel.cpp.o CMakeFiles/lxqt-panel.dir/moc_lxqtpanelapplication.cpp.o CMakeFiles/lxqt-panel.dir/moc_lxqtpanellayout.cpp.o CMakeFiles/lxqt-panel.dir/moc_lxqtpanelpluginconfigdialog.cpp.o CMakeFiles/lxqt-panel.dir/config/moc_configpaneldialog.cpp.o CMakeFiles/lxqt-panel.dir/moc_plugin.cpp.o CMakeFiles/lxqt-panel.dir/moc_pluginmoveprocessor.cpp.o CMakeFiles/lxqt-panel.dir/LXQtAppTranslationLoader.cpp.o  -o lxqt-panel -rdynamic -lQt5Xdg ../plugin-clock/libclock.a ../plugin-desktopswitch/libdesktopswitch.a ../plugin-mainmenu/libmainmenu.a ../plugin-quicklaunch/libquicklaunch.a ../plugin-showdesktop/libshowdesktop.a ../plugin-taskbar/libtaskbar.a ../plugin-tray/libtray.a -llxqt-globalkeys-ui -lmenu-cache -lglib-2.0 -llxqt-globalkeys /usr/lib64/liblxqt.so.0.9.0 -lQt5Xdg /usr/lib64/libQt5Xml.so.5.4.1 /usr/lib64/libQt5DBus.so.5.4.1 /usr/lib64/libKF5WindowSystem.so.5.10.0 /usr/lib64/libQt5Widgets.so.5.4.1 /usr/lib64/libQt5X11Extras.so.5.4.1 /usr/lib64/libQt5Gui.so.5.4.1 /usr/lib64/libQt5Core.so.5.4.1 -lSM -lICE -lX11 -lXext -lXcomposite -lXdamage -lXfixes -lXrender -lX11 -lxcb-damage -lxcb-xfixes -lxcb-render -lxcb-shape -lxcb 
CMakeFiles/lxqt-panel.dir/plugin.cpp.o: In function `Plugin::findStaticPlugin(QString const&)':
/var/tmp/portage/lxqt-base/lxqt-panel-9999/work/lxqt-panel-9999/panel/plugin.cpp:(.text+0x1e71): undefined reference to `vtable for LxQtWorldClockLibrary'
x86_64-pc-linux-gnu-clang-3.6.0: error: linker command failed with exit code 1 (use -v to see invocation)
panel/CMakeFiles/lxqt-panel.dir/build.make:754: recipe for target 'panel/lxqt-panel' failed

With world clock plugin enabled, it builds fine.

**Comment by palinek** [comment]
The correct spelling is WORLDCLOCK_PLUGIN. Didn't you catch the cmake warning?:
```
-- *********************************************************************
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    WORLD_CLOCK_PLUGIN

```

**Comment by lefta** [comment]
Hem, sorry for the spelling, I didn't copy-paste it. I used the right spelling in my config, this is just a typo in the bug report, sorry for that...

**Comment by palinek** [comment]
What version/commit are you trying to compile?
Just tried a clean build on current master and everything went fine.

**Comment by lefta** [comment]
Latest as of bug report. I built it with my package manager (gentoo portage) which always pull before building. I will try outside of portage later, tomorrow I think, to be sure it doesn't interfere. I will provide full configuration line to reproduce the problem BTW.

**Comment by lefta** [comment]
Hem, I'm really sorry, but I just figured out that my build system clones from old git.lxde.org repositories. I hope you did not loose too much time with my mistake.
Sorry again... :(
