### ISSUE TITLE
Ubuntu 15.04 fail to launch lxqt-panel

### ISSUE THREAD

**Issue by HaoHeng** [lxde/lxqt#663]
we build LXQt from source. After building successfully, we attempt to launch the panel
```
$ lxqt-panel  
lxqt-panel: error while loading shared libraries: liblxqt-globalkeys-ui.so.0: cannot open shared object file: No such file or directory
```
solution:
```
$cp /usr/lib64/liblxqt-globalkeys-ui.so.0 /usr/lib/
$cp /usr/lib64/liblxqt-globalkeys.so.0 /usr/lib/
```
then the lxqt-panel is able to launch.

**Comment by palinek** [comment]
IMO this is definetly a distribution specific issue...

Could you provide the `ldd` output of official `lxqt-panel` and `lxqt-panel` built by yourself?

**Comment by pmattern** [comment]
Also, could you please provide the exact commands you used to build both lxqt-panel and lxqt-globalkeys?

@palinek
I think you misunderstood. They're using Ubuntu but so far LXQt built from source *only*.

**Comment by palinek** [comment]
@pmattern As I understood it. They built only `lxqt-panel` from source...everything else from official (or PPA) packages.

**Comment by pmattern** [comment]
@palinek 
Hm. "we build *LXQt* from source." Maybe they will read our conversation and enlighten us.

**Comment by limitimil** [comment]
Hi, I am one of the team members. Sorry for too few information.

We refer to the steps given by http://wiki.lxde.org/en/Build_LXDE-Qt_From_Source .
and we prepared a brand new virtual machine Ubuntu 15.04 64bit for it.

Below is how we build the LXQT

1. download Qt5 here 
http://www.qt.io/download-open-source/

2. setup Qt5 with
$cd Download/
$chmod 744 qt-unified-linux-x64-2.0.0-online.run
$./qt-unified-linux-x64-2.0.0-online.run

3. prepare the external dependencies which are  mentioned here
http://wiki.lxde.org/en/Build_LXDE-Qt_From_Source#List_of_external_dependencies

$sudo apt-get -y install cmake \
&& sudo apt-get -y install automake \
&& sudo apt-get -y install libkf5windowsystem-dev \
&& sudo apt-get -y install libudev-dev \
&& sudo apt-get -y install xcursor.dev \
&& sudo apt-get -y install glib-2.0 \
&& sudo apt-get -y install liboobs-1-dev \
&& sudo apt-get -y install libkf5guiaddons-dev \
&& sudo apt-get -y install libkf5solid-dev \
&& sudo apt-get -y install libpulse-dev \
&& sudo apt-get -y install libmenu-cache-dev \
&& sudo apt-get -y install libsensors4-dev \
&& sudo apt-get -y install libxcb-util0-dev \
&& sudo apt-get -y install libxcb-damage0-dev \
&& sudo apt-get -y install libxcomposite-dev \
&& sudo apt-get -y install libasound2-dev \
&& sudo apt-get -y install libdbusmenu-qt5-dev \
&& sudo apt-get -y install libpolkit-qt5-1-dev \
&& sudo apt-get -y install libpolkit-agent-1-dev \
&& sudo apt-get -y install libxcb-screensaver0-dev \
&& sudo apt-get -y install libxcb-dpms0-dev \
&& sudo apt-get -y install libfm-dev \
&& sudo apt-get -y install libexif-dev \
&& sudo apt-get -y install libconfig-dev \
&& sudo apt-get -y install libqt4-dev \
&& sudo apt-get -y install openbox-dev \
&& sudo apt-get -y install qtbase5-private-dev \
&& sudo apt-get -y install libqt5x11extras5-dev \
&& sudo apt-get -y install qttools5-dev \
&& sudo apt-get -y install libqt5svg5-dev \
&& sudo apt-get -y install qtscript5-dev \
&& sudo apt-get -y install qttools5-dev\

4. clone the source from github

$git clone https://github.com/lxde/lxqt
$cd lxqt
$git submodule init
$git submodule update
$git submodule foreach git checkout master
$git submodule foreach git pull --rebase

5. export enviroment variable and start install

$echo "export CMAKE_PREFIX_PATH=/home/ksyang/Qt/5.4/gcc_64" >> .bashrc \
&& echo "export USE_QT5=ON" >> .bashrc 

$LXQT_PREFIX=/usr LIB_SUFFIX=64 ./build_all.sh

6. start LXQT and choose openbox for window manager

At first scene, we can only see the desktop background and the icons of the files in Desktop. 
We found the panel is missing so we give this command
$lxqt-panel 
that's how we get the error message which we mentioned above.

Thanks.

**Comment by paulolieuthier** [comment]
@limitimil looks like you are adding the `export` commands to your `.bashrc` but not actually executing them. Then, libqtxdg is not linked to Qt5, but Qt4, and the other components fail. OR something close to that. Can you please confirm this?

**Comment by palinek** [comment]
> cp /usr/lib64/liblxqt-globalkeys-ui.so.0 /usr/lib/

It seems that library is installed here because you used the LIB_SUFFIX=64, but it seems that ld.so(1) on your system doesn't search /usr/lib64 and also you don't have this directory in LD_LIBRARY_PATH.

Why do you want to have the libraries in /usr/lib64 (AFAIK this library is deprecated)?

**Comment by palinek** [comment]
> @limitimil looks like you are adding the export commands to your .bashrc but not actually executing them. Then, libqtxdg is not linked to Qt5, but Qt4, and the other components fail. OR something close to that. Can you please confirm this?

@paulolieuthier IMO they've sorted out the building process...they have a problem in run-time

**Comment by harry830622** [comment]
@palinek Yes, we have finished building process. We add the LIB_SUFFIX=64 because our Ubuntu is 64bit version. Now it seems no meaning lol. Thanks for the help!!!

**Comment by palinek** [comment]
> Now it seems no meaning lol. Thanks for the help!!!

Should we close this issue?

**Comment by harry830622** [comment]
Yes, thank you!!!
