### ISSUE TITLE
lxqt-sudo should be less verbose

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#666]
it's a general bug/annoyance with our binaries - they are to verbose. 
<pre>
$ lxqt-sudo ls
iconTheme "oxygen"
iconTheme "oxygen"
iconTheme "oxygen"
iconTheme "oxygen"
Theme: Cannot open file for reading: "/usr/share/lxqt/themes/ambiance/lxqt-sudo.qss"
checkout  lxqt-sudo_0.1.0-3.dsc           lxqt-sudo_0.1.0-3_source.changes       lxqt-sudo_0.1.0-3.tar.gz
</pre>

**Comment by palinek** [comment]
All of these are flushed from liblxqt....
@jleclanche, @paulolieuthier, @luis-pereira should we get rid of those messages from liblxqt?

**Comment by jleclanche** [comment]
Yes, I've been meaning to get rid of most of them.

**Comment by jleclanche** [comment]
@palinek Go ahead.

**Comment by palinek** [comment]
Removed in lxde/lxqt-qtplugin@e3e3044 and lxde/liblxqt@b16807a (need to build the liblxqt library as release type)

**Comment by paulolieuthier** [comment]
Nice work.
