### ISSUE TITLE
add wiki link to website

### ISSUE THREAD

**Issue by jubalh** [lxde/lxqt#670]
I think it would be good to add a link to the [github wiki](https://github.com/lxde/lxqt/wiki) to the [website](http://lxqt.org/).
And because of [this post](http://wiki.lxde.org/en/Build_LXDE-Qt_From_Source) I assumed we would use the LXDE wiki. I think it would be much clearer, and since some users are just users and dont know github it might be easier for them to find the link just on the official website.

**Comment by paulolieuthier** [comment]
Actually, we should move that article to Github's wiki, to avoid misunderstanding and improve information consistency.

**Comment by jubalh** [comment]
I already imported it yesterday,and added a link at the top of the article to point to the github wiki ;)

**Comment by jubalh** [comment]
@paulolieuthier  see https://github.com/lxde/lxqt/wiki/Building-From-Source and top of http://wiki.lxde.org/en/Build_LXQt_From_Source

**Comment by paulolieuthier** [comment]
Thanks, I was actually starting to rewrite it here!

**Comment by jubalh** [comment]
It still could use some polishing in regard of proper markdown, way to many dots for my taste.

Anyways, I think you guys should add a link to the wiki on the website :)

**Comment by jubalh** [comment]
thanks :)
