### ISSUE TITLE
lxqt-panel: show menu by cli option

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#672]
Please add a way to show menu via command line, analogous to ```lxpanelctl menu``` command.

**Comment by palinek** [comment]
What menu are you thinking about?

**Comment by Vladimir-csp** [comment]
Applications menu. Sorry for vagueness.

**Comment by palinek** [comment]
IMO not needed to implement such thing. Mainmenu plugin registers a shortcut for showing the menu, so you just need to simulate the keystroke. A quick google search found [xdotool](http://www.semicomplete.com/projects/xdotool/). This is working here:
```bash
 xdotool key alt+F1
```

**Comment by Vladimir-csp** [comment]
That would work if lxqt-globalkeys is running, cli option is kinda alternative to that.
If it is too much of a trouble, then never mind, close the issue.

**Comment by palinek** [comment]
The mainmenu is just a plugin so I don't think it's a good idea to hardcode a command line option into lxqt-panel. The mainmenu:
- may not even be present in any of the panels
- there may be more of them (even on multiple panels), menu of which should be shown (each plugin can show different menu based on configuration)?

**Comment by Vladimir-csp** [comment]
I agree. How was it addressed in lxpanel and lxpanelctl?

**Comment by palinek** [comment]
> How was it addressed in lxpanel and lxpanelctl?

I don't know.

**Comment by LStranger** [comment]
>I agree. How was it addressed in lxpanel and lxpanelctl?

Right now it sends a callback to a menu plugin if it present in any panel.
It's planned for future release to change it into more generic way though.

**Comment by PCMan** [comment]
An alternative might be to leverage the existing dbus stuff.
Just export a public dbus method on lxqt-panel application.
So it can be called with a simple "dbus-send" command line.

**Comment by ianorlin** [comment]
PCMan Looking at the man page for lxpanelctl and dbus-send I would think lxpanelctl is easier. Or did @PCMan mean something like how lxsession-defualt works that calls the dbus-stuff externally I don't think many end users understand dbus enough to use it directly from the command line.

**Comment by PCMan** [comment]
The dbus stuff can be wrapped in a short shell script, though.
I'm ok with both solution, be it an command line option or a dbus interface.
We'll need to use dbus anyways since supporting this still requires IPC.

**Comment by jleclanche** [comment]
There are a lot of concerns around this, it's doable with keyboard shortcuts and the use cases are minor, almost nonexistant.

Rejecting.

**Comment by QiangF** [comment]
Maybe use xdotools
https://bbs.archlinux.org/viewtopic.php?id=268826

**Comment by gfgit** [comment]
@Vladimir-csp have you seen #1861 ?

**Comment by Vladimir-csp** [comment]
Thanks ) I drifted away from this panel since then.

**Comment by gfgit** [comment]
> Thanks ) I drifted away from this panel since then.

Sorry to hear that
