### ISSUE TITLE
Move aboutdialog away from liblxqt into lxqt-about

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#678]
It's only used by lxqt-about anyway. It will reduce the exported symbol count thus speeding up liblxqt loading and dynamic linking.

**Comment by jleclanche** [comment]
+1

**Comment by luis-pereira** [comment]
Closed by:
* https://github.com/lxde/liblxqt/commit/5b69371f24d9e91885e8f9503b17f67bc2608eb7
* https://github.com/lxde/lxqt-about/commit/8bb8e45644d76d9d25c7d0f5a13e5f61230925b1

On my system liblxqt was reduced from 612K to 499K. An 113K saving (20%)/
