### ISSUE TITLE
Task manager: two problems moving buttons by drag & drop

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#681]
If a button gets moved within a Task manager instance by drag & drop other buttons that were traversed keep looking like highlighted.
E. g. in this screenshot
![lxqt_panel_task-manager_dand_highlighting](https://cloud.githubusercontent.com/assets/9860801/8035311/bd5e5e74-0def-11e5-949a-b21c42580dfa.png)
Firefox button was dragged from the outer left to its current position.
That highlighting can be  reverted by clicking or hovering only. Problem exists in all themes provided by lxqt-common but isn't that obvious in all due the colors chosen.

Sometimes buttons don't get placed where they were dropped.
E. g. in this screenshot
![lxqt_panel_task-manager_dand_position](https://cloud.githubusercontent.com/assets/9860801/8035315/c8af8492-0def-11e5-98f3-d5e7136ec875.png)
Firefox button "five" had been at the outer right and was dropped between "two" and "three".
The problem doesn't affect every drag&drop action. Conditions seem to be that the buttons are filling all the available space in Task manager.
The location where the button ends isn't necessarily adjacent to the one were it was dropped as shown in the screenshot but can be more distant, too. That distance seems to get greater the more buttons there are per Task manager instance.
The direction into which the button gets moved accidentally can be both the one corresponding to drag & drop and the opposite.
Problem has been getting better as of Qt 5.4.*2* but still persists.

Latest Git checkouts of all LXQt components compiled against Qt 5.4.2 on Arch Linux i686 or x86_64.

**Comment by Vladimir-csp** [comment]
I can confirm this.
If some kind of swapping reorder animation while drag is feasible, that would be the best solution, IMHO.

**Comment by pmattern** [comment]
Well, this could be done, of course.

But the actual problem seems to be the horizontal range that's considered to sort of belong to the boundary between two buttons: the misplacement can e. g. be seen if the (horizontal) middle of the dragged button is apparently placed right over the boundary of the two buttons it shall be placed between before dropping.

**Comment by paulolieuthier** [comment]
The first problem is very annoying, and I'm not sure how to fix it. It looks like qss's hover property is not updated when dragging out. The second problem is more important, but I can't reproduce, it always work well here.

**Comment by pmattern** [comment]
> The second problem is more important, but I can't reproduce [...]

Strange, it's getting on my nerves each and every day. You are aware that the buttons must fill all horizontal space available to plugin-taskbar? Also, you may want to open a number of windows such that the horizontal width of buttons gets automatically decreased which makes the problem reproducible 100% here.

**Comment by paulolieuthier** [comment]
No matter what I try, it always work well here.

**Comment by pmattern** [comment]
Just had another look a the second problem:
Cannot reproduce in a KVM/QEMU virtual machine featuring a single virtual graphics card with a single output only either. The machine where it's bothering me as stated above is featuring an on-board ATI Radeon card with one monitor connected to its DVI and VGA output respectively. But the problem also appears if only one monitor is in use and the other is switched off.
So could this eventually be caused by some multi-monitor issue?

**Comment by paulolieuthier** [comment]
I have one monitor only.

**Comment by palinek** [comment]
@pmattern Could you see if the lxde/lxqt-panel#252 fixes both issues stated here?
