### ISSUE TITLE
lxqt-config-file-associations: how to add a Mime type ?

### ISSUE THREAD

**Issue by Esclapion** [lxde/lxqt#683]
For example, I wish to add a file association between .pro and qtcreator. How to do it, and if it is manual (likely) how in practice?

**Comment by Vladimir-csp** [comment]
You need to add xml description of the type to ```mime/packages/``` in one of $XDG_DATA_DIRS
```
<?xml version='1.0' encoding='utf-8'?>
<mime-info xmlns='http://www.freedesktop.org/standards/shared-mime-info'>
<mime-type type='some/type'>
  <comment>Example filetype</comment>
  <comment xml:lang="en">this is not english</comment>
  <glob pattern="*.extension"/>
  <glob pattern="*.otherextension"/>
  <generic-icon name="icon-name"/>
</mime-type>
</mime-info>
```
Then:
- either have a .desktop file in ```applications/``` in one of $XDG_DATA_DIRS  that lists this type in ```MimeType=``` parameter,
- or list association in ```mimeapps.list``` file in $XDG_DATA_DIRS or $XDG_CONFIG_DIRS or $XDG_CONFIG_HOME.

Long answer:
- http://standards.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-0.18.html 
- http://standards.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.1.html

**Comment by Esclapion** [comment]
Thanks a lot. Closed.
