### ISSUE TITLE
lxqt-panel: taskbarbutton's right-click selection list is invalid in some cases

### ISSUE THREAD

**Issue by limitimil** [lxde/lxqt#684]
When the window of an application is Minimized, I cannot use Maximize and Restore functions,which are in the function list when I right click on the taskbutton, to show the application on the desktop.
However, the buttons act normally when the application windows are showing on the desktop.
![image](https://cloud.githubusercontent.com/assets/11483962/8065915/2a22cd1a-0f17-11e5-84a0-0b4ad2a75bbf.png)

Our team have traced lxqttaskbutton.cpp and done some adjustment to make it partly fixed. Keep working on it.

**Comment by limitimil** [comment]
It seems to work well after revising the file "lxqt/lxqt-panel/plugin-taskbar/lxqttaskbutton.cpp".

https://gist.github.com/limitimil/2b04b17545773f41ad74

**Comment by paulolieuthier** [comment]
@limitimil please, send us a [pull request](https://help.github.com/articles/creating-a-pull-request).
