### ISSUE TITLE
lxqt-runner improvement: toggle with keyboard shortcut

### ISSUE THREAD

**Issue by excalibur1234** [lxde/lxqt#685]
the keyboard shortcut of lxqt-runner OPENS the application, but does NOT CLOSES it.
please change it to toggle lxqt-runner.

when i search something with lxqt-runner and lxqt-runner cannot find it or i want to quickly switch my focus (because i have received an IRC message), i have to close lxqt-runner with my mouse cursor or with ALT + F4. 
i would like to be able to close lxqt-runner easily by pressing the keyboard shortcut again (when lxqt-runner is already open).

**Comment by pmattern** [comment]
And hitting `Esc` doesn't fit your needs? It's actually even simpler than hitting the shortcuts normally assigned again as those involve a combination of two keys.

**Comment by excalibur1234** [comment]
you are right.
hitting ESC works, too. this is already an improvement over ALT + F4.

i use one key (the meta/windows/... key) to open lxqt-runner. this key is even easier to reach with my hands on the keyboard than the ESC key.

to me, it just feels right to have a keyboard shortcut, which toggles lxqt-runner.

**Comment by paulolieuthier** [comment]
@excalibur1234 please, update it and test it.

**Comment by excalibur1234** [comment]
works beautifully.
thanks for this quick improvement!
