### ISSUE TITLE
[lxqt-panel] plugin-clock not working

### ISSUE THREAD

**Issue by AlfredoRamos** [lxde/lxqt#687]
Hi there,

I'm using the ```lxqt-panel-git``` package for Arch, today I upgraded this package to the latest commit and the plugin-clock stopped working, it only shows a blank space.

![lxqt-panel](https://cloud.githubusercontent.com/assets/4165935/8119079/873eb4f4-1058-11e5-9f3a-ee93d334f154.jpg)

I've tried deleting and re-adding the plugin, reinstalling other lxqt packages first, kill ```lxqt-panel``` and then start it again with no luck. It was working just fine until commit fb7d256

Running lxqt-panel through the terminal doesn't show any relevant info.

**Comment by palinek** [comment]
@AlfredoRamos can you, please, try if the problem persists also after lxde/lxqt-panel@fb7d256c234d2bbf6741645d64435b1b68fb9751

**Comment by palinek** [comment]
@AlfredoRamos can you share the panel configuration and any (optional) steps to reproduce?

**Comment by AlfredoRamos** [comment]
Sure, here is my panel.conf are some screenshots.

[panel.conf](https://pastebin.osuosl.org/27126/)
[Configure Panel](https://cloud.githubusercontent.com/assets/4165935/8124163/8cf5f6a2-109c-11e5-9ea0-2241bb362e51.jpg)
[Clock Settings](https://cloud.githubusercontent.com/assets/4165935/8124164/8cfebeae-109c-11e5-91cd-b3f9290084b2.jpg)

Actually I think the clock plugin is working but the font size is too small, I can see a little dot just after the volume control icon, it's either that or I need to see an ophthalmologist lol

**Comment by palinek** [comment]
... not seeing the issue here with the same configuration. What QT version are you running on?

**Comment by AlfredoRamos** [comment]
Qt 5.4.2

I will reinstall all the packages, meanwhile i'll use the world clock.

**Comment by palinek** [comment]
I'm on QT 5.3.2.

@paulolieuthier can you, please, check if you are able to reproduce the discussed behaviour?

**Comment by AlfredoRamos** [comment]
I was able to reproduce the issue.

I reinstalled all the lxqt-* packages first, then delete my ~/.config/lxqt folder and tried to configure the clock.

[Screencast](http://tinypic.com/player.php?v=2rrnz9y&s=8)

PS: Sorry for using tinypic, it's the only video hosting service that reproduces the video.

**Comment by palinek** [comment]
I've tried to set the minimum width for the widget.... @AlfredoRamos can you please check if lxde/lxqt-panel@eae99f58722b (new branch clock_width) fixes this?

**Comment by AlfredoRamos** [comment]
Yeah, the issue has been fixed. Thank you @palinek

**Comment by palinek** [comment]
@AlfredoRamos You're welcome, thanks for assistance
