### ISSUE TITLE
lximage-qt in the menu appears under "utility" not "graphics"

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#690]
No idea why "utility" get's chosen first. lximage-qt.desktop file reads:
Categories=Graphics;Utility;Core;Qt;Viewer;RasterGraphics;2DGraphics;Photography;

Fact is removing "utility" fixes the problem. I made also a test introducing "utility" in org.kde.gwenview.desktop which behaves the same way and moves to "utility" from "graphics".

Same goes eventually for lximage-qt-screenshot.desktop

**Comment by pmattern** [comment]
The problem is in /etc/xdg/menu/lxqt-applications.menu which excludes items from submenu 'Graphics' if they state 'Utility' in key 'Categories' as well
```
        <!-- Graphics -->
        <Menu>
                <Name>Graphics</Name>
                <Directory>lxde-graphics.directory</Directory>
                <Include>
                        <And>
                                <Category>Graphics</Category>
                                <Not><Category>Utility</Category></Not>
                        </And>
                </Include>
        </Menu> <!-- End Graphics -->
```
The behaviour was adopted from lxde-applications.menu where it was introduced on purpose in lxde/lxmenu-data@31cd1bd some years ago.

Personally I don't think it makes any sense either. That's why I sent a [message](http://sourceforge.net/p/lxde/mailman/message/33260803/) to the mailing list some months ago but I wasn't fortunate enough to get an answer.

@PCMan 
Any chance you could tell us the purpose of the said commit and what you think about that whole thing by now?

**Comment by agaida** [comment]
i would bet, that the last matching main category wins - in that case
this is utility instead of graphics. So removing the xdg main category
'utility' should be perfectly fine.

http://standards.freedesktop.org/menu-spec/latest/apa.html#main-category-registry

**Comment by paulolieuthier** [comment]
@PCMan ping.

**Comment by pmattern** [comment]
Just had another look: if key 'Categories' in some *.desktop file states several values all of which are corresponding to a sub-menu of a panel main menu as defined by a *.menu the handling seems to vary. Xfce panel lists the *.desktop in all those sub-menus while the main menus of both LXDE and LXQt indeed seem to prioritize according to the list stated by agaida.

Obviously removing 'Utility' from key 'Categories' in lximage-qt[-screenshot].desktop would do the trick.

Nevertheless I still don't understand the benefit of that line `<Not><Category>Utility</Category></Not>`. If it's meant to avoid duplicate entries in sub-menus "Graphics" and "Accessories" I'd rather go the other way around and state `<Not><Category>Graphics</Category></Not>` in the stanza of sub-menu "Accessories".

**Comment by LStranger** [comment]
>Nevertheless I still don't understand the benefit of that line `<Not><Category>Utility</Category></Not>`. If it's meant to avoid duplicate entries in sub-menus "Graphics" and "Accessories" I'd rather go the other way around and state `<Not><Category>Graphics</Category></Not>` in the stanza of sub-menu "Accessories".

That sounds reasonable and I'd apply that to the lxmenu-data unless PCMan
objects on that.
