### ISSUE TITLE
Desktop always crash after (sddm) login

### ISSUE THREAD

**Issue by MttCastelli** [lxde/lxqt#691]
![2015-06-14-140531_1280x1024_scrot](https://cloud.githubusercontent.com/assets/11462157/8148455/133cbb34-129f-11e5-8181-cf0732feea44.png)

**Comment by pmattern** [comment]
Cannot reproduce, neither running latest stable release nor recent VCS checkouts of both SDDM and all LXQt components.
We definitely need more information:
* which OS are you running
* is it running in a virtual machine or "bare metal"
* which version of SDDM and LXQt and how were these installed
* content of /etc/xdg/autostart and ~/.config/autostart
* are you aware of some recent change that may have triggered the problem, e. g. an update of some or more system components

**Comment by MttCastelli** [comment]
@pmattern you're right, sorry.

. Distributor ID: Ubuntu
Description:    Ubuntu 15.04
Release:        15.04
Codename:       vivid

. it's a dual boot alongside Windows 7 on a HP Mini 210

. apt-cache show sddm
Package: sddm
Priority: optional
Section: universe/kde
Installed-Size: 1091
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian/Kubuntu Qt/KDE Maintainers <debian-qt-kde@lists.debian.org>
Architecture: amd64
Version: 0.11.0-0ubuntu10
(sddm and sddm-theme-lubuntu-chooser are from vivid repository)

. matteo@HP-Mini-210:/etc/xdg/autostart$ ls -l
totale 112
-rw-r--r-- 1 root root 9279 ago  7  2014 cute-updates.desktop
-rw-r--r-- 1 root root  450 apr  8 17:34 gnome-keyring-gpg.desktop
-rw-r--r-- 1 root root  485 apr  8 17:34 gnome-keyring-pkcs11.desktop
-rw-r--r-- 1 root root  478 apr  8 17:34 gnome-keyring-secrets.desktop
-rw-r--r-- 1 root root  445 apr  8 17:34 gnome-keyring-ssh.desktop
-rw-r--r-- 1 root root  279 nov  3  2014 gsettings-data-convert.desktop
-rw-r--r-- 1 root root  249 gen 28 22:21 indicator-application.desktop
-rw-r--r-- 1 root root  444 giu  9 15:52 lxqt-compton.desktop
-rw-r--r-- 1 root root  877 giu  9 15:52 lxqt-desktop.desktop
-rw-r--r-- 1 root root 1070 giu  9 15:52 lxqt-globalkeyshortcuts.desktop
-rw-r--r-- 1 root root 1173 giu  9 15:52 lxqt-notifications.desktop
-rw-r--r-- 1 root root  720 giu  9 15:52 lxqt-panel.desktop
-rw-r--r-- 1 root root 1255 giu  9 15:52 lxqt-policykit-agent.desktop
-rw-r--r-- 1 root root  248 giu 15 22:16 lxqt-powermanagement.desktop
-rw-r--r-- 1 root root 1172 giu  9 15:52 lxqt-ptbatterysystemtray-autostart.desktop
-rw-r--r-- 1 root root  847 giu  9 15:52 lxqt-qlipper-autostart.desktop
-rw-r--r-- 1 root root  767 giu  9 15:52 lxqt-qxkb-autostart.desktop
-rw-r--r-- 1 root root  824 giu  9 15:52 lxqt-runner.desktop
-rw-r--r-- 1 root root  193 mag 19 07:05 lxqt-screenlocker.desktop
-rw-r--r-- 1 root root 1140 giu  9 15:52 lxqt-xscreensaver-autostart.desktop
-rw-r--r-- 1 root root  244 apr 16 17:51 notification-daemon-autostart.desktop
-rw-r--r-- 1 root root  358 nov 21  2014 polkit-gnome-authentication-agent-1.desktop
-rw-r--r-- 1 root root  375 apr  8 11:06 print-applet.desktop
-rw-r--r-- 1 root root 4362 apr 20 17:39 pulseaudio.desktop
-rw-r--r-- 1 root root  312 lug  3  2013 user-dirs-update-gtk.desktop
 
and 

matteo@HP-Mini-210:~/.config/autostart$ ls -l
totale 32
-rw-rw-r-- 1 matteo matteo   96 apr 29 16:34 CMST.desktop
-rw-rw-r-- 1 matteo matteo  235 giu 17 15:36 dropbox.desktop
-rwxr-xr-x 1 matteo matteo  305 feb 18 23:11 grive-indicator-autostart.desktop
-rw-rw-r-- 1 matteo matteo 2204 apr 26 12:27 light-locker.desktop
-rw-rw-r-- 1 matteo matteo  283 feb 22 13:17 lxqt-compton.desktop
-rw-rw-r-- 1 matteo matteo  275 giu 10 09:54 lxqt-config-monitor-autostart.desktop
-rw-rw-r-- 1 matteo matteo  116 apr 29 16:34 lxqt-connman-applet.desktop
-rw-rw-r-- 1 matteo matteo  228 apr 26 12:27 lxrandr-autostart.desktop


I update daily the ubuntu packages and lubuntu-dev PPA.

**Comment by palinek** [comment]
@MttCastelli could you also paste the content of ~/.xsession-errors (from session where the 'desktop crashed too...' is shown)

**Comment by MttCastelli** [comment]
of course, ~/.xsession-errors:

/build/lxqt-session-XT7UiZ/lxqt-session-0.9.0.0.1+bzr245+201505301638~ubuntu15.04.1/lxqt-session/src/sessionapplication.cpp : 75 Session "session" about to launch (default 'session')
Environment variable BROWSER = qupzilla
Environment variable GTK_CSD = 0
Environment variable TERM = qterminal
"/home/matteo/.config/lxqt/session.conf"
xrdb: Xcursor.theme:DMZ-White
Xcursor.size:18
Xcursor.theme_core:true

Window Manager started
start "/home/matteo/.config/autostart/dropbox.desktop"
start "/home/matteo/.config/autostart/grive-indicator-autostart.desktop"
start "/home/matteo/.config/autostart/light-locker.desktop"
start "/home/matteo/.config/autostart/lxqt-config-monitor-autostart.desktop"
start "/etc/xdg/autostart/cute-updates.desktop"
start "/etc/xdg/autostart/lxqt-desktop.desktop"
start "/etc/xdg/autostart/lxqt-globalkeyshortcuts.desktop"
start "/etc/xdg/autostart/lxqt-notifications.desktop"
start "/etc/xdg/autostart/lxqt-panel.desktop"
start "/etc/xdg/autostart/lxqt-policykit-agent.desktop"
start "/etc/xdg/autostart/lxqt-runner.desktop"
start "/etc/xdg/autostart/print-applet.desktop"
start "/etc/xdg/autostart/pulseaudio.desktop"

** (grive-indicator:825): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Process "Desktop" ( LxQtModule(0x1335540) ) has to be restarted
Process "Desktop" ( LxQtModule(0x1335540) ) has to be restarted
System Tray started
start tray app "/home/matteo/.config/autostart/CMST.desktop"
start tray app "/etc/xdg/autostart/lxqt-powermanagement.desktop"
Process "Desktop" ( LxQtModule(0x1335540) ) has to be restarted
Process "Desktop" ( LxQtModule(0x1335540) ) has to be restarted
Process "Desktop" ( LxQtModule(0x1335540) ) has to be restarted
/opt/thefanclub/grive-tools/grive-indicator:75: Warning: Source ID 4 was not found when attempting to remove it
  GLib.source_remove(timerName)

**Comment by MttCastelli** [comment]
@pmattern @palinek I think you can reproduce this if you set desktop as hme dir and reboot, I've tested to logon with desktop as ~/Desktop and everything goes right. If I set destop as home dir after the login it works, owever. So, I gues I can say:

1. this bug is not about sddm a all, and I could maybe change the thread name
2. this bug is somehow releated to #541 (it seems really to be a curse for me... :)

**Comment by pmattern** [comment]
In the meantime I could confirm your findings as follows:
Problem is indeed caused by using $HOME as desktop directory (XDG_DESKTOP_DIR="$HOME" in .config/user-dirs.dirs). It doesn't matter whether the session is launched by a display manager like SDDM or LightDM or from a virtual terminal by running startx.
But it can be seen with the said *buntu PPA only, not with recent VCS packages from Arch Linux AUR. Using the latter $HOME as desktop directory works flawlessly as can be seen from the icons on the desktop.

This is a bit odd as the PPA seems to be up-to-date at a glance. On the other hand they do specific tweaking as can be seen from that infamous split of lxqt-leave we had to discuss recently in #653.
So all in all this looks like a downstream issue to me the discussion of which should, if at all on this tracker, be continued in #541.
