### ISSUE TITLE
Translation  sources not complete, to update

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#693]
As far as I have seen:
lxqt-config-monitor.ts (lxqt-config)
lxqt-config-session.ts (lxqt-session)
lxqt-panel: panel itself, plugin taskbar
/lxqt-notificationd/config/translations/lxqt-config-notificationd.ts
lxqt-config-globalkeyshortcuts.ts

**Comment by palinek** [comment]
Translations are not updated reguarly (after each change in sources)....

@jleclanche, @luis-pereira what's the strategy for updating the translation files?

**Comment by luis-pereira** [comment]
@palinek Undefined AFAIK

**Comment by paulolieuthier** [comment]
@palinek I guess after most bugs are fixed and we are ready for the release, all translation sources must be updated, and translators must work and the the release done.

**Comment by luis-pereira** [comment]
@palinek @paulolieuthier before a release we should have a string freeze.

**Comment by paulolieuthier** [comment]
@luis-pereira that's exactly what I mean.

**Comment by stefonarch** [comment]
A string freeze is okay before releasing, but when translators get only one (sun)day before the release  as it seems to be now we are  to ship half translated panel and config (as for Italy a lot of users just don't understand any english).  Just for the panel * pligins I did'n see heavy changes, there would have been plenty of time to translate IMHO.

So I think policy updating *.ts files should be more flexible.

**Comment by jleclanche** [comment]
@stefonarch I agree. I wasnt going to talk about this just yet but I thought about it during the night; here's some initial thoughts on restructuring of the project with pootle in mind: https://github.com/lxde/lxqt/wiki/Thoughts-on-Pootle

This means that I'm hoping to set up a single tree for translations with daily updates, which will automatically be pulled in by cmake or some such.

**Comment by dglent** [comment]
In the above thoughts page there is no mention for transifex, it is excluded from any discussion ?

**Comment by jleclanche** [comment]
We won't be using transifex. They're neither open source nor self-hostable, and we already have pootle architecture in place with a bunch of users.

**Comment by stefonarch** [comment]
On the last release I didn't see any update of .ts files in panel and other settings, it would be nice to have some time to translate new stuff this time.
