### ISSUE TITLE
Make use of new CMake features

### ISSUE THREAD

**Issue by paulolieuthier** [lxde/lxqt#698]
There are some new CMake features we could be using, and we are not. Take a look at [`CMAKE_AUTOUIC`](http://www.cmake.org/cmake/help/v3.0/prop_tgt/AUTOUIC.html) and [`CMAKE_AUTORCC`](http://www.cmake.org/cmake/help/v3.0/prop_tgt/AUTORCC.html). [I've been waiting for it](https://github.com/lxde/lxqt-panel/blob/master/CMakeLists.txt#L48), and the only reason for not using it (IMO) was that Debian stable didn't package the minimum necessary version, which is 3.0.2. That's why LXQt components depend on CMake 2.8.12+. But now CMake 3.0.2 has come to Debian stable. And also Qt 5.3.2.

I take Debian stable as my reference, as it's widely used and very solid, with old versions of most packages. But sadly, it has [no signal of KF5](https://tracker.debian.org/pkg/kwindowsystem) that I know of.

**Comment by luis-pereira** [comment]
@paulolieuthier I'm on updating the build system to use the Targets infrastructure. 
LXQt minimum CMake requirement was 2.8.11. To use Targets 2.8.12 is required.  I've done most of the work (libqtxdg, liblxqt) requiring only 2.8.12. If we could bump the CMake minimum required to 3.0.2 would be nice. Targets improved a lot from 2.8.12 to 3.0.2.

**Comment by paulolieuthier** [comment]
Opinions?

**Comment by Esclapion** [comment]
Here (Manjaro stable), I have 3.2.3, for info.

**Comment by pmattern** [comment]
@Esclapion 
Closing this one wasn't really intentional, was it?

**Comment by Esclapion** [comment]
Sorry, a bad click... :-( not intentional, sure.

**Comment by jleclanche** [comment]
CMake 3.0 was released over a year ago. I'm OK with depending on Cmake 3 because it's the maintainer's job to compile the packages, and they should have no problems getting hold of cmake 3 even when packaging for debian stable.

So +1.

**Comment by jleclanche** [comment]
This can be landed for next milestone if someone is willing to pick it up.

**Comment by jleclanche** [comment]
Please make sure to add it to the roadmap if it does go in: https://github.com/lxde/lxqt/wiki/0.10-Roadmap

**Comment by paulolieuthier** [comment]
@luis-pereira let's do it.

**Comment by luis-pereira** [comment]
@paulolieuthier Yeap. Let's use v3.0.2 as the minimum required. I will be updating CMakeLists.txt in the Targets branch to `cmake_minimum_required(VERSION 3.0.2 FATAL_ERROR)`

**Comment by paulolieuthier** [comment]
@jleclanche done.
