### ISSUE TITLE
PCManFM translations in places view

### ISSUE THREAD

**Issue by antis81** [lxde/lxqt#699]
Small one. In the German version of LXQt, the "Desktop" entry is translated with "Arbeitsplatz" (workspace), while it should be "Schreibtisch".

Screenshots:
![pcmanfm-qt-i18n](https://cloud.githubusercontent.com/assets/440517/8229516/09f7ed70-15b8-11e5-9ae4-1f4f41ce615b.png)

**Comment by pmattern** [comment]
[Closing by pushing to my (testing) repo unintended for now. Stay tuned.]

**Comment by antis81** [comment]
Consistency is what I want to achieve here in the first place. For the term itself I agree, that the German term "Arbeitsfläche" would fit the meaning better. But ... especially these nasty terms unfortunately got established by a well known other desktop environment. Thus, I suggest to settle with this for now and not waste time on this one. The day will come, when the term can be corrected consistently. Thanks a lot! :+1:
