### ISSUE TITLE
lqxt-panel, plugin main-menu custom font size setting not working

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#705]
Right click, activating "use custom font size" and changing it to any value does not change font size at all.

**Comment by pmattern** [comment]
Confirmed.

**Comment by stefonarch** [comment]
I see that it get's applied obly after restarting lxqt-panel.

**Comment by pmattern** [comment]
I wonder whether it may be related to #441. lxde/liblxqt#33 was just a workaround but LXQt isn't adapted to that new Qt behaviour yet.

**Comment by palinek** [comment]
@pmattern this wasn't connected to #441 and IMHO the #441 issue is fixed in lxde/liblxqt#33 correctly (not a hackish workaround).
