### ISSUE TITLE
plugin-mount: window listing devices disappears upon clicking panel icon only

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#706]
The window listing available devices or the lack thereof that comes up by clicking on plugin-mount's icon disappears when that icon gets clicked again only. It doesn't disappear when any other location on the desktop / in other windows gets clicked.

Latest VCS checkouts of LXQt on Arch Linux i686 or x86_64, hence compiled against Qt 5.4.2. (→ Hopefully not a remnant of #436 / [QTBUG-44231](https://bugreports.qt.io/browse/QTBUG-44231)?)

**Comment by palinek** [comment]
I thought this is a feature. How should it be changed?

**Comment by pmattern** [comment]
I think the listing should disappear upon clicking any spot on the desktop that doesn't belong to the plugin, much as it's handled by plugin-mainmenu already.
This would both make more sense and be consistent.

On a side note I stumbled upon some inconsistency regarding plugin-[world]clock.
The calendar that pops up by clicking the panel icon of those plugins disappears when any area outside the plugin is clicked as stated above, but also after the mouse got moved elsewhere without clicking anything. I think the latter should get adapted to the behaviour described above as well.
On the one hand this would again be consistent. But IMO it would also make sense aside from that. A calendar is an object a user may very well want to stay open while the mouse gets hovered above some other object on the desktop, e. g. to compare dates or the likes.

**Comment by palinek** [comment]
@pmattern please, check & reopen if neccessary.

**Comment by pmattern** [comment]
The actual behaviour of the objects coming up on (left) clicking is now alright in all three plugins affected.

But the commit introduced a minor regression in both `plugin-[world]clock`: if the calendar was opened by clicking on the icon and closed by clicking elsewhere on the desktop the panel plugin itself is further highlighted (?) which can only be removed by hovering again. E. g. in this screenshot
![lxqt-panel_clock-highlighting-after-closing-calendar](https://cloud.githubusercontent.com/assets/9860801/10706110/edcaab34-79e3-11e5-814c-fb5aa73c75ec.png)
the calendar of `plugin-clock` at the left had been dealt with as stated leaving `plugin-worldclock` at the right as is (selection of `plugin-clock` just as example, `plugin-worldclock` behaves exactly the same).

**Comment by jleclanche** [comment]
@pmattern please commit in branches, otherwise you end up autoclosing issues.

**Comment by pmattern** [comment]
@jleclanche 
Will pay attention better next time. Yet this is some pretty stupid behaviour, IMO: I wasn't *committing* anything but just synced my GitHub fork with `master`...

**Comment by paulolieuthier** [comment]
> The actual behaviour of the objects coming up on (left) clicking is now alright in all three plugins affected.

@pmattern so we can close this?

**Comment by pmattern** [comment]
> @pmattern so we can close this?

The problem itself is solved.
The regression depicted [above](https://github.com/lxde/lxqt/issues/706#issuecomment-150705635) persists. But it can be seen with other plugins like plugin-mainmenu as well and is eventually caused by the upstream issues discussed in #971.

So to some degree it's a matter of taste whether we close this or leave it open as kind of reminder. But we sure can remove the 0.11 tag as the current status can definitely make it into a release.

**Comment by paulolieuthier** [comment]
Let's keep the remaining discussion in #971, then.
