### ISSUE TITLE
panel clock plugin - fontsize changes, when seconds displayed

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#709]
http://bugs.siduction.org/attachments/download/221/vokoscreen-2015-06-22_01-12-30.mkv

**Comment by pmattern** [comment]
Probably due to the same root problem discussed in general in #632 and regarding Date & time in #660. Maybe even a consequence of the changes introduced by the latter.

**Comment by paulolieuthier** [comment]
Fixed by lxde/lxqt-panel#220.

**Comment by palinek** [comment]
> Fixed by lxde/lxqt-panel#220.

@paulolieuthier I hope so... but @agaida needs to confirm that

**Comment by agaida** [comment]
confirmed
