### ISSUE TITLE
Configure context menu on right mouse click

### ISSUE THREAD

**Issue by lastyle** [lxde/lxqt#711]
Please, where is the settings for configure contents of the context menu bringing up by right mouse click on background. I cant find anythink, no panel for settings this, no configuration file.
By using pcman i can only enable/disable this menu.
Tnx

**Comment by pmattern** [comment]
Unfortunately the context menu provided by LXQt itself upon right-clicking the desktop can't be tweaked in any way by now. Also, a menu opened by middle-click isn't provided by LXQt at all.
Discussions on how to eventually change this were e. g. started in #464 or #469.

All that can be tweaked is whether to use the context menu provided by LXQt or those of the underlying window manager.
This is set in Tab "Advanced" of GUI "Desktop Preferences" that can e. g. be launched from panel main menu - Preferences - LXQt settings - Desktop or by running `pcmanfm-qt --desktop-prefs={general,advanced}`.
It's this GUI you had in mind saying "By using pcman..."?

Maybe it would make sense to share your thoughts in #464 and close this one.

**Comment by lastyle** [comment]
Thx for reply. I readed 464, but this is not the same thing.
This information is important for me, Cant be tweaked.
Thx one more time
