### ISSUE TITLE
confirmation before leaving checked but not in effect in new user profiles

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#712]
When LXQt is used for the first time by a distinct user "Ask confirmation to leave session" in lxqt-config-session - "Basic Settings" is checked but doesn't apply.
The setting only gets valid when it was unchecked and checked again which is reflected in the corresponding setting in ~/.config/lxqt/session.conf.

Btw. shouldn't this be "Ask *for* confirmation to leave session"?

**Comment by paulolieuthier** [comment]
@pmattern good catch.
