### ISSUE TITLE
Correct signal handling in applications

### ISSUE THREAD

**Issue by palinek** [lxde/lxqt#714]
According to official Qt documentation [Calling Qt Functions From Unix Signal Handlers](http://doc.qt.io/qt-5/unix-signals.html) we are not correcly handling our applications exit. E.g. in lxqt-panel, the signal handling function does following:
```c++
void termSignalHandler(int)
{
    if (qApp)
        qApp->quit();
}
```

We probably should not assume that there are only async-signal-safe functions in logic of  `QCoreApplication::quit()` (which only calls `QCoreApplication::exit(0)`).

Should we implement correct (termination) signal handling directly into `LxQt::Application`?

**Comment by paulolieuthier** [comment]
I didn't know that. I took that code from KDE's source.

**Comment by luis-pereira** [comment]
Closed by https://github.com/lxde/liblxqt/issues/52

**Comment by palinek** [comment]
@luis-pereira did you search in other apps if they do signal handling on its own?

**Comment by luis-pereira** [comment]
@palinek Yes. Did I miss something ?

**Comment by palinek** [comment]
I didn't search...i'll trust you :-)

**Comment by luis-pereira** [comment]
:smile: searching for `sigaction`  returns 0 matches

**Comment by palinek** [comment]
> :smile: searching for sigaction returns 0 matches

...but searching for SIGTERM, SIGINT found something:
```
...
./lxqt-sudo/main.cpp:    ::signal(SIGTERM, termSignalHandler);
./lxqt-sudo/main.cpp:    ::signal(SIGINT, termSignalHandler);
./lxqt-globalkeys/daemon/core.cpp:        ::signal(SIGTERM, ::unixSignalHandler);
./lxqt-globalkeys/daemon/core.cpp:        ::signal(SIGINT, ::unixSignalHandler);
...
```

**Comment by palinek** [comment]
.. updated in lxde/lxqt-sudo@6c95b3ece03fb245e967083d2632f0b6bf11a9a9 and lxde/lxqt-globalkeys@c163211

**Comment by luis-pereira** [comment]
@palinek hmmmmmmmmm An biased search, I actually stopped using ```signal``` over ```sigaction``` 
_given enough eyeballs, all bugs are shallow_
