### ISSUE TITLE
Maximised window sticks out on second display in dual screen extended view setup

### ISSUE THREAD

**Issue by robwoj** [lxde/lxqt#715]
Hi,

When I maximize a window (any window, e.g. firefox or lxterminal), it is maximised on one screen, but I can see a strip of the maximized window on a second screen. I has probably only one pixel width.

**Comment by palinek** [comment]
This is 99% not LXQt issue and is probably connected to your screens resolution/position settings.
What window manager (and any compositor?) are you using, what is the resolution/position of all screens?

**Comment by Vladimir-csp** [comment]
Either WM or compositor drops shadow or thick border out, or xrandr configuration has a small overlap between displays. Give geometry data from xrandr output.

**Comment by robwoj** [comment]
Indeed, my fault. My xrandr settings got for some reason invalid values for x axis offset. Thx for a quick reply!
