### ISSUE TITLE
[feature request] Add confirmation dialog for remove panel context menu option

### ISSUE THREAD

**Issue by robwoj** [lxde/lxqt#716]
It happens more than once to me to drop configured panel accidentally by clicking with right mouse button on the panel. It would be nice to show some confirmation dialog to avoid reconfiguring all those widgets.

Best regards,
Robert

**Comment by maces** [comment]
+1 happend here too. It is especially frustrating when many quick launchers are configured.
btw: You can always use your backup and restore the config files.
