### ISSUE TITLE
Targets testing

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#718]
This PR is a "wrapper" that contains all the targets PR's. It''s a boring test, but it would be great to give some testing before getting it into master.

Steps to test:
* Uninstall all clean. This is very important, please don't skip it.
* Pull the __targets__ branch
* Compile and install as usual
* Report bugs

List of PR's to pull:
https://github.com/lxde/libqtxdg/pull/61
https://github.com/lxde/liblxqt/pull/51
https://github.com/lxde/lxqt-globalkeys/pull/17
https://github.com/lxde/libsysstat/pull/8
https://github.com/lxde/lxqt-config/pull/50
https://github.com/lxde/lxqt-common/pull/32
https://github.com/lxde/lxqt-session/pull/35
https://github.com/lxde/lxqt-panel/pull/222
https://github.com/lxde/lxqt-sudo/pull/4
https://github.com/lxde/lxqt-admin/pull/27
https://github.com/lxde/lxqt-powermanagement/pull/19
https://github.com/lxde/lxqt-qtplugin/pull/3
https://github.com/lxde/lxqt-policykit/pull/13
https://github.com/lxde/lxqt-openssh-askpass/pull/9
https://github.com/lxde/lxqt-about/pull/15
https://github.com/lxde/lxqt-notificationd/pull/33
https://github.com/lxde/lxqt-runner/pull/24

There are still other tasks to do. But they are "easy". They can be done without disrupting the build system. And we already have other PR's depending on these.  Some of them will need some discussion. I'm starting to open an PR for each one.

All CMake repos also support superbuild. It means that one can type:
`cmake ..`
`make`
`make install`
and all lxqt CMake repos are configured, built and installed, at once. I'm still polishing it. Stay tunned !

**Comment by paulolieuthier** [comment]
Just tested after completely removing LXQt from my system. Worked perfectly using the `build_all_cmake_projects.sh` build script. The superbuild thing will be a awesome feature, but it didn't work for me. I didn't save the log, though. Will try again later.

**Comment by luis-pereira** [comment]
@paulolieuthier You need to set the ```CMAKE_PREFIX_PATH``` to make the superbuild work. I will create config.cmake files for libfm-qt5 and then update the main ```CMakeLists.txt```

**Comment by luis-pereira** [comment]
@paulolieuthier @palinek @agaida Thinking in merging all the Targets stuff tomorrow. Any thoughts ?

**Comment by paulolieuthier** [comment]
Please, go ahead.

**Comment by palinek** [comment]
Of course, do it
