### ISSUE TITLE
lxqt-panel application menu icon changable via gui

### ISSUE THREAD

**Issue by jubalh** [lxde/lxqt#720]
the settings gui for application menu allows chaning of the text but not the icon, for this one has to edit the theme file. is there a reason for that, or could we add the option to change the icon too?
i would volunteer to work on this one.

**Comment by paulolieuthier** [comment]
Go ahead. Create a "Custom icon" field.

**Comment by jleclanche** [comment]
@jubalh you still want to do this?

**Comment by jubalh** [comment]
Yes, actually I startedpreparing my laptop for work on LXQt just yesterday. But unfortunately I have limited time. Will be away for the weekend and can start next week. sorry for the long delay, was really busy.

**Comment by intialonso** [comment]
This will be useful for the "System" theme we are discussing in #892 

@jubalh are you still into this?

**Comment by palinek** [comment]
Implemented in lxde/lxqt-panel#281
