### ISSUE TITLE
Disabling the second monitor makes its panel move to the first monitor and stay there

### ISSUE THREAD

**Issue by paulolieuthier** [lxde/lxqt#722]
"Say you have one panel on each monitor. If the monitor configuration changes momentarily so that the 2nd monitor isn't present anymore, the panel on that monitor goes to the other one and stays there."

**Comment by Vladimir-csp** [comment]
I wonder, how does it count which monitor is first, second, etc?

**Comment by paulolieuthier** [comment]
Good question. But Qt knows it: http://doc.qt.io/qt-4.8/qdesktopwidget.html#use-of-the-primary-screen.

**Comment by jleclanche** [comment]
More info on #779
