### ISSUE TITLE
lxqt-panel transparency like lxpanel, without compositor?

### ISSUE THREAD

**Issue by jeremywh7** [lxde/lxqt#723]
I know that lxqt-panel had the message added for the transparency option regarding a compositor:
https://github.com/lxde/lxqt/issues/514

In that Issue, @Vladimir-csp asked about 'pseduo-transparency.'  After it was closed, I asked about it, but realize nobody looks at closed Issues.  :-)

Please reference my post there at the bottom for details/pics, but the summary is that on the same (Openbox) system without compositor, lxde/lxpanel can make the panel transparent/translucent, while lxqt-panel can't.  So I'm wondering if this can be done in lxqt-panel (or do you not want to?).

Also, I saw a recent headline about a simple Qt compositor...maybe something you guys might be interested in, if only for a few simple things (like this, if the pseudo operation isn't possible/desirable).
Ah, here it is, for X11:
http://www.phoronix.com/scan.php?page=news_item&px=qt-compositing-manager-x11
In my search, I also saw refernce to QtCompositor for Wayland.

Anyway, thanks guys.  I know you're looking for more to do...  :-P

**Comment by paulolieuthier** [comment]
@jeremywh7 sorry for not answering you there. well, this is a limitation of how Qt works. I don't know how to workaround it. That's [documented](http://doc.qt.io/qt-5/qwidget.html#creating-translucent-windows), actually. And it's unfortunate, I agree. If you really want transparency, you'll need a compositor.

**Comment by jeremywh7** [comment]
For others who happen upon this, looking for a solution; I installed xcompmgr and it works a-ok to just have simple panel translucency.  And its really small...
Name           : xcompmgr
Version        : 1.1.7-1
Description    : Composite Window-effects manager for X.org
Architecture   : x86_64
URL            : http://xorg.freedesktop.org/
Depends On     : libxcomposite  libxdamage  libxrender  libxext
Conflicts With : xapps
Replaces       : xapps
Installed Size :  <b>69.00 KiB</b>

**Comment by Vladimir-csp** [comment]
Xcompmgr is old and buggy. Compton is its advanced fork.

**Comment by jeremywh7** [comment]
I did see that, but xcompmgr is an Arch package, while compton and all the others in the Arch wiki[1] are AUR...and I'm trying to 'KISS'.  :)  I was really surprised that compton isn't an official package though.  I'm hoping that using it in its default mode[2] will avoid those bugs...?  Sine I only want the LXQT panel to be translucent.

[1] https://wiki.archlinux.org/index.php/Xorg#Composite
[2] "-n     Simple client-side compositing. This is the default mode."

**Comment by jeremywh7** [comment]
Ok I'll bite...tried building Compton (on x64) for size comparison.  It had two deps:
Packages (1) libconfig-1.5-1
Total Installed Size:  0.19 MiB
(only needed for make) Packages (1) asciidoc-8.6.9-2
Total Installed Size:  0.75 MiB
And compton is:
Packages (1) compton-0.1_beta2-5
Total Installed Size:  0.25 MiB

So only 0.44 MiB to install.

**Comment by Ovi329** [comment]
> @jeremywh7 sorry for not answering you there. well, this is a limitation of how Qt works. I don't know how to workaround it. That's [documented](http://doc.qt.io/qt-5/qwidget.html#creating-translucent-windows), actually. And it's unfortunate, I agree. If you really want transparency, you'll need a compositor. Thanks for your help.

how do i use picom[compton fork] to make the 2 pixel bar transparent?
