### ISSUE TITLE
lx-panel task manager and application menu should not allow clicking below icons.  (remove  panel border next to screen edge)

### ISSUE THREAD

**Issue by kanliot** [lxde/lxqt#725]
In any other desktop, if you move the mouse to the very bottom of the screen/panel you can still click on the application menu, task manager buttons.  left click or right click.  

Since I'm used to other desktops, and it's often uncomfortable to move the mouse a small distance after moving the mouse to the bottom of the screen, please change lx-panel so that clicks on the bottom pixels of the screen allow the activation of the app menu, task manager buttons, etc.

You can read more concerns about a similar usability problem here: https://bugs.kde.org/show_bug.cgi?id=96727

**Comment by palinek** [comment]
This was discussed & fixed in #597 

@kanliot what version of lxqt are you running on?

**Comment by palinek** [comment]
closing...as I believe it was fixed in all .qss theme styles.
