### ISSUE TITLE
Two parallel translation directories in lxqt-powermanagment

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#726]
Only the first one contains the trayicon-section in .ts source file.
lxqt-powermanagement/src/translations/
lxqt-powermanagement/config/translations/

**Comment by palinek** [comment]
I don't follow... what's the problem here?
There are two components in lxqt-powermanagement: lxqt-powermanagement (the daemon) and lxqt-config-powermanagement (configuration GUI). Both components have their own translations.

**Comment by luis-pereira** [comment]
@palinek I also don't follow. I don't see any problem.

**Comment by stefonarch** [comment]
Ok I see, I did not look close enough at the files, they seemed identical except for trayicon.
Closing,.
