### ISSUE TITLE
keyboard state indicator: show only layout by default

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#730]
I may be wrong, but such applet is usually used for monitoring/changing keyboard layouts. So *lock state indicators could be disabled by default.

Also, layout indicator appears to be in "activated" state which makes no sense for it.

**Comment by agaida** [comment]
layout indicator allways activated is a matter of personal taste i think - i prefer it activated allways

**Comment by Vladimir-csp** [comment]
Just to be clear, I mean it looks graphically as "active" like in checkbox is checked, comparing to *lock indicators, while it itself is not an "on/off switch".

**Comment by palinek** [comment]
We probably should give the layout widget object a name... to be able to style it in theme. Not?

**Comment by zjes** [comment]
Other labels in normal state in this plugin are disabled. So is correct to disable this label to (to common style on whole control), but is possible define style to distinguish it. Object name exists - LayoutLabel.

**Comment by paulolieuthier** [comment]
Fixed.
