### ISSUE TITLE
lxqt-panel: keyboard state indicator plugin triggers some kind of loop

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#731]
Testing new layout switcher in keyboard state indicator plugin. The bug is triggered sometimes by switching layout by shortcut:
lxqt-panel eats up CPU, keyboard layout is being switched back and forth indefinitely.
Nothing is produced in lxqt-panel stdout or stderr.

**Comment by zjes** [comment]
Needs more info. Which mode, layouts... something :(
I cannot reproduce this.

**Comment by Vladimir-csp** [comment]
```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,ru
variant:    ,
options:    grp:alt_shift_toggle,grp_led:scroll,terminate:ctrl_alt_bksp
```
try switching and typing right away.

**Comment by zjes** [comment]
Confirmed :(
One times I caught it, but it disappeared after few time, before i understood what going on in debugger.

**Comment by paulolieuthier** [comment]
@Vladimir-csp can you test again? @zjes may have solved it with the referenced PR. And what is the shortcut you are using to trigger the behaviour?

**Comment by Vladimir-csp** [comment]
The shortcut, as stated by setxkbmap above, is alt+shift
looks like it's rebuilding time...

**Comment by Vladimir-csp** [comment]
After five minutes of keyboard bashing nothing broke, so far so good.

**Comment by paulolieuthier** [comment]
@Vladimir-csp great. I'm closing this. We'll reopen it if needed.
