### ISSUE TITLE
lxqt-panel/plugin-kbindicator Ui enhancement

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#735]
Current:
![screen-2015-07-06-07-21-56](https://cloud.githubusercontent.com/assets/62877/8525390/6e2ea116-23b5-11e5-96cb-a158adfbce87.png)

Proposal:

![screen-2015-07-06-07-52-18](https://cloud.githubusercontent.com/assets/62877/8525426/a7867894-23b5-11e5-8b0a-90a9ff877e55.png)

Default values can be discussed later on.

**Comment by luis-pereira** [comment]
@palinek @paulolieuthier @agaida @zjes @Vladimir-csp Would like to know your opinions.

**Comment by jleclanche** [comment]
Quick pass on the dialog as a whole, if we're gonna improve it:

- -1 on the visible "square" around the layout mode values. Can you make it not show borders?
- Change "Leds" to "Lock Indicators"
- Change "Show keyboard layout" into just a title: "Keyboard Layout Indicator"
- Move the enable/disable checkbox back inside, with the label "Enable Layout Indicator"
- "Show flags" should be a 2-value dropdown labeled as "Indicator type": "Country code" / "Country flag"
- Rename "Configure layouts" to "Keyboard and Layout settings"

**Comment by Vladimir-csp** [comment]
What jleclanche said. Flatten it up.

**Comment by jleclanche** [comment]
BTW, I don't actually understand what "Layout mode" is.

**Comment by zjes** [comment]
This is not country code/country flags. This is language code, country flag (i don't know if need it. Country flag is little bit incorrect). Layout mode - switching policy?

**Comment by palinek** [comment]
I'm for Jerome's proposals except the 2-value dropdown box (I like the checkbox here more).

**Comment by pmattern** [comment]
Just a side-note while at it: lxde/lxqt-panel@3b9c7b9 completely removed kbindicator's translations. Was this really intentional? Shouldn't these be added again somehow?

**Comment by luis-pereira** [comment]
>Quick pass on the dialog as a whole, if we're gonna improve it:
Good :smile: 

>-1 on the visible "square" around the layout mode values. Can you make it not show borders?
It's an GroupBox that makes the Radio Buttons mutually exclusive. It can be made flat. On some styles it has that effect (Oxygen, Breeze)
>Change "Leds" to "Lock Indicators"
Done

>Change "Show keyboard layout" into just a title: "Keyboard Layout Indicator"
Stopping it from being an checkable groupbox ?

>Move the enable/disable checkbox back inside, with the label "Enable Layout Indicator"
On some styles (Oxygen, Breeze)  the groupbox caption appears inside the groupbox.

>"Show flags" should be a 2-value dropdown labeled as "Indicator type": "Country code" / "Country flag"
It's not implemted, AFAIK. maybe delete it ?

>Rename "Configure layouts" to "Keyboard and Layout settings"
Done

Preview  in Fusion and Breeze
![screen-2015-07-08-13-21-12](https://cloud.githubusercontent.com/assets/62877/8581260/73cbf0d6-2574-11e5-8597-847cbbe5fe1f.png)
![screen-2015-07-08-13-20-23](https://cloud.githubusercontent.com/assets/62877/8581261/73cf6338-2574-11e5-9f4f-f54d3a8952cf.png)

**Comment by zjes** [comment]
Switch policy (layout mode) can be as dropdown list?
![conf](https://cloud.githubusercontent.com/assets/550431/8603932/9fceed84-267b-11e5-8feb-a6a3de7d0efa.png)

**Comment by Vladimir-csp** [comment]
radiobuttons are easier to operate. There's only three variants anyway.

**Comment by paulolieuthier** [comment]
I prefer radio buttons as well, and I agree on @luis-pereira's proposal.

**Comment by ThomasVie** [comment]
I suggest three dots after "Keyboard and Layout settings".

**Comment by pmattern** [comment]
> I suggest three dots after "Keyboard and Layout settings".

Don't think this makes sense.
Dots like this are normally used within menus to distinguish topics representing an action themselves from those opening another dialog window. But this doesn't apply here as it's a button and hence pretty obvious that clicking will open another window.

**Comment by jleclanche** [comment]
> Stopping it from being an checkable groupbox ?

Yes, it shouldnt be checkable. Instead, there should be an "Enable" checkbox *inside* of it.

> It's not implemted, AFAIK. maybe delete it ?

If it's not implemented then yes, get rid of it.
