### ISSUE TITLE
lxqt-leave: small GUI issues

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#736]
I would suggest setting size (height at least) for buttons, so they do not depend on icons, but rather icons would be sized according to buttons. Those buttons which have no icons are smaller:
![lxqt-leave](https://cloud.githubusercontent.com/assets/4061903/8545037/64a3fbce-24b3-11e5-820c-72f164a8a57f.jpg)

**Comment by ypnos** [comment]
I think the buttons should also be reordered and grouped.

* Lock Session
* Logout

* Suspend
* Hibernate

* Shutdown
* Reboot

Right now it is confusing as hell.

**Comment by luis-pereira** [comment]
@Vladimir-csp Making the buttons have the same height is really easy.
It's needs a facelift.
I agree with @ypnos it's confusing.
@jleclanche can help for sure.

I loved the Razor dialog. I'm in favor of something in that way.

![screen-2015-07-08-14-38-47](https://cloud.githubusercontent.com/assets/62877/8583021/5447770c-257f-11e5-9d43-e4252b481a1e.png)

**Comment by antis81** [comment]
I'm happy, that this dialog was finally readded after it disappeared in LXQt 0.9.

As a hint: The following flags prevent the dialog from being dragged via mouse (even "disables" the X11 Alt key) and disables the window frame:
```c++
// suggestion: I'd prefere to make it an "absolute" top-level window to the session 
dlg->setWindowFlags(dlg->windowFlags() | Qt::BypassWindowManagerHint | Qt::WindowStaysOnTopHint);
```

I'm also missing a `Switch User` button (rough equivalent to `su - anotheruser) to start a new LXQt session with another user. Does LXQt support this?

**Comment by ypnos** [comment]
Switch user is a functionality of the Display Manager (the recommended one for LXQt is SDDM).
LightDM and SDDM can receive a dbus method call for this functionality. You can trigger it from console via:
    
    dbus-send --type=method_call --system --dest=org.freedesktop.DisplayManager /org/freedesktop/DisplayManager/Seat0 org.freedesktop.DisplayManager.Seat.SwitchToGreeter

I also think it would be welcome to add "Switch User" to LXQt, but maybe it would be better to have a separate bug report.

**Comment by Vladimir-csp** [comment]
There could be simple selector based on current running DM, see this message: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=304406#49

**Comment by ypnos** [comment]
Yes, I would just recommend to first probe the method call via dbus, then go and check for binaries. The first will only be available if the DM also running, not only installed.

**Comment by pmattern** [comment]
Now that the GUI of `lxqt-leave` was revamped I think the counterparts of invocations like `lxqt-leave --logout` should be adjusted accordingly.
Having `lxqt-leave` shine the new way while all those others still come as regular window is an inconsistency which looks a bit odd, IMO.
