### ISSUE TITLE
libqtxdg: quoting in desktop file Exec

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#737]
I've used to start conky by autostart entry with:
```
Exec=sh -c 'sleep 1 ; conky & sleep 20 ; kill $! ; exec conky'
```
(start conky, kill and start again after 20 seconds to work around some size bugs).
Such line worked wit lxde and openbox sessions, but not with lxqt-sesson. In this variant it gives "Unterminated quoted string" error in .xsession-errors when started.

Ok, so the spec says: "Quoting must be done by enclosing the argument between double quotes and escaping the double quote character, backtick character ("`"), dollar sign ("$") and backslash character ("\") by preceding it with an additional backslash character."
So I edited the line like so:
```
Exec="sh -c 'sleep 1 ; conky & sleep 20 ; kill \$! ; exec conky '"
```
And it still does not start.
How to do this properly? And is everything OK with LXQt implementation?

**Comment by pmattern** [comment]
`Exec=sh -c "sleep 1 ; conky & sleep 20 ; kill $! ; exec conky"` is working here, also if '&' and '$' are escaped by a backslash.
Didn't manage to reproduce the message in ~/.xession-errors you state, though.

Not sure whether there's a violation of the [specification](http://www.freedesktop.org/wiki/Specifications/desktop-entry-spec/).
It states that binary arguments should be quoted by double quotes as a whole. But I didn't manage to get something like `Exec=sh "-c sleep 1 [...] exec conky"` running. This does work with a Firefox invocation like `Exec=/usr/lib/firefox/firefox "-P Intranet\ 1" -new-instance %u` which made me stumble upon that whole thing some months ago.
Also, I can remember some `Exec` lines LXQt refused to accept did work both on LXDE and Xfce.
On the other hand the [part about key `Exec`](http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s06.html) doesn't seem exactly unambiguous to me: First it's stated some characters must be escaped
> Quoting must be done by enclosing the argument between double quotes and escaping the double quote character, backtick character ("`"), dollar sign ...

next those very same characters represent only a fraction of so-called "reserved" ones
> Reserved characters are space (" "), tab, newline, ...

Btw. successfully launching that sh-command, either on a terminal emulator or via a *.desktop file, yielded two running conky instances here.

**Comment by luis-pereira** [comment]
@pmattern @Vladimir-csp ```Exec=sh -c "sleep 1 ; conky \& sleep 20 ; kill \$! ; exec conky"``` works.
It's an violation or a result of the special meaning of the `-c` option ? Not really sure. More testing needed. @Vladimir-csp original line also let the `-c` out of the single quotes. Replacing the `'` by `"` and escaping `&` and `$` it's done according to the standard. 

The standard splits the command line in two parts: the executable and the arguments. Quoting everything makes the all command line part of the executable and leaves the arguments empty.

The single quotes are not even refereed in the specification.

This issue _reminds_ me of writing a simple tool to run .desktop files on the command line. How do you guys are testing ?

**Comment by Vladimir-csp** [comment]
As far as I can tell, sh takes command line as a single argument to -c option (quoted). So libqtxdg (am I right here?) runs sh with two arguments: -c and whatever is in double quotes. It works. If you also quote -c together with the rest of line, it would not make any sense to sh.

I used first single quotes variant because of historic reasons, it worked for me before LXQt. I'm gladly dumping it now.

@luis-pereira, some weeks ago I've googled a .desktop launcher written in python:
```
#!/usr/bin/python

from gi.repository import Gio
import sys 

def main(myname, desktop, *uris):
    launcher = Gio.DesktopAppInfo.new_from_filename(desktop)
    launcher.launch_uris(uris, None)

if __name__ == "__main__":
    main(*sys.argv)
```

**Comment by luis-pereira** [comment]
@Vladimir-csp Yes, It's that's what libqtxdg does. I made some additional checks and didn't found anything unexpected.

That's a good script to have at hand. Thanks.
I will write something to enable us to test libqtxdg implementation. I did my tests by putting an .desktop in the panel quicklaunch. 
Nothing fancy, something like this: `qtxdg-desktop --exec xpto.desktop`

**Comment by luis-pereira** [comment]
@Vladimir-csp Can this be closed ?

**Comment by Vladimir-csp** [comment]
If no one intends to recheck the spec implementation just in case, then yes. Works on my side.
