### ISSUE TITLE
lxqt-globalkeys ftbfs with Qt 5.3.2 and cmake 3.0.2

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#742]
<pre>CMake Error: install(EXPORT "lxqt-globalkeys-targets") given absolute DESTINATION "/usr/lib/i386-linux-gnu/cmake/lxqt-globalkeys" but the export references an installation of target "lxqt-globalkeys" which has relative DESTINATION "lib/i386-linux-gnu".
CMake Error: install(EXPORT "lxqt-globalkeys-ui-targets") given absolute DESTINATION "/usr/lib/i386-linux-gnu/cmake/lxqt-globalkeys-ui" but the export references an installation of target "lxqt-globalkeys-ui" which has relative DESTINATION "lib/i386-linux-gnu".</pre>

find the full paste here: http://pastebin.com/wn7CeR6r

Qt 5.4.2 build fine without changes. All other packages build fine with Qt 5.3.2

@paulolieuthier @luis-pereira - sorry, but this a bit over my cmake knowledge

**Comment by paulolieuthier** [comment]
@luis-pereira we're still using the `LIB_SUFFIX` variable in lxqt-globlakeys.

https://github.com/lxde/lxqt-globalkeys/blob/master/client/CMakeLists.txt#L206
https://github.com/lxde/lxqt-globalkeys/blob/master/CMakeLists.txt#L15

**Comment by luis-pereira** [comment]
@paulolieuthier @agaida I'm on the process of changing that to GnuInstallDirs. Already cleaned up libsystat. lxqt-globalkeys is next.

Actually I'm cleaning it up everywhere.

**Comment by paulolieuthier** [comment]
Nice.

**Comment by luis-pereira** [comment]
There's a mix of relative paths with full paths and hardcoded stuff.

**Comment by agaida** [comment]
sounds like a lot of fun :) - thank you

**Comment by luis-pereira** [comment]
@agaida Can you test https://github.com/lxde/lxqt-globalkeys/commit/d2f45dbbc6c184d5bbadc9d334c035cea65dbd43 ?
There are yet other cleanup to do, but this should fix this FTBFS.

lxqt-mount, lxqt-config and lxqt-admin may have the same problem

**Comment by agaida** [comment]
build, install and work fine with sid
build and install with jessie - couldn't test it right now, later
big thanks

**Comment by luis-pereira** [comment]
@agaida It works Ok, pls merge. Not sure if I will be around.

**Comment by agaida** [comment]
done
