### ISSUE TITLE
some icons are missing

### ISSUE THREAD

**Issue by fguzm** [lxde/lxqt#743]
panel: volume icon missing
lxqt-config: all icons but openbox setting and gparted and synaptic missing
lxqt-leave: all icons missing
debian testing  64bit, no difference between user (me), new user and root

**Comment by pmattern** [comment]
This is for sure not a general problem.
To further track we need more info: Version of LXQt and way it was installed? Icon theme in use (see main menu - Preferences - LXQt settings - Appearance - Icon Theme)?

**Comment by fguzm** [comment]
Installed via http://packages.siduction.org/lxqt/ unstable main
Version 0.9.0
Seems I cannot change icon theme with lxqt-config-appearance, but at least is has no effect to the missing icons.
I last tested lxqt 3 month ago or so, at this time the icons were visible. So my config files are 3 month old?

**Comment by Vladimir-csp** [comment]
I've seen the same behavior with LXQt components when I used them in LXDE session. (Debian testing, LXQt packages rebuilt from lubuntu-daily ppa).
It supposedly began after qt libs upgrade in Debian.
When I switched to LXQt session, I had no such issue.
Since LXQt components are somewhat DE-independent, this worth some investigation. They should theme themselves properly outside LXQt session.

**Comment by fguzm** [comment]
That was the problem, thank you Vladimir-csp.
I lately have fiddled around with qt5.5 and messed up the versions.

**Comment by Vladimir-csp** [comment]
I think, this should remain open, see my previous message/

**Comment by pmattern** [comment]
I agree that things like theming should work on desktop environments other than LXQt as well but cannot confirm the findings regarding LXDE either:
Icons in lxqt-config, panel plugin volume as well as those belonging to lxqt-leave show up correctly, changing the icon theme in lxqt-config-appearance works and gets adopted by e. g. LXImage-Qt and PCManFM-Qt at once.
Again either release 0.9.0 or latest Git code on Arch Linux.

Given that the Arch packages are vanilla stuff and in addition considering 
> It supposedly began after qt libs upgrade in Debian.

as well as
> I lately have fiddled around with qt5.5 and messed up the versions.

this pretty much looks like a downstream issue to me.

**Comment by fguzm** [comment]
I upgraded the qt libs to version 5.5 from the experimental debian repo, thus I had to uninstall the most lxqt things. So I compiled lxqt myself using the git version (thanks to Mr. palinek!).
But this icon issue is now back again, exactly like described in the initial post.

**Comment by luis-pereira** [comment]
@fguzm what icon theme are you using ?

**Comment by fguzm** [comment]
gnome-wise

**Comment by luis-pereira** [comment]
Ok. What other icon themes do you have installed ?

**Comment by fguzm** [comment]
adwaita and gnome

**Comment by luis-pereira** [comment]
Does it work with Adwaita ?

**Comment by fguzm** [comment]
Switching the theme doesn't change the panel icons in any way.
Btw "activate item on single click" also not works.

**Comment by luis-pereira** [comment]
@fguzm do you have lxqt-qtplugin installed and the `QT_QPA_PLATFORMTHEME=lxqt` set ?

**Comment by fguzm** [comment]
QT_QPA_PLATFORMTHEME=lxqt did the trick, thank you!
The page https://github.com/lxde/lxqt-qtplugin describes it, but who reads that?
Why is the variable not automatically set, I would expect that from a desktop 'environment'

**Comment by palinek** [comment]
https://github.com/lxde/lxqt-common/blob/master/startlxqt.in#L60

**Comment by luis-pereira** [comment]
@palinek faster than the speed of light :smiley:

**Comment by fguzm** [comment]
Why so rude? I have installed lxqt-common and lxqt-qtplugin, but this variable in not automatically set.

**Comment by pmattern** [comment]
Environment variable `QT_QPA_PLATFORMTHEME` gets very well set on Debian testing x86_64 running LXQt from the Siduction repository here, doesn't matter whether the LXQt session is started by SDDM or from a virtual terminal by `startx`.
So for the reasons stated in my previous post this pretty much looks like a problem of your particular system, it's not even a downstream problem in general.
You may want to look whether `/usr/bin/startlxqt` is featuring the `export` line stated by palinek and investigate why it's eventually missing.

> Why so rude?

Cannot find anything rude in this thread.
But presuming problems in upstream code ("Why is the variable not automatically set, I would expect that from a desktop 'environment'") as long there's basically no real evidence for sure isn't something rendering developers more friendly.
