### ISSUE TITLE
lxqt-runner: add case insensitive matching in history

### ISSUE THREAD

**Issue by antis81** [lxde/lxqt#745]
I really like LXQt-Runner and it became immediately a preferred way to run applications. Usually I type the name lower case, which works totally fine for registered entries (e.g.: Type "firef" and "Firefox" appears in the list).

What's a bit annoying however is, that this does not work for entries in the history ("Verlauf" in German). Typing a name like "myapplication" will not show "MyApplication", while typing "MyApplication" finds it.

Can you please change the matching to case insensitive?

**Comment by palinek** [comment]
fixed in lxde/lxqt-runner@7d9ba4a4b0bc43a887e2ad3d32fe87e538c4db27
