### ISSUE TITLE
Ubuntu builds via PPA (as per Wiki) missing Pulseaudio option in volume control settings

### ISSUE THREAD

**Issue by tomchiverton** [lxde/lxqt#747]

**Comment by palinek** [comment]
Isn't this a downstream issue? And as so ....shouldn't this be reported in the downstream (ubuntu/ppa) tracker?

**Comment by tomchiverton** [comment]
Not AFAIK. It's a package issue in the lxqt PPA if the option is available on other platforms? 
-- 
Tom

**Comment by palinek** [comment]
> It's a package issue in the lxqt PPA if the option is available on other platforms?

IMO yes, there is no runtime check for pulse audio libraries. PA support/libraries is/are checked/compiled in build time. See [here](https://github.com/lxde/lxqt-panel/blob/master/CMakeLists.txt#L240) and [here](https://github.com/lxde/lxqt-panel/blob/master/plugin-volume/CMakeLists.txt#L33)

**Comment by tomchiverton** [comment]
So where should I be raising this issue ?

**Comment by palinek** [comment]
IMO here -> https://bugs.launchpad.net/~lubuntu-dev
