### ISSUE TITLE
lxqt downloads URL is not working

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxde/lxqt#748]
At the website http://lxqt.org is a reference to http://downloads.lxqt.org, which is used by https://aur.archlinux.org/packages/lximage-qt/

However, the URL does not seem to work.

**Comment by medicalwei** [comment]
I temporarily created a GitHub pages for the transition as the domain name was erroneously pointed to GitHub.

**Comment by ArthurBorsboom** [comment]
Do you know of a working URL with released versions?

**Comment by medicalwei** [comment]
No, as we need to generate it ourselves as for GitHub pages. If you really
need it, please visit https://github.com/lxde/downloads.lxqt.org to find
the relative URL.

And that repo is only a temporary measure to keep the AUR you posted
working. I asked our DNS server maintainer to redirect the domain name to
the server we have full control, and the server is ready to serve the files.

Arthur Borsboom <notifications@github.com> 於 2015年7月15日週三 14:49 寫道：

**Comment by jleclanche** [comment]
@ArthurBorsboom I'm hoping to get this fixed by the end o fthe week.

**Comment by jleclanche** [comment]
All taken care of.
