### ISSUE TITLE
lxqt-config-globalkeyshortcuts: UI compromised

### ISSUE THREAD

**Issue by antis81** [lxde/lxqt#749]
Uhm ... I don't know what exactly happened, but when I open the `global keyboard shortcuts configuration` it's completely empty and even more all buttons (edit, add, remove, ...) are disabled. The config file however is still in the right place at `~/.config/lxqt/globalkeyshortcuts.conf` - phew :sweat_smile:. I also checked the file permissions are correct and were not changed by accident :white_check_mark:.

When I opened the dialog yesterday after a recent upgrade, everything was "as usual". I think something went badly wrong here (in code?).

Here's a screenshot to further push this topic:
![lxqt-hotkey-config-empty](https://cloud.githubusercontent.com/assets/440517/8692938/6d025bbe-2ad3-11e5-99eb-395722dd4fe5.png)

**Comment by pmattern** [comment]
Confirmed.

Tests on Arch Linux running all LXQt components except lxqt-globalkeys from recent Git checkout compiled against Qt 5.5.0 suggest it's a regression introduced in lxde/lxqt-globalkeys@40c1559.

**Comment by luis-pereira** [comment]
There's an proposed fix [here] (https://github.com/lxde/lxqt-globalkeys/pull/20)

@pmattern Thanks for the bisection. It helped a lot. 
@antis81 Thanks for the report. Next time try to follow the guidelines @pmattern stated. It helps.
