### ISSUE TITLE
lxqt-runner: VBOXRUNNER_HEADLESS option dependency and default value

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#753]
I'm working on build system "cleanups".
Stumble on the [`VBOXRUNNER_HEADLESS`](https://github.com/lxde/lxqt-runner/blob/master/CMakeLists.txt#L126) _option_. 
Question:
* Is the _option _ a completely independent one ? Is it independent from [`RUNNER_VBOX`](https://github.com/lxde/lxqt-runner/blob/master/CMakeLists.txt#L122) ?
* What should be `VBOXRUNNER_HEADLESS` default value ?

In the CMake code it is independent, but in the C++ code [here](https://github.com/lxde/lxqt-runner/blob/master/providers.cpp#L600) and [here](https://github.com/lxde/lxqt-runner/blob/master/providers.cpp#L616) it isn't. The C++ code is actually makes sense.

Code committed by @CaledoniaProject. Can you help ?

**Comment by CaledoniaProject** [comment]
Yes, VBOXRUNNER_HEADLESS depends on RUNNER_VBOX

VBOXRUNNER_HEADLESS should not be defined by default
