### ISSUE TITLE
lxqt-runner: missing menu icon

### ISSUE THREAD

**Issue by antis81** [lxde/lxqt#754]
When I started writing this issue yesterday, I noticed the effect was gone - waited for some time until it re-appeared - which is now. In `lxqt-runner` (Alt+F2) the icon for the menu (three horizontal lines) magically disappears.

system info:
```text
Base Distro:    Lubuntu 15.04 (Desktop, 64 bit)
LXQt version:  >0.9 development version from PPA
Hardware:       MacBook 2,1 (second VGA monitor)
```

Active Theme: `Ambiance` (tried also `Dark` - same behaviour)

Here's some visual help (with a nice red square marking the gap):
![lxqt-runner-no-menu-icon](https://cloud.githubusercontent.com/assets/440517/8741681/e7dc2d62-2c5c-11e5-8ead-f6040f9022d4.png)

**Comment by luis-pereira** [comment]
@antis81 which icon theme are you using ?

**Comment by antis81** [comment]
@luis-pereira external icon theme (MacOSY), but it should be ok in this case. Here's another screenshot with the normal appearance (which is currently - no reboot or anything !?).

![lxqt-runner-menu-normal](https://cloud.githubusercontent.com/assets/440517/8749495/37775294-2ca2-11e5-8d3b-827433d7e566.png)

Any ideas?

**Comment by luis-pereira** [comment]
@antis81 Some clues. Pls change to the oxygen icon theme and see what changes.

**Comment by jleclanche** [comment]
We should have a fallback for that icon regardless.

**Comment by antis81** [comment]
Switched to oxygen icon theme - appearance is ok (and icons in lxqt-runner are exactly the same). Not sure about the behaviour though. Btw. the icon theme I use is correctly called `MBuntu-OS-Y` from noobslab - a widely used one.

**Comment by luis-pereira** [comment]
@jleclanche We ship our icon with each theme. Only a cosmic ray would make it fail. The solution here is to not set any icon on the code and let qss do it's work. Code and qss are known to produce undefined results.

@antis81 You have to restart lxqt-runner to see the changes. There's an proposed fix [here](https://github.com/lxde/lxqt-runner/pull/27)

**Comment by antis81** [comment]
Turns out fine, thanks!
