### ISSUE TITLE
keyring for lxqt ?

### ISSUE THREAD

**Issue by haheute** [lxde/lxqt#756]
I am trying lxqt (coming from gnome), and filezilla does not ask for my ssh key password without gnome-keyring, i think. (So it doesn't connect to the server)

How can I achieve that lxqt asks for ssh-key password? 
Or, is there a keyring application for lxqt ? (if that would help)

**Comment by jleclanche** [comment]
You can install `lxqt-openssh-askpass` for an ssh askpass dialog.

We don't have a keyring module yet though.

**Comment by haheute** [comment]
Ok. Thank you. I  have installed everything in the `lxqt` group and `lxqt-openssh-askpass` is installed. Are there problems known with filezilla ? I don't know where to search the error.

**Comment by pmattern** [comment]
First just to avoid misunderstandings: we're talking about establishing an SFTP connection via public key authentication and the local key is protected by a password, right?

Your question got me curious so I had a look at FileZilla 3.12.0.2 on Arch Linux.
Trying to configure the SFTP session at Settings - Connection - SFTP I ended up with
![filezilla_public-key-auth_message-about-keys](https://cloud.githubusercontent.com/assets/9860801/8787161/dc6482a8-2f32-11e5-893b-99a0c6e849a0.png)
so FileZilla doesn't seem to support password-protected keys itself but only with the help of tools like GNOME keyring. A counterpart of the latter indeed doesn't exist on LXQt yet, there's just some non-official [project](https://github.com/mhogomchungu/lxqt_wallet) by a GitHub user for now.

Note that PCManFM-Qt does support SFTP via GVFS, though.
There are still some rough edges but it's definitely usable both with password and public key authentication.

**Comment by haheute** [comment]
ok. thank you. will try pcmanfm-qt then
