### ISSUE TITLE
lxqt-sudo: How to install?

### ISSUE THREAD

**Issue by antis81** [lxde/lxqt#760]
I cannot find an APT package for `lxqt-sudo` on debian (Lubuntu) and the command does not exist on my system. Is that work in progress? Is lxqt-sudo part of some other package (e.g. `lxqt-session` or something)? How do I add it?

System:
```text
Ditro:    Lubuntu 15.04
LXQt:     0.9 dev. verson from lubuntu-daily ppa
```

**Comment by jleclanche** [comment]
lxqt-sudo hasn't had an official release yet.

**Comment by jleclanche** [comment]
We're planning for a full release in the next couple of months, so it should come along with that.

**Comment by palinek** [comment]
Note: there is a debian package in [siduction repository](http://packages.siduction.org/?Repositories:lxqt_amd64)

**Comment by antis81** [comment]
I'll happily wait for official release (or maybe compile it here). Thanks.
