### ISSUE TITLE
Add shutdown/suspend buttons by default

### ISSUE THREAD

**Issue by Atalanttore** [lxde/lxqt#763]
Hi,

there are no shutdown and suspend buttons after a fresh installation by default. This could be a big problem for beginners.

Regards,
Ettore

**Comment by palinek** [comment]
What OS are you running and did you install LXQt?

**Comment by Atalanttore** [comment]
I run Kubuntu 15.04 (64 bit) and installed LXQt 0.9 from the PPA ppa:lubuntu-dev/lubuntu-daily

**Comment by pmattern** [comment]
It's pretty likely you're missing package `lxqt-leave` that was split from `lxqt-session` in this PPA for whatever reason.
Details of this recurring problem can be found in #653.

**Comment by Atalanttore** [comment]
Installing the package lxqt-leave solved the problem for me.
