### ISSUE TITLE
Improve (panel) plugin translation loading

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#766]
There's situations where the translations aren't loaded.
Example [here](https://github.com/lxde/lxqt-panel/pull/228)

Already found a nice way to do it. Just polishing it so it will integrate nicely with a new buildsystem plugin that I have in mind.

**Comment by ThomasVie** [comment]
There are some more examples where the translation is available but it is not displayed:
- Tooltip of "Show desktop", "Removable media manager"
- Context menu of quicklaunch icons ("move left / right", "Remove from quicklaunch")

**Comment by luis-pereira** [comment]
@ThomasVie I will take a look at it.... after the holidays
