### ISSUE TITLE
Impossible select single icon if other icons are too near

### ISSUE THREAD

**Issue by hifi25nl** [lxde/lxqt#768]
Impossible select single icon if other icons are too near. If I click on an icon surrounded by other icons all are selected instead of the single one. Both with standard pcmanfm-qt and pcmanfm-qt git.

**Comment by pmattern** [comment]
Valid issue. Regarding the code in question probably related to lxde/pcmanfm-qt#97, btw.

**Comment by bibo01** [comment]
+1 on this issue

**Comment by pmattern** [comment]
FWIW a workaround is to click the icon that was intended to get selected again when it's part of a group of selected icons.

**Comment by hifi25nl** [comment]
Some news? i think this bug is very annoying, and maybe should have high priority.

**Comment by paulolieuthier** [comment]
Agreed.

**Comment by paulolieuthier** [comment]
@PCMan can you take a look at this one?

**Comment by jleclanche** [comment]
Unless someone tells me this can be easily fixed, I'm going to start the release process today.

**Comment by hifi25nl** [comment]
It would be not advisable to release Lxqt with such a bug.

**Comment by jleclanche** [comment]
@hifi25nl I don't believe this is a regression, so it's in 0.9 as well. Releasing 0.10 with the bug would make no difference.

I think we will do a 0.9.1 release on select components though, so this could be fixed then. I don't want to rush a bugfix and have something worse crop up because we didn't look close enough.

**Comment by tsujan** [comment]
This simple commit fixes the issue for me:

https://github.com/tsujan/pcmanfm-qt/commit/26a9a754e67602490fddc2e3c69bfdad7efa98f2

Please test it before I make a PR!

**Comment by paulolieuthier** [comment]
@tsujan that's great news. Make the PR and we test, comment and discuss.

**Comment by pmattern** [comment]
@hifi25nl 
This should be fixed in latest VCS code. Could you please verify? Also the discussion in lxde/pcmanfm-qt#252.

**Comment by palinek** [comment]
Isn't this one already fixed?

**Comment by stefonarch** [comment]
For me yes

Il 06/01/2016 00:10, palinek ha scritto:

**Comment by pmattern** [comment]
Problem was indeed solved by lxde/pcmanfm-qt#252.
