### ISSUE TITLE
Error when opening system settings

### ISSUE THREAD

**Issue by Atalanttore** [lxde/lxqt#769]
Hi,

I wanted to open the system settings of LXQt due to bug #764, but this always causes the following (german) error message.

![lxqt_systemeinstellungen](https://cloud.githubusercontent.com/assets/628474/9026546/ed137cc6-3932-11e5-8219-99fec257e598.png)

Regards,
Ettore

**Comment by pmattern** [comment]
The screenshot is displaying the window of *KDE's* system settings which don't work on LXQt.
The counterpart of LXQt is called "Configuration Center" ("Konfigurationszentrum" in German for now), the corresponding binary is `lxqt-config`.
You can always get English output by using environment variable LANG, e. g. `LANG=C lxqt-config`.

**Comment by Atalanttore** [comment]
Okay. I've clicked the system settings, because it has an entry in the application menu.

**Comment by pmattern** [comment]
> I've clicked the system settings, because it has an entry in the application menu.

This is due to #582. Without that bug KDE's System settings would show up as 'KDE System Settings' *only* in all desktop environments except KDE itself.
Note that in recent versions all configuration tools belonging to LXQt are summarized in Application menu - Preferences - LXQt settings.

**Comment by Atalanttore** [comment]
> and has basically nothing to do with #764 .

I wanted to change something and see (or rather hear) if it solves the problem.
