### ISSUE TITLE
KDE 5 doesn't work anymore

### ISSUE THREAD

**Issue by Atalanttore** [lxde/lxqt#772]
Hi,

KDE 5 installed next to LXQt doesn't work anymore. The KDE desktop just shows a black background with a bright bar at the bottom side of the monitor screen.

syslog:
*[clipped]*

Regards,
Ettore

**Comment by pmattern** [comment]
KDE and LXQt are coexisting without any issue here (Arch Linux, Plasma 5 from the official repositories, LXQt from VCS checkouts / AUR).
So this is obviously a downstream issue.
Assuming that your findings are on Kubuntu running LXQt from PPA ppa:lubuntu-dev/lubuntu-daily (which you again didn't state, unfortunately) you may want to have a look at `/var/log/apt/{term,history}.log` or one of the gzipped archives. It's pretty likely that installing LXQt removed packages needed by KDE.
