### ISSUE TITLE
Filename changes in file properties dialog are not applied

### ISSUE THREAD

**Issue by Atalanttore** [lxde/lxqt#773]
Hi,

changes to the name of a file on the desktop via the file properties dialog are not applied after clicking "OK".

Regards,
Ettore

**Comment by pmattern** [comment]
Confirmed running latest Git code on Arch Linux.
Changes don't seem to get applied at all as can be seen by opening the preferences dialog another time.

**Comment by pmattern** [comment]
Roughly the same issue was reported in lxde/pcmanfm-qt#324 so one of the two needs to get closed.
Choosing this one besides it was opened first as a similar other one exists in the dedicated tracker of PCManFM-Qt so as to avoid clutter.
