### ISSUE TITLE
Suspend does not lock the screen

### ISSUE THREAD

**Issue by jjvattamattom** [lxde/lxqt#775]
I use suspend when I leave for the day. When I turn it on, it loads the session unlocked. I expect that when I resume from suspend, I am asked for my password.

I use 0.9 with Kubuntu 15.04

**Comment by pmattern** [comment]
Could you just elaborate how exactly LXQt was installed? (Asking as PPA ppa:lubuntu-dev/lubuntu-daily is tagging VCS packages as "0.9-foo" thus "0.9" stated above could eventually be misleading.)

**Comment by jjvattamattom** [comment]
I have installed it like:
 
sudo add-apt-repository -y ppa:lubuntu-dev/lubuntu-daily
sudo apt-get install lxqt-metapackage lxqt-panel openbox
Source: http://linoxide.com/ubuntu-how-to/install-lxqt-desktop-ubuntu/

Here are excerpts of package details:

$ dpkg -s lxqt-metapackage
Version: 0.0.1+bzr60+201508012301~ubuntu15.04.1
$ dpkg -s lxqt-panel
Version: 0.9.0.0.0+bzr972+201508032131~ubuntu15.04.1
Depends: libasound2 (>= 1.0.16), libc6 (>= 2.14), libdbusmenu-qt5, libglib2.0-0 (>= 2.12.0), libkf5solid5 (>= 4.97.0), libkf5windowsystem5 (>= 5.6.0+git20150112.0023+15.04), liblxqt0, libmenu-cache3, libpulse0 (>= 0.99.1), libqt5core5a (>= 5.4.0), libqt5dbus5 (>= 5.0.2), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5widgets5 (>= 5.2.0), libqt5x11extras5 (>= 5.1.0), libqt5xdg1, libqt5xml5 (>= 5.0.2), libstatgrab9, libstdc++6 (>= 4.1.1), libsysstat-qt5-0, libx11-6, libxcb-xkb1, libxcb1, libxcomposite1 (>= 1:0.3-1), libxdamage1 (>= 1:1.1), libxkbcommon-x11-0 (>= 0.4.0), libxkbcommon0 (>= 0.2.0), libxrender1, lxqt-globalkeys
$ dpkg -s lxqt-common
Version: 0.9.1.0.0+bzr116+201507210101~ubuntu15.04.1

**Comment by mid-kid** [comment]
I wrote a [small patch](https://github.com/mid-kid/config/blob/master/patches/liblxqt-0.9.0-lock-screen-on-suspend-and-hybernate.patch) for personal use that does exactly that.
That said, I can't into C++, so it "just werks for me".

**Comment by paulolieuthier** [comment]
@mid-kid don't you send us a pull request to get credits for the fix? You can use git's format-patch command if you don't want to fork on Github.

**Comment by mid-kid** [comment]
It was just a quick fix for myself. I don't even know if it's the proper way to fix it.
But okay, I'll file a pull request soon. I guess it can be discussed there if need be.

**Comment by RalfJung** [comment]
This is still an issue with LXQt 0.10: The usual behavior of systems on suspend (default e.g. on KDE, Cinnamon, Windows) is that they come back up with the screen locked. This is important to prevent unauthorized access to the machine. LXQt should do the same.

**Comment by RalfJung** [comment]
There is no screen lock when I close the lid or select "Suspend" in the menu even if I enable screen locking in the screen saver configuration. (Which does not seem to be the default...?)

**Comment by RalfJung** [comment]
I now learned that I can use xss-lock <https://wiki.archlinux.org/index.php/Power_management#xss-lock> to automatically lock the screen on suspend, by adding this to the autostarts:
`xss-lock -- xdg-screensaver lock`

Now I wonder - do you expect distributions to do this? Should I report a bug in Debian to add xss-lock to the dependencies and to add such an autostart entry? Or would you rather do this in LXQt upstream?

**Comment by paulolieuthier** [comment]
@RalfJung xss-lock is a nice tool, but it's LXQt's responsability to at least offer this option. See the referenced PR.
