### ISSUE TITLE
screen freezes on resume after suspending

### ISSUE THREAD

**Issue by antis81** [lxde/lxqt#787]
Not sure, if this bug is related to LXQt or low-level, but a really annoying one for laptop users with changing environment.

Following happens:
:heavy_check_mark: Step 1: Close laptop lid -> laptop goes to `suspend` mode (not hibernate)
:x: Step 2: Open laptop lid -> backlight goes on :bulb:, but screen "freezes" (no mouse movement, keyboard, etc.). Results in hard switch off and reboot.

System info:

Component | Version
---- | ----
Hardware | Macbook 2,1 (late 2007, plastic)
Distro | Lubuntu 15.04 (Linux kernel 3.19-26)
LXQt | >0.9 from lubuntu-daily ppa

**Comment by paulolieuthier** [comment]
You should try a newer kernel.

**Comment by antis81** [comment]
@paulolieuthier I'll try with current 4.1 kernel and report back. Though in my productive environment I decided to stick with the official kernel (3.19 for Lubuntu >= 14.04 LTS).

**Comment by paulolieuthier** [comment]
You're actually a recent kernel. But you should try a newer one to see if it fixes it. Anyway, it indeed does not look like it's related to LXQt. I'd suggest playing with systemd/upower.

**Comment by antis81** [comment]
Unfortunately I'm currently a bit short on time and investigation will probably eat a day or two. I'm pretty sure this works with a 4.1 kernel - tried it about a month ago.

**Comment by Esclapion** [comment]
4.1 will be a "true" LTS. 3.19 already disappeared in kernel.org.

**Comment by jleclanche** [comment]
I'm closing this because there's no way LXQt is at fault. Likely kernel, yeah.

**Comment by antis81** [comment]
Yep, thanks.
