### ISSUE TITLE
computer hangs on shutdown

### ISSUE THREAD

**Issue by antis81** [lxde/lxqt#788]
This issue might be related to issue #787 and (once more), not sure if an LXQt bug. When I want to power off (shutdown) my computer, all processes seem to be stopped ok, but finally it stalls (freezes) and I have to force power off almost each single time.

Not a single clue why, but once in a while it works like it should -> system powers off. Maybe due to a previous `apt-get upgrade` ...

There's an error message, telling that something's wrong with the `D-Bus`. If you tell me, where to find, I can provide the crash report or kernel dump. 

System is the same like in above mentioned issue:

Component | Version
---- | ----
Hardware | Macbook 2,1 (late 2007, plastic)
Distro | Lubuntu 15.04 (Linux kernel 3.19-26)
LXQt | >0.9 from lubuntu-daily ppa

**Comment by jleclanche** [comment]
Track this in #787, I don't think it could be an lxqt issue.
