### ISSUE TITLE
How to increase the size of the lxqt menu icons ?

### ISSUE THREAD

**Issue by Esclapion** [lxde/lxqt#790]
I tried with .gtkrc-2.0.mine, but it's ineffective...

**Comment by palinek** [comment]
Are you talking about `Application menu` plugin/widget in panel?

**Comment by Esclapion** [comment]
yes. The icons who appears when you click on Menu. I can change the font size with a right-click on that, but it serves to nothing if the icons don't follow.
May be I miss something ?

**Comment by palinek** [comment]
AFAIK you don't miss anything... it's not configurable.

**Comment by Esclapion** [comment]
They are a little bit small. 24x24 would be probably better

**Comment by palinek** [comment]
@Esclapion, please, try the lxde/lxqt-panel#235 ...

Note: currently the theme stylesheet for QMenu conflicts with bigger icons than 30 px:
```css
QMenu::item {
    color: #DEDEDE;
    padding: 5px 13px 5px 30px;
}
```

**Comment by Esclapion** [comment]
Difficult for me, I use the Arch binary packages.

**Comment by pmattern** [comment]
Just had a look on Arch i686: works exactly as expected.

**Comment by Esclapion** [comment]
If I understand the modification, the icons size will now follow the font size ? If yes, nice :-)

**Comment by pmattern** [comment]
> If I understand the modification

You do.

**Comment by Esclapion** [comment]
I tried the modification, but I have too old sources, and a thing is missing 

/home/pat/repoarch/lxqt-panel/src/lxqt-panel-0.9.0/plugin-mainmenu/lxqtmainmenu.cpp:290:40: erreur: ‘menuFont’ was not declared in this scope

**Comment by palinek** [comment]
> I tried the modification, but I have too old sources, and a thing is missing

Now that the change is in master, you can try it with the arch's git package...not?

**Comment by Esclapion** [comment]
With the git's, yes. But for the moment, I use stable packages to produce my manjaro ISOs.

A problem is that the git is too far of the Arch stable version, now... :-(

**Comment by palinek** [comment]
> With the git's, yes. But for the moment, I use stable packages to produce my manjaro ISOs.
A problem is that the git is too far of the Arch stable version, now... :-(

If you wish, you can try to modify the source manualy based on following diff:
plugin-mainmenu/lxqtmainmenu.cpp
```diff
@@ -240,6 +225,8 @@ void LxQtMainMenu::settingsChanged()
     }
     mShortcutSeq = QKeySequence(shortcut);
 
+    setMenuFontSize();
+
     realign();
 }

@@ -266,17 +253,36 @@ void LxQtMainMenu::buildMenu()
     }
 
     menu->installEventFilter(this);
 
     QMenu *oldMenu = mMenu;
     mMenu = menu;
     if(oldMenu)
         delete oldMenu;
 
+    setMenuFontSize();
+}
+
+/************************************************
+
+ ************************************************/
+void LxQtMainMenu::setMenuFontSize()
+{
+    if (!mMenu)
+        return;
+
+    QFont menuFont = mButton.font();
     if(settings()->value("customFont", false).toBool())
     {
-        QFont menuFont = mMenu->font();
+        menuFont = mMenu->font();
         menuFont.setPointSize(settings()->value("customFontSize").toInt());
+    }
 
+    if (mMenu->font() != menuFont)
+    {
         mMenu->setFont(menuFont);
         QList<QMenu*> subMenuList = mMenu->findChildren<QMenu*>();
         foreach (QMenu* subMenu, subMenuList)
@@ -284,6 +290,9 @@ void LxQtMainMenu::buildMenu()
             subMenu->setFont(menuFont);
         }
     }
+
+    //icon size the same as the font height
+    mTopMenuStyle.setIconSize(QFontMetrics(menuFont).height());
 }
```
plugin-mainmenu/lxqtmainmenu.cpp
```diff
@@ -78,12 +78,14 @@ protected:
     bool eventFilter(QObject *obj, QEvent *event);
 
 private:
+    void setMenuFontSize();
+
+private:
     QToolButton mButton;
     QString mLogDir;
     QMenu* mMenu;
```

**Comment by tsujan** [comment]
I added an *experimental* hacking option to Kvantum Manager for this when the main menu is **NOT** styled by LXQT (no `#MainMenu  QMenu` in the theme and no custom font). In this screenshot, its value is set to 32 (max.):

![2016-04-08-14 11 09-scrot](https://cloud.githubusercontent.com/assets/981076/14384728/d49ed2f0-fdb1-11e5-8eac-b99d98a0b93e.png)

Hopefully, future versions of the main menu will provide a better way of its identification.

**Comment by Esclapion** [comment]
The current system works well, btw.

**Comment by tsujan** [comment]
> The current system works well, btw.

The current lxqt-panel code makes the icon size depend on the font size; hence the hack.
