### ISSUE TITLE
Newly created file is always placed in the top left side

### ISSUE THREAD

**Issue by Atalanttore** [lxde/lxqt#791]
Hi,

a newly created file on the desktop is always placed in the top left side even if there is already another file placed at this position.

Regards,
Ettore

**Comment by pmattern** [comment]
Confirmed running VCS checkout of 2015-08-21 on Arch Linux i686 or x86_64.

Not 100% reproducible, though.
Sometimes new icons get placed overlapping with existing ones which doesn't necessarily affect the top-left corner of a display, sometimes the new icon is placed reasonably at the top-left position that's available / not occupied yet.
Failed to figure out the exact conditions of the different behaviour so far.

Probably related to #768 and lxde/pcmanfm-qt#97.

**Comment by Atalanttore** [comment]
Here is the screenshot:

![desktop](https://cloud.githubusercontent.com/assets/628474/9447493/f3e81c98-4a97-11e5-80e2-ba304959a916.png)

**Comment by pmattern** [comment]
IMO this was among several other problems fixed in the wake of lxde/pcmanfm-qt#252, too.

@Atalanttore 
Any chance you can verify by running a recent checkout of PCManFM-Qt and the spin-off libfm-qt which took place in the meantime?

**Comment by tsujan** [comment]
Closed by https://github.com/lxde/pcmanfm-qt/pull/252.

**Comment by Atalanttore** [comment]
@pmattern 
I didn't see this problem for over a month. It seems to be fixed.

**Comment by pmattern** [comment]
@Atalanttore 
Alright then. Please drop another note should you run into this once more.
