### ISSUE TITLE
lxqt-sudo should not have a .desktop file and maybe shorter name

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#794]
It ends up under "other" as "GUI sudo" and produces only an error "no command provided".
Alternatively  could   provide a dialog for the comand to run, saying "running application as admin" or so.

As usually it gets invoked only  in terminal windows I find the name to long to type, even using TAB.
 Personally I created a symlink /usr/bin/qtsu

**Comment by pmattern** [comment]
The desktop entry file is indeed useless but was removed in lxde/lxqt-sudo@7679457 three months ago.

The name was criticised in lxde/lxqt-sudo#1 already, not only regarding the length but also because of the fact it suggests 'sudo' is the only backend supported which is about to be changed by now, see lxde/lxqt-sudo#7.
IMO all those arguments still apply and it would make a lot of sense to discuss the name once more, in particular before the first official release is made.

**Comment by stefonarch** [comment]
In fact I see my lxqt-sudo.desktop file is old, from June.
The name should be similar to gksu and  kdesu IMO.

**Comment by palinek** [comment]
@pmattern, @paulolieuthier, @jleclanche, @luis-pereira, @PCMan do we want/need a better name for lxqt-sudo?...what are your proposals?

**Comment by paulolieuthier** [comment]
Yes, I'd like to see a shorter name, and "su" instead of "sudo" would be a plus as well. But this is not a big deal, just my preferences. I'm not very creative, but I think lxqtsu is easier and faster to type. What do you think?

**Comment by jleclanche** [comment]
@palinek @paulolieuthier Sorry for the late response.

I think `lxsu` would be a fine name for the binary. Failing that, lxqt-sudo is fine.

**Comment by Vladimir-csp** [comment]
+1 for lxsu.
Sooner or later 'qt' part would become irrelevant anyway.

**Comment by paulolieuthier** [comment]
Makes sense.

**Comment by palinek** [comment]
I personaly like that (mostly) every LXQt component (package name in distribution) does follow the `lxqt-*` pattern. How about leaving the component name as is `lxqt-sudo` but adding a symbolic link for executable lxsu -> lxqt-sudo?

**Comment by jleclanche** [comment]
I'm fine with that.

**Comment by palinek** [comment]
... see lxde/lxqt-sudo#12

**Comment by pmattern** [comment]
On the one hand su [is about](https://github.com/lxde/lxqt-sudo/pull/7) to get another backend of the binary, on the other hand implementing lxde/lxqt-sudo#12 would mean that both `lxqt-sudo` and `lxsu` have the same functionality besides comprising "sudo" and "su" respectively in their name.
Doesn't this give rise to confusion?

(Personally I don't think a shorter name is needed at all. We all got tab completion on our shells, don't we?)

**Comment by jleclanche** [comment]
This is not about "having a shorter name" as much as it is having a name that falls in line with the kdesu/gksu naming.

**Comment by pmattern** [comment]
> This is not about "having a shorter name"

You did read the title, the first comment of the thread and the first of paulolieuthier?

**Comment by jleclanche** [comment]
Yes, I'm well aware - and I disagree that that's the main reason we're doing this.

**Comment by Vladimir-csp** [comment]
Side note: gksu uses su (by default), but it has a symlink gksudo -> gksu. If run via this symlink, ($0=gksudo) it switches to sudo.

Maybe, replicating this behavior would prevent ambiguity, ship like this:
- lxqt-elevate (binary with generic name, configurable backend)
- lxsu -> lxqt-su (symlink, always runs su)
- lxsudo -> lxqt-su (symlink, always runs sudo)

**Comment by pmattern** [comment]
@Vladimir-csp
Pretty good ideas, IMO. Everything.
→ Generic name for the binary itself isn't and will never be misleading with regards to the backends in use.
→ Stating the backends names in symlinks only provides a clear and easy way to pick a distinct backend. Short as well (besides I personally don't care about that). CLI options of binary itself to pick one could of course be preserved nevertheless.

**Comment by palinek** [comment]
The lxde/lxqt-sudo#12 implements the "3-way backend logic":
- if invoked by `lxqt-sudo` -> no backend is selected and the user must choose `--su` or `--sudo` option
- if invoked by `lxsu` -> `su` backend is default (but the user can change it by using `--sudo` option)
- if invoked by `lxsudo` -> `sudo` backend is default (but the user can change it by using `--su` option)

**Comment by jleclanche** [comment]
@palinek why is that needed?

**Comment by palinek** [comment]
That's just implementation of what was proposed in this thread...

**Comment by jleclanche** [comment]
@palinek There's nobody saying we *want* such an implementation, only @Vladimir-csp noting that gnome has it.

I suppose it doesn't hurt, but I'm never a fan of adding in things we don't need just because some other DE is doing it.

**Comment by palinek** [comment]
> This is not about "having a shorter name" as much as it is having a name that falls in line with the kdesu/gksu naming.

...


> I suppose it doesn't hurt, but I'm never a fan of adding in things we don't need just because some other DE is doing it.

Well, then do we want to be in a line with others or don't we? I personaly don't care for the shorter name, but when doing it the @Vladimir-csp's proposal seem very reasonable to me. But I can revert it happily.

Let's settle this now (and for ever :) ). Do we want
- `lxsu` (default backend su), `lxsudo` (default backend sudo) and `lxqt-sudo` (no default backend)?
- `lxsu` (default backend sudo) and `lxqt-sudo` (default backend sudo) ?
- `lxsu` (default backend sudo) -> renaming the whole package?
- anything else?

**Comment by pmattern** [comment]
The primary motiviation of Vladimir-csp's proposal was *not* to just copy the behaviour of other DEs. Rather, it was about banning both "su" and "sudo" from the binary's name so as to avoid suggesting the binary is only providing one of these. This was a proposal I hade made not only with regards to those two backends but also to the idea that others like pkexec could eventually get added in the future.
Adding those links `lxdu` and `lxsudo` was just a second step to provide an easy access to those distinct backends which as side affect provides short names that have been wished several times as well (not by me).

**Comment by Vladimir-csp** [comment]
It was never my intention to suggest copying anything from Gnome. Links are just perfect for solving ambiguity, and such solution happens to be implemented for similar tool in Gnome, that's it. I proposed an expanded variant with lxqt-elevate generic binary, so anything could fit in cleanly.

**Comment by jleclanche** [comment]
@palinek fair point, but there's a difference between a technical detail and a user-facing detail. User expectations matter.

I also happen to agree with @Vladimir-csp in that having `sudo` in the name suggests something that isn't necessarily true. However, the name needs to also be short to type, so I stand by my previous statement: `lxsu` would be a fine binary name. Failing that, keeping `lxqt-sudo` is also fine. This isn't as big an issue as we're making it to be.

**Comment by palinek** [comment]
> I also happen to agree with @Vladimir-csp in that having sudo in the name suggests something that isn't necessarily true. However, the name needs to also be short to type, so I stand by my previous statement: lxsu would be a fine binary name. Failing that, keeping lxqt-sudo is also fine. This isn't as big an issue as we're making it to be.

This is too vague for me. Please, say it clearly: "... do it this way..." and I'll make it.

**Comment by jleclanche** [comment]
I'd normally let discussion run its course but for the sake of moving on with this issue then yes, please update your PR to link to have an `lxsu` symlink and don't bother with binary name calls to specific backends.

**Comment by Vladimir-csp** [comment]
Is generalizing the whole component name out of question (lxqt-elevate)?
IMHO, that would make the logic perfect: universal extensible privilege elevation tool.
Since the component is still in development phase, such change should happen now or never.

**Comment by paulolieuthier** [comment]
@Vladimir-csp that would fit well, of couse, but it's not necessary. I agree with @jleclanche here.

**Comment by jleclanche** [comment]
The name doesn't need to be "generic", and `lxqt-elevate` gets a -1 from me.
