### ISSUE TITLE
lightdm lxqt greeter

### ISSUE THREAD

**Issue by zjes** [lxde/lxqt#795]
This is not a issue.
I have a qt5 greeter (but without liblightdm-qt dependency) for lxqt, with lxqt theming support. This is just first functional version (without configuration tool). I know you are prefer sddm, but this sddm is not enough for my conditions, i prefer lightdm and without qml.  :) Old lxqt greeter was moved out from lxqt tree. I suggest another one.
Code is here: https://github.com/zjes/lightdm-lxqt-greeter
If you interesting this tool, i will continue develop, otherwise will continue using for myself.

Biodiversity - is base of evolution. :)

**Comment by surlykke** [comment]
2015-08-25 10:28 GMT+02:00 zjes <notifications@github.com>:

> This is not a issue.
> I have a qt5 greeter (but without liblightdm-qt dependency) for lxqt, with
> lxqt theming support. This is just first functional version (without
> configuration tool). I know you are prefer sddm, but this sddm is not
> enough for my conditions, i prefer lightdm and without qml. :)
> Code is here: https://github.com/zjes/lightdm-lxqt-greeter
> If you interesting this tool, i will continue develop, otherwise will
> continue using for myself.
>
> Biodiversity - is base of evolution. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/795>.
>

Actually there *is* a lightdm greeter for LXQt:
https://github.com/surlykke/lxqt-lightdm-greeter . It used to be part of
LXQt and previously Razor. But since everybody seems to use sddm, it is no
longer part of the project. I still maintain it and use it myself, though.
You can have a look at that if you wish. (It *does* depend on
liblightdm-qt.)

br. Chr.

**Comment by fguzm** [comment]
"..since everybody seems to use sddm.."
Have you seen the dependencies of sddm?
I use lightdm.

**Comment by zjes** [comment]
@surlykke lets try to merge code (features) to one project? :)

**Comment by surlykke** [comment]
2015-08-26 8:54 GMT+02:00 zjes <notifications@github.com>:

> @surlykke <https://github.com/surlykke> lets try to merge code (features)
> to one project? :)
>
> Well TBH. lxqt-lightdm-greeter + lightdm does all I need from a display
manager, so it's not a priority for me to add new functionality. I'll
handle bug reports (but they are rare), but I'm not doing active
development on it.

br. Chr.

**Comment by paiiou** [comment]
I see another reason to use lightdm. sddm does not support computers that that do not support sse2 and more. 
Yes, he left! 
So if the version of lightdm not requires sse2, yes it's a additional reason to continue.

**Comment by Esclapion** [comment]
I tried both, and never problem with sddm. I looked at the size of both in my environment, and sddm was not heavier, if we count all dependencies.

**Comment by paiiou** [comment]
@ escaplion Have you essay sddm on a computer that does not have the support sse2?

**Comment by Esclapion** [comment]
I have a 6 years old computer. I looked now, it supports SSE4.2. To be honest, I don't know exactly what it means... :-)

**Comment by Esclapion** [comment]
"SSE2, Streaming SIMD Extensions 2, is one of the Intel SIMD (Single Instruction, Multiple Data) processor supplementary instruction sets first introduced by Intel with the initial version of the Pentium 4 in 2001"

Your PC is older, or it's not an Intel ?

**Comment by paiiou** [comment]
Yes it an ordinosaure > 10 years. I use it only for backup.
It use a AMD processor, only sse, not sse2 and above

**Comment by jleclanche** [comment]
We officially only support sddm now. If your computer doesn't support it, SLiM is probably your next best bet.
