### ISSUE TITLE
plugin-kbindicator: removal of translations

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#796]
lxde/lxqt-panel@3b9c7b9 which was one of the changes due to #735 removed all existing translations, only German has been re-added manually in the meantime.

Can't check whether this was eventually intentional right now but I think the other preexisting translations should be re-added as well if feasible.

Btw. problem has already been addressed in #735 but comment remained unanswered.

**Comment by paulolieuthier** [comment]
When we fix the issues of the current milestone, the string freeze period will begin and translators will come. I'll be fixed.

**Comment by pmattern** [comment]
@paulolieuthier 
Could very well be that translators will come. But that way we'd urge them to start over while all the work they've done before and they put time into gets thrown into the trash can.
Not exactly kind behaviour, IMO.

On a side note the current mantra to basically wait for string freezes before really getting into translations doesn't make too much sense.
It's causing lots of superfluous work like [this PR](https://github.com/lxde/lxqt-panel/pull/249) and if we want to stop translators from doing updates like this manually as proposed [here](https://github.com/lxde/liblxqt/pull/46) we basically prevent them from doing work right now.
Different story, of course.

**Comment by paulolieuthier** [comment]
Yeah, I said that hoping the Pootle server would come back.

**Comment by palinek** [comment]
Readded remnants from pre lxde/lxqt-panel@3b9c7b9 days in lxde/lxqt-panel@995183b and lxde/translations@893a92c
