### ISSUE TITLE
[critical bug] - LXQt stopped working after recent upgrade

### ISSUE THREAD

**Issue by antis81** [lxde/lxqt#797]
This issue belongs to category: Things, that **must not** happen!

Currently writing from an openbox fallback session. Yesterday an upgrade for `liblxqt` arrived. After running `apt-get upgrade` as usual, all LXQt apps stopped working.

Sounds like a linking problem:
`lxqt-about: symbol lookup error: lxqt-about: undefined symbol: _ZTVN4LxQt11ApplicationE`

System:

Component | Version
---- | ----
Hardware | Macbook 2,1 (late 2007, plastic)
Distro | Lubuntu 15.04 (Linux kernel 3.19-26)
LXQt | >0.9 from lubuntu-daily ppa

**Comment by surlykke** [comment]
2015-08-30 8:48 GMT+02:00 Nils Fenner <notifications@github.com>:

> This issue belongs to category: Things, that *must not* happen!
>
> Currently writing from an openbox fallback session. Yesterday an upgrade
> for liblxqt arrived. After running apt-get upgrade as usual, all LXQt
> apps stopped working.
>
> Sounds like a linking problem:
> lxqt-about: symbol lookup error: lxqt-about: undefined symbol:
> _ZTVN4LxQt11ApplicationE
>
> You may need to run 'sudo ldconfig' .

br. Chr.

**Comment by antis81** [comment]
@surlykke Thanks, though ldconfig didn't work - same result. Looks like liblxqt (or other lib?) introduced an incompatible change, that every LXQt app requires to run. If I get this right, the only way is to update every LXQt app in the `lubuntu-daily` PPA to fix the problem.

**Comment by agaida** [comment]
Such things will happend - if one don't want this one should not use daily-ppas and go for proper distribution packages. It is really such a simple thing. We had a namespace fix that affects the most of the LXQt packages. Daily-PPA is bleeding edge, so nobody should be surprised if it break things. Closing this now with no further action.

PS: And yes, i know that most of the LXQt packages are not in the regular Ubuntu repositories. As a beginning libqtxdg and liblxqt are available for wily - and this will be the only trustworthy, maintained and tested packages available for Ubuntu right now. All other repos are more or less bleeding or cutting edge.

**Comment by antis81** [comment]
@agaida Looks like I hit a nerve eh - sorry. :)

Anyway, that doesn't solve the issue. Please reopen until things are back to usual.

**Comment by agaida** [comment]
no, i will not reopen this - but its really such simple - the daily builds grap the current development and build it - and if the resultig packages break things - they will break things :D - build the whole set of packages yesterday and have this running, no bad things happend. if you encounter problems after the next build its up to downstream, nothing the LXQt team can and will do
