### ISSUE TITLE
Login no longer works

### ISSUE THREAD

**Issue by Atalanttore** [lxde/lxqt#798]
Hi,

login to LxQt no longer works since some days. Login to LXDE still works properly.

syslog during login attempt:
<code>Aug 30 17:03:08 Notebook sddm-helper: pam_ecryptfs: pam_sm_authenticate: /home/nas is already mounted</code>
<code>Aug 30 17:03:08 Notebook systemd[1]: Started Session 6 of user A.</code>
<code>Aug 30 17:03:08 Notebook systemd[1]: Starting Session 6 of user A.</code>
<code>Aug 30 17:03:09 Notebook acpid: client 3664[0:0] has disconnected</code>
<code>Aug 30 17:03:09 Notebook acpid: client connected from 3881[0:0]</code>
<code>Aug 30 17:03:09 Notebook acpid: 1 client rule loaded</code>
<code>Aug 30 17:03:09 Notebook systemd[1]: Started Session 7 of user sddm.</code>
<code>Aug 30 17:03:09 Notebook systemd[1]: Starting Session 7 of user sddm.</code>

What could be the reason for this problem?

Regards,
Ettore

**Comment by pmattern** [comment]
Distro? LXQt version and way it was installed?
Please state this informations in *every* issue you open. We can't memorise the systems of all users posting on this tracker.

**Comment by rogerfranz** [comment]
I have the same issue. Login does not work.

What was updated between logins is (from the apt log):

`Start-Date: 2015-08-29  17:22:46
Commandline: /usr/sbin/synaptic
Install: oggz-tools:amd64 (1.1.1-3, automatic), libkate-tools:amd64 (0.4.1-4), libffms2-3:amd64 (2.20-1build1, automatic), performous-tools:amd64 (1.0-2), python-pykaraoke:amd64 (0.7.5-1.1, automatic), pykaraoke:amd64 (0.7.5-1.1), aegisub:amd64 (3.1.2-1build1), pykaraoke-bin:amd64 (0.7.5-1.1, automatic), performous:amd64 (1.0-2), karlyriceditor:amd64 (1.11-1), performous-dbg:amd64 (1.0-2), liboggz2:amd64 (1.1.1-3, automatic), python-pythoncard:amd64 (0.8.2-5, automatic)
Upgrade: liblxqt-data:amd64 (0.9.0+bzr324+201508280516~ubuntu15.04.1, 0.9.0+bzr325+201508291716~ubuntu15.04.1), libfm-qt5-data:amd64 (0.9.0+bzr351+201508271632~ubuntu15.04.1, 0.9.0+bzr352+201508282231~ubuntu15.04.1), liblxqt0:amd64 (0.9.0+bzr324+201508280516~ubuntu15.04.1, 0.9.0+bzr325+201508291716~ubuntu15.04.1), pcmanfm-qt:amd64 (0.9.0+bzr351+201508271632~ubuntu15.04.1, 0.9.0+bzr352+201508282231~ubuntu15.04.1), lxqt-panel:amd64 (0.9.0.0.0+bzr982+201508260116~ubuntu15.04.1, 0.9.0.0.0+bzr983+201508291317~ubuntu15.04.1), libfm-qt5-2:amd64 (0.9.0+bzr351+201508271632~ubuntu15.04.1, 0.9.0+bzr352+201508282231~ubuntu15.04.1)
End-Date: 2015-08-29  17:23:41`

Here's a portion of syslog:

`Aug 30 10:15:28 firefly lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
Aug 30 10:15:28 firefly lightdm: PAM adding faulty module: pam_gnome_keyring.so
Aug 30 10:15:28 firefly lightdm: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open shared object file: No such file or directory
Aug 30 10:15:28 firefly lightdm: PAM adding faulty module: pam_kwallet.so
Aug 30 10:15:28 firefly lightdm: pam_unix(lightdm-greeter:session): session opened for user lightdm by (uid=0)
Aug 30 10:15:28 firefly systemd-logind[751]: New session c1 of user lightdm.
Aug 30 10:15:28 firefly systemd: pam_unix(systemd-user:session): session opened for user lightdm by (uid=0)
Aug 30 10:15:30 firefly lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
Aug 30 10:15:30 firefly lightdm: PAM adding faulty module: pam_gnome_keyring.so
Aug 30 10:15:30 firefly lightdm: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open shared object file: No such file or directory
Aug 30 10:15:30 firefly lightdm: PAM adding faulty module: pam_kwallet.so
Aug 30 10:15:30 firefly lightdm: pam_succeed_if(lightdm:auth): requirement "user ingroup nopasswdlogin" not met by user "rwfranz"
Aug 30 10:15:42 firefly lightdm: pam_unix(lightdm-greeter:session): session closed for user lightdm
Aug 30 10:15:42 firefly lightdm: pam_unix(lightdm:session): session opened for user rwfranz by (uid=0)
Aug 30 10:15:42 firefly systemd-logind[751]: Removed session c1.
Aug 30 10:15:42 firefly systemd: pam_unix(systemd-user:session): session opened for user rwfranz by (uid=0)
Aug 30 10:15:42 firefly systemd: pam_unix(systemd-user:session): session closed for user lightdm
Aug 30 10:15:42 firefly systemd-logind[751]: New session c2 of user rwfranz.
Aug 30 10:15:46 firefly lightdm: pam_unix(lightdm:session): session closed for user rwfranz
Aug 30 10:15:47 firefly lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
Aug 30 10:15:47 firefly lightdm: PAM adding faulty module: pam_gnome_keyring.so
Aug 30 10:15:47 firefly lightdm: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open shared object file: No such file or directory
Aug 30 10:15:47 firefly lightdm: PAM adding faulty module: pam_kwallet.so
Aug 30 10:15:47 firefly lightdm: pam_unix(lightdm-greeter:session): session opened for user lightdm by (uid=0)
Aug 30 10:15:47 firefly systemd-logind[751]: New session c3 of user lightdm.
Aug 30 10:15:47 firefly systemd: pam_unix(systemd-user:session): session opened for user lightdm by (uid=0)
Aug 30 10:15:47 firefly lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
Aug 30 10:15:47 firefly lightdm: PAM adding faulty module: pam_gnome_keyring.so
Aug 30 10:15:47 firefly lightdm: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open shared object file: No such file or directory
Aug 30 10:15:47 firefly lightdm: PAM adding faulty module: pam_kwallet.so
Aug 30 10:15:47 firefly lightdm: pam_succeed_if(lightdm:auth): requirement "user ingroup nopasswdlogin" not met by user "rwfranz"
Aug 30 10:15:55 firefly systemd-logind[751]: Removed session c2.
Aug 30 10:15:55 firefly systemd: pam_unix(systemd-user:session): session closed for user rwfranz`

Versions (from dpkg-query):
`| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-================================================================================================
ii  lxqt-about                                    0.9.0+bzr42+201508072001~ub amd64                       lxqt-about

ii  lxqt-admin                                    0.9.0+bzr49+201508222246~ub amd64                       lxqt-admin

ii  lxqt-common                                   0.9.1.0.0+bzr116+2015072101 all                         lxqt-common

ii  lxqt-config                                   0.9.0.0.0+bzr319+2015082807 amd64                       lxqt-config

ii  lxqt-globalkeys                               0.9.0+bzr156+201508221346~u amd64                       lxqt-globalkeys

ii  lxqt-leave                                    0.9.0.0.1+bzr263+2015082610 amd64                       lxqt-leave

ii  lxqt-metapackage                              0.0.1+bzr60+201508012301~ub all                         lxqt-metapackage

ii  lxqt-notificationd                            0.9.0.0.0+bzr125+2015080819 amd64                       lxqt-notificationd

ii  lxqt-openssh-askpass                          0.9.0+bzr34+201508171946~ub amd64                       lxqt-openssh-askpass

ii  lxqt-panel                                    0.9.0.0.0+bzr983+2015082913 amd64                       lxqt-panel

ii  lxqt-policykit                                0.9.0+bzr42+201508222001~ub amd64                       lxqt-policykit

ii  lxqt-powermanagement                          0.9.0+bzr154+201508071932~u amd64                       lxqt-powermanagement

ii  lxqt-qtplugin                                 0.9.0+bzr32+201508182301~ub amd64                       lxqt-qtplugin

ii  lxqt-runner                                   0.9.0+bzr157+201508071931~u amd64                       lxqt-runner

ii  lxqt-session                                  0.9.0.0.1+bzr263+2015082610 amd64                       lxqt-session

ii  lxqt-sudo                                     0.9.0+bzr32+201508280746~ub amd64                       lxqt-sudo`

Openbox works for login. LXQT does not, at the moment. It worked fine on 2015-08-29, until poweroff at 2:44 am 2015-08-30 (after the updates), when there was an authentication problem that ran along similar veins.

Distribution is Lubuntu 15.04.

I haven't tried specific stepping backwards in versions yet, but that's next.

**Comment by rogerfranz** [comment]
Updated packages have now fixed this issue.

dpkg-query:
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                           Version              Architecture         Description
+++-==============================-====================-====================-=================================================================
ii  lxqt-about                     0.9.0+bzr44+20150830 amd64                lxqt-about
ii  lxqt-admin                     0.9.0+bzr51+20150830 amd64                lxqt-admin
ii  lxqt-common                    0.9.1.0.0+bzr117+201 all                  lxqt-common
ii  lxqt-config                    0.9.0.0.0+bzr319+201 amd64                lxqt-config
un  lxqt-connman-applet            <none>               <none>               (no description available)
ii  lxqt-globalkeys                0.9.0+bzr156+2015082 amd64                lxqt-globalkeys
ii  lxqt-leave                     0.9.0.0.1+bzr266+201 amd64                lxqt-leave
ii  lxqt-metapackage               0.0.1+bzr60+20150801 all                  lxqt-metapackage
ii  lxqt-notificationd             0.9.0.0.0+bzr127+201 amd64                lxqt-notificationd
ii  lxqt-openssh-askpass           0.9.0+bzr35+20150829 amd64                lxqt-openssh-askpass
ii  lxqt-panel                     0.9.0.0.0+bzr984+201 amd64                lxqt-panel
ii  lxqt-policykit                 0.9.0+bzr44+20150830 amd64                lxqt-policykit
ii  lxqt-powermanagement           0.9.0+bzr156+2015083 amd64                lxqt-powermanagement
ii  lxqt-qtplugin                  0.9.0+bzr32+20150818 amd64                lxqt-qtplugin
ii  lxqt-runner                    0.9.0+bzr160+2015083 amd64                lxqt-runner
ii  lxqt-session                   0.9.0.0.1+bzr266+201 amd64                lxqt-session
ii  lxqt-sudo                      0.9.0+bzr32+20150828 amd64                lxqt-sudo
```

**Comment by pmattern** [comment]
Confirmed, both problem and fix by recent update running Lubuntu 15.04 plus LXQt from PPA ppa:lubuntu-dev/lubuntu-daily.
This was a problem involving faulty implementation of some changes that took place recently upstream.

**Comment by Atalanttore** [comment]
I've installed LXQt 0.9 on Kubuntu 15.04 from <code>ppa:lubuntu-dev/lubuntu-daily</code>.

**Comment by pmattern** [comment]
@Atalanttore 
So it's probably fixed by the latest update as well, isn't it?

**Comment by Atalanttore** [comment]
The latest update fixed the login problem also on my machine.
