### ISSUE TITLE
Global hotkeys and its configuration tool are broken

### ISSUE THREAD

**Issue by Atalanttore** [lxde/lxqt#799]
Hi,

the global hotkeys (e.g. for volume and brightness) and its configuration tool doesn't work anymore after updating to latest version to fix the login problem (#798) on my machine.

My machine:
LXQt installed on Kubuntu 15.04 via <code>ppa:lubuntu-dev/lubuntu-daily</code>.

Regards,
Ettore

**Comment by paulolieuthier** [comment]
It works here (git master).

**Comment by pmattern** [comment]
Confirmed but in a way that seems related to #771. Findings / steps to reproduce:

1. start a session: all keyboard shortcuts and special keys like XF86Audio{Lower,Raise}Volume are working flawlessly
1. launch `lxqt-config-globalkeyshortcuts`: problems described in #771 can be seen; once `lxqt-config-globalkeyshortcuts` got "frozen" due to double-clicking a shortcut and closed thereafter all kinds of keyboard shortcuts stop working, sometimes input in QTerminal is even compromised as well
1. restart session or lxqt-globalkeysd: same as 1.

@paulolieuthier 
Can you try and reproduce that way?

Issue could be a kind of mixture, IMO: general failure of special keys / keyboard shortcuts → specific to PPA `ppa:lubuntu-dev/lubuntu-daily`, trouble caused by `lxqt-config-globalkeyshortcuts` → upstream problem.

Arch Linux x86_64 with all LXQt components from VCS checkout some hours ago.

**Comment by paulolieuthier** [comment]
@pmattern I can reproduce the issue described in #771. But I think this is different. My first thought here was a downstream problem after the LxQt to LXQt renaming. But the PPA looks updated.

@Atalanttore, can you even start `lxqt-config-globalkeyshortcuts`? Please run it in a console and show us the output if it is not working.

**Comment by Atalanttore** [comment]
I've started <code>lxqt-config-globalkeyshortcuts</code> in a console, but got this error:

<code>lxqt-config-globalkeyshortcuts: symbol lookup error: lxqt-config-globalkeyshortcuts: undefined symbol: _ZN4LxQt17SingleApplicationC1ERiPPcNS0_12StartOptionsE</code>

**Comment by paulolieuthier** [comment]
That's exactly what I thought. @Atalanttore you need to update liblxqt.

**Comment by Atalanttore** [comment]
I will wait for an update via <code>ppa:lubuntu-dev/lubuntu-daily</code>.

**Comment by paulolieuthier** [comment]
No, sorry. It's lxqt-globalkeys that needs an update.

**Comment by paulolieuthier** [comment]
But the PPA is already up to date, as I said.

**Comment by paulolieuthier** [comment]
@Atalanttore what is the version of the lxqt-globalkeys package you have installed?

**Comment by Atalanttore** [comment]
It's version 0.9.0+bzr156+201508221346~ubuntu15.04.1

**Comment by paulolieuthier** [comment]
I was wrong, the PPA is not updated. I hope it will be soon. That will fix it.

**Comment by rcmn** [comment]
Other affected :

lxqt-config: symbol lookup error: lxqt-config: undefined symbol:
_ZN4LxQt17SingleApplicationC1ERiPPcNS0_12StartOptionsE

lxqt-config-appearance: symbol lookup error: lxqt-config-appearance:
undefined symbol: _ZN4LxQt17SingleApplicationC1ERiPPcNS0_12StartOptionsE

lxqt-config-file-associations: symbol lookup error:
lxqt-config-file-associations: undefined symbol:
_ZN4LxQt17SingleApplicationC1ERiPPcNS0_12StartOptionsE

lxqt-config-globalkeyshortcuts: symbol lookup error:
lxqt-config-globalkeyshortcuts: undefined symbol:
_ZN4LxQt17SingleApplicationC1ERiPPcNS0_12StartOptionsE

lxqt-config-input: symbol lookup error: lxqt-config-input: undefined
symbol: _ZN4LxQt17SingleApplicationC1ERiPPcNS0_12StartOptionsE

lxqt-config-monitor: symbol lookup error: lxqt-config-monitor: undefined
symbol: _ZN4LxQt17SingleApplicationC1ERiPPcNS0_12StartOptionsE

lxqt-sudo: symbol lookup error: lxqt-sudo: undefined symbol:
_ZTVN4LxQt11ApplicationE

I started this before we got the issue narrow down. But for those who are
running into this...


On Mon, Aug 31, 2015 at 8:03 PM, Paulo Lieuthier <notifications@github.com>
wrote:

> @Atalanttore <https://github.com/Atalanttore> what is the version of the
> lxqt-globalkeys package you have installed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/799#issuecomment-136531844>.
>



-- 
R.

**Comment by pmattern** [comment]
That PPA was having massive issues due to the renaming LxQt → LXQt, see #798 and #797.

@paulolieuthier 
Can you also confirm that shortcuts stop working after `lxqt-config-globalkeyshortcuts` was behaving as stated above ("freeze")?
If yes we should add this to #771 while this issue seems to be yet another downstream problem affecting this particular PPA.

**Comment by paulolieuthier** [comment]
@pmattern I confirm #771's issue. But I don't think it's related.

**Comment by paulolieuthier** [comment]
@jleclanche we should ping the lubuntu-dev PPA maintainer.

**Comment by Atalanttore** [comment]
@paulolieuthier No problem. Changing brightness/volume via console is not a big deal. I hope to get the latest update soon.

**Comment by Atalanttore** [comment]
FYI, this is the Launchpad site of the lubuntu-dev PPA maintainer:
https://launchpad.net/~gilir

**Comment by jleclanche** [comment]
@gilir is the maintainer.

**Comment by Atalanttore** [comment]
It works again with latest updates from lubuntu-dev PPA.

**Comment by antis81** [comment]
>It works again with latest updates from lubuntu-dev PPA.

@Atalanttore @gilir Did you try `lxqt-config`? Still doesn't work here (PPA: `lubuntu-daily` -- see #808).

**Comment by Atalanttore** [comment]
@antis81 No, it doesn't. But the brightness/volume hotkeys and the GUI tool are working.

**Comment by celiapgt** [comment]
I'm no developer.
I'm just a humble fan of LXQT's team work.

I report that I have this error:
lxqt-config-input: symbol lookup error: lxqt-config-input: undefined symbol: _ZN4LxQt17SingleApplicationC1ERiPPcNS0_12StartOptionsE

And I cannot use most shortcuts (only works Win+E): not for cycling thru desktops, not for volume uo/down, not for Run dialog...

They are so important! I use keyboard a lot and now the shortcuts are gone!  


Please help. I can report as you advice.

**Comment by paulolieuthier** [comment]
@celiapgt you are using Ubuntu, right? This is a distribution problem, responsability of the packager. Hopefully very soon updated packages will land. You just have to wait. :disappointed:

**Comment by antis81** [comment]
@celiapgt I made up a central issue #808, listing the broken packages in `lubuntu-daily` PPA - (I am running a `Lubuntu 15.04` system). The package you are talking about here is called `lxqt-globalkeys` - which actually works fine on my system (so, maybe update your system?).

The most important packages are alive an up-to-date again (lxqt-session, lxqt-globalkeysd, ...), but in the first place `lxqt-config` and most of it's components are broken. Means, there's not a single dialog available for the system settings. This situation should not happen - even in a daily build (which currently is the only opertunity to actually install LXQt) …

@paulolieuthier I really do think, that reopening issue #808 helps a lot of people to get this sorted out. I'm waiting for this particular update for about 3 weeks now … really annoying. :(

**Comment by paulolieuthier** [comment]
@antis81 you are right, I just opened. To workaround this situation, you can get latest code of liblxqt from git and `make install` it.

**Comment by antis81** [comment]
@paulolieuthier 
Thanks! :+1:

AFAIK the root for all the trouble is a change to the `liblxqt` API (a `namespace` was added/renamed). So … the workaround will most probably not work stated above (btw.: I just received an liblxqt upgrade today -> does not fix the situation!). I do not recommend working around this problem, as this requires the affected applications (`lxqt-config*`) to be `make install`'ed with their latest version from Git. So I think the best way is to wait for the (hopefully very soon available) PPA upgrade.

**Comment by paulolieuthier** [comment]
Yeah, I was wrong. The workaround is to `make install` the components with the old symbols. I think it will be fixed in the next days.

**Comment by antis81** [comment]
@paulolieuthier It's fixed upstream! @gilir fixed it today!

**Comment by paulolieuthier** [comment]
Great! Thanks for your help.
