### ISSUE TITLE
lxqt-panel broken on ubuntu14.04.1_amd64

### ISSUE THREAD

**Issue by ferronrsmith** [lxde/lxqt#800]
Receiving the follow error after updating to : 

lqxqt-panel_0.9.0.0.0+bzr939+201506300023~ubuntu14.04.1_amd64

I had to revert back to lxpanel
lxqt-panel: symbol lookup error: lxqt-panel: undefined symbol: _ZTIN4LxQt12ConfigDialogE

**Comment by pmattern** [comment]
According to the error message this yet another manifestation of a well-known downstream problem affecting the *buntu PPA only, see #797, #798, #799.
Also note that your're not running the latest version of package `lxqt-panel` which is working flawlessly in a VM here.

**Comment by ferronrsmith** [comment]
Seems the daily build failed so we haven't gotten the latest version as yet, thanks!

**Comment by pmattern** [comment]
Just had a look at an Ubuntu 14.04 system which seems a bit odd:
The package lists on https://launchpad.net/~lubuntu-dev/+archive/ubuntu/lubuntu-daily state `0.9.0.0.0+bzr985+201508311316~ubuntu14.04.1` as latest version available. Yet `apt-get` is still listing the one you mentioned the failure of which can be reproduced here exactly as described, too.
Maybe a problem regarding the repo in addition to the one affecting the package?

**Comment by ferronrsmith** [comment]
Yea it seems so. I am unable to get the latest package. Build system seems
very slow.

On Wed, Sep 2, 2015 at 2:54 PM, Peter Mattern <notifications@github.com>
wrote:

> Just had a look at an Ubuntu 14.04 system which seems a bit odd:
> The package lists on
> https://launchpad.net/~lubuntu-dev/+archive/ubuntu/lubuntu-daily
> <https://launchpad.net/%7Elubuntu-dev/+archive/ubuntu/lubuntu-daily>
> state 0.9.0.0.0+bzr985+201508311316~ubuntu14.04.1 as latest version
> available. Yet apt-get is still listing the one you mentioned the failure
> of which can be reproduced here exactly as described, too.
> Maybe a problem regarding the repo in addition to the one affecting the
> package?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/800#issuecomment-137210208>.
>



-- 
"*Give me a place to stand* on, *and I will move the Earth*."

Ferron Hanse

**Comment by ferronrsmith** [comment]
Because of lxde/lxqt#338 I was unable to build the lxqt-panel locally. Had to revert the fix, because KWindowSystem on lubuntu is outdated. Needs at least v5.7.0 to support `KWindowSystem::setShowingDesktop`

**Comment by pmattern** [comment]
Yet I still think aside from the general flaws regarding this PPA there's something particularly wrong with the Ubuntu 14.04 packages. Note that LXQt panel from the very same PPA is working flawlessly on Lubuntu 15.04 (besides this  [doesn't help too much](https://github.com/lxde/lxqt/issues/808)).

**Comment by pmattern** [comment]
@ferronrsmith 
In the meantime this was s [stated by the PPA maintainer](https://github.com/lxde/lxqt/issues/808#issuecomment-140294269) as well. So you may eventually have to consider upgrading to a later *buntu flavour in order to use `lxqt-panel` in a reasonable way.

**Comment by ferronrsmith** [comment]
@pmattern that's fine. I was able to build it from the source, I'll do that going forward

**Comment by paulolieuthier** [comment]
@ferronrsmith you can get only the necessary kf5 packages from a KDE PPA (https://community.kde.org/Kubuntu/PPAs#Kubuntu.27s_PPA_Repositories).

**Comment by ferronrsmith** [comment]
thanks

**Comment by Esclapion** [comment]
It affects also Manjaro (arch-based).
