### ISSUE TITLE
pcmanfm-qt closes abruptly

### ISSUE THREAD

**Issue by ferronrsmith** [lxde/lxqt#801]
There are 2 cases where this happens.

- If I create a bookmark for a folder
- Delete the folder
- Try to navigate to the folder (deleted) using the bookmark. pcmanfm crashes

I using maven alot for work

- If I navigate inside the `targets` folder
- Then perform a mvn clean via the terminal (which removes the targets folder)
- pcmanfm-qt crashes.

Are these expected behavior ? 

Expected behavior

1. If a user tries to navigate via a bookmark to a folder that does not exist, A message saying  "Folder does not exist"
2. If a folder is deleted while a user is currently access it, it should always take them to the parent level and so on 

e.g.

`/home/ferron/lxqt/targets` <-- deleting target should take me back to `/home/ferron/lxqt`

**Comment by pmattern** [comment]
The common practice to use this issue tracker for components featuring a dedicated one as well seems highly questionable to me.
Yet reporting on both kinds of tracker in parallel doesn't make sense.
