### ISSUE TITLE
missed license headers in lxqt-powermanagement

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#803]
config/helpers.h: *No copyright* UNKNOWN
src/iconproducer.h: *No copyright* UNKNOWN
src/batteryinfodialog.cpp: *No copyright* UNKNOWN
src/batteryinfodialog.h: *No copyright* UNKNOWN
src/iconproducer.cpp: *No copyright* UNKNOWN
src/powermanagementd.h: *No copyright* UNKNOWN
src/watcher.h: *No copyright* UNKNOWN

**Comment by surlykke** [comment]
I've added headers to said files. I took the liberty of using the license
header I proposed in another thread. I do not mean do foreclose the debate
on how LXQt license headers shall look. Once that is settled I can adjust
these.

br. Chr.

2015-09-03 0:38 GMT+02:00 Alf Gaida <notifications@github.com>:

**Comment by jleclanche** [comment]
Yes that's completely fine.
