### ISSUE TITLE
Strange mix-ups of PCManfm's

### ISSUE THREAD

**Issue by Baltasarq** [lxde/lxqt#806]
This is rather strange. I had an updated Lubuntu, and switched to LxQt. The pcmanfm I'm using is v1.2.3:

    $ sudo apt list pcmanfm
    Listing... Done
    pcmanfm/vivid,now 1.2.3+bzr1422+201507131931~ubuntu15.04.1 amd64 [installed]
    N: There is 1 additional version. Please use the '-a' switch to see it

    $ ps aux | grep pcmanfm
    baltasa+  1586  0.0  0.7 973484 60280 ?        Sl   sep01   0:06 pcmanfm-qt --desktop --profile=lxqt
    baltasa+  6462  0.0  0.0  12012  2332 pts/0    S+   14:30   0:00 grep --color=auto pcmanfm

So far so good. However, one day I noticed a weird behaviour: if I launch pcmanfm, then pcmanfm-qt 1.2.3 is correctly launched. If I click a folder in the desktop, however, then... pcmanfm 0.9 is launched!! (though it is not even installed).

The problem is that I'm unable to drag&drop between both pcmanfm's. I can drag&drop between two windows of the pcmanfm 0.9, and two windows of pcmanfm 1.2.3, but not from a 0.9.0 window to a 1.2.3 one. Also, the drag&drop process is different: the 0.9 one always prompts whether to copy or move the file, and the icon has a black background.

![pcmanfms](https://cloud.githubusercontent.com/assets/201012/9658439/a1569158-5249-11e5-9dc4-8b1c290a912d.png)

Can pcmanfm-qt v1.2.3 be skinned differently?
What's going on?

**Comment by Baltasarq** [comment]
Okay, forget it. I did have pcmanfm from Lxde installed. It turns out that pcmanfm-qt is the one identifying itself as pcmanfm-0.9, while cpmanfm using gtk2 was the one identifying itself as v1.2.3. Sorry for the confusion.

Can I remove the question about moving, or copying file here while drag&drop? I'd like the old behaviour, when moving was the default, while pressing ctrl would copy instead of moving.

**Comment by pmattern** [comment]
You've indeed got both the GTK version "PCManFM" and the Qt version "PCManFM-Qt" installed which can be seen from the output you posted - there's both a package `pcmanfm` and a binary `pcmanfm-qt` which belongs to package pcmanfm-qt, see `dpkg --search $(which pcmanfm-qt)`.
The GTK version is placing its icon under "System Tools" in Application menu, the Qt version under "Accessories" which makes that whole thing a bit difficult to detect.
PCManFM-Qt is launched upon clicking on desktop icons as it got assigned MIME type `inode/directory`.

What you call "old behaviour" with regards to d&d is a reasonable suggestion. AFAIK it was never implemented in PCManFM-*Qt* and should be filed as a new issue possibly on PCManFM-Qt's [dedicated tracker](https://github.com/lxde/pcmanfm-qt/issues).
