### ISSUE TITLE
[feature request] create an analogon of xfce4-quicklauncher-plugin

### ISSUE THREAD

**Issue by eugen-br** [lxde/lxqt#811]
Hello LXQt Team!
I would like to have two rows of launchers in my LXQt panel, but only one row with big window buttons in task manager. This could either be achived with a special container for launchers like the xfce4-quicklauncher-plugin http://goodies.xfce.org/projects/panel-plugins/xfce4-quicklauncher-plugin or with a task manager option allowing for one row while the panel has two rows.
Thank you and good luck with version 8.10!

**Comment by pmattern** [comment]
Issues was submitted [twice](https://github.com/lxde/lxqt/issues/810).
