### ISSUE TITLE
Task manager plugin buttons -  Icon view is stretched

### ISSUE THREAD

**Issue by intialonso** [lxde/lxqt#813]
A new install of LXQT over Arch compiling from AUR.

When setting the Task Manager plugin button style to "Icon" the button width is the same as with Text + Icon.

![screen](https://cloud.githubusercontent.com/assets/7544231/9720310/7f035d00-5552-11e5-9d4d-597327f1f6c0.jpeg)

It should shrink itself to the width of the icon. It seems to be a problem with the plugin, not the themes.

**Comment by palinek** [comment]
Great to see you back @intialonso.
Now it's up to the user how she/he sets the maximum width/height...

**Comment by intialonso** [comment]
Thank you.

I see, closing this.
