### ISSUE TITLE
How to "compress" a file by the pop up menu?

### ISSUE THREAD

**Issue by hykwok** [lxde/lxqt#815]
After I "right click" a file on the desktop, a pop up menu is shown. Then I select the "Compress" command but nothing is happen (no compressed output, no warning or error message)
So, how do I troubleshoot this problem?
![lxqt_error_006](https://cloud.githubusercontent.com/assets/11486595/9724774/7af7a244-560f-11e5-8931-7a034b583cf2.png)

**Comment by stefonarch** [comment]
Did you specificy an application for handling archives in PCmanfm >
settings > avanced?
Here it opens ark (kde tool) and works.

Il 08/09/2015 03:54, hykwok ha scritto:

**Comment by hykwok** [comment]
Thank you for your instruction.
After I select the correct archiver (xarchiver is used in my case), the function works now.
Actually, I expect the system would show a message likes "The application is found...."

**Comment by stefonarch** [comment]
Yes, it would be fine this  the config dialog or a messagge "no archive tool specified, please select one in ..." would be shown.

**Comment by pmattern** [comment]
FYI I agree that a warning is lacking here and opened lxde/pcmanfm-qt#226 covering this and some more aspects from this context.

**Comment by Adityashaw** [comment]
I am also using xarchiver and the "compress" option in the context menu doesn't work. Searching over Internet shows many bugs (dating 2017) stating that xarchiver has started using command line argument and hence, is incompatible with current pcmanfm. 
PS: Other features like "Extract here" are working fine.

**Comment by tsujan** [comment]
> I am also using xarchiver

LXQt has [lxqt-archiver](https://github.com/lxqt/lxqt-archiver) now. It works well but we need more feedback. If you use it, make sure you have its latest git version (its pre-beta release isn't up-to-date).

**Comment by Adityashaw** [comment]
> 
> LXQt has [lxqt-archiver](https://github.com/lxqt/lxqt-archiver) now. It works well but we need more feedback. If you use it, make sure you have its latest git version (its pre-beta release isn't up-to-date).

Thanks a lot for the suggestion!
Can you please refer me a guide that I can follow to build (or install) the package on Arch? I have never done that. Sorry for the trouble.

**Comment by tsujan** [comment]
> ... a guide that I can follow to build (or install) the package on Arch?

Arch? It's the best distro for having git packages: https://aur.archlinux.org/packages/lxqt-archiver-git/

**Comment by tsujan** [comment]
> I have never done that.

Oh, sorry, I missed that part.

In Arch, you're responsible for your system. You may make mistakes but they can always be corrected.

You need to replace your libfm-qt and pcmanfm-qt installations with their AUR git packages too. And that's OK because they're very stable.

In Arch, you could use an AUR helper (like `yay`) for such jobs or, instead, download the snapshots, open a terminal inside their extracted folders and issue `makepkg` (read probable error messages and do accordingly, if any) and, finally, install the created packages.

Arch Wiki is very handy; you might need to read its relevant pages.

**Comment by Adityashaw** [comment]
> > ... a guide that I can follow to build (or install) the package on Arch?
> 
> Arch? It's the best distro for having git packages: https://aur.archlinux.org/packages/lxqt-archiver-git/

I have installed `pikaur` and it works flawlessly. I am worried because Aur Package is showing last updated in **2018**. Is it the latest? In other words, does this package automatically fetches the latest source from the GitHub Repo of `lxqt-archiver`?
And thanks for fast responses!

**Comment by tsujan** [comment]
> ... In other words, does this package automatically fetches the latest source from the GitHub Repo

Yes, it does. And it's maintained by an LXQt developer.

A git PKGBUILD usually doesn't need updates. When you or an AUR helper uses `makepkg`, `pkgver` will be changed to the latest git commit.
