### ISSUE TITLE
plugin-statusnotifier operating with a fraction of applications only

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#817]
Apparently plugin-statusnotifier is operating with a fraction of applications only.

E. g. on KDE Plasma 5 Otter Browser, Quassel client, qps from QtDesktop, LXQt ConnMan applet and [radiotray](https://bitbucket.org/carlmig/radio-tray) as GTK application compiled against [libappindicator](https://launchpad.net/libappindicator) are working flawlessly in the new System Tray plugin implementing [SNI](http://www.freedesktop.org/wiki/Specifications/StatusNotifierItem). Regarding Otter this comprises tasks like opening tabs from the System Tray icon, regarding Quassel the problem described in #708 doesn't exist and the window comes up at once.
Running LXQt on otherwise identical systems radiotray was the only among those applications that worked in plugin-statusnotifier here. It didn't matter whether or not plugin-tray was available in addition, the findings were even the same when a new user profile was used and plugin-tray removed from the panel before launching any of the said applications the first time.

Is this problem eventually due to the fact that the fallback functionality that's actually part of the SNI specification was omitted?

All findings on up-to-date Arch Linux i686 or x86_64, Quassel client and radiotray as latest release from the repos, all other applications from latest VCS checkouts.

**Comment by stefonarch** [comment]
Akregator, linphone and konversation (latter has an issue with non popping up directly, but this is present in systray too) work well here.

**Comment by pmattern** [comment]
Confirmed regarding Akregator and Konversation. Couldn't get linphone's icon to show up which may have been due to lacking knowledge about that program and probably doesn't mean a thing.
Cross checked another time: all applications were from the very same Arch Linux binary packages on KDE Plasma and LXQt as stated in first comment.
Sigh...

**Comment by pmattern** [comment]
Akregator and Konversation are showing up in plugin-statusnotifier here as well but Linphone doesn't. Could Linphone eventually be placed in plugin-tray adjacent to plugin-statusnotfier on your system?

As in this would suggest some schema: applications interacting with plugin-statusnotifier are either belonging to KDE or compiled against [libappindicator](http://launchpad.net/libappindicator) which is explicitely stated to support *K*SNI.
This in turn could mean there's some problem regarding SNI vs. KSNI, imo.

**Comment by stefonarch** [comment]
You were right about Linphone, it was just adjacent.

Il 12/09/2015 20:29, Peter Mattern ha scritto:

**Comment by palinek** [comment]
It may be that the lxde/lxqt-panel#239 fixes also this....

@pmattern can you check it?

**Comment by paulolieuthier** [comment]
The only applications what already go to the status notifier are Qt4 applications (with sni-qt installed), KDE applications and the libappindicator-based GTK apps. Qt5 applications, like lxqt-powermanagement, are still in the old plugin, although Qt 5.5 and later versions natively supports the new spec. This is because the backend must be implemented in our Qt plugin. I've been experimenting with it and hope I'll be able to delivery soon. Then only applications static linked to Qt5 < 5.5 will remain in the old plugin, and GTK applications not using libappindicator, like nm-applet and Thunderbird.

**Comment by pmattern** [comment]
@palinek 
Tests involving Otter Browser and LXQt ConnMan applet suggest that the commits proposed in lxde/lxqt-panel#239 don't change the problem addressed in this issue: if both plugin-statusnotifier and plugin-tray are available, the icons of both applications come up in the latter, if only plugin-statusnotifier is available the icons don't show up at all.
Regarding Quassel the findings are slightly different, see https://github.com/lxde/lxqt/issues/708#issuecomment-142317251.
Given what @paulolieuthier found out in the meantime I assume we should definitely wait until he has time to implement his findings before tracking this issue any further.

**Comment by paulolieuthier** [comment]
@pmattern please, test lxde/lxqt-qtplugin#5.

**Comment by pmattern** [comment]
lxde/lxqt-qtplugin@ca7f30a from branch `sni` seems to do the trick - all applications tested so far are by default using plugin-statusnotifier now, no matter whether or not plugin-tray is available in addition.
But this only applies if branch `notifier_fixes` from lxqt-panel is used as well. If lxqt-panel master is used there's still the same behaviour as depicted in my previous post.

Arch i686 and x86_64 as usual.

**Comment by paulolieuthier** [comment]
Are you sure one has to apply notifier_fixes? I don't think so. Did you wait enough for the apps to appear in the statusnotifier? AFAIK, without this branch the apps still work, they just take longer to show up.

**Comment by pmattern** [comment]
@paulolieuthier 
You are right. Branch `sni` of lxqt-qtplugin is fixing this issue on its own, it is *not* necessary to complement it with branch `notifier_fixes` of lxqt-panel the `master` branch of which works as well. No clue what made me think otherwise earlier.
Complementing branch `sni` of lxqt-qtplugin with `notifier_fixes` doesn't hurt, though. In fact I couldn't see any difference, also with regards to the interval until icons show up in plugin-statusnotifier.

**Comment by jleclanche** [comment]
@paulolieuthier @palinek Hey sorry I caught this so late but how come the systray and status notifier plugins are mutually exclusive? If we have 2 plugins, the idea was to have both next to each other. If we have just one plugin, the plugin should support both.

**Comment by pmattern** [comment]
`plugin-tray` and `plugin-statusnotifier` are working just fine and without any issue in parallel here (VCS checkouts on Arch Linux i686 or x86_64). In fact the usage of both is even rather mandatory right now as `plugin-statusnotifier` lacks the ability to fall back to handling applets according to the old System Tray Specification.

How come you think parallel usage doesn't work? Any steps to reproduce?

**Comment by paulolieuthier** [comment]
@jleclanche each plugin handles its protocol.
