### ISSUE TITLE
lxqt-metapackage in PPA

### ISSUE THREAD

**Issue by jl451** [lxde/lxqt#823]
In package "lxqt-metapackage" in "Daily builds for Lubuntu" https://launchpad.net/~lubuntu-dev/+archive/ubuntu/lubuntu-daily

"lxqt-metapackage" unreasonable depends from xserver-xorg-video-all, xserver-xorg-input-all

"lxqt-metapackage" now depends from xserver-xorg-video-all, xserver-xorg-input-all

must need be depends from xorg-driver-video and xorg-driver-input

apt-cache policy lxqt-metapackage
 *** 0.0.1+bzr60+201508012301~ubuntu15.04.1 0
        500 http://ppa.launchpad.net/lubuntu-dev/lubuntu-daily/ubuntu/ vivid/main amd64 Packages

ps: sorry my english

**Comment by pmattern** [comment]
This issue tracker is dedicated to the development of LXQt and related components themselves but doesn't cover downstream issues like packaging of the said repository.

It looks like we had to set up a wiki page explaining this, for now you may want to have a look at [this comment](https://github.com/lxde/lxqt/issues/808#issuecomment-137946340) where I had tried to explain the situation recently.

**Comment by agaida** [comment]
@pmattern - do you really think this would help (or that the users would reed this) ?

**Comment by gilir** [comment]
@pmattern I completely understand that you don't want downstream issues on the upstream tracker. However, I'm quite happy with the fact that users report upstream, the issues they have with daily builds (which are basicly git snapshots in a .deb, with minimum changes). In a normal work flow, most of the issues people will report with this type of packages will be issues for upstream (except during big API or build system modification). So I was wondering if it's possible on github to have a sub-tracker for downstream ?
Example for this type of bug report, you move it to the sub-tracker if you are quite sure it's a downstream issue. The responsible of the downstream distribution triage the bug, and if it's finally a real upstream issue, he re-affect it to upstream tracker. It can be also the opposite : downstream advise people to report under the downstream bug tracker, and if it's a real upstream issue, we re-affect to upstream bug tracker.

**Comment by pmattern** [comment]
Regarding your PPA the vast majority of problems reported by its users on these trackers was downstream. Also, I'm pretty sure that all of us LXQt folks are very well able to distinguish LXQt bugs from downstream issues with reasonable effort. If we set up a tracker dedicated to your *buntu PPA lots of other distributions may come along and with the same wish which would pretty much clutter our trackers up. Moving issues from one tracker to an other on GitHub is possible via hacks only and probably not at all easier than transferring to a tracker on launchpad.net.
So all in all I for one am still absolutely against opening a downstream tracker on github.com/lxde.
Given the importance of your PPA which is very likely to increase once LXQt gets official desktop of Lubuntu I think a means to ease exchanging issues between the trackers on GitHub and launchapd.net would be something nice to have. No clue whether this is technically feasible, though. Regarding GitHub maybe some bot similar to the one submitting posts on #lxde that can be triggered by team members?

**Comment by gilir** [comment]
@pmattern Ok, thanks for the answer. If people continue to report downstream issues for Ubuntu packages, feel free to point them to https://bugs.launchpad.net/lubuntu-next. I'll try to triage the bug reports there. I'll pass the word to the Lubuntu mailing list.

**Comment by pmattern** [comment]
>  feel free to point them to https://bugs.launchpad.net/lubuntu-next. I'll try to triage the bug reports there.

Alright. Let's handle it that way. If it turns out to be inefficient we can still think about something else.
Also, as stated above, I wouldn't expect much triage work to be left on that launchpad tracker.

> I'll pass the word to the Lubuntu mailing list.

Mind posting a link here if you do (couldn't find anything yet)?

**Comment by gilir** [comment]
Sure, this is the list : https://lists.ubuntu.com/mailman/listinfo/lubuntu-users
