### ISSUE TITLE
lxqt-session.qss not found

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#825]
I found in 
$ journalctl -a 
....
lug 05 18:19:28 arch systemd[13425]: Starting Default.                                                                           
lug 05 18:19:29 arch lxqt-session[13429]: Theme: Cannot open file for reading: "/usr/share/lxqt/themes/frost/lxqt-session.qss"   

 $ locate lxqt-session.qss gives 
no output at all.

**Comment by stefonarch** [comment]
I see it was only back in July, recent log is clean.

**Comment by paulolieuthier** [comment]
This message could be safely ignored. It was removed not to confuse users.
