### ISSUE TITLE
lxqt-config: Please make lxqt-config-monitor less verbose

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#828]
<pre>
agaida@razorbox:~/work/siduction/code/pkg-lxqt/lxqt-config/upstream$ lxqt-config-monitor
"Identifier" = "0x23e"
"Timestamp" = "79958488"
"Subpixel" = "unknown"
"Gamma" = "1.0:1.0:1.0"
"Brightness" = "1.0"
"Clones" = ""
"CRTC" = "0"
"CRTCs" = "0 1"
"Transform" = "1.000000 0.000000 0.000000
0.000000 1.000000 0.000000
0.000000 0.000000 1.000000
filter:"
"EDID" = "
00ffffffffffff004c2df40336324454
0a120103803722782aee91a3544c9926
0f5054bfef80a94081808140714f0101
010101010101283c80a070b023403020
360006442100001a000000fd00384b1e
5111000a202020202020000000fc0053
796e634d61737465720a2020000000ff
004831414b3530303030300a20200088"
VendorHex: "53796e634d61737465720a202" Vendor "SyncMaster
 "
"SignalFormat" = "TMDS 
supported: TMDS"
"ConnectorType" = "DVI-I "
"ConnectorNumber" = "0 "
"_ConnectorLocation" = "0 "
Reading modes end
Monitor "DVI-I-1"
Monitor "Monitor 1: DVI-I-1 (DVI-Bildschirm) SyncMaster
 "
"Identifier" = "0x23e"
"Timestamp" = "79958488"
"Subpixel" = "unknown"
"Gamma" = "1.0:1.0:1.0"
"Brightness" = "1.0"
"Clones" = ""
"CRTC" = "0"
"CRTCs" = "0 1"
"Transform" = "1.000000 0.000000 0.000000
0.000000 1.000000 0.000000
0.000000 0.000000 1.000000
filter:"
"EDID" = "
00ffffffffffff004c2df40336324454
0a120103803722782aee91a3544c9926
0f5054bfef80a94081808140714f0101
010101010101283c80a070b023403020
360006442100001a000000fd00384b1e
5111000a202020202020000000fc0053
796e634d61737465720a2020000000ff
004831414b3530303030300a20200088"
VendorHex: "53796e634d61737465720a202" Vendor "SyncMaster
 "
"SignalFormat" = "TMDS 
supported: TMDS"
"ConnectorType" = "DVI-I "
"ConnectorNumber" = "0 "
"_ConnectorLocation" = "0 "
Reading modes end
</pre>

Really, please :)

**Comment by paulolieuthier** [comment]
After the port to KScreen is completed, it'll shine, my friend. Silently. :smile:

**Comment by jleclanche** [comment]
Closing because it comes for free with the kscreen port.
