### ISSUE TITLE
Application switcher

### ISSUE THREAD

**Issue by zjes** [lxde/lxqt#829]
Hi, it's not a issue, again :), just sharing of the code. I just don't know where to post such user contributions.
Normally I used openbox application switcher in lxqt, but this switcher doesn't good enough for me. For example, cannot set icons size, style, filters by desktop and active screen. And old application switcher was deprecated and thrown out from lxqt. So, I just created simple switcher (https://github.com/zjes/lxqt-appswitcher) with lxqt integration and those filters. For example it looks for ambiance theme like this:
![appswitcher](https://cloud.githubusercontent.com/assets/550431/10096655/8d28eeca-6373-11e5-8881-d931c9c35e3c.png)
This switcher is very raw, but works (somehow).  If someone interested with such switcher then I will be glad. :)

**Comment by palinek** [comment]
@jleclanche How about putting information about such 3rd party contribution into wiki somewhere?

**Comment by jleclanche** [comment]
Yes that's fine. As long as it's being maintained by someone, feel free.

**Comment by paulolieuthier** [comment]
Done here: https://github.com/lxde/lxqt/wiki/Third-party-apps. @zjes thanks!
