### ISSUE TITLE
Pcmanfm-qt should not close on Alt-F4 ..

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#830]
when painting the desktop. Noticed this behaviour with xfwm4, openbox and kwin are ok.
pcmanfm don't show this behaviour, so i would call this a regression.

**Comment by pmattern** [comment]
But that's a dupe of lxde/pcmanfm-qt#194, isn't it?

**Comment by agaida** [comment]
yes - forget that pcmanfm-qt has his own bug tracker - anyways, this is not the intended behaviour and should be fixed before the release.

**Comment by pmattern** [comment]
Well, so I guess you don't mind as closing this one so as to avoid clutter, right?
