### ISSUE TITLE
LXQt versus the screensaver

### ISSUE THREAD

**Issue by gauthma** [lxde/lxqt#833]
In order to lock the screen and suspend the session, I used a `slock` and a `systemd` script, as described [here](http://erroneousthoughts.org/my-notes-for-a-swift-arch-linux-install/#Graphical_Environment). I'm an Archlinux user. This worked really well, until I upgraded to the latest and greatest LXQt version from `git`: now, when I close the lid, an error is shown complaining that `xscreensaver` is not installed, **and the session is NOT suspended**! When open the lid back up, and click "Ok" in the error message box, **then** the screen is locked and the session suspended!

After ingloriously googling for a solution, I started `grep`ing the code, and found that `xdg-screensaver` was used to manipulate the screensaver, in file `liblxqtscreensaver.cpp` (package `liblxqt`). The problem is that with `xdg-utils` 1.1.0.git20150323-1 (the current version in Arch), the LXQt desktop is **not detected**. And the error message complaining about `xscreensaver` seems to be output from blindly looking at `xdg-screensaver`'s exit code.

I managed to workaround this issue by changing line 60 of `liblxqtscreensaver.cpp` to:

     m_xdgProcess->start("xdg-screensaver", QStringList() << "--version");

In the original there was "lock" instead of "--version". If I just commented out the line, it also worked, but only from the *second* time I closed the lid (closing the lid for the first time after a reboot did nothing...). I'm not sure this is even a bug with `LXQt` (instead of `xdg-utils`), but if anyone has any thoughts on this, I'd like to hear them :-)

**Comment by paulolieuthier** [comment]
Fixed in lxde/liblxqt@e3f610a73b8ea162bb892be426ea087f0f07f163. We still hardcode xscreensaver, though. And locking the screen only works when locking through a LXQt application. We should make use of longid's signal, as described [here](http://blog.martin-graesslin.com/blog/2015/01/locking-the-screen-before-system-suspends/).

**Comment by paulolieuthier** [comment]
@gauthma thanks for the report. Please, update liblxqt from git and test it again. If it still doesn't work, please reopen the issue.

**Comment by gauthma** [comment]
It works... kind of. Now closing the lid the session is suspended, and when opening it back up, the screen is locked. But after typing the password, the box with the error message is already there waiting for me! Re-opening...

**Comment by gauthma** [comment]
Actually, I can't reopen the bug (since it was closed by a rep collaborator), but I think it should be re-opened...

**Comment by paulolieuthier** [comment]
@gauthma you're using slock, right? So it's a different problem now.

**Comment by paulolieuthier** [comment]
See #834.

**Comment by gauthma** [comment]
Yes, I use slock. This seems to be a race condition of sorts: the box with the error message is shown, but the session is suspended before there is enough time to clear it.  If I click on "Lock screen" on the main menu, I get a quick glimpse of a box being drawn and then erased.

**Comment by paulolieuthier** [comment]
@gauthma please update again and test it.

**Comment by gauthma** [comment]
@paulolieuthier I'm afraid the latest change brought back the original problem (to which I had to apply the original workaround).

**Comment by paulolieuthier** [comment]
@gauthma do you see the problem I'm trying to solve is to make the system suspend even if it can't be locked? The warning dialog will still show up.

**Comment by paulolieuthier** [comment]
@gauthma can you please try lxde/liblxqt#64? Thanks for your help.

**Comment by gauthma** [comment]
@paulolieuthier Thanks for your efforts in fixing this! The good news is that lxde/liblxqt#64 fixes this bug. The bad news is that it causes two new problems: first, main menu -> Leave -> Logout no longer works (it does nothing). Second, after restarting the graphical environment, LXQt Power Management stops working: just after logging in an error message is shown stating that LXQt Power Management has crashed too many times, and thus has been stopped until the next login.

**Comment by paulolieuthier** [comment]
> The good news is that lxde/liblxqt#64 indeed fixed this bug.

Finally! :smile: 

> The bad news is that it causes two new problems.

Yeah, I saw that after I submitted the PR. I'm working on it.

**Comment by racuna** [comment]
"LXQt Power Management has crashed too many times, and thus has been stopped until the next login"

Same here.. no details about what is happening tho.
