### ISSUE TITLE
lxqt-powermanagement: option to lock screen

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#837]
Please add separate option to enable/disable screen locking on suspend/hibernate.

**Comment by paulolieuthier** [comment]
I've been planning that, but I'm not sure it should go in lxqt-config-powermanagement. It sounds more like session setting to me.

**Comment by jleclanche** [comment]
@paulolieuthier session settings will eventually disappear I think.

**Comment by Vladimir-csp** [comment]
> session settings will eventually disappear I think. 
@jleclanche, what do you mean by that?

**Comment by RalfJung** [comment]
This looks like a duplicate of #775
