### ISSUE TITLE
lxqt-sudo: does not start from runner

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#838]
lxqt-sudo does not show up if run from runner (tested with lxqt-runner and gmrun by running `lxqt-sudo synaptic`)
But if runner itself is launched via terminal, then lxqt-sudo works. So perhaps this is related to either stdout handling or login records.

**Comment by palinek** [comment]
The very same scenario is working here as expected. What version are you using?

**Comment by Vladimir-csp** [comment]
0.9.0+bzr35+201509090801~ubuntu15.04.1

**Comment by Vladimir-csp** [comment]
OK, tested a little bit more:
When I restarted lxqt-runner via lxqt-config-session, lxqt-sudo started working. Previously I launched it via gmrun which is launched by openbox shortcut. I will test some more...

**Comment by Vladimir-csp** [comment]
Try repoducing this way:
Launching lxqt-runner by openbox shortcut, running `lxqt-sudo some_command` in lxqt-runer.
Launching `lxqt-sudo some_command` directly by openbox shortcut.

**Comment by palinek** [comment]
> Launching lxqt-runner by openbox shortcut, running lxqt-sudo some_command in lxqt-runer.
Launching lxqt-sudo some_command directly by openbox shortcut.

@Vladimir-csp Xurrent `lxqt-sudo` needs a controlling terminal and the problem with such invocation is that there is no terminal attached at all.
In [lxsu](https://github.com/lxde/lxqt-sudo/pull/12) branch of lxqt-sudo the logic for su/sudo backend is unified and creating a new controling terminal for su/sudo. With this branch I'm able to to run `lxqt-sudo` directly by the openbox shortcut.

**Comment by Vladimir-csp** [comment]
Thanks, I'll try it!
Closing the issue since as far as I can tell lxsu branch is going to be merged into master eventually.
