### ISSUE TITLE
configuration dialog: numbering of plugins not reset upon removal

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#839]
The counter indicating the number of instances per plugin in dialog "Configure Panel" doesn't get reset if a plugin is removed completely which yields faulty and somehow confusing results.

E. g. the panel corresponding to this screenshot
![lxqt-panel_numbering-of-plugins](https://cloud.githubusercontent.com/assets/9860801/10230669/b0030588-687e-11e5-8b75-63fdd52616a6.png)
is comprising three instances of plugin-mainmenu, at least one instance had been running all the time so the numbering is correct. But there are only two instances of plugin-showdesktop, numbers 2 and 3 are due to the fact that all instances had been removed before re-adding the actual two. Similarly there's only one instance of both plugin-clock and plugin-desktopswitch but the former had been removed and re-added, the latter hadn't.

The behaviour stays the same if the only instance of a plugin gets removed and re-added after starting another session only (which seems a bit odd to me as I couldn't find a location saving information about the former instance while no LXQt session is running).

**Comment by palinek** [comment]
The name of newly added plugin is assembled as \<plugin-type\>\<lowest unused number from 2\>, see [here](https://github.com/lxde/lxqt-panel/blob/master/panel/panelpluginsmodel.cpp#L243). I don't know the reasoning for that.

You normally get the name as \<plugin-type\> only in case of a new user running lxqt-panel (the default config file from ...*(i don't remember the path)* is used, where the names of instances are the same as the type) or manually editing the `panel.conf`.

**Comment by rbazaud** [comment]
Submitted pull request lxde/lxqt-panel#245 which does seem to solve the problem as described. Could you conﬁrm it please ?

**Comment by pmattern** [comment]
Apparently the problem is fixed in some plugins only. E. g. plugin-spacer isn't affected any longer but plugin-{mainmenu,showdesktop} still are.
Arch Linux running yesterday's VCS checkout of LXQt, so lxqt-panel lxde/lxqt-panel@d6fed23.

Side-note while at it:
Personally I think the current layout in dialog "Configure Panel" placing the number right after the plugin description isn't exactly intuitive and helpful. The meaning of that number would be more apparent if e. g. a blank space was in between.
What do you guys think?

**Comment by palinek** [comment]
The shown number/name is the name of section in configutation file. Nothing more, nothing less. IMO this information definitely s not needed to be presented

**Comment by palinek** [comment]
Sorry...accidentaly pushed the button while editing on the phone

**Comment by pmattern** [comment]
Well, but the number also informs about plugin instances which are eventually running already. And having this information does make some sense, IMO.

**Comment by palinek** [comment]
Closing.. as the name for instance is now assembled as *pluginname* or *pluginnameX* (beggining with X from 2)
