### ISSUE TITLE
lxqt-config-session: adjusting trigger of dialog about need to restart session could improve UX

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#840]
If drop-down list `Window Manager` in section `Basic Settings` (left pane) is opened and closed without committing a change by clicking the arrow down icon twice there's no warning when lxqt-config-session is closed. But if the very same action is performed with drop-downs `Terminal Emulation` or `Web Browser` in section `Default Applications` leaving lxqt-config-session triggers the dialog informing about the need to restart the session in order to apply the changed settings.
I think it would be better if all drop-down lists behaved like `Window Manager`.

Similarly, the said warning will come up when changes were made in any of those drop downs but reverted.
Probably the UX could be improved as well if the warning came up only if settings were in fact changed.

**Comment by luis-pereira** [comment]
@pmattern In Basic Settings > Window Manager clicking the Search button also triggers it. The Leave session doesn't need an logout to work Ok. But that's the exception.

The rule should be, "Issue an warning only on settings change". I'm implementing it.

**Comment by pmattern** [comment]
Strictly speaking the rule had to be "Show the message informing about the need to restart the session only if settings were in fact changed that indeed need the session to get restarted in order to take effect".
Don't know to which of the settings in `lxqt-config-session` the latter applies and would have to test it for each of them. Guess you know better.

Aside from this I happened to see that (un-) checking boxes at Basic Settings - LXQt Modules as well as Autostart does *not* necessarily trigger the said message.

**Comment by luis-pereira** [comment]
Done. Closing it.

**Comment by pmattern** [comment]
@luis-pereira 
I just stumbled upon one more related detail: the message telling that changes that were made will apply after restarting the LXQt session only comes up when environment variables are added or modified in topic "Environment (Advanced)" but not if they are deleted.
Wouldn't it make sense to have the message displayed in that case, too?

**Comment by luis-pereira** [comment]
@pmattern Yes. Pls test https://github.com/lxde/lxqt-session/pull/81.
