### ISSUE TITLE
Graphical Problems with Network Manager Applet

### ISSUE THREAD

**Issue by AwlsomeAlex** [lxde/lxqt#841]
Whenever I leave the Network Manager Applet alone for a while, the icon will start to glitch out and look wierd, however, if you disconnect from the wifi or click on it (sometimes) it will revert back to normal. Also I am running Xubuntu and LXQt on a separate
![problem](https://cloud.githubusercontent.com/assets/11639639/10237700/50eb0168-6883-11e5-8944-c43a8b0fed45.png)
 option.

**Comment by palinek** [comment]
dup of #106
