### ISSUE TITLE
[pcmanfm-qt] icons for rename and compress ?

### ISSUE THREAD

**Issue by Esclapion** [lxde/lxqt#845]
Sorry, because it's more a question than an issue, but i tried a dozen of themes and none displays an icon for those both operations when right-clicking on a folder or a file.
What can be please the name of those icons, if some are associated to that ?
![screen](https://cloud.githubusercontent.com/assets/3512979/10395912/c1f55a8a-6e9f-11e5-8188-4283a2f02efd.png)

**Comment by palinek** [comment]
Why did you submit this twice? #844

**Comment by Esclapion** [comment]
I don't know why it was submitted twice. One is to delete.
