### ISSUE TITLE
LXQt Panel configuration

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#846]
the items should be named with both display language and object name. This is done in the configuration window, but not in the plugin dialog (and to be true - the object names are better, i have to guess, what a plugin will do if i see only the translated names) http://i.imgur.com/QLYYxOA.png

**Comment by palinek** [comment]
There is no object name to show in the add plugin dialog. There are shown the available plugins types (found \*.desktop descriptions) and not instances of the plugins. Are you suggesting to shiw there also the name of the .desktop file?

**Comment by agaida** [comment]
if this are the things in brackets - yes
