### ISSUE TITLE
No transfer rate in file operations dialog

### ISSUE THREAD

**Issue by Atalanttore** [lxde/lxqt#847]
Hi,

there is no transfer rate shown in the file operations dialog. That's bad.

Regards,
Ettore

**Comment by pmattern** [comment]
This badly needs to get elaborated. You didn't even state the LXQt component you deem affected let alone any steps to reproduce your findings.

**Comment by Atalanttore** [comment]
The file operations dialog appears when you copy a file in PCManFM-Qt.

**Comment by PCMan** [comment]
It's already supported by the latest version in git.
