### ISSUE TITLE
Natural scrolling via xmodmap

### ISSUE THREAD

**Issue by tomh0665** [lxde/lxqt#848]
[I'm running Ubuntu 15.10 beta with the lubuntu-daily ppa]

'xmodmap -e "pointer = 1 2 3 5 4 7 6 8 9 10 11 12"' is respected by lxterminal, leafpad, and pcmanfm but not by qterminal, juff, or pcmanfm-qt.

**Comment by surlykke** [comment]
Qt does not look at button numbers when scrolling. Instead of executing the
xmodmap command, I have a file:
/etc/X11/xorg.conf.d/10-naturalscrolling.conf

looking like:

Section "InputClass"
        Identifier "Natural scroll"
        Option "VertScrollDelta" "-50"
        Option "HorizScrollDelta" "-50"
EndSection

br. Chr.

2015-10-12 14:52 GMT+02:00 Tom H <notifications@github.com>:

**Comment by tomh0665** [comment]
Thanks. It's my first interaction with Qt. Sorry for the noise.

**Comment by pmattern** [comment]
@tomh0665 
Couldn't this issue get closed then? Can be done by hitting button `Close and comment` below the form to edit comments, even if nothing was filed in the latter.

**Comment by tomh0665** [comment]
Sorry. Assumed that only a dev could do so. Closing.
