### ISSUE TITLE
GUI: malfunction of button "Add"

### ISSUE THREAD

**Issue by AlfredoRamos** [lxde/lxqt#850]
Hi there,

With the commit lxde/lxqt-globalkeys@f1ebb16 the "Add" button stopped working.

From what I read in the docs, the constructor QModelIndex() creates an invalid index, so It will always exit in the function `MainWindow::editAction()` when checking if it's valid.

Reverting the changes only in that function fixes this issue, but there may be another fix.

**Comment by pmattern** [comment]
Confirmed.
