### ISSUE TITLE
lxqt-config-session: rephrase the Session Restarted Required message info

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#852]
Write it in a non technical / non developer way.
![screen-2015-10-21-20-10-29](https://cloud.githubusercontent.com/assets/62877/10647820/9da1da40-7832-11e5-938e-5483b4a497ea.png)

**Comment by palinek** [comment]
Any suggestion on the worging? (IMO the existing is OK)

**Comment by luis-pereira** [comment]
A non technical / developer user probably doesn't know about `lxqt-session`. 
Something like:
`You need to restart your session to make the settings effective.`
`Just Logout and Login again.`

**Comment by palinek** [comment]
If you have the right wording in you mind... why don't you acctualy create the PR/commit right away?

**Comment by jeremywh7** [comment]
How about something more formal like, "Please restart the session to apply the changes.  Select 'Logout' then login again."

**Comment by Vladimir-csp** [comment]
"Some settings will only be applied to new desktop session. Consider ending current session by logging out."

**Comment by luis-pereira** [comment]
@palinek To raise the discussion before writing the PR.
What about a mix o @jeremywh7  and @Vladimir-csp:

**Some settings will only be applied to new desktop session.**
**Please restart the session to apply the changes. Select 'Logout' then login again.**

**Comment by paulolieuthier** [comment]
> Some settings will only be applied to new desktop session. Please restart the session to apply the changes. Select 'Logout' then login again.

I would only change "new" for "next".

**Comment by jleclanche** [comment]
It doesn't need to be that long, nor even suggest the user *has* to relog immediately. You can just say **Some settings will not take effect until your next log in. Relog to apply all changes.**.

**Comment by jeremywh7** [comment]
In that case, I'd go even simpler, but no pronouns; "Some settings will not take effect until the next log in."

**Comment by paulolieuthier** [comment]
Great.

**Comment by luis-pereira** [comment]
I like @jeremywh7 proposal. Simple and to the point. @jleclanche proposition is also fine :)

**Comment by jleclanche** [comment]
Yeah let's go with that.
