### ISSUE TITLE
[lxqt-panel] Regression: right-click on panel keeps it stuck unhidden until mouse-over

### ISSUE THREAD

**Issue by jeremywh7** [lxde/lxqt#853]
Regression from: https://github.com/lxde/lxqt/issues/629
Right-clicking on any panel element, whether something is selected or not, keeps the panel stuck unhidden (including interaction w/ the desktop or applications) until panel mouse-over.

My update on issue 629, with more details:
@palinek: I've now updated my arch setup to use an AUR helper to build lxqt-desktop-git; I was previously just manually building lxqt-panel-git and its many dependencies. I will note that my system updated to Qt 5.5.1 today too.

It appears this issue has regressed; afaict I am building lxqt-desktop-git correctly; it picked up the lxqt-powermanagement-git change today, and lxqt-panel-git is at change 331 since the last release label.

**Comment by palinek** [comment]
I can't reproduce this on my system right now, so I'm not able to debug and resolve it. But Qt 5.5 is on the way to debian unstable.

Maybe someone else can have a look on it till then...

**Comment by jeremywh7** [comment]
Also; the panel also gets stuck unhidden if the clock is opened (left-clicked).

**Comment by paulolieuthier** [comment]
This is an old bug. AFAIK this has to do with Qt's focus system, which got a little messy in Qt 5. See [this](https://github.com/lxde/lxqt-panel/blob/master/panel/lxqtpanel.cpp#L132).

> I can't reproduce this on my system right now

This comes to me as a surprise.

**Comment by jeremywh7** [comment]
So do you think Qt 5.5.1 reintroduced this bug (which was resolved w/ Qt 5.4.2 and https://github.com/lxde/lxqt-panel/commit/da80ec944051b4a816bc7b6d9afc6d6457cbed12)?

Another quirk which I finally made reproducible...if I load LXQT, wait for the panel to autohide, then mouseover and right click, then un-mouseover; it autohides <b>only this first time</b>.  However, if I left-click (like in the open desktop) first, it will not autohides as per the aforemioned issue.  Thus, there's also a glitch w/ left-clicking and the first hide entry.

**Comment by paulolieuthier** [comment]
Yeah, looks like a regression.

**Comment by jeremywh7** [comment]
I found another mouse-over/click event anomaly; when nested task bar applications are selected (like, if you have two terminals open, and try to access them) and pop-up, the panel autohides when you mouse off the 'panel area' to try and select the application.

**Comment by jeremywh7** [comment]
Can these issues get a 0.10.1 or 0.11 tag?  To summarize them:
1. Right-clicking on any panel element, whether something is selected or not, keeps the panel stuck unhidden (including interaction w/ the desktop or applications) until panel mouse-over. [is this really due to qt-base 5.5.1, and/or to other changes in the panel since the fixes in 629?]
2. The panel also gets stuck unhidden if the clock is opened (left-clicked)
3. If I load LXQT (startx), wait for the panel to autohide, then mouseover and right-click in the panel, then un-mouseover; it autohides only this first time. [I think there are other interactions here still]
4. Nested task bar application mouseover selection hides the panel, and thus also the intended application selection.

**Comment by palinek** [comment]
Working on this... seems that something changed between Qt 5.4 and 5.5. Submitted bug/question to Qt guys - https://bugreports.qt.io/browse/QTBUG-49222

@pmattern don't you have some testing system with Qt 5.4 running to test this one (or even the submitted qt bug scenario)?

**Comment by jeremywh7** [comment]
@palinek @paulolieuthier @pmattern I came across something very interesting last night, working on thte panel & session man pages.  Right before I suspended...I found that the items 1 & 2 were 'fixed'.  Logout and startx...couldn't reproduce it.  Then I thought maybe it was due to having used LibreOffice Writer (rarely use it), esp since I noticed the menus were messed (would only show the text with a mouse-over).

But that wasn't it.  It was Gajim:
Name           : gajim
Version        : 0.16.4-1
Description    : A full featured and easy to use Jabber client
URL            : http://www.gajim.org/
Licenses       : GPL3
Depends On     : pygtk  python2-pyopenssl  python2-pyasn1  python2-nbxmpp  ca-certificates  ldns

This did not affect item 4, which I ran into a lot last night.  :)  Exiting Gajim still retains the 'fix' (until a new session).  Hope this provides some useful clue!

**Comment by jeremywh7** [comment]
If this helps, output of...
strace -f -eopen gajim
...when the issue gets 'fixed' (I disabled the accounts used, to clean up the output):
https://gist.github.com/jeremywh7/ca8fafc8a101d26e3fa6

**Comment by palinek** [comment]
@jeremywh7 I'm also observing something similar.... the installed panel from sidduction autohides correcly. But the one build from latest git suffers from described problems. Strange because the sidduction package is good enough up-to-date...

**Comment by jeremywh7** [comment]
Do you have applications loading at launch?  My LXQt doesn't autoload anything extraneous except (recently) compton (and xcompmgr a few days before that).  Running gajim is the only one I've found that 'fixes' this issue.  Also have run: libreoffice-fresh, diffuse, firefox, and (I think) the LXDE image viewer ...with no change to this issue.

**Comment by jeremywh7** [comment]
@palinek I've found another operation where the panel gets stuck unhidden.  The autohide doesn't recognize the mouseover leave event **through a tooltip popup** *if it straddles between the panel and the desktop area*.  It occurs in all parts of the panel.

**Comment by palinek** [comment]
@jeremywh7 can you, please, check the lxde/lxqt-panel@c4345e8

**Comment by pmattern** [comment]
@palinek 
Problem with tooltips as stated above is fixed in lxde/lxqt-panel@c4345e8.

**Comment by jeremywh7** [comment]
@palinek Done; verified fixed.  Thanks again!
