### ISSUE TITLE
Clicking desktop icon highlights more than one item

### ISSUE THREAD

**Issue by h0llow** [lxde/lxqt#854]
Sorry if this is already in. I did look and see if one was made but didn't see one :)

If I place icons on the desktop and click on it, sometimes it will highlight other items and it is a pain to deselect it. I usually end up clicking whatever I can and trying again. If my memory is correct, I may also be seeing this in PCmanFM, especially if I click a file name that is long.

In the image, I cannot un-select one item, even with the CTRL button pressed. It ends up un-selecting both icons then re-selects it when clicked on.

The only way to get around it is using a mouse and click and drag to make a selection on one icon and move it away.

What I noticed (which I cant explain well) when you start moving the icon, you see the black box surrounding it. If you move the icon anywhere near another one where it would have the imaginary black box (since it's not being moved), then it'll get stuck being selected if you choose either one. In MS Windows terms, it needs icon spacing where it knows not to overlap. Hopefully that makes sense. If not, then I will be more than glad to make a quick video and send it to a dev.
![untitled](https://cloud.githubusercontent.com/assets/15258859/10684801/1e0a6882-7941-11e5-99a1-9225475ffcc6.jpg)

lxqt version: 0.9.0
ArchLinux: newest along with packages updated as of date.

**Comment by stefonarch** [comment]
Duplicate of https://github.com/lxde/lxqt/issues/768 ?

**Comment by h0llow** [comment]
Ahh yes! Haha thank you! I don't know why I couldn't find it.. Maybe it's just been a long day for me -_-
