### ISSUE TITLE
lxqt-leave: Doesn't honor the "Ask for confirmation to leave session" session setting

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#855]
Steps to reproduce:
Call `lxqt-leave` without options. A dialog pops up. Ask for confirmation to leave session setting will be ignored.

**Comment by pmattern** [comment]
IMO the current behaviour makes sense:

The reason to ask for confirmations is to avoid that *a single action* like clicking some button may have a both unwanted and somewhat momentous consequence.
This applies very well to invocations like `lxqt-leave --{logout,reboot}` and so on which do not feature an UI themselves. E. g. clicking a corresponding icon in main menu - Leave without confirmations disabled may indeed be bad.
But unlike this the invocation of `lxqt-leave` without any argument does provide an UI where the user has to chose the action to perform. So an opportunity that a single action like a click in main menu - Leave yields something unwanted basically does not exist. Rather, if the GUI of `lxqt-leave` behaved like those others when confirmation is enabled, the usage would involve three steps, invoking `lxqt-leave` - chose an action - confirm, which doesn't seem very handy to me.

**Comment by jleclanche** [comment]
This is unhelpful when calling `lxqt-leave` from a script though...

**Comment by pmattern** [comment]
> This is unhelpful when calling lxqt-leave from a script though...

Any hint what "This" is meaning here? Invoking `lxqt-leave` without any argument doesn't make sense in scripts anyway as it brings up a GUI.

**Comment by luis-pereira** [comment]
My point here the difference between choosing the Logout directly and choosing Leave > Logout.
Maybe it's just me, but, I was expecting the same behaviour.

**Comment by jleclanche** [comment]
I agree with Luis.
