### ISSUE TITLE
Taskbar items being moved are not themed

### ISSUE THREAD

**Issue by jleclanche** [lxde/lxqt#856]
In a dark theme, the taskbar items are half-themed, still clear.

Milestoned 0.10 if it's simple.

**Comment by paulolieuthier** [comment]
Does it happen after applying lxde/lxqt-panel#253?

**Comment by jleclanche** [comment]
Only affects *unfocused* buttons.

I will test #253 once it's merged, but I think this is a css issue...

**Comment by palinek** [comment]
> I will test #253 once it's merged

I thought you would give it a try as it was you who suggested we need a visual feedback for the button move.

**Comment by palinek** [comment]
Just tested with lxde/lxqt-panel#253 & Dark theme. I don't see any discrepancy either with compton (working transparency) or without it (transparency not working).

**Comment by jleclanche** [comment]
@palinek in my current setup it's not easy to test PRs :/ I'll try to get a better setup going asap, but the move is taking longer than I expected.

**Comment by paulolieuthier** [comment]
@jleclanche please test it now.

**Comment by palinek** [comment]
IMO this should be closed.

**Comment by jleclanche** [comment]
Yeah can close now.
