### ISSUE TITLE
GIMP crashing in LXQT

### ISSUE THREAD

**Issue by janprunk** [lxde/lxqt#858]
Hello !

I noticed GIMP crashing in LXQT on Debian stable when copying cropped image into clipboard.
The error is:

~$ gimp DSC04720.jpg 
(gimp:21861): Gimp-Widgets-CRITICAL **: gimp_device_info_set_device: assertion '(info->device == NULL && GDK_IS_DEVICE (device)) || (GDK_IS_DEVICE (info->device) && device == NULL)' failed
While parsing XMP metadata:
Error: No XMP packet found
The program 'gimp' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 145808 error_code 3 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(script-fu:21866): LibGimpBase-WARNING **: script-fu: gimp_wire_read(): error

~$ dpkg -l |grep lxqt
ii  liblxqt-globalkeys-ui0                 0.9.0+20150926-1~bpo8+1              amd64        daemon used to register global keyboard shortcuts (ui files)
ii  liblxqt-globalkeys0                    0.9.0+20150926-1~bpo8+1              amd64        daemon used to register global keyboard shortcuts (shared libs)
ii  liblxqt0:amd64                         0.9.0+20151024-1~bpo8+1              amd64        Shared libraries for LXQt desktop environment (libs)
ii  lxqt                                   0.9.0-5~bpo8+1                       all          Metapackage for LXQt
ii  lxqt-about                             0.9.0+20150902-2~bpo8+1              amd64        About screen for LXQt
ii  lxqt-admin                             0.9.0+20150830-2~bpo8+1              amd64        Admin tools for LXQt
ii  lxqt-common                            0.9.1+20151003-1~bpo8+1              all          Common files for LXQt
ii  lxqt-config                            0.9.0+20150923-1~bpo8+1              amd64        LXQt system settings center
ii  lxqt-core                              0.9.0-5~bpo8+1                       all          Metapackage for the LXQt core
ii  lxqt-globalkeys                        0.9.0+20150926-1~bpo8+1              amd64        daemon used to register global keyboard shortcuts (appl.)
ii  lxqt-notificationd                     0.9.0+20150903-1~bpo8+1              amd64        LXQt notification daemon
ii  lxqt-openssh-askpass                   0.9.0+20150830-1~bpo8+1              amd64        OpenSSH user/password GUI dialog for LXQt
ii  lxqt-panel                             0.9.0+20150925-1~bpo8+1              amd64        LXQt desktop panel
ii  lxqt-policykit                         0.9.0+20150830-1~bpo8+1              amd64        LXQt authentication agent for PolicyKit
ii  lxqt-powermanagement                   0.9.0+20150930-1~bpo8+1              amd64        power management module for LXQt
ii  lxqt-qtplugin                          0.9.0+20150924-1~bpo8+1              amd64        LXQt system integration plugin for Qt
ii  lxqt-runner                            0.9.0+20150831-1~bpo8+1              amd64        LXQt program launcher
ii  lxqt-session                           0.9.0+20151023-1~bpo8+1              amd64        session manager component for LXQt
ii  lxqt-sudo                              0.9.0+20150908-1~bpo8+1              amd64        Graphical QT frontend for plain sudo

Kind regards, 
Jan

**Comment by agaida** [comment]
nice, you use the siduction backport packages -  if there is a problem with lxqt this is clearly a downstream problem. But a bug in Gimp:
<pre>
(gimp:21861): Gimp-Widgets-CRITICAL **: gimp_device_info_set_device: assertion '(info->device == NULL && GDK_IS_DEVICE (device)) || (GDK_IS_DEVICE (info->device) && device == NULL)' failed
While parsing XMP metadata:
Error: No XMP packet found
</pre>
is not a LXQt upstream nor a downstream problem i think.

**Comment by janprunk** [comment]
The problem was with clipboard manager called "/usr/bin/qlipper", which was causing the GIMP to crash. After disabling qlipper it seemed to work out.

Regards, 
Jan

**Comment by pmattern** [comment]
@janprunk 
If you should be able to figure out what exactly happens or how to reproduce the [devs](https://github.com/pvanek/qlipper) would probably be happy if you opened an issue.

**Comment by agaida** [comment]
whats happend ist easy - qlipper try to 'clip' a object with metadata included - the mechanism of the application don't work well in such cases because of not clean implemented mechanisms for transfering meta-datas into the external clipboad. Worst case is inkscape - now gimp. Until now i never had any problems with gimp, but @janprunk is right and the gimp dev seems to know the problem very well :grimacing:

**Comment by schumaml** [comment]
Um... no, I don't think we do. All we know is that clipboard managers seem to cause this. So if anyone can describe what is happening here, this would be extremely helpful.

**Comment by agaida** [comment]
@schumaml - no problem, but after our release (~ENOTIME) :P

**Comment by janprunk** [comment]
Hi !

There is a more detailed log with "gdb" output on GIMP's/Gnome bugtracker, you can lookup bug number 757070 - https://bugzilla.gnome.org/show_bug.cgi?id=757070

Kind regards, 
Jan

**Comment by palinek** [comment]
Shouldn't this be reported as qlipper issue/bug -> https://github.com/pvanek/qlipper/issues

**Comment by agaida** [comment]
it is a gimp bug. qlipper behave like any other clipboard manager in that case

**Comment by schumaml** [comment]
I hope you still remember to provide us with hints about what to change?

**Comment by agaida** [comment]
ok: not advise people to avoid clipboard managers https://bugzilla.gnome.org/show_bug.cgi?id=757070 - sorry, couldn't resist :) 
second: the image, that create the mess: http://jp.si/DSC07095.JPG
nomacs says about the image:
```
Error: Offset of directory Sony1, entry 0x2001 is out of bounds: Offset = 0x005a005e; truncating the entry
Error: Offset of directory Sony1, entry 0x2001 is out of bounds: Offset = 0x005a005e; truncating the entry
Error: Offset of directory Sony1, entry 0x2001 is out of bounds: Offset = 0x005a005e; truncating the entry
deleting illegal EXIV orientation:  -1
```
```
$ gimp DSC07095.JPG 
(gimp:8008): GLib-GObject-WARNING **: g_object_set_valist: object class 'GeglConfig' has no property named 'cache-size'
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D0130 from "gimp:point-layer-mode" to "gimp:dissolve-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D0600 from "gimp:point-layer-mode" to "gimp:behind-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D0C60 from "gimp:point-layer-mode" to "gimp:multiply-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D1030 from "gimp:point-layer-mode" to "gimp:screen-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D1420 from "gimp:point-layer-mode" to "gimp:overlay-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D1850 from "gimp:point-layer-mode" to "gimp:difference-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D1C10 from "gimp:point-layer-mode" to "gimp:addition-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D2050 from "gimp:point-layer-mode" to "gimp:subtract-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D2410 from "gimp:point-layer-mode" to "gimp:darken-only-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D2860 from "gimp:point-layer-mode" to "gimp:lighten-only-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D2C70 from "gimp:point-layer-mode" to "gimp:hue-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D2FA0 from "gimp:point-layer-mode" to "gimp:saturation-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D3400 from "gimp:point-layer-mode" to "gimp:color-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D3870 from "gimp:point-layer-mode" to "gimp:value-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D3BF0 from "gimp:point-layer-mode" to "gimp:divide-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D4070 from "gimp:point-layer-mode" to "gimp:dodge-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D4C00 from "gimp:point-layer-mode" to "gimp:burn-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D5030 from "gimp:point-layer-mode" to "gimp:hardlight-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D53D0 from "gimp:point-layer-mode" to "gimp:softlight-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D57D0 from "gimp:point-layer-mode" to "gimp:grain-extract-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D5C30 from "gimp:point-layer-mode" to "gimp:grain-merge-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D5FE0 from "gimp:point-layer-mode" to "gimp:color-erase-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D6440 from "gimp:point-layer-mode" to "gimp:erase-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D68A0 from "gimp:point-layer-mode" to "gimp:replace-mode"
(gimp:8008): GEGL-gegl-operation.c-WARNING **: Cannot change name of operation class 0x28D6C40 from "gimp:point-layer-mode" to "gimp:anti-erase-mode"
While parsing XMP metadata:
Fehler: Es wurde kein XMP-Paket gefunden
(gimp:8008): Gdk-CRITICAL **: IA__gdk_window_get_events: assertion 'GDK_IS_WINDOW (window)' failed
(gimp:8008): Gdk-CRITICAL **: IA__gdk_window_set_events: assertion 'GDK_IS_WINDOW (window)' failed
(gimp:8008): Gdk-CRITICAL **: IA__gdk_window_get_events: assertion 'GDK_IS_WINDOW (window)' failed
(gimp:8008): Gdk-CRITICAL **: IA__gdk_window_set_events: assertion 'GDK_IS_WINDOW (window)' failed
(gimp:8008): Gdk-CRITICAL **: IA__gdk_window_get_events: assertion 'GDK_IS_WINDOW (window)' failed
(gimp:8008): Gdk-CRITICAL **: IA__gdk_window_set_events: assertion 'GDK_IS_WINDOW (window)' failed
(gimp:8008): Gdk-CRITICAL **: IA__gdk_window_get_events: assertion 'GDK_IS_WINDOW (window)' failed
(gimp:8008): Gdk-CRITICAL **: IA__gdk_window_set_events: assertion 'GDK_IS_WINDOW (window)' failed
(gimp:8008): Gdk-CRITICAL **: IA__gdk_window_get_events: assertion 'GDK_IS_WINDOW (window)' failed
(gimp:8008): Gdk-CRITICAL **: IA__gdk_window_set_events: assertion 'GDK_IS_WINDOW (window)' failed
The program 'gimp' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 65776 error_code 3 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
(script-fu:8019): LibGimpBase-WARNING **: script-fu: gimp_wire_read(): error
```
If you want a backtrace from an up to date sid system i can create one.

**Comment by agaida** [comment]
btw - some month later it don't crash that hard anymore - one have to do more copy actions until gimp finally crashes.

**Comment by pvanek** [comment]
I will look at it soon or later in qlipper itself

**Comment by agaida** [comment]
@pvanek - i'm afraid that you can't do much about - it's the same thing we encounter in inkscape for years. one try to clip something and the appclication in charge try to deliver and than behave not so kind. But good luck anyways..

**Comment by tsujan** [comment]
> i'm afraid that you can't do much about

I use Inkscape a lot. Neither when I was a KDE user (with klipper) nor now under LXQT (with clipit), I've had any problem with clipping. I've also done lots of cropping, copying and clipping with Krita and Gimp with no problem. So this should be a qlipper bug. Most probably, its developer could find and fix it.

**Comment by schumaml** [comment]
What would be nice is some hints along the lines of:

qlipper does $foo.
Any application involved in clipboard handling should do $bar, but must not do $baz.

That description should be on a coding or meta-coding level.

**Comment by agaida** [comment]
i'm out of this

**Comment by palinek** [comment]
Just made simple test:
- runnig qlipper (with some added debug output)
- starting gimp with an .png image 640x400 (only white background)
- choosing "Rectangle Select Tool"
- click on the image/canvas
- changing the selection by inserting the "Position:" -> 0, 0 & "Size:' -> 1 x 1
- pressing ctrl+c
- gimp crashing

The data receieved into qlipper from clipboard -> https://gist.github.com/palinek/039be10ca74d97088dd1

This seems like a bunch of trash.... but qlipper doesn't set the clipboard in any way (until the clipboard owner/gimp dies).

Could it be that gimp somehow doesn't like that someone instantly reads the clipboard content?

**Comment by palinek** [comment]
Or event the most simple qt testing program... (steps to reproduce are the same)
```c++
#include <QApplication>
#include <QClipboard>
#include <QMimeData>
#include <QDebug>

int main(int argc, char * argv[])
{
    QApplication app{argc, argv};
    QObject::connect(QApplication::clipboard(), &QClipboard::changed, [] (QClipboard::Mode mode)
    {   
        qDebug() << Q_FUNC_INFO << "-----------------------------------";
        const QMimeData * mime = QApplication::clipboard()->mimeData(mode);
        for (const auto & format : mime->formats())
        {   
            qDebug().noquote() << format << ": " << mime->data(format).toBase64();
         }
    });

    return app.exec();
}
```
The content of clipboard -> https://gist.github.com/palinek/31a61ff09a1f25dc8871

**Comment by tsujan** [comment]
> This seems like a bunch of trash

I don't think so. It's the copied image.

**Comment by tsujan** [comment]
I haven't tried qlipper yet but, theoretically, the fix seems simple: "don't copy images from clipboard!" (sorry if programmatically it's not simple)

**Comment by palinek** [comment]
Wel.. it definitely seems like some interaction problem. Should the reading of clipboard in Qt be postponed, like e.g. (1 second delay):
```c++
#include <QApplication>
#include <QClipboard>
#include <QMimeData>
#include <QDebug>
#include <QTimer>

int main(int argc, char * argv[])
{
    QApplication app{argc, argv};
    QObject::connect(QApplication::clipboard(), &QClipboard::changed, [] (QClipboard::Mode mode)
    {   
        qDebug() << Q_FUNC_INFO << "-----------------------------------";
        QClipboard::Mode l_mode = mode;
        QTimer::singleShot(1000, [l_mode]
        {   
            const QMimeData * mime = QApplication::clipboard()->mimeData(l_mode);
            for (const auto & format : mime->formats())
            {   
                qDebug().noquote() << format << ": " << mime->data(format).toBase64();
             }
         });
    });

    return app.exec();
}
```
... then gimp will not crash.

@schumaml will this help you?

**Comment by tsujan** [comment]
> ... Should the reading of clipboard in Qt be postponed...

Just a word: if `QTimer::singleShot(0, X)` doesn't work, putting any value in place of `0` will mean relying on chance (CPU power and other circumstances).

**Comment by palinek** [comment]
Another hint: If we don't use/store the `image/x-bitmap` & `image/x-MS-bitmap` in qlipper, then gimp is not crashing. That means this patch:
```diff
diff --git a/src/qlipperitem.cpp b/src/qlipperitem.cpp
index 2a5d859..0fc4ccf 100644
--- a/src/qlipperitem.cpp
+++ b/src/qlipperitem.cpp
@@ -62,7 +62,8 @@ QlipperItem::QlipperItem(QClipboard::Mode mode)
     foreach (QString format, mimeData->formats())
     {
         //qDebug() << format << mimeData->data(format);
-        m_content[format] = mimeData->data(format);
+        if (QStringLiteral("image/x-MS-bmp") != format && QStringLiteral("image/x-bmp") != format)
+            m_content[format] = mimeData->data(format);
     }
 
     m_display = mimeData->text();
```

**Comment by palinek** [comment]
Another review of gimp code and its debug:
```
$ gimp --sync --verbose ~/tmp/downloads/test_white.png
INIT: gimp_load_config
Parsing '/home/palco/.gimp-2.8/unitrc'
Parsing '/etc/gimp/2.0/gimprc'
Parsing '/home/palco/.gimp-2.8/gimprc'
gimp_composite: verbose=no
Processor instruction sets: +mmx +sse +sse2 -3dnow -altivec -vis

(gimp:25071): GLib-GObject-WARNING **: g_object_set_valist: object class 'GeglConfig' has no property named 'cache-size'

$ gimp --sync --verbose ~/tmp/downloads/test_white.png
INIT: gimp_load_config
Parsing '/home/palco/.gimp-2.8/unitrc'
Parsing '/etc/gimp/2.0/gimprc'
Parsing '/home/palco/.gimp-2.8/gimprc'
gimp_composite: verbose=no
Processor instruction sets: +mmx +sse +sse2 -3dnow -altivec -vis

(gimp:25071): GLib-GObject-WARNING **: g_object_set_valist: object class 'GeglConfig' has no property named 'cache-size'
...
clipboard: writable pixbuf format: image/png
clipboard: writable pixbuf format: image/bmp
clipboard: writable pixbuf format: image/x-bmp
clipboard: writable pixbuf format: image/x-MS-bmp
clipboard: writable pixbuf format: image/x-icon
clipboard: writable pixbuf format: image/x-ico
clipboard: writable pixbuf format: image/x-win-bitmap
clipboard: writable pixbuf format: image/vnd.microsoft.icon
clipboard: writable pixbuf format: application/ico
clipboard: writable pixbuf format: image/ico
clipboard: writable pixbuf format: image/icon
clipboard: writable pixbuf format: text/ico
clipboard: writable pixbuf format: image/tiff
clipboard: writable pixbuf format: image/jpeg

(gimp:25086): Gimp-Widgets-CRITICAL **: gimp_device_info_set_device: assertion '(info->device == NULL && GDK_IS_DEVICE (device)) || (GDK_IS_DEVICE (info->device) && device == NULL)' failed
Parsing '/home/palco/.gimp-2.8/sessionrc'
...

clipboard: sending pixbuf data as 'image/png'
clipboard: sending pixbuf data as 'image/bmp'
clipboard: sending pixbuf data as 'image/x-bmp'
The program 'gimp' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 64012 error_code 3 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(script-fu:25093): LibGimpBase-WARNING **: script-fu: gimp_wire_read(): error
```
... so the crash is somewhere here -> https://github.com/GNOME/gimp/blob/master/app/widgets/gimpclipboard.c#L896

This crash does happen only if the the (opposite) application is trying to read the `image/x-bmp` data.
Don't konw much about neither gimp nor gdk or how it works... but can the gdk loader for bmb be somehow broken (if it is flushing the same picture multiple times)?

**Comment by tsujan** [comment]
What about this, quoted from http://doc.qt.io/qt-5/qclipboard.html#notes-for-x11-users :

"You should not store or retrieve the clipboard contents in response to timer or non-user-input events."

**Comment by tsujan** [comment]
OK, I had time to look into qlipper's code but before that, I tested gimp-2.8.16 with qlipper-5.0.0 from Debian and, whatever I did, no crash occurred. I also tested @palinek's code: still no crash and the output was OK:
````
...
image/bmp :  Qk06AAAAAAAAADYAAAAoAAAAAQAAAAEAAAABABgAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAA////8g==
image/x-bmp :  Qk06AAAAAAAAADYAAAAoAAAAAQAAAAEAAAABABgAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAA////8g==
...
application/x-qt-image :  iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAABHNCSVQICAgIfAhkiAAAAAtJREFUCFtj+A8EAAn7A/2fHywAAAAAAElFTkSuQmCC
````
So, there was no need to study qlipper's code ;)

**Comment by agaida** [comment]
@tsujan - have you done your tests with the provided picture?

**Comment by tsujan** [comment]
> have you done your tests with the provided picture?

No, I did it as @palinek told and also with a few PNG images. But after reading your comment, I tested with that picture and *yes, this time the crash happened.*

Even without this crash, considering @palinek's tests, I was going to say that the bug existed but wasn't reproducible with all CPUs or images.

IMO, the bug is in qlipper, not in gimp or gtk2, and I still think there's something important in the above-mentioned quote from Qt doc.

**Comment by agaida** [comment]
@tsujan - the next test could be: open the image in nomacs and then save it without further manipulation. This could result in an image with corrected meta datas - it would be nice to see the if the so modificated image works with gimp and qlipper. And by the way - i had an image with totally stripped meta-datas - result: no crashes. So i guess the bug is in gimp and the handling of meta datas.

**Comment by tsujan** [comment]
> it would be nice to see the if the so modificated image works with gimp and qlipper.

But that wouldn't explain why the crash happens only when the data is *read* from clipboard by using `Clipboard::changed()`. As I said earlier, clipit and, perhaps, other clipboard managers don't have any problem with gimp and that image.

Tomorrow I might have time to do some tests in other directions. If we put together @palinek's, yours and my tests, we might reach a conclusion.

**Comment by tsujan** [comment]
The result of my tests:

Reading the data of each format *alone* doesn't cause any crash -- not even `image/x-bmp` or `image/x-MS-bmp`. The crash only happens when the data of all or many formats are read together (by `foreach`). Usually there's only one format but, in the case of copying a selection with GIMP, there are 15 formats! This situation may happen with other image editors or even other apps too.

A look at `klipper.cpp` shows that Klipper does the job in a fundamentally different way. IMO, this issue shows that we lack some basic knowledge about how QClipboard works under x11.

**Comment by tsujan** [comment]
This should prevent the crash:
````
diff -ruNp qlipper-orig/src/qlipperitem.cpp qlipper/src/qlipperitem.cpp
--- qlipper-orig/src/qlipperitem.cpp
+++ qlipper/src/qlipperitem.cpp
@@ -59,9 +59,17 @@ QlipperItem::QlipperItem(QClipboard::Mod
         m_enforceHistory = true;
     }
 
+    bool binaryFound(false);
     foreach (QString format, mimeData->formats())
     {
         //qDebug() << format << mimeData->data(format);
+        if (format != "text/plain" && format != "text/uri-list" && format != "text/html")
+        {
+            if (binaryFound)
+                continue;
+            else
+                binaryFound = true;
+        }
         m_content[format] = mimeData->data(format);
     }
 

````

**Comment by agaida** [comment]
really impressive - will test the patch today evening
