### ISSUE TITLE
maximized windows partially hidden behind panel on multi-monitor systems

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#861]
Pull request lxde/lxqt-panel#225 introduced some different behaviour of windows when the panel's auto-hide feature is enabled but caused a regression due to which the bottom part of maximized windows may get hidden behind the panel when the auto-hide feature is *dis*abled.

The problem appears e. g. on a dual-monitor system if the panel is placed at the bottom of the output (in terms of xrandr) with the smaller vertical resolution. Windows displayed on that output aren't aware of the panel then and hence their bottom part gets hidden behind it upon maximizing.
Problem cannot be seen if the panel is placed at the bottom or left / right edge of outputs.
It is apparently independent from the window manager as it can be seen with Openbox, KWin and Xfwm. It doesn't seem to be hardware-specific as the findings were the same using the DVI and VGA output of a Radeon IGP or two virtual outputs provided by the QXL graphics card of SPICE in a KVM/QEMU virtual machine.

IMO this regression outweighs the eventual benefit of the new behaviour and isn't something that should make it to a release. I think the problem should either get fixed before 0.10 or the commits in question should get reverted until a solution is found.

[EDIT state actual problem a bit more precisely]

**Comment by palinek** [comment]
Still no luck to reproduce the described bug here (followed all the steps)...

(debian unstable + siduction)

**Comment by pmattern** [comment]
Weird.
Still seeing the problem. Some minor details are different than I first thought so I edited the first comment a bit.
Maybe we should try and discuss this on IRC some time.

**Comment by palinek** [comment]
> The problem appears e. g. on a dual-monitor system as soon as the panel is on the output (in terms of xrandr) with the smaller vertical resolution.

This may be the clue... will try it later.

**Comment by palinek** [comment]
@pmattern finally simulated the behaviour.... please, have a look in lxde/lxqt-panel#269

**Comment by pmattern** [comment]
The actual problem is fixed by lxde/lxqt-panel@ff680ae, windows are always aware of the panel and maximizing works as expected.

While testing I stumbled upon some misbehaviour regarding the numbering of outputs.
"bare metal" changing the panel's position sometimes doesn't yield any effect. Say the panel's current position is stated as `Bottom of desktop 2` at "Configure Panel (context menu panel) - Panel (left pane) - Alignment & position - Position". Then switching to `Bottom of desktop 1` sometimes doesn't have any effect. `Top of desktop 1` behaves as expected, though, and makes `Bottom of desktop {1,2}` behave as expected, too.
In that VM featuring a virtual multi-head system it was even worse. Sometimes switching from `Bottom of desktop n` to `Top of desktop m` made the panel disappear altogether. When two outputs were placed adjacent the regular six options `{Top,Left,Bottom} of desktop 1` and `{Top,Right,Bottom} of desktop 2` sometimes were reduced to `{Top,Left} of desktop 1` and `{Right,Bottom} of desktop 2`. Also, panel GUIs components like the main menu itself or all context menus sometimes were completely dysfunctional after changing resolutions, similar to the findings described in #520.
The findings "bare metal" seems to be the same running e. g. lxde/lxqt-panel@52d2f72 and I digged into that virtual multi-head stuff some days ago only so couldn't tell whether the findings may be caused by the VM itself.

Considering that whole thing it's a bit odd that a new release is scheduled for tomorrow. But all in all I'd vote for shipping lxde/lxqt-panel@ff680ae nevertheless as it definitely looks like an improvement all in all.

**Comment by eyalroz** [comment]
I _think_ I am seeing this problem on my Lubuntu 15.10 . That is, the effect is the same; and while I don't use two monitors, it's a laptop, and a second monitor is often connected. Just to be clear - the bottom edge of a maximized window is behind the panel. Is this possible/making sense?

**Comment by pmattern** [comment]
@eyalroz 
> Is this possible/making sense?

Your system can very well be affected if you happen to use a commit were the problem which was a regression hadn't been fixed yet.
Could you please tell us which way you installed LXQt on your system?

**Comment by josehfurtado** [comment]
I installed LXQt in Xubuntu and removed XFCE. I'm using Two monitors and the notebook one is deactivated. I just need a big screen. The problem is, left side to the desktop can't be clicked at all. It's difficult to use auto hide function on LXQt panel on the left side. Is it a LXQt problem, Ubuntu or hardware?
