### ISSUE TITLE
lxqt-panel: issues with dual-head monitor (nvidia)

### ISSUE THREAD

**Issue by dbautistadecabo** [lxde/lxqt#862]
Hi!

With the last update to LXQt 0.9.0 (I still was in 0.7.0) in Gentoo Linux, when I login into lxqt, suddenly the taskbar disappears and the background changes to the previous lightdm background (although the background is still seen in a minimal square in the top-left corner of the first monitor). I have updated several computers to LXQt 0.9.0 with no problem (one monitor and intel card) but with mine (two nvidias) I have this weird problem...

I have tried to login from lightdm and kdm, or executing startx but with no success. If I kill the pcmanfm-qt process the lxqt background reappears, but I haven't been able to get the taskbar to appear...

Can someone help me?

Thanks in advance!

**Comment by Vladimir-csp** [comment]
> taskbar disappears and the background changes to the previous lightdm background

That looks as if lxqt-panel and pcmanfm-qt crash.  Which menu appears if you make right click on desktop just after that?

**Comment by dbautistadecabo** [comment]
An openbox menu, I think. Not the usual lxqt menu.

**Comment by Vladimir-csp** [comment]
This means that pcmanfm-qt desktop handler is not running.
Look at ~/.xsession-errors for clues.

**Comment by dbautistadecabo** [comment]
![lxqt9_snapshot](https://cloud.githubusercontent.com/assets/11425458/10868724/1623efc6-808f-11e5-8386-23ab7cdc0de9.jpg)

**Comment by dbautistadecabo** [comment]
xsession-errors:

Xlib:  extension "RANDR" missing on display ":0".
LxQt::Translator: Qt translations not found
iconTheme "oxygen"
iconTheme "oxygen"
iconTheme "oxygen"
iconTheme "oxygen"
Theme: Cannot open file for reading: "/usr/share/lxqt/themes/Frost/lxqt-session.qss"
/var/tmp/portage/lxqt-base/lxqt-session-0.9.0-r1/work/lxqt-session-0.9.0/lxqt-session/src/sessionapplication.cpp : 74 Session "session" about to launch (default 'session')
Environment variable BROWSER = firefox
Environment variable GTK_CSD = 0
Environment variable TERM = konsole
"/home/daniel/.config/lxqt/session.conf"
xrdb: Xcursor.theme:whiteglass
Xcursor.size:18
Xcursor.theme_core:true

Window Manager started
start "/home/daniel/.config/autostart/hplip-systray.desktop"
start "/home/daniel/.config/autostart/kopete.desktop"
start "/home/daniel/.config/autostart/qsynergy.desktop"
start "/home/daniel/.config/autostart/thunderbird.desktop"
start "/etc/xdg/autostart/lxqt-desktop.desktop"
start "/etc/xdg/autostart/lxqt-globalkeyshortcuts.desktop"
start "/etc/xdg/autostart/lxqt-notifications.desktop"
start "/etc/xdg/autostart/lxqt-panel.desktop"
start "/etc/xdg/autostart/lxqt-policykit-agent.desktop"
start "/etc/xdg/autostart/lxqt-runner.desktop"

(process:24256): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Xlib:  extension "RANDR" missing on display ":0".
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
start "/etc/xdg/autostart/lxqt-xscreensaver-autostart.desktop"
Xlib:  extension "RANDR" missing on display ":0".
kbuildsycoca4 running...

(thunderbird:24256): GLib-GIO-WARNING **: /usr/share/applications/defaults.list contains a [Added Associations] group, but it is not permitted here.  Only the non-desktop-specific mimeapps.list file may add or remove associations.
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
No systemtrayicon available
QSystemTrayIcon::setVisible: No Icon set
No systemtrayicon available
QDBusConnection: name 'org.kde.kglobalaccel' had owner '' but we thought it was ':1.22'
kopete(24258)/kdecore (KLibrary) kde4Factory: The library "/usr/lib64/kde4/kopete_history.so" does not offer a qt_plugin_instance function.
kopete(24258)/libkopete Kopete::PluginManager::loadPluginInternal: Unable to find a plugin named ' "kopete_msn" '! 
kopete(24258)/libkopete Kopete::PluginManager::loadPluginInternal: Unable to find a plugin named ' "" '! 
kio_file(24339) kdemain: Starting 24339
QDBusConnection: name 'org.kde.kwalletd' had owner '' but we thought it was ':1.28'
Unknown signature value:  795 
Unknown signature value:  795 
Unknown signature value:  795 
Unknown signature value:  795 
Unknown signature value:  795 
Unknown signature value:  795 
Unknown signature value:  7 
Unknown signature value:  795 

(thunderbird:24256): Gtk-CRITICAL **: IA__gtk_icon_theme_append_search_path: assertion 'path != NULL' failed
unexpected version response
*** WARNING *** The program 'qsynergy' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=qsynergy>
*** WARNING *** The program 'qsynergy' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=qsynergy&f=DNSServiceRegister>
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.0.29/work/alsa-lib-1.0.29/src/pcm/pcm_route.c:867:(find_matching_chmap) Found no matching channel map
kio_file(24421) kdemain: Starting 24421
kio_file(24421) kdemain: Done

**Comment by dbautistadecabo** [comment]
ps xaufwww:

root     24167  0.0  0.1 288904  8104 ?        SLsl 11:39   0:00 /usr/sbin/lightdm
root     24174  3.3  1.7 208304 108016 tty7    Ss+  11:39   0:04  \_ /usr/bin/X :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
root     24204  0.0  0.1 159796  6348 ?        Sl   11:39   0:00  \_ lightdm --session-child 11 18
daniel   24224  0.1  0.7 374172 46952 ?        Ssl  11:39   0:00      \_ lxqt-session
daniel   24247  0.1  0.6 234960 41976 ?        S    11:39   0:00          \_ openbox
daniel   24257  1.1  0.8 630996 54440 ?        Sl   11:39   0:01          \_ pcmanfm-qt --desktop --profile=lxqt
daniel   24259  0.0  0.1 155676 10292 ?        Sl   11:39   0:00          \_ lxqt-globalkeysd
daniel   24260  0.0  0.7 300408 45496 ?        Sl   11:39   0:00          \_ lxqt-notificationd
daniel   24261  0.2  0.9 518004 58192 ?        Sl   11:39   0:00          \_ lxqt-panel
daniel   24262  0.0  0.7 394888 48364 ?        Sl   11:39   0:00          \_ lxqt-policykit-agent
daniel   24263  1.3  0.9 498884 56444 ?        Sl   11:39   0:01          \_ lxqt-runner

**Comment by dbautistadecabo** [comment]
I can't see anything relevant in the xsession-errors, pcmanfm-qt is running and I have not found traces of crashes. But yes, it seems that something happens with pcmanfm-qt and lxqt-panel...

This is what I have installed:

 `--  lxqt-base/lxqt-meta-0.9.0-r2  ~amd64 
   `--  lxde-base/lxmenu-data-0.1.2  (>=lxde-base/lxmenu-data-0.1.2) amd64 
   `--  lxqt-base/lxqt-about-0.9.0  (~lxqt-base/lxqt-about-0.9.0) ~amd64 
   `--  lxqt-base/lxqt-common-0.9.1  (=lxqt-base/lxqt-common-0.9*) ~amd64 
   `--  lxqt-base/lxqt-config-0.9.0  (~lxqt-base/lxqt-config-0.9.0) ~amd64 
   `--  lxqt-base/lxqt-globalkeys-0.9.0  (~lxqt-base/lxqt-globalkeys-0.9.0) ~amd64 
   `--  lxqt-base/lxqt-notificationd-0.9.0-r1  (~lxqt-base/lxqt-notificationd-0.9.0) ~amd64 
   `--  lxqt-base/lxqt-panel-0.9.0  (~lxqt-base/lxqt-panel-0.9.0) ~amd64 
   `--  lxqt-base/lxqt-qtplugin-0.9.0  (~lxqt-base/lxqt-qtplugin-0.9.0) ~amd64 
   `--  lxqt-base/lxqt-runner-0.9.0  (~lxqt-base/lxqt-runner-0.9.0) ~amd64 
   `--  lxqt-base/lxqt-session-0.9.0-r1  (~lxqt-base/lxqt-session-0.9.0) ~amd64 
   `--  virtual/ttf-fonts-1  (virtual/ttf-fonts) amd64 
   `--  lxqt-base/lxqt-admin-0.9.0  (~lxqt-base/lxqt-admin-0.9.0) ~amd64 [NOT INSTALLED]
   `--  x11-misc/pcmanfm-qt-0.9.0  (~x11-misc/pcmanfm-qt-0.9.0) ~amd64 
   `--  kde-apps/oxygen-icons-4.14.3  (kde-apps/oxygen-icons) amd64 
   `--  virtual/freedesktop-icon-theme-0  (virtual/freedesktop-icon-theme) amd64 
   `--  x11-misc/lightdm-1.10.5  (x11-misc/lightdm) amd64 
   `--  media-gfx/lximage-qt-0.4.0  (media-gfx/lximage-qt) ~amd64 
   `--  x11-wm/openbox-3.5.2-r1  (x11-wm/openbox) amd64 
   `--  x11-misc/obconf-qt-0.9.0_p20150729  (x11-misc/obconf-qt) ~amd64 
   `--  lxqt-base/lxqt-policykit-0.9.0  (~lxqt-base/lxqt-policykit-0.9.0) ~amd64 
   `--  sys-auth/consolekit-0.4.6  (sys-auth/consolekit) amd64  [policykit(-)]
   `--  sys-apps/systemd-218-r5  (sys-apps/systemd) amd64  [policykit(-)]
   `--  lxqt-base/lxqt-powermanagement-0.9.0  (~lxqt-base/lxqt-powermanagement-0.9.0) ~amd64 [NOT INSTALLED]
   `--  x11-misc/sddm-0.12.0-r1  (>=x11-misc/sddm-0.10.0) ~amd64 [NOT INSTALLED]
   `--  lxqt-base/lxqt-openssh-askpass-0.9.0  (~lxqt-base/lxqt-openssh-askpass-0.9.0) ~amd64 [NOT INSTALLED]

**Comment by dbautistadecabo** [comment]
If you need more logs, don't hesitate to ask.

**Comment by dbautistadecabo** [comment]
I confirm that this is also happening in LXQt 0.10.0.

Packages installed:

--  lxqt-base/lxqt-meta-0.10.0  ~amd64 
--  lxde-base/lxmenu-data-0.1.2  (>=lxde-base/lxmenu-data-0.1.2) amd64 
--  lxqt-base/lxqt-common-0.10.0  (=lxqt-base/lxqt-common-0.10*) ~amd64 
--  lxqt-base/lxqt-config-0.10.0  (~lxqt-base/lxqt-config-0.10.0) ~amd64 
--  lxqt-base/lxqt-globalkeys-0.10.0  (~lxqt-base/lxqt-globalkeys-0.10.0) ~amd64 
--  lxqt-base/lxqt-notificationd-0.10.0  (~lxqt-base/lxqt-notificationd-0.10.0) ~amd64 
--  lxqt-base/lxqt-panel-0.10.0  (~lxqt-base/lxqt-panel-0.10.0) ~amd64 
--  lxqt-base/lxqt-qtplugin-0.10.0  (~lxqt-base/lxqt-qtplugin-0.10.0) ~amd64 
--  lxqt-base/lxqt-runner-0.10.0  (~lxqt-base/lxqt-runner-0.10.0) ~amd64 
--  lxqt-base/lxqt-session-0.10.0  (~lxqt-base/lxqt-session-0.10.0) ~amd64 
--  lxqt-base/lxqt-policykit-0.10.0  (~lxqt-base/lxqt-policykit-0.10.0) ~amd64 
--  lxqt-base/lxqt-about-0.10.0  (~lxqt-base/lxqt-about-0.10.0) ~amd64 
--  x11-misc/pcmanfm-qt-0.10.0  (~x11-misc/pcmanfm-qt-0.10.0) ~amd64 
--  virtual/ttf-fonts-1  (virtual/ttf-fonts) amd64 
--  virtual/freedesktop-icon-theme-0  (virtual/freedesktop-icon-theme) amd64 
--  x11-misc/lightdm-1.10.5  (x11-misc/lightdm) amd64 
--  media-gfx/lximage-qt-0.4.0  (media-gfx/lximage-qt) ~amd64 
--  x11-wm/openbox-3.5.2-r1  (x11-wm/openbox) amd64 
--  x11-misc/obconf-qt-0.9.0_p20150729  (x11-misc/obconf-qt) ~amd64 
--  sys-auth/consolekit-0.4.6  (sys-auth/consolekit) amd64  [policykit(-)]
--  kde-frameworks/oxygen-icons-4.14.3  (kde-frameworks/oxygen-icons) amd64 
--  kde-frameworks/extra-cmake-modules-5.16.0  ~amd64
--  kde-frameworks/solid-5.16.0  ~amd64
--  kde-frameworks/kwindowsystem-5.14.0  ~amd64
--  kde-frameworks/kguiaddons-5.14.0  ~amd64
--  dev-qt/qtdbus-5.4.2  (dev-qt/qtdbus) ~amd64 
--  dev-qt/qtdeclarative-5.4.2-r1  (dev-qt/qtdeclarative) amd64 
--  dev-qt/qtwidgets-5.4.2  (dev-qt/qtwidgets) ~amd64 
--  dev-qt/qtxml-5.4.2  (dev-qt/qtxml) amd64 
--  dev-qt/linguist-tools-5.4.2  (dev-qt/linguist-tools) amd64 
--  dev-qt/qtconcurrent-5.4.2  (dev-qt/qtconcurrent) amd64 
--  dev-qt/qttest-5.4.2  (>=dev-qt/qttest-5.4.2) amd64 
--  dev-qt/qtcore-5.4.2  (>=dev-qt/qtcore-5.4.2) ~amd64 
--  sys-fs/udisks-2.1.4  (sys-fs/udisks) amd64 
--  virtual/udev-215  (virtual/udev) amd64 
--  x11-drivers/nvidia-drivers-340.96  ~amd64
--  x11-base/xorg-server-1.16.4  (<x11-base/xorg-server-1.17.99) amd64

**Comment by palinek** [comment]
Can you try to run e.g. the `lxqt-panel` from terminal and paste the output (stdout, stderr and/or anything supicious)?

**Comment by dbautistadecabo** [comment]
I cannot see anything suspicious:

    daniel@pc-daniel ~ $ lxqt-panel
    WinIdChange 3c00007 handle QWidgetWindow(0x24f75e0, name = "LXQtPanel panel1Window") QScreen(0x24b82f0)
    Another systray is running
    ^C
    
    daniel@pc-daniel ~ $ killall -9 lxqt-panel ; lxqt-panel
    WinIdChange 1a00007 handle QWidgetWindow(0x21f5e10, name = "LXQtPanel panel1Window") QScreen(0x2057b90)
    Systray started
    ^C
    
    daniel@pc-daniel ~ $ killall -9 pcmanfm-qt ; pcmanfm-qt --desktop --profile=lxqt
    isPrimaryInstance
    desktopManager: 1
    size of cached file QSize(54, 54) , requiredSize: QSize(3840, 1080)
    no cached wallpaper. generate a new one!
    size of original image QSize(0, 0)
    winid change: 27262981
    desktopManager: 1
    ^C

.xsession-errors:

    Xlib:  extension "RANDR" missing on display ":0".
    /var/tmp/portage/lxqt-base/lxqt-session-0.10.0/work/lxqt-session-0.10.0/lxqt-session/src/sessionapplication.cpp : 76 Session "session" about to launch (default 'session')
    Environment variable BROWSER = firefox
    Environment variable GTK_CSD = 0
    Environment variable TERM = konsole
    "/home/daniel/.config/lxqt/session.conf"
    xrdb: Xcursor.theme:whiteglass
    Xcursor.size:18
    Xcursor.theme_core:true
    
    Window Manager started
    start "/home/daniel/.config/autostart/Gentoo-print-applet.desktop"
    start "/home/daniel/.config/autostart/hplip-systray.desktop"
    start "/home/daniel/.config/autostart/kopete.desktop"                                                                                                                                                                                        
    start "/home/daniel/.config/autostart/qsynergy.desktop"                                                                                                                                                                                      
    start "/home/daniel/.config/autostart/thunderbird.desktop"                                                                                                                                                                                   
    start "/etc/xdg/autostart/lxqt-desktop.desktop"                                                                                                                                                                                              
    start "/etc/xdg/autostart/lxqt-globalkeyshortcuts.desktop"                                                                                                                                                                                   
    start "/etc/xdg/autostart/lxqt-notifications.desktop"                                                                                                                                                                                        
    start "/etc/xdg/autostart/lxqt-panel.desktop"                                                                                                                                                                                                
    start "/etc/xdg/autostart/lxqt-policykit-agent.desktop"                                                                                                                                                                                      
    start "/etc/xdg/autostart/lxqt-runner.desktop"                                                                                                                                                                                               
                                                                                                                                                                                                                                                 
    (process:13033): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed                                                                                                                                                 
    start "/etc/xdg/autostart/lxqt-xscreensaver-autostart.desktop"                                                                                                                                                                               
    Xlib:  extension "RANDR" missing on display ":0".                                                                                                                                                                                            
    start "/etc/xdg/autostart/polkit-gnome-authentication-agent-1.desktop"                                                                                                                                                                       
    Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)                                                                                                                                       
    Xlib:  extension "RANDR" missing on display ":0".                                                                                                                                                                                            
    /usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK                                                                                                 
      set_interactive(1)                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                 
    ** (polkit-gnome-authentication-agent-1:13046): WARNING **: Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject                       
    Cannot register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject                                                                                      
    kbuildsycoca4 running...                                                                                                                                                                                                                     
    No systemtrayicon available                                                                                                                                                                                                                  
    QSystemTrayIcon::setVisible: No Icon set                                                                                                                                                                                                     
    No systemtrayicon available                                                                                                                                                                                                                  
    
    (thunderbird:13033): GLib-GIO-WARNING **: /usr/share/applications/defaults.list contains a [Added Associations] group, but it is not permitted here.  Only the non-desktop-specific mimeapps.list file may add or remove associations.
    QDBusConnection: name 'org.kde.kglobalaccel' had owner '' but we thought it was ':1.30'
    kopete(13032)/kdecore (KLibrary) kde4Factory: The library "/usr/lib64/kde4/kopete_history.so" does not offer a qt_plugin_instance function.
    kopete(13032)/libkopete Kopete::PluginManager::loadPluginInternal: Unable to find a plugin named ' "kopete_msn" '! 
    kopete(13032)/libkopete Kopete::PluginManager::loadPluginInternal: Unable to find a plugin named ' "" '! 
    QDBusConnection: name 'org.kde.kwalletd' had owner '' but we thought it was ':1.33'
    kio_file(13128) kdemain: Starting 13128
    Unknown signature value:  795 
    Unknown signature value:  795 
    Unknown signature value:  795 
    Unknown signature value:  795 
    Unknown signature value:  795 
    Unknown signature value:  795 
    Unknown signature value:  7 
    Unknown signature value:  795

**Comment by palinek** [comment]
- Is there any difference if you run the lxqt components with only one attached display?
- Do all other Qt5 GUI applications work as expected (with dual head)?

**Comment by dbautistadecabo** [comment]
Good questions!

* Yes, there is a difference with only one attached display: it works.
* I have tested qterminal with qt5 in dual head and it also works with no problem.

For the dual head I'm using nvidia with Xinerama (no randr and no composite). I cannot see many differences between the xsession-errors files (dual and single head), only this:

    Xlib:  extension "RANDR" missing on display ":0".

**Comment by palinek** [comment]
Don't know much abut Xinerama (better to say nothing). Just googled [around](https://forum.qt.io/topic/25664/qscreen-with-different-graphics-cards-qscreen-and-xinerama)...and it seems that Xinerama is a cause of problems somewhere.
I'm out of questions for you to check. We probably have only one way to know what is happening => debugging, but unfortunately I'm not able to debug your case on my hardware...

**Comment by dbautistadecabo** [comment]
I've tried to upgrade QT 5.4.2 to 5.5.1, and now the openbox menu doesn't appear, but the panel is still missing (and I can't launch a terminal with Alt+F2).

Maybe I should switch to Nouveau/XRandR...

**Comment by dbautistadecabo** [comment]
OK, so I switched from Xinerama to XRandR and everything works! :)
