### ISSUE TITLE
Jumping panel

### ISSUE THREAD

**Issue by zjes** [lxde/lxqt#867]
Hi, last update from lxqt master brought strange things.
1) Random crash all lxqt-* components (seems in liblxqt lib) in different time. (Mostly after monitor powersave)
2) After powersave of the external monitor, panel jumps to other screen, or disappear (seems not crashed, exists in process list with old pid). Restart of the panel can show it, or not (maybe shows somewhere out of screens :)).

BTW, which optimal version of the kwindowsystem?

**Comment by pmattern** [comment]
Could you please tell us on which OS you're running into this and how LXQt was installed?

**Comment by zjes** [comment]
Debian testing.
lxqt from git master (... ./build_all.sh)

**Comment by pmattern** [comment]
> Debian testing

To my knowledge there's quite some dependency hell right now in Debian testing. This could very well explain your findings which I cannot reproduce on Arch Linux, btw.
@agaida
Any chance you can drop a note on this one?

**Comment by zjes** [comment]
I trying to find why... because before lxqt pulling it just worked. Something was strongly changed last month. :)

BTW, qt was updated too, now is v. 5.5.1.

**Comment by tsujan** [comment]
@zjes
I use Debian Testing too, with some packages from Unstable. I don't use "build_all.sh" but make separate deb packages and install them one by one to be able to track dependencies. The latest Qt5 5.5.1 upgrade in Debian Testing first broke everything (because it was incomplete) and then removed some of my lxqt deb packages (specifically libqtxdg and lxqt-qtplugin). After rebuilding them, everything got OK.

**Comment by zjes** [comment]
About crashes - HDMI external monitor + powersave + qt5.5.1

segfault in libQt5XcbQpa.so.5.5.1

Crashs all qt applications. It's not a bug of lxqt. Sorry.

**Comment by agaida** [comment]
all things will be good - in about 10-12 days. All packages are in debian right now, have to rebuild the sid packages to prepare a clean transition - it will last approx. 5-6 days until all those packages enter testing. If this is done i will manually migrate the 0.10 release to sid. After another 5 days the packages will be in testing if no problems occour.
So stay tuned :)

**Comment by Vladimir-csp** [comment]
Riding on the edge here on Debian testing+sid. Great news!

Sorry for off topic and far fetched question, but is there any chance of jessie backport in foreseeable future?

**Comment by agaida** [comment]
http://packages.siduction.org/lxqt - i think the 0.10 backport will be ready in a week or two

**Comment by Vladimir-csp** [comment]
Not so far fetched after all. Thanks!
