### ISSUE TITLE
[lxqt-panel] The panel causes frequent wakeups and higher power comsumption.

### ISSUE THREAD

**Issue by PCMan** [lxde/lxqt#873]
From the output of profiling tool powertop, we can note that lxqt-panel causes frequent and long period of CPU wake up time, which is bad for power consumption. In comparison, the wake up counts of xfce-panel is low. We need to dig into the issue since this is important for laptops.
-------------------------------------------------------------------------------------------------------------
PowerTOP 2.6.1    Overview   Idle stats   Frequency stats   Device stats   Tunables                                     

The battery reports a discharge rate of 6.67 W
The estimated remaining time is 2 hours, 54 minutes

Summary: 552.5 wakeups/second,  16.4 GPU ops/seconds, 0.0 VFS ops/sec and 22.5% CPU use

                Usage       Events/s    Category       Description
            100.0%                      Device         Radio device: asus-nb-wmi
             47.9%                      Device         Display backlight
              2.4 ms/s     191.8        Interrupt      PS/2 Touchpad / Keyboard / Mouse
              1.8 ms/s     103.1        Process        compton --dbus
            178.7 ms/s      33.1        Process        /usr/bin/X -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
              9.8 ms/s      68.3        Process        /usr/bin/roxterm
            170.9   s/s  22.4        kWork          flush_to_ldisc
              2.1 pkts/s                Device         Network interface: wlan0 (iwlwifi)
            153.8   s/s  20.9        Process        [rcu_sched]
              2.9 ms/s      13.7        Process        /opt/google/chrome/chrome
            359.2   s/s  13.9        Process        /usr/bin/syndaemon -d -i 1
              1.8 ms/s      11.3        Process        lxqt-panel
             10.5 ms/s       7.2        Process        /opt/google/chrome/chrome --type=renderer --lang=zh-TW --force-fieldtrials=*AffiliationBasedMa
            293.1   s/s   7.9        Process        /usr/lib/at-spi2-core/at-spi2-registryd --use-gnome-session
            290.1   s/s   6.1        Process        openbox
            102.1   s/s   7.0        Process        [rcuos/0]
            687.8   s/s   6.7        Process        /usr/bin/fcitx
            342.0   s/s   6.6        Timer          tick_sched_timer
            ..........................................
            161.8   s/s   1.7        Process        xfce4-panel
            275.8   s/s   1.2        Process        lxqt-runner

**Comment by PCMan** [comment]
After some more investigation, it seems that the worldclock plugin causes the problem. We probably need to  adjust the QTimer inside it. @kuzmas Would you please take a look at that?
Thank you.

**Comment by PCMan** [comment]
Do we need to receive notification from the timer every 10 ms? This causes 10 wake ups of CPU from idle state per second, which drains the battery.

**Comment by pmattern** [comment]
@PCMan 
FIY / FWIW https://github.com/lxde/lxqt/issues/771#issuecomment-143084321

**Comment by palinek** [comment]
> Do we need to receive notification from the timer every 10 ms? This causes 10 wake ups of CPU from idle state per second, which drains the battery.

I knew I didn't like the worldclock ... maybe some kind of 6th sense? :smile:

I can have a look on it later.

**Comment by palinek** [comment]
This is the "bad" commit: lxde/lxqt-panel@494c09ac6ee6f8b5dad77de712de5d4e493bd4a7. Here the logic was changed from "wake-up and do what is needed" to "wake-up at least each 100ms and check if there is something to do"

**Comment by paulolieuthier** [comment]
@PCMan besides the wordclock plugin, is there any other abnormalities?
