### ISSUE TITLE
Possible to customize the start menu>leave options?

### ISSUE THREAD

**Issue by gituser6** [lxde/lxqt#876]
I am wondering if the "Leave" options can be edited? I'd like to remove a few of them from showing up.

**Comment by Vladimir-csp** [comment]
Menu entries are .desktop files, so they can be overridden like any application.
Buttons in generic lxqt-leave dialog are another story, not editatble. And #580 was rejected.

**Comment by gituser6** [comment]
So I can remove "Leave" totally be deleting /usr/share/desktop-directories/lxqt-leave.directory but I cannot remove or edit some of the options you are saying? Is it possible for me to compile it from source without any option except logout? Or is there an alternative involving deleting /usr/share/desktop-directories/lxqt-leave.directory and adding a logout button somehow? Thank you :)

**Comment by Vladimir-csp** [comment]
/usr/share/desktop-directories/lxqt-leave.directory is just a menu directory description.
Application entries are:
/usr/share/applications/lxqt-{logout,reboot,shutdown,suspend,hibernate,lockscreen}.desktop.
They can be edited, or overridden on user-level, see [desktop entry spec](http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html)

**Comment by gituser6** [comment]
Thank you. I was able to add the Hidden=true to them and now it works the way I would like it to.

**Comment by pmattern** [comment]
In case you don't want to read the whole specification stated above changes on a per-user basis can be made by copying the files to `~/.local/share/applications`. (Of course you can edit files in that directory from scratch as well but this doesn't seem to be needed to solve your problem.)

Btw. eventually providing a GUI to edit those desktop entry files is discussed in #820.

If you question got answered by now please close this issue by hitting the respective button below the form to file comments.

**Comment by gituser6** [comment]
Thank you both!

**Comment by gituser6** [comment]
Sorry, I had to reopen this. I tried copied these  `~/.local/share/applications` and added the `Hidden=true` line to each of them, but lxqt doesn't respect the files it seems after I logged out and back in.

```
% ls ~/.local/share/applications  
lxqt-hibernate.desktop  lxqt-leave.desktop  lxqt-reboot.desktop  lxqt-shutdown.desktop  lxqt-suspend.desktop
```

Example:
```
% grep Hidden ~/.local/share/applications/lxqt-reboot.desktop 
Hidden=true
```

Is there something else I need to do?

**Comment by tsujan** [comment]
Try "NoDisplay=true"!

**Comment by gituser6** [comment]
Yes, that worked, thank you.

**Comment by pmattern** [comment]
This got me curious so I compared the behaviour of KDE, LXQt, LXDE and Xfce.

Both `NoDisplay=true` and `Hidden=true` prevent the corresponding topic from appearing in the menu if stated in files `/usr/share/applications/*.desktop` in all those desktop environments. In files `~/.local/share/applications/*.desktop` both keys behave the same as in `/usr/share/applications` in Xfce, in KDE and LXQt only `NoDisplay=true` works while  `Hidden=true` doesn't have any effect and in LXDE `~/.local/share/applications` doesn't seem to get considered at all.
The [specification](http://www.freedesktop.org/wiki/Specifications/desktop-entry-spec/) doesn't give hints regarding any different behaviour of `Hidden=true` at those two different paths.

All in all this seems a bit odd to me. Shouldn't both keys have the same effect at both locations suggesting that there's something wrong with the implementations e. g. in KDE and LXQt? Am I missing something?

@gituser6 
If you should ever happen to see changes in the menu apparently no taking place again you may bear in mind #65. (Just FYI, doesn't affect the problem discussed here.)

**Comment by Vladimir-csp** [comment]
By spec, the difference between `NoDisplay` and `Hidden` is that `NoDisplay` should just hide entry from showing up in menus, but still leaving it in resulting application database. `Hidden` should completely remove application from resulting application database (and from menus, obviously) as if no desktop entry for it exists. So there is clearly a misimplementation somewhere (libqtxdg?).

**Comment by knm100** [comment]
This way doesn't seem to work for Wayland sessions.  it is possible to customize the leave menu

**Comment by stefonarch** [comment]
You mean the central leave menu with the 6 options or the one in the applications menu? The first one can't be customized, the latter should work.

**Comment by knm100** [comment]
I mean the central leave menu with the 6 options,  but I tried,  it didn,t work.

**Comment by stefonarch** [comment]
As I said: this can't be configured by modifying `.desktop` files.

**Comment by knm100** [comment]
> Sorry, I had to reopen this. I copied these to `~/.local/share/applications` and added the `Hidden=true` line to each of them, but lxqt doesn't respect the files it seems after I logged out and back in because I still see them listed in the menu under "Leave."
I see @Vladimir-csp did it by this way ,and it worked, isn't this way only for X11 and not for wayland?

**Comment by stefonarch** [comment]
There is no difference between wayland and x11 here.
 `NoDisplay=true` works in the panel menu → Leave.

**Comment by knm100** [comment]
> Sorry, I had to reopen this. I copied these to `~/.local/share/applications` and added the `Hidden=true` line to each of them, but lxqt doesn't respect the files it seems after I logged out and back in because I still see them listed in the menu under "Leave."
> 
> ```
> % ls ~/.local/share/applications  
> lxqt-hibernate.desktop  lxqt-leave.desktop  lxqt-reboot.desktop  lxqt-shutdown.desktop  lxqt-suspend.desktop
> ```
> 
> Example:
> 
> ```
> % grep Hidden ~/.local/share/applications/lxqt*.desktop
> /home/mags/.local/share/applications/lxqt-hibernate.desktop:Hidden=true
> /home/mags/.local/share/applications/lxqt-leave.desktop:Hidden=true
> /home/mags/.local/share/applications/lxqt-reboot.desktop:Hidden=true
> /home/mags/.local/share/applications/lxqt-shutdown.desktop:Hidden=true
> /home/mags/.local/share/applications/lxqt-suspend.desktop:Hidden=true
> ```

But judging from what @gituser6  said, it was definitely not about "leave botton in main menu", it was about the leave menu with the 6 options

**Comment by knm100** [comment]
> /usr/share/desktop-directories/lxqt-leave.directory is just a menu directory description.
> Application entries are:
> /usr/share/applications/lxqt-{logout,reboot,shutdown,suspend,hibernate,lockscreen}.desktop.
> They can be edited, or overridden on user-level, see [desktop entry spec](http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html)

This is about the button

**Comment by tsujan** [comment]
@knm100 
Any item you see in the main menu or Fancy menu corresponds to a desktop entry. `NoDisplay=true` and similar key-values work with all, regardless of X11 and Wayland.

**Comment by knm100** [comment]
@tsujan  if I want to hide the button or change the icon of the button of lock screen under the leave menu.   is it possible?    It  look like it's in neither the main menu nor the fancy menu

**Comment by tsujan** [comment]
The icons are taken from your icon theme. They can also be changed in desktop entries (`Icon=...`). You may need to restart the panel to see the effect.

**Comment by tsujan** [comment]
If by "button" you mean a button inside a dialog, and not the icon of the menu entry, the only way to change its icon is changing your icon theme.

**Comment by knm100** [comment]
@stefonarch @tsujan  Thank you both for helping me figure this out

**Comment by knm100** [comment]
@tsujan, One more question:  So the secton 4.2 in  archwiki  is not  true. (https://wiki.archlinux.org/title/LXQt )

**Comment by tsujan** [comment]
>  So the section 4.2 of lxqt wiki in archwiki is not true

It is correct. It's about the items you see under the "Leave" sub-menu, not about the buttons inside lxqt-leave dialog. That dialog shows all options.

**Comment by knm100** [comment]
but  it is not work for me .
![swappy-20240605-165310](https://github.com/lxqt/lxqt/assets/166389780/13cc70dc-5994-45f4-bc01-9ecdc1dd64de)

**Comment by stefonarch** [comment]
Some screenshots.
I have set `NoDisplay=true` for hibernation to avoid clicking it by mistake as it is buggy on my laptop.

It works here (panel applications menus):

![immagine](https://github.com/lxqt/lxqt/assets/10681413/ce7db1d1-5f07-4897-9e78-db6eb436ee6f)
It will never work here (leave dialog):

![immagine](https://github.com/lxqt/lxqt/assets/10681413/de900f69-0366-4e34-8e9d-28f6d0efbc26)

**Comment by knm100** [comment]
At least you have one place to work. With me, neither.

**Comment by knm100** [comment]
After looking at your screenshot, I realized that there is a leave menu in the fancy menu.
In my case, the leave menu in the fancy menu is also problematic, whether I set NoDisplay=true or not, it doesn't change here, there is no lock screen option

**Comment by Vladimir-csp** [comment]
Long time ago I suggested a thing that would prevent this issue from happening, at least the logout dialog part: #580

**Comment by stefonarch** [comment]
@knm100 in your screenshot `NoDisplay=true` is commented out...

In the application menus "Lock Screen" is not displayed inside the "Leave" menu as it isn't part of  `Categories=System;X-Leave;`.

**Comment by knm100** [comment]
thank you it work  in fancy menu, if i  cp /usr/share/applications/lxqt-hibernate.desktop  ~/.local/share/applications
and add the NoDisplay=true to   ~/.local/share/applications/lxqt-hibernate.desktop.
