### ISSUE TITLE
lxqt-about - shows old version

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxde/lxqt#877]
On my system, lxqt-about still shows v0.9 while all the lxqt packages have been updated to v0.10 (Arch Linux).

![2015-11-04-092615_635x443_scrot](https://cloud.githubusercontent.com/assets/6639859/10933103/5a6d01a6-82d6-11e5-8177-18753f6de744.png)

![2015-11-04-092857_884x557_scrot](https://cloud.githubusercontent.com/assets/6639859/10933122/7e4c0f0e-82d6-11e5-84bd-25a2753ff969.png)

I am unsure if this is a local, packaging, or code issue.

**Comment by ruegerjr** [comment]
I observe the same problem, also on Arch Linux. Have not tried back-tracking to source.  Possibly lxqt-globalkeys, maybe CMakeLists.txt not being up-to-date when packages built for arch?

**Comment by jleclanche** [comment]
I can't figure out why this is the case but yes, this is a packaging problem in arch. If anyone knows what's going on precisely, I'll take it. In the mean time it seems to just be a matter of version output so...

**Comment by ruegerjr** [comment]
Agree that this has no impact on functionality, but be prepared for the less wary to complain that the upgrade fails for them.

**Comment by palinek** [comment]
Is the liblxqt-dev (or whatever the name of  dev package is) 0.10.0 deployed/installed when the other packages are built?

**Comment by jleclanche** [comment]
Yeah.

**Comment by jleclanche** [comment]
Ok I think I know what the problem is. I'll do a rebuild.

**Comment by palinek** [comment]
> Ok I think I know what the problem is. I'll do a rebuild.

...share your knowledge, please.

**Comment by ArthurBorsboom** [comment]
After new packages have been released for Arch Linux, the issue has been solved on my system. Closing the issue.
