### ISSUE TITLE
[lxqt-config-monitor] Unable to save settings

### ISSUE THREAD

**Issue by geokapp** [lxde/lxqt#878]
Hi, 

On my setup the Save button on the Monitor Settings tool is no longer working after upgrading to 0.10. It only applies the changes but it doesn't pop up the save msgbox as in the previous version.

I use  Debian testing and I have downloaded LXQt from the siduction repo.

Package: lxqt-config
Version: 0.10.0-1
Architecture: amd64
Maintainer: LXQt Packaging Team <pkg-lxqt-devel@lists.alioth.debian.org>

Regards,
Giorgos

**Comment by pmattern** [comment]
Saving settings doesn't work in 0.10 and latest VCS checkouts as the transition to KScreen as backend of `lxqt-config-monitor` unfortunately didn't get completely finished before release 0.10. You may trace this in lxde/lxqt-config#45 and lxde/lxqt-config#63.
So it seems rather likely this is what you're suffering from.

If the problem ceases on your system once the upstream fix made it to Siduction you may close this issue by hitting the respective button below the form to file comments.

**Comment by geokapp** [comment]
Thanks, probably the issue relates to the transition to KScreen as you suggested.

**Comment by selairi** [comment]
If have upgrade from 0.9 version, old config files can set your older
screen modes. You can remove your old config files from
~/.config/autostart/.

Could you be so kind to test it?

Thanks

2015-11-04 15:27 GMT+01:00, Giorgos Kappes <notifications@github.com>:

**Comment by geokapp** [comment]
I found out that xrandr was uninstalled from my system during the upgrade. After reinstalling it, the old monitor conf file ~/.config/autostart/lxqt-config-monitor-autostart.desktop sets my old display modes properly trough xrandr. However, the version of lxqt-config-monitor that is currently installed does not update this file through the save button (it only applies the changes) and so when I remove it manually, the file is not recreated by pressing save. No error message is displayed about the save operation (line 199 in monitorsettingsdialog.cpp) as well.

**Comment by selairi** [comment]
Could you be so kind to run the next command?

echo $XDG_CONFIG_HOME

lxqt-config-monitor should save file in ~/.config/autostart, but if
XDG_CONFIG_HOME environment variable is set, lxqt-config-monitor
should save autostart in XDG_CONFIG_HOME path.

Thanks

2015-11-06 11:05 GMT+01:00, Giorgos Kappes <notifications@github.com>:

**Comment by geokapp** [comment]
XDG_CONFIG_HOME is set to the default config location:

gkappes@dolphin:~$ echo $XDG_CONFIG_HOME
/home/gkappes/.config

**Comment by geokapp** [comment]
The following is the output of strace lxqt-conf0g-monitor:

...
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(2, "kscreen: Primary output changed "..., 178kscreen: Primary output changed from KScreen::Output(Id: 88 , Name: "DisplayPort-3" ) ( "DisplayPort-3" ) to KScreen::Output(Id: 88 , Name: "DisplayPort-3" ) ( "DisplayPort-3" )
) = 178
stat("/home/gkappes/.config/LXQt/lxqt-config-monitor.conf", {st_mode=S_IFREG|0644, st_size=960, ...}) = 0
open("/home/gkappes/.config/LXQt/lxqt-config-monitor.conf", O_RDONLY|O_CLOEXEC) = 11
stat("/etc/xdg/LXQt/lxqt-config-monitor.conf", 0x7ffe2be82b10) = -1 ENOENT (No such file or directory)
stat("/etc/xdg/LXQt/lxqt-config-monitor.conf", 0x7ffe2be82ae0) = -1 ENOENT (No such file or directory)
stat("/etc/xdg/LXQt.conf", 0x7ffe2be82b10) = -1 ENOENT (No such file or directory)
stat("/etc/xdg/LXQt.conf", 0x7ffe2be82b10) = -1 ENOENT (No such file or directory)
stat("/etc/xdg/LXQt.conf", 0x7ffe2be82ae0) = -1 ENOENT (No such file or directory)
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
open("/home/gkappes/.config/lxqt-config-monitor-autostart.desktop", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 11
fcntl(11, F_SETFD, FD_CLOEXEC)          = 0
fstat(11, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(11, "[Desktop Entry]\nType=Application"..., 171) = 171
...

From the above output it is clear that lxqt-config actually saves the config file under: 
~/config/lxqt-config-monitor-autostart.desktop
as the value of XDG_CONFIG_HOME is /home/gkappes/.config
Copying this file manually under ~/.config/autostart/. solves the problem. So I was wondering if the config file should be saved under XDG_CONFIG_HOME/autostart. in case XDG_CONFIG_HOME is set. maybe the line 186 of monitorsettingsdialog.cpp:

autostartPath = QString(qgetenv("XDG_CONFIG_HOME")); 

can be changed to: 

autostartPath = QString(qgetenv("XDG_CONFIG_HOME") + "/autostart/");

**Comment by selairi** [comment]
Ok, fixed.

2015-11-06 14:00 GMT+01:00, Giorgos Kappes <notifications@github.com>:

**Comment by geokapp** [comment]
Thanks a lot, I'm closing the issue. :)
