### ISSUE TITLE
Possible to invoke lxqt-leave --logout without the "do you really want to..." dialog?

### ISSUE THREAD

**Issue by gituser6** [lxde/lxqt#879]
Is it possible to issue an `lxqt-leave --logout` and suppress the "do you really want to..." dialog from coming up?  I'd like an instant logout effect. I did not see anything from the --help output.  I am not opposed to changing the code and compiling if that is what is required, I just don't know how to do it or in which file. Thank you in advance.

**Comment by pmattern** [comment]
In dialog "LXQt Session Settings" topic "Basic Settings" at the left column brings up a setting "Ask for confirmation [...]" which is probably what you want.
The dialog can be launched from panel main menu - Preferences - LXQt settings - Session Settings or "LXQt Configuration Center", binary is `lxqt-config-session`.
The current inconsistency between topic "Leave" from panel main menu - Leave (binary `lxqt-leave` without arguments) and others like "Logout" or "Reboot" (binary invocation `lxqt-leave --foobar`) is beeing addressed in #855.

**Comment by paulolieuthier** [comment]
@gituser6 feel free to reopen it.

**Comment by gituser6** [comment]
Just what I was looking for, thank you again :)

**Comment by anohren** [comment]
Would've been handy to have this as a command option `--no-confirm`. That way the GUI would be able to have confirmation, while the physical power button would not.
