### ISSUE TITLE
Build for ARM architecture in Ubuntu PPA

### ISSUE THREAD

**Issue by emk2203** [lxde/lxqt#880]
The project is ideally suited to run on SBCs like Raspberry Pi 2 or Odroid C1+ - lightweight, modern architecture.

However, your Ubuntu PPA builds only for x386 and x64, not for ARM. Could you add ARM to your supported architectures on Ubuntu?

**Comment by palinek** [comment]
This is good point, but for downstream. @gilir @agaida how is it with building packages for other than *86 architectures?

**Comment by gilir** [comment]
ARM support is not available by default on Launchpad PPA. We need special authorization to add this architecture to a PPA.

However, Ubuntu 16.04 will have 0.10 in the official repositories very soon, which include ARM and PowerPC support by default.

**Comment by gilir** [comment]
I checked for ARM support on the PPA, and unfortunately, the PPA is too big for adding ARM support (see https://dev.launchpad.net/CommunityARMBuilds). However, if you are using Ubuntu Xenial (futur 16.04), you already have packages for 0.10 with ARM support.

**Comment by agaida** [comment]
full ack, thats the way to go
