### ISSUE TITLE
Missing desktopswitcher and taskbar with kwindowsystem 5.13

### ISSUE THREAD

**Issue by rezso** [lxde/lxqt#881]
After upgrading kwindowsystem to 5.13, the desktop switcher and the taskbar are missing on the panel.
Downgrading kwindowsystem to 5.11 solves the problem, both (desktop switcher and taskbar) visible again.

**Comment by jleclanche** [comment]
@mgraesslin did you guys make any backwards-incompatible changes?

**Comment by mgraesslin** [comment]
no, of course not. The only thing which comes to my mind is that we moved the windowing system relevant code into a plugin. Some distros f**d up their packaging and forgot to include the new binary files.

**Comment by palinek** [comment]
@rezso what distro are you running on?

**Comment by rezso** [comment]
I use a little distro, UHU-Linux.
The kwindowsystem package contains the plugin libraries (KF5WindowSystemX11Plugin.so and KF5WindowSystemWaylandPlugin.so), I checked it. So this is very weird.

**Comment by pmattern** [comment]
I've never seen any such problem compiling the then actual VCS checkouts of lxqt-panel against KWindowSystem 5.8-5.15 in the course of the last months on Arch Linux here.

> I use a little distro, UHU-Linux.

The interesting part would have been how LXQt gets installed on that distro.
Maybe the problem is that lxqt-panel just needs to get re-compiled against the new KWindowSystem version? Thinking of the Arch Linux AUR which is *not* aware of the need to re-compile if *versions* of dependencies have changed which may introduce incompatibilities.

**Comment by mgraesslin** [comment]
can you check the debug output (might need to be enabled first). If the plugin is not found it will print something like:

    kwin(23744)/(org.kde.kwindowsystem) loadPlugin: Could not find any platform plugin

**Comment by rezso** [comment]
@pmattern: in the first step I compiled the lxqt-panel with the new KWindowSystem 5.13.
But now I found an interesting thing:

ldd lxqt-panel
	liblxqt-globalkeys-ui.so.0 => /usr/lib/liblxqt-globalkeys-ui.so.0 (0xb77ac000)
	libmenu-cache.so.3 => /usr/lib/libmenu-cache.so.3 (0xb77a4000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0xb766f000)
	liblxqt-globalkeys.so.0 => /usr/lib/liblxqt-globalkeys.so.0 (0xb7659000)
	libdbusmenu-qt5.so.2 => /usr/lib/libdbusmenu-qt5.so.2 (0xb7627000)
	libSM.so.6 => /usr/lib/libSM.so.6 (0xb761f000)
	libICE.so.6 => /usr/lib/libICE.so.6 (0xb7606000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0xb74d0000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0xb74bd000)
	libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0xb74ba000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0xb74b7000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0xb74b2000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0xb74a8000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0xb7486000)
	libxcb-damage.so.0 => /usr/lib/libxcb-damage.so.0 (0xb7483000)
	libxcb-xfixes.so.0 => /usr/lib/libxcb-xfixes.so.0 (0xb747c000)
	libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0xb7473000)
	libxcb-shape.so.0 => /usr/lib/libxcb-shape.so.0 (0xb7470000)
	liblxqt.so.0 => /usr/lib/liblxqt.so.0 (0xb7428000)
	libQt5Xdg.so.1 => /usr/lib/libQt5Xdg.so.1 (0xb73d8000)
	libQt5Xml.so.5 => /usr/lib/qt5/lib/libQt5Xml.so.5 (0xb739c000)
	libQt5DBus.so.5 => /usr/lib/qt5/lib/libQt5DBus.so.5 (0xb731d000)
	libKF5WindowSystem.so.5 => /usr/lib/libKF5WindowSystem.so.5 (0xb72b9000)
	libQt5Widgets.so.5 => /usr/lib/qt5/lib/libQt5Widgets.so.5 (0xb6c5f000)
	libQt5X11Extras.so.5 => /usr/lib/qt5/lib/libQt5X11Extras.so.5 (0xb6c5b000)
	libQt5Gui.so.5 => /usr/lib/qt5/lib/libQt5Gui.so.5 (0xb66de000)
	libQt5Core.so.5 => /usr/lib/qt5/lib/libQt5Core.so.5 (0xb6210000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xb6128000)
	libm.so.6 => /lib/libm.so.6 (0xb60e4000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xb60c8000)
	libc.so.6 => /lib/libc.so.6 (0xb5f2c000)
	libpthread.so.0 => /lib/libpthread.so.0 (0xb5f11000)
	libgio-2.0.so.0 => /usr/lib/../lib/libgio-2.0.so.0 (0xb5d91000)
	libgmodule-2.0.so.0 => /usr/lib/../lib/libgmodule-2.0.so.0 (0xb5d8c000)
	libdl.so.2 => /lib/libdl.so.2 (0xb5d88000)
	libz.so.1 => /usr/lib/../lib/libz.so.1 (0xb5d6f000)
	libresolv.so.2 => /lib/libresolv.so.2 (0xb5d58000)
	libgobject-2.0.so.0 => /usr/lib/../lib/libgobject-2.0.so.0 (0xb5d08000)
	libffi.so.6 => /usr/lib/../lib/libffi.so.6 (0xb5d01000)
	libuuid.so.1 => /lib/libuuid.so.1 (0xb5cfd000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0xb5cfa000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0xb5cf4000)
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0xb5b1b000)
	libcrypt.so.1 => /lib/libcrypt.so.1 (0xb5aea000)
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0xb5a7b000)
	libdbus-1.so.3 => /lib/libdbus-1.so.3 (0xb5a25000)
	libxcb-keysyms.so.1 => /usr/lib/libxcb-keysyms.so.1 (0xb5a22000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0xb59c0000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0xb5989000)
	libicui18n.so.51 => /usr/lib/libicui18n.so.51 (0xb5781000)
	libicuuc.so.51 => /usr/lib/libicuuc.so.51 (0xb5614000)
	libicudata.so.51 => /usr/lib/libicudata.so.51 (0xb40c9000)
	libpcre16.so.0 => /usr/lib/libpcre16.so.0 (0xb408c000)
	libgthread-2.0.so.0 => /usr/lib/libgthread-2.0.so.0 (0xb408a000)
	librt.so.1 => /lib/librt.so.1 (0xb4081000)
	/lib/ld-linux.so.2 (0xb77ca000)
	libglapi.so.0 => /usr/lib/libglapi.so.0 (0xb4069000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0xb4066000)
	libxcb-glx.so.0 => /usr/lib/libxcb-glx.so.0 (0xb404f000)
	libxcb-dri2.so.0 => /usr/lib/libxcb-dri2.so.0 (0xb404a000)
	libxcb-dri3.so.0 => /usr/lib/libxcb-dri3.so.0 (0xb4047000)
	libxcb-present.so.0 => /usr/lib/libxcb-present.so.0 (0xb4044000)
	libxcb-sync.so.1 => /usr/lib/libxcb-sync.so.1 (0xb403d000)
	libxshmfence.so.1 => /usr/lib/libxshmfence.so.1 (0xb403b000)
	libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0xb4036000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0xb402a000)

lxqt-panel linked with libKF5WindowSystem.so.5

ldd libKF5WindowSystem.so.5.13.0
	libQt5Widgets.so.5 => /usr/lib/qt5/lib/libQt5Widgets.so.5 (0xb70b9000)
	libQt5X11Extras.so.5 => /usr/lib/qt5/lib/libQt5X11Extras.so.5 (0xb70b5000)
	libSM.so.6 => /usr/lib/libSM.so.6 (0xb7094000)
	libICE.so.6 => /usr/lib/libICE.so.6 (0xb707b000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0xb6f45000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0xb6f33000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0xb6f2e000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0xb6f24000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0xb6f02000)
	libxcb-keysyms.so.1 => /usr/lib/libxcb-keysyms.so.1 (0xb6eff000)
	libQt5Gui.so.5 => /usr/lib/qt5/lib/libQt5Gui.so.5 (0xb6982000)
	libQt5Core.so.5 => /usr/lib/qt5/lib/libQt5Core.so.5 (0xb64b4000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xb63cc000)
	libm.so.6 => /lib/libm.so.6 (0xb6388000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xb636c000)
	libc.so.6 => /lib/libc.so.6 (0xb61d0000)
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0xb5ff8000)
	libcrypt.so.1 => /lib/libcrypt.so.1 (0xb5fc7000)
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0xb5f57000)
	libpthread.so.0 => /lib/libpthread.so.0 (0xb5f3c000)
	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0xb5eec000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0xb5db7000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0xb5d56000)
	libuuid.so.1 => /lib/libuuid.so.1 (0xb5d52000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0xb5d4e000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0xb5d48000)
	libdl.so.2 => /lib/libdl.so.2 (0xb5d44000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0xb5d0d000)
	libz.so.1 => /usr/lib/libz.so.1 (0xb5cf4000)
	libicui18n.so.51 => /usr/lib/libicui18n.so.51 (0xb5aeb000)
	libicuuc.so.51 => /usr/lib/libicuuc.so.51 (0xb597e000)
	libicudata.so.51 => /usr/lib/libicudata.so.51 (0xb4433000)
	libpcre16.so.0 => /usr/lib/libpcre16.so.0 (0xb43f7000)
	libgthread-2.0.so.0 => /usr/lib/libgthread-2.0.so.0 (0xb43f5000)
	librt.so.1 => /lib/librt.so.1 (0xb43eb000)
	/lib/ld-linux.so.2 (0xb7767000)
	libffi.so.6 => /usr/lib/../lib/libffi.so.6 (0xb43e5000)
	libglapi.so.0 => /usr/lib/libglapi.so.0 (0xb43cd000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0xb43ca000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0xb43c8000)
	libxcb-glx.so.0 => /usr/lib/libxcb-glx.so.0 (0xb43b0000)
	libxcb-dri2.so.0 => /usr/lib/libxcb-dri2.so.0 (0xb43ab000)
	libxcb-dri3.so.0 => /usr/lib/libxcb-dri3.so.0 (0xb43a8000)
	libxcb-present.so.0 => /usr/lib/libxcb-present.so.0 (0xb43a5000)
	libxcb-sync.so.1 => /usr/lib/libxcb-sync.so.1 (0xb439f000)
	libxshmfence.so.1 => /usr/lib/libxshmfence.so.1 (0xb439c000)
	libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0xb4397000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0xb438b000)

libKF5WindowSystem.so.5 not linked with KF5WindowSystemX11Plugin.so...
But:

ldd KF5WindowSystemX11Plugin.so
	libKF5WindowSystem.so.5 => /usr/lib/libKF5WindowSystem.so.5 (0xb76be000)
	libQt5X11Extras.so.5 => /usr/lib/qt5/lib/libQt5X11Extras.so.5 (0xb76ba000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0xb7698000)
	libSM.so.6 => /usr/lib/libSM.so.6 (0xb7690000)
	libICE.so.6 => /usr/lib/libICE.so.6 (0xb7677000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0xb7541000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0xb752f000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0xb752a000)
	libQt5Widgets.so.5 => /usr/lib/qt5/lib/libQt5Widgets.so.5 (0xb6ed0000)
	libQt5Gui.so.5 => /usr/lib/qt5/lib/libQt5Gui.so.5 (0xb6953000)
	libQt5Core.so.5 => /usr/lib/qt5/lib/libQt5Core.so.5 (0xb6485000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xb639d000)
	libm.so.6 => /lib/libm.so.6 (0xb635a000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xb633d000)
	libc.so.6 => /lib/libc.so.6 (0xb61a1000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0xb6197000)
	libxcb-keysyms.so.1 => /usr/lib/libxcb-keysyms.so.1 (0xb6194000)
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0xb5fbc000)
	libcrypt.so.1 => /lib/libcrypt.so.1 (0xb5f8a000)
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0xb5f1b000)
	libpthread.so.0 => /lib/libpthread.so.0 (0xb5f00000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0xb5e9f000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0xb5e9c000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0xb5e95000)
	libuuid.so.1 => /lib/libuuid.so.1 (0xb5e91000)
	libdl.so.2 => /lib/libdl.so.2 (0xb5e8d000)
	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0xb5e3d000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0xb5d08000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0xb5cd0000)
	libz.so.1 => /usr/lib/libz.so.1 (0xb5cb7000)
	libicui18n.so.51 => /usr/lib/libicui18n.so.51 (0xb5aaf000)
	libicuuc.so.51 => /usr/lib/libicuuc.so.51 (0xb5942000)
	libicudata.so.51 => /usr/lib/libicudata.so.51 (0xb43f7000)
	libpcre16.so.0 => /usr/lib/libpcre16.so.0 (0xb43ba000)
	libgthread-2.0.so.0 => /usr/lib/libgthread-2.0.so.0 (0xb43b8000)
	librt.so.1 => /lib/librt.so.1 (0xb43af000)
	/lib/ld-linux.so.2 (0xb775a000)
	libglapi.so.0 => /usr/lib/libglapi.so.0 (0xb4397000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0xb4394000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0xb4391000)
	libxcb-glx.so.0 => /usr/lib/libxcb-glx.so.0 (0xb437a000)
	libxcb-dri2.so.0 => /usr/lib/libxcb-dri2.so.0 (0xb4375000)
	libxcb-dri3.so.0 => /usr/lib/libxcb-dri3.so.0 (0xb4372000)
	libxcb-present.so.0 => /usr/lib/libxcb-present.so.0 (0xb436f000)
	libxcb-sync.so.1 => /usr/lib/libxcb-sync.so.1 (0xb4368000)
	libxshmfence.so.1 => /usr/lib/libxshmfence.so.1 (0xb4366000)
	libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0xb4361000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0xb4355000)
	libffi.so.6 => /usr/lib/../lib/libffi.so.6 (0xb434f000)

I think, linking lxqt-panel with KF5WindowSystemX11Plugin.so (if exists) instead of libKF5WindowSystem.so.5 is not a bad idea...

**Comment by rezso** [comment]
@mgraesslin: yes, I get this error. But the plugin library is exists...

And now this issue is fixed. Many kiss for kde developers.
First, kwindowsystem uses standard qt paths, so the -DKDE_INSTALL_USE_QT_SYS_PATHS=ON is required. Second, with this the xcb plugin path will "/usr//usr/lib/qt5/plugins/org.kde.kwindowsystem.platforms/KF5WindowSystemX11Plugin.so" instead of "/usr/lib/qt5/plugins/kf5/org.kde.kwindowsystem.platforms/KF5WindowSystemX11Plugin.so" in the config-kwindowsystem.h. Third, this bad XCB_PLUGIN_PATH is used in the kwindowsystem.cpp...

Thank you for your help.
