### ISSUE TITLE
The problem in the assembly package lxqt-globalkeys.

### ISSUE THREAD

**Issue by lukman-gentoo** [lxde/lxqt#882]
Hello! When i try to install LXQt 0.10.0 of the overlay error in assembling the package lxqt-base / lxqt-globalkeys-9999. Please help me understand.

build.log and emerge --info
https://gist.github.com/lukman-gentoo/487672edbdc9cfad850d

**Comment by lukman-gentoo** [comment]
Unknown CMake command "lxqt_enable_target_exceptions"

**Comment by lukman-gentoo** [comment]
Verifying ebuild manifests
>>> Emerging (1 of 13) lxqt-base/lxqt-globalkeys-9999::qt
>>> Failed to emerge lxqt-base/lxqt-globalkeys-9999, Log file:
>>>  '/var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/temp/build.log'
>>> Jobs: 0 of 13 complete, 1 failed                Load avg: 0.67, 0.44, 0.24
 * Package:    lxqt-base/lxqt-globalkeys-9999
 * Repository: qt
 * Maintainer: lxqt@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
 * Fetching git://git.lxde.org/git/lxde/lxqt-globalkeys.git ...
git fetch git://git.lxde.org/git/lxde/lxqt-globalkeys.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/lxqt-base/lxqt-globalkeys/0/__main__ refs/heads/master
 * Checking out git://git.lxde.org/git/lxde/lxqt-globalkeys.git to /var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/work/lxqt-globalkeys-9999 ...
git checkout --quiet master
GIT update -->
   repository:               git://git.lxde.org/git/lxde/lxqt-globalkeys.git
   at the commit:            2693406dc16972b506a9b3db5b20bf0617a8761d
>>> Working in BUILD_DIR: "/var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/work/lxqt-globalkeys-9999_build"
cmake --no-warn-unused-cli -C /var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/work/lxqt-globalkeys-9999_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_INSTALL_DO_STRIP=OFF -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/work/lxqt-globalkeys-9999_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/work/lxqt-globalkeys-9999_build/gentoo_toolchain.cmake  /var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/work/lxqt-globalkeys-9999
Not searching for unused variables given on the command line.
loading initial cache file /var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/work/lxqt-globalkeys-9999_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:28 (include):
  include could not find load file:

    LXQtCompilerSettings


-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
CMake Error at daemon/CMakeLists.txt:145 (lxqt_enable_target_exceptions):
  Unknown CMake command "lxqt_enable_target_exceptions".


-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/work/lxqt-globalkeys-9999_build/CMakeFiles/CMakeOutput.log".
 * ERROR: lxqt-base/lxqt-globalkeys-9999::qt failed (configure phase):
 *   cmake failed
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_configure
 *   environment, line 3376:  Called cmake-utils_src_configure
 *   environment, line  931:  Called _execute_optionally 'src_configure'
 *   environment, line  294:  Called enable_cmake-utils_src_configure
 *   environment, line 1274:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
 * 
 * If you need support, post the output of `emerge --info '=lxqt-base/lxqt-globalkeys-9999::qt'`,
 * the complete build log and the output of `emerge -pqv '=lxqt-base/lxqt-globalkeys-9999::qt'`.
 * The complete build log is located at '/var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/work/lxqt-globalkeys-9999_build'
 * S: '/var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/work/lxqt-globalkeys-9999'

 * Messages for package lxqt-base/lxqt-globalkeys-9999:

 * ERROR: lxqt-base/lxqt-globalkeys-9999::qt failed (configure phase):
 *   cmake failed
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_configure
 *   environment, line 3376:  Called cmake-utils_src_configure
 *   environment, line  931:  Called _execute_optionally 'src_configure'
 *   environment, line  294:  Called enable_cmake-utils_src_configure
 *   environment, line 1274:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
 * 
 * If you need support, post the output of `emerge --info '=lxqt-base/lxqt-globalkeys-9999::qt'`,
 * the complete build log and the output of `emerge -pqv '=lxqt-base/lxqt-globalkeys-9999::qt'`.
 * The complete build log is located at '/var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/work/lxqt-globalkeys-9999_build'
 * S: '/var/tmp/portage/lxqt-base/lxqt-globalkeys-9999/work/lxqt-globalkeys-9999'

**Comment by luis-pereira** [comment]
@lukman-gentoo The real issue is [not finding LXQtCompilerSettings.cmake] (https://gist.github.com/lukman-gentoo/487672edbdc9cfad850d#file-build-log-L32). It's installed by liblxqt. Pls make sure liblxqt is properly installed on your system.

**Comment by lukman-gentoo** [comment]
@luis-pereira I reinstalled the package, but it did not help

```    
~ $ eix -Ie liblxqt
[I] lxqt-base/liblxqt
     Available versions:  ~0.7.0 ~0.8.0 (~)0.9.0 (**)9999[1]
     Installed versions:  9999[1](20:32:39 07.11.2015)
     Homepage:            http://lxqt.org/
     Description:         Common base library for the LXQt desktop environment

[1] "qt" /var/lib/layman/qt
```

**Comment by luis-pereira** [comment]
@lukman-gentoo Is `LXQtCompilerSettings.cmake` installed in  `<prefix>/share/cmake/lxqt/modules/` ?

**Comment by lukman-gentoo** [comment]
@luis-pereira It seems no
```
 $ ls -l /usr/share/cmake/lxqt/modules/
итого 56
-rw-r--r-- 1 root root  395 ноя  7 20:32 LXQtAppTranslationLoader.cpp.in
-rw-r--r-- 1 root root 8445 ноя  7 20:32 LXQtCreatePkgConfigFile.cmake
-rw-r--r-- 1 root root  389 ноя  7 20:32 LXQtLibTranslationLoader.cpp.in
-rw-r--r-- 1 root root 1756 ноя  7 20:32 LXQtTranslate.cmake
-rw-r--r-- 1 root root 3923 ноя  7 20:32 LXQtTranslateDesktop.cmake
-rw-r--r-- 1 root root 4989 ноя  7 20:32 LXQtTranslateTs.cmake
-rw-r--r-- 1 root root 3043 ноя  7 20:32 LXQtTranslationLoader.cmake
-rw-r--r-- 1 root root 4730 ноя  7 20:32 Qt5PatchedLinguistToolsMacros.cmake
-rw-r--r-- 1 root root 2402 ноя  7 20:32 Qt5TranslationLoader.cmake
-rw-r--r-- 1 root root 1058 ноя  7 20:32 Qt5TranslationLoader.cpp.in
```

**Comment by luis-pereira** [comment]
@lukman-gentoo That is not liblxq 0.10. There are several files missing.

**Comment by lukman-gentoo** [comment]
@luis-pereira please tell me how can I fix it?

**Comment by luis-pereira** [comment]
How did you installed liblxqt ?

**Comment by lukman-gentoo** [comment]
@luis-pereira 
I set at the beginning of the version from the repository Gentoo version 0.9.0, but I wanted to install version 0.10 of the overlay using layman. Probably somewhere in these stages it was installed this package liblxqt.

**Comment by luis-pereira** [comment]
@lukman-gentoo you need to install liblxqt 0.10.

**Comment by lukman-gentoo** [comment]
already installed
`[ebuild   R   *] lxqt-base/liblxqt-9999::qt`

**Comment by lukman-gentoo** [comment]
Thank you. I downgrade to 0.9.0 :grimacing:

**Comment by luis-pereira** [comment]
@lukman-gentoo is this solved ?

**Comment by lukman-gentoo** [comment]
@luis-pereira I'm sorry for the long answer. I installed the package from a repository Gentoo lxqt-base/lxqt-meta 0.9.0
