### ISSUE TITLE
lxqt-panel: add a plain theme/no theme

### ISSUE THREAD

**Issue by sixsixfive** [lxde/lxqt#892]
I never really liked the idea to need 2 themes for my desktop, so it would be nice if you could add a theme that follows the actual Qt-Style/theme(eg like KDE3/Xfce4/Gnome2/Mate)

**Comment by pmattern** [comment]
IMO this should go into #572. At least related closely.

**Comment by sixsixfive** [comment]
I dont think its the same #572 is about theme paths, this is about to override/disable the loading of a qtstylesheets in lxqt-panel to use the native qt theme.

**Comment by pmattern** [comment]
I didn't say it's the same. But #572 is certainly not just about paths. It's an attempt to discuss theming in LXQt in general, covering things like the different kinds of themes, how to improve exchange of different kinds of themes and the likes.
And as such your issue here if of course not the same but related to all that stuff, if I'm not mistaken.

**Comment by palinek** [comment]
If anybody is interested, how his/her environement would look like w/o a custom theme (if \<prefix\> is /usr):
- `mkdir /usr/share/lxqt/themes/notheme`
- `touch /usr/share/lxqt/themes/notheme/lxqt-panel.qss`
- choose the `Notheme` in lxqt-config-appearance

**Comment by jubalh** [comment]
@palinek I added this info to https://github.com/lxde/lxqt/wiki/Themes if that's okay.

**Comment by intialonso** [comment]
+1
I love this idea, this way we can achieve a more integrated desktop, and a simplified look and feel. One setting and thats it.

One little thing: we still need a qss to set the menu icon.

**Comment by sixsixfive** [comment]
>we still need a qss to set the menu icon.

hm if there is no qss, lxqt could use the default freedesktop icon for that(places/start-here) since it exists in almost all icon themes

**Comment by intialonso** [comment]
I suggested that some time ago, but it was voted against. I still think that it will be a nice solution.

Our current styles uses some unique widgets (the panel itselfs for example) that could give some problems. This could be fixed if the themes include a custom style for the lxqt panel, as some of them do for Thunar, XFCE, or Unity.

Im exploring this posibilities with a gtk apps.rc custom file, but with no succes at the moment.

**Comment by intialonso** [comment]
This is LXQT using the Arc Dark gtk theme, I have found no workaround for the panel background and the menu icon, but generally speaking I like the idea of including a "System" theme in LXQT that uses the current widget theme of the system.

@palinek @paulolieuthier @jleclanche what do you think?

![lxqt-arc-dark](https://cloud.githubusercontent.com/assets/7544231/11338723/bc9051ac-91c3-11e5-83d6-f06ff4d0ddb4.png)

**Comment by palinek** [comment]
This seems good..

> I have found no workaround for the panel background and the menu icon

We can change the the menu icon to be "hardcoded" in the panel (and configurable via GUI).
Panel's background color/image is configurable, not?

**Comment by intialonso** [comment]
>Panel's background color/image is configurable, not?

Yes, it is.  

So the only thing missing will be the icon. I agree with a configurable icon as in #720 but nobody seems to be working on that.

**Comment by paulolieuthier** [comment]
@intialonso sorry, I'm yet to fully understand your proposal. Your idea sounds really nice, and I want to work close with you (and with whoever wants as well). So, you mean merging "Widget Style" and "LXQt Theme" in Appearance Configuration? Not only merging the pages, I imagine, but also the concepts? Like, if I select the Light theme, which is the one I use, not only the panel/runner/notifications will be affected, but also the widget style and applications colors, all in once? Is that what you imagine? Is this what the issue proposes?

If we are to change that, it may involve more than just UI changes. It's not a problem, I'm just saying. Your mockups look great, and will be very useful. When I have time, I want to work on this, and I'll need your help.

**Comment by Vladimir-csp** [comment]
This is not a mockup. It is lxqt-panel without LXQt theme. Which means it uses Qt theme, and Qt is configured to use GTK+ engine, and GTK is configured to use "Arc Dark" theme.
Correct me if I'm wrong.

Related question: what else except lxqt-panel and lxqt-notificationd uses custom LXQt themes?

**Comment by paulolieuthier** [comment]
> This is not a mockup. It is lxqt-panel without LXQt theme.

I wasn't referring to this image, but to all he's already posted. But thanks for the enlightment, I didn't recall that was possible.

> Which means it uses Qt theme, and Qt is configured to use GTK+ engine, and GTK is configured to use "Arc Dark" theme.

This is not what IMO we should strive for. Qt's GTK+ engine is supposed to be used by GTK-based DEs. We shouldn't depend on GTK.

> Related question: what else except lxqt-panel and lxqt-notificationd uses custom LXQt themes?

lxqt-runner.

**Comment by palinek** [comment]
@intialonso You can try the lxde/lxqt-panel#281

**Comment by intialonso** [comment]
@paulolieuthier I put that example using GTK, but this work also with QT, here is an example using Breeze:

![lxqt-breeze](https://cloud.githubusercontent.com/assets/7544231/11369969/69295bc2-928f-11e5-89bb-a38960c2f143.png)

What the OP suggested is to have a "No theme" or "System" theme option in the Appearance Configuration. What this empty theme does, is just make LXQT use the theme of the current "Widget Style" for the panel, notifications and runner.

@palinek Im at the office, I will test this later at home.

**Comment by paulolieuthier** [comment]
I see now.

**Comment by Vladimir-csp** [comment]
>> Which means it uses Qt theme, and Qt is configured to use GTK+ engine, and GTK is configured to use "Arc Dark" theme.

> This is not what IMO we should strive for. Qt's GTK+ engine is supposed to be used by GTK-based DEs. We shouldn't depend on GTK.

Well, lxqt-config-appearance should be able to choose an engine and tweak at least some basic parameters of that engine, like theme. It currently only can choose an engine, but not a theme. If different engines would adhere to common standards regarding themes, engine significance from UX standpoint would dissolve, and choosing a theme would become a prevalent action. GTK is just another engine. @tsujan mentioned in #572 that he will try to make Kvantum use standard themes paths. This part of discussion should continue in #572.

**Comment by tsujan** [comment]
> @tsujan mentioned in #572 that he will try to make Kvantum use standard themes paths

That's done, as you proposed (-> last section of Theme-Making.pdf)  :)

The idea suggested here seems good to me. The default panel background could be `QApplication::palette().color(QPalette::Window)`. The main menu icon could be what is used in the "About LXQT" dialog (LXQT logo, I suppose). All other elements could be left to the theme engine. However, the capability to use a custom panel theme should be kept as it is, IMHO.

**Comment by palinek** [comment]
...submitted PRs for all 3 "styled" components to be able to use widget style background.

**Comment by palinek** [comment]
Resume:
- lxde/lxqt-common#43 adds the "System" theme (no theme)
- lxde/lxqt-panel#282 adds support for the window background of panel
- lxde/lxqt-notificationd#46 & lxde/lxqt-runner#36 adds support for window background of notification & icons for buttons

..after applying all those 4 PRs we have the "System" (No Theme) working, I suppose.

**Comment by palinek** [comment]
All the PRs were merged. The "System" theme has a semi-transparent preview and the lxqt-config-appearance was updated to fill the background of preview on the fly https://github.com/lxde/lxqt-config/commit/4f0f42ec04b6610f83f6b46ad50d6d1a2b155aac

... now this issue is fully resolved, right?

**Comment by hashashini** [comment]
Maybe instead of "System" it should be called "${engine}", that might reduce confusion.
