### ISSUE TITLE
lxqt-config-session/xdg-user-dirs: review relation to binaries xdg-user-dir[s-update]

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#896]
Several problems exist right now when binaries `xdg-user-dir[s-update]` are absent.
E. g. start a session on a new user profile and assign any of the keys corresponding to xdg-user-dirs like `XDG_DOCUMENTS_DIR` an arbitrary directory in `/home/<user>`, log out and in again → `/` is used as desktop directory.
Directory `/home/user/Desktop` gets always created no matter which locale is in use, probably by PCManFM-Qt.

On the other hand LXQt code doesn't depend on binaries `xdg-user-dir[s-update]` in any way.

So either it should be ensured that the code does depend on those binaries somehow. I don't know how a runtime-only dependency like this could be handled, in particular with regards to having an impact on downstream packaging. Similar problem as discussed with regards to lxqt-panel [here](https://github.com/lxde/lxqt/issues/783#issuecomment-141455534), btw.
Otherwise `lxqt-config-session` should behave reasonable if `xdg-user-dir[s-update]` are lacking. Either by fixing the problems stated above (and maybe others). Maybe it would be an option to check for the binaries and just grey all settings in section `Locations` (left pane right now, [probably](https://github.com/lxde/lxqt-session/pull/57) "User Directories" in the future) if these are absent, too.

**Comment by luis-pereira** [comment]
@pmattern Good point. I'm in favor on make `xdg-user-dir[s-update]` an lxqt-session dependecy. I'm not aware of an CMake find_pacakge() that provides that functionalilty, but, it's easy to write one.

**Comment by luis-pereira** [comment]
Closed by lxde/liblxqt#73 and lxde/lxqt-session#60.
