### ISSUE TITLE
Panel CPU Usage Increase

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#898]
I upgraded lxqt-panel and noticed a significant increase in CPU usage. By "significant" I don't mean high at all -- at least not with my powerful laptop -- but while previously all CPU cores showed 0-3% at rest, now one of them shows 10-13%.

I think (but I'm not sure) that this increase is due to some changes in the worldclock plugin.

**Comment by tsujan** [comment]
Yep! It was worldclock. I replaced just that plugin with that of a version from three months ago (with LxQT changed to LXQT) and the CPU usage got normal.

**Comment by palinek** [comment]
So is this a dup of #873 and as so fixed by lxde/lxqt-panel#272?

**Comment by pmattern** [comment]
> So is this a dup of #873 and as so fixed by lxde/lxqt-panel#272?

Hardly. Seeing exactly the behaviour as described by @tsujan with lxde/lxqt-panel@c4345e8 here. 20% of a CPU core running at 1.5GHz when plugin-worldclock is active, about 1% when it's not.

Wouldn't it eventually be reasonable to make plugin-worldclock work the same way as plugin-clock which doesn't increase CPU load either?
Issue is a bit related to eventually merging the two as discussed in #312 but as far as plugin-worldclock is concerned the discussion should go into #873 which needed to get reopened then, shouldn't it?

**Comment by palinek** [comment]
Actualy this is my fault.... and the update timer wash shot each 1ms. Fixed by lxde/lxqt-panel@0957f8a

**Comment by tsujan** [comment]
Yes!  lxde/lxqt-panel@0957f8a fixes this issue :)
