### ISSUE TITLE
pcmanfm-qt not properly scaling icon theme

### ISSUE THREAD

**Issue by LonCJr** [lxde/lxqt#90]
Icons in the navigation bar and main panel aren't being scaled.  Icons in the device panel are though.  See screenshot.
![](https://cdn.mediacru.sh/eh5Wg0M5WA8w.jpg)

This is an odd icon theme, Buuf-Nestort:
http://gnome-look.org/content/show.php/Buuf-based+Nestort?content=143347
Icons are almost completely 128x128 pixel PNG's.

Using Manjaro(Arch based) 64-bit.
pcmanfm-qt-git 0.7.0.2.g86ba94c-1
gtk+2 theme and .gtkrc-2.0.mine

**Comment by PCMan** [comment]
Duplicated. The same problem as #343. Let's fix it there.
