### ISSUE TITLE
One Click on Dektop Icons

### ISSUE THREAD

**Issue by kdax** [lxde/lxqt#900]
Hello,
how can I get rid off  oneclicking icons on my desktop, and change it to doubleclick?
I tried it in the lxqt-menu for mouse and keyboard and unchecked for oneclick the box, but nothing changed. Is there any other option i have to look for or a configuration file?

I'm running manjaro lxqt 15.09.

Thanks for your help.

**Comment by tsujan** [comment]
Do you use Kvantum style engine?

**Comment by kdax** [comment]
I can not tell you, I just installed this release: https://forum.manjaro.org/index.php?topic=26636.msg225284#msg225284

**Comment by tsujan** [comment]
Open LXQT Configuration Center and see if there's any item named "Kvantum Manager".

**Comment by Esclapion** [comment]
Open pcmanfm-qt and have a look in its options.

**Comment by pmattern** [comment]
The relevant setting should be "Open files with single click" in PCManFM-Qt's Preferences - Behaviour (left pane) - Browsing (right pane).

**Comment by pmattern** [comment]
@kdax 
Any news on this one? Can we eventually close this issue?

**Comment by palinek** [comment]
Closing due to lack of feedback.
