### ISSUE TITLE
Create a modern menu

### ISSUE THREAD

**Issue by alfredobonino** [lxde/lxqt#902]
Why not create a modern menu like whisker menu for xfce, the cinnamon menu, the KDE menu or budgie desktop menu???

**Comment by Esclapion** [comment]
With a command search window :-) A lot of users ask for that.

**Comment by intialonso** [comment]
Someone tried to do it in #101 but it seems dead. Maybe this is a duplicate of the same issue.

**Comment by jleclanche** [comment]
dup
