### ISSUE TITLE
Theming problems: Kontact

### ISSUE THREAD

**Issue by m1ga** [lxde/lxqt#903]
I've started using lxqt on Fedora as an alternative to KDE but still want to use some KDE tools.
Its running very well but I have a problem with the themes. Dolphin and other programs look right but kontact doesn't look like its using the theme:
![lxqt](https://cloud.githubusercontent.com/assets/4334997/11323384/8ad7cde6-9111-11e5-8da8-a72146480d67.jpg)

my settings:
stil: oxygen
symbols: breeze
lxqt design: frost

do I miss a package?

**Comment by jleclanche** [comment]
I'm guessing kontact was compiled for qt4?

**Comment by m1ga** [comment]
my bad, you are right. The whole PIM is Qt: 4.8.7,KDE: 4.14.14, Kontact: 4.14.10 in Fedora.

**Comment by m1ga** [comment]
This help: https://github.com/lxde/lxqt/issues/692 using qtconfig-qt4 makes it look better
