### ISSUE TITLE
Exit menu (needless) redundancy

### ISSUE THREAD

**Issue by MttCastelli** [lxde/lxqt#904]
![sshot_systools_detail](https://cloud.githubusercontent.com/assets/11462157/11337122/d4633dcc-91ea-11e5-9920-a6662f8be4f3.jpg)
 
I guess image explains all. The shortcuts for leave options in System tools menu (Strumenti di sistema>) should be removed, cause they all are in the Exit menu (Esci>) 4 rows below already.

**Comment by pmattern** [comment]
This is already addressed in lxde/lxqt-common#42 which only didn't get merged yet.

Maybe we should leave this issue open for now nevertheless in case other users run into the problem, too.

**Comment by pmattern** [comment]
Fixed in lxde/lxqt-common@f30bf43.

**Comment by MttCastelli** [comment]
![sshot_systools_detail3](https://cloud.githubusercontent.com/assets/11462157/11363264/0f328a62-9299-11e5-8e0e-536b30084a68.jpg)
 You're all fast to solve, when you want (see #541;)

**Comment by pmattern** [comment]
Your previous screenshot is displaying exactly the expected behaviour. Could you please elaborate what should be wrong there?

**Comment by MttCastelli** [comment]
Nothing, the latest sshot just to show you it's solved and to thank. :)

**Comment by pmattern** [comment]
Alright. I was assuming you still saw a problem as you were referencing #541 which is *not* solved yet.
