### ISSUE TITLE
[lxqt-panel] panel does not detect monitor / resolution changes 

### ISSUE THREAD

**Issue by quite** [lxde/lxqt#906]
When I move my desktop from laptop screen to external, the panel does not detect the change in resolution, and is positioned vertically 1/3 from the bottom of the external screen. Should it perhaps detect the change? Opening the lxqt session program and from there stopping and then starting the Panel again will correct its position.

**Comment by palinek** [comment]
> When I move my desktop from laptop screen to external

Please, be more specific about the procedure of "moving desktop.

**Comment by quite** [comment]
Plugging in my screen as VGA and using "monitor settings" program do first deactivate LVDS* (1366x768) and then activate VGA (1680x1050)

**Comment by pmattern** [comment]
> Opening the lxqt session program and from there stopping and then starting the Panel again will correct its position.

Don't understand. Could you please elaborate what you mean here?

That aside we've been seeing a similar problem some months ago, please read https://github.com/lxde/lxqt/issues/650#issuecomment-107385604. Could very well be that `lxqt-config-monitor` is setting something similar here.
Please post the output of `xrandr` right when you're seeing the problem.

Also, we need to know which OS and version of LXQt you're running and how the latter was installed.

**Comment by quite** [comment]
> > Opening the lxqt session program and from there stopping and then starting the Panel again will correct its position.
> 
> Don't understand. Could you please elaborate what you mean here?

It was just a way to restart lxqt-panel. Same effect if I just kill
the lxqt-panel process and manuall start it again -- it realizes how big my
primary screen actually is and positions itself correctly at the bottom.

> That aside we've been seeing a similar problem some months ago, please read https://github.com/lxde/lxqt/issues/650#issuecomment-107385604. Could very well be that `lxqt-config-monitor` is setting something similar here.
> Please post the output of `xrandr` right when you're seeing the problem.

    Screen 0: minimum 8 x 8, current 1680 x 1050, maximum 32767 x 32767
    LVDS1 connected (normal left inverted right x axis y axis)
       1366x768      60.00 +
       1280x720      60.00  
       1024x768      60.00  
       1024x576      60.00  
       960x540       60.00  
       800x600       60.32    56.25  
       864x486       60.00  
       640x480       59.94  
       720x405       60.00  
       680x384       60.00  
       640x360       60.00  
    DP1 disconnected (normal left inverted right x axis y axis)
    DP2 disconnected (normal left inverted right x axis y axis)
    DP3 disconnected (normal left inverted right x axis y axis)
    HDMI1 disconnected (normal left inverted right x axis y axis)
    HDMI2 disconnected (normal left inverted right x axis y axis)
    HDMI3 disconnected (normal left inverted right x axis y axis)
    VGA1 connected primary 1680x1050+0+0 (normal left inverted right x axis y axis) 473mm x 296mm
       1680x1050     59.95*+
       1600x1000     60.01  
       1280x1024     75.02    60.02  
       1440x900      59.89  
       1280x960      60.00  
       1152x864      75.00  
       1024x768      75.08    60.00  
       832x624       74.55  
       800x600       75.00    60.32  
       640x480       75.00    60.00  
       720x400       70.08  
    VIRTUAL1 disconnected (normal left inverted right x axis y axis)

> Also, we need to know which OS and version of LXQt you're running and how
> the latter was installed.

Fresh Arch Linux, with lxqt "0.10.0-2" installed from community.


Again, the issue I'm having is that lxqt-panel doesn't react to my primary
monitor changing (from both laptop & external monitor being active
(mirrored) just after I startx, to only external active, achieved using
lxqt-config-monitor). But I have no idea of how this is supposed to happen,
if at all...

**Comment by palinek** [comment]
I believe, this is fixed by lxde/lxqt-panel#310 and the @RalfJung's patch in Qt https://codereview.qt-project.org/#/c/153942

Can we close it?

**Comment by pmattern** [comment]
Except the minor problem left discussed in lxde/lxqt-panel#310 I'd agree we can, yes.
Maybe @quite can test latest panel master and drop another note.
