### ISSUE TITLE
VLC leave an empty task on the panel

### ISSUE THREAD

**Issue by MttCastelli** [lxde/lxqt#907]
![sshot_vlc2](https://cloud.githubusercontent.com/assets/11462157/11440270/6239c3b4-9501-11e5-952f-4c925b826193.jpg)

![sshot_vlc3](https://cloud.githubusercontent.com/assets/11462157/11440431/a8aecd84-9502-11e5-9dd9-6532af7f13fa.jpg)

VLC (and maybe other app) leave an empty task on the lxqt-panel. While when it is running it count 2 tasks (2nd sshot): the empty one and the one of the video actually playing.
Sometimes, closing another app such as the broser (qupzilla, here) also the empty taskbar disappear, but not always.

**Comment by tsujan** [comment]
I confirm that the task manager sometimes shows empty tasks when a window is created by `showMinimized()` and then closed by `close()` in the code of an app.

**Comment by MttCastelli** [comment]
And the latest trojita-nightlies 0.5+bzr4526+201511271601~ubuntu15.10.1 too, just upated from lubuntu-dev PPA for wily.

**Comment by tsujan** [comment]
@palinek 
So, it was a bug in KWindowsSystem and you worked around it?

**Comment by palinek** [comment]
> So, it was a bug in KWindowsSystem and you worked around it?

I don't know if it's a bug or feature :)

**Comment by MttCastelli** [comment]
Here is openbox, anyway.

Il giorno mar 1 dic 2015, 13:32 palinek <notifications@github.com> ha
scritto:

**Comment by palinek** [comment]
> Here is openbox, anyway.

[KWindowSystem](http://api.kde.org/frameworks-api/frameworks5-apidocs/kwindowsystem/html/index.html) is a library we are using, independent on window manager.

**Comment by tsujan** [comment]
@palinek 
The strange thing is that, even without your patch, I don't see the problem anymore. Maybe it was really a KWindowsSystem bug, which is fixed in libkf5windowsystem-5.16.0.

**Comment by palinek** [comment]
> The strange thing is that, even without your patch, I don't see the problem anymore. Maybe it was really a KWindowsSystem bug, which is fixed in libkf5windowsystem-5.16.0.

For me this bug wasn't reproducible all the time.
It can be, that something got fixed in KWindowSystem, but IMO the lxde/lxqt-panel@592a2a7 doesn't hurt.
