### ISSUE TITLE
FTBFS as of e069600

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#908]
As of lxde/lxqt-config@e069600 lxqt-config fails to build from source.

The usual cmake invocation doesn't report any problems but make fails throwing
```
[...]
Scanning dependencies of target lxqt-config-locale_automoc
[ 96%] Automatic moc, uic and rcc for target lxqt-config-locale
Generating ui_localeconfig.h
Generating moc_localeconfig.cpp
[ 96%] Built target lxqt-config-locale_automoc
[ 96%] Generating lxqt-config-locale.desktop
lxqt-config-locale/CMakeFiles/lxqt-config-locale.dir/build.make:73: recipe for target 'lxqt-config-locale/lxqt-config-locale.desktop' failed
make[2]: *** [lxqt-config-locale/lxqt-config-locale.desktop] Error 1
make[2]: *** Deleting file 'lxqt-config-locale/lxqt-config-locale.desktop'
CMakeFiles/Makefile2:707: recipe for target 'lxqt-config-locale/CMakeFiles/lxqt-config-locale.dir/all' failed
make[1]: *** [lxqt-config-locale/CMakeFiles/lxqt-config-locale.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
Unfortunately I haven't got time to try and look into this deeper but preceding commit lxde/lxqt-config@4f0f42e definitely compiles and works flawlessly on the very same systems.

**Comment by palinek** [comment]
Sorry... my fault. @luis-pereira shouldn't we change the [translation](https://github.com/lxde/liblxqt/blob/master/cmake/modules/LXQtTranslateDesktop.cmake#L75) to not fail if no suitable lines found? Or is it better to know that the translation file is "bad" in compile time?

**Comment by pmattern** [comment]
If you don't mind me adding my two cents:
Please don't change the current behaviour as it's always better to get aware of problems. This even applies if the consequence is something as serious as the FTBFS seen here which still ceases when the underlying problem gets fixed.

**Comment by luis-pereira** [comment]
@palinek We could but them it would become much harder to find the cause. It took me a minute to find it. I agree with @pmattern

**Comment by palinek** [comment]
Agreed
