### ISSUE TITLE
Receiving errors on ubuntu 14.04 after building develop

### ISSUE THREAD

**Issue by ferronrsmith** [lxde/lxqt#910]
After building the master branch I got the following error :

pcmanfm-qt: symbol lookup error: /usr/local/lib/libfm-qt.so.2: undefined symbol: _ZNK19QAbstractProxyModel15canDropMimeDataEPK9QMimeDataN2Qt10DropActionEiiRK11QModelIndex

Can anyone point me in the right direction on how to resolve this. I am using Qt 5.5.1 to build `lxqt`

ldd output

```bash
	linux-vdso.so.1 =>  (0x00007ffc7ddfa000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007fd321370000)
	libQt5X11Extras.so.5 => /usr/lib/x86_64-linux-gnu/libQt5X11Extras.so.5 (0x00007fd32116c000)
	libfm.so.4 => /usr/local/lib/libfm.so.4 (0x00007fd320f30000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fd320bbd000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fd32096c000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fd320664000)
	libmenu-cache.so.3 => /usr/local/lib/libmenu-cache.so.3 (0x00007fd32045b000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007fd31fe0e000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007fd31f768000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd31f45c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd31f097000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd31ee79000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fd31eb44000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd31e83e000)
	libexif.so.12 => /usr/lib/x86_64-linux-gnu/libexif.so.12 (0x00007fd31e5fa000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd31e3f6000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fd31e1f2000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd31dfd9000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fd31ddb6000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fd31db9b000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fd31d993000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fd31d755000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fd31d52f000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fd31d2da000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007fd31d04b000)
	libicui18n.so.52 => /usr/lib/x86_64-linux-gnu/libicui18n.so.52 (0x00007fd31cc44000)
	libicuuc.so.52 => /usr/lib/x86_64-linux-gnu/libicuuc.so.52 (0x00007fd31c8cb000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd31c6c3000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd31c4ac000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd321e63000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fd31c28d000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fd31bfea000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fd31bdce000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fd31bba4000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007fd31b976000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fd31b764000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fd31b561000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fd31b35b000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fd31b159000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007fd31af42000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007fd31ad3d000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007fd31ab3a000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007fd31a937000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007fd31a731000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007fd31a52f000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fd31a329000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fd31a11b000)
	libicudata.so.52 => /usr/lib/x86_64-linux-gnu/libicudata.so.52 (0x00007fd3188ae000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fd3186aa000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fd3184a4000)
```

**Comment by palinek** [comment]
Do you have multiple versions of Qt installed?
Can it be, that in runtime the older version of `libQt5Core` is loaded? (`canDropMimeData` was added in v5.4 http://doc.qt.io/qt-5/qabstractproxymodel.html#canDropMimeData)
What does `nm -D /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 | egrep canDropMimeData | c++filt` say?

**Comment by ferronrsmith** [comment]
I only have 1 version of QT installed ~/Qt/5.5.

The `libQt5Core` is used by other applications so that might be causing a conflict


`nm -D /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 | egrep canDropMimeData | c++filt`

```bash
000000000021ad30 T QAbstractItemModel::canDropMimeData(QMimeData const*, Qt::DropAction, int, int, QModelIndex const&) const
```

**Comment by luis-pereira** [comment]
@ferronrsmith I have Qt 5.5 on Arch.
My output:
```
000000000023f160 T QAbstractItemModel::canDropMimeData(QMimeData const*, Qt::DropAction, int, int, QModelIndex const&) const
000000000024b790 T QAbstractProxyModel::canDropMimeData(QMimeData const*, Qt::DropAction, int, int, QModelIndex const&) const
```


So, in some way you are not using Qt 5.5.

**Comment by pmattern** [comment]
@ferronrsmith
You are aware that libfm-qt has been moved to a repo on its own some days ago and hence recent PCManFM-Qt checkouts have got to get compiled against that oursourced version of libfm-qt?
Asking as
> pcmanfm-qt: symbol lookup error: /usr/local/lib/libfm-qt.so.2: undefined symbol: 

had made me wonder whether some wrong version of libfm-qt could eventually be involved. It's not too likely as cmake is complaining about missing files `fm-qtConfig.cmake` or `fm-qt-config.cmake` in case the matching libfm-qt is lacking, though.

That aside I'm not that sure whether compiling recent VCS checkouts of LXQt on that elderly Ubuntu version is a really good idea. I remember that I tried this some months ago but gave up finding it too cumbersome.
Just saying...

**Comment by palinek** [comment]
> I only have 1 version of QT installed ~/Qt/5.5.
The libQt5Core is used by other applications so that might be causing a conflict

So, you definitely have at least 2 versions of Qt installed. I assume that you are compiling against the v5.5 in *~/Qt/5.5*, but in runtime the system's v5.2 in */usr* is linked.

**Comment by ferronrsmith** [comment]
@pmattern Yea i did checkout the latest repositories sometime yesterday. I guess the ubuntu version is just too old to build. I'll probably end up using the prepackaged version of lxqt.

**Comment by palinek** [comment]
>  I'll probably end up using the prepackaged version of lxqt.

If you were able to build the lxqt packges. You should also be able to run them. Did you try to point the loader to your *~/Qt/5.5* libraries by LD_LIBRARY_PATH ?

**Comment by ferronrsmith** [comment]
echo $LD_LIBRARY_PATH                                                                                                                                                                                    
`/home/ferron/.gvm/pkgsets/go1.4.2/global/overlay/lib:~/Qt/5.5/gcc_64/lib/:`
 

`nm -D ~/Qt/5.5/gcc_64/lib/libQt5Core.so.5.5.1 | egrep canDropMimeData | c++filt`

```bash
0000000000237340 T QAbstractItemModel::canDropMimeData(QMimeData const*, Qt::DropAction, int, int, QModelIndex const&) const
00000000002433e0 T QAbstractProxyModel::canDropMimeData(QMimeData const*, Qt::DropAction, int, int, QModelIndex const&) const
```

**Comment by palinek** [comment]
And? Are you able to run the pcmafm-qt with that?

**Comment by ferronrsmith** [comment]
@palinek  Yup everything worked! thanks for the help!
