### ISSUE TITLE
openbox context menu entry obconf does not call obconf-qt

### ISSUE THREAD

**Issue by shze** [lxde/lxqt#912]
I'm running LXQt (Debian testing, lxqt packages 0.10.0-2) with OpenBox and obconf-qt. 

Clicking on "ObConf" in the OpenBox context menu (right click on Desktop) should call obconf-qt, but only results in the error: "Failed to execute child process 'obconf' (No such file or directory)". Running obconf-qt manually works. When obconf instead of obconf-qt is installed, obconf is called correctly.

**Comment by palinek** [comment]
The menu you're talking about is provided by openbox itself. Obconf is it's default (and AFAIK the only supported) configuration tool. We're providing a Qt port of obconf, but this is not something that openbox is considering.
We can't do anything with it. You can try to talk to openbox people.

**Comment by stefonarch** [comment]
You can still  try to create a symlink in  /usr/bin/ 
obconf → obconf-qt
