### ISSUE TITLE
Can't have a binary & folder with the same name

### ISSUE THREAD

**Issue by ferronrsmith** [lxde/lxqt#918]
Not sure if this is normal, but I can't seem to have a binary and a folder with the same name.

My thought is that the file manager would be able to differentiate between a folder and a file

'eclipse' the folder vs 'eclipse' the executable

**Comment by tsujan** [comment]
No two files can have the same name under the same directory. If you think you've seen such a thing under MS Windows, that's because Windows may not show the whole file name (hiding its extension).

And of course, pcmanfm-qt differentiates between files and folders!! And more than that.

**Comment by ferronrsmith** [comment]
Apologies for my ignorance.
