### ISSUE TITLE
My screen have bug.

### ISSUE THREAD

**Issue by BlackHat26** [lxde/lxqt#922]
![screenshot from 2015-12-20 21-08-12](https://cloud.githubusercontent.com/assets/15937173/11918329/d409f3be-a75e-11e5-94fd-72bd992c1279.png)

At the corner of my screen with a few white dots. I don't know how to fix it. I tried to change background and theme but it not change. 

![screenshot from 2015-12-20 21-20-43](https://cloud.githubusercontent.com/assets/15937173/11918340/9435c802-a75f-11e5-88d7-e560b9fe91eb.png)
![screenshot from 2015-12-20 21-21-41](https://cloud.githubusercontent.com/assets/15937173/11918350/cfc82694-a75f-11e5-8515-14a7a7c83be1.png)

Somebody help me fix this bug. Thanks. 
I think lxqt very promising.

**Comment by intialonso** [comment]
Looks like you have the panel set to a very low height. I guess you cant right click on that little panel, so go to ./config/lxqt/ and edit the panel.conf file, we want to change the "panelSize" line, put anything above 24.

**Comment by BlackHat26** [comment]
It not solve my problem! So sad. :(

**Comment by intialonso** [comment]
Delete the ./config/lxqt/ folder completly and restart your session.
