### ISSUE TITLE
Launchers in Task Manager widget

### ISSUE THREAD

**Issue by goetzc** [lxde/lxqt#925]
Having launchers in the task manager instead of being a separated widget would give the advantage of using less space by reusing the icon (transforming the launcher icon into the task), and provide the possibility to create a launcher for any running application by right clicking the task icon and selecting the option.

**Comment by intialonso** [comment]
I agree. I guess i done like this for convenience and easiness, but in the future I think that it should work as you propose. Lets wait if someone can take the job.

**Comment by pmattern** [comment]
Duplicate of #131.
