### ISSUE TITLE
Panel fails to launch as of 01db080

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#928]
As of commit lxde/lxqt-panel@01db080 the panel fails to launch.

An attempt to launch from a virtual terminal yields a message
```
]$ lxqt-panel & 
[1] 721
[peter@arch-64-lxqt-git ~]$ ()
lxqt-panel: symbol lookup error: /usr/lib/lxqt-panel/libcpuload.so: undefined symbol: _ZNK14PluginSettings5valueERK7QStringRK8QVariant
```

Apparently it's a regression introduced somewhere between lxde/lxqt-panel@456f597 and lxde/lxqt-panel@01db080. Further bisecting doesn't seem to be possible as commits lxde/lxqt-panel@456f597 and lxde/lxqt-panel@fa9d8b8 fail to build from source with error message
```
[ 56%] Building CXX object plugin-sensors/CMakeFiles/sensors.dir/lxqtsensorsplugin.cpp.o
/usr/local/peter/lxqt-panel-git/src/lxqt-panel/plugin-sensors/lxqtsensorsplugin.cpp: In member function 'virtual QDialog* LXQtSensorsPlugin::configureDialog()':
/usr/local/peter/lxqt-panel-git/src/lxqt-panel/plugin-sensors/lxqtsensorsplugin.cpp:55:51: error: no matching function for call to 'LXQtSensorsConfiguration::LXQtSensorsConfiguration(PluginSettings*)'
     return new LXQtSensorsConfiguration(settings());
                                                   ^
In file included from /usr/local/peter/lxqt-panel-git/src/lxqt-panel/plugin-sensors/lxqtsensorsplugin.cpp:30:0:
/usr/local/peter/lxqt-panel-git/src/lxqt-panel/plugin-sensors/lxqtsensorsconfiguration.h:47:14: note: candidate: LXQtSensorsConfiguration::LXQtSensorsConfiguration(QSettings*, QWidget*)
     explicit LXQtSensorsConfiguration(QSettings *settings, QWidget *parent = nullptr);
              ^
/usr/local/peter/lxqt-panel-git/src/lxqt-panel/plugin-sensors/lxqtsensorsconfiguration.h:47:14: note:   no known conversion for argument 1 from 'PluginSettings*' to 'QSettings*'
plugin-sensors/CMakeFiles/sensors.dir/build.make:163: recipe for target 'plugin-sensors/CMakeFiles/sensors.dir/lxqtsensorsplugin.cpp.o' failed
make[2]: *** [plugin-sensors/CMakeFiles/sensors.dir/lxqtsensorsplugin.cpp.o] Error 1
CMakeFiles/Makefile2:966: recipe for target 'plugin-sensors/CMakeFiles/sensors.dir/all' failed
make[1]: *** [plugin-sensors/CMakeFiles/sensors.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

```

Up to date Arch Linux x86_64 with all LXQt components from latest Git checkouts via their AUR packages.

**Comment by palinek** [comment]
This is strange... I can compile/run the latest GIT sources happily.

@pmattern  Isn't it possible, that you're running different builds of `lxqt-panel` binary and plugins (`plugin-cpuload`)?

**Comment by stefonarch** [comment]
Same thing here, talked about on IRC; arch linux latest AUR everything up-to-date.
git checkout 470bbb06f4dcfbde66e928e570f49749d49f8704 and then compiling  works.

After deleting config files my error changed from libsensors to libvolume:

lxqt-panel: symbol lookup error: /usr/lib/lxqt-panel/libsensors.so: undefined symbol: 
stef@arch:~/.config/lxqt$ rm panel.conf*
stef@arch:~/.config/lxqt$ lxqt-panel 
lxqt-panel: symbol lookup error: /usr/lib/lxqt-panel/libvolume.so: undefined symbol: _ZNK14PluginSettings5valueERK7QStringRK8QVariant
.

**Comment by pmattern** [comment]
Output when starting the panel from a virtual terminal after compiling with `-DCMAKE_BUILD_TYPE=Debug` set as discussed in IRC, additionally on a new user profile
```
$ lxqt-panel & 
[1] 693
[peter@arch-64-lxqt-git ~]$ QFSFileEngine::open: No file name specified
XdgDesktopFile "firefox.desktop" is not valid
QFSFileEngine::open: No file name specified
XdgDesktopFile "chromium-browser.desktop" is not valid
()
lxqt-panel: symbol lookup error: /usr/lib/lxqt-panel/libvolume.so: undefined symbol: _ZNK14PluginSettings5valueERK7QStringRK8QVariant
```

Neither Firefox nor Chromium are installed, files `firefox.desktop` and `chromium-browser.desktop` cannot be found by mlocate. So the corresponding messages are probably due to these files being referenced in `./panel/resources/panel.conf` (source code).

**Comment by stefonarch** [comment]
I had exact the same output except that I got only the chromium-desktop error.

**Comment by paulolieuthier** [comment]
Where do you have plugins installed? `/usr/share` and `/usr/local/share`? The plugins built before that commit won't work. Delete them all and reinstall.

**Comment by pmattern** [comment]
@paulolieuthier 
The plugins are in `/usr/lib/lxqt-panel`. But anyway, conflicting old and new versions of panel components shouldn't be possible if all versions of lxqt-panel were installed via the same AUR package [lxqt-panel-git](https://aur.archlinux.org/packages/lxqt-panel-git/), should they?

**Comment by paulolieuthier** [comment]
Yeah, s/share/lib.

**Comment by nbvcxz** [comment]
Confirmed - same symptoms with lxqt-panel-git in Arch Linux x86_64 (everything up to date, testing repo not used)

**Comment by palinek** [comment]
Can anyone with the symptoms described here test if the lxde/lxqt-panel#920 does the trick?

**Comment by stefonarch** [comment]
Seems working for me.

**Comment by palinek** [comment]
Finaly... I've got the failure here also. The difference was the compiler gcc vs. clang.

Merging the PR....
