### ISSUE TITLE
Problems with task manager when panel 'auto-hide' attribute is set

### ISSUE THREAD

**Issue by jauhien** [lxde/lxqt#930]
When there is a number of windows for a given application, they all are shown in one entry that gives a drop-down menu, when mouse comes across it. When the panel that task manager belongs to, has 'auto-hide' attribute set, this menu disappears when user tries to click on any of entries. This probably happens because mouse goes out of the main panel space and drop-down menu is not considered as the part of the panel, so the panel gets hiden. This destroys drop-down menu.

LXQT version: 0.10.0.

**Comment by pmattern** [comment]
The problem has been discussed in #871 and is fixed in Git.

On a side note grouping of windows into a single button in "Task Manager" / plugin-task isn't mandatory. It can be toggled and tweaked in dialogue "Task Manager Settings" which can be invoked from the plugin's context menu.
