### ISSUE TITLE
plugin-mainmenu: issues in way to deal with icons

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#931]
The way plugin-mainmenu deals with the icon displayed in the panel suffers from some issues the adjustment of which could improve the UX.

When LXQt gets launched the first time on a user's profile `/usr/share/lxqt/graphics/helix.svg` is displayed. When the theme gets changed from `lxqt-config-appearance` plugin-mainmenu starts displaying the icons which belong to the selected theme, among other `mainmenu.svg` and no longer `helix.svg` if some other theme gets selected and then Frost again.
This is an inconsistency which albeit minor may be confusing.
So I suggest the icon belonging to the active theme, `mainmenu.svg` in Frost right now, should always be displayed unless an other icon is manually chosen in dialogue "Main Menu settings".

Sometimes the icon corresponding to the active theme gets replaced with `helix.svg` for apparently no reason. Happens sporadically, couldn't find out the trigger yet.

When another theme gets chosen in `lxqt-config-appearance` and the corresponding icon is rightly displayed in plugin-mainmenu form "Icon" in GUI "Main Menu settings" - General nevertheless keeps stating `/usr/share/lxqt/graphics/helix.svg` all the time.
This shouldn't happen, rather the path displayed in form "Icon" should always reflect the icon that's in fact in use.
FWIW GUI "Desktop Preferences" (`pcmanfm-qt --desktop-pref=[...]`) is in a similar relationship to `lxqt-config-appearance` with regards to the wallpaper graphics but does adopt changes made in `lxqt-config-appearance` correctly

Recent VCS checkouts of all LXQt components on Arch Linux.

**Comment by palinek** [comment]
@pmattern can you, please, check if the lxde/lxqt-panel#298 can be considered as fix to this issue?

**Comment by pmattern** [comment]
All problems seem to be solved by lxde/lxqt-panel@fa0610e.
The icon belonging to the actual theme is by default selected all the time.
Can't say much about that falling back to `helix.svg` as it was happening sporadically only. But considering that the way the icon gets chosen in dialogue "Main Menu settings" was revamped completely it seems very likely that this problem is fixed, too.
An icon chosen individually from "Main Menu settings" supersedes the icons of the themes even if the latter get tweaked in lxqt-config-appearance which makes just as much sense as the revamped method to choose icons in "Main Menu settings".

While testing I stumbled upon something that's not related to lxde/lxqt-panel@fa0610e but to this issue and that *could* eventually be changed additionally:
When an individual icon had already been selected and another one shall get selected from "Main Menu settings" dialogue "Choose icon file" always starts looking in `/usr/share/lxqt/graphics`. I think it would be more convenient if the default directory was either something more suitable like e. g. `/usr/share/icons` or, maybe even better, simply the directory comprising the currently active icon.

**Comment by palinek** [comment]
> When an individual icon had already been selected and another one shall get selected from "Main Menu settings" dialogue "Choose icon file" always starts looking in /usr/share/lxqt/graphics. I think it would be more convenient if the default directory was either something more suitable like e. g. /usr/share/icons or, maybe even better, simply the directory comprising the currently active icon.

Tried to fix in lxde/lxqt-panel@216669b. @pmattern please, confirm.

**Comment by pmattern** [comment]
@palinek 
As of lxde/lxqt-panel@216669b dialog "Choose icon file" starts to look in the old icon's directory when a distinct icon that had been selected before gets modified.
So really everything fixed now.
