### ISSUE TITLE
plugin-quicklaunch: shipping default applications seems questionable

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#933]
While it's very reasonable to have plugin-quicklaunch appear in the default panel on new user profiles the benefit of adding applications to the plugin by default seems questionable.

Any preselection will be a matter of personal taste. So it's very likely users will have to adjust it anyway and hence don't save any time compared to an instance of plugin-quicklaunch that's empty in the first place.
More importantly preselections in plugin-quicklaunch are making it much less intuitive to understand the plugin's mode of operation for first-time users, IMO. Without any content there's a text "Drop application icons here" which is helpful trying to understand how the plugin works. If on the other hand content preexists it's not even obvious to see that the different icons belong to the same panel plugin let alone how the latter is meant to be used.

All in all I think it would be much better to simply drop those preselections like in pmattern/lxqt-panel@da96995.

Note
Preselections of applications have been available in `/etc/xdg/lxqt/panel.conf` for ages but became manifest by default in lxde/lxqt-panel@9d6345e only. Until lxde/lxqt-panel@470bbb0 they became manifest only if the panel was invoked as `lxqt-panel --config /etc/xdg/lxqt/panel.conf` which is probably related to #250. (The commits between the two stated above failed to work, see lxde/lxqt#928.)

**Comment by palinek** [comment]
+1

**Comment by palinek** [comment]
+1

@pmattern the pmattern/lxqt-panel@da96995 is GTM

**Comment by paulolieuthier** [comment]
> @pmattern the pmattern/lxqt-panel@da96995 is GTM

Agreed. Ship it.
