### ISSUE TITLE
Mouse non-functional

### ISSUE THREAD

**Issue by saucyjack42** [lxde/lxqt#935]
As the title states.  Clicking works but mouse movement does not register.

**Comment by palinek** [comment]
1. This definitely seems, that it isn't connected to any LXQt component.
2. I doubt, that anyone could be able to hlep you witch such description (we aren't magicians with superpowers).

Please, elaborate more or close this issue.

**Comment by saucyjack42** [comment]
'we aren't magicians with superpowers'
Pfft, you're making an amazing DE, of course you are.
Gnome 3 and Budgie function just fine.  I'm running Arch Linux, libinput (have tried multiple versions), and GDM for the manager.

**Comment by pmattern** [comment]
So could you please enlighten us as to which version of LXQt you're running, probably either the release packages from the community repo or the VCS packages from the AUR?
Is it "bare metal" or in a virtual machine (if so, in which)? Graphics Driver in use?

**Comment by stefonarch** [comment]
Could be a problem of using gdm, as far as I know only sddm is supported by LXQt

**Comment by tsujan** [comment]
> Could be a problem of using gdm

No! I have gdm too and everything is fine.

**Comment by tsujan** [comment]
Oh, sorry, I mistook gdm with lightdm -- I use the latter and have neither gdm nor sddm. My bad!

**Comment by saucyjack42** [comment]
I'm running lxqt .10 from the community Arch repo. It's not running in a virtual machine. Graphics driver is Mesa, not that it should matter.

**Comment by bleverett** [comment]
I had this issue with my work computer.  Upgraded from lxqt-0.8.0 to lxqt-0.10.0 and mouse/kbd did not work.  I had to ssh in with my phone to recover the computer.  I am running gentoo linux.  lxqt-0.8.0 runs great.  I had to revert to something working quickly so I didn't have time to investigate.

**Comment by tsujan** [comment]
@bleverett  Which display manager you used? GDM, SDDM ot Lightdm?

**Comment by bleverett** [comment]
I use lxdm, although I could try lightdm.

**Comment by tsujan** [comment]
> I use lxdm, although I could try lightdm.

I was just suspicious of GDM. That suspicion is ruled out now.
