### ISSUE TITLE
proposal: nomacs as default image viewer.

### ISSUE THREAD

**Issue by MttCastelli** [lxde/lxqt#938]
https://github.com/nomacs/nomacs

It's qt5, so you don't have to develop your own.

**Comment by palinek** [comment]
I'm using it happily...

**Comment by tsujan** [comment]
@MttCastelli  and @palinek 
nomacs is a decent Qt image viewer -- I agree. But why should we abandon lximage-qt with all the potentials in its code? I use my own Qt image viewer because lximage-qt has problem with scaling svg images but I decided to fix its problems/drawbacks and use it in the future (I already added gif support). Why not reporting its bugs and request more features for it instead? Is there any fundamental problem with it in your opinion?

**Comment by palinek** [comment]
I didn't say "let's abandon lximage-qt". I just noted, that I'm using it too. 
OK... i should better say "...probably all lximage-qt devs are aware of *nomacs*, but they want to invest their time into it"

**Comment by tsujan** [comment]
@palinek
OK, I admit that I misunderstood your words, although I couldn't have misunderstood the title of this issue: there couldn't be two defaults and I'm against making nomacs the default image viewer, which would mean adding it to https://github.com/lxde/, which, in its turn, would mean leaving lximage-qt as it is.

**Comment by paulolieuthier** [comment]
Choosing nomacs as the default image viewer doesn't mean adding it to our organization, it means advertising it to the distributions willing to use LXQt by default. Anyway, although it sounds nice to reduce the amount of work in the project by choosing a thirdy part app, we (as @tsujan said) already have our own image viewer.

**Comment by gbcox** [comment]
On Tue, Jan 12, 2016 at 10:29 AM, Paulo Lieuthier <notifications@github.com>
wrote:

> Choosing nomacs as the default image viewer doesn't mean adding it to our
> organization, it means advertising it to the distributions willing to use
> LXQt by default. Anyway, although it sounds nice to reduce the amount of
> work in the project by choosing a thirdy part app, we (as @tsujan
> <https://github.com/tsujan>
>
> said) already have our own image viewer.
>
>
I didn't even know what lximage was... it isn't currently in the Fedora
distribution - I DO see it has been recently approved to be included
(rhbz#1293075).  I've been using Gwenview.  Also just tested nomacs and it
appears to work fine also.

**Comment by MttCastelli** [comment]
...or use it as an easy and small image manipulation tool: LXQt under Ubuntu uses mtpaint (GTK), just to let you know. Regards
