### ISSUE TITLE
Suspend/Hibernate not working with consolekit2 

### ISSUE THREAD

**Issue by ophuls** [lxde/lxqt#939]
lxqt-0.10.0 on a Gentoo system with OpenRC and consolekit2 doesn't support suspend/hibernate functionality.
I found the following commits in liblxqt git:
https://github.com/jordi-pujol/liblxqt/commit/e624cbb0f4402a8cf1fa5fcc68a9652fdf12a475
https://github.com/jordi-pujol/liblxqt/commit/01cca711067fdf4cfe4d96c971d3613d95febcaf
I applied the patch to my laptop and all seems working fine.
Any ideas why those commits weren't merged and the pull request was closed? 

thanks
thomas

**Comment by paulolieuthier** [comment]
Original PR: lxde/liblxqt#47.

**Comment by ophuls** [comment]
Still don't understand if the proposed PR https://github.com/lxde/liblxqt/pull/47 was not ok from the code point of view or if it was closed because of not enough regression test performed.
As for now I can use a local overlay in my gentoo system to apply original PR patch.
I'm quite bad in coding so I do not have a better solution for the issue and I don't think a new PR with the same commit is the right way to go.

thanks anyway

**Comment by paulolieuthier** [comment]
@ophuls I only referenced the original PR to explain what happened and give the background. I'll take a look at it.

**Comment by paulolieuthier** [comment]
@ophuls can you test the `consolekit` branch please?

**Comment by ophuls** [comment]
@paulolieuthier I tested the consolekit branch and cannot work. 
Looks like that using "dBusCall" is ok only for command "Restart" and "Stop".
For command "Suspend" and "Hibernate" the dbusCallSystemd need to be used, if not I see in the notification area the following error:
**Type of message '()' does not match expected type '(b)'**

Maybe is due to the fact that using in terminal the following:

*dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.CanStop*

will return a boolean (true) but using  

*dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.CanSuspend*

will return a string ("yes")?

Sorry for my poor "styling"!

**Comment by paulolieuthier** [comment]
Please update and try again.

**Comment by ophuls** [comment]
@paulolieuthier: updated and tested.
With this update the commands "Suspend" and "Hibernate" work correctly from leave menu or leave dialog windows.
But now "Stop" and "Restart" stop to work: they are grayed out in the leave dialog windows and if executed directly from the leave menu nothing happen, no error in notification area.

**Comment by paulolieuthier** [comment]
@ophuls try again please. All actions should be working now.

**Comment by ophuls** [comment]
@paulolieuthier tested your update, all works good.
But looking more deep in the code I think I found out why Stop/Restart and Suspend/Hibernate need different dbuscall functions (wrong method). 
I submitted the PR https://github.com/lxde/liblxqt/pull/79 to the consolekit branch, the PR should simplify a little the code. 
I tested on my laptop also this change and everything works good (with consolekit2- 1.0.1).
If you can, please review it. If something wrong let me know (first time with Git!).

thanks
thomas

**Comment by paulolieuthier** [comment]
You solution is very good, the only problem is that is uses consolekit2, not the original consolekit, which the major distros ship (e.g. Debian unstable). Am I wrong? @agaida ping.

**Comment by ophuls** [comment]
Both solutions can work in my case and of course it my PR is going to break things feel free to close it!
I just wonder if suspend/hibernate (which need to call "dbusCallSystemd") can work also with original consolekit. Unfortunately I found it hard to downgrade my system to the original consolekit without making a mess in order to test.

**Comment by pierre-labastie** [comment]
Let me add a few comments:
- No, original ConsoleKit does not have the Suspend/Hibernate Capability. Only Restart/Shutdown.
- Distros using systemd do not need to use ConsoleKit for Suspend/Hibernate/Shutdown/Reboot, since those capabilities are provided by logind. So this PR wouldn't break things on those distros.
- Only Distros without systemd need an alternative to UPower, since new versions of UPower have dropped Suspend/Hibernate capability. For those, ConsoleKit2 is the way to go, and this PR allows to use ConsoleKit2 in LXQt.

**Comment by paulolieuthier** [comment]
@pierre-labastie thanks for your help. I know all that, the problem with the PR is that the original ConsoleKit will no longer work, even for shutdown/reboot.

**Comment by paulolieuthier** [comment]
This will be fixes before next release, I hope.

**Comment by pierre-labastie** [comment]
@paulolieuthier Sorry if I told you things you already knew. Actually, I understand I did not think enough: it may happen that people would want LXQt on old distros, which do not have ConsoleKit2 nor Logind. So it means that we should use the old API for Shutdown/Reboot (which is still present in ConsoleKit2), and the new API for Suspend/hibernate. I think I can make a patch for that (but I can test it only with ConsoleKit2). Should I make the patch against the consolekit branch or master?

**Comment by paulolieuthier** [comment]
@pierre-labastie I didn't want to sound harsh, sorry. And I actually don't know to what extent is the old ConsoleKit still used. If almost nobody is using it, I see no problem in deprecating support for it and moving focus to ConsoleKit2 only.

Anyway, the patch you suggested was already done in the consolekit branch, wasn't it? Could you test it? If it doesn't work for you and you still want to contribute it, the master branch is what you should target.

**Comment by paulolieuthier** [comment]
After more thought (and some chatting with @agaida) I think there is reason why we should support the old ConsoleKit. It's no longer been maintained for some time already, LXQt's dependencies already suggest the need for distros with recent packages on repos and we simply don't have the manpower to support multiple backends (besides Systemd *and* ConsoleKit2, I mean).

That way, I think we should delete my branch and merge @ophuls's PR. @agaida, @luis-pereira, @palinek what do you think?

**Comment by pierre-labastie** [comment]
Hmm. I really feel sorry because I've read this thread to superficially, and had not understood that the code in the consolekit branch was working. I believed @ophuls's PR was needed to fix it. I should have looked at the code earlier...
Anyway, at least my contribution has motivated some "more thought".

**Comment by paulolieuthier** [comment]
>  Anyway, at least my contribution has motivated some "more thought".

Definitely. Don't be sorry, I'm glad you stepped in. Any help is appreciated! I welcome you [next release's milestone issues](https://github.com/lxde/lxqt/milestones/0.11).

**Comment by agaida** [comment]
if it don't break systemd, merge it

**Comment by palinek** [comment]
> That way, I think we should delete my branch and merge @ophuls's PR. @agaida, @luis-pereira, @palinek what do you think?

Seems like you've settled this already :)

**Comment by paulolieuthier** [comment]
Opinions are still relevant.
