### ISSUE TITLE
Use Starter Icons as Taskbar icons

### ISSUE THREAD

**Issue by sixsixfive** [lxde/lxqt#943]
running the same applications(trojita, qmmp, qt-desgner, qt-linguist & kodi) in plasma and lxqt 

![kde](https://cloud.githubusercontent.com/assets/3780774/12559174/b9aa88d4-c393-11e5-8bdc-5e56958ae663.png)

as you can see on the screenshot if icon only is set in taskbar settings it can get very confusing to find the right application because its using different icons than in the menu/*.desktop files.

**Comment by pmattern** [comment]
In your screenshot *LXQt* is using the very same icons in panel's `plugin-taskbar` which are normally used in plugin-mainmenu. Same thing trying to reproduce your findings in a VM here.
Isn't it rathter *KDE* that's using different stuff? Am I missing something else?

**Comment by sixsixfive** [comment]
>which are normally used in plugin-mainmenu. 

exactly its using the default icons but not the icons from the icon theme

here my menu which uses the icons from the icon theme:

![menu](https://cloud.githubusercontent.com/assets/3780774/12560784/d4c00e4c-c39c-11e5-965b-f7cc9ddb4c52.png)

**Comment by tsujan** [comment]
This is a valid report to me. LXQT should always use icons from the user icon theme and only if nonexistent, fallback ones.

**Comment by palinek** [comment]
We get the icon from the [KWindowSystem](http://api.kde.org/frameworks-api/frameworks5-apidocs/kwindowsystem/html/classKWindowSystem.html) -> see [here](https://github.com/lxde/lxqt-panel/blob/master/plugin-taskbar/lxqttaskbar.cpp#L273).

... this finaly goes into:
```c++
QPixmap KWindowSystemPrivateX11::iconFromNetWinInfo(int width, int height, bool scale, int flags, NETWinInfo *info)
{
    QPixmap result;
    if (!info) {
        return result;
    }
    if (flags & KWindowSystem::NETWM) {
        NETIcon ni = info->icon(width, height);
        if (ni.data && ni.size.width > 0 && ni.size.height > 0) {
            QImage img((uchar *) ni.data, (int) ni.size.width, (int) ni.size.height, QImage::Format_ARGB32);
            if (scale && width > 0 && height > 0 && img.size() != QSize(width, height) && !img.isNull()) {
                img = img.scaled(width, height, Qt::IgnoreAspectRatio, Qt::SmoothTransformation);
            }  
            if (!img.isNull()) {
                result = QPixmap::fromImage(img);
            }
            return result;
        }
    }

    if (flags & KWindowSystem::WMHints) {
        xcb_pixmap_t p = info->icccmIconPixmap();
        xcb_pixmap_t p_mask = info->icccmIconPixmapMask();

        if (p != XCB_PIXMAP_NONE) {
            QPixmap pm = KXUtils::createPixmapFromHandle(info->xcbConnection(), p, p_mask);
            if (scale && width > 0 && height > 0 && !pm.isNull()
                    && (pm.width() != width || pm.height() != height)) {
                result = QPixmap::fromImage(pm.toImage().scaled(width, height, Qt::IgnoreAspectRatio, Qt::SmoothTransformation));
            } else { 
                result = pm;
            }
        }
    }

    // Since width can be any arbitrary size, but the icons cannot,
    // take the nearest value for best results (ignoring 22 pixel
    // icons as they don't exist for apps):
    int iconWidth;
    if (width < 24) {
        iconWidth = 16;
    } else if (width < 40) {
        iconWidth = 32;
    } else {
        iconWidth = 48;
    }

    if (flags & KWindowSystem::ClassHint) {
        // Try to load the icon from the classhint if the app didn't specify
        // its own:
        if (result.isNull()) {
            const QIcon icon = QIcon::fromTheme(QString::fromUtf8(info->windowClassClass()).toLower());
            const QPixmap pm = icon.isNull() ? QPixmap() : icon.pixmap(iconWidth, iconWidth);
            if (scale && !pm.isNull()) {
                result = QPixmap::fromImage(pm.toImage().scaled(width, height, Qt::IgnoreAspectRatio, Qt::SmoothTransformation));
            } else {
                result = pm;
            }
        }
    }

    if (flags & KWindowSystem::XApp) {
        // If the icon is still a null pixmap, load the icon for X applications
        // as a last resort:
        if (result.isNull()) {
            const QIcon icon = QIcon::fromTheme(QLatin1String("xorg"));
            const QPixmap pm = icon.isNull() ? QPixmap() : icon.pixmap(iconWidth, iconWidth);
            if (scale && !pm.isNull()) {
                result = QPixmap::fromImage(pm.toImage().scaled(width, height, Qt::IgnoreAspectRatio, Qt::SmoothTransformation));
            } else {
                result = pm;
            }
        }
    }
    return result;
}
```

...so the question here is: are we going to honor the priority of getting icon information as it is defined/implemented in `KwindowSystem` or do we want to override it by first trying to get icon from theme (based on *windowClass*)?

(I don't know the specification of showing the icon of application...)

@jleclanche, @tsujan, @paulolieuthier, @luis-pereira, @PCMan ?

**Comment by pmattern** [comment]
I didn't say the issue isn't valid but don't think it's that obvious to understand, in particular as the screenshots don't display a single icon in plugin-taskbar that's differing from its counterpart in plugin-menu.

Genuine icons like e. g. the ones of Firefox, Thunderbird or whatever go to icon theme `hicolor` anyway and hence there cannot be any confusion as there's a single icon only (aside from different sizes or file types which do not matter here).

The problem can affect icons like the ones defined by the Icon Naming Specification, though.
E. g. launch `lxqt-config-notificationd` - change the current icon theme by `lxqt-config-appearance` → icons in menu and plugin-taskbar are different.
But the icon in plugin-taskbar seems to be different until the application in question, here `lxqt-config-notificationd` is launched the next time which makes me wonder about the practical impact of the problem.

**Comment by palinek** [comment]
In the lxde/lxqt-panel#299 is a preview of what I've said in the above comment...

**Comment by tsujan** [comment]
@palinek 
I need some time. I'll start to study this part of LXQT tomorrow -- previously I'd never encountered any serious problem about it, hence my lack of knowledge. And, BTW, this problem isn't serious at all!

@pmattern 
I didn't mean that you meant it is invalid ;) I'm familiar with sixsixfive's style of bug reporting and feature requesting from Kvantum. He may not convey his mind clearly in English but, most of the time, his attention to minute details has been an invaluable asset to me.

**Comment by palinek** [comment]
Just to clarify this issue... Hereafter is the difference between current master and the lxde/lxqt-panel#299 with *Numix circle* icon theme -> which provides icons for many applications (the example applications: xterm, chromium, Qt Designer, Skrooge):
- current master
![screenshot](https://cloud.githubusercontent.com/assets/10990929/12574601/b59afbf8-c405-11e5-8d9e-801e9363d56e.png)

-  lxde/lxqt-panel#299 (the existing icon from theme is used)
![screenshot](https://cloud.githubusercontent.com/assets/10990929/12574568/4019dae8-c405-11e5-9002-5f3902c16283.png)

@pmattern is the point of this issue more straightforward now?

**Comment by tsujan** [comment]
@palinek
Yes! Your commit at lxde/lxqt-panel#299 works here. Now, Qt Creator and Qt Designer use the user theme. Logically, it should also work for the other apps sixsixfive mentioned.

**Comment by tsujan** [comment]
However, some apps, like SMPlayer and VLC, seem to still enforce their icons. @sixsixfive : Do they have the same behavior under KDE (I don't have KDE here)?

**Comment by tsujan** [comment]
Oh, SMPlayer and VLC are Qt4-based, so that behavior is expected.

**Comment by palinek** [comment]
> Oh, SMPlayer and VLC are Qt4-based, so that behavior is expected.

This shouldn't have nothing to do with Qt version or even a framework (or maybe yes... I don't know who is responsible for setting the windowClass for X). You can test the existence of icon based on the windowClass `xprop | egrep -i class`

**Comment by tsujan** [comment]
@palinek
Under LXQT, no Qt4 app can use the user theme in its GUI either. I expected that since LXQT doesn't support Qt4. For example, GUI icons of Qt4-Designer are all Qt4 icons and not the user ones.

**Comment by tsujan** [comment]
All in all, I think your commit is the best that can be done, although I can't be sure.

**Comment by palinek** [comment]
> All in all, I think your commit is the best that can be done, although I can't be sure.

Let's wait also for others, what they think.

But there is one drawback in current lxde/lxqt-panel#299: if the icon from theme is used for application in taskbar, then user changes the icon theme and in the new theme there is no icon for the application => no icon will be shown until application restart or panel's "heavy reconfiguration"...

**Comment by tsujan** [comment]
> But there is one drawback in current lxde/lxqt-panel#299 ...

Then, please try to fix that too -- I'm still a newbie in Panel's code.

**Comment by palinek** [comment]
> Then, please try to fix that too -- I'm still a newbie in Panel's code.

Tried that in lxde/lxqt-panel@9866027. Please, test.

**Comment by tsujan** [comment]
> Tried that in lxde/lxqt-panel@9866027. Please, test.

Perfect! It works. And you proved that I was wrong: now VLC and SMPlayer pick their taskbar icons from the user theme too.

**Comment by palinek** [comment]
> The problem can affect icons like the ones defined by the Icon Naming Specification, though.
E. g. launch lxqt-config-notificationd - change the current icon theme by lxqt-config-appearance → icons in plugin-taskbar and plugin-menu are different.

I tend to say that this is a Qt bug. The icon for the window is set by [QWidget::setWindowIcon](http://doc.qt.io/qt-5/qwidget.html#windowIcon-prop). So the provided `QIcon` object (picture based on theme) and `QWidget` should re-set the correct image to X whenever the theme is changed.

However Qt sets the application's WM_CLASS based on the application name and/or value of `-name` parameter and/or value of env variable `RESOURCE_NAME` ... so if we change the application name to `app.setApplicationName("preferences-desktop-theme");`, the icon will be correctly "refreshed" after theme change with the lxde/lxqt-panel#299.

**Comment by palinek** [comment]
I'm still not convinced that the icon derived from windowClass should override the image(s) provided by app to window system...

E.g. the pidgin's conversation window sets the icon/image as the buddy icon, with the lxde/lxqt-panel#299... the icon in task bar will be the one provided by the them for `pidgin` (if there is one).

**Comment by tsujan** [comment]
> E.g. the pidgin's conversation window sets...

Could you think of a situation where that would create a problem?

**Comment by tsujan** [comment]
I use Plank (dock) and it does the same thing, in its own way.

**Comment by palinek** [comment]
> Could you think of a situation where that would create a problem?

Nothing mentioned here should be considered as a bug/problem. It is all about the user experience/preference.

**Comment by tsujan** [comment]
It might be called a feature request but it would make no difference. User experience and a consistent look-n-feel are important for GUI apps.

**Comment by sixsixfive** [comment]
>Nothing mentioned here should be considered as a bug/problem.

LXQt allows to change the icon theme, but since it isn't/wasn't possible on an LXQt application So I would call it a bug

there exist also monochrome themes like awoken , or all those new iphone like blocky themes that use a completely different icon style than the default icons.

**Comment by palinek** [comment]
Now there is an option in taskbar configuration to use the icon based on WindowClass.

**Comment by stefonarch** [comment]
Nice, this option fixes also a "generic icon" issue that I had with zoiper and konversation in the taskbar, now their icons are correct, thanks!
