### ISSUE TITLE
[lxqt-panel] Regression: right-click on app icons keeps panel unhidden until mouse-over

### ISSUE THREAD

**Issue by jeremywh7** [lxde/lxqt#944]
I just noticed this panel autohide regression after updating to lxqt-panel-git 0.10.0.43.g216669b-1 (arch x64: previously on g3dc228d), and is similar to (part of) https://github.com/lxde/lxqt/issues/853.  From what I've checked so far, it only affects right-clicking window application icons in the Panel's 'Task Manager'.

**Comment by palinek** [comment]
@jeremywh7 please, confirm that this is fixed in master now...

**Comment by jeremywh7** [comment]
Fixed; everything looks good.  Thanks!
