### ISSUE TITLE
lxqt-panel shows too many items

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxde/lxqt#946]
When I startup Virtualbox I have many of the same items in the panel.
I would expect to see only two items (Win7 + Oracle VM Box), but instead I see this.

![2016-01-30-111356_3520x1200_scrot](https://cloud.githubusercontent.com/assets/6639859/12695086/02436afe-c743-11e5-985a-4c0c0d5deb5f.png)

**Comment by sixsixfive** [comment]
probably the same issue as https://github.com/lxde/lxqt/issues/937

**Comment by tsujan** [comment]
I can't reproduce this issue, even when I shut down a virtual machine and run another:

![vbox](https://cloud.githubusercontent.com/assets/981076/12696652/564ee2c6-c785-11e5-8ad5-332ea28cb1d7.png)

**Comment by ArthurBorsboom** [comment]
Maybe it is because I have multiple logical CPU's assigned to the VM?
Can you try that?

On 30 January 2016 at 16:43, tsujan <notifications@github.com> wrote:

> I can't reproduce this issue, even when I shut down a virtual machine and
> run another:
>
> [image: vbox]
> <https://cloud.githubusercontent.com/assets/981076/12696652/564ee2c6-c785-11e5-8ad5-332ea28cb1d7.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/946#issuecomment-177213750>.
>



-- 
Arthur Borsboom
Mob: +31629089953
Email: arthurborsboom@gmail.com
Skype: Arthur Borsboom, The Hague, The Netherlands

[image: View Arthur's LinkedIn profile]
<http://uk.linkedin.com/in/arthurborsboom>

**Comment by tsujan** [comment]
> Maybe it is because I have multiple logical CPU's assigned to the VM?

I don't think so. In the previous screenshot, the v-machine had 2 processors.
It may be related to the version of lxqt-panel. Mine is the latest git, compiled from the source.

**Comment by ArthurBorsboom** [comment]
My lxqt-panel is the latest git. However, i have a mix of lxqt v0.10
packages and latest git packages, for the benefit of previous issues with
lxqt-panel.

I will investigate a bit more, and report back if I notice another pattern.

**Comment by tsujan** [comment]
Good! Please also consider the version of kf5 libraries too. Here, it's 5.16.0.

**Comment by paulolieuthier** [comment]
@ArthurBorsboom which window manager?

**Comment by ArthurBorsboom** [comment]
I am using Arch with kf5 5.18 and openbox

The issue is reproducable and if it is helpful, I can provide a Teamviewer
session.

arthur@z97:~$ yaourt -Q | grep lxqt

local/liblxqt-git 0.10.0.12.g1b34ac9-1
local/liblxqt-mount 0.9.0-2
local/lximage-qt 0.4.0-1 (lxqt)
community/lxqt-about 0.10.0-4 (lxqt)
community/lxqt-common 0.10.0-2 (lxqt)
community/lxqt-config 0.10.0-3 (lxqt)
community/lxqt-globalkeys 0.10.0-3 (lxqt)
community/lxqt-notificationd 0.10.0-3 (lxqt)
community/lxqt-openssh-askpass 0.10.0-3 (lxqt)
local/lxqt-panel-git 0.10.0.45.g798b856-1
community/lxqt-policykit 0.10.0-3 (lxqt)
community/lxqt-powermanagement 0.10.0-3 (lxqt)
community/lxqt-qtplugin 0.10.0-3 (lxqt)
community/lxqt-runner 0.10.0-4 (lxqt)
community/lxqt-session 0.10.0-3 (lxqt)
community/openbox 3.6.1-2 (lxde lxqt)
community/pcmanfm-qt 0.10.0-3 (lxqt)


On 31 January 2016 at 01:20, Paulo Lieuthier <notifications@github.com>
wrote:

> @ArthurBorsboom <https://github.com/ArthurBorsboom> which window manager?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/946#issuecomment-177343229>.
>



-- 
Arthur Borsboom
Mob: +31629089953
Email: arthurborsboom@gmail.com
Skype: Arthur Borsboom, The Hague, The Netherlands

[image: View Arthur's LinkedIn profile]
<http://uk.linkedin.com/in/arthurborsboom>

**Comment by palinek** [comment]
I believe, this is fixed... if not, please, reopen
