### ISSUE TITLE
Removable Media widget doesn't show any error message when removable media couldn't be ejected

### ISSUE THREAD

**Issue by birdie-github** [lxde/lxqt#95]
When I press the "Eject" button on a certain medium and it cannot be unmounted/ejected, the Removable Media widget doesn't show any error message. It's a bug.

Also if it cannot be ejected, `lsof /mount/point` or `fuser -vm /mount/point` (fuser is probably better) must be run to show what processes block the removal, in this form

```
The following processes prevent /mount/point removal

User  PID  Process
user1 123  /usr/bin/bash
user2 234  /usr/bin/mc
user3 345  /usr/bin/nano
```

**Comment by palinek** [comment]
Just tried something with this... with running my compiled lxqt-panel from cmdline (for my USB key pressing 'eject') I always get
```
UDisks2MountDevice::mDbus_error "Type of message, '()', does not match expected type '(a{sv})'"
```
this cames from liblxqt-mount/providers.cpp:
```c++
void UDiskMountDevice::dbusError(const QDBusError &err, const QDBusMessage &msg)
{
    qWarning() << "UdisksInfo::mDbus_error" << err.message();
    emit error(err.message());
}
```
It is probably caused by trying ejecting of device after unmount, because filesystem gets unmounted correctly.
When mounted filesystem is busy, I get:
```
UDisks2MountDevice::mDbus_error "Error unmounting /dev/sdb1: Command-line `umount  "/media/usb0"' exited with non-zero exit status 32: umount: /media/usb0: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
"
```

It seems that ``` res = setIsEjectable(mDbus->property("DriveIsMediaEjectable").toBool());``` is not 100% valid.

Partial solution of this issue can be to present dbus errors (of actions mount/unmount) in notification area. But we need to hide the "false eject error". We can connect "eject error" to another slot and silently discard it (as now are discarded all dbus errors).

**Comment by jleclanche** [comment]
Solid handles this properly, I was looking at it the other day.

**Comment by palinek** [comment]
@jleclanche I don't follow...

**Comment by palinek** [comment]
Oh.. you mean to drop using liblxqt-mount and use https://solid.kde.org/ ?

**Comment by jleclanche** [comment]
Yes, that's been the plan for a year or so now, but nobody picked it up yet.

**Comment by palinek** [comment]
Hi all.
I was fighting with all the building environment for KF5Solid (packages, cmake....never mind) on my machine and finaly got somewhere.
I've got something working in palinek/lxqt-panel@b332707. It's a realy raw piece of code and the functionality is not polished (or even everything working)... 
Now would realy appreciate review(s) if this is the right way to go.
@jleclanche can you, please, notify guys whose are reliable to review(or even test) the commit and give me some notes to that.

thanks

**Comment by jleclanche** [comment]
@palinek i will review it. Can you come on irc?

**Comment by palinek** [comment]
@jleclanche just commited... it seems working for me. Just got one problem with optical drive... when the new panel is running, after inserting DVD a error dialog is shown: ```Error mounting system-managed device /dev/sr0: Command-line `mount "/media/cdrom0"' exited with non-zero exit status 32: mount: no medium found on /dev/sr0``` and the disk is ejected. I was debugging it a little bit and realized that the panel (and new plugin-mount) is not ejecting the disk. I don't know where this error message dialog comes from.... 
Jerome, can you, please, test how is the "new" widget working for you?

**Comment by jleclanche** [comment]
@palinek I had fixed it on my fork: https://github.com/jleclanche/lxqt-panel/commits/mount_solid_migrate

Only tested on another partition on my local drive for now. Mounting works. Ejection is broken. Also, I looked at the code quickly, you're supposed to use signals such as teardownDone etc.

**Comment by jleclanche** [comment]
@palinek note that I'm going to be committing some header/whitespace cleanups so you'll need to do a bit of rebasing in a few.

**Comment by palinek** [comment]
@jleclanche I've already commited new changes that you probably missed... can you take a look on that?

**Comment by palinek** [comment]
Is the lxde/lxqt-panel#143 enough for this (just presenting that the error ocured) or do we realy want to further investigate the reason (like ```fuser``` or ```lsof```)?

**Comment by paulolieuthier** [comment]
I think just presenting the error is enough (at least for now).

**Comment by palinek** [comment]
So this one is ready to be closed...
