### ISSUE TITLE
lxqt-session (0.10.0-3) crashes directly on login and writes core dump

### ISSUE THREAD

**Issue by Schwefelsaeure** [lxde/lxqt#950]
After latest update on Arch Linux two days ago, `lxqt-session` crashes directly on login using `sddm` and writes a core dump.

Used compenents:

- Arch Linux with kernel 4.3.3-3
- sddm 0.13.0-2
- lxqt-session 0.10.0-3

Core dump:

```
Feb 03 22:16:59 idefix systemd-coredump[665]: Process 654 (lxqt-session) of user 1000 dumped core.
                                              
                                              Stack trace of thread 654:
                                              #0  0x00007ff5e093a5f8 raise (libc.so.6)
                                              #1  0x00007ff5e093ba7a abort (libc.so.6)
                                              #2  0x00007ff5e10c01e1 _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5)
                                              #3  0x00007ff5d7cf6064 _ZN14QXcbConnectionC1EP19QXcbNativeInterfacebjPKc (libQt5XcbQpa.so.5)
                                              #4  0x00007ff5d7cfb83d _ZN15QXcbIntegrationC1ERK11QStringListRiPPc (libQt5XcbQpa.so.5)
                                              #5  0x00007ff5e2d293ad n/a (/usr/lib/qt/plugins/platforms/libqxcb.so)
                                              #6  0x00007ff5e15e1e62 _ZN27QPlatformIntegrationFactory6createERK7QStringRK11QStringListRiPPcS2_ (libQt5Gui.so.5)
                                              #7  0x00007ff5e15ee052 _ZN22QGuiApplicationPrivate25createPlatformIntegrationEv (libQt5Gui.so.5)
                                              #8  0x00007ff5e15eef8d _ZN22QGuiApplicationPrivate21createEventDispatcherEv (libQt5Gui.so.5)
                                              #9  0x00007ff5e12b8126 _ZN16QCoreApplication4initEv (libQt5Core.so.5)
                                              #10 0x00007ff5e12b8196 _ZN16QCoreApplicationC1ER23QCoreApplicationPrivate (libQt5Core.so.5)
                                              #11 0x00007ff5e15f0d79 _ZN15QGuiApplicationC1ER22QGuiApplicationPrivate (libQt5Gui.so.5)
                                              #12 0x00007ff5e1ba951d _ZN12QApplicationC2ERiPPci (libQt5Widgets.so.5)
                                              #13 0x00007ff5e25a4917 _ZN4LXQt11ApplicationC1ERiPPc (liblxqt.so.0)
                                              #14 0x0000000000412f58 n/a (lxqt-session)
                                              #15 0x0000000000408bcf n/a (lxqt-session)
                                              #16 0x00007ff5e0927610 __libc_start_main (libc.so.6)
                                              #17 0x0000000000408c49 _start (lxqt-session)
```

After chrashing, `sddm` restarts and offers possibility to login again (using other desktop environment).

Other desktop environments like KDE Plasma work with same setup.

**Comment by pmattern** [comment]
Cannot reproduce your findings on Arch Linux x86_64 or i686 running in KVM/QEMU virtual machines.
Systems updated today, hence among other kernel 4.4.1, but this actually shouldn't matter.

So besides I can't really judge the stack trace you provided I tend to say this is a particular problem of your system.
Did you eventually do partial upgrades or install some of the packages from the AUR?
To further track this down you could eventually start a session on a new user profile and/or from a virtual terminal by running `startx`. Also, you could remove any device specific graphics driver and hence enforce the usage of the modesetting driver which is part of the X server as of 1.17.

**Comment by palinek** [comment]
This realy seems like some build problem. The application is crashing in initialization of the Qt core....

**Comment by Schwefelsaeure** [comment]
Thanks for pointing me in the right direction. :) It seems to be a `sddm` problem when theme `breeze` is used (see [Arch Linux Forum](https://bbs.archlinux.org/viewtopic.php?id=207705)).

As workaround, I use `maui` (default) theme for `sddm` and it works now. Sorry for blaming `lxqt-session`, but the stack trace put me in the wrong direction.
