### ISSUE TITLE
lxqt-runner: random segfaults on startup with already running instances

### ISSUE THREAD

**Issue by npmiller** [lxde/lxqt#951]
I've been having some segfaults happening fairly regularly when running the `lxqt-runner` with an lxqt runner instance already running.

It still has the expected behaviour so it's not too bad but I think it's still a problem.

So I've been looking into `LXQtSingleApplication` and improved a few things that might have helped:

* Cleanup the adaptor: https://github.com/npmiller/liblxqt/commit/980bfdd7ee87bd783f91bf9616b3cc3b2c24c252
* Use a blocking dbus call: https://github.com/npmiller/liblxqt/commit/7cda1afee4e857ca72229c96d096660bd70da930

But even with that, I'm still having segfaults, ultimately I think it's probably a bad idea to call `::exit(0);` from inside a constructor, and indeed, a little logging revealed that the segfault happens there.

Unfortunately, I don't see a good way to get rid of the `::exit(0);` while maintaining the exact same interface.

**Comment by palinek** [comment]
@npmiller see lxde/liblxqt#81..

**Comment by npmiller** [comment]
Nice, that fixes the segfault issue.
