### ISSUE TITLE
Please release libfm-qt

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#952]
It will make distribution maintainers happy if the latest release of pcmanfm-qt depend on a already released library. 
@PCMan

**Comment by PCMan** [comment]
Yes, time to make a new release. There are still some issues but they are not blockers.
@jleclanche let's do it?

**Comment by agaida** [comment]
@PCMan: not a new release - the first one. At least please tag a pre-release or beta. Making packages for debian from never released nor tagged sources is not so funny. Dito for snapshots. Thanks.

**Comment by PCMan** [comment]
@agaida It's almost ready for a new stable release (not pre-release). Previously I'd like to merge the remaining PRs first, but I do not have enough time for that. Maybe we should make the initial release first. Thank you. I'll do that this week (tag and tarball release).

**Comment by agaida** [comment]
Cool, Thanks.
