### ISSUE TITLE
lxqt-config-session doesn't read "Path" in desktop files for autostart

### ISSUE THREAD

**Issue by goetzc** [lxde/lxqt#954]
It seems to be ignored.

**Comment by palinek** [comment]
Did you try the latest libqtxdg from git? This [commit](https://github.com/lxde/libqtxdg/commit/f87f2089c4e99a54701022a6e956101145f7bd3e) should fix that...

**Comment by goetzc** [comment]
Oh, I'm using the latest release version.
 I guess it should work, and will test it, until that, I'll close this.
