### ISSUE TITLE
Panel freeze if I change the Qt theme

### ISSUE THREAD

**Issue by YamashitaRen** [lxde/lxqt#955]
Built master ~2 days ago.
If I change the Qt Style, the panel will freeze (I think I tried Breeze and Oxygen).
If I restart the session after the change, the panel will not appear anymore (and use all the cpu).
Latest release of lxqt-panel doesn't have this bug.

**Comment by palinek** [comment]
@YamashitaRen can you, please, check if lxde/lxqt-panel#302 makes it better on your side?

**Comment by YamashitaRen** [comment]
Good ! It works here :)
