### ISSUE TITLE
Building from source creates unusable .desktop file when grep 2.23 is installed.

### ISSUE THREAD

**Issue by styrsven** [lxde/lxqt#957]
When grep 2.22 is installed the .desktop files are created correctly.
This has been discovered on a gentoo system, and found in at least
lxqt-base/lxqt-common-0.10.0
lxqt-base/lxqt-panel-0.10.0
x11-misc/pcmanfm-qt.0.10.0
x11-misc/obconf-qt-0.9.0_p20150729
lxqt-base/lxqt-session-0.10.0
lxqt-base/lxqt-config-0.10.0
lxqt-base/lxqt-powermanagement-0.10.0
lxqt-base/lxqt-notificationd-0.10.0
lxqt-base/lxqt-globalkeys-0.10.0
lxqt-base/lxqt-admin-0.10.0
lxqt-base/lxqt-about-0.10.0

I've attached samples showing bad (with grep 2.23) and good (with grep 2.22)

[lxqt-desktop.desktop.bad.txt](https://github.com/lxde/lxqt/files/127562/lxqt-desktop.desktop.bad.txt)
[lxqt-desktop.desktop.good.txt](https://github.com/lxde/lxqt/files/127561/lxqt-desktop.desktop.good.txt)

**Comment by palinek** [comment]
@styrsven please, confirm that the lxde/liblxqt@082321a fixes this issue on your side.

**Comment by styrsven** [comment]
Thanks, this fixed the issue for everything that depends on liblxqt

**Comment by rapgro** [comment]
:+1: We need and use this patch in Fedora, too.

**Comment by styrsven** [comment]
Just remember there are separate copies of the file in compton.conf, libfm-qt, lximage-qt, obconf-qt and pcmanfm-qt. They need also to be updated.

**Comment by palinek** [comment]
@jleclanche @PCMan @luis-pereira @paulolieuthier @tsujan 
Should I update all the components to use the *translate\** from `liblxqt` in build time?

**Comment by paulolieuthier** [comment]
Only lximage-qt. The others should keep lxqt-independent, AFAIK.

**Comment by palinek** [comment]
> Only lximage-qt. The others should keep lxqt-independent, AFAIK.

And the reasoning?

**Comment by paulolieuthier** [comment]
Alright, I'm OK with build-dependency.

**Comment by pmattern** [comment]
Just in case someone stumbles upon this issue via searches or so:
The problem gets manifest only when some of (all?) the various environment variables `LC_*` are set to C. So an easy workaround is setting an arbitrary UTF-8 locale system-wide or as value of `LC_ALL` when invoking `cmake` and `make`.

**Comment by palinek** [comment]
Why is this still open?

**Comment by agaida** [comment]
@palinek - i guess because of the build dependency thing - we should talk about after the release
