### ISSUE TITLE
dialogue "Configure Panel": widget configuration dysfunctional

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#959]
The configuration of plugins (widgets) from panel's dialogue "Configure Panel" - Widgets (left pane) is dysfunctional in recent VCS code.

If a plugin in the main pane in the middle gets selected by single mouse click and one of the buttons at the right corresponding to actions like move or open the plugin's configuration dialogue gets clicked most of the time just nothing happens.
Sometimes those actions are applied to a plugin other than the selected one but so far I failed to figure out when exactly this takes place.
Moving or opening the configuration dialogue still works from a running plugin's context menu (except [plugin-volume](https://github.com/lxde/lxqt/issues/960)).

Arch Linux x86_64 or i686, yesterday's checkout of all LXQt components, in particular lxqt-panel lxde/lxqt-panel@43bdf15.

**Comment by palinek** [comment]
working on this...

**Comment by palinek** [comment]
Done... @pmattern, please, test the lxde/lxqt-panel#305

**Comment by pmattern** [comment]
@palinek 
Problem is fixed in lxde/lxqt-panel@223a913.
