### ISSUE TITLE
plugin-volume: attempts to configure from context menu trigger panel crash

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#960]
Attempts to launch the configuration dialogue of plugin-volume by selecting `Configure "Volume control"` from the plugin's context menu make the panel crash and dump core.

Figuring out whether  the dialogue can eventually be launched via panel's dialogue "Configure Panel" - Widgets (left pane) failed due to #959. The problem seems to be different from #958 as it cannot be seen with lxqt-panel release 0.10.0
A stack trace as found in systemd journal is at https://gist.github.com/pmattern/0d398552ec815e702898, a backtrace after importing the core dump to GDB is about 60k lines so I thought it's better when everyone interested creates it locally, in particular as the problem is 100% reproducible.

Arch Linux x86_64 or i686, yesterday's checkout of all LXQt components, in particular lxqt-panel lxde/lxqt-panel@43bdf15.

**Comment by palinek** [comment]
@pmattern please, try the lxde/lxqt-panel#304..

**Comment by pmattern** [comment]
@palinek 
Problem is fixed in lxde/lxqt-panel@0931c85.

**Comment by palinek** [comment]
ok... merging

**Comment by palinek** [comment]
thanks for testing
