### ISSUE TITLE
http://lxqt.org - please remove siduction ...

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#961]
as we don't provide any packages any longer.

Please add debian instead, the whole LXQt is in debian unstable/testing now.
Currently we work on a snapshot repo with packages close to the current git.

**Comment by palinek** [comment]
> Currently we work on a snapshot repo with packages close to the current git.

Should you need some man power, I'll be glad to help you.

**Comment by palinek** [comment]
Done in lxde/lxde.github.io@5bff2a1

**Comment by agaida** [comment]
@palinek: yes, we will need man power later, any help will be appreciated.
