### ISSUE TITLE
Plugin showdesktop

### ISSUE THREAD

**Issue by OhDaeto** [lxde/lxqt#962]
![_2016-02-23_14-33-49](https://cloud.githubusercontent.com/assets/14937307/13250356/9d1a43cc-da3a-11e5-8afc-43fc44a68e8d.png)
Please drag the area for plugin-showdesktop at 1 pixel up.
I want to like Xfce from the first time to hit the button to minimize windows.

**Comment by palinek** [comment]
Sorry, but I don't follow this message. What is the problem or what do you wish to achieve?

**Comment by xDShot** [comment]
There is a 1-pixel depth gap between "show desktop" button and the top side of screen edge. So, if you drag the mouse at the top, you can't press the button, and so you have to move your cursor a bit lower to hit it. OP just meant that there were no same issues with Xfce as it worked perfectly for him :)

**Comment by intialonso** [comment]
So is the clickable area not working as expected? In which themes have you seen this isuue?

**Comment by OhDaeto** [comment]
In all themes.

**Comment by OhDaeto** [comment]
Also, the clock display is clicked on the last pixel.

**Comment by intialonso** [comment]
This seems the same as #374 I will close this one as duplicate. Some things have changed since then, so I will review the theming to see if this can be fixed now.

**Comment by palinek** [comment]
@OhDaeto what version of LXQt are you using?
A time ago I made this [commit](https://github.com/lxde/lxqt-common/commit/d0e0edaa486fcec13bab67eeaade6810eea8fe2f), which I believe is fixing this partially. But if you have configured the icon size smaller than the height of the panel, the widgets are centered -> leaving a gap that you are reporting.

**Comment by OhDaeto** [comment]
@palinek This problem manifests itself when the panel is at the top

**Comment by palinek** [comment]
how is your panel configured(panel size, icon size, # of rows)?

**Comment by OhDaeto** [comment]
![screenshot_2016-02-28_21-13-12](https://cloud.githubusercontent.com/assets/14937307/13380959/358ad6c0-de60-11e5-8a21-cbcedf6fd390.png)

**Comment by palinek** [comment]
@OhDaeto did you read my previous post?
> But if you have configured the icon size smaller than the height of the panel, the widgets are centered -> leaving a gap that you are reporting.

Based on the screenshot... it is exactly your situation.

**Comment by OhDaeto** [comment]
![_2016-02-28_21-29-21](https://cloud.githubusercontent.com/assets/14937307/13381045/74c68a3a-de62-11e5-9696-0648bef4f16f.png)
The problem persists

**Comment by palinek** [comment]
confirmed

**Comment by palinek** [comment]
@OhDaeto can you check the lxde/lxqt-panel#306 ?

**Comment by OhDaeto** [comment]
I compile minutes ago and now everything works fine! Thank you!

**Comment by palinek** [comment]
@OhDaeto thanks... let's wait for some other review before merging the lxde/lxqt-panel#306 PR
