### ISSUE TITLE
Upgrade to qt5 v 5.5.1 seems to have broken a dependency

### ISSUE THREAD

**Issue by rogerfranz** [lxde/lxqt#963]
Not sure this is where this belongs, but an upgrade today removed all of lxqt except lxqt-common because of broken dependencies. I think the problem is qtbase-abi-5-4-2, formerly supplied by libqt5core5a, but which now supplies qtbase-abi-5-5-1. I'm not really good at tracking these things down, though, and I've been awake far too long. But I'm unhappy to lose all of lxqt to a dependency issue and I'm hoping someone has some ideas.

Running Ubuntu Wily (15.10).

**Comment by palinek** [comment]
That's a packaging downstream problem.

@gilir, can you give @rogerfranz further information? thanks

**Comment by pmattern** [comment]
@rogerfranz 
You may want to tell as which way you installed LXQt because right now [two different PPAs](https://github.com/lxde/lxqt/wiki) are available.

**Comment by rogerfranz** [comment]
okay. I'm using:

deb http://ppa.launchpad.net/lubuntu-dev/lubuntu-daily/ubuntu wily main

Installed via Synaptic.

**Comment by gilir** [comment]
I started a rebuild of most lxqt components to rebuild again the new qt package, just in case. But It's weird to have a qt change on a stable release (15.10 is stable since november).

**Comment by rogerfranz** [comment]
Here's why I think it's qtbase-abi -- apt-get output, modified (... inserted for removed lines) for brevity:

```
root@firefly:~# apt-get install lxqt-about
...
The following packages have unmet dependencies:
 lxqt-about : Depends: liblxqt0 (>= 0.9.0+20150911) but it is not going to be installed
              Depends: libqt5xdg1 (>= 1.0.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@firefly:~# apt-get install liblxqt0
...
The following packages have unmet dependencies:
 liblxqt0 : Depends: libqt5xdg1 (>= 1.0.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@firefly:~# apt-get install libqt5xdg1
...
The following packages have unmet dependencies:
 libqt5xdg1 : Depends: qtbase-abi-5-4-2
E: Unable to correct problems, you have held broken packages.
root@firefly:~# apt-get install qtbase-abi-5-4-2
...
Package qtbase-abi-5-4-2 is a virtual package provided by:
  libqt5core5a 5.4.2+dfsg-2ubuntu9 [Not candidate version]

E: Package 'qtbase-abi-5-4-2' has no installation candidate
root@firefly:~# 

```
Not sure what to do next. I hesitate to downgrade (there were quite some few files upgraded to 5.5.1).

**Comment by tsujan** [comment]
Not sure if this could be of any help but I also saw a similar issue when Qt5-5.5.1 came to Debian months ago. Upgrading of Qt5 *incompletely* (with some Qt5 deb packages having the older version -- especially libqt5x11extras5) could cause serious problems. The Qt5 maintainer should make new Qt5 deb packages in such a way that all of them are upgraded together.

**Comment by rogerfranz** [comment]
I note that Debian has libqt5xdg1 depending on the correct virtual, https://packages.debian.org/sid/libqt5xdg1

Not sure I should go get it from there, because I've had issues mixing Ubuntu distro and Debian distro packages.

**Comment by gilir** [comment]
Actually, 15.10 has 5.4, not 5.5 : http://packages.ubuntu.com/fr/wily/qt5-default
Please check the origin of your 5.5 packages and downgrade them, you should not have them

**Comment by agaida** [comment]
@rogerfranz: the abi package is a virtual package, provided by qtbase afaik - so one don't want depend on it if one has Qt in a former version installed. And yes - the packages work great in sid and testing - but are not binary compatible with ubuntu 15.10

**Comment by intialonso** [comment]
I faced this issue but I was running the Kubuntu ppa, so the problem as
Gilir says come from foreign upgrades.

**Comment by agaida** [comment]
beside of that - i would hereby recommend to leave 15.10 alone and use xenial - ok, might not be the best choice for beginners, but for advanced users.

**Comment by gilir** [comment]
Thanks for the feedback, closing as it's the Kubuntu PPA that seems to cause the conflict.
