### ISSUE TITLE
Saving monitor settings

### ISSUE THREAD

**Issue by nboughton** [lxde/lxqt#964]
Distribution: Arch Linux
LXQT version: 0.10.0

Saving monitor settings (for a multimonitor set up) from the config GUI creates ~/.config/LXQt/lxqt-config-monitor.conf whereas all other settings are stored in ~/.config/lxqt as such the LXQt folder is never read and so monitor settings appear to never be saved even though they are.

Reproduce steps:
Attach secondary monitor
Go to LXQT menu -> Preferences -> LXQT Settings -> Monitor Settings
Arrange monitors in GUI
Click save
Log out and log in
Notice that the session seems to have forgotten your monitor settings
Go to ~/.config
See new folder LXQt that only contains lxqt-config-monitor.conf

**Comment by limusch** [comment]
To solve this issue, I did add an entry to LXQt Autostart in Session Settings
which runs the command:

`lxqt-config-monitor -l`

This seems to load the monitor configuration.

**Comment by pmattern** [comment]
These are valid findings which have already been addressed in #923, though.

May I ask you to add your thoughts to that issue so that we can avoid clutter on the issue tracker?
