### ISSUE TITLE
autostart files: Qlipper and XScreenSaver daemon should probably be handled as LXQt Module as well

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#966]
In files `/etc/xdg/autostart/*.desktop` which belong to lxqt-common and are used to launch several daemon-like processes all corresponding binaries are treated as LXQt Module (`X-LXQt-Module=true`) except Qlipper and XScreenSaver daemon. The latter seems questionable to me.

In practice, that missing key `X-LXQt-Module=true` excludes these programs from list "LXQt Modules" in `lxqt-config-session` - Basic Settings. This in turn makes it much harder for users to disable the auto start of these tools at the beginning of a session.
Of course it could be argued that the two components don't belong to LXQt. But this applies to Compton as well which is nevertheless treated as LXQt Module.

So I think it would be best to simply make those two components an "LXQt Module", too. If it should turn out that this doesn't make sense I think an other means should be found to allow users for toggling their auto start in a convenient way.

**Comment by Vladimir-csp** [comment]
IMHO, it's better to merge "LXQt Modules" into Autostart. They are handled by same mechanism, diffenences are only cosmetic. Accentuate them by sorting up in the list or something.

Or/and present autostart as a table where "Comment" entry field also visible.

Lack of Start/Stop buttons for generic autostarted apps could also be addressed.

**Comment by pmattern** [comment]
The difference is not a cosmetic one only.
Applications handled according to the Autostart Specification are launched once when the session starts and then forgotten. The so-called LXQt Modules are monitored all over the session and re-launched if they exit before the session ends, e. g. due to a crash.
Both approaches are reasonable with regards to the respective applications and should be kept which means merging isn't an option.

**Comment by Vladimir-csp** [comment]
Does monitoring need any special feedback from application being monitored? If not, then anything can be watched and restarted by adding `X-LXQt-Module=true`. If so, then again, why separate these lists on different sections of lxqt-config-session instead of adding "watch and restart" checkbox for applications.

**Comment by paulolieuthier** [comment]
> Does monitoring need any special feedback from application being monitored?

No. Nevertheless, LXQt modules are not the usual apps you would want to be autostarted. They are essential to the DE and IMO should be treated differently.

**Comment by paulolieuthier** [comment]
@palinek 

>This in turn makes it much harder for users to disable the auto start of these tools at the beginning of a session.

How is that so?

**Comment by pmattern** [comment]
@paulolieuthier 
(Assuming it's me you wanted to address due to the quote.)
When opening this issue I wasn't aware that both applications are listed in section "Autostart" of `lxqt-config-session`. Looking back I have no clue why I missed that.
So the main concern, being able to toggle the auto start in a convenient way, is in fact a non issue.
Still files `/etc/xdg/autostart/lxqt-{qlipper,xscreensaver-autostart}.desktop` are the only ones provided by lxqt-common missing `X-LXQt-Module=true` besides the applications launched by these files are pretty similar. So adding the key would actually be a bit more coherent and maybe make it more intuitive to deal with those files. But that aside this issue can simply get closed.

**Comment by paulolieuthier** [comment]
I don't think they should be LXQt modules, as they are third party apps, but I wouln't bother if they were either. Let's close this (discussion can, of course, continue).

**Comment by pmattern** [comment]
Agree.

While my concern that toggling the autostart via a GUI isn't possible turned out to be pointless I was thinking about the fact that only LXQt Modules get relaunched upon failure in the meantime.
Actually this could be a reason to make those two tools an LXQt Module in the long run. But on the other hand relaunching may mask issues causing crashes which sure isn't desirable at the current status the components involved.
So indeed nothing to change right now, any further discussion can take place here or elsewhere if needed.
