### ISSUE TITLE
CMake minimum version to 3.1.3 ?

### ISSUE THREAD

**Issue by gilir** [lxde/lxqt#970]
Some components (lxqt-runner, lxqt-session for example) started to fail to build on some old Ubuntu versions.
See examples : 
- Build OK : https://launchpadlibrarian.net/245936047/buildlog_ubuntu-wily-i386.lxqt-runner_0.10.0+201603042347~ubuntu15.10.1_BUILDING.txt.gz
- Build fail : https://launchpadlibrarian.net/245935749/buildlog_ubuntu-vivid-i386.lxqt-runner_0.10.0+201603042347~ubuntu15.04.1_BUILDING.txt.gz

Tracking the differences between the environment, I found that the ones failing was the ones with 3.0.2 cmake installed (instead of 3.2.2 for the others).

Looking more on the build log, I found some missing logs on the failed ones : 
-- Detecting C compile features
-- Detecting C compile features - done
and
-- Detecting CXX compile features
-- Detecting CXX compile features - done

I'm not an expert of cmake, a wild guessing and a bit of google make me think that the problem is some cmake compile features which are involved (like this https://cmake.org/cmake/help/v3.1/manual/cmake-compile-features.7.html) which are 3.1.3 features.

I'll be happy to provide more information if its' necessary.

**Comment by agaida** [comment]
@gilir: there is nothing wrong with cmake i guess - reading the vivid log i found these lines after the capabilities check:
```
CMake Error at /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:345 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:399 (_pkg_check_modules_internal)
  CMakeLists.txt:41 (pkg_check_modules)
```
CMakeLists.txt:41ff. is
```
37: if (USE_MENU_CACHE)
38:     # optionally use libmenu-cache from lxde to generate the application menu
39:     find_package(PkgConfig REQUIRED QUIET)
40: 
41:     pkg_check_modules(MENU_CACHE REQUIRED QUIET
42:         libmenu-cache>=0.3.3
43:     )
44: endif()
```
so i guess you run into a problem with libmenu-cache. I will check this in a vivid installation.

**Comment by agaida** [comment]
@gilir: The good news is - i got the builds working, the not so good news is - i don't know why. The fault is really that the pkg_check_modules fails - it is not visible, we should remove the QUIET. After some testing the module is found on my test system. Have to setup an vivid again and find the reason for that behaviour.

**Comment by gilir** [comment]
@agaida  Thanks for the test, and yes the bug seems to be in menu-cache. I updated the version on the PPA, and the behavior is now more understandable for me :-)

**Comment by agaida** [comment]
@gilir: right now i really don't understand it - libmenu-cache-dev contain the .pc file - this should be sufficient. There must be at least a missed dependency - but hey - glad it works for you.

**Comment by agaida** [comment]
ok, found it - there is a dependency missed - and i don't know the reason, maybe it was added later in the process and is not there for earlier versions. 

Adding libglib2.0-dev to the build-dependencies should solve the bug for lxqt-runner, but i guees the dependency should be introduced in another package like libfm-gtk or menu-cache. We will never know until we analyze it :) - beware of the sound, unfortunally vokoscreen has monitored audacious 
http://bugs.siduction.org/attachments/download/244/vokoscreen-2016-03-06_18-26-54.avi

**Comment by agaida** [comment]
@gilir - so you should port the dependency of the dev package too
http://git.lxde.org/gitweb/?p=debian/menu-cache.git;a=commitdiff;h=c00089c5ddf5995c97f14246c3beb4e316900709

**Comment by gilir** [comment]
Yes the libglib-dev depends is an old bug on the packaging, but it was fixed some time ago, and I was hit by it several times :-)

**Comment by agaida** [comment]
:)
