### ISSUE TITLE
lxqt-config-brightness-settings: Shouldn't we drop superfluous suffix "-settings"?

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#975]
The purpose of each and every binary `lxqt-config-*` is tweaking settings so suffix "-settings" is basically a tautology. Also, it's inconsistent with the naming of all those other binaries.

So shouldn't we just drop that suffix? IMO this would be more intuitive somehow.

**Comment by palinek** [comment]
+1

**Comment by agaida** [comment]
+1

**Comment by paulolieuthier** [comment]
Sure.

**Comment by selairi** [comment]
Done.

**Comment by paulolieuthier** [comment]
lxde/lxqt-config@3a38f64def0d2d50d6836f231d874920a1193157.
