### ISSUE TITLE
GTK mouse cursor is set to default

### ISSUE THREAD

**Issue by neon12345** [lxde/lxqt#978]
When I start lxqt with kwin I can see that the cursor is set to the default big X when I use nm-applet in the lxqt-panel. 
When I start openbox without lxqt and then start lxqt-panel the theme is applied with the cursor.
The rest of the gtk theme is correct, only the cursor is somehow reset to default. Since this does not happen with openbox standalone I assume this is connected to lxqt.

**Comment by neon12345** [comment]
Some more details: When I use the chrome browser I have the selected cursor with some exceptions.

1. Using the right click context menu on a web page, the cursor is as expected.
2. Using the right click context menu on a tab, the cursor changes to the big X default until the mouse is moved over the context menu.
3. nm-applet shows the big X in the menu even when moving the mouse. 

Don't know if this is related to lxqt. I'm using stock debian and compiled lxqt from git.

**Comment by agaida** [comment]
Why does one do that? And how do you compile it?

**Comment by neon12345** [comment]
I don't think it's that easy because I use lxappearance. It does not crash for me and it fixes the problem. But as soon as I restart lxqt the cursor is broken again.

**Comment by neon12345** [comment]
I compile it as described, why not? So why exactly is this the expected behaviour?

**Comment by neon12345** [comment]
Adding "xsetroot -cursor_name left_ptr" to the startup fixes the problem. Since this does not happen with other wms I still assume there is something missing in the startup of lxqt.

**Comment by wbsgit** [comment]
I had the same issue running Archlinux. Putting
`xsetroot -cursor_name left_ptrxsetroot -cursor_name left_ptr`
to autostart fixes the issue.
