### ISSUE TITLE
[plugin-clock] calendar unreadable

### ISSUE THREAD

**Issue by Esclapion** [lxde/lxqt#982]
If the font of the panel is light (#ffffff], it's impossible to read the last month. If we darken the fonts of the panel, it works, but all others things are difficult to read.

How can I change only the value of the calendar background, please ?

A sample : 

http://i.imgur.com/FIaJkPp.jpg

**Comment by intialonso** [comment]
Hi @Esclapion is that problem present in the default themes? Which theme?

If you want to customize the calendar I have bad news, the QTCalendarWIdget is very limited in what can be customized. 

You can try this:

`QCalendarWidget QWidget{ 
   background-color: %%BASECOLOR%%; 
   alternate-background-color: %%HIGHLIGHTDISABLECOLOR%%;
   color: %%TEXTCOLOR%%;
}`

**Comment by Esclapion** [comment]
Hi @intialonso, i don' use the default theme. I have this problem since a long time, with various theme.

I'm not sure it's theme-dependent ? I do now a try with mediterraneannight and another, same problem, absolutely no change. The color depend of the panel font color, imho.

I use compiled packages, not source. Can I do your try anyway, and where ?

I find no qss related to this plugin ? Or it is under another name ?

**Comment by intialonso** [comment]
I cant reproduce this issue. Did you changed the panel font settings? It could be that.

The QSS is in the **panel.qss** file in /usr/share/lxqt/themes/THEME-NAME/
In that file there is a section for the Calendar.

**Comment by Esclapion** [comment]
I changed nothing, a.f.a.i.k.

http://www.auplod.com/u/dpaolu777cc.jpeg

I will do some tries un panel.qss.

**Comment by intialonso** [comment]
Ahh you are using "Custom styling" font and background color. There is your problem.

Those options are very simple, and the panel is a little more complex. If you want to cutomize your panel the right way, I suggest you to create a custom theme, and write your own QSS file,

Im marking this as invalid because the issue is the result of a user choice of font and background colors in the config dialog, and not a LXQT default.

**Comment by Esclapion** [comment]
Uncheking Custom styling, it works, thanks. But it means also than this styling causes problem, no ?

**Comment by intialonso** [comment]
Yeah, the user been able to set any color can produce problems (depending on his personal taste). Im not sure why that option was included, I dont think it was a good choice. Anyway, by default is unchecked, so it requiere a clear interaction and responsability from the user.
