### ISSUE TITLE
[lxqt-panel] Empty menu item

### ISSUE THREAD

**Issue by Esclapion** [lxde/lxqt#983]
I installed gtk3 (due to a dependency), and an empty item "Programming" appeared in the Menu.

It's not very important, but a blog complained about that.

A little digging, there are three tools in this section, gtk+ demo, icon browser, and widget factory. The three corresponding .desktop contain NoDisplay=true.

**Comment by luis-pereira** [comment]
@Esclapion If the .desktop files contain `NoDisplay=true` it's not a bug.
From the standard:
> NoDisplay means "this application exists, but don't display it in the menus". This can be useful to e.g. associate this application with MIME types, so that it gets launched from a file manager (or other apps), without having a menu entry for it (there are tons of good reasons for this, including e.g. the netscape -remote, or kfmclient openURL kind of stuff).

**Comment by jleclanche** [comment]
@luis-pereira we should not be displaying empty menus

**Comment by luis-pereira** [comment]
@jleclanche Sure. Did not notice that's lxqt-panel. Thought was in libqtxdg.
This is probably an menu-cache issue.

**Comment by luis-pereira** [comment]
@jleclanche It doesn't show up when using `XdgMenuWidget`

**Comment by Esclapion** [comment]
@luis-pereira : yes,i knew that, i was only digging to understand why this item is displayed.

**Comment by luis-pereira** [comment]
Everything points to menu-cache generation. Will dig a bit more.

**Comment by palinek** [comment]
This was already discussed in #65 also.

**Comment by luis-pereira** [comment]
@palinek Wasn't aware of #65. So this is just a duplicated.
@Esclapion Discussion is (or was) happening at #65

**Comment by Esclapion** [comment]
Thanks, i didn't read that. But nothing since December.
