### ISSUE TITLE
Usability issue: "Add panel" hides previous panel

### ISSUE THREAD

**Issue by RalfJung** [lxde/lxqt#988]
It can quickly happen that one accidentally clicks "Add Panel", e.g. when slightly missing an icon in the system tray (resulting in the wrong context menu being opened).
LXQt then creates the new panel *on top* of the previous panel, which is a UI disaster: When this happened to me for the first time, I actually thought that I had accidentally *deleted* the old panel, and started manually adding the widgets again. I only noticed that I had two panels on top of each other when I was unable to add a SysTray, with LXQt saying there can be only one SysTray.

The new panel should appear above the old one, or at least on a different edge of the screen, to avoid this issue.

**Comment by intialonso** [comment]
+1 +It has happened to me before.

**Comment by stefonarch** [comment]
+1 Happened to me too,   I had my underlaying panel increased so it was half cut away and I understood what has happened. Adding new ones on free edge of screen?

**Comment by palinek** [comment]
dup of #373
