### ISSUE TITLE
Keyboard layout is reset when unplugging and replugging keyboard

### ISSUE THREAD

**Issue by RalfJung** [lxde/lxqt#989]
Steps to reproduce:
* Configure a non-default keyboard layout (e.g., I prefer the "no dead keys" variant of the German keyboard)
* Unplug the keyboard (I am on a laptop, so the internal keyboard remains)
* Re-plug the keyboard

Actual behavior:
* The keyboard configuration is reset, keys are dead again

Expected behavior:
* The configuration should persist

I am unplugging keyboard at least twice a day when I move the laptop between desks, so this bug pretty much forces me to use the default keyboard configuration.

**Comment by palinek** [comment]
Please, check if this is the same as in #399

**Comment by RalfJung** [comment]
How would I check that? That issue says it has been fixed. I am running LXQt 0.10, so I think the fix should be included. I can confirm that running "lxqt-session" after plugging in the keyboard fixes the layout. However, it also starts a second panel and seems to re-run the autostart scripts, so I don't think that's a solution.

I should notice that if I open the keyboard layout configuration after the layout has been forgotten; that config, too, is reset to the default.

**Comment by palinek** [comment]
Do you see [this note](https://github.com/lxde/lxqt-session/blob/master/lxqt-session/src/sessionapplication.cpp#L100) in *~/.xsession-errors* (or the systemd journal)?

**Comment by RalfJung** [comment]
There is nothing in `.xsession-errors`.

**Comment by palinek** [comment]
How did you install/build the lxqt-session ?

**Comment by RalfJung** [comment]
I am using the Debian testing packages.

**Comment by palinek** [comment]
The "layout reappling" was dissabled in default build in [this commit](https://github.com/lxde/lxqt-session/commit/db818c25) ... however I don't believe it is a debian specific issue (it was originaly reported by Arch users)

@RalfJung I would be great if you could re-build the lxqt-session package with the  LIBUDEV_MONITOR enabled and test if it helps

@agaida please, consider enabling the LIBUDEV_MONITOR for lxqt-session package in debian

**Comment by RalfJung** [comment]
I patched the Debian package to explicitly set `-DLIBUDEV_MONITOR=ON`, that fixed the issue.

**Comment by agaida** [comment]
@RalfJung @palinek - we could for sure set this explicitly - or we could fix the logic behind. I'm in favour of the second option. :grin:

**Comment by RalfJung** [comment]
What is the logic supposed to be? Automatically detect presence of `libudev`?

In any case, until upstream releases a fixed version, it'd be nice to have a patch in Debian :)

**Comment by agaida** [comment]
yes - and come online :D

**Comment by palinek** [comment]
> or we could fix the logic behind

What logic do you want to fix? It's a 'feature' of X.org. If new input device is connected, the layout is reset to the global setting (that means /etc/keyboard in debian IIRC). (I can't search for it now)

Do you want to store the keyboard layout into system wide config? Or change the bahavoiur of X.org? Neither of those was the option in the time this issue was investigated, therefore we made thus workaround.

**Comment by agaida** [comment]
@palinek have a look @ CMakeLists.txt - imho the way to go is

find($foo)
if found then
   bar
else
  baz
end

Right now in CMakeLists there is if (...), which is never set - makes no sense imho.

**Comment by RalfJung** [comment]
@agaida @palinek I submitted a pull request which automates libudev detection <https://github.com/lxde/lxqt-session/pull/64>

**Comment by palinek** [comment]
That's wrong. It's not about checking if libudev can be found. The feature requires libudev and will fail correctly if not found. But the feature must be explicitly enabled in build time. That is what i've suggested... `cmake -DLIBUDEV_MONITOR=yes....` how @RalfJung said before.

**Comment by agaida** [comment]
erm - the CMakeList.txt will be parsed short before builds - and that should be enough. if this is not enough, a cmake override is still possible
