### ISSUE TITLE
Panel does not adapt to changed screen geometry

### ISSUE THREAD

**Issue by RalfJung** [lxde/lxqt#990]
Steps to reproduce:
* I have two screens, the laptop screen with 1366x768 and an external screen with 1920x1200.
* I use LightDM as display manager.
* After login, the screens are configured to their native resolutions, and both are at the same position in the screen layout. On the big screen, that looks like in the screenshot below. On the laptop screen, the panel is at the bottom and as wide as the screen. Considering that LXQt does not touch the screen layout when starting, it is hard to do anything reasonable, so this is fine.
* Now I disable the laptop screen with xrandr.

Actual behavior:
No change on the main screen, the panel stays where it was:
![screen png](https://cloud.githubusercontent.com/assets/330628/13906900/33e4d00e-eee2-11e5-903e-deb907adb0c7.jpg)

Expected behavior:
The panel should now move to the bottom.
Interesting enough, I can trigger it to move to the bottom by starting ScreenGrab.

To me it seems like LXQt does not think it needs to do anything, since the resolution and position of the big screen did not change. But that's a false assumption.

**Comment by RalfJung** [comment]
Potentially related: #906

**Comment by pmattern** [comment]
As well as #650 and #680.

**Comment by RalfJung** [comment]
#650 is not entirely fixed by my PR. If you have two overlapping screens, LXQt will still select one of them (the primary one, if one of them is primary) and put the panel at the bottom of that screen. This looks really ugly on the other screen.

I guess the alternative would be to put it at the bottom of the highest screen, and make it as wide as the widest screen. The it wouldn't look ugly on the larger screen any more; but there would be no panel visible on the smaller screen. Also, I am not entirely sure what is the best way to detect this -- for example, how should we handle a configuration of three screens where the first two are adjacent, and the third one "overlaps" both other screens?

**Comment by Vladimir-csp** [comment]
I tried to introduce some concepts of dealing with with this stuff via positional placement instead of numbering monitors, but it was rejected (#523)

**Comment by paulolieuthier** [comment]
Each panel has a configuration option to set where it is supposed to be. IMO, by default the panel must be in the primary screen.

**Comment by RalfJung** [comment]
I don't disagree. It doesn't look pretty, but it's hard to do better. IMHO the DM should leave X11 in a different state (mirrored) to better sync the screens; LXQt cannot do much.

**Comment by paulolieuthier** [comment]
@RalfJung when you disable the laptop screen, does the second screen get selected as primary?

**Comment by RalfJung** [comment]
In which sense? xrandr considers it "primary" (it's the only screen after all). And the panel moves to the bottom the way it should.

**Comment by RalfJung** [comment]
Actually, this issue has been fixed by merging #310.

**Comment by paulolieuthier** [comment]
I believe you mean lxqt/lxqt-panel#310. Anyway, I thought xrandr might not set the remaining screen as primary. Thanks for the fix.

**Comment by liweitianux** [comment]
Hi, I'm having this exact problem with Labwc (wayland compositor). Here is the screenshot:

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/31f8ebb3-ba4c-43cd-b053-6d3cedc31c4d" />

This happens when I switch from the laptop internal screen to a bigger external monitor, with the laptop screen disabled.

However, when I switch back from the external monitor to the laptop screen, this panel placement problem doesn't happen.

```
% lxqt-panel --version
lxqt-panel 2.3.2
liblxqt   2.3.0
Qt        6.10.2

% labwc --version
labwc 0.9.6 (+xwayland +nls +rsvg +libsfdo)

% cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux forky/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=forky
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by stefonarch** [comment]
It's kind of necroposting here, fast forward 10 years to Wayland ;)

Your monitors have different resolutions, true? 
How do you switch, using `kanshictl`?
It maybe well that the panel module should be restarted (from Session Settings or by cli/script which could be done in kanshi afaik too).
```
#!/bin/bash
qdbus6 org.lxqt.session /LXQtSession org.lxqt.session.stopModule lxqt-"panel".desktop;
sleep 1;
qdbus6 org.lxqt.session /LXQtSession org.lxqt.session.startModule lxqt-"panel".desktop;
```

**Comment by liweitianux** [comment]
> It's kind of necroposting here, fast forward 10 years to Wayland ;)

If it isn't for such a mixed-DPI multiple monitors setup, I'd just stick with Xfce4 on X11 :)

> Your monitors have different resolutions, true?

Yah, the laptop internal: 2240x1400, 14 inch, and the external is 3840x2160, 32 inch

> How do you switch, using `kanshictl`?

Oh, I didn't even know the `kanshictl` helper. I just plugged the HDMI/Type-C cable to my laptop and then manually executed `kanshi` to let it do the switch and then killed it.

Here is my config (switching from `laptop` to `office_1`):

```
output "eDP-1" {
    scale 1.5
    alias $internal
}

output "Dell Inc. DELL P3225QE *" {
    scale 1.25
    alias $dell_p3225qe
}

profile laptop {
    output $internal enable position 0,0
}

profile office_1 {
    output $dell_p3225qe enable position 0,0
    output $internal disable
}
```

> It maybe well that the panel module should be restarted (from Session Settings or by cli/script which could be done in kanshi afaik too).
> 
> ```
> #!/bin/bash
> qdbus6 org.lxqt.session /LXQtSession org.lxqt.session.stopModule lxqt-"panel".desktop;
> sleep 1;
> qdbus6 org.lxqt.session /LXQtSession org.lxqt.session.startModule lxqt-"panel".desktop;
> ```

Thanks for the suggestion.

My current workaround is to open the panel configuration, and change the position from `bottom` to `top` and then from `top` back to `bottom` ;)

**Comment by liweitianux** [comment]
> It's kind of necroposting here, fast forward 10 years to Wayland ;)

I'm sorry for this misbehavior and apologize for the disturbance.

I've created a new issue at: https://github.com/lxqt/lxqt-panel/issues/2432

Thank you all.

**Comment by stefonarch** [comment]
No problem, let's continue in the new issue.
