### ISSUE TITLE
Cannot bind shortcut to print key

### ISSUE THREAD

**Issue by RalfJung** [lxde/lxqt#991]
I would like tor ecover the usual functionality of the Print key, by binding it to the ScreenGrab application with a global shortcut. However, that is not possible: When I select to "Add..." a shortcut and click the button to select the key, and press the print key, nothing happens. It does not seem to be accepted as a shortcut.

For now, I used Ctrl+Print instead, but it'd really be nicer to use the rather universal "Print" shortcut.

**Comment by RalfJung** [comment]
Hm, actually it seems there is *something* running that does take a screenshot when I press Print and stores it in $HOME. I don't know what it is, and there is no response to indicate that anything happened, but it works, so that's good enough :)

**Comment by selairi** [comment]
I have found problems with Openbox shortcuts. Openbox already define a shortcut for Print key, and lxqt-globalkeysd can not use shortcuts defined by Openbox. 

If you use another window-manager, like Afterstep, you will be able to use Print key or other shortcuts.

You can edit ~/.config/openbox/rc.xml in order to change Openbox shortcuts.

lxqt-globalkeysd doesn't show Openbox shortcuts and Openbox is not using default config file of LXQt.

**Comment by RalfJung** [comment]
Oh, there are Openbox shortcuts? I didn't even know^^ obconf-qt does not even mention them. I'll look into that; I wanted to set up some WM-related shortcuts anyway.

**Comment by Vladimir-csp** [comment]
There is a good GUI for that called obkey.

**Comment by pmattern** [comment]
... the development of which is basically stalled. This applies to both the [initial project](https://code.google.com/archive/p/obkey/) as well as the fork provided e. g. by Arch Linux [AUR package obkey-git](https://aur.archlinux.org/packages/obkey-git/) the maintainer of which once stated that he basically just wants to port the tool to current software to keep it usable but doesn't intend any real active development.
That aside its UI may as usual be a matter of taste, personally I find its usage not even remotely intuitive.

**Comment by Vladimir-csp** [comment]
I just pointed out its existence, I did not suggest including it into LXQt :) 
AFAIK, it is the only such tool available. Maybe some bits of the code can be salvaged though.

**Comment by pmattern** [comment]
Sure, but no offense intended anyway. Just a supplementary note as it is indeed the only available tool right now as far as I know as well.

**Comment by selairi** [comment]
@pmattern  look [#1002](https://github.com/lxde/lxqt/issues/1002). lxqt-globalkeysd could be used perfectly.

**Comment by pmattern** [comment]
@selairi 
Basically for sure. But IMO the topics addressed in #979 as well as issue #506 do represent some obstacle for now, though.

**Comment by selairi** [comment]
> Basically for sure. But IMO the topics addressed in #979 as well as issue #506 do represent some obstacle for now, though.

Yes, they does. But [ #979](https://github.com/lxde/lxqt/issues/979) is almost solved by [#1002](https://github.com/lxde/lxqt/issues/1002).
