### ISSUE TITLE
lxqt-runner: Browse histroy with up and down keys

### ISSUE THREAD

**Issue by RalfJung** [lxde/lxqt#999]
It would be nice if pressing the up/down keys in the lxqt-runner would browse through the history, similar to a shell and the Plasma KRunner.

**Comment by Vladimir-csp** [comment]
+1

**Comment by paulolieuthier** [comment]
I just submitted a PR to fix showing history with the down key.

**Comment by Vladimir-csp** [comment]
Do you mean showing history with **up** key, I hope?

**Comment by paulolieuthier** [comment]
Down, really. It was buggy for me.

**Comment by Vladimir-csp** [comment]
The history is usually up.

**Comment by stefonarch** [comment]
I notice that moving trough history and just closing runner without starting nothing it reopens with history  open (same goes for typing some characters without starting the application I see).

Clean all on close would be better IMHO.

History limit is last 15 item, right?

**Comment by paulolieuthier** [comment]
> History limit is last 15 item, right?

https://github.com/lxde/lxqt-runner/blob/master/providers.cpp#L54

**Comment by paulolieuthier** [comment]
Done.

**Comment by palinek** [comment]
> Clean all on close would be better IMHO.

Actualy, the "not clearing feature" is something I rahter like

**Comment by paulolieuthier** [comment]
OK, I merged the commit that actually concerns this issue.
